define(
//begin v1.x content
{
	"KES_symbol": "Ksh",
	"USD_displayName": "Iropiyianí ɔ́ɔ̄ lamarekani",
	"TZS_displayName": "Iropiyianí e Tanzania",
	"ZMW_displayName": "Iropiyianí e Sambia",
	"MAD_displayName": "Iropiyianí e Moroko",
	"NGN_displayName": "Iropiyianí e Nijeria",
	"ZWD_displayName": "Iropiyianí e Simbabwe",
	"SDG_displayName": "Iropiyianí e Sudani",
	"MWK_displayName": "Iropiyianí e Malawi",
	"KMF_displayName": "Iropiyianí e Komoro",
	"SCR_displayName": "Iropiyianí e Shelisheli",
	"EGP_displayName": "Iropiyianí e Misri",
	"CVE_displayName": "Iropiyianí e Kepuvede",
	"LYD_displayName": "Iropiyianí e Libya",
	"CAD_displayName": "Iropiyianí e Kanada",
	"INR_displayName": "Iropiyianí e India",
	"JPY_displayName": "Iropiyianí e Japani",
	"LRD_displayName": "Iropiyianí e Liberia",
	"ZAR_displayName": "Iropiyianí e Afrika Kusini",
	"AOA_displayName": "Iropiyianí e Angola",
	"TND_displayName": "Iropiyianí e Tunisia",
	"GHC_displayName": "Iropiyianí e Ghana",
	"BWP_displayName": "Iropiyianí e Botswana",
	"DZD_displayName": "Iropiyianí e Algeria",
	"ZMK_displayName": "Iropiyianí e Sambia (1968–2012)",
	"NAD_displayName": "Iropiyianí e Namibia",
	"AED_displayName": "Iropiyianí ɔ́ɔ̄ lmarabu",
	"ETB_displayName": "Iropiyianí e Uhabeshi",
	"MZM_displayName": "Iropiyianí e Msumbiji",
	"BIF_displayName": "Iropiyianí e Burundi",
	"RWF_displayName": "Iropiyianí e Rwanda",
	"STD_displayName": "Iropiyianí e Saotome",
	"SZL_displayName": "Iropiyianí e lilangeni",
	"EUR_displayName": "Iropiyianí e yuro",
	"ERN_displayName": "Iropiyianí e Eritrea",
	"SAR_displayName": "Iropiyianí e Saudi",
	"DJF_displayName": "Iropiyianí e Jibuti",
	"CDF_displayName": "Iropiyianí e Kongo",
	"GBP_displayName": "Iropiyianí e Nkɨ́resa",
	"CHF_displayName": "Iropiyianí e Uswisi",
	"MUR_displayName": "Iropiyianí e Morisi",
	"SOS_displayName": "Iropiyianí e Somalia",
	"BHD_displayName": "Iropiyianí e Bahareini",
	"XOF_displayName": "Iropiyianí e CFA BCEAO",
	"GNS_displayName": "Iropiyianí e Gine",
	"SLL_displayName": "Iropiyianí e leoni",
	"UGX_displayName": "Iropiyianí e Uganda",
	"MGA_displayName": "Iropiyianí e Bukini",
	"AUD_displayName": "Iropiyianí e Austria",
	"KES_displayName": "Iropiyianí e Kenya",
	"SHP_displayName": "Iropiyianí e Santahelena",
	"XAF_displayName": "Iropiyianí e CFA BEAC",
	"LSL_displayName": "Iropiyianí e Lesoto",
	"MRO_displayName": "Iropiyianí e Moritania",
	"CNY_displayName": "Iropiyianí e China",
	"GMD_displayName": "Iropiyianí e Gambia"
}
//end v1.x content
);