define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Ɛnkakɛnyá/Ɛndámâ",
	"field-minute": "Oldákikaè",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Ŋolé",
	"field-weekday": "Ɛnkɔ́lɔŋ ewíkî",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Ɛnkátá",
	"field-hour": "Ɛ́sáâ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Táatá",
	"field-day-relative+1": "Tááisérè",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Ɛ́sáâ o inkuapí",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Ɔlárì",
	"field-week": "Ewíkî",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Ɔlápà",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "Sekunde",
	"field-day": "Ɛnkɔlɔ́ŋ",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);