define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateTimeFormat-full": "{1}, {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "dd.MM.y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"dateTimeFormat-long": "{1}, {0}",
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, dd.MM.y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-H": "H",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.y G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);