define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM.y",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-yQ": "QQQ y 'г'.",
	"dayPeriods-format-wide-pm": "после полудня",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateTimeFormat-full": "{1}, {0}",
	"dateFormatItem-MMdd": "dd.MM",
	"days-standAlone-wide": [
		"Воскресенье",
		"Понедельник",
		"Вторник",
		"Среда",
		"Четверг",
		"Пятница",
		"Суббота"
	],
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"dayPeriods-format-wide-am": "до полудня",
	"dateTimeFormat-medium": "{1}, {0}",
	"timeFormat-full": "H:mm:ss zzzz",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"Мухаррам",
		"Сафар",
		"Раби-уль-авваль",
		"Раби-уль-ахир",
		"Джумад-уль-авваль",
		"Джумад-уль-ахир",
		"Раджаб",
		"Шаабан",
		"Рамадан",
		"Шавваль",
		"Зуль-Каада",
		"Зуль-Хиджжа"
	],
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yyyyLLLL": "LLLL y G",
	"days-standAlone-narrow": [
		"В",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"dateFormatItem-yyyyMM": "MM.yyyy G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-yyMM": "MM.yy G",
	"dateFormat-medium": "dd.MM.yyyy G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dayPeriods-format-narrow-pm": "пп",
	"dateFormatItem-yyMMM": "LLL yy G",
	"dateFormatItem-yMd": "dd.MM.y",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"dayPeriods-format-narrow-am": "дп",
	"dateTimeFormat-long": "{1}, {0}",
	"months-standAlone-wide": [
		"Мухаррам",
		"Сафар",
		"Раби-уль-авваль",
		"Раби-уль-ахир",
		"Джумад-уль-авваль",
		"Джумад-уль-ахир",
		"Раджаб",
		"Шаабан",
		"Рамадан",
		"Шавваль",
		"Зуль-Каада",
		"Зуль-Хиджжа"
	],
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, dd.MM.y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyMMMEd": "E, d MMM yy G",
	"dateFormatItem-yyQ": "Q yy G",
	"months-format-abbr": [
		"Мухаррам",
		"Сафар",
		"Раби-уль-авваль",
		"Раби-уль-ахир",
		"Джумад-уль-авваль",
		"Джумад-уль-ахир",
		"Раджаб",
		"Шаабан",
		"Рамадан",
		"Шавваль",
		"Зуль-Каада",
		"Зуль-Хиджжа"
	],
	"dateFormatItem-E": "ccc",
	"timeFormat-long": "H:mm:ss z",
	"dateFormatItem-H": "H",
	"timeFormat-short": "H:mm",
	"quarters-format-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"days-format-abbr": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"dateFormatItem-M": "L",
	"days-format-narrow": [
		"В",
		"Пн",
		"Вт",
		"С",
		"Ч",
		"П",
		"С"
	],
	"dateFormatItem-yMMMd": "d MMM y 'г'.",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"days-standAlone-abbr": [
		"Вс",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"dayPeriods-format-abbr-pm": "после полудня",
	"dateFormat-short": "dd.MM.yy G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yMEd": "E, dd.MM.y",
	"months-format-wide": [
		"Мухаррам",
		"Сафар",
		"Раби-уль-авваль",
		"Раби-уль-ахир",
		"Джумад-уль-авваль",
		"Джумад-уль-ахир",
		"Раджаб",
		"Шаабан",
		"Рамадан",
		"Шавваль",
		"Зуль-Каада",
		"Зуль-Хиджжа"
	],
	"dayPeriods-format-abbr-am": "до полудня",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"days-format-wide": [
		"воскресенье",
		"понедельник",
		"вторник",
		"среда",
		"четверг",
		"пятница",
		"суббота"
	]
}
//end v1.x content
);