define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dayPeriods-format-wide-pm": "после полудня",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateTimeFormat-full": "{1}, {0}",
	"days-standAlone-wide": [
		"Воскресенье",
		"Понедельник",
		"Вторник",
		"Среда",
		"Четверг",
		"Пятница",
		"Суббота"
	],
	"months-standAlone-narrow": [
		"Я",
		"Ф",
		"М",
		"А",
		"М",
		"И",
		"И",
		"А",
		"С",
		"О",
		"Н",
		"Д"
	],
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Gy": "y G",
	"dayPeriods-format-wide-am": "до полудня",
	"dateTimeFormat-medium": "{1}, {0}",
	"quarters-standAlone-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"dateFormatItem-y": "y G",
	"timeFormat-full": "H:mm:ss zzzz",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"Фарвардин",
		"Ордибехешт",
		"Хордад",
		"Тир",
		"Мордад",
		"Шахривер",
		"Мехр",
		"Абан",
		"Азер",
		"Дей",
		"Бахман",
		"Эсфанд"
	],
	"dateFormatItem-Ed": "E, d",
	"days-standAlone-narrow": [
		"В",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "dd.MM.y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dayPeriods-format-narrow-pm": "пп",
	"quarters-standAlone-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"dayPeriods-format-narrow-am": "дп",
	"dateTimeFormat-long": "{1}, {0}",
	"months-standAlone-wide": [
		"Фарвардин",
		"Ордибехешт",
		"Хордад",
		"Тир",
		"Мордад",
		"Шахривер",
		"Мехр",
		"Абан",
		"Азер",
		"Дей",
		"Бахман",
		"Эсфанд"
	],
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, dd.MM.y G",
	"dateFormatItem-MMMd": "d MMM",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"Фарвардин",
		"Ордибехешт",
		"Хордад",
		"Тир",
		"Мордад",
		"Шахривер",
		"Мехр",
		"Абан",
		"Азер",
		"Дей",
		"Бахман",
		"Эсфанд"
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H",
	"quarters-format-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"days-format-abbr": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-format-narrow": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, dd.MM",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"days-standAlone-short": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-standAlone-abbr": [
		"Вс",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"dayPeriods-format-abbr-pm": "после полудня",
	"dateFormat-short": "dd.MM.y G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormatItem-Md": "dd.MM",
	"months-format-wide": [
		"Фарвардин",
		"Ордибехешт",
		"Хордад",
		"Тир",
		"Мордад",
		"Шахривер",
		"Мехр",
		"Абан",
		"Азер",
		"Дей",
		"Бахман",
		"Эсфанд"
	],
	"dayPeriods-format-abbr-am": "до полудня",
	"days-format-short": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"dateFormatItem-yyyyMMM": "LLL y G",
	"quarters-format-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"days-format-wide": [
		"воскресенье",
		"понедельник",
		"вторник",
		"среда",
		"четверг",
		"пятница",
		"суббота"
	]
}
//end v1.x content
);