define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateFormatItem-MMdd": "dd.MM",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyQQQ": "QQQ yy G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yyyyLLLL": "LLLL y G",
	"dateFormatItem-yyyyMM": "MM.yyyy G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-yyMM": "MM.yy G",
	"dateFormat-medium": "dd.MM.yyyy G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyMMM": "LLL yy G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, dd.MM.y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyMMMEd": "E, d MMM yy G",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-H": "H",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateFormat-short": "dd.MM.yy G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d"
}
//end v1.x content
);