define(
//begin v1.x content
{
	"field-tue-relative+-1": "last Tuesday",
	"field-year": "↑↑↑",
	"dateFormatItem-Hm": "↑↑↑",
	"field-wed-relative+0": "this Wednesday",
	"field-wed-relative+1": "next Wednesday",
	"dateFormatItem-ms": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "last mo",
	"field-tue-narrow-relative+0": "this Tu",
	"field-tue-narrow-relative+1": "next Tu",
	"field-day-short-relative+-1": "↑↑↑",
	"field-thu-short-relative+0": "this Thu",
	"dateTimeFormat-short": "↑↑↑",
	"field-day-relative+0": "today",
	"field-thu-short-relative+1": "next Thu",
	"field-day-relative+1": "tomorrow",
	"field-week-narrow-relative+0": "this wk",
	"field-week-narrow-relative+1": "next wk",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-wed-narrow-relative+-1": "last W",
	"field-year-narrow": "yr",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "this yr",
	"field-tue-relative+0": "this Tuesday",
	"field-year-narrow-relative+1": "next yr",
	"field-tue-relative+1": "next Tuesday",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec",
	"dateFormatItem-MMMd": "↑↑↑",
	"field-weekdayOfMonth-narrow": "wkday of mo",
	"field-week-relative+0": "this week",
	"field-month-relative+0": "this month",
	"field-week-relative+1": "next week",
	"field-month-relative+1": "next month",
	"field-sun-narrow-relative+0": "this Su",
	"field-mon-short-relative+0": "this Mon",
	"field-sun-narrow-relative+1": "next Su",
	"field-mon-short-relative+1": "next Mon",
	"field-second-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQ": "↑↑↑",
	"field-weekOfMonth": "↑↑↑",
	"field-month-short": "mo",
	"dateFormatItem-GyMMMEd": "↑↑↑",
	"dateFormatItem-yyyyMd": "↑↑↑",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "day of yr",
	"field-year-relative+-1": "last year",
	"field-sat-short-relative+-1": "last Sat",
	"field-hour-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMEd": "↑↑↑",
	"field-second-short-relative+0": "↑↑↑",
	"field-wed-relative+-1": "last Wednesday",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "last Sa",
	"field-second": "↑↑↑",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "↑↑↑",
	"dateFormatItem-GyMMMd": "↑↑↑",
	"field-hour-short-relative+0": "↑↑↑",
	"field-quarter": "↑↑↑",
	"field-week-short": "wk",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"field-tue-short-relative+0": "this Tue",
	"field-tue-short-relative+1": "next Tue",
	"field-month-short-relative+-1": "last mo",
	"field-mon-relative+-1": "last Monday",
	"dateFormatItem-GyMMM": "↑↑↑",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dateFormatItem-MMM": "↑↑↑",
	"field-minute-short": "min",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "this Sat",
	"field-sat-short-relative+1": "next Sat",
	"dateFormat-medium": "↑↑↑",
	"dateFormatItem-yyyyMMMM": "↑↑↑",
	"dateFormatItem-yyyyM": "↑↑↑",
	"field-second-narrow": "sec",
	"field-mon-relative+0": "this Monday",
	"field-mon-relative+1": "next Monday",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "yr",
	"field-quarter-relative+-1": "last quarter",
	"dateFormatItem-yyyyMMMd": "↑↑↑",
	"field-dayperiod-narrow": "am/pm",
	"field-week-narrow-relative+-1": "last wk",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "last Saturday",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "↑↑↑",
	"field-hour": "↑↑↑",
	"field-minute-narrow-relative+0": "↑↑↑",
	"dateFormat-full": "↑↑↑",
	"field-month-relative+-1": "last month",
	"dateFormatItem-Hms": "↑↑↑",
	"field-quarter-short": "qtr",
	"field-sat-narrow-relative+0": "this Sa",
	"field-fri-relative+0": "this Friday",
	"field-sat-narrow-relative+1": "next Sa",
	"field-fri-relative+1": "next Friday",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "this mo",
	"field-month-narrow-relative+1": "next mo",
	"field-sun-short-relative+0": "this Sun",
	"field-sun-short-relative+1": "next Sun",
	"field-week-relative+-1": "last week",
	"dateFormatItem-Ehm": "↑↑↑",
	"field-minute-short-relative+0": "↑↑↑",
	"field-quarter-relative+0": "this quarter",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "next quarter",
	"field-wed-short-relative+-1": "last Wed",
	"dateFormat-short": "↑↑↑",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "last yr",
	"field-thu-short-relative+-1": "last Thu",
	"dateFormatItem-yyyyMMMEd": "↑↑↑",
	"field-mon-narrow-relative+-1": "last M",
	"dateFormatItem-MMMMd": "↑↑↑",
	"field-thu-narrow-relative+-1": "last Th",
	"dateFormatItem-E": "↑↑↑",
	"field-tue-narrow-relative+-1": "last Tu",
	"dateFormatItem-H": "↑↑↑",
	"field-weekOfMonth-short": "wk of mo",
	"dateFormatItem-yyyy": "↑↑↑",
	"dateFormatItem-M": "↑↑↑",
	"field-wed-short-relative+0": "this Wed",
	"field-wed-short-relative+1": "next Wed",
	"field-sun-relative+-1": "last Sunday",
	"dateTimeFormat-full": "↑↑↑",
	"field-second-narrow-relative+0": "↑↑↑",
	"dateFormatItem-hm": "↑↑↑",
	"dateFormatItem-d": "↑↑↑",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "this Saturday",
	"dateFormatItem-h": "↑↑↑",
	"field-sat-relative+1": "next Saturday",
	"field-week-short-relative+0": "this wk",
	"field-week-short-relative+1": "next wk",
	"field-dayOfYear-narrow": "day of yr",
	"field-month-short-relative+0": "this mo",
	"field-month-short-relative+1": "next mo",
	"field-weekdayOfMonth-short": "wkday of mo",
	"dateFormatItem-MEd": "E dd/MM",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "↑↑↑",
	"field-thu-narrow-relative+0": "this Th",
	"field-sun-narrow-relative+-1": "last Su",
	"field-mon-short-relative+-1": "last Mon",
	"field-thu-narrow-relative+1": "next Th",
	"field-thu-relative+0": "this Thursday",
	"field-thu-relative+1": "next Thursday",
	"dateFormatItem-hms": "↑↑↑",
	"field-fri-short-relative+-1": "last Fri",
	"field-thu-relative+-1": "last Thursday",
	"field-week": "↑↑↑",
	"dateFormatItem-Ed": "↑↑↑",
	"field-wed-narrow-relative+0": "this W",
	"field-wed-narrow-relative+1": "next W",
	"field-year-short-relative+0": "this yr",
	"dateFormatItem-yyyyMMM": "↑↑↑",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "next yr",
	"field-fri-short-relative+0": "this Fri",
	"field-fri-short-relative+1": "next Fri",
	"field-week-short-relative+-1": "last wk",
	"field-hour-narrow-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQQ": "↑↑↑",
	"field-hour-short": "hr",
	"field-zone-short": "↑↑↑",
	"field-month-narrow": "mo",
	"field-hour-narrow": "hr",
	"field-fri-narrow-relative+-1": "last F",
	"field-year-relative+0": "this year",
	"field-year-relative+1": "next year",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "last Friday",
	"dateFormatItem-Bhms": "↑↑↑",
	"field-tue-short-relative+-1": "last Tue",
	"field-minute-narrow": "min",
	"field-mon-narrow-relative+0": "this M",
	"dateFormatItem-EHm": "↑↑↑",
	"field-mon-narrow-relative+1": "next M",
	"field-year-short-relative+-1": "last yr",
	"field-zone": "↑↑↑",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-weekOfMonth-narrow": "wk of mo",
	"dateFormatItem-EHms": "↑↑↑",
	"field-weekday-narrow": "day of wk",
	"field-quarter-narrow": "qtr",
	"field-sun-short-relative+-1": "last Sun",
	"field-day-relative+-1": "yesterday",
	"field-weekday-short": "day of wk",
	"dateFormatItem-Bhm": "↑↑↑",
	"field-sun-relative+0": "this Sunday",
	"field-sun-relative+1": "next Sunday",
	"dateFormatItem-Gy": "↑↑↑",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "wk",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "this F",
	"field-fri-narrow-relative+1": "next F"
}
//end v1.x content
);