define(
//begin v1.x content
{
	"dayPeriods-standAlone-abbr-noon": "noon",
	"field-tue-relative+-1": "last Tuesday",
	"field-year": "↑↑↑",
	"dateFormatItem-yw": "↑↑↑",
	"dayPeriods-format-abbr-afternoon1": "↑↑↑",
	"dateFormatItem-Hm": "HH:mm",
	"field-wed-relative+0": "this Wednesday",
	"field-wed-relative+1": "next Wednesday",
	"dateFormatItem-ms": "mm:ss",
	"timeFormat-short": "HH:mm",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "last mo",
	"field-tue-narrow-relative+0": "this Tu",
	"field-tue-narrow-relative+1": "next Tu",
	"field-thu-short-relative+0": "this Thu",
	"field-day-short-relative+-1": "↑↑↑",
	"dateTimeFormat-short": "{1}, {0}",
	"field-thu-short-relative+1": "next Thu",
	"field-day-relative+0": "today",
	"field-day-relative+1": "tomorrow",
	"field-week-narrow-relative+0": "this wk",
	"field-week-narrow-relative+1": "next wk",
	"field-wed-narrow-relative+-1": "last W",
	"dateFormatItem-EBhms": "E h:mm:ss B",
	"field-year-narrow": "yr",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "this yr",
	"field-tue-relative+0": "this Tuesday",
	"field-year-narrow-relative+1": "next yr",
	"field-tue-relative+1": "next Tuesday",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec",
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-standAlone-abbr-morning1": "↑↑↑",
	"dateFormatItem-MMMd": "d MMM",
	"dayPeriods-format-narrow-morning1": "↑↑↑",
	"field-weekdayOfMonth-narrow": "wkday of mo",
	"dayPeriods-format-abbr-am": "am",
	"field-week-relative+0": "this week",
	"field-month-relative+0": "this month",
	"field-week-relative+1": "next week",
	"field-month-relative+1": "next month",
	"field-sun-narrow-relative+0": "this Su",
	"timeFormat-medium": "HH:mm:ss",
	"field-mon-short-relative+0": "this Mon",
	"field-sun-narrow-relative+1": "next Su",
	"field-mon-short-relative+1": "next Mon",
	"field-second-relative+0": "↑↑↑",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-standAlone-wide-noon": "↑↑↑",
	"eraNames": [
		"Before Christ",
		"Anno Domini"
	],
	"field-weekOfMonth": "↑↑↑",
	"dayPeriods-standAlone-abbr-pm": "pm",
	"field-month-short": "mo",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"field-day": "↑↑↑",
	"dayPeriods-standAlone-wide-night1": "↑↑↑",
	"field-dayOfYear-short": "day of yr",
	"field-year-relative+-1": "last year",
	"dayPeriods-format-wide-am": "am",
	"field-sat-short-relative+-1": "last Sat",
	"dayPeriods-format-narrow-afternoon1": "↑↑↑",
	"dayPeriods-format-wide-afternoon1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"field-second-short-relative+0": "↑↑↑",
	"field-wed-relative+-1": "last Wednesday",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-sat-narrow-relative+-1": "last Sa",
	"field-second": "↑↑↑",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"W",
		"T",
		"F",
		"S"
	],
	"dayPeriods-standAlone-narrow-noon": "noon",
	"dayPeriods-standAlone-wide-pm": "pm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormat-long": "d MMMM y",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-hour-short-relative+0": "↑↑↑",
	"dayPeriods-standAlone-abbr-midnight": "midnight",
	"field-quarter": "↑↑↑",
	"field-week-short": "wk",
	"dayPeriods-format-narrow-midnight": "↑↑↑",
	"field-day-narrow-relative+0": "↑↑↑",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"field-day-narrow-relative+1": "↑↑↑",
	"quarters-standAlone-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"W",
		"T",
		"F",
		"S"
	],
	"dayPeriods-format-wide-evening1": "↑↑↑",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-tue-short-relative+0": "this Tue",
	"field-tue-short-relative+1": "next Tue",
	"field-month-short-relative+-1": "last mo",
	"field-mon-relative+-1": "last Monday",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dayPeriods-standAlone-abbr-night1": "↑↑↑",
	"dayPeriods-standAlone-narrow-afternoon1": "↑↑↑",
	"dateFormatItem-MMM": "LLL",
	"field-minute-short": "min",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "this Sat",
	"field-sat-short-relative+1": "next Sat",
	"dayPeriods-format-narrow-pm": "p",
	"dateFormat-medium": "d MMM y",
	"eraAbbr": [
		"BC",
		"AD"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dayPeriods-format-abbr-pm": "pm",
	"field-second-narrow": "sec",
	"field-mon-relative+0": "this Monday",
	"dayPeriods-standAlone-narrow-night1": "↑↑↑",
	"field-mon-relative+1": "next Monday",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "yr",
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-format-wide-morning1": "↑↑↑",
	"field-quarter-relative+-1": "last quarter",
	"field-dayperiod-narrow": "am/pm",
	"dayPeriods-standAlone-narrow-am": "↑↑↑",
	"field-week-narrow-relative+-1": "last wk",
	"days-format-short": [
		"Su",
		"Mo",
		"Tu",
		"We",
		"Th",
		"Fr",
		"Sa"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dayPeriods-format-wide-pm": "pm",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "last Saturday",
	"dateTimeFormat-long": "{1} 'at' {0}",
	"dateFormatItem-Md": "dd/MM",
	"field-minute-narrow-relative+0": "↑↑↑",
	"field-hour": "↑↑↑",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"months-format-wide": [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December"
	],
	"dayPeriods-format-wide-night1": "↑↑↑",
	"dateFormat-full": "EEEE, d MMMM y",
	"field-month-relative+-1": "last month",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-quarter-short": "qtr",
	"field-sat-narrow-relative+0": "this Sa",
	"dateFormatItem-Hmv": "↑↑↑",
	"field-fri-relative+0": "this Friday",
	"field-sat-narrow-relative+1": "next Sa",
	"field-fri-relative+1": "next Friday",
	"dateFormatItem-EBhm": "E h:mm B",
	"field-month-narrow-relative+0": "this mo",
	"field-month-narrow-relative+1": "next mo",
	"dayPeriods-format-narrow-noon": "n",
	"field-sun-short-relative+0": "this Sun",
	"field-sun-short-relative+1": "next Sun",
	"field-week-relative+-1": "last week",
	"dateFormatItem-Ehm": "E h:mm a",
	"field-minute-short-relative+0": "↑↑↑",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sept",
		"Oct",
		"Nov",
		"Dec"
	],
	"dayPeriods-format-wide-midnight": "↑↑↑",
	"timeFormat-long": "HH:mm:ss z",
	"field-quarter-relative+0": "this quarter",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "next quarter",
	"field-wed-short-relative+-1": "last Wed",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormat-short": "dd/MM/y",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "last yr",
	"dayPeriods-format-abbr-night1": "↑↑↑",
	"dateFormatItem-MMMMW": "↑↑↑",
	"field-thu-short-relative+-1": "last Thu",
	"days-standAlone-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	],
	"field-mon-narrow-relative+-1": "last M",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-thu-narrow-relative+-1": "last Th",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-H": "HH",
	"field-weekOfMonth-short": "wk of mo",
	"field-tue-narrow-relative+-1": "last Tu",
	"dayPeriods-format-abbr-evening1": "↑↑↑",
	"dayPeriods-standAlone-narrow-pm": "pm",
	"dateFormatItem-M": "L",
	"months-standAlone-wide": [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December"
	],
	"field-wed-short-relative+0": "this Wed",
	"field-wed-short-relative+1": "next Wed",
	"dateFormatItem-Hmsv": "↑↑↑",
	"field-sun-relative+-1": "last Sunday",
	"days-standAlone-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateTimeFormat-full": "{1} 'at' {0}",
	"field-second-narrow-relative+0": "↑↑↑",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-d": "d",
	"field-weekday": "↑↑↑",
	"dayPeriods-standAlone-wide-evening1": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "this Saturday",
	"dateFormatItem-h": "h a",
	"field-sat-relative+1": "next Saturday",
	"field-week-short-relative+0": "this wk",
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sept",
		"Oct",
		"Nov",
		"Dec"
	],
	"dateFormatItem-hmsv": "↑↑↑",
	"field-week-short-relative+1": "next wk",
	"dayPeriods-format-abbr-morning1": "↑↑↑",
	"dayPeriods-standAlone-narrow-evening1": "↑↑↑",
	"field-dayOfYear-narrow": "day of yr",
	"field-month-short-relative+0": "this mo",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-month-short-relative+1": "next mo",
	"field-weekdayOfMonth-short": "wkday of mo",
	"dateFormatItem-MEd": "↑↑↑",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "y",
	"field-thu-narrow-relative+0": "this Th",
	"field-sun-narrow-relative+-1": "last Su",
	"field-mon-short-relative+-1": "last Mon",
	"field-thu-narrow-relative+1": "next Th",
	"field-thu-relative+0": "this Thursday",
	"dayPeriods-standAlone-abbr-afternoon1": "↑↑↑",
	"field-thu-relative+1": "next Thursday",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-fri-short-relative+-1": "last Fri",
	"dateFormatItem-hmv": "↑↑↑",
	"dayPeriods-format-abbr-noon": "noon",
	"field-thu-relative+-1": "last Thursday",
	"dateFormatItem-yMd": "dd/MM/y",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-week": "↑↑↑",
	"quarters-format-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"dateFormatItem-Ed": "E d",
	"field-wed-narrow-relative+0": "this W",
	"field-wed-narrow-relative+1": "next W",
	"dayPeriods-standAlone-wide-morning1": "↑↑↑",
	"field-year-short-relative+0": "this yr",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "next yr",
	"field-fri-short-relative+0": "this Fri",
	"field-fri-short-relative+1": "next Fri",
	"days-standAlone-short": [
		"Su",
		"Mo",
		"Tu",
		"We",
		"Th",
		"Fr",
		"Sa"
	],
	"field-week-short-relative+-1": "last wk",
	"dayPeriods-standAlone-narrow-morning1": "↑↑↑",
	"field-hour-narrow-relative+0": "↑↑↑",
	"dayPeriods-format-abbr-midnight": "↑↑↑",
	"field-hour-short": "hr",
	"field-zone-short": "↑↑↑",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"field-month-narrow": "mo",
	"field-hour-narrow": "hr",
	"field-fri-narrow-relative+-1": "last F",
	"field-year-relative+0": "this year",
	"field-year-relative+1": "next year",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "last Friday",
	"eraNarrow": [
		"BC",
		"AD"
	],
	"dateFormatItem-Bhms": "↑↑↑",
	"dayPeriods-format-wide-noon": "noon",
	"field-tue-short-relative+-1": "last Tue",
	"field-minute-narrow": "min",
	"dayPeriods-standAlone-wide-afternoon1": "↑↑↑",
	"dateFormatItem-yQQQ": "QQQ y",
	"days-format-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	],
	"field-mon-narrow-relative+0": "this M",
	"dateFormatItem-EHm": "E HH:mm",
	"field-mon-narrow-relative+1": "next M",
	"dayPeriods-standAlone-wide-midnight": "↑↑↑",
	"field-year-short-relative+-1": "last yr",
	"dateFormatItem-yM": "MM/y",
	"field-zone": "↑↑↑",
	"dateFormatItem-yMMMM": "↑↑↑",
	"dateFormatItem-MMMEd": "↑↑↑",
	"field-weekOfMonth-narrow": "wk of mo",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"field-weekday-narrow": "day of wk",
	"dayPeriods-standAlone-narrow-midnight": "midnight",
	"field-quarter-narrow": "qtr",
	"dayPeriods-standAlone-abbr-am": "am",
	"field-day-relative+-1": "yesterday",
	"field-sun-short-relative+-1": "last Sun",
	"dayPeriods-format-narrow-night1": "↑↑↑",
	"field-weekday-short": "day of wk",
	"dateFormatItem-Bhm": "↑↑↑",
	"days-format-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateFormatItem-MMdd": "dd/MM",
	"field-sun-relative+0": "this Sunday",
	"field-sun-relative+1": "next Sunday",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-Gy": "y G",
	"field-era": "↑↑↑",
	"field-week-narrow": "wk",
	"field-day-short": "↑↑↑",
	"dayPeriods-standAlone-abbr-evening1": "↑↑↑",
	"field-fri-narrow-relative+0": "this F",
	"dayPeriods-format-narrow-evening1": "↑↑↑",
	"field-fri-narrow-relative+1": "next F",
	"dayPeriods-standAlone-wide-am": "am"
}
//end v1.x content
);