({
	"dateTimeAvailableFormats": [
		"E, d/M", 
		"E d MMM", 
		"d MMMM", 
		"dd/MM", 
		"d/M", 
		"EEE, d/M/yyyy", 
		"MMM yy", 
		"MM/yyyy", 
		"MMMM yyyy", 
		"M/d", 
		"d", 
		"h:mm a", 
		"mm:ss", 
		"yyyy", 
		"M/yyyy", 
		"EEE, M/d/yyyy", 
		"MMM yyyy", 
		"EEE, MMM d, yyyy", 
		"MMMM yyyy", 
		"Q yyyy", 
		"QQQ yyyy"
	], 
	"timeFormat-full": "HH:mm:ss v", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormat-medium": "d MMM yyyy", 
	"dateFormat-full": "EEEE, d MMMM yyyy", 
	"timeFormat-long": "HH:mm:ss z", 
	"timeFormat-short": "HH:mm", 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormat-long": "d MMMM yyyy"
})