define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-minute": "Minit",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Pan",
	"field-weekday": "Ni̱n jokä",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Gua̱a̱th Ruëc",
	"field-hour": "Thaak",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Walɛ",
	"field-day-relative+1": "Ruun",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Ruɔ̱n",
	"field-week": "Jiɔk",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Pay",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Thɛkɛni",
	"field-day": "Cäŋ",
	"dateFormatItem-MEd": "E، d-M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E، d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E، d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);