define(
//begin v1.x content
{
	"KES_symbol": "Ksh",
	"USD_displayName": "Dolaitab ya Amareka",
	"TZS_displayName": "silingitab Tanzania",
	"ZMW_displayName": "Kwachaitab Zambia",
	"MAD_displayName": "Rabisiekab Moroccan",
	"NGN_displayName": "Rabisiekab Nigeria",
	"ZWD_displayName": "Dolaitab ya Zimbabwe",
	"SDG_displayName": "Pouditab Sudan",
	"MWK_displayName": "Rabisiekaby Malawi",
	"KMF_displayName": "Rabisiekab Komoro",
	"SCR_displayName": "Rabisiekab Shelisheli",
	"EGP_displayName": "Pauditab Misri",
	"CVE_displayName": "Rabisiekab Kepuvede",
	"LYD_displayName": "Rabisiekab Libya",
	"CAD_displayName": "Dolaitab Kanada",
	"INR_displayName": "Rabisiekab India",
	"JPY_displayName": "Rabisiekab Japan",
	"LRD_displayName": "Dolaitab Liberia",
	"ZAR_displayName": "Randitab Afrika nebo murot tai",
	"AOA_displayName": "Rabisiekab Angolan",
	"TND_displayName": "RabisiekabTunisia",
	"GHC_displayName": "Rabisiekab Ghana",
	"BWP_displayName": "Rabisiekab Botswana",
	"DZD_displayName": "Rabisiekab Algerian",
	"ZMK_displayName": "Kwachaitab Zambia (1968–2012)",
	"NAD_displayName": "Dolaitab Namibia",
	"AED_displayName": "Rabisiekab Kibagegeitab arabuk",
	"ETB_displayName": "Rabisiekab Ethiopia",
	"MZM_displayName": "Rabisiekab Msumbiji",
	"BIF_displayName": "Rabisiekab Burundi",
	"RWF_displayName": "Rabisiekab Rwanda",
	"STD_displayName": "Rabisiekab Sao Tome ak Principe",
	"SZL_displayName": "Lilangenit",
	"EUR_displayName": "Yuroit",
	"ERN_displayName": "Rabisiekab Eritrea",
	"SAR_displayName": "Rabisiekab Saudia",
	"DJF_displayName": "Rabisiekab Jibuti",
	"CDF_displayName": "Rabisiekab Congo",
	"GBP_displayName": "pounditab Uingereza",
	"CHF_displayName": "Rabisiekab Swiss",
	"MUR_displayName": "Rabisiekab Mauritius",
	"SOS_displayName": "siligitab Somalia",
	"BHD_displayName": "Rabisiekab Bahrain",
	"XOF_displayName": "Rabisiekab CFA BCEAO",
	"GNS_displayName": "Rabisiekab Guinea",
	"SLL_displayName": "Leonit",
	"UGX_displayName": "Silingitab Uganda",
	"MGA_displayName": "Rabisiekab Malagasy",
	"AUD_displayName": "Dolaitab Australian",
	"KES_displayName": "Silingitab ya Kenya",
	"SHP_displayName": "Pouditab helena ne tilil",
	"XAF_displayName": "Rabisiekab CFA BEAC",
	"LSL_displayName": "Rabisiekab Lesoto",
	"MRO_displayName": "Rabisiekab Mauritania",
	"CNY_displayName": "Rabisiekab China",
	"GMD_displayName": "Rabisiekab Gambia"
}
//end v1.x content
);