define(
//begin v1.x content
{
	"field-sat-relative+0": "Sabtu ini",
	"field-sat-relative+1": "Sabtu depan",
	"field-dayperiod": "PG/PTG",
	"field-sun-relative+-1": "Ahad lalu",
	"field-mon-relative+-1": "Isnin lalu",
	"field-minute": "Minit",
	"field-day-relative+-1": "Semalam",
	"field-weekday": "Hari dalam Minggu",
	"field-day-relative+-2": "Hari sebelum semalam",
	"field-era": "Era",
	"field-hour": "Jam",
	"field-sun-relative+0": "Ahad ini",
	"field-sun-relative+1": "Ahad depan",
	"field-wed-relative+-1": "Rabu lalu",
	"field-day-relative+0": "Hari ini",
	"field-day-relative+1": "Esok",
	"eraAbbr": [
		"Before R.O.C.",
		"R.O.C."
	],
	"field-day-relative+2": "Hari selepas esok",
	"field-tue-relative+0": "Selasa ini",
	"field-zone": "Zon Waktu",
	"field-tue-relative+1": "Selasa depan",
	"field-week-relative+-1": "minggu lepas",
	"field-year-relative+0": "tahun ini",
	"field-year-relative+1": "tahun depan",
	"field-sat-relative+-1": "Sabtu lalu",
	"field-year-relative+-1": "tahun lepas",
	"field-year": "Tahun",
	"field-fri-relative+0": "Jumaat ini",
	"field-fri-relative+1": "Jumaat depan",
	"field-week": "Minggu",
	"field-week-relative+0": "minggu ini",
	"field-week-relative+1": "minggu depan",
	"field-month-relative+0": "bulan ini",
	"field-month": "Bulan",
	"field-month-relative+1": "bulan depan",
	"field-fri-relative+-1": "Jumaat lalu",
	"field-second": "Kedua",
	"field-tue-relative+-1": "Selasa lalu",
	"field-day": "Hari",
	"field-mon-relative+0": "Isnin ini",
	"field-mon-relative+1": "Isnin depan",
	"field-thu-relative+0": "Khamis ini",
	"field-second-relative+0": "sekarang",
	"field-thu-relative+1": "Khamis depan",
	"field-wed-relative+0": "Rabu ini",
	"field-wed-relative+1": "Rabu depan",
	"field-month-relative+-1": "bulan lalu",
	"field-thu-relative+-1": "Khamis lalu"
}
//end v1.x content
);