({
	"dateFormatItem-yM": "M/yyyy", 
	"field-dayperiod": "a.m./p.m.", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-minute": "minut", 
	"dateFormatItem-MMMEd": "E d MMM", 
	"eraNames": [
		"aC", 
		"dC"
	], 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "dia de la setmana", 
	"days-standAlone-wide": [
		"diumenge", 
		"dilluns", 
		"dimarts", 
		"dimecres", 
		"dijous", 
		"divendres", 
		"dissabte"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"g", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"a", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"field-era": "era", 
	"field-hour": "hora", 
	"quarters-standAlone-abbr": [
		"1T", 
		"2T", 
		"3T", 
		"4T"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "H:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"gen.", 
		"febr.", 
		"març", 
		"abr.", 
		"maig", 
		"juny", 
		"jul.", 
		"ag.", 
		"set.", 
		"oct.", 
		"nov.", 
		"des."
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"days-standAlone-narrow": [
		"g", 
		"l", 
		"t", 
		"c", 
		"j", 
		"v", 
		"s"
	], 
	"eraAbbr": [
		"aC", 
		"dC"
	], 
	"dateFormatItem-yyyyMM": "MM/yyyy", 
	"dateFormat-long": "d 'de' MMMM 'de' y", 
	"timeFormat-medium": "H:mm:ss", 
	"dateFormatItem-EEEd": "EEE d", 
	"field-zone": "zona", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "dd/MM/yyyy", 
	"quarters-standAlone-wide": [
		"1r trimestre", 
		"2n trimestre", 
		"3r trimestre", 
		"4t trimestre"
	], 
	"dateFormatItem-yMMMM": "LLLL 'del' y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "any", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"dateFormatItem-HHmmss": "HH:mm:ss", 
	"field-week": "setmana", 
	"months-standAlone-wide": [
		"gener", 
		"febrer", 
		"març", 
		"abril", 
		"maig", 
		"juny", 
		"juliol", 
		"agost", 
		"setembre", 
		"octubre", 
		"novembre", 
		"desembre"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "H:mm:ss z", 
	"months-format-abbr": [
		"gen.", 
		"febr.", 
		"març", 
		"abr.", 
		"maig", 
		"juny", 
		"jul.", 
		"ag.", 
		"set.", 
		"oct.", 
		"nov.", 
		"des."
	], 
	"timeFormat-short": "H:mm", 
	"field-month": "mes", 
	"dateFormatItem-MMMMd": "d 'de' MMMM", 
	"quarters-format-abbr": [
		"1T", 
		"2T", 
		"3T", 
		"4T"
	], 
	"days-format-abbr": [
		"dg.", 
		"dl.", 
		"dt.", 
		"dc.", 
		"dj.", 
		"dv.", 
		"ds."
	], 
	"pm": "p.m.", 
	"dateFormatItem-mmss": "mm:ss", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"g", 
		"l", 
		"t", 
		"c", 
		"j", 
		"v", 
		"s"
	], 
	"field-second": "segon", 
	"field-day": "dia", 
	"dateFormatItem-MEd": "E d/M", 
	"months-format-narrow": [
		"g", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"a", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"am": "a.m.", 
	"days-standAlone-abbr": [
		"dg", 
		"dl", 
		"dt", 
		"dc", 
		"dj", 
		"dv", 
		"ds"
	], 
	"dateFormat-short": "dd/MM/yy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d 'de' MMMM 'de' y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "E d/M/yyyy", 
	"months-format-wide": [
		"gener", 
		"febrer", 
		"març", 
		"abril", 
		"maig", 
		"juny", 
		"juliol", 
		"agost", 
		"setembre", 
		"octubre", 
		"novembre", 
		"desembre"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1r trimestre", 
		"2n trimestre", 
		"3r trimestre", 
		"4t trimestre"
	], 
	"days-format-wide": [
		"diumenge", 
		"dilluns", 
		"dimarts", 
		"dimecres", 
		"dijous", 
		"divendres", 
		"dissabte"
	], 
	"eraNarrow": [
		"aC", 
		"dC"
	]
})