define(
//begin v1.x content
{
	"field-sat-relative+0": "leygardagur henda viku",
	"field-sat-relative+1": "leygardagur næstu vika",
	"field-sun-relative+-1": "sunnudagu síðstu vika",
	"field-mon-relative+-1": "mánadagur síðstu vika",
	"field-day-relative+-1": "í gær",
	"field-day-relative+-2": "í fyrradag",
	"field-sun-relative+0": "sunnudagu henda viku",
	"field-sun-relative+1": "sunnudagu næstu vika",
	"field-wed-relative+-1": "mikudagur síðstu vika",
	"field-day-relative+0": "í dag",
	"field-day-relative+1": "á morgunn",
	"field-day-relative+2": "á yfirmorgunn",
	"dateFormat-long": "d. MMM y G",
	"field-tue-relative+0": "týsdagur henda viku",
	"field-tue-relative+1": "týsdagur næstu vika",
	"field-week-relative+-1": "síðstu vika",
	"dateFormat-medium": "dd-MM-y G",
	"field-year-relative+0": "hetta ár",
	"field-year-relative+1": "næstu ár",
	"field-sat-relative+-1": "leygardagur síðstu vika",
	"field-year-relative+-1": "síðstu ár",
	"field-fri-relative+0": "fríggjadagur henda viku",
	"field-fri-relative+1": "fríggjadagur næstu vika",
	"field-week-relative+0": "henda viku",
	"field-week-relative+1": "næstu vika",
	"field-month-relative+0": "henda mánuður",
	"field-month-relative+1": "næstu mánuður",
	"field-fri-relative+-1": "fríggjadagur síðstu vika",
	"field-tue-relative+-1": "týsdagur síðstu vika",
	"field-mon-relative+0": "mánadagur henda viku",
	"field-mon-relative+1": "mánadagur næstu vika",
	"field-thu-relative+0": "hósdagur henda viku",
	"dateFormat-short": "dd-MM-yy GGGGG",
	"field-thu-relative+1": "hósdagur næstu vika",
	"dateFormat-full": "EEEE dd MMMM y G",
	"field-wed-relative+0": "mikudagur henda viku",
	"field-wed-relative+1": "mikudagur næstu vika",
	"field-month-relative+-1": "síðstu mánuður",
	"field-thu-relative+-1": "hósdagur síðstu vika"
}
//end v1.x content
);