define(
//begin v1.x content
{
	"field-sat-relative+0": "Owáŋkayužažapi kiŋ lé",
	"field-sat-relative+1": "Owáŋkayužažapi kiŋháŋ",
	"field-sun-relative+-1": "Aŋpétuwakȟáŋ kʼuŋ héhaŋ",
	"field-mon-relative+-1": "Aŋpétutȟokahe kʼuŋ héhaŋ",
	"field-minute": "Owápȟe oȟʼáŋkȟo",
	"field-day-relative+-1": "Lé aŋpétu kiŋ",
	"field-weekday": "Okó-aŋpétu",
	"field-hour": "Owápȟe",
	"field-sun-relative+0": "Aŋpétuwakȟáŋ kiŋ lé",
	"field-sun-relative+1": "Aŋpétuwakȟáŋ kiŋháŋ",
	"field-wed-relative+-1": "Aŋpétuyamni kʼuŋ héhaŋ",
	"field-day-relative+0": "Lé aŋpétu kiŋ",
	"field-day-relative+1": "Híŋhaŋni kiŋháŋ",
	"field-tue-relative+0": "Aŋpétunuŋpa kiŋ lé",
	"field-tue-relative+1": "Aŋpétunuŋpa kiŋháŋ",
	"field-week-relative+-1": "Okó kʼuŋ héhaŋ",
	"field-year-relative+0": "Lé ómakȟa kiŋ",
	"field-year-relative+1": "Tȟokáta ómakȟa kiŋháŋ",
	"field-sat-relative+-1": "Owáŋkayužažapi kʼuŋ héhaŋ",
	"field-year-relative+-1": "Ómakȟa kʼuŋ héhaŋ",
	"field-year": "Ómakȟa",
	"field-fri-relative+0": "Apétuzaptaŋ kiŋ lé",
	"field-fri-relative+1": "Aŋpétuzaptaŋ kiŋháŋ",
	"field-week": "Okó",
	"field-week-relative+0": "Lé okó kiŋ",
	"field-week-relative+1": "Tȟokáta okó kiŋháŋ",
	"field-month-relative+0": "Lé wí kiŋ",
	"field-month": "Wí",
	"field-month-relative+1": "Wí kiŋháŋ",
	"field-fri-relative+-1": "Aŋpétuzaŋptaŋ kʼuŋ héhaŋ",
	"field-second": "Okpí",
	"field-tue-relative+-1": "Aŋpétunuŋpa kʼuŋ héhaŋ",
	"field-day": "Aŋpétu",
	"field-mon-relative+0": "Aŋpétutȟokahe kiŋ lé",
	"field-mon-relative+1": "Aŋpétutȟokahe kiŋháŋ",
	"field-thu-relative+0": "Aŋpétutopa kiŋ lé",
	"field-thu-relative+1": "Aŋpétutopa kiŋháŋ",
	"field-wed-relative+0": "Aŋpétuyamni kiŋ lé",
	"field-wed-relative+1": "Aŋpétuyamni kiŋháŋ",
	"field-month-relative+-1": "Wí kʼuŋ héhaŋ",
	"field-thu-relative+-1": "Aŋpétutopa kʼuŋ héhaŋ"
}
//end v1.x content
);