define(
//begin v1.x content
{
	"USD_displayName": "Dolarɛ ya Ameriki",
	"TZS_displayName": "Shilingɛ ya Tanzani",
	"ZMW_displayName": "Kwasha ya Zambi",
	"MAD_displayName": "Dirihame ya Marokɛ",
	"NGN_displayName": "Naira ya Nizerya",
	"ZWD_displayName": "Dolarɛ ya Zimbabwɛ",
	"SDG_displayName": "Dinarɛ ya Sudá",
	"MWK_displayName": "Kwasha ya Malawi",
	"KMF_displayName": "Falánga ya Komoro",
	"SCR_displayName": "Rupi ya Sɛshɛlɛ",
	"CDF_symbol": "FC",
	"EGP_displayName": "Paunɛ ya Ezípitɛ",
	"CVE_displayName": "Esikudo ya Kapevɛrɛ",
	"LYD_displayName": "Dinarɛ ya Libí",
	"CAD_displayName": "Dolarɛ ya Kanadá",
	"INR_displayName": "Rupi ya Índɛ",
	"JPY_displayName": "Yeni ya Zapɔ",
	"LRD_displayName": "Dolarɛ ya Liberya",
	"ZAR_displayName": "Randɛ ya Afríka Súdi",
	"AOA_displayName": "Kwanza ya Angóla",
	"TND_displayName": "Dinarɛ ya Tinizi",
	"GHC_displayName": "Sedi ya Gana",
	"BWP_displayName": "Pula ya Botswana",
	"DZD_displayName": "Dinarɛ ya Alizeri",
	"ZMK_displayName": "Kwasha ya Zambi (1968–2012)",
	"NAD_displayName": "Dolarɛ ya Namibi",
	"AED_displayName": "Dirihamɛ ya Lémila alabo",
	"ETB_displayName": "Birɛ ya Etsiópi",
	"MZM_displayName": "Metikali ya Mozambiki",
	"BIF_displayName": "Falánga ya Burundi",
	"RWF_displayName": "Falánga ya Rwanda",
	"STD_displayName": "Dobra ya Sao Tomé mpé Presipe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Ɛlɔ́",
	"ERN_displayName": "Nakfa ya Elitlɛ",
	"SAR_displayName": "Riyalɛ ya Alabi Sawuditɛ",
	"DJF_displayName": "Falánga ya Dzibuti",
	"CDF_displayName": "Falánga ya Kongó",
	"GBP_displayName": "Paunɛ ya Angɛlɛtɛ́lɛ",
	"CHF_displayName": "Falánga ya Swisɛ",
	"MUR_displayName": "Rupi ya Morisi",
	"SOS_displayName": "Shilingɛ ya Somali",
	"BHD_displayName": "Dinarɛ ya Bahrɛnɛ",
	"XOF_displayName": "Falánga CFA BCEAO",
	"GNS_displayName": "Falánga ya Ginɛ",
	"SLL_displayName": "Leonɛ",
	"UGX_displayName": "Shilingɛ ya Uganda",
	"MGA_displayName": "Falánga ya Madagasikarɛ",
	"SDP_displayName": "Paunɛ ya Sudá",
	"AUD_displayName": "Dolarɛ ya Ositali",
	"KES_displayName": "Shilingɛ ya Kenya",
	"SHP_displayName": "Paunɛ ya Sántu elena",
	"XAF_displayName": "Falánga CFA BEAC",
	"LSL_displayName": "Loti ya Lesóto",
	"MRO_displayName": "Ugwiya ya Moritani",
	"CNY_displayName": "Yuanɛ Renminbi ya Sinɛ",
	"GMD_displayName": "Dalasi ya Gambi"
}
//end v1.x content
);