define(
//begin v1.x content
{
	"USD_displayName": "Doola ey'Amerika",
	"TZS_displayName": "Silingi ey'eTanzaniya",
	"ZMW_displayName": "Kwaca ey'eZambya",
	"MAD_displayName": "Diraamu ey'eMoroko",
	"NGN_displayName": "Nayira ey'eNayijerya",
	"ZWD_displayName": "Doola ey'eZimbabwe",
	"SDG_displayName": "Dinaali ey'eSudaani",
	"MWK_displayName": "Kwaca ey'eMalawi",
	"KMF_displayName": "Faranga ya Komoro",
	"SCR_displayName": "Rupiya ey'eSesere",
	"EGP_displayName": "Pawunda ya Misiri",
	"CVE_displayName": "Esikudo ya Keepu Veredi",
	"LYD_displayName": "Dinaali ya Libya",
	"CAD_displayName": "Doola ya Kanada",
	"INR_displayName": "Rupiya ya Buyindi",
	"JPY_displayName": "Yeni ya Japani",
	"LRD_displayName": "Doola ya Liberya",
	"ZAR_displayName": "Randi ey'eSawusafirika",
	"AOA_displayName": "Kwanza y'Angola",
	"TND_displayName": "Dinaali ey'eTunizya",
	"GHC_displayName": "Sedi ya Gana",
	"BWP_displayName": "Pula ya Botiswana",
	"DZD_displayName": "Dinaali y'Aligerya",
	"ZMK_displayName": "Kwaca ey'eZambya (1968–2012)",
	"AED_displayName": "Diraamu eya Emireeti",
	"ETB_displayName": "Biiru ya Esyopya",
	"MZM_displayName": "Metikaali ey'eMozambiiki",
	"BIF_displayName": "Faranga ya burundi",
	"RWF_displayName": "Faranga ey'eRwanda",
	"STD_displayName": "Dobura ey'eSantome ne Purincipe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakifa ya Eritureya",
	"SAR_displayName": "Riyaali ey'eBuwarabu",
	"DJF_displayName": "Faranga ya Jjibuti",
	"CDF_displayName": "Faranga ya Kongo",
	"GBP_displayName": "Pawunda ya Bungereza",
	"CHF_displayName": "Faranga ey'eSwitizirandi",
	"MUR_displayName": "Rupiya ey'eMawurisyasi",
	"SOS_displayName": "Silingi ey'eSomaliya",
	"BHD_displayName": "Dinaali ya Baareeni",
	"XOF_displayName": "Faranga yamu Afirika ya bugwanjuba",
	"UGX_symbol": "USh",
	"GNS_displayName": "Faranga ya Gini",
	"SLL_displayName": "Lewone",
	"UGX_displayName": "Silingi eya Yuganda",
	"MGA_displayName": "Faranga ey'eMalagase",
	"SDP_displayName": "Pawunda ey'eSudaani",
	"AUD_displayName": "Doola y'Awusiturelya",
	"KES_displayName": "Silingi ya Kenya",
	"SHP_displayName": "Pawunda ey'eSenti Herena",
	"XAF_displayName": "Faranga yamu Afirika ya wakati",
	"LSL_displayName": "Loti ya Lesoso",
	"MRO_displayName": "Wugwiya ey'eMawritenya",
	"CNY_displayName": "Yuwani Reniminibi ya Cayina",
	"GMD_displayName": "Dalasi ya Gambya"
}
//end v1.x content
);