define(
//begin v1.x content
{
	"USD_displayName": "Dɔlà è US",
	"TZS_displayName": "Shwɨlà è Tàanzanyìa",
	"ZMW_displayName": "Kwachà è Zambìa",
	"MAD_displayName": "Dilàm è Mòlokò",
	"NGN_displayName": "Naelà è Gɨ̀anyɨ",
	"ZWD_displayName": "Dɔlà è Zìmbagbɛ̀",
	"SDG_displayName": "Bɔ̀ŋ è Sùdànê",
	"MWK_displayName": "Kwachà è Màlawè",
	"KMF_displayName": "Fàlâŋ è Komolìa",
	"SCR_displayName": "Lukpìi è Sɛchɛ̀lɛ̀",
	"EGP_displayName": "Bɔ̀ŋ è Edzì",
	"CVE_displayName": "Kàbòvàdianù è Èsùkudò",
	"LYD_displayName": "Dinà è Lebìa",
	"CAD_displayName": "Dɔlà è Kanadà",
	"INR_displayName": "Lukpì è Endìa",
	"JPY_displayName": "Ghɨ̂n Dzàkpànê",
	"LRD_displayName": "Dɔlà Làebɛlìa",
	"ZAR_displayName": "Lân è Afɨlekà ghɨ Emàm ghò",
	"AOA_displayName": "Kwanzà è Àŋgolà",
	"TND_displayName": "Dinà è Tùwneshìa",
	"GHC_displayName": "Sɛ̀di è Gaanà",
	"BWP_displayName": "Kpuwlà è Botɨshǔanà",
	"DZD_displayName": "Dinà è Àdzɛlìa",
	"ZMK_displayName": "Kwachà è Zambìa (1968–2012)",
	"NAD_displayName": "Dɔlà è Nàmibìa",
	"AED_displayName": "Dilàm è Yùnaetɛ Alab Emelɛ̀",
	"ETB_displayName": "Bîi è Etyǒkpìa",
	"MZM_displayName": "Mètikà è Mùzàmbî",
	"BIF_displayName": "Fàlâŋ è Bùlundì",
	"RWF_displayName": "Fàlâŋ è Lùwandà",
	"STD_displayName": "Dɔbàlà è Sàwu Tɔ̀me à Pèlènsipè",
	"SZL_displayName": "Lèlàŋgenè",
	"EUR_displayName": "Yulù",
	"ERN_displayName": "Nakafa è Èletɨ̀làe",
	"SAR_displayName": "Leyà è Sàwudì",
	"DJF_displayName": "Fàlâŋ è Dzìbutì",
	"CDF_displayName": "Fàlâŋ è Kuŋgùlê",
	"GBP_displayName": "Bɔ̀ŋ Sɨ̀telè è Bèletì",
	"CHF_displayName": "Fàlâŋ è Sues",
	"MUR_displayName": "Lukpìi è Mùleshòs",
	"SOS_displayName": "Shwɨlà è Sùmalìa",
	"BHD_displayName": "Dinà è Balae",
	"XOF_displayName": "CFA Fàlâŋ BCEAO",
	"GNS_displayName": "Fàlâŋ è Ginè",
	"SLL_displayName": "Lyɔ̂ŋ",
	"UGX_displayName": "Shwɨlà è Yùgandà",
	"MGA_displayName": "Àlǐalè è Màlàgasì",
	"AUD_displayName": "Dɔlà e Ùsɨ̀tɛ̀lɛlìa",
	"KES_displayName": "Shwɨlà tɨ Kenyà",
	"SHP_displayName": "Bɔ̀ŋ è Sɛ̀n Èlenà",
	"XAF_displayName": "CFA Fàlâŋ BEAC",
	"LSL_displayName": "Lɔtì Lèsutù",
	"MRO_displayName": "Ùgueya è Mùlètenyìa",
	"CNY_displayName": "Yùwân Lèmembi è Chaenî",
	"GMD_displayName": "Dàlasì è Gambìa"
}
//end v1.x content
);