define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "â tsɨ̀",
	"field-minute": "menè",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "ā zūɛɛ",
	"field-weekday": "tsuʔu mɨ̀ èwɨ̄n",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "kɨtîgh",
	"field-hour": "tàm",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "nɛ",
	"field-day-relative+1": "tsʉtsʉ",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "dɨŋò kɨ enɨ̀gha",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "kɨnûm",
	"field-week": "ewɨn",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "ndzɔŋ",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "sɛkɔ̀n",
	"field-day": "utsuʔ",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);