define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "U년 MMM d일 (E)",
	"dateFormatItem-MMMEd": "MMM d일 (E)",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-Gy": "U년",
	"dateFormatItem-y": "U년",
	"dateFormatItem-yyyy": "U년",
	"dateFormatItem-yyyyMMMEEEEd": "U년 MMM d일 EEEE",
	"dateFormatItem-EEEEd": "d일 EEEE",
	"dateFormatItem-Ed": "d일 (E)",
	"dateFormatItem-GyMMMd": "U년 MMM d일",
	"dateFormat-long": "U년 M월 d일",
	"dateFormatItem-MMMEEEEd": "MMM d일 EEEE",
	"dateFormat-medium": "y. M. d.",
	"dateFormatItem-Hms": "H시 m분 s초",
	"dateFormatItem-yMd": "U. M. d.",
	"dateFormatItem-yyyyQQQQ": "U년 QQQQ",
	"dateFormatItem-GyMMMEEEEd": "U년 MMM d일 EEEE",
	"dateFormatItem-yyyyMd": "U. M. d.",
	"dateFormatItem-yyyyMMMd": "U년 MMM d일",
	"dateFormatItem-yyyyMEd": "U. M. d. (E)",
	"dateFormatItem-yyyyMEEEEd": "U. M. d. EEEE",
	"dateFormatItem-MMMd": "MMM d일",
	"dateFormatItem-H": "H시",
	"dateFormatItem-M": "M월",
	"dateFormatItem-GyMMMEd": "U년 MMM d일 (E)",
	"dateFormatItem-GyMMM": "U년 MMM",
	"dateFormatItem-MEEEEd": "M. d. EEEE",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateFormatItem-yyyyQQQ": "U년 QQQ",
	"dateFormatItem-hm": "a h:mm",
	"dateFormat-short": "y. M. d.",
	"dateFormatItem-yyyyM": "U. M.",
	"dateFormat-full": "U년 M월 d일 EEEE",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-yyyyMMM": "U년 MMM",
	"dateFormatItem-d": "d일",
	"dateFormatItem-h": "a h시"
}
//end v1.x content
);