// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"안도라 페세타",
	AED_displayName:"아랍에미리트 디르함",
	AFA_displayName:"아프가니 (1927-2002)",
	AFN_displayName:"아프가니",
	ALL_displayName:"알바니아 레크",
	ALL_symbol:"레크",
	AMD_displayName:"아르메니아 드람",
	AMD_symbol:"드램",
	ANG_displayName:"네덜란드령 안틸레스 길더",
	AOA_displayName:"앙골라 콴자",
	AOK_displayName:"앙골라 콴자 (1977-1990)",
	AON_displayName:"앙골라 신콴자 (1990-2000)",
	AOR_displayName:"앙골라 콴자 Reajustado (1995-1999)",
	ARA_displayName:"아르헨티나 오스트랄",
	ARP_displayName:"아르헨티나 페소 (1983-1985)",
	ARS_displayName:"아르헨티나 페소",
	ATS_displayName:"호주 실링",
	AUD_displayName:"호주 달러",
	AUD_symbol:"A$",
	AWG_displayName:"아루바 길더",
	AZM_displayName:"아제르바이젠 마나트",
	AZN_displayName:"아제르바이잔 마나트",
	BAD_displayName:"보스니아-헤르체고비나 디나르",
	BAM_displayName:"보스니아-헤르체고비나 태환 마르크",
	BBD_displayName:"바베이도스 달러",
	BBD_symbol:"BDS$",
	BDT_displayName:"방글라데시 타카",
	BEC_displayName:"벨기에 프랑 (태환)",
	BEF_displayName:"벨기에 프랑",
	BEL_displayName:"벨기에 프랑 (금융)",
	BGL_displayName:"불가리아 동전 렛",
	BGN_displayName:"불가리아 신권 렛",
	BHD_displayName:"바레인 디나르",
	BIF_displayName:"부룬디 프랑",
	BMD_displayName:"버뮤다 달러",
	BMD_symbol:"BM$",
	BND_displayName:"부루나이 달러",
	BND_symbol:"B$",
	BOB_displayName:"볼리비아노",
	BOP_displayName:"볼리비아노 페소",
	BRB_displayName:"볼리비아노 크루제이루 노보 (1967-1986)",
	BRC_displayName:"브라질 크루자두",
	BRE_displayName:"브라질 크루제이루 (1990-1993)",
	BRL_displayName:"브라질 레알",
	BRN_displayName:"브라질 크루자두 노보",
	BRR_displayName:"브라질 크루제이루",
	BSD_displayName:"바하마 달러",
	BTN_displayName:"부탄 눌투눔",
	BUK_displayName:"버마 차트",
	BWP_displayName:"보츠와나 폴라",
	BYB_displayName:"벨라루스 신권 루블 (1994-1999)",
	BYR_displayName:"벨라루스 루블",
	BZD_displayName:"벨리즈 달러",
	BZD_symbol:"BZ$",
	CAD_displayName:"캐나다 달러",
	CAD_symbol:"Can$",
	CDF_displayName:"콩고 프랑 콩골라스",
	CHE_displayName:"WIR 유로",
	CHF_displayName:"스위스 프랑",
	CHW_displayName:"WIR 프랑",
	CLP_displayName:"칠레 페소",
	CLP_symbol:"Ch$",
	CNY_displayName:"중국 위안 인민폐",
	CNY_symbol:"¥",
	COP_displayName:"콜롬비아 페소",
	COP_symbol:"Col$",
	CRC_displayName:"코스타리카 콜론",
	CSD_displayName:"고 세르비아 디나르",
	CSK_displayName:"체코슬로바키아 동전 코루나",
	CUP_displayName:"쿠바 페소",
	CVE_displayName:"카보베르데 에스쿠도",
	CYP_displayName:"싸이프러스 파운드",
	CYP_symbol:"￡C",
	CZK_displayName:"체코 공화국 코루나",
	DDM_displayName:"동독 오스트마르크",
	DEM_displayName:"독일 마르크",
	DJF_displayName:"지부티 프랑",
	DKK_displayName:"덴마크 크로네",
	DOP_displayName:"도미니카 페소",
	DOP_symbol:"RD$",
	DZD_displayName:"알제리 디나르",
	ECS_displayName:"에쿠아도르 수크레",
	EEK_displayName:"에스토니아 크룬",
	EGP_displayName:"이집트 파운드",
	ERN_displayName:"에리트리아 나크파",
	ESA_displayName:"스페인 페세타(예금)",
	ESB_displayName:"스페인 페세타(변환 예금)",
	ESP_displayName:"스페인 페세타",
	ETB_displayName:"이디오피아 비르",
	EUR_displayName:"유로화",
	FIM_displayName:"핀란드 마르카",
	FJD_displayName:"피지 달러",
	FJD_symbol:"F$",
	FKP_displayName:"포클랜드제도 파운드",
	FRF_displayName:"프랑스 프랑",
	FRF_symbol:"₣",
	GBP_displayName:"영국령 파운드 스털링",
	GEK_displayName:"그루지야 지폐 라리트",
	GEL_displayName:"그루지야 라리",
	GHC_displayName:"가나 시디",
	GIP_displayName:"지브롤터 파운드",
	GMD_displayName:"감비아 달라시",
	GNF_displayName:"기니 프랑",
	GNS_displayName:"기니 시리",
	GRD_displayName:"그리스 드라크마",
	GTQ_displayName:"과테말라 케트살",
	GWE_displayName:"포르투갈령 기니 에스쿠도",
	GWP_displayName:"기네비쏘 페소",
	GYD_displayName:"가이아나 달러",
	GYD_symbol:"G$",
	HKD_displayName:"홍콩 달러",
	HKD_symbol:"HK$",
	HNL_displayName:"온두라스 렘피라",
	HRD_displayName:"크로아티아 디나르",
	HRK_displayName:"크로아티아 쿠나",
	HTG_displayName:"하이티 구르드",
	HUF_displayName:"헝가리 포린트",
	IDR_displayName:"인도네시아 루피아",
	IEP_displayName:"아일랜드 파운드",
	IEP_symbol:"IR£",
	ILP_displayName:"이스라엘 파운드",
	ILS_displayName:"이스라엘 신권 세켈",
	INR_displayName:"인도 루피",
	INR_symbol:"0≤Rs.|1≤Re.|1<Rs.",
	IQD_displayName:"이라크 디나르",
	IRR_displayName:"이란 리얄",
	ISK_displayName:"아이슬란드 크로나",
	ITL_displayName:"이탈리아 리라",
	ITL_symbol:"₤",
	JMD_displayName:"자메이카 달러",
	JOD_displayName:"요르단 디나르",
	JPY_displayName:"일본 엔",
	JPY_symbol:"￥",
	KES_displayName:"케냐 실링",
	KGS_displayName:"키르기스스탄 솜",
	KHR_displayName:"캄보디아 리얄",
	KMF_displayName:"코모르 프랑",
	KPW_displayName:"조선 민주주의 인민 공화국 원",
	KPW_symbol:"₩",
	KRW_displayName:"대한민국 원",
	KRW_symbol:"￦",
	KWD_displayName:"쿠웨이트 디나르",
	KYD_displayName:"케이맨 제도 달러",
	KZT_displayName:"카자흐스탄 텐게",
	LAK_displayName:"라오스 키프",
	LBP_displayName:"레바논 파운드",
	LKR_displayName:"스리랑카 루피",
	LRD_displayName:"라이베리아 달러",
	LSL_displayName:"레소토 로티",
	LSM_displayName:"로티",
	LTL_displayName:"리투아니아 리타",
	LTT_displayName:"룩셈부르크 타로나",
	LUC_displayName:"룩셈부르크 변환 프랑",
	LUF_displayName:"룩셈부르크 프랑",
	LUL_displayName:"룩셈부르크 재정 프랑",
	LVL_displayName:"라트비아 라트",
	LVR_displayName:"라트비아 루블",
	LYD_displayName:"리비아 디나르",
	MAD_displayName:"모로코 디렘",
	MAF_displayName:"모로코 프랑",
	MDL_displayName:"몰도바 레이",
	MGA_displayName:"마다가스카르 아리아리",
	MGF_displayName:"마다가스카르 프랑",
	MKD_displayName:"마케도니아 디나르",
	MLF_displayName:"말리 프랑",
	MMK_displayName:"미얀마 키얏",
	MNT_displayName:"몽골 투그릭",
	MOP_displayName:"마카오 파타카",
	MRO_displayName:"모리타니 우기야",
	MRO_symbol:"UM",
	MTL_displayName:"몰타 리라",
	MTP_displayName:"몰타 파운드",
	MUR_displayName:"모리셔스 루피",
	MVR_displayName:"몰디브 제도 루피아",
	MWK_displayName:"말라위 콰쳐",
	MXN_displayName:"멕시코 페소",
	MXP_displayName:"멕시코 실버 페소 (1861-1992)",
	MXV_displayName:"멕시코 UDI(Unidad de Inversion)",
	MYR_displayName:"말레이시아 링깃",
	MZE_displayName:"모잠비크 에스쿠도",
	MZM_displayName:"고 모잠비크 메티칼",
	MZN_displayName:"모잠비크 메티칼",
	NAD_displayName:"나미비아 달러",
	NGN_displayName:"니제르 나이라",
	NIC_displayName:"니카라과 코르도바",
	NIO_displayName:"니카라과 코르도바 오로",
	NLG_displayName:"네델란드 길더",
	NOK_displayName:"노르웨이 크로네",
	NPR_displayName:"네팔 루피",
	NZD_displayName:"뉴질랜드 달러",
	OMR_displayName:"오만 리얄",
	PAB_displayName:"파나마 발보아",
	PEI_displayName:"페루 인티",
	PEN_displayName:"페루 솔 누에보",
	PES_displayName:"페루 솔",
	PGK_displayName:"파푸아뉴기니 키나",
	PHP_displayName:"필리핀 페소",
	PKR_displayName:"파키스탄 루피",
	PLN_displayName:"폴란드 즐로티",
	PLZ_displayName:"폴란드 즐로티 (1950-1995)",
	PTE_displayName:"포르투갈 에스쿠도",
	PYG_displayName:"파라과이 과라니",
	QAR_displayName:"카타르 리얄",
	RHD_displayName:"로디지아 달러",
	ROL_displayName:"루마니아 레이",
	RON_displayName:"루마니아 레우",
	RSD_displayName:"세르비아 디나르",
	RUB_displayName:"러시아 루블",
	RUR_displayName:"러시아 루블 (1991-1998)",
	RWF_displayName:"르완다 프랑",
	SAR_displayName:"사우디아라비아 리얄",
	SBD_displayName:"솔로몬 제도 달러",
	SCR_displayName:"세이쉴 루피",
	SDD_displayName:"수단 디나르",
	SDP_displayName:"수단 파운드",
	SEK_displayName:"스웨덴 크로나",
	SGD_displayName:"싱가폴 달러",
	SGD_symbol:"S$",
	SHP_displayName:"세인트헬레나 파운드",
	SIT_displayName:"슬로베니아 톨라르",
	SKK_displayName:"슬로바키아 코루나",
	SLL_displayName:"시에라리온 리온",
	SOS_displayName:"소말리아 실링",
	SRD_displayName:"수리남 달러",
	SRG_displayName:"수리남 길더",
	STD_displayName:"상투메 프린시페 도브라",
	SUR_displayName:"소련 루블",
	SVC_displayName:"엘살바도르 콜론",
	SYP_displayName:"시리아 파운드",
	SZL_displayName:"스와질란드 릴랑게니",
	THB_displayName:"태국 바트",
	TJR_displayName:"타지키스탄 루블",
	TJS_displayName:"타지키스탄 소모니",
	TMM_displayName:"투르크메니스탄 마나트",
	TND_displayName:"튀니지 디나르",
	TOP_displayName:"통가 파앙가",
	TPE_displayName:"티모르 에스쿠도",
	TRL_displayName:"터키 리라",
	TRY_displayName:"새로운 터키 리라",
	TTD_displayName:"트리니다드 토바고 달러",
	TWD_displayName:"대만 신권 달러",
	TWD_symbol:"NT$",
	TZS_displayName:"탄자니아 실링",
	UAH_displayName:"우크라이나 그리브나",
	UAK_displayName:"우크라이나 카보바네츠",
	UGS_displayName:"우간다 실링 (1966-1987)",
	UGX_displayName:"우간다 실링",
	USD_displayName:"미국 달러",
	USN_displayName:"미국 달러(다음날)",
	USS_displayName:"미국 달러(당일)",
	UYP_displayName:"우루과이 페소 (1975-1993)",
	UYU_displayName:"우루과이 페소 우루과요",
	UZS_displayName:"우즈베키스탄 숨",
	VEB_displayName:"베네주엘라 볼리바르",
	VND_displayName:"베트남 동",
	VUV_displayName:"바누아투 바투",
	WST_displayName:"서 사모아 탈라",
	XAF_displayName:"CFA 프랑 BEAC",
	XAG_displayName:"은화",
	XAU_displayName:"금",
	XBA_displayName:"유르코 (유럽 회계 단위)",
	XBB_displayName:"유럽 통화 동맹",
	XBC_displayName:"유럽 계산 단위 (XBC)",
	XBD_displayName:"유럽 계산 단위 (XBD)",
	XCD_displayName:"동카리브 달러",
	XDR_displayName:"특별인출권",
	XEU_displayName:"유럽 환율 단위",
	XFO_displayName:"프랑스 Gold 프랑",
	XFU_displayName:"프랑스 UIC-프랑",
	XOF_displayName:"CFA 프랑 BCEAO",
	XPD_displayName:"팔라듐",
	XPF_displayName:"CFP 프랑",
	XPT_displayName:"백금",
	XRE_displayName:"RINET 기금",
	XTS_displayName:"테스트 통화 코드",
	XXX_displayName:"알수없거나 유효하지않은 통화단위",
	YDD_displayName:"예멘 디나르",
	YER_displayName:"예멘 리알",
	YUD_displayName:"유고슬라비아 동전 디나르",
	YUM_displayName:"유고슬라비아 노비 디나르",
	YUN_displayName:"유고슬라비아 전환 디나르",
	ZAL_displayName:"남아프리카 랜드 (금융)",
	ZAR_displayName:"남아프리카 랜드",
	ZMK_displayName:"쟘비아 콰쳐",
	ZRN_displayName:"자이르 신권 자이르",
	ZRZ_displayName:"자이르 자이르",
	ZWD_displayName:"짐비브웨 달러"
})
                 