define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "G y년 MMM d일 (E)",
	"dateFormatItem-MMMEd": "MMM d일 (E)",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "G y년",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "G y년",
	"dateFormatItem-yyyy": "G y년",
	"dateFormatItem-yyyyMMMEEEEd": "G y년 MMM d일 EEEE",
	"dateFormatItem-EEEEd": "d일 EEEE",
	"dateFormatItem-Ed": "d일 (E)",
	"dateFormatItem-GyMMMd": "G y년 MMM d일",
	"dateFormat-long": "G y년 M월 d일",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMMEEEEd": "MMM d일 EEEE",
	"dateFormat-medium": "G y. M. d.",
	"dateFormatItem-Hms": "H시 m분 s초",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "G y년 QQQQ",
	"dateFormatItem-GyMMMEEEEd": "G y년 MMM d일 EEEE",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-yyyyMd": "G y. M. d.",
	"dateFormatItem-yyyyMMMd": "G y년 MMM d일",
	"dateFormatItem-yyyyMEd": "G y. M. d. (E)",
	"dateFormatItem-yyyyMEEEEd": "G y. M. d. EEEE",
	"dateFormatItem-MMMd": "MMM d일",
	"dateFormatItem-H": "H시",
	"dateFormatItem-M": "M월",
	"dateFormatItem-GyMMMEd": "G y년 MMM d일 (E)",
	"dateFormatItem-GyMMM": "G y년 MMM",
	"dateFormatItem-MEEEEd": "M. d. EEEE",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateFormatItem-yyyyQQQ": "G y년 QQQ",
	"dateFormatItem-hm": "a h:mm",
	"dateFormat-short": "G y. M. d.",
	"dateFormatItem-yyyyM": "G y. M.",
	"dateFormat-full": "G y년 M월 d일 EEEE",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-yyyyMMM": "G y년 MMM",
	"dateFormatItem-d": "d일",
	"dateFormatItem-h": "a h시"
}
//end v1.x content
);