({
	"dateFormatItem-yM": "yyyy. M.", 
	"field-dayperiod": "오전/오후", 
	"dateFormatItem-yQ": "y년 Q분기", 
	"field-minute": "분", 
	"eraNames": [
		"서력기원전", 
		"서력기원"
	], 
	"dateFormatItem-MMMEd": "MMM d일 (E)", 
	"dateTimeFormat-full": "{1} {0}", 
	"dateFormatItem-MMdd": "MM. dd", 
	"dateFormatItem-yQQQ": "y년 QQQ", 
	"field-weekday": "요일", 
	"days-standAlone-wide": [
		"일요일", 
		"월요일", 
		"화요일", 
		"수요일", 
		"목요일", 
		"금요일", 
		"토요일"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"1월", 
		"2월", 
		"3월", 
		"4월", 
		"5월", 
		"6월", 
		"7월", 
		"8월", 
		"9월", 
		"10월", 
		"11월", 
		"12월"
	], 
	"dateTimeFormat-short": "{1} {0}", 
	"dateTimeFormat-medium": "{1} {0}", 
	"field-era": "연호", 
	"field-hour": "시", 
	"dayPeriods-am-format-wide": "오전", 
	"quarters-standAlone-abbr": [
		"1분기", 
		"2분기", 
		"3분기", 
		"4분기"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "a h시 m분 s초 zzzz", 
	"dayPeriods-pm-format-wide": "오후", 
	"months-standAlone-abbr": [
		"1월", 
		"2월", 
		"3월", 
		"4월", 
		"5월", 
		"6월", 
		"7월", 
		"8월", 
		"9월", 
		"10월", 
		"11월", 
		"12월"
	], 
	"dateFormatItem-Ed": "d일 (E)", 
	"dateFormatItem-yMMM": "y년 MMM", 
	"days-standAlone-narrow": [
		"일", 
		"월", 
		"화", 
		"수", 
		"목", 
		"금", 
		"토"
	], 
	"eraAbbr": [
		"기원전", 
		"서기"
	], 
	"dateFormatItem-yyyyMM": "yyyy. MM", 
	"dateFormat-long": "y년 M월 d일", 
	"timeFormat-medium": "a h:mm:ss", 
	"dateFormatItem-EEEd": "d일 EEE", 
	"field-zone": "시간대", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "yyyy. M. d.", 
	"dateFormatItem-yyMM": "YY. M.", 
	"dateFormatItem-Hms": "H시 m분 s초", 
	"dateFormatItem-yyMMM": "yy년 MMM", 
	"quarters-standAlone-wide": [
		"제 1/4분기", 
		"제 2/4분기", 
		"제 3/4분기", 
		"제 4/4분기"
	], 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "년", 
	"dateTimeFormat-long": "{1} {0}", 
	"dateFormatItem-HHmmss": "HH:mm:ss", 
	"field-week": "주", 
	"months-standAlone-wide": [
		"1월", 
		"2월", 
		"3월", 
		"4월", 
		"5월", 
		"6월", 
		"7월", 
		"8월", 
		"9월", 
		"10월", 
		"11월", 
		"12월"
	], 
	"dateFormatItem-MMMd": "MMM d일", 
	"dateFormatItem-yyQ": "yy년 Q분기", 
	"timeFormat-long": "a h시 m분 s초 z", 
	"months-format-abbr": [
		"1월", 
		"2월", 
		"3월", 
		"4월", 
		"5월", 
		"6월", 
		"7월", 
		"8월", 
		"9월", 
		"10월", 
		"11월", 
		"12월"
	], 
	"timeFormat-short": "a h:mm", 
	"field-month": "월", 
	"quarters-format-abbr": [
		"1분기", 
		"2분기", 
		"3분기", 
		"4분기"
	], 
	"days-format-abbr": [
		"일", 
		"월", 
		"화", 
		"수", 
		"목", 
		"금", 
		"토"
	], 
	"dateFormatItem-M": "L", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"일", 
		"월", 
		"화", 
		"수", 
		"목", 
		"금", 
		"토"
	], 
	"dateFormatItem-yMMMd": "y년 MMM d일", 
	"field-second": "초", 
	"field-day": "일", 
	"dateFormatItem-MEd": "M. d. (E)", 
	"months-format-narrow": [
		"1월", 
		"2월", 
		"3월", 
		"4월", 
		"5월", 
		"6월", 
		"7월", 
		"8월", 
		"9월", 
		"10월", 
		"11월", 
		"12월"
	], 
	"days-standAlone-abbr": [
		"일", 
		"월", 
		"화", 
		"수", 
		"목", 
		"금", 
		"토"
	], 
	"dateFormat-short": "yy. M. d.", 
	"dateFormatItem-yMMMEd": "y년 MMM d일 EEE", 
	"dateFormat-full": "y년 M월 d일 EEEE", 
	"dateFormatItem-Md": "M. d.", 
	"dateFormatItem-yMEd": "yyyy. M. d. EEE", 
	"months-format-wide": [
		"1월", 
		"2월", 
		"3월", 
		"4월", 
		"5월", 
		"6월", 
		"7월", 
		"8월", 
		"9월", 
		"10월", 
		"11월", 
		"12월"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"제 1/4분기", 
		"제 2/4분기", 
		"제 3/4분기", 
		"제 4/4분기"
	], 
	"days-format-wide": [
		"일요일", 
		"월요일", 
		"화요일", 
		"수요일", 
		"목요일", 
		"금요일", 
		"토요일"
	], 
	"eraNarrow": [
		"기원전", 
		"서기"
	]
})