// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
	'months-format-abbr':["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"],
	'months-format-wide':["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"],
	'months-standAlone-abbr':["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"],
	'months-standAlone-narrow':["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"],
	'months-standAlone-wide':["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"],
	'days-format-abbr':["일","월","화","수","목","금","토"],
	'days-format-wide':["일요일","월요일","화요일","수요일","목요일","금요일","토요일"],
	'days-standAlone-narrow':["일","월","화","수","목","금","토"],
	'quarters-format-abbr':["1분기","2분기","3분기","4분기"],
	'quarters-format-wide':["제 1/4분기","제 2/4분기","제 3/4분기","제 4/4분기"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'am':"오전",
	'pm':"오후",
	'eraNames':["서력기원전","서력기원"],
	'eraAbbr':["기원전","서기"],
	'dateFormat-full': "yyyy년 M월 d일 EEEE",
	'dateFormat-long': "yyyy년 M월 d일",
	'dateFormat-medium': "yyyy. M. d.",
	'dateFormat-short': "yy. M. d.",
	'timeFormat-full': "a hh시 mm분 ss초 v",
	'timeFormat-long': "a hh시 mm분 ss초 z",
	'timeFormat-medium': "a h:mm:ss",
	'timeFormat-short': "a h:mm",
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeAvailableFormats':["d일 (E)","HH:mm","HH:mm:ss","H:mm","H시 m분 s초","L","M. d. (E)","LLL","MMM d일 (E)","MMMM d일 (E)","MMMM d일","MMM d일","MM. dd","M. d.","d","mm:ss","mm:ss","yyyy","yyyy. M.","yyyy. M. d. EEE","yyyy년 MMM","yyyy년 MMM d일 EEE","yyyy년 MMMM","yyyy년 Q분기","yyyy년 QQQ","YY. M.","yy년 MMM","yy년 Q분기","yyyy. MM"],
        'field-era':"연호",
        'field-year':"년",
        'field-month':"월",
        'field-week':"주",
        'field-day':"일",
        'field-weekday':"요일",
        'field-dayperiod':"오전/오후",
        'field-hour':"시",
        'field-minute':"분",
        'field-second':"초",
        'field-zone':"시간대"
})
                        