// generated from ldml/main/*.xml, xpath: ldml/numbers
({
	'decimal':".",
	'group':",",
	'list':";",
	'percentSign':"%",
	'nativeZeroDigit':"0",
	'patternDigit':"#",
	'plusSign':"+",
	'minusSign':"-",
	'exponential':"E",
	'perMille':"‰",
	'infinity':"∞",
	'nan':"NaN",
	'decimalFormat':"#,##0.###",
	'scientificFormat':"#E0",
	'percentFormat':"#,##0%",
	'currencyFormat':"¤#,##0.00"
})
