define(
//begin v1.x content
{
	"field-sat-relative+0": "šį šeštadienį",
	"field-sat-relative+1": "kitą šeštadienį",
	"field-dayperiod": "Iki pietų / po pietų",
	"field-sun-relative+-1": "praėjusį sekmadienį",
	"field-mon-relative+-1": "praėjusį pirmadienį",
	"field-minute": "Minutė",
	"field-day-relative+-1": "vakar",
	"field-weekday": "Savaitės diena",
	"field-day-relative+-2": "užvakar",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"field-era": "Era",
	"field-hour": "Valanda",
	"field-sun-relative+0": "šį sekmadienį",
	"field-sun-relative+1": "kitą sekmadienį",
	"field-wed-relative+-1": "praėjusį trečiadienį",
	"field-day-relative+0": "šiandien",
	"field-day-relative+1": "rytoj",
	"field-day-relative+2": "poryt",
	"field-tue-relative+0": "šį antradienį",
	"field-zone": "Laiko juosta",
	"field-tue-relative+1": "kitą antradienį",
	"field-week-relative+-1": "praėjusią savaitę",
	"field-year-relative+0": "šiais metais",
	"field-year-relative+1": "kitais metais",
	"field-sat-relative+-1": "praėjusį šeštadienį",
	"field-year-relative+-1": "praėjusiais metais",
	"field-year": "Metai",
	"field-fri-relative+0": "šį penktadienį",
	"field-fri-relative+1": "kitą penktadienį",
	"field-week": "Savaitė",
	"field-week-relative+0": "šią savaitę",
	"field-week-relative+1": "kitą savaitę",
	"field-month-relative+0": "šį mėnesį",
	"field-month": "Mėnuo",
	"field-month-relative+1": "kitą mėnesį",
	"field-fri-relative+-1": "praėjusį penktadienį",
	"field-second": "Sekundė",
	"field-tue-relative+-1": "praėjusį antradienį",
	"field-day": "Diena",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"field-mon-relative+0": "šį pirmadienį",
	"field-mon-relative+1": "kitą pirmadienį",
	"field-thu-relative+0": "šį ketvirtadienį",
	"field-second-relative+0": "dabar",
	"field-thu-relative+1": "kitą ketvirtadienį",
	"field-wed-relative+0": "šį trečiadienį",
	"field-wed-relative+1": "kitą trečiadienį",
	"field-month-relative+-1": "praėjusį mėnesį",
	"field-thu-relative+-1": "praėjusį ketvirtadienį"
}
//end v1.x content
);