define(
//begin v1.x content
{
	"USD_displayName": "dol$ara ttî äLetäa-Ôko tî Amerîka",
	"TZS_displayName": "shilîngi tî Tanzanïi",
	"ZMW_displayName": "kwâtia tî Zambïi",
	"MAD_displayName": "dirâm tî Marôko",
	"NGN_displayName": "nâîra tî Nizerïa",
	"ZWD_displayName": "dolära tî Zimbäbwe",
	"SDG_displayName": "pôndo tî Sudäan",
	"MWK_displayName": "kwâtia tî Malawïi",
	"KMF_displayName": "farânga tî Kömôro",
	"SCR_displayName": "rupïi tî Sëyshêle",
	"EGP_displayName": "pôndo tî Kâmitâ",
	"CVE_displayName": "eskûêdo tî Kâpo-Vêre",
	"LYD_displayName": "dinäar tî Libïi",
	"CAD_displayName": "dolära tî kanadäa",
	"INR_displayName": "rupïi tî Ênnde",
	"JPY_displayName": "yêni tî Zapön",
	"LRD_displayName": "dolära tî Liberïa",
	"ZAR_displayName": "rânde tî Mbongo-Afrîka",
	"AOA_displayName": "kwânza tî Angoläa",
	"TND_displayName": "dinära tî Tunizïi",
	"GHC_displayName": "sêdi tî Ganäa",
	"BWP_displayName": "pûla tî Botswana",
	"DZD_displayName": "dinäri tî Alzerïi",
	"ZMK_displayName": "kwâtia tî Zambïi (1968–2012)",
	"NAD_displayName": "dolära tî Namibïi",
	"AED_displayName": "dirâm tî âEmirâti tî Arâbo Ôko",
	"ETB_displayName": "bir tî Etiopïi",
	"MZM_displayName": "metikala tî Mozambîka",
	"BIF_displayName": "farânga tî Burundïi",
	"RWF_displayName": "farânga tî Ruandäa",
	"STD_displayName": "dôbra tî Sâô Tomë na Prinsîpe",
	"SZL_displayName": "lilangùeni tî Swazïlânde",
	"EUR_displayName": "zoröo",
	"ERN_displayName": "nakafa tî Eritrëe",
	"SAR_displayName": "riâli tî Saûdi Arabïi",
	"DJF_displayName": "farânga tî Dibutïi",
	"CDF_displayName": "farânga tî Kongöo",
	"GBP_displayName": "pôndo tî Anglëe",
	"CHF_displayName": "farânga tî Sûîsi",
	"MUR_displayName": "rupïi tî Mörîsi",
	"SOS_displayName": "shilîngi tî Somalïi",
	"BHD_displayName": "dolùara tî Bahrâina",
	"XOF_displayName": "farânga CFA (BCEAO)",
	"GNS_displayName": "sili tî Ginëe",
	"SLL_displayName": "leône tî Sierâ-Leône",
	"UGX_displayName": "shilîngi tî Ugandäa",
	"MGA_displayName": "ariâri tî Madagasikära",
	"AUD_displayName": "dolära tî Ostralïi",
	"KES_displayName": "shilîngi tî Kenyäa",
	"SHP_displayName": "pôndo tî Zûâ Sênt-Helêna",
	"XAF_displayName": "farânga CFA (BEAC)",
	"LSL_displayName": "loti tî Lesôtho",
	"MRO_displayName": "ugîya tî Moritanïi",
	"CNY_displayName": "yuan renminbi tî Shîni",
	"GMD_displayName": "dalasi tî gambïi"
}
//end v1.x content
);