define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Na lâ",
	"field-minute": "Ndurü ngbonga",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Bîrï",
	"field-weekday": "Bïkua",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "Kùotângo",
	"field-hour": "Ngbonga",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Lâsô",
	"field-day-relative+1": "Kêkerêke",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Zukangbonga",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Ngû",
	"field-week": "Dimâsi",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Nze",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"field-second": "Nzîna ngbonga",
	"field-day": "Lâ",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);