define(
//begin v1.x content
{
	"USD_displayName": "Ḍular Umirikani",
	"TZS_displayName": "Cilin Uṭanzani",
	"ZMW_displayName": "Kwača Uzambi",
	"MAD_displayName": "Derhem Umeṛṛuki",
	"NGN_displayName": "Nayra Unijiri",
	"ZWD_displayName": "Ḍular Uzimbabwi",
	"SDG_displayName": "Junih Usudani",
	"MWK_displayName": "Kwača Umalawi",
	"KMF_displayName": "Frank Uqumuri",
	"SCR_displayName": "Rupi Usicili",
	"EGP_displayName": "Junih Umiṣṛi",
	"CVE_displayName": "Iskudu Ukabuvirdyani",
	"LYD_displayName": "Ḍinar Ulibi",
	"CAD_displayName": "Ḍular Ukanadi",
	"INR_displayName": "Rupi Uḥindi",
	"JPY_displayName": "Yann Ujappuni",
	"LRD_displayName": "Ḍular Ulibiri",
	"ZAR_displayName": "Rand Ufriki Unzul",
	"AOA_displayName": "Kwanza Unguli",
	"TND_displayName": "Ḍinar Utunsi",
	"GHC_displayName": "Sidi Uɣani",
	"BWP_displayName": "Pula Ubutswani",
	"DZD_displayName": "Ḍinar Udzayri",
	"ZMK_displayName": "Kwača Uzambi (1968–2012)",
	"NAD_displayName": "Ḍular Unamibi",
	"AED_displayName": "Derhem Uymarati",
	"ETB_displayName": "Birr Uyityuppi",
	"MZM_displayName": "Mitikal Umuzambiqi",
	"BIF_displayName": "Frank Uburundi",
	"RWF_displayName": "Frank Urwandi",
	"STD_displayName": "Dubra Usawṭumi",
	"SZL_displayName": "Lilanjini Uswazi",
	"EUR_displayName": "Uṛu",
	"ERN_displayName": "Nakfa Uyritri",
	"SAR_displayName": "Ryal Usaεudi",
	"DJF_displayName": "Frank Uğibuti",
	"CDF_displayName": "Frank Ukunguli",
	"GBP_displayName": "Junih Usterlini Ubriṭani",
	"CHF_displayName": "Frank Uswisri",
	"MUR_displayName": "Rupi Umurisi",
	"SOS_displayName": "Cilin Uṣumali",
	"BHD_displayName": "Ḍinar Ubaḥrayni",
	"XOF_displayName": "Frank CFA (BCEAO)",
	"GNS_displayName": "Frank Uɣini",
	"SLL_displayName": "Lyun Usirralyuni",
	"UGX_displayName": "Cilin Uɣandi (1966–1987)",
	"MGA_displayName": "Aryari Umalɣaci",
	"SDP_displayName": "Junih Usudani (1956–2007)",
	"AUD_displayName": "Ḍular Usṭrali",
	"KES_displayName": "Cillin Ukini",
	"SHP_displayName": "Junih Usantehilini",
	"XAF_displayName": "Frank CFA (BEAC)",
	"LSL_displayName": "Luti Ulusuṭi",
	"MRO_displayName": "Uqiyya Umuritani",
	"CNY_displayName": "Ywan Renminbi Ucinwi",
	"GMD_displayName": "Dalasi Agambi"
}
//end v1.x content
);