define(
//begin v1.x content
{
	"USD_displayName": "Dolár yá amɛ́rəkə",
	"TZS_displayName": "Silíŋ yá Tanazaní",
	"ZMW_displayName": "Kwatsa yá Zambí",
	"MAD_displayName": "Dirám yá Maróg",
	"NGN_displayName": "Náíra yá Nihéria",
	"ZWD_displayName": "Dolár yá Zimbabwé",
	"SDG_displayName": "Lívələ yá Sudán",
	"MWK_displayName": "Kwatsa yá Malawí",
	"KMF_displayName": "Fəláŋ yá Komória",
	"SCR_displayName": "Rupí yá Sɛsɛ́l",
	"EGP_displayName": "Lívə́lə yá Ehíbətía",
	"CVE_displayName": "Esəkúdo yá Kápə́vɛ́rə",
	"LYD_displayName": "Dinár yá Libí",
	"CAD_displayName": "Dolár yá Kanáda",
	"INR_displayName": "Rupí yá ɛ́ndía",
	"JPY_displayName": "Yɛ́n yá Hapɔ́n",
	"LRD_displayName": "Dolár yá Libéria",
	"ZAR_displayName": "Ránədə yá Afiríka",
	"AOA_displayName": "Kwánəza yá Angolá",
	"TND_displayName": "Dinár yá Tunisí",
	"GHC_displayName": "Tzedí yá Ganá",
	"BWP_displayName": "Púlá yá Botswána",
	"DZD_displayName": "Dinár yá Alehérí",
	"ZMK_displayName": "Kwatsa yá Zambí (1968–2012)",
	"NAD_displayName": "Dolár yá Namibí",
	"AED_displayName": "Dirám yá Emirá Aráb Uní",
	"ETB_displayName": "Bír yá Etsiópia",
	"MZM_displayName": "Metikal yá Mozambíg",
	"BIF_displayName": "Fəláŋ yá Burundí",
	"RWF_displayName": "Fəláŋ yá Ruwandá",
	"STD_displayName": "Dóbə́ra yá Saó Tomé ai Pəlinəsípe",
	"SZL_displayName": "Lilangeni yá Swazí",
	"EUR_displayName": "əró",
	"ERN_displayName": "Náfəka yá Eritelé",
	"SAR_displayName": "Riál yá Arabí Saudí",
	"DJF_displayName": "Fəláŋ yá dzibutí",
	"CDF_displayName": "Fəláŋ yá Kongo",
	"GBP_displayName": "Lívə́lə Sətərəlíŋ",
	"CHF_displayName": "Fəláŋ yá Suís",
	"MUR_displayName": "Rupí yá Morís",
	"SOS_displayName": "Silíŋ yá Somalí",
	"BHD_displayName": "Dinár yá Bahərɛ́n",
	"XOF_displayName": "Fəláŋ CFA (BCEAO)",
	"GNS_displayName": "Síli yá Giné",
	"SLL_displayName": "Leóne yá Sierá-leónə",
	"UGX_displayName": "Silíŋ yá Ugandá (1966–1987)",
	"MGA_displayName": "Ariari yá Maləgás",
	"SDP_displayName": "Lívələ yá Sudán (1956–2007)",
	"AUD_displayName": "Dolár yá Osətəralí",
	"KES_displayName": "Silíŋ yá Keniá",
	"SHP_displayName": "Lívələ yá Ǹfúfúb Elɛ́n",
	"XAF_displayName": "Fəláŋ CFA (BEAC)",
	"LSL_displayName": "Lotí yá Lesotó",
	"MRO_displayName": "Ugiya yá Moritaní",
	"CNY_displayName": "Yuán Renəminəbí yá Tsainís",
	"GMD_displayName": "Dalasí yá Gámbía"
}
//end v1.x content
);