define(
//begin v1.x content
{
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "this wk",
	"field-week-narrow-relative+1": "next wk",
	"field-wed-narrow-relative+-1": "↑↑↑",
	"field-year-narrow": "↑↑↑",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "this yr",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "next yr",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"field-weekdayOfMonth-narrow": "wkday of mo",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-weekOfMonth": "↑↑↑",
	"field-month-short": "mo.",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "day of yr",
	"field-year-relative+-1": "↑↑↑",
	"field-sat-short-relative+-1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"field-wed-relative+-1": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"dateFormat-long": "↑↑↑",
	"field-quarter": "↑↑↑",
	"field-week-short": "↑↑↑",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"field-minute-short": "min.",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dateFormat-medium": "↑↑↑",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "↑↑↑",
	"months-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-quarter-relative+-1": "↑↑↑",
	"field-dayperiod-narrow": "am/pm",
	"field-week-narrow-relative+-1": "last wk",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"field-hour": "↑↑↑",
	"months-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormat-full": "↑↑↑",
	"field-month-relative+-1": "↑↑↑",
	"field-quarter-short": "↑↑↑",
	"field-sat-narrow-relative+0": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"months-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormat-short": "↑↑↑",
	"field-thu-short-relative+-1": "↑↑↑",
	"field-year-narrow-relative+-1": "last yr",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+-1": "last Tu",
	"field-weekOfMonth-short": "wk of mo.",
	"field-wed-short-relative+0": "↑↑↑",
	"months-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"Third Month",
		"Fourth Month",
		"Fifth Month",
		"Sixth Month",
		"Seventh Month",
		"Eighth Month",
		"Ninth Month",
		"Tenth Month",
		"Eleventh Month",
		"Twelfth Month"
	],
	"field-wed-short-relative+1": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"field-week-short-relative+0": "this wk",
	"field-week-short-relative+1": "next wk",
	"months-standAlone-abbr": [
		"Mo1",
		"Mo2",
		"Mo3",
		"Mo4",
		"Mo5",
		"Mo6",
		"Mo7",
		"Mo8",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-dayOfYear-narrow": "day of yr",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "wkday of mo.",
	"field-zone-narrow": "↑↑↑",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"field-week": "↑↑↑",
	"field-wed-narrow-relative+0": "↑↑↑",
	"field-wed-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+0": "↑↑↑",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"field-week-short-relative+-1": "last wk",
	"field-hour-short": "h",
	"field-zone-short": "↑↑↑",
	"field-month-narrow": "mo.",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "↑↑↑",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"field-mon-narrow-relative+0": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "↑↑↑",
	"field-weekOfMonth-narrow": "wk of mo",
	"field-weekday-narrow": "day of wk",
	"field-quarter-narrow": "↑↑↑",
	"field-sun-short-relative+-1": "↑↑↑",
	"field-day-relative+-1": "↑↑↑",
	"field-weekday-short": "day of wk",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "↑↑↑",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "↑↑↑",
	"field-fri-narrow-relative+1": "↑↑↑"
}
//end v1.x content
);