define(
//begin v1.x content
{
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"dateFormatItem-Hm": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"dateFormatItem-ms": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"dateTimeFormat-short": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "this wk",
	"field-week-narrow-relative+1": "next wk",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-wed-narrow-relative+-1": "↑↑↑",
	"field-year-narrow": "↑↑↑",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "this yr",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "next yr",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dateFormatItem-MMMd": "d MMM",
	"field-weekdayOfMonth-narrow": "wkday of mo",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"field-weekOfMonth": "↑↑↑",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-yyyyMd": "dd/MM/y GGGGG",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "day of yr",
	"field-year-relative+-1": "↑↑↑",
	"field-sat-short-relative+-1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMEd": "E, dd/MM/y GGGGG",
	"field-wed-relative+-1": "↑↑↑",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-quarter": "↑↑↑",
	"field-week-short": "↑↑↑",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dateFormatItem-MMM": "LLL",
	"field-minute-short": "min.",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yyyyM": "MM/y GGGGG",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "↑↑↑",
	"field-quarter-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"field-dayperiod-narrow": "am/pm",
	"field-week-narrow-relative+-1": "last wk",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "dd/MM",
	"field-hour": "↑↑↑",
	"dateFormat-full": "EEEE, d MMMM y G",
	"field-month-relative+-1": "↑↑↑",
	"dateFormatItem-Hms": "↑↑↑",
	"field-quarter-short": "↑↑↑",
	"field-sat-narrow-relative+0": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"dateFormatItem-Ehm": "↑↑↑",
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormat-short": "↑↑↑",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "last yr",
	"field-thu-short-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-E": "↑↑↑",
	"dateFormatItem-H": "↑↑↑",
	"field-weekOfMonth-short": "wk of mo.",
	"field-tue-narrow-relative+-1": "last Tu",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-M": "LL",
	"field-wed-short-relative+0": "↑↑↑",
	"field-wed-short-relative+1": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"dateTimeFormat-full": "↑↑↑",
	"dateFormatItem-hm": "↑↑↑",
	"dateFormatItem-d": "d",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"dateFormatItem-h": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"field-week-short-relative+0": "this wk",
	"field-week-short-relative+1": "next wk",
	"field-dayOfYear-narrow": "day of yr",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "wkday of mo.",
	"dateFormatItem-MEd": "↑↑↑",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "y G",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"dateFormatItem-hms": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"dateFormatItem-yMd": "dd/MM/y",
	"field-week": "↑↑↑",
	"dateFormatItem-Ed": "E d",
	"field-wed-narrow-relative+0": "↑↑↑",
	"field-wed-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"field-week-short-relative+-1": "last wk",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-hour-short": "h",
	"field-zone-short": "↑↑↑",
	"field-month-narrow": "mo.",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "↑↑↑",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"dateFormatItem-Bhms": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"field-mon-narrow-relative+0": "↑↑↑",
	"dateFormatItem-EHm": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "↑↑↑",
	"dateFormatItem-MMMEd": "↑↑↑",
	"field-weekOfMonth-narrow": "wk of mo",
	"dateFormatItem-EHms": "↑↑↑",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"field-weekday-narrow": "day of wk",
	"field-quarter-narrow": "↑↑↑",
	"field-sun-short-relative+-1": "↑↑↑",
	"field-day-relative+-1": "↑↑↑",
	"field-weekday-short": "day of wk",
	"dateFormatItem-Bhm": "↑↑↑",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"dateFormatItem-Gy": "y G",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "↑↑↑",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "↑↑↑",
	"field-fri-narrow-relative+1": "↑↑↑"
}
//end v1.x content
);