define(
//begin v1.x content
{
	"dayPeriods-standAlone-abbr-noon": "midday",
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"dateFormatItem-yw": "↑↑↑",
	"dayPeriods-format-abbr-afternoon1": "afternoon",
	"dateFormatItem-Hm": "HH:mm",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"dateFormatItem-ms": "mm:ss",
	"timeFormat-short": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"dateTimeFormat-short": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "this wk",
	"field-week-narrow-relative+1": "next wk",
	"field-wed-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-year-narrow": "↑↑↑",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "this yr",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "next yr",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dayPeriods-format-narrow-am": "am",
	"dayPeriods-standAlone-abbr-morning1": "morning",
	"dateFormatItem-MMMd": "d MMM",
	"dayPeriods-format-narrow-morning1": "morning",
	"field-weekdayOfMonth-narrow": "wkday of mo",
	"dayPeriods-format-abbr-am": "am",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"timeFormat-medium": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-standAlone-wide-noon": "midday",
	"eraNames": [
		"Before Christ",
		"Anno Domini"
	],
	"field-weekOfMonth": "↑↑↑",
	"dayPeriods-standAlone-abbr-pm": "pm",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"field-day": "↑↑↑",
	"dayPeriods-standAlone-wide-night1": "↑↑↑",
	"field-dayOfYear-short": "day of yr",
	"field-year-relative+-1": "↑↑↑",
	"dayPeriods-format-wide-am": "am",
	"field-sat-short-relative+-1": "↑↑↑",
	"dayPeriods-format-narrow-afternoon1": "afternoon",
	"dayPeriods-format-wide-afternoon1": "in the afternoon",
	"field-hour-relative+0": "↑↑↑",
	"field-wed-relative+-1": "↑↑↑",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"days-standAlone-narrow": [
		"Su.",
		"M.",
		"Tu.",
		"W.",
		"Th.",
		"F.",
		"Sa."
	],
	"dayPeriods-standAlone-narrow-noon": "midday",
	"dayPeriods-standAlone-wide-pm": "pm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormat-long": "↑↑↑",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dayPeriods-standAlone-abbr-midnight": "midnight",
	"field-quarter": "↑↑↑",
	"field-week-short": "↑↑↑",
	"dayPeriods-format-narrow-midnight": "midnight",
	"field-day-narrow-relative+0": "↑↑↑",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"field-day-narrow-relative+1": "↑↑↑",
	"quarters-standAlone-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"days-format-narrow": [
		"Su.",
		"M.",
		"Tu.",
		"W.",
		"Th.",
		"F.",
		"Sa."
	],
	"dayPeriods-format-wide-evening1": "in the evening",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dayPeriods-standAlone-abbr-night1": "night",
	"dayPeriods-standAlone-narrow-afternoon1": "afternoon",
	"dateFormatItem-MMM": "LLL",
	"field-minute-short": "min.",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dayPeriods-format-narrow-pm": "pm",
	"dateFormat-medium": "↑↑↑",
	"eraAbbr": [
		"BC",
		"AD"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dayPeriods-format-abbr-pm": "pm",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"dayPeriods-standAlone-narrow-night1": "night",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "↑↑↑",
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-format-wide-morning1": "in the morning",
	"field-quarter-relative+-1": "↑↑↑",
	"field-dayperiod-narrow": "am/pm",
	"dayPeriods-standAlone-narrow-am": "am",
	"field-week-narrow-relative+-1": "last wk",
	"days-format-short": [
		"Su",
		"Mon",
		"Tu",
		"Wed",
		"Th",
		"Fri",
		"Sat"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dayPeriods-format-wide-pm": "pm",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "d/M",
	"field-hour": "↑↑↑",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"months-format-wide": [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December"
	],
	"dayPeriods-format-wide-night1": "at night",
	"dateFormat-full": "↑↑↑",
	"field-month-relative+-1": "↑↑↑",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-quarter-short": "↑↑↑",
	"field-sat-narrow-relative+0": "↑↑↑",
	"dateFormatItem-Hmv": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"dayPeriods-format-narrow-noon": "midday",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"dateFormatItem-Ehm": "E h:mm a",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"June",
		"July",
		"Aug",
		"Sept",
		"Oct",
		"Nov",
		"Dec"
	],
	"dayPeriods-format-wide-midnight": "midnight",
	"timeFormat-long": "↑↑↑",
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormat-short": "d/M/yy",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "last yr",
	"dayPeriods-format-abbr-night1": "night",
	"dateFormatItem-MMMMW": "↑↑↑",
	"field-thu-short-relative+-1": "↑↑↑",
	"days-standAlone-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	],
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-H": "HH",
	"field-weekOfMonth-short": "wk of mo.",
	"field-tue-narrow-relative+-1": "last Tu",
	"dayPeriods-format-abbr-evening1": "evening",
	"dayPeriods-standAlone-narrow-pm": "pm",
	"dateFormatItem-M": "↑↑↑",
	"months-standAlone-wide": [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December"
	],
	"field-wed-short-relative+0": "↑↑↑",
	"field-wed-short-relative+1": "↑↑↑",
	"dateFormatItem-Hmsv": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"days-standAlone-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateTimeFormat-full": "↑↑↑",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-d": "d",
	"field-weekday": "↑↑↑",
	"dayPeriods-standAlone-wide-evening1": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"dateFormatItem-h": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"field-week-short-relative+0": "this wk",
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec"
	],
	"dateFormatItem-hmsv": "↑↑↑",
	"field-week-short-relative+1": "next wk",
	"dayPeriods-format-abbr-morning1": "morning",
	"dayPeriods-standAlone-narrow-evening1": "evening",
	"field-dayOfYear-narrow": "day of yr",
	"field-month-short-relative+0": "↑↑↑",
	"timeFormat-full": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "wkday of mo.",
	"dateFormatItem-MEd": "E, d/M",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "y",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"dayPeriods-standAlone-abbr-afternoon1": "afternoon",
	"field-thu-relative+1": "↑↑↑",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-fri-short-relative+-1": "↑↑↑",
	"dateFormatItem-hmv": "↑↑↑",
	"dayPeriods-format-abbr-noon": "midday",
	"field-thu-relative+-1": "↑↑↑",
	"dateFormatItem-yMd": "↑↑↑",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-week": "↑↑↑",
	"quarters-format-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"dateFormatItem-Ed": "E d",
	"field-wed-narrow-relative+0": "↑↑↑",
	"field-wed-narrow-relative+1": "↑↑↑",
	"dayPeriods-standAlone-wide-morning1": "↑↑↑",
	"field-year-short-relative+0": "↑↑↑",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"days-standAlone-short": [
		"Su",
		"Mon",
		"Tu",
		"Wed",
		"Th",
		"Fri",
		"Sat"
	],
	"field-week-short-relative+-1": "last wk",
	"dayPeriods-standAlone-narrow-morning1": "morning",
	"dayPeriods-format-abbr-midnight": "midnight",
	"field-hour-short": "h",
	"field-zone-short": "↑↑↑",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"field-month-narrow": "mo.",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "↑↑↑",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"eraNarrow": [
		"BC",
		"AD"
	],
	"dateFormatItem-Bhms": "↑↑↑",
	"dayPeriods-format-wide-noon": "midday",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"dayPeriods-standAlone-wide-afternoon1": "↑↑↑",
	"dateFormatItem-yQQQ": "QQQ y",
	"days-format-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	],
	"field-mon-narrow-relative+0": "↑↑↑",
	"dateFormatItem-EHm": "E HH:mm",
	"field-mon-narrow-relative+1": "↑↑↑",
	"dayPeriods-standAlone-wide-midnight": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"dateFormatItem-yM": "MM/y",
	"field-zone": "↑↑↑",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-MMMEd": "↑↑↑",
	"field-weekOfMonth-narrow": "wk of mo",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-yMEd": "↑↑↑",
	"field-weekday-narrow": "day of wk",
	"dayPeriods-standAlone-narrow-midnight": "midnight",
	"field-quarter-narrow": "↑↑↑",
	"dayPeriods-standAlone-abbr-am": "am",
	"field-day-relative+-1": "↑↑↑",
	"field-sun-short-relative+-1": "↑↑↑",
	"dayPeriods-format-narrow-night1": "night",
	"field-weekday-short": "day of wk",
	"dateFormatItem-Bhm": "↑↑↑",
	"days-format-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateFormatItem-MMdd": "dd/MM",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-Gy": "y G",
	"field-era": "↑↑↑",
	"field-week-narrow": "↑↑↑",
	"field-day-short": "↑↑↑",
	"dayPeriods-standAlone-abbr-evening1": "evening",
	"field-fri-narrow-relative+0": "↑↑↑",
	"dayPeriods-format-narrow-evening1": "evening",
	"field-fri-narrow-relative+1": "↑↑↑",
	"dayPeriods-standAlone-wide-am": "am"
}
//end v1.x content
);