define(
//begin v1.x content
{
	"dateTimeFormats-appendItem-Year": "{0} {1}",
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"dateFormatItem-Hm": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"dateFormatItem-ms": "↑↑↑",
	"timeFormat-short": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"dateTimeFormat-short": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "this wk",
	"field-week-narrow-relative+1": "next wk",
	"field-wed-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-year-narrow": "↑↑↑",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "this yr",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "next yr",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dayPeriods-format-narrow-am": "am",
	"dateFormatItem-MMMd": "d MMM",
	"field-weekdayOfMonth-narrow": "wkday of mo",
	"dayPeriods-format-abbr-am": "am",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"timeFormat-medium": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-weekOfMonth": "↑↑↑",
	"dayPeriods-standAlone-abbr-pm": "pm",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-yyyyMd": "dd/MM/y GGGGG",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "day of yr",
	"field-year-relative+-1": "↑↑↑",
	"dayPeriods-format-wide-am": "am",
	"field-sat-short-relative+-1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMEd": "E, dd/MM/y GGGGG",
	"field-wed-relative+-1": "↑↑↑",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"days-standAlone-narrow": [
		"Su.",
		"M.",
		"Tu.",
		"W.",
		"Th.",
		"F.",
		"Sa."
	],
	"dayPeriods-standAlone-wide-pm": "pm",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-quarter": "↑↑↑",
	"field-week-short": "↑↑↑",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"quarters-standAlone-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"days-format-narrow": [
		"Su.",
		"M.",
		"Tu.",
		"W.",
		"Th.",
		"F.",
		"Sa."
	],
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dateFormatItem-MMM": "LLL",
	"field-minute-short": "min.",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dayPeriods-format-narrow-pm": "pm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"eraAbbr": [
		"AH"
	],
	"dayPeriods-format-abbr-pm": "pm",
	"dateFormatItem-yyyyM": "MM/y GGGGG",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "↑↑↑",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-quarter-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"field-dayperiod-narrow": "am/pm",
	"dayPeriods-standAlone-narrow-am": "am",
	"field-week-narrow-relative+-1": "last wk",
	"days-format-short": [
		"Su",
		"Mon",
		"Tu",
		"Wed",
		"Th",
		"Fri",
		"Sat"
	],
	"dayPeriods-format-wide-pm": "pm",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "dd/MM",
	"field-hour": "↑↑↑",
	"months-format-wide": [
		"Muharram",
		"Safar",
		"Rabiʻ I",
		"Rabiʻ II",
		"Jumada I",
		"Jumada II",
		"Rajab",
		"Shaʻban",
		"Ramadan",
		"Shawwal",
		"Dhuʻl-Qiʻdah",
		"Dhuʻl-Hijjah"
	],
	"dateFormat-full": "EEEE, d MMMM y G",
	"field-month-relative+-1": "↑↑↑",
	"dateFormatItem-Hms": "↑↑↑",
	"field-quarter-short": "↑↑↑",
	"field-sat-narrow-relative+0": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"dateFormatItem-Ehm": "↑↑↑",
	"months-format-abbr": [
		"Muh.",
		"Saf.",
		"Rab. I",
		"Rab. II",
		"Jum. I",
		"Jum. II",
		"Raj.",
		"Sha.",
		"Ram.",
		"Shaw.",
		"Dhuʻl-Q.",
		"Dhuʻl-H."
	],
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"timeFormat-long": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-Bh": "↑↑↑",
	"field-thu-short-relative+-1": "↑↑↑",
	"field-year-narrow-relative+-1": "last yr",
	"days-standAlone-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	],
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateTimeFormats-appendItem-Era": "{0} {1}",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-E": "ccc",
	"field-tue-narrow-relative+-1": "last Tu",
	"field-weekOfMonth-short": "wk of mo.",
	"dateFormatItem-H": "↑↑↑",
	"dateFormatItem-yyyy": "y G",
	"dayPeriods-standAlone-narrow-pm": "pm",
	"field-wed-short-relative+0": "↑↑↑",
	"dateFormatItem-M": "LL",
	"months-standAlone-wide": [
		"Muharram",
		"Safar",
		"Rabiʻ I",
		"Rabiʻ II",
		"Jumada I",
		"Jumada II",
		"Rajab",
		"Shaʻban",
		"Ramadan",
		"Shawwal",
		"Dhuʻl-Qiʻdah",
		"Dhuʻl-Hijjah"
	],
	"field-wed-short-relative+1": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"dateTimeFormat-full": "↑↑↑",
	"dateFormatItem-hm": "↑↑↑",
	"dateFormatItem-d": "d",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"dateFormatItem-h": "↑↑↑",
	"field-week-short-relative+0": "this wk",
	"field-week-short-relative+1": "next wk",
	"months-standAlone-abbr": [
		"Muh.",
		"Saf.",
		"Rab. I",
		"Rab. II",
		"Jum. I",
		"Jum. II",
		"Raj.",
		"Sha.",
		"Ram.",
		"Shaw.",
		"Dhuʻl-Q.",
		"Dhuʻl-H."
	],
	"field-dayOfYear-narrow": "day of yr",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "wkday of mo.",
	"timeFormat-full": "↑↑↑",
	"dateFormatItem-MEd": "↑↑↑",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "y G",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"dateFormatItem-hms": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"dateFormatItem-yMd": "dd/MM/y",
	"field-week": "↑↑↑",
	"quarters-format-wide": [
		"1st quarter",
		"2nd quarter",
		"3rd quarter",
		"4th quarter"
	],
	"dateFormatItem-Ed": "E d",
	"field-wed-narrow-relative+0": "↑↑↑",
	"field-wed-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"days-standAlone-short": [
		"Su",
		"Mon",
		"Tu",
		"Wed",
		"Th",
		"Fri",
		"Sat"
	],
	"field-week-short-relative+-1": "last wk",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-hour-short": "h",
	"field-zone-short": "↑↑↑",
	"field-month-narrow": "mo.",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "↑↑↑",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"dateFormatItem-Bhms": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"days-format-wide": [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	],
	"field-mon-narrow-relative+0": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"dateFormatItem-EHm": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "↑↑↑",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-weekOfMonth-narrow": "wk of mo",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"dateFormatItem-EHms": "↑↑↑",
	"field-weekday-narrow": "day of wk",
	"field-quarter-narrow": "↑↑↑",
	"field-sun-short-relative+-1": "↑↑↑",
	"field-day-relative+-1": "↑↑↑",
	"dayPeriods-standAlone-abbr-am": "am",
	"field-weekday-short": "day of wk",
	"dateFormatItem-Bhm": "↑↑↑",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"dateFormatItem-Gy": "y G",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "↑↑↑",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "↑↑↑",
	"field-fri-narrow-relative+1": "↑↑↑",
	"dayPeriods-standAlone-wide-am": "am"
}
//end v1.x content
);