define(
//begin v1.x content
{
	"USD_displayName": "Dora re Amerika",
	"TZS_displayName": "Shiringi re Tanzania",
	"ZMW_displayName": "Kwacha ye Zambia",
	"MAD_displayName": "Dirham ye Moroko",
	"NGN_displayName": "Naira ye Nijeria",
	"ZWD_displayName": "Dora re Zimbabwe",
	"SDG_displayName": "Dinari re Sudani",
	"MWK_displayName": "Kwacha ye Malawi",
	"KMF_displayName": "Furenki re Komoro",
	"SCR_displayName": "Rupi re Seyisheri",
	"EGP_displayName": "Paundi re Ijipita",
	"CVE_displayName": "Dhora re Escudo",
	"LYD_displayName": "Dinari re Libya",
	"CAD_displayName": "Dora re Kanada",
	"INR_displayName": "Rupe re India",
	"JPY_displayName": "Yeni ye Japani",
	"LRD_displayName": "Dora re Liberia",
	"ZAR_displayName": "Randi",
	"AOA_displayName": "Kwanza ye Angola",
	"TND_displayName": "Dinari re Tunisia",
	"GHC_displayName": "Sedi ye Ghana",
	"BWP_displayName": "Pura re Botswana",
	"DZD_displayName": "Dhinari re Aljeria",
	"ZMK_displayName": "Kwacha ye Zambia (1968–2012)",
	"NAD_displayName": "Dora re Namibia",
	"AED_displayName": "Diramu re United Arab Emirates",
	"ETB_displayName": "Dhora re Etiopia",
	"MZM_displayName": "Metika ye Mozambiki",
	"BIF_displayName": "Furenki re Bhurundi",
	"RWF_displayName": "Furenki re Ruwanda",
	"STD_displayName": "Dobra re Sao Tome ne Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakfa re Eritrea",
	"SAR_displayName": "Riyali re Saudi",
	"DJF_displayName": "Furenki re Jibhuti",
	"CDF_displayName": "Furenki re Kongo",
	"GBP_displayName": "Paundi ye Bhiriteni",
	"CHF_displayName": "Furenki re Swisi",
	"MUR_displayName": "Rupi ye Morishasi",
	"SOS_displayName": "Shiringi re Somalia",
	"BHD_displayName": "Dhinari re Bhahareni",
	"XOF_displayName": "Furenki CFA BCEAO",
	"GNS_displayName": "Furenki re Gine",
	"SLL_displayName": "Leoni",
	"UGX_displayName": "Shiringi re Uganda",
	"MGA_displayName": "Furenki re Malagasi",
	"SDP_displayName": "Paundi re Sudani",
	"AUD_displayName": "Dora re Australia",
	"KES_displayName": "Shiringi ye Kenya",
	"SHP_displayName": "Paundi re Senti Helena",
	"XAF_displayName": "Furenki CFA BEAC",
	"LSL_displayName": "Loti ye Lesoto",
	"MRO_displayName": "Ugwiya ye Moritania",
	"CNY_displayName": "Yuan Renminbi ye China",
	"GMD_displayName": "Dalasi ye Gambia"
}
//end v1.x content
);