define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, MMM d, y G",
	"field-minute": "ᎢᏯᏔᏬᏍᏔᏅ",
	"field-day-relative+-1": "ᏒᎯ",
	"field-weekday": "ᏒᎾᏙᏓᏆᏍᏗ ᎠᏣᎢᎵᏒ",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-era": "ᎡᎶᎯ ᎠᏣᎢᎵᏒᎢ",
	"dateFormatItem-Gy": "y G",
	"field-hour": "ᏑᏣᎶᏓ",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"field-day-relative+0": "ᎪᎯ ᎢᎦ",
	"field-day-relative+1": "ᏌᎾᎴᎢ",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-GyMMMd": "MMM d, y G",
	"dateFormat-long": "MMMM d, y G",
	"field-zone": "ᎡᎶᎯ ᎠᏍᏓᏅᏅ",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"field-year": "ᏑᏕᏘᏴᏓ",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-week": "ᏒᎾᏙᏓᏆᏍᏗ",
	"dateFormatItem-yyyyMd": "M/d/y G",
	"dateFormatItem-yyyyMMMd": "MMM d, y G",
	"dateFormatItem-yyyyMEd": "E, M/d/y G",
	"dateFormatItem-MMMd": "MMM d",
	"field-month": "ᏏᏅᏓ",
	"field-second": "ᎠᏎᏢ",
	"dateFormatItem-GyMMMEd": "E, MMM d, y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-day": "ᏏᎦ",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "M/d/y GGGGG",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormat-full": "EEEE, MMMM d, y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyMMM": "MMM y G"
}
//end v1.x content
);