define(
//begin v1.x content
{
	"USD_displayName": "Dɔla ti Orílɛ́ède Amerika",
	"TZS_displayName": "Sile ti Orílɛ́ède Tansania",
	"ZMW_displayName": "Kawasha ti Orílɛ́ède Saabia",
	"MAD_displayName": "Dirami ti Orílɛ́ède Moroko",
	"NGN_displayName": "Naira ti Orílɛ́ède Nàìjíríà",
	"ZWD_displayName": "Dɔla ti Orílɛ́ède Siibabuwe",
	"SDG_displayName": "Dina ti Orílɛ́ède Sudani",
	"MWK_displayName": "Kasha ti Orílɛ́ède Malawi",
	"KMF_displayName": "Faransi ti Orílɛ́ède shomoriani",
	"SCR_displayName": "Rupi ti Orílɛ́ède Sayiselesi",
	"EGP_displayName": "pɔɔn ti Orílɛ́ède Egipiti",
	"CVE_displayName": "Kabofediano ti Orílɛ́ède Esuodo",
	"LYD_displayName": "Dina ti Orílɛ́ède Libiya",
	"CAD_displayName": "Dɔla ti Orílɛ́ède Kánádà",
	"INR_displayName": "Rupi ti Orílɛ́ède Indina",
	"JPY_displayName": "Yeni ti Orílɛ́ède Japani",
	"LRD_displayName": "Dɔla ti Orílɛ́ède Liberia",
	"ZAR_displayName": "Randi ti Orílɛ́ède Ariwa Afirika",
	"AOA_displayName": "Wansa ti Orílɛ́ède Àngólà",
	"TND_displayName": "Dina ti Orílɛ́ède Tunisia",
	"GHC_displayName": "shidi ti Orílɛ́ède Gana",
	"BWP_displayName": "Pula ti Orílɛ́ède Bɔ̀tìsúwánà",
	"DZD_displayName": "Dina ti Orílɛ́ède Àlùgèríánì",
	"ZMK_displayName": "Kawasha ti Orílɛ́ède Saabia (1968–2012)",
	"NAD_displayName": "Dɔla ti Orílɛ́ède Namibia",
	"AED_displayName": "Diami ti Awon Orílɛ́ède Arabu",
	"ETB_displayName": "Biri ti Orílɛ́ède Eutopia",
	"MZM_displayName": "Metika ti Orílɛ́ède Mosamibiki",
	"BIF_displayName": "Faransi ti Orílɛ́ède Bùùrúndì",
	"RWF_displayName": "Faransi ti Orílɛ́ède Ruwanda",
	"STD_displayName": "Dobira ti Orílɛ́ède Sao tome Ati Pirisipe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Uro",
	"ERN_displayName": "Nakifa ti Orílɛ́ède Eriteriani",
	"SAR_displayName": "Riya ti Orílɛ́ède Saudi",
	"DJF_displayName": "Faransi ti Orílɛ́ède Dibouti",
	"CDF_displayName": "Faransi ti Orílɛ́ède Kóngò",
	"GBP_displayName": "Pɔɔn ti Orílɛ́ède Bírítísì",
	"CHF_displayName": "Faransi ti Orílɛ́ède Siwisi",
	"MUR_displayName": "Rupi ti Orílɛ́ède Maritiusi",
	"SOS_displayName": "Sile ti Orílɛ́ède Somali",
	"BHD_displayName": "Dina ti Orílɛ́ède Báránì",
	"XOF_displayName": "Faransi ti Orílɛ́ède BIKEAO",
	"GNS_displayName": "Faransi ti Orílɛ́ède Gini",
	"SLL_displayName": "Lioni",
	"UGX_displayName": "Siile ti Orílɛ́ède Uganda",
	"MGA_displayName": "Faransi ti Orílɛ́ède Malagasi",
	"SDP_displayName": "Pɔɔun ti Orílɛ́ède Sudani",
	"AUD_displayName": "Dɔla ti Orílɛ́ède Ástràlìá",
	"KES_displayName": "shiili ti Orílɛ́ède Kenya",
	"SHP_displayName": "Pɔɔun ti Orílɛ́ède ̣Elena",
	"XAF_displayName": "Faransi ti Orílɛ́ède BEKA",
	"LSL_displayName": "Loti ti Orílɛ́ède Lesoto",
	"MRO_displayName": "Ouguiya ti Orílɛ́ède Maritania",
	"NGN_symbol": "₦",
	"CNY_displayName": "Reminibi ti Orílɛ́ède sháínà",
	"GMD_displayName": "Dalasi ti Orílɛ́ède Gamibia"
}
//end v1.x content
);