define(
//begin v1.x content
{
	"USD_displayName": "ꕶꕱ ꕜꕞ",
	"TZS_displayName": "ꕚꘋꕤꕇꕰ ꔻꔝꘋ",
	"ZMW_displayName": "ꕤꔭꕩ ꖴꕎꕦ",
	"MAD_displayName": "ꗞꕟꖏ ꔵꕌꕆ",
	"NGN_displayName": "ꕯꔤꕀꔸꕩ ꕯꔤꕟ",
	"ZWD_displayName": "ꔽꕓꖜꔃ ꕜꕞ",
	"SDG_displayName": "ꖬꗵꘋ ꗁꖻꘋ",
	"MWK_displayName": "ꕮꕞꕌꔨ ꖴꕎꕦ",
	"KMF_displayName": "ꖏꖒꖄ ꖢꕟꘋꕃ",
	"SCR_displayName": "ꔖꗼꔷ ꖩꔪ",
	"EGP_displayName": "ꕆꔻꕞ ꗁꖻꘋ",
	"CVE_displayName": "ꗡꔻꖴꖁ ꕪꕷꗲꗡꔵꕩꖆ",
	"LYD_displayName": "ꔷꔫꕩ ꔵꕯ",
	"CAD_displayName": "ꕪꕯꕜ ꕜꕞꕌ",
	"INR_displayName": "ꔤꔺꕩ ꖩꔪ",
	"JPY_displayName": "ꕧꕐꕇꔧ ꘂꘋ",
	"LRD_displayName": "ꕞꔤꔫꕩ ꕜꕞꕌ",
	"ZAR_displayName": "ꕉꔱꔸꕪ ꗛꔤ ꔒꘋꗣ ꗏ ꕟꘋꔵ",
	"AOA_displayName": "ꕉꖐꕞ ꖴꕎꘋꕤ",
	"TND_displayName": "ꖤꕇꔻꕩ ꔵꕯ",
	"GHC_displayName": "ꕭꕌꕯ ꔻꔵ",
	"BWP_displayName": "ꕷꖬꕎꕯ ꖛꕞ",
	"DZD_displayName": "ꕉꔷꕀꔸꕩ ꔵꕯ",
	"ZMK_displayName": "ꕤꔭꕩ ꖴꕎꕦ (1968–2012)",
	"LRD_symbol": "$",
	"NAD_displayName": "ꕯꕆꔫꕩ ꕜꕞꕌ",
	"AED_displayName": "ꖳꕯꔤꗳ ꕉꕟꔬ ꗡꕆꔓꔻ ꔵꕌꕆ",
	"ETB_displayName": "ꔤꕿꖎꔪꕩ ꔫꔤ",
	"MZM_displayName": "ꗞꕤꔭꕃ ꕆꔳꕪ",
	"BIF_displayName": "ꖜꖩꔺ ꖢꕟꘋꕃ",
	"RWF_displayName": "ꕟꖙꕡ ꖢꕟꘋꕃ",
	"STD_displayName": "ꕢꕴ ꕿꔈ ꗪ ꕉ ꕗꕴ ꖁꖜꕟ",
	"SZL_displayName": "ꔷꕞꔟꕇ",
	"EUR_displayName": "ꖳꖄ",
	"ERN_displayName": "ꔀꔸꔳꕟ ꗁꖻꘋ",
	"SAR_displayName": "ꕢꖙꔵ ꔸꕩꔷ",
	"DJF_displayName": "ꕀꖜꔳ ꖢꕟꘋꕃ",
	"CDF_displayName": "ꖏꖐꕱ ꖢꕟꘋꕃ",
	"GBP_displayName": "ꔛꔟꔻ ꗁꖻꘋ ꔻꗳꔷꘋ",
	"CHF_displayName": "ꖬꔃꕤ ꖨꕮꕊ ꖢꕟꘋꕃ",
	"MUR_displayName": "ꗞꔓꗔ ꖩꔪ",
	"SOS_displayName": "ꖇꕮꔷ ꔻꔝꘋ",
	"BHD_displayName": "ꕑꗸꘋ",
	"GNS_displayName": "ꕅꔤꕇ ꖢꕟꘋꕃ",
	"SLL_displayName": "ꔷꗚꘋ",
	"UGX_displayName": "ꖳꕭꕡ ꔻꔝꘋ",
	"MGA_displayName": "ꕮꕞꕭꕌꔻ ꕉꔸꕩꔸ",
	"AUD_displayName": "ꖺꔻꖤꔃꔷꕩ ꕜꕞꕌ",
	"KES_displayName": "ꔞꕰ ꔻꔝꘋ",
	"SHP_displayName": "ꔻꘋ ꗥꔷꕯ ꗁꖻꘋ",
	"LSL_displayName": "ꔷꖇꕿ ꖃꔳ",
	"MRO_displayName": "ꗞꔸꕚꕇꕰ ꖳꕅꕩ",
	"CNY_displayName": "ꕦꕇꔧ ꖳꕎꘋ ꔓꕆꘋꔬ",
	"GMD_displayName": "ꕭꔭꕩ ꕜꕞꔻ"
}
//end v1.x content
);