define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-minute": "ꕆꕇ",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "ꖴꖸ",
	"field-weekday": "ꔨꕃꕮ ꔎꔒ",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-hour": "ꕌꕎ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ꗦꗷ",
	"field-day-relative+1": "ꔻꕯ",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ꕢꘋ",
	"field-week": "ꔨꔤꕃ",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "ꕪꖃ",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "ꕧꕃꕧꕪ",
	"field-day": "ꔎꔒ",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);