// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
        'months-format-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
        'months-format-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
        'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
        'days-format-abbr':["1","2","3","4","5","6","7"],
        'days-format-wide':["1","2","3","4","5","6","7"],
        'days-standAlone-narrow':["1","2","3","4","5","6","7"],
        'quarters-format-abbreviated':["Q1","Q2","Q3","Q4"],
        'quarters-format-wide':["Q1","Q2","Q3","Q4"],
        'am':"AM",
        'pm':"PM",
        'eraNames':["BCE","CE"],
        'eraAbbr':["BCE","CE"],
        'dateFormat-full': "EEEE, yyyy MMMM dd",
        'dateFormat-long': "yyyy MMMM d",
        'dateFormat-medium': "yyyy MMM d",
        'dateFormat-short': "yy/MM/dd",
        'timeFormat-full': "HH:mm:ss z",
        'timeFormat-long': "HH:mm:ss z",
        'timeFormat-medium': "HH:mm:ss",
        'timeFormat-short': "HH:mm",
        'dateTimeFormat': "{1} {0}" ,
        'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
        'dateTimeFormats-appendItem-Era':"{0} {1}",
        'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Timezone':"{0} {1}",
        'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
        'dateTimeFormats-appendItem-Year':"{0} {1}",
        'field-era':"Era",
        'field-year':"Year",
        'field-month':"Month",
        'field-week':"Week",
        'field-day':"Day",
        'field-weekday':"Day of the Week",
        'field-dayperiod':"Dayperiod",
        'field-hour':"Hour",
        'field-minute':"Minute",
        'field-second':"Second",
        'field-zone':"Zone"
})
                        