define(
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.
//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "艾莉斯蓝",
antiquewhite: "古董白",
aqua: "水绿",
aquamarine: "碧绿色",
azure: "浅天蓝",
beige: "米色",
bisque: "桔黄色",
black: "黑色",
blanchedalmond: "白杏色",
blue: "蓝色",
blueviolet: "蓝紫色",
brown: "棕色",
burlywood: "原木色",
cadetblue: "灰蓝色",
chartreuse: "浅黄绿色",
chocolate: "巧克力色",
coral: "珊瑚色",
cornflowerblue: "藏蓝色",
cornsilk: "玉米黄",
crimson: "绯红色",
cyan: "蓝绿色",
darkblue: "深蓝色",
darkcyan: "深青色",
darkgoldenrod: "深金黄色",
darkgray: "深灰色",
darkgreen: "深绿色",
darkgrey: "深灰色", // same as darkgray
darkkhaki: "深褐色",
darkmagenta: "暗洋红色",
darkolivegreen: "深橄榄绿",
darkorange: "深橙",
darkorchid: "暗淡紫色",
darkred: "深红色",
darksalmon: "深橙红",
darkseagreen: "暗海蓝色",
darkslateblue: "深青蓝",
darkslategray: "深青灰",
darkslategrey: "深青灰", // same as darkslategray
darkturquoise: "青绿",
darkviolet: "暗紫色",
deeppink: "深粉色",
deepskyblue: "深天蓝",
dimgray: "暗灰色",
dimgrey: "暗灰色", // same as dimgray
dodgerblue: "宝蓝",
firebrick: "砖红色",
floralwhite: "花白",
forestgreen: "森林绿",
fuchsia: "紫红色",
gainsboro: "淡灰色",
ghostwhite: "苍白",
gold: "金黄色",
goldenrod: "鲜黄",
gray: "灰色",
green: "绿色",
greenyellow: "黄绿色",
grey: "灰色", // same as gray
honeydew: "蜜色",
hotpink: "暗粉",
indianred: "印度红",
indigo: "靛青",
ivory: "象牙色",
khaki: "卡其色",
lavender: "淡紫色",
lavenderblush: "淡紫红",
lawngreen: "草绿色",
lemonchiffon: "柠檬绸色",
lightblue: "淡蓝色",
lightcoral: "浅珊瑚红",
lightcyan: "浅青色",
lightgoldenrodyellow: "浅金黄色",
lightgray: "浅灰色",
lightgreen: "浅绿色",
lightgrey: "浅灰色", // same as lightgray
lightpink: "浅粉色",
lightsalmon: "淡橙色",
lightseagreen: "浅海藻绿",
lightskyblue: "浅天蓝色",
lightslategray: "浅石板灰",
lightslategrey: "浅石板灰", // same as lightslategray
lightsteelblue: "浅钢蓝",
lightyellow: "淡黄色",
lime: "浅绿",
limegreen: "橙绿色",
linen: "亚麻布色",
magenta: "品红色",
maroon: "褐红",
mediumaquamarine: "淡碧绿色",
mediumblue: "中蓝色",
mediumorchid: "间紫色",
mediumpurple: "间紫色",
mediumseagreen: "间海蓝色",
mediumslateblue: "亚石板蓝",
mediumspringgreen: "淡草绿色",
mediumturquoise: "间绿宝石色",
mediumvioletred: "间紫罗兰色",
midnightblue: "深蓝",
mintcream: "薄荷乳色",
mistyrose: "粉红玫瑰",
moccasin: "鹿皮黄",
navajowhite: "纳瓦白",
navy: "藏青",
oldlace: "旧布黄",
olive: "橄榄色",
olivedrab: "草绿色",
orange: "橙色",
orangered: "橙红色",
orchid: "兰花色",
palegoldenrod: "淡金黄色",
palegreen: "淡绿色",
paleturquoise: "浅绿松石色",
palevioletred: "苍紫罗兰色",
papayawhip: "番木色",
peachpuff: "粉桃红",
peru: "秘鲁色",
pink: "粉色",
plum: "梅红色",
powderblue: "粉末蓝",
purple: "紫色",
red: "红色",
rosybrown: "褐玫瑰红",
royalblue: "宝蓝色",
saddlebrown: "鞍具棕",
salmon: "橙红色",
sandybrown: "浅褐色",
seagreen: "海绿色",
seashell: "贝壳白",
sienna: "赭色",
silver: "银色",
skyblue: "天蓝色",
slateblue: "石蓝色",
slategray: "灰石色",
slategrey: "灰石色", // same as slategray
snow: "雪白色",
springgreen: "春绿",
steelblue: "钢青色",
tan: "棕褐色",
teal: "凫蓝",
thistle: "蓟色",
tomato: "西红柿色",
transparent: "透明的",
turquoise: "绿松石色",
violet: "紫色",
wheat: "淡黄色",
white: "白色",
whitesmoke: "烟白色",
yellow: "黄色",
yellowgreen: "黄绿色"
})
);
