define(
//begin v1.x content
{
	"KES_symbol": "Ksh",
	"USD_displayName": "Dola eel Marekani",
	"TZS_displayName": "Njilingi eel Tanzania",
	"ZMW_displayName": "Njilingi eel Zambia",
	"MAD_displayName": "Njilingi eel Moroko",
	"NGN_displayName": "Njilingi eel Nijeria",
	"ZWD_displayName": "Dola eel Zimbabwe",
	"SDG_displayName": "Paunt eel Sudani",
	"MWK_displayName": "Njilingi eel Malawi",
	"KMF_displayName": "Njilingi eel Komoro",
	"SCR_displayName": "Njilingi eel Shelisheli",
	"EGP_displayName": "Njilingi eel Misri",
	"CVE_displayName": "Njilingi eel Kepuvede",
	"LYD_displayName": "Njilingi eel Libya",
	"CAD_displayName": "Njilingi eel Kanada",
	"INR_displayName": "Njilingi eel India",
	"JPY_displayName": "Njilingi eel Kijapani",
	"LRD_displayName": "Dola eel Liberia",
	"ZAR_displayName": "Njilingi eel Afrika Kusini",
	"AOA_displayName": "Njilingi eel Angola",
	"TND_displayName": "Njilingi eel Tunisia",
	"GHC_displayName": "Njilingi eel Ghana",
	"BWP_displayName": "Njilingi eel Botswana",
	"DZD_displayName": "Njilingi eel Aljeria",
	"ZMK_displayName": "Njilingi eel Zambia (1968–2012)",
	"NAD_displayName": "Njilingi eel Namibia",
	"AED_displayName": "Njilingi eel Falme za Kiarabu",
	"ETB_displayName": "Njilingi eel Uhabeshi",
	"MZM_displayName": "Njilingi eel Msumbiji",
	"BIF_displayName": "Njilingi eel Burundi",
	"RWF_displayName": "Njilingi eel Rwanda",
	"STD_displayName": "Njilingi eel Sao Tome na Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Njilingi eel Eritrea",
	"SAR_displayName": "Njilingi eel Saudia",
	"DJF_displayName": "Njilingi eel Jibuti",
	"CDF_displayName": "Njilingi eel Kongo",
	"GBP_displayName": "Njilingi eel Uingereza",
	"CHF_displayName": "Njilingi eel Uswisi",
	"MUR_displayName": "Njilingi eel Morisi",
	"SOS_displayName": "Njilingi eel Somalia",
	"BHD_displayName": "Njilingi eel Bahareni",
	"XOF_displayName": "Njilingi eel CFA BCEAO",
	"GNS_displayName": "Njilingi eel Gine",
	"SLL_displayName": "Leoni",
	"UGX_displayName": "Njilingi eel Uganda",
	"MGA_displayName": "Njilingi eel Bukini",
	"AUD_displayName": "Njilingi eel Australia",
	"KES_displayName": "Njilingi eel Kenya",
	"SHP_displayName": "Paunt eel Santahelena",
	"XAF_displayName": "Njilingi eel CFA BEAC",
	"LSL_displayName": "Njilingi eel Lesoto",
	"MRO_displayName": "Njilingi eel Moritania",
	"CNY_displayName": "Njilingi eel China",
	"GMD_displayName": "Njilingi eel Gambia"
}
//end v1.x content
);