// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"Peseta de Andorra",
	AED_displayName:"Dirém dos Emirados Árabes Unidos",
	AFA_displayName:"Afegane (1927-2002)",
	AFN_displayName:"Afegane",
	AFN_symbol:"Af",
	ALL_displayName:"Lek Albanês",
	ALL_symbol:"lek",
	AMD_displayName:"Dram Arménio",
	AMD_symbol:"dram",
	ANG_displayName:"Guilder das Antilhas Holandesas",
	ANG_symbol:"NA f.",
	AOA_displayName:"Cuanza angolano",
	AOK_displayName:"Cuanza angolano (1977-1990)",
	AON_displayName:"Novo cuanza angolano (1990-2000)",
	AOR_displayName:"Cuanza angolano reajustado (1995-1999)",
	ARA_displayName:"Austral argentino",
	ARP_displayName:"Peso argentino (1983-1985)",
	ARS_displayName:"Peso argentino",
	ARS_symbol:"Arg$",
	ATS_displayName:"Xelim austríaco",
	AUD_displayName:"Dólar australiano",
	AUD_symbol:"$A",
	AWG_displayName:"Guilder de Aruba",
	AZM_displayName:"Manat azerbaijano",
	AZN_displayName:"Manat do Azerbaijão",
	BAD_displayName:"Dinar da Bósnia-Herzegovina",
	BAM_displayName:"Marco bósnio-herzegovino conversível",
	BAM_symbol:"KM",
	BBD_displayName:"Dólar de Barbados",
	BBD_symbol:"BDS$",
	BDT_displayName:"Taka de Bangladesh",
	BDT_symbol:"Tk",
	BEC_displayName:"Franco belga (conversível)",
	BEF_displayName:"Franco belga",
	BEF_symbol:"BF",
	BEL_displayName:"Franco belga (financeiro)",
	BGL_displayName:"Lev forte búlgaro",
	BGL_symbol:"lev",
	BGN_displayName:"Lev novo búlgaro",
	BHD_displayName:"Dinar bareinita",
	BHD_symbol:"BD",
	BIF_displayName:"Franco do Burundi",
	BIF_symbol:"Fbu",
	BMD_displayName:"Dólar das Bermudas",
	BMD_symbol:"Ber$",
	BND_displayName:"Dólar do Brunei",
	BOB_displayName:"Boliviano",
	BOB_symbol:"Bs",
	BOP_displayName:"Peso boliviano",
	BOV_displayName:"Mvdol boliviano",
	BRB_displayName:"Cruzeiro novo brasileiro (1967-1986)",
	BRC_displayName:"Cruzado brasileiro",
	BRE_displayName:"Cruzeiro brasileiro (1990-1993)",
	BRL_displayName:"Real brasileiro",
	BRN_displayName:"Cruzado novo brasileiro",
	BRR_displayName:"Cruzeiro brasileiro",
	BSD_displayName:"Dólar das Bahamas",
	BTN_displayName:"Ngultrum do Butão",
	BTN_symbol:"Nu",
	BUK_displayName:"Kyat birmanês",
	BWP_displayName:"Pula botsuanesa",
	BYB_displayName:"Rublo novo bielo-russo (1994-1999)",
	BYR_displayName:"Rublo bielo-russo",
	BYR_symbol:"Rbl",
	BZD_displayName:"Dólar do Belize",
	BZD_symbol:"BZ$",
	CAD_displayName:"Dólar canadense",
	CAD_symbol:"Can$",
	CDF_displayName:"Franco congolês",
	CHE_displayName:"Euro WIR",
	CHF_displayName:"Franco suíço",
	CHF_symbol:"SwF",
	CHW_displayName:"Franco WIR",
	CLF_displayName:"Unidades de Fomento chilenas",
	CLP_displayName:"Peso chileno",
	CLP_symbol:"Ch$",
	CNY_displayName:"Yuan Renminbi chinês",
	CNY_symbol:"Y",
	COP_displayName:"Peso colombiano",
	COP_symbol:"Col$",
	COU_displayName:"Unidade de Valor Real",
	CRC_displayName:"Colon da Costa Rica",
	CRC_symbol:"C",
	CSD_displayName:"Dinar Antigo sérvio",
	CSK_displayName:"Coroa Forte checoslovaca",
	CUP_displayName:"Peso cubano",
	CVE_displayName:"Escudo cabo-verdiano",
	CVE_symbol:"CVEsc",
	CYP_displayName:"Libra cipriota",
	CYP_symbol:"£C",
	CZK_displayName:"Coroa checa",
	DDM_displayName:"Ostmark da Alemanha Oriental",
	DEM_displayName:"Marco alemão",
	DJF_displayName:"Franco do Djibuti",
	DJF_symbol:"DF",
	DKK_displayName:"Coroa dinamarquesa",
	DKK_symbol:"DKr",
	DOP_displayName:"Peso dominicano",
	DOP_symbol:"RD$",
	DZD_displayName:"Dinar argelino",
	DZD_symbol:"DA",
	ECS_displayName:"Sucre equatoriano",
	ECV_displayName:"Unidade de Valor Constante (UVC) do Equador",
	EEK_displayName:"Coroa estoniana",
	EGP_displayName:"Libra egípcia",
	EQE_displayName:"Ekwele",
	ERN_displayName:"Nakfa da Eritréia",
	ESA_displayName:"Peseta espanhola (conta A)",
	ESB_displayName:"Peseta espanhola (conta conversível)",
	ESP_displayName:"Peseta espanhola",
	ESP_symbol:"₧",
	ETB_displayName:"Birr etíope",
	EUR_displayName:"Euro",
	FIM_displayName:"Marca finlandesa",
	FJD_displayName:"Dólar de Fiji",
	FJD_symbol:"F$",
	FKP_displayName:"Libra das Malvinas",
	FRF_displayName:"Franco francês",
	GBP_displayName:"Libra esterlina britânica",
	GBP_symbol:"£",
	GEK_displayName:"Cupom Lari georgiano",
	GEL_displayName:"Lari georgiano",
	GEL_symbol:"lari",
	GHC_displayName:"Cedi de Gana (1979-2007)",
	GHS_displayName:"Cedi ganês",
	GIP_displayName:"Libra de Gibraltar",
	GMD_displayName:"Dalasi de Gâmbia",
	GNF_displayName:"Franco de Guiné",
	GNF_symbol:"GF",
	GNS_displayName:"Syli da Guiné",
	GQE_displayName:"Ekwele da Guiné Equatorial",
	GRD_displayName:"Dracma grego",
	GTQ_displayName:"Quetçal da Guatemala",
	GTQ_symbol:"Q",
	GWE_displayName:"Escudo da Guiné Portuguesa",
	GWP_displayName:"Peso da Guiné-Bissau",
	GYD_displayName:"Dólar da Guiana",
	GYD_symbol:"G$",
	HKD_displayName:"Dólar de Hong Kong",
	HKD_symbol:"HK$",
	HNL_displayName:"Lempira de Honduras",
	HNL_symbol:"L",
	HRD_displayName:"Dinar croata",
	HRK_displayName:"Kuna croata",
	HTG_displayName:"Gurde do Haiti",
	HUF_displayName:"Forinte húngaro",
	HUF_symbol:"Ft",
	IDR_displayName:"Rupia indonésia",
	IDR_symbol:"Rp",
	IEP_displayName:"Libra irlandesa",
	IEP_symbol:"IR£",
	ILP_displayName:"Libra israelita",
	ILS_displayName:"Sheqel Novo israelita",
	INR_displayName:"Rúpia indiana",
	INR_symbol:"0≤Rs.|1≤Re.|1",
	IQD_displayName:"Dinar iraquiano",
	IQD_symbol:"ID",
	IRR_displayName:"Rial iraniano",
	IRR_symbol:"RI",
	ISK_displayName:"Coroa islandesa",
	ITL_displayName:"Lira italiana",
	ITL_symbol:"₤",
	JMD_displayName:"Dólar jamaicano",
	JMD_symbol:"J$",
	JOD_displayName:"Dinar jordaniano",
	JOD_symbol:"JD",
	JPY_displayName:"Iene japonês",
	JPY_symbol:"¥",
	KES_displayName:"Xelim queniano",
	KES_symbol:"K Sh",
	KGS_displayName:"Som do Quirguistão",
	KGS_symbol:"som",
	KHR_displayName:"Riel cambojano",
	KHR_symbol:"CR",
	KMF_displayName:"Franco de Comores",
	KMF_symbol:"CF",
	KPW_displayName:"Won norte-coreano",
	KRW_displayName:"Won sul-coreano",
	KWD_displayName:"Dinar coveitiano",
	KWD_symbol:"KD",
	KYD_displayName:"Dólar das Ilhas Caiman",
	KZT_displayName:"Tenge do Cazaquistão",
	KZT_symbol:"T",
	LAK_displayName:"Kip de Laos",
	LBP_displayName:"Libra libanesa",
	LBP_symbol:"LL",
	LKR_displayName:"Rupia do Sri Lanka",
	LKR_symbol:"SL Re",
	LRD_displayName:"Dólar liberiano",
	LSL_displayName:"Loti do Lesoto",
	LSL_symbol:"M",
	LSM_displayName:"Maloti",
	LTL_displayName:"Lita lituano",
	LTT_displayName:"Talonas lituano",
	LUC_displayName:"Franco conversível de Luxemburgo",
	LUF_displayName:"Franco luxemburguês",
	LUL_displayName:"Franco financeiro de Luxemburgo",
	LVL_displayName:"Lats letão",
	LVR_displayName:"Rublo letão",
	LYD_displayName:"Dinar líbio",
	LYD_symbol:"LD",
	MAD_displayName:"Dirém marroquino",
	MAF_displayName:"Franco marroquino",
	MDL_displayName:"Leu da Moldávia",
	MGA_displayName:"Ariary de Madagascar",
	MGF_displayName:"Franco de Madagascar",
	MKD_displayName:"Dinar macedônio",
	MKD_symbol:"MDen",
	MLF_displayName:"Franco de Mali",
	MMK_displayName:"Kyat de Mianmar",
	MNT_displayName:"Tugrik mongol",
	MNT_symbol:"Tug",
	MOP_displayName:"Pataca macaense",
	MRO_displayName:"Ouguiya da Mauritânia",
	MRO_symbol:"UM",
	MTL_displayName:"Lira maltesa",
	MTL_symbol:"Lm",
	MTP_displayName:"Libra maltesa",
	MUR_displayName:"Rupia de Maurício",
	MVR_displayName:"Rupias das Ilhas Maldivas",
	MWK_displayName:"Cuacha do Maláui",
	MWK_symbol:"MK",
	MXN_displayName:"Peso mexicano",
	MXN_symbol:"MEX$",
	MXP_displayName:"Peso Prata mexicano (1861-1992)",
	MXV_displayName:"Unidade de Investimento (UDI) mexicana",
	MYR_displayName:"Ringgit malaio",
	MYR_symbol:"RM",
	MZE_displayName:"Escudo de Moçambique",
	MZM_displayName:"Metical antigo de Moçambique",
	MZM_symbol:"Mt",
	MZN_displayName:"Metical do Moçambique",
	MZN_symbol:"MTn",
	NAD_displayName:"Dólar da Namíbia",
	NAD_symbol:"N$",
	NGN_displayName:"Naira nigeriana",
	NIC_displayName:"Córdoba nicaraguense",
	NIO_displayName:"Córdoba Ouro nicaraguense",
	NLG_displayName:"Florim holandês",
	NOK_displayName:"Coroa norueguesa",
	NOK_symbol:"NKr",
	NPR_displayName:"Rupia nepalesa",
	NPR_symbol:"Nrs",
	NZD_displayName:"Dólar da Nova Zelândia",
	NZD_symbol:"$NZ",
	OMR_displayName:"Rial de Omã",
	OMR_symbol:"RO",
	PAB_displayName:"Balboa panamenho",
	PEI_displayName:"Inti peruano",
	PEN_displayName:"Sol Novo peruano",
	PES_displayName:"Sol peruano",
	PGK_displayName:"Kina da Papua-Nova Guiné",
	PHP_displayName:"Peso filipino",
	PHP_symbol:"Php",
	PKR_displayName:"Rupia paquistanesa",
	PKR_symbol:"Pra",
	PLN_displayName:"Zloti polonês",
	PLN_symbol:"Zl",
	PLZ_displayName:"Zloti polonês (1950-1995)",
	PTE_displayName:"Escudo português",
	PTE_symbol:"Esc.",
	PYG_displayName:"Guarani paraguaio",
	QAR_displayName:"Rial catariano",
	QAR_symbol:"QR",
	RHD_displayName:"Dólar rodesiano",
	ROL_displayName:"Leu romeno antigo",
	RON_displayName:"Leu romeno",
	RON_symbol:"0≤lei|1≤leu|1",
	RSD_displayName:"Dinar sérvio",
	RUB_displayName:"Rublo russo",
	RUR_displayName:"Rublo russo (1991-1998)",
	RWF_displayName:"Franco ruandês",
	SAR_displayName:"Rial saudita",
	SAR_symbol:"SRI",
	SBD_displayName:"Dólar das Ilhas Salomão",
	SBD_symbol:"SI$",
	SCR_displayName:"Rupia das Seychelles",
	SCR_symbol:"SR",
	SDD_displayName:"Dinar sudanês",
	SDG_displayName:"Libra sudanesa",
	SDP_displayName:"Libra sudanesa antiga",
	SEK_displayName:"Coroa sueca",
	SEK_symbol:"SKr",
	SGD_displayName:"Dólar de Cingapura",
	SGD_symbol:"S$",
	SHP_displayName:"Libra de Santa Helena",
	SIT_displayName:"Tolar Bons esloveno",
	SKK_displayName:"Coroa eslovaca",
	SKK_symbol:"Sk",
	SLL_displayName:"Leone de Serra Leoa",
	SOS_displayName:"Xelim somali",
	SOS_symbol:"Sh.",
	SRD_displayName:"Dólar do Suriname",
	SRG_displayName:"Florim do Suriname",
	SRG_symbol:"Sf",
	STD_displayName:"Dobra de São Tomé e Príncipe",
	STD_symbol:"Db",
	SUR_displayName:"Rublo soviético",
	SVC_displayName:"Colom salvadorenho",
	SYP_displayName:"Libra síria",
	SYP_symbol:"LS",
	SZL_displayName:"Lilangeni da Suazilândia",
	SZL_symbol:"E",
	THB_displayName:"Baht tailandês",
	TJR_displayName:"Rublo do Tadjiquistão",
	TJS_displayName:"Somoni tadjique",
	TMM_displayName:"Manat do Turcomenistão",
	TND_displayName:"Dinar tunisiano",
	TOP_displayName:"Paʻanga de Tonga",
	TOP_symbol:"T$",
	TPE_displayName:"Escudo timorense",
	TRL_displayName:"Lira turca antiga",
	TRL_symbol:"TL",
	TRY_displayName:"Lira turca",
	TTD_displayName:"Dólar de Trinidad e Tobago",
	TTD_symbol:"TT$",
	TWD_displayName:"Dólar Novo de Taiwan",
	TWD_symbol:"NT$",
	TZS_displayName:"Xelim da Tanzânia",
	TZS_symbol:"T Sh",
	UAH_displayName:"Hryvnia ucraniano",
	UAK_displayName:"Karbovanetz ucraniano",
	UGS_displayName:"Xelim ugandense (1966-1987)",
	UGX_displayName:"Xelim ugandense",
	UGX_symbol:"U Sh",
	USD_displayName:"Dólar norte-americano",
	USN_displayName:"Dólar norte-americano (Dia seguinte)",
	USS_displayName:"Dólar norte-americano (Mesmo dia)",
	UYI_displayName:"Peso uruguaio en unidades indexadas",
	UYP_displayName:"Peso uruguaio (1975-1993)",
	UYU_displayName:"Peso uruguaio",
	UYU_symbol:"Ur$",
	UZS_displayName:"Sum do Usbequistão",
	VEB_displayName:"Bolívar venezuelano",
	VEB_symbol:"Be",
	VEF_displayName:"Bolívar v enezuelano forte",
	VND_displayName:"Dong vietnamita",
	VND_symbol:"đ",
	VUV_displayName:"Vatu de Vanuatu",
	VUV_symbol:"VT",
	WST_displayName:"Tala da Samoa Ocidental",
	XAF_displayName:"Franco CFA BEAC",
	XAG_displayName:"Prata",
	XAU_displayName:"Ouro",
	XBA_displayName:"Unidade Composta Européia",
	XBB_displayName:"Unidade Monetária Européia",
	XBC_displayName:"Unidade de Conta Européia (XBC)",
	XBD_displayName:"Unidade de Conta Européia (XBD)",
	XCD_displayName:"Dólar do Caribe Oriental",
	XCD_symbol:"EC$",
	XDR_displayName:"Direitos Especiais de Giro",
	XEU_displayName:"Unidade de Moeda Européia",
	XFO_displayName:"Franco-ouro francês",
	XFU_displayName:"Franco UIC francês",
	XOF_displayName:"Franco CFA BCEAO",
	XPD_displayName:"Paládio",
	XPF_displayName:"Franco CFP",
	XPF_symbol:"CFPF",
	XPT_displayName:"Platina",
	XRE_displayName:"Fundos RINET",
	XTS_displayName:"Código de Moeda de Teste",
	XXX_displayName:"Moeda Desconhecida ou Inválida",
	YDD_displayName:"Dinar iemenita",
	YER_displayName:"Rial iemenita",
	YER_symbol:"YRl",
	YUD_displayName:"Dinar forte iugoslavo",
	YUM_displayName:"Super Dinar iugoslavo",
	YUN_displayName:"Dinar conversível iugoslavo",
	ZAL_displayName:"Rand sul-africano (financeiro)",
	ZAR_displayName:"Rand sul-africano",
	ZAR_symbol:"R",
	ZMK_displayName:"Cuacha zambiano",
	ZRN_displayName:"Zaire Novo zairense",
	ZRZ_displayName:"Zaire zairense",
	ZWD_displayName:"Dólar do Zimbábue",
	ZWD_symbol:"Z$"
})
                 