({
	"dateFormatItem-yM": "MM/yyyy", 
	"field-dayperiod": "Período do dia", 
	"dateFormatItem-yQ": "yyyy Q", 
	"field-minute": "Minuto", 
	"eraNames": [
		"Antes de Cristo", 
		"Ano do Senhor"
	], 
	"dateFormatItem-MMMEd": "EEE, d 'de' MMM", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"field-weekday": "Dia da semana", 
	"days-standAlone-wide": [
		"domingo", 
		"segunda-feira", 
		"terça-feira", 
		"quarta-feira", 
		"quinta-feira", 
		"sexta-feira", 
		"sábado"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "Era", 
	"field-hour": "Hora", 
	"quarters-standAlone-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE, d 'de' MMM 'de' yy", 
	"timeFormat-full": "HH'h'mm'min'ss's' zzzz", 
	"months-standAlone-abbr": [
		"jan", 
		"fev", 
		"mar", 
		"abr", 
		"mai", 
		"jun", 
		"jul", 
		"ago", 
		"set", 
		"out", 
		"nov", 
		"dez"
	], 
	"dateFormatItem-yMMM": "MMM 'de' y", 
	"days-standAlone-narrow": [
		"D", 
		"S", 
		"T", 
		"Q", 
		"Q", 
		"S", 
		"S"
	], 
	"eraAbbr": [
		"a.C.", 
		"d.C."
	], 
	"dateFormatItem-yyyyMM": "MM/yyyy", 
	"dateFormat-long": "d 'de' MMMM 'de' y", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-EEEd": "EEE, d", 
	"field-zone": "Fuso", 
	"dateFormatItem-Hm": "HH'h'mm", 
	"dateFormat-medium": "dd/MM/yyyy", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dayPeriods-morning-format-wide": "manhã", 
	"dateFormatItem-yyMMM": "MMM 'de' yy", 
	"quarters-standAlone-wide": [
		"1º trimestre", 
		"2º trimestre", 
		"3º trimestre", 
		"4º trimestre"
	], 
	"dateFormatItem-ms": "mm'min'ss's'", 
	"field-year": "Ano", 
	"dateFormatItem-HHmmss": "HH'h'mm'min'ss's'", 
	"dateFormatItem-yyMMMd": "d 'de' MMM 'de' yy", 
	"field-week": "Semana", 
	"months-standAlone-wide": [
		"janeiro", 
		"fevereiro", 
		"março", 
		"abril", 
		"maio", 
		"junho", 
		"julho", 
		"agosto", 
		"setembro", 
		"outubro", 
		"novembro", 
		"dezembro"
	], 
	"dateFormatItem-MMMd": "d 'de' MMM", 
	"dateFormatItem-HHmm": "HH'h'mm", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH'h'mm'min'ss's' z", 
	"months-format-abbr": [
		"jan", 
		"fev", 
		"mar", 
		"abr", 
		"mai", 
		"jun", 
		"jul", 
		"ago", 
		"set", 
		"out", 
		"nov", 
		"dez"
	], 
	"dayPeriods-afternoon-format-wide": "tarde", 
	"timeFormat-short": "HH:mm", 
	"field-month": "Mês", 
	"quarters-format-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"days-format-abbr": [
		"dom", 
		"seg", 
		"ter", 
		"qua", 
		"qui", 
		"sex", 
		"sáb"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"D", 
		"S", 
		"T", 
		"Q", 
		"Q", 
		"S", 
		"S"
	], 
	"field-second": "Segundo", 
	"field-day": "Dia", 
	"dateFormatItem-MEd": "EEE, dd/MM", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-night-format-wide": "noite", 
	"days-standAlone-abbr": [
		"dom", 
		"seg", 
		"ter", 
		"qua", 
		"qui", 
		"sex", 
		"sáb"
	], 
	"dateFormat-short": "dd/MM/yy", 
	"dateFormatItem-yMMMEd": "EEE, d 'de' MMM 'de' y", 
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y", 
	"dateFormatItem-Md": "d/M", 
	"dayPeriods-noon-format-wide": "meio-dia", 
	"dateFormatItem-yMEd": "EEE, dd/MM/yyyy", 
	"months-format-wide": [
		"janeiro", 
		"fevereiro", 
		"março", 
		"abril", 
		"maio", 
		"junho", 
		"julho", 
		"agosto", 
		"setembro", 
		"outubro", 
		"novembro", 
		"dezembro"
	], 
	"dateFormatItem-yyyyMMM": "MMM 'de' y", 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1º trimestre", 
		"2º trimestre", 
		"3º trimestre", 
		"4º trimestre"
	], 
	"days-format-wide": [
		"domingo", 
		"segunda-feira", 
		"terça-feira", 
		"quarta-feira", 
		"quinta-feira", 
		"sexta-feira", 
		"sábado"
	], 
	"eraNarrow": [
		"a.C.", 
		"d.C."
	]
})