define(
//begin v1.x content
{
	"USD_displayName": "Idolari ry'abanyamerika",
	"TZS_displayName": "Ishilingi rya Tanzaniya",
	"ZMW_displayName": "Ikwaca ryo muri Zambiya",
	"MAD_displayName": "Idiramu ryo muri Maroke",
	"NGN_displayName": "Inayira ryo muri Nijeriya",
	"ZWD_displayName": "Idolari ryo muri Zimbabwe",
	"SDG_displayName": "Ipawundi rya Sudani",
	"MWK_displayName": "Ikwaca ryo muri Malawi",
	"KMF_displayName": "Ifaranga rya Komore",
	"SCR_displayName": "Irupiya ryo mu birwa bya Sayisheli",
	"EGP_displayName": "Ipawundi rya Misiri",
	"CVE_displayName": "Irikaboveridiyano ryo muri Esikudo",
	"LYD_displayName": "Idinari rya Libiya",
	"CAD_displayName": "Idolari rya Kanada",
	"INR_displayName": "Irupiya ryo mu Buhindi",
	"BIF_symbol": "FBu",
	"JPY_displayName": "Iyeni ry'Ubuyapani",
	"LRD_displayName": "Idolari rya Liberiya",
	"ZAR_displayName": "Irandi ryo muri Afurika y'Epfo",
	"AOA_displayName": "Ikwanza ryo muri Angola",
	"TND_displayName": "Idinari ryo muri Tuniziya",
	"GHC_displayName": "Icedi ryo muri Gana",
	"BWP_displayName": "Ipula ryo muri Botswana",
	"DZD_displayName": "Idinari ryo muri Alijeriya",
	"ZMK_displayName": "Ikwaca ryo muri Zambiya (1968–2012)",
	"NAD_displayName": "Idolari rya Namibiya",
	"AED_displayName": "Idiramu ryo muri Leta Zunze Ubumwe z'Abarabu",
	"ETB_displayName": "Ibiri ryo muri Etiyopiya",
	"MZM_displayName": "Irimetikali ryo muri Mozambike",
	"BIF_displayName": "Ifaranga ry'Uburundi",
	"RWF_displayName": "Ifaranga ry'u Rwanda",
	"STD_displayName": "Idobura ryo muri Sawotome na Perensipe",
	"SZL_displayName": "Ililangeni",
	"EUR_displayName": "Iyero",
	"ERN_displayName": "Irinakufa ryo muri Eritereya",
	"SAR_displayName": "Iriyari ryo muri Arabiya Sawudite",
	"DJF_displayName": "Ifaranga ryo muri Jibuti",
	"CDF_displayName": "Ifaranga rya Kongo",
	"GBP_displayName": "Ipawundi ryo mu Bwongereza",
	"CHF_displayName": "Ifaranga ry'Ubusuwisi",
	"MUR_displayName": "Irupiya ryo mu birwa bya Morise",
	"SOS_displayName": "Ishilingi ryo muri Somaliya",
	"BHD_displayName": "Idinari ry'iribahireyini",
	"GNS_displayName": "Ifaranga ryo muri Gineya",
	"SLL_displayName": "Ilewone",
	"UGX_displayName": "Ishilingi ry'Ubugande",
	"MGA_displayName": "Iriyari ryo muri Madagasikari",
	"AUD_displayName": "Idolari ryo muri Ositaraliya",
	"KES_displayName": "Ishilingi rya Kenya",
	"SHP_displayName": "Ipawundi rya Sente Helena",
	"LSL_displayName": "Iloti ryo muro Lesoto",
	"MRO_displayName": "Ugwiya ryo muri Moritaniya",
	"CNY_displayName": "Iyuwani ryo mu Bushinwa",
	"GMD_displayName": "Idalasi ryo muri Gambiya"
}
//end v1.x content
);