define(
//begin v1.x content
{
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+-1": "last We",
	"field-year-narrow": "yr.",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "↑↑↑",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "↑↑↑",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dateFormatItem-MMMd": "MMM d",
	"field-weekdayOfMonth-narrow": "↑↑↑",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"months-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-weekOfMonth": "↑↑↑",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, MMM d, r(U)",
	"dateFormatItem-yyyyMd": "d/M/r",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "↑↑↑",
	"field-year-relative+-1": "↑↑↑",
	"field-sat-short-relative+-1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMEd": "E, d/M/r",
	"field-wed-relative+-1": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"dateFormat-long": "MMMM d, r(U)",
	"dateFormatItem-GyMMMd": "MMM d, r",
	"field-quarter": "↑↑↑",
	"field-week-short": "wk.",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"field-minute-short": "min.",
	"field-dayperiod": "a.m./p.m.",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dateFormat-medium": "MMM d, r",
	"dateFormatItem-yyyyM": "M/r",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "yr.",
	"months-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-quarter-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMd": "MMM d, r",
	"field-dayperiod-narrow": "a.m./p.m.",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateFormatItem-Md": "d/M",
	"field-hour": "↑↑↑",
	"months-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormat-full": "EEEE, MMMM d, r(U)",
	"dateFormatItem-UMd": "d/M/U",
	"field-month-relative+-1": "↑↑↑",
	"field-quarter-short": "qtr.",
	"field-sat-narrow-relative+0": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"months-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormat-short": "d/M/r",
	"field-thu-short-relative+-1": "↑↑↑",
	"field-year-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMEd": "E, MMM d, r(U)",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-MMMMd": "MMMM d",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+-1": "↑↑↑",
	"field-weekOfMonth-short": "↑↑↑",
	"field-wed-short-relative+0": "↑↑↑",
	"months-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-wed-short-relative+1": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"field-week-short-relative+0": "↑↑↑",
	"field-week-short-relative+1": "↑↑↑",
	"months-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-dayOfYear-narrow": "↑↑↑",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "↑↑↑",
	"dateFormatItem-MEd": "E, d/M",
	"field-zone-narrow": "↑↑↑",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"dateFormatItem-yMd": "d/M/r",
	"field-week": "↑↑↑",
	"dateFormatItem-Ed": "d E",
	"field-wed-narrow-relative+0": "this We",
	"field-wed-narrow-relative+1": "next We",
	"field-year-short-relative+0": "↑↑↑",
	"field-dayperiod-short": "a.m./p.m.",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"field-week-short-relative+-1": "↑↑↑",
	"dateFormatItem-UMMMd": "MMM d, U",
	"field-hour-short": "hr.",
	"field-zone-short": "↑↑↑",
	"field-month-narrow": "mo.",
	"field-hour-narrow": "hr.",
	"field-fri-narrow-relative+-1": "last Fr",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"field-mon-narrow-relative+0": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "↑↑↑",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-weekOfMonth-narrow": "↑↑↑",
	"field-weekday-narrow": "↑↑↑",
	"field-quarter-narrow": "qtr.",
	"field-sun-short-relative+-1": "↑↑↑",
	"field-day-relative+-1": "↑↑↑",
	"field-weekday-short": "↑↑↑",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "wk.",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "this Fr",
	"field-fri-narrow-relative+1": "next Fr"
}
//end v1.x content
);