define(
//begin v1.x content
{
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"dateFormatItem-Hm": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"dateFormatItem-ms": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"dateTimeFormat-short": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-week-narrow-relative+1": "↑↑↑",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-wed-narrow-relative+-1": "last We",
	"field-year-narrow": "yr.",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "↑↑↑",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "↑↑↑",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dateFormatItem-MMMd": "MMM d",
	"field-weekdayOfMonth-narrow": "↑↑↑",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQ": "↑↑↑",
	"field-weekOfMonth": "↑↑↑",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, MMM d, y G",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "↑↑↑",
	"field-year-relative+-1": "↑↑↑",
	"field-sat-short-relative+-1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMEd": "E, d/M/y GGGGG",
	"field-wed-relative+-1": "↑↑↑",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "MMMM d, y G",
	"dateFormatItem-GyMMMd": "MMM d, y G",
	"field-quarter": "↑↑↑",
	"field-week-short": "wk.",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"dateFormatItem-GyMMM": "↑↑↑",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dateFormatItem-MMM": "↑↑↑",
	"field-minute-short": "min.",
	"field-dayperiod": "a.m./p.m.",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-yyyyMMMM": "↑↑↑",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "yr.",
	"field-quarter-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMd": "MMM d, y G",
	"field-dayperiod-narrow": "a.m./p.m.",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "d/M",
	"field-hour": "↑↑↑",
	"dateFormat-full": "EEEE, MMMM d, y G",
	"field-month-relative+-1": "↑↑↑",
	"dateFormatItem-Hms": "↑↑↑",
	"field-quarter-short": "qtr.",
	"field-sat-narrow-relative+0": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"dateFormatItem-Ehm": "↑↑↑",
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "↑↑↑",
	"field-thu-short-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMEd": "E, MMM d, y G",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-MMMMd": "↑↑↑",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-E": "↑↑↑",
	"field-tue-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-H": "↑↑↑",
	"field-weekOfMonth-short": "↑↑↑",
	"dateFormatItem-yyyy": "↑↑↑",
	"dateFormatItem-M": "↑↑↑",
	"field-wed-short-relative+0": "↑↑↑",
	"field-wed-short-relative+1": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"dateTimeFormat-full": "↑↑↑",
	"dateFormatItem-hm": "↑↑↑",
	"dateFormatItem-d": "↑↑↑",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"dateFormatItem-h": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"field-week-short-relative+0": "↑↑↑",
	"field-week-short-relative+1": "↑↑↑",
	"field-dayOfYear-narrow": "↑↑↑",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "↑↑↑",
	"dateFormatItem-MEd": "E, d/M",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "↑↑↑",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"dateFormatItem-hms": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"field-week": "↑↑↑",
	"dateFormatItem-Ed": "d E",
	"field-wed-narrow-relative+0": "this We",
	"field-wed-narrow-relative+1": "next We",
	"field-year-short-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMMM": "↑↑↑",
	"field-dayperiod-short": "a.m./p.m.",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"field-week-short-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyQQQQ": "↑↑↑",
	"field-hour-short": "hr.",
	"field-zone-short": "↑↑↑",
	"field-month-narrow": "mo.",
	"field-hour-narrow": "hr.",
	"field-fri-narrow-relative+-1": "last Fr",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"dateFormatItem-Bhms": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"field-mon-narrow-relative+0": "↑↑↑",
	"dateFormatItem-EHm": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "↑↑↑",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-weekOfMonth-narrow": "↑↑↑",
	"dateFormatItem-EHms": "↑↑↑",
	"field-weekday-narrow": "↑↑↑",
	"field-quarter-narrow": "qtr.",
	"field-sun-short-relative+-1": "↑↑↑",
	"field-day-relative+-1": "↑↑↑",
	"field-weekday-short": "↑↑↑",
	"dateFormatItem-Bhm": "↑↑↑",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"dateFormatItem-Gy": "↑↑↑",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "wk.",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "this Fr",
	"field-fri-narrow-relative+1": "next Fr"
}
//end v1.x content
);