define(
//begin v1.x content
{
	"dayPeriods-standAlone-abbr-noon": "↑↑↑",
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"dateFormatItem-yw": "↑↑↑",
	"dayPeriods-format-abbr-afternoon1": "↑↑↑",
	"dateFormatItem-Hm": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"dateFormatItem-ms": "↑↑↑",
	"timeFormat-short": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"dateTimeFormat-short": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+-1": "last We",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-year-narrow": "yr.",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "↑↑↑",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "↑↑↑",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dayPeriods-format-narrow-am": "am",
	"dayPeriods-standAlone-abbr-morning1": "↑↑↑",
	"dateFormatItem-MMMd": "MMM d",
	"dayPeriods-format-narrow-morning1": "mor",
	"field-weekdayOfMonth-narrow": "↑↑↑",
	"dayPeriods-format-abbr-am": "a.m.",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"timeFormat-medium": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"months-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-standAlone-wide-noon": "↑↑↑",
	"eraNames": [
		"↑↑↑",
		"↑↑↑"
	],
	"field-weekOfMonth": "↑↑↑",
	"dayPeriods-standAlone-abbr-pm": "p.m.",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, MMM d, y G",
	"field-day": "↑↑↑",
	"dayPeriods-standAlone-wide-night1": "↑↑↑",
	"field-dayOfYear-short": "↑↑↑",
	"field-year-relative+-1": "↑↑↑",
	"dayPeriods-format-wide-am": "a.m.",
	"field-sat-short-relative+-1": "↑↑↑",
	"dayPeriods-format-narrow-afternoon1": "aft",
	"dayPeriods-format-wide-afternoon1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"field-wed-relative+-1": "↑↑↑",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"days-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-standAlone-narrow-noon": "↑↑↑",
	"dayPeriods-standAlone-wide-pm": "p.m.",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "MMMM d, y",
	"dateFormatItem-GyMMMd": "MMM d, y G",
	"dayPeriods-standAlone-abbr-midnight": "↑↑↑",
	"field-quarter": "↑↑↑",
	"field-week-short": "wk.",
	"dayPeriods-format-narrow-midnight": "mid",
	"field-day-narrow-relative+0": "↑↑↑",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"field-day-narrow-relative+1": "↑↑↑",
	"quarters-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"days-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-wide-evening1": "↑↑↑",
	"dateTimeFormats-appendItem-Timezone": "↑↑↑",
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"dateFormatItem-GyMMM": "↑↑↑",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dayPeriods-standAlone-abbr-night1": "↑↑↑",
	"dayPeriods-standAlone-narrow-afternoon1": "aft",
	"dateFormatItem-MMM": "↑↑↑",
	"field-minute-short": "min.",
	"field-dayperiod": "a.m./p.m.",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dayPeriods-format-narrow-pm": "pm",
	"dateFormat-medium": "MMM d, y",
	"eraAbbr": [
		"↑↑↑",
		"↑↑↑"
	],
	"quarters-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-abbr-pm": "p.m.",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"dayPeriods-standAlone-narrow-night1": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "yr.",
	"months-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-wide-morning1": "↑↑↑",
	"field-quarter-relative+-1": "↑↑↑",
	"field-dayperiod-narrow": "a.m./p.m.",
	"dayPeriods-standAlone-narrow-am": "a.m.",
	"field-week-narrow-relative+-1": "↑↑↑",
	"days-format-short": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"quarters-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-wide-pm": "p.m.",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "d/M",
	"field-hour": "↑↑↑",
	"dateFormatItem-yQQQQ": "↑↑↑",
	"months-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-wide-night1": "↑↑↑",
	"dateFormat-full": "EEEE, MMMM d, y",
	"field-month-relative+-1": "↑↑↑",
	"dateFormatItem-Hms": "↑↑↑",
	"field-quarter-short": "qtr.",
	"field-sat-narrow-relative+0": "↑↑↑",
	"dateFormatItem-Hmv": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"dayPeriods-format-narrow-noon": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"dateFormatItem-Ehm": "↑↑↑",
	"months-format-abbr": [
		"Jan.",
		"Feb.",
		"Mar.",
		"Apr.",
		"May",
		"Jun.",
		"Jul.",
		"Aug.",
		"Sep.",
		"Oct.",
		"Nov.",
		"Dec."
	],
	"dayPeriods-format-wide-midnight": "↑↑↑",
	"timeFormat-long": "↑↑↑",
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormatItem-yMMM": "↑↑↑",
	"dateFormat-short": "d/M/yy",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "↑↑↑",
	"dayPeriods-format-abbr-night1": "↑↑↑",
	"dateFormatItem-MMMMW": "↑↑↑",
	"field-thu-short-relative+-1": "↑↑↑",
	"days-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-MMMMd": "MMMM d",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-E": "↑↑↑",
	"dateFormatItem-H": "↑↑↑",
	"field-weekOfMonth-short": "↑↑↑",
	"field-tue-narrow-relative+-1": "↑↑↑",
	"dayPeriods-format-abbr-evening1": "↑↑↑",
	"dayPeriods-standAlone-narrow-pm": "pm",
	"dateFormatItem-M": "↑↑↑",
	"months-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-wed-short-relative+0": "↑↑↑",
	"field-wed-short-relative+1": "↑↑↑",
	"dateFormatItem-Hmsv": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"days-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateTimeFormat-full": "↑↑↑",
	"dateFormatItem-hm": "↑↑↑",
	"dateFormatItem-d": "↑↑↑",
	"field-weekday": "↑↑↑",
	"dayPeriods-standAlone-wide-evening1": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"dateFormatItem-h": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"field-week-short-relative+0": "↑↑↑",
	"months-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-hmsv": "↑↑↑",
	"field-week-short-relative+1": "↑↑↑",
	"dayPeriods-format-abbr-morning1": "↑↑↑",
	"dayPeriods-standAlone-narrow-evening1": "eve",
	"field-dayOfYear-narrow": "↑↑↑",
	"field-month-short-relative+0": "↑↑↑",
	"timeFormat-full": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "↑↑↑",
	"dateFormatItem-MEd": "E, d/M",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "↑↑↑",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"dayPeriods-standAlone-abbr-afternoon1": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"dateFormatItem-hms": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"dateFormatItem-hmv": "↑↑↑",
	"dayPeriods-format-abbr-noon": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"dateFormatItem-yMd": "d/M/y",
	"quarters-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-week": "↑↑↑",
	"quarters-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-Ed": "↑↑↑",
	"field-wed-narrow-relative+0": "this We",
	"field-wed-narrow-relative+1": "next We",
	"dayPeriods-standAlone-wide-morning1": "↑↑↑",
	"field-year-short-relative+0": "↑↑↑",
	"field-dayperiod-short": "a.m./p.m.",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"days-standAlone-short": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-week-short-relative+-1": "↑↑↑",
	"dayPeriods-standAlone-narrow-morning1": "mor",
	"dayPeriods-format-abbr-midnight": "↑↑↑",
	"field-hour-short": "hr.",
	"field-zone-short": "↑↑↑",
	"quarters-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-month-narrow": "mo.",
	"field-hour-narrow": "hr.",
	"field-fri-narrow-relative+-1": "last Fr",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"eraNarrow": [
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-Bhms": "↑↑↑",
	"dayPeriods-format-wide-noon": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"dayPeriods-standAlone-wide-afternoon1": "↑↑↑",
	"dateFormatItem-yQQQ": "↑↑↑",
	"days-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-mon-narrow-relative+0": "↑↑↑",
	"dateFormatItem-EHm": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"dayPeriods-standAlone-wide-midnight": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"dateFormatItem-yM": "M/y",
	"field-zone": "↑↑↑",
	"dateFormatItem-yMMMM": "↑↑↑",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-weekOfMonth-narrow": "↑↑↑",
	"dateFormatItem-EHms": "↑↑↑",
	"dateFormatItem-yMEd": "E, d/M/y",
	"field-weekday-narrow": "↑↑↑",
	"dayPeriods-standAlone-narrow-midnight": "mid",
	"field-quarter-narrow": "qtr.",
	"dayPeriods-standAlone-abbr-am": "a.m.",
	"field-day-relative+-1": "↑↑↑",
	"field-sun-short-relative+-1": "↑↑↑",
	"dayPeriods-format-narrow-night1": "night",
	"field-weekday-short": "↑↑↑",
	"dateFormatItem-Bhm": "↑↑↑",
	"days-format-abbr": [
		"Sun.",
		"Mon.",
		"Tue.",
		"Wed.",
		"Thu.",
		"Fri.",
		"Sat."
	],
	"dateFormatItem-MMdd": "dd/MM",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"dateFormatItem-yMMMd": "MMM d, y",
	"dateFormatItem-Gy": "↑↑↑",
	"field-era": "↑↑↑",
	"field-week-narrow": "wk.",
	"field-day-short": "↑↑↑",
	"dayPeriods-standAlone-abbr-evening1": "↑↑↑",
	"field-fri-narrow-relative+0": "this Fr",
	"dayPeriods-format-narrow-evening1": "eve",
	"field-fri-narrow-relative+1": "next Fr",
	"dayPeriods-standAlone-wide-am": "a.m."
}
//end v1.x content
);