define(
//begin v1.x content
{
	"dateTimeFormats-appendItem-Year": "{0} {1}",
	"field-tue-relative+-1": "↑↑↑",
	"field-year": "↑↑↑",
	"dateFormatItem-Hm": "↑↑↑",
	"field-wed-relative+0": "↑↑↑",
	"field-wed-relative+1": "↑↑↑",
	"dateFormatItem-ms": "↑↑↑",
	"timeFormat-short": "↑↑↑",
	"field-minute": "↑↑↑",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "↑↑↑",
	"field-tue-narrow-relative+1": "↑↑↑",
	"field-thu-short-relative+0": "↑↑↑",
	"field-day-short-relative+-1": "↑↑↑",
	"dateTimeFormat-short": "↑↑↑",
	"field-thu-short-relative+1": "↑↑↑",
	"field-day-relative+0": "↑↑↑",
	"field-day-relative+1": "↑↑↑",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+-1": "last We",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-year-narrow": "yr.",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "↑↑↑",
	"field-tue-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "↑↑↑",
	"field-tue-relative+1": "↑↑↑",
	"field-weekdayOfMonth": "↑↑↑",
	"field-second-short": "sec.",
	"dayPeriods-format-narrow-am": "am",
	"dateFormatItem-MMMd": "MMM d",
	"field-weekdayOfMonth-narrow": "↑↑↑",
	"dayPeriods-format-abbr-am": "a.m.",
	"field-week-relative+0": "↑↑↑",
	"field-month-relative+0": "↑↑↑",
	"field-week-relative+1": "↑↑↑",
	"field-month-relative+1": "↑↑↑",
	"field-sun-narrow-relative+0": "↑↑↑",
	"timeFormat-medium": "↑↑↑",
	"field-mon-short-relative+0": "↑↑↑",
	"field-sun-narrow-relative+1": "↑↑↑",
	"field-mon-short-relative+1": "↑↑↑",
	"field-second-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQ": "↑↑↑",
	"months-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"eraNames": [
		"↑↑↑"
	],
	"field-weekOfMonth": "↑↑↑",
	"dayPeriods-standAlone-abbr-pm": "p.m.",
	"field-month-short": "mo.",
	"dateFormatItem-GyMMMEd": "E, MMM d, y G",
	"dateFormatItem-yyyyMd": "y-MM-dd GGGGG",
	"field-day": "↑↑↑",
	"field-dayOfYear-short": "↑↑↑",
	"field-year-relative+-1": "↑↑↑",
	"dayPeriods-format-wide-am": "a.m.",
	"field-sat-short-relative+-1": "↑↑↑",
	"field-hour-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMEd": "↑↑↑",
	"field-wed-relative+-1": "↑↑↑",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "↑↑↑",
	"field-second": "↑↑↑",
	"days-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-standAlone-wide-pm": "p.m.",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "MMMM d, y G",
	"dateFormatItem-GyMMMd": "MMM d, y G",
	"field-quarter": "↑↑↑",
	"field-week-short": "wk.",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"quarters-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"days-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-tue-short-relative+0": "↑↑↑",
	"field-tue-short-relative+1": "↑↑↑",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "↑↑↑",
	"dateFormatItem-GyMMM": "↑↑↑",
	"field-month": "↑↑↑",
	"field-day-narrow": "↑↑↑",
	"dateFormatItem-MMM": "↑↑↑",
	"field-minute-short": "min.",
	"field-dayperiod": "a.m./p.m.",
	"field-sat-short-relative+0": "↑↑↑",
	"field-sat-short-relative+1": "↑↑↑",
	"dayPeriods-format-narrow-pm": "pm",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-yyyyMMMM": "↑↑↑",
	"eraAbbr": [
		"↑↑↑"
	],
	"quarters-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-abbr-pm": "p.m.",
	"dateFormatItem-yyyyM": "y-MM GGGG",
	"field-second-narrow": "sec.",
	"field-mon-relative+0": "↑↑↑",
	"field-mon-relative+1": "↑↑↑",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "yr.",
	"months-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-quarter-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyMMMd": "MMM d, y G",
	"field-dayperiod-narrow": "a.m./p.m.",
	"dayPeriods-standAlone-narrow-am": "a.m.",
	"field-week-narrow-relative+-1": "↑↑↑",
	"days-format-short": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"quarters-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-wide-pm": "p.m.",
	"field-dayOfYear": "↑↑↑",
	"field-sat-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "↑↑↑",
	"field-hour": "↑↑↑",
	"months-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormat-full": "↑↑↑",
	"field-month-relative+-1": "↑↑↑",
	"dateFormatItem-Hms": "↑↑↑",
	"field-quarter-short": "qtr.",
	"field-sat-narrow-relative+0": "↑↑↑",
	"field-fri-relative+0": "↑↑↑",
	"field-sat-narrow-relative+1": "↑↑↑",
	"field-fri-relative+1": "↑↑↑",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "↑↑↑",
	"field-sun-short-relative+1": "↑↑↑",
	"field-week-relative+-1": "↑↑↑",
	"dateFormatItem-Ehm": "↑↑↑",
	"months-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-quarter-relative+0": "↑↑↑",
	"field-minute-relative+0": "↑↑↑",
	"timeFormat-long": "↑↑↑",
	"field-quarter-relative+1": "↑↑↑",
	"field-wed-short-relative+-1": "↑↑↑",
	"dateFormat-short": "↑↑↑",
	"dateFormatItem-Bh": "↑↑↑",
	"field-thu-short-relative+-1": "↑↑↑",
	"field-year-narrow-relative+-1": "↑↑↑",
	"days-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-yyyyMMMEd": "E, MMM d, y G",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateTimeFormats-appendItem-Era": "{0} {1}",
	"dateFormatItem-MMMMd": "↑↑↑",
	"field-thu-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-E": "↑↑↑",
	"field-tue-narrow-relative+-1": "↑↑↑",
	"field-weekOfMonth-short": "↑↑↑",
	"dateFormatItem-H": "↑↑↑",
	"dateFormatItem-yyyy": "↑↑↑",
	"dayPeriods-standAlone-narrow-pm": "pm",
	"field-wed-short-relative+0": "↑↑↑",
	"dateFormatItem-M": "↑↑↑",
	"months-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-wed-short-relative+1": "↑↑↑",
	"field-sun-relative+-1": "↑↑↑",
	"days-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateTimeFormat-full": "↑↑↑",
	"dateFormatItem-hm": "↑↑↑",
	"dateFormatItem-d": "↑↑↑",
	"field-weekday": "↑↑↑",
	"field-day-short-relative+0": "↑↑↑",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+0": "↑↑↑",
	"field-sat-relative+1": "↑↑↑",
	"dateFormatItem-h": "↑↑↑",
	"field-week-short-relative+0": "↑↑↑",
	"field-week-short-relative+1": "↑↑↑",
	"months-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-dayOfYear-narrow": "↑↑↑",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "↑↑↑",
	"timeFormat-full": "↑↑↑",
	"dateFormatItem-MEd": "E, MM-dd",
	"field-zone-narrow": "↑↑↑",
	"dateFormatItem-y": "↑↑↑",
	"field-thu-narrow-relative+0": "↑↑↑",
	"field-sun-narrow-relative+-1": "↑↑↑",
	"field-mon-short-relative+-1": "↑↑↑",
	"field-thu-narrow-relative+1": "↑↑↑",
	"field-thu-relative+0": "↑↑↑",
	"field-thu-relative+1": "↑↑↑",
	"field-fri-short-relative+-1": "↑↑↑",
	"dateFormatItem-hms": "↑↑↑",
	"field-thu-relative+-1": "↑↑↑",
	"field-week": "↑↑↑",
	"quarters-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"quarters-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-Ed": "↑↑↑",
	"field-wed-narrow-relative+0": "this We",
	"field-wed-narrow-relative+1": "next We",
	"field-year-short-relative+0": "↑↑↑",
	"dateFormatItem-yyyyMMM": "↑↑↑",
	"field-dayperiod-short": "a.m./p.m.",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "↑↑↑",
	"field-fri-short-relative+1": "↑↑↑",
	"days-standAlone-short": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-week-short-relative+-1": "↑↑↑",
	"dateFormatItem-yyyyQQQQ": "↑↑↑",
	"field-hour-short": "hr.",
	"field-zone-short": "↑↑↑",
	"quarters-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-month-narrow": "mo.",
	"field-hour-narrow": "hr.",
	"field-fri-narrow-relative+-1": "last Fr",
	"field-year-relative+0": "↑↑↑",
	"field-year-relative+1": "↑↑↑",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "↑↑↑",
	"eraNarrow": [
		"↑↑↑"
	],
	"dateFormatItem-Bhms": "↑↑↑",
	"field-tue-short-relative+-1": "↑↑↑",
	"field-minute-narrow": "min.",
	"days-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-mon-narrow-relative+0": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"dateFormatItem-EHm": "↑↑↑",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "↑↑↑",
	"dateFormatItem-MMMEd": "↑↑↑",
	"field-weekOfMonth-narrow": "↑↑↑",
	"dateFormatItem-EHms": "↑↑↑",
	"field-weekday-narrow": "↑↑↑",
	"field-quarter-narrow": "qtr.",
	"field-sun-short-relative+-1": "↑↑↑",
	"field-day-relative+-1": "↑↑↑",
	"dayPeriods-standAlone-abbr-am": "a.m.",
	"field-weekday-short": "↑↑↑",
	"days-format-abbr": [
		"Sun.",
		"Mon.",
		"Tue.",
		"Wed.",
		"Thu.",
		"Fri.",
		"Sat."
	],
	"dateFormatItem-Bhm": "↑↑↑",
	"field-sun-relative+0": "↑↑↑",
	"field-sun-relative+1": "↑↑↑",
	"dateFormatItem-Gy": "↑↑↑",
	"field-day-short": "↑↑↑",
	"field-week-narrow": "wk.",
	"field-era": "↑↑↑",
	"field-fri-narrow-relative+0": "this Fr",
	"field-fri-narrow-relative+1": "next Fr",
	"dayPeriods-standAlone-wide-am": "a.m."
}
//end v1.x content
);