define(
//begin v1.x content
{
	"field-quarter-short-relative+0": "detta kv.",
	"field-quarter-short-relative+1": "nästa kv.",
	"field-tue-relative+-1": "tisdag förra veckan",
	"field-year": "år",
	"field-wed-relative+0": "onsdag denna vecka",
	"field-wed-relative+1": "onsdag nästa vecka",
	"timeFormat-short": "HH.mm",
	"field-minute": "minut",
	"field-month-narrow-relative+-1": "förra mån.",
	"field-tue-narrow-relative+0": "denna tis.",
	"field-tue-narrow-relative+1": "nästa tis.",
	"field-thu-short-relative+0": "tors. denna vecka",
	"field-day-short-relative+-1": "i går",
	"dateTimeFormat-short": "↑↑↑",
	"field-thu-short-relative+1": "tors. nästa vecka",
	"field-day-relative+0": "i dag",
	"field-day-short-relative+-2": "i förrgår",
	"field-day-relative+1": "i morgon",
	"field-week-narrow-relative+0": "denna v.",
	"field-day-relative+2": "i övermorgon",
	"field-week-narrow-relative+1": "nästa v.",
	"field-wed-narrow-relative+-1": "förra ons.",
	"field-year-narrow": "år",
	"field-era-short": "era",
	"field-year-narrow-relative+0": "i år",
	"field-tue-relative+0": "tisdag denna vecka",
	"field-year-narrow-relative+1": "nästa år",
	"field-tue-relative+1": "tisdag nästa vecka",
	"field-weekdayOfMonth": "veckodag i månad",
	"field-second-short": "sek",
	"dayPeriods-format-narrow-am": "fm",
	"dateFormatItem-yyyyMM": "y-MM G",
	"dateFormatItem-MMMd": "↑↑↑",
	"field-weekdayOfMonth-narrow": "veckodag i mån.",
	"dayPeriods-format-abbr-am": "fm",
	"field-week-relative+0": "denna vecka",
	"field-month-relative+0": "denna månad",
	"field-week-relative+1": "nästa vecka",
	"field-month-relative+1": "nästa månad",
	"field-sun-narrow-relative+0": "denna sön.",
	"timeFormat-medium": "HH.mm.ss",
	"field-mon-short-relative+0": "mån. denna vecka",
	"field-sun-narrow-relative+1": "nästa sön.",
	"field-mon-short-relative+1": "mån. nästa vecka",
	"field-second-relative+0": "nu",
	"dateFormatItem-yyyyQQQ": "↑↑↑",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"eraNames": [
		"Buddhistisk era"
	],
	"field-weekOfMonth": "vecka i månaden",
	"dayPeriods-standAlone-abbr-pm": "e.m.",
	"field-month-short": "m",
	"dateFormatItem-GyMMMEd": "↑↑↑",
	"dateFormatItem-yyyyMd": "↑↑↑",
	"field-day": "dag",
	"field-dayOfYear-short": "dag under året",
	"field-year-relative+-1": "i fjol",
	"dayPeriods-format-wide-am": "fm",
	"field-sat-short-relative+-1": "lör. förra veckan",
	"field-hour-relative+0": "denna timme",
	"dateFormatItem-yyyyMEd": "↑↑↑",
	"field-second-short-relative+0": "nu",
	"field-wed-relative+-1": "onsdag förra veckan",
	"dateTimeFormat-medium": "↑↑↑",
	"field-sat-narrow-relative+-1": "förra lör.",
	"field-second": "sekund",
	"days-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"O",
		"↑↑↑",
		"↑↑↑",
		"L"
	],
	"dayPeriods-standAlone-wide-pm": "eftermiddag",
	"dateFormat-long": "↑↑↑",
	"dateFormatItem-GyMMMd": "↑↑↑",
	"field-hour-short-relative+0": "denna timme",
	"field-quarter": "kvartal",
	"field-week-short": "v",
	"field-day-narrow-relative+0": "idag",
	"field-day-narrow-relative+1": "imorgon",
	"field-day-narrow-relative+2": "i övermorgon",
	"quarters-standAlone-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"days-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"O",
		"↑↑↑",
		"↑↑↑",
		"L"
	],
	"field-tue-short-relative+0": "tis. denna vecka",
	"field-tue-short-relative+1": "tis. nästa vecka",
	"field-month-short-relative+-1": "förra mån.",
	"field-mon-relative+-1": "måndag förra veckan",
	"dateFormatItem-GyMMM": "↑↑↑",
	"field-month": "månad",
	"field-day-narrow": "dag",
	"dateFormatItem-MMM": "↑↑↑",
	"field-minute-short": "min",
	"field-dayperiod": "fm/em",
	"field-sat-short-relative+0": "lör. denna vecka",
	"field-sat-short-relative+1": "lör. nästa vecka",
	"dayPeriods-format-narrow-pm": "em",
	"dateFormat-medium": "↑↑↑",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"eraAbbr": [
		"BE"
	],
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"dayPeriods-format-abbr-pm": "em",
	"dateFormatItem-yyyyM": "↑↑↑",
	"field-second-narrow": "s",
	"dateFormatItem-MMd": "↑↑↑",
	"field-mon-relative+0": "måndag denna vecka",
	"field-mon-relative+1": "måndag nästa vecka",
	"field-day-narrow-relative+-1": "igår",
	"field-year-short": "år",
	"field-day-narrow-relative+-2": "i förrgår",
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-quarter-relative+-1": "förra kvartalet",
	"dateFormatItem-yyyyMMMd": "↑↑↑",
	"field-dayperiod-narrow": "fm/em",
	"dayPeriods-standAlone-narrow-am": "fm",
	"field-week-narrow-relative+-1": "förra v.",
	"days-format-short": [
		"sö",
		"må",
		"ti",
		"on",
		"to",
		"fr",
		"lö"
	],
	"dayPeriods-format-wide-pm": "em",
	"field-dayOfYear": "dag under året",
	"field-sat-relative+-1": "lördag förra veckan",
	"dateTimeFormat-long": "↑↑↑",
	"dateFormatItem-Md": "↑↑↑",
	"field-minute-narrow-relative+0": "denna minut",
	"field-hour": "timme",
	"months-format-wide": [
		"januari",
		"februari",
		"mars",
		"april",
		"maj",
		"juni",
		"juli",
		"augusti",
		"september",
		"oktober",
		"november",
		"december"
	],
	"dateFormat-full": "↑↑↑",
	"field-month-relative+-1": "förra månaden",
	"field-quarter-short": "kv.",
	"field-sat-narrow-relative+0": "denna lör.",
	"field-fri-relative+0": "fredag denna vecka",
	"field-sat-narrow-relative+1": "nästa lör.",
	"field-fri-relative+1": "fredag nästa vecka",
	"field-month-narrow-relative+0": "denna mån.",
	"field-month-narrow-relative+1": "nästa mån.",
	"field-sun-short-relative+0": "sön. denna vecka",
	"field-sun-short-relative+1": "sön. nästa vecka",
	"field-week-relative+-1": "förra veckan",
	"field-quarter-short-relative+-1": "förra kv.",
	"field-minute-short-relative+0": "denna minut",
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"maj",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"field-quarter-relative+0": "detta kvartal",
	"field-minute-relative+0": "denna minut",
	"timeFormat-long": "HH.mm.ss z",
	"field-quarter-relative+1": "nästa kvartal",
	"field-wed-short-relative+-1": "ons. förra veckan",
	"dateFormat-short": "y-MM-dd G",
	"field-thu-short-relative+-1": "tors. förra veckan",
	"field-year-narrow-relative+-1": "i fjol",
	"days-standAlone-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	],
	"dateFormatItem-yyyyMMMEd": "↑↑↑",
	"field-mon-narrow-relative+-1": "↑↑↑",
	"dateFormatItem-MMMMd": "↑↑↑",
	"field-thu-narrow-relative+-1": "förra tors.",
	"dateFormatItem-E": "↑↑↑",
	"field-weekOfMonth-short": "vk. i mån.",
	"field-tue-narrow-relative+-1": "förra tis.",
	"dateFormatItem-yyyy": "↑↑↑",
	"dayPeriods-standAlone-narrow-pm": "em",
	"dateFormatItem-M": "↑↑↑",
	"field-wed-short-relative+0": "ons. denna vecka",
	"months-standAlone-wide": [
		"januari",
		"februari",
		"mars",
		"april",
		"maj",
		"juni",
		"juli",
		"augusti",
		"september",
		"oktober",
		"november",
		"december"
	],
	"field-wed-short-relative+1": "ons. nästa vecka",
	"field-sun-relative+-1": "söndag förra veckan",
	"dateFormatItem-MMMMEd": "↑↑↑",
	"days-standAlone-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"dateTimeFormat-full": "↑↑↑",
	"field-second-narrow-relative+0": "nu",
	"dateFormatItem-d": "↑↑↑",
	"field-weekday": "veckodag",
	"field-day-short-relative+0": "i dag",
	"field-quarter-narrow-relative+0": "detta kv.",
	"field-day-short-relative+1": "i morgon",
	"field-sat-relative+0": "lördag denna vecka",
	"field-quarter-narrow-relative+1": "nästa kv.",
	"field-day-short-relative+2": "i övermorgon",
	"field-sat-relative+1": "lördag nästa vecka",
	"field-week-short-relative+0": "denna v.",
	"field-week-short-relative+1": "nästa v.",
	"months-standAlone-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"maj",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"field-dayOfYear-narrow": "dag under året",
	"field-month-short-relative+0": "denna mån.",
	"field-month-short-relative+1": "nästa mån.",
	"field-weekdayOfMonth-short": "veckodag i mån.",
	"timeFormat-full": "'kl'. HH.mm.ss zzzz",
	"dateFormatItem-MEd": "↑↑↑",
	"field-zone-narrow": "tidszon",
	"dateFormatItem-y": "↑↑↑",
	"field-thu-narrow-relative+0": "denna tors.",
	"field-sun-narrow-relative+-1": "förra sön.",
	"field-mon-short-relative+-1": "mån. förra veckan",
	"field-thu-narrow-relative+1": "nästa tors.",
	"field-thu-relative+0": "torsdag denna vecka",
	"field-thu-relative+1": "torsdag nästa vecka",
	"field-fri-short-relative+-1": "fre. förra veckan",
	"field-thu-relative+-1": "torsdag förra veckan",
	"field-week": "vecka",
	"quarters-format-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"dateFormatItem-Ed": "↑↑↑",
	"field-wed-narrow-relative+0": "denna ons.",
	"field-wed-narrow-relative+1": "nästa ons.",
	"field-quarter-narrow-relative+-1": "förra kv.",
	"field-year-short-relative+0": "i år",
	"dateFormatItem-yyyyMMM": "↑↑↑",
	"field-dayperiod-short": "fm/em",
	"field-year-short-relative+1": "nästa år",
	"field-fri-short-relative+0": "fre. denna vecka",
	"field-fri-short-relative+1": "fre. nästa vecka",
	"days-standAlone-short": [
		"sö",
		"må",
		"ti",
		"on",
		"to",
		"fr",
		"lö"
	],
	"field-week-short-relative+-1": "förra v.",
	"field-hour-narrow-relative+0": "denna timme",
	"dateFormatItem-yyyyQQQQ": "↑↑↑",
	"field-hour-short": "tim",
	"field-zone-short": "tidszon",
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"field-month-narrow": "mån",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "förra fre.",
	"field-year-relative+0": "i år",
	"field-year-relative+1": "nästa år",
	"field-era-narrow": "era",
	"field-fri-relative+-1": "fredag förra veckan",
	"eraNarrow": "BE",
	"field-tue-short-relative+-1": "tis. förra veckan",
	"field-minute-narrow": "m",
	"days-format-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	],
	"field-mon-narrow-relative+0": "↑↑↑",
	"field-mon-narrow-relative+1": "↑↑↑",
	"field-year-short-relative+-1": "i fjol",
	"field-zone": "tidszon",
	"dateFormatItem-MMMEd": "↑↑↑",
	"field-weekOfMonth-narrow": "vk.i mån.",
	"field-weekday-narrow": "veckodag",
	"field-quarter-narrow": "kv.",
	"field-sun-short-relative+-1": "sön. förra veckan",
	"field-day-relative+-1": "i går",
	"dayPeriods-standAlone-abbr-am": "f.m.",
	"field-day-relative+-2": "i förrgår",
	"field-weekday-short": "veckodag",
	"days-format-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"field-sun-relative+0": "söndag denna vecka",
	"dateFormatItem-MMdd": "d/M",
	"field-sun-relative+1": "söndag nästa vecka",
	"dateFormatItem-Gy": "↑↑↑",
	"field-day-short": "dag",
	"field-week-narrow": "v",
	"field-era": "era",
	"field-fri-narrow-relative+0": "denna fre.",
	"field-fri-narrow-relative+1": "nästa fre.",
	"dayPeriods-standAlone-wide-am": "förmiddag"
}
//end v1.x content
);