define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMM": "G y-MM",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d/M",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "G y-MM-dd",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMEd": "E d:'e' MMMM",
	"dateFormatItem-yyyyMEd": "E, y-MM-dd G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "d:'e' MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyQQQ": "G y QQQ",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "G y-MM-dd",
	"dateFormatItem-yyyyM": "G y-MM",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);