define(
//begin v1.x content
{
	"dateFormatItem-yM": "yyyy-MM",
	"field-dayperiod": "fm/em",
	"dayPeriods-format-wide-pm": "em",
	"dateFormatItem-yQ": "yyyy Q",
	"field-minute": "minut",
	"eraNames": [
		"före Kristus",
		"efter Kristus"
	],
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "i går",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "i förrgår",
	"field-weekday": "veckodag",
	"field-day-relative+-3": "i förrförrgår",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-format-wide-am": "fm",
	"field-era": "era",
	"field-hour": "timme",
	"dateFormatItem-y": "y",
	"timeFormat-full": "'kl'. HH:mm:ss zzzz",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "i dag",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"field-day-relative+1": "i morgon",
	"eraAbbr": [
		"f.Kr.",
		"e.Kr."
	],
	"field-day-relative+2": "i övermorgon",
	"field-day-relative+3": "i överövermorgon",
	"dateFormatItem-yyyyMM": "yyyy-MM",
	"dateFormat-long": "d MMMM y",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-EEEd": "EEE d",
	"field-zone": "tidszon",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d/M",
	"dateFormat-medium": "d MMM y",
	"dateFormatItem-yyMM": "yy-MM",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM -yy",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y",
	"field-year": "år",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-week": "vecka",
	"dateFormatItem-MMMMEEEd": "EEE d MMMM",
	"dateFormatItem-MMMMEd": "E d:'e' MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"maj",
		"jun",
		"jul",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"timeFormat-short": "HH:mm",
	"field-month": "månad",
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"dateFormatItem-MMMMd": "d:'e' MMMM",
	"days-format-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"dateFormatItem-M": "L",
	"field-second": "sekund",
	"field-day": "dag",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "yyyy-MM-dd",
	"dateFormatItem-yMMMEd": "EEE d MMM y",
	"dateFormat-full": "EEEE'en' 'den' d:'e' MMMM y",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "EEE, yyyy-MM-dd",
	"months-format-wide": [
		"januari",
		"februari",
		"mars",
		"april",
		"maj",
		"juni",
		"juli",
		"augusti",
		"september",
		"oktober",
		"november",
		"december"
	],
	"dateFormatItem-yyyyMMM": "MMM y",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"days-format-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	]
}
//end v1.x content
);