define(
//begin v1.x content
{
	"USD_displayName": "heleri sa Marekani",
	"TZS_displayName": "heleri sa Tanzania",
	"ZMW_displayName": "heleri sa Zambia",
	"MAD_displayName": "heleri sa Moroko",
	"NGN_displayName": "heleri sa Nijeria",
	"ZWD_displayName": "heleri sa Zimbabwe",
	"SDG_displayName": "heleri sa Sudani",
	"MWK_displayName": "heleri sa Malawi",
	"KMF_displayName": "heleri sa Komoro",
	"SCR_displayName": "heleri sa Shelisheli",
	"EGP_displayName": "heleri sa Misri",
	"CVE_displayName": "heleri sa Kepuvede",
	"LYD_displayName": "heleri sa Libya",
	"CAD_displayName": "heleri sa Kanada",
	"INR_displayName": "heleri sa India",
	"JPY_displayName": "heleri sa Japani",
	"TZS_symbol": "TSh",
	"LRD_displayName": "heleri sa Liberia",
	"ZAR_displayName": "heleri sa Afrika Kusini",
	"AOA_displayName": "heleri sa Angola",
	"TND_displayName": "heleri sa Tunisia",
	"GHC_displayName": "heleri sa Ghana",
	"BWP_displayName": "heleri sa Botswana",
	"DZD_displayName": "heleri sa Aljeria",
	"ZMK_displayName": "heleri sa Zambia (1968–2012)",
	"NAD_displayName": "heleri sa Namibia",
	"AED_displayName": "heleri sa Falme za Kiarabu",
	"ETB_displayName": "heleri sa Uhabeshi",
	"MZM_displayName": "heleri sa Msumbiji",
	"BIF_displayName": "heleri sa Burundi",
	"RWF_displayName": "heleri sa Rwanda",
	"STD_displayName": "heleri sa Sao Tome na Principe",
	"SZL_displayName": "lilangeni",
	"EUR_displayName": "yuro",
	"ERN_displayName": "heleri sa Eritrea",
	"SAR_displayName": "heleri sa Saudia",
	"DJF_displayName": "heleri sa Jibuti",
	"CDF_displayName": "heleri sa Kongo",
	"GBP_displayName": "heleri sa Uingereza",
	"CHF_displayName": "heleri sa Uswisi",
	"MUR_displayName": "heleri sa Morisi",
	"SOS_displayName": "heleri sa Somalia",
	"BHD_displayName": "heleri sa Bahareni",
	"XOF_displayName": "heleri sa CFA BCEAO",
	"GNS_displayName": "heleri sa Gine",
	"SLL_displayName": "leoni",
	"UGX_displayName": "heleri sa Uganda",
	"MGA_displayName": "heleri sa Bukini",
	"AUD_displayName": "heleri sa Australia",
	"KES_displayName": "heleri sa Kenya",
	"SHP_displayName": "heleri sa Santahelena",
	"XAF_displayName": "heleri sa CFA BEAC",
	"LSL_displayName": "heleri sa Lesoto",
	"MRO_displayName": "heleri sa Moritania",
	"CNY_displayName": "heleri sa China",
	"GMD_displayName": "heleri sa Gambia"
}
//end v1.x content
);