define(
//begin v1.x content
{
	"USD_displayName": "dolar amerikin",
	"TZS_displayName": "shiling tanzanien",
	"ZMW_displayName": "kwacha zanbien",
	"MAD_displayName": "dirham marokin",
	"NGN_displayName": "naira nizerian",
	"ZWD_displayName": "dolar zimbawe",
	"SDG_displayName": "dinar soudane",
	"MWK_displayName": "kwacha malawit",
	"KMF_displayName": "fran komorien",
	"SCR_displayName": "roupi seselwa",
	"EGP_displayName": "liv ezipsien",
	"CVE_displayName": "eskudo kapverdien",
	"LYD_displayName": "dinar libien",
	"CAD_displayName": "dolar kanadien",
	"INR_displayName": "roupi",
	"JPY_displayName": "yen zapone",
	"LRD_displayName": "dolar liberien",
	"ZAR_displayName": "rand sid-afrikin",
	"AOA_displayName": "kwanza angole",
	"TND_displayName": "dinar tinizien",
	"GHC_displayName": "sedi ganeen",
	"BWP_displayName": "pula ya botswane",
	"DZD_displayName": "dinar alzerien",
	"ZMK_displayName": "kwacha zanbien (1968–2012)",
	"NAD_displayName": "dolar namibien",
	"AED_displayName": "dirham Emira arab ini",
	"ETB_displayName": "birr etiopien",
	"MZM_displayName": "metikal mozanbikin",
	"BIF_displayName": "fran burunde",
	"RWF_displayName": "fran rwande",
	"STD_displayName": "dobra santomeen",
	"SZL_displayName": "lilangeni swazi",
	"EUR_displayName": "euro",
	"ERN_displayName": "nafka erythreen",
	"SAR_displayName": "rial saoudien",
	"DJF_displayName": "fran djiboutien",
	"CDF_displayName": "fran kongole",
	"GBP_displayName": "liv sterlin",
	"CHF_displayName": "fran swis",
	"MUR_displayName": "roupi morisien",
	"SOS_displayName": "shilingi somalien",
	"BHD_displayName": "dinar bahreïn",
	"XOF_displayName": "fran CFA (BCEAO)",
	"GNS_displayName": "fran gineen",
	"SLL_displayName": "leonn Sierra-Leone",
	"UGX_displayName": "shiling ougande",
	"MGA_displayName": "fran malgas",
	"SDP_displayName": "liv soudane",
	"AUD_displayName": "dolar ostralien",
	"KES_displayName": "shiling kenyan",
	"SHP_displayName": "liv Sainte-Hélène",
	"MUR_symbol": "Rs",
	"XAF_displayName": "fran CFA (BEAC)",
	"LSL_displayName": "loti lezoto",
	"MRO_displayName": "ouguiya moritanien",
	"CNY_displayName": "yuan renminbi sinwa",
	"GMD_displayName": "dalasi gambien"
}
//end v1.x content
);