define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Peryod dan lazourne",
	"field-minute": "Minit",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Yer",
	"field-weekday": "Zour lasemenn",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "Lepok",
	"field-hour": "Ler",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Zordi",
	"field-day-relative+1": "Demin",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Peryod letan",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Lane",
	"field-week": "Semenn",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Mwa",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Segonn",
	"field-day": "Zour",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);