define(
//begin v1.x content
{
	"dateFormatItem-GyMMM": "MMM U",
	"dateFormat-medium": "d MMM U",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MEd": "E d-M",
	"dateFormatItem-yyyyMMM": "MMM U",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-H": "HH",
	"dateFormatItem-GyMMMd": "d MMM U",
	"dateFormatItem-y": "U",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yyyyQQQQ": "QQQQ U",
	"dateFormatItem-GyMMMEd": "E d MMM U",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "E d MMM U",
	"dateFormatItem-yyyyMEd": "E d-M-y",
	"dateFormatItem-yyyyMMMM": "MMMM U",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-yyyy": "U",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "d MMMM U",
	"dateFormatItem-yyyyQQQ": "QQQ U",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "dd-MM-yy",
	"dateFormatItem-Gy": "U",
	"dateFormatItem-d": "d",
	"dateFormatItem-yyyyMMMd": "d MMM U",
	"dateFormatItem-h": "h a",
	"dateFormatItem-yyyyM": "M-y",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "EEEE d MMMM U",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyyyMd": "d-M-y",
	"dateFormatItem-Ed": "E d"
}
//end v1.x content
);