({
	"dateFormatItem-yM": "M-y", 
	"field-dayperiod": "AM/PM", 
	"dayPeriods-format-wide-pm": "PM", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-minute": "Minuut", 
	"eraNames": [
		"Voor Christus", 
		"na Christus"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "gisteren", 
	"dateFormatItem-MMdd": "dd-MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-day-relative+-2": "eergisteren", 
	"field-weekday": "Dag van de week", 
	"field-day-relative+-3": "eereergisteren", 
	"days-standAlone-wide": [
		"zondag", 
		"maandag", 
		"dinsdag", 
		"woensdag", 
		"donderdag", 
		"vrijdag", 
		"zaterdag"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "AM", 
	"field-era": "Tijdperk", 
	"field-hour": "Uur", 
	"quarters-standAlone-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"jan.", 
		"feb.", 
		"mrt.", 
		"apr.", 
		"mei", 
		"jun.", 
		"jul.", 
		"aug.", 
		"sep.", 
		"okt.", 
		"nov.", 
		"dec."
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "vandaag", 
	"days-standAlone-narrow": [
		"Z", 
		"M", 
		"D", 
		"W", 
		"D", 
		"V", 
		"Z"
	], 
	"field-day-relative+1": "morgen", 
	"eraAbbr": [
		"v. Chr.", 
		"n. Chr."
	], 
	"field-day-relative+2": "overmorgen", 
	"field-day-relative+3": "overovermorgen", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Zone", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormatItem-MMd": "d-MM", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-yyMM": "MM-yy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"dateFormatItem-yyQQQQ": "QQQQ yy", 
	"quarters-standAlone-wide": [
		"1e kwartaal", 
		"2e kwartaal", 
		"3e kwartaal", 
		"4e kwartaal"
	], 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Jaar", 
	"field-week": "Week", 
	"months-standAlone-wide": [
		"januari", 
		"februari", 
		"maart", 
		"april", 
		"mei", 
		"juni", 
		"juli", 
		"augustus", 
		"september", 
		"oktober", 
		"november", 
		"december"
	], 
	"dateFormatItem-MMMd": "d-MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"jan.", 
		"feb.", 
		"mrt.", 
		"apr.", 
		"mei", 
		"jun.", 
		"jul.", 
		"aug.", 
		"sep.", 
		"okt.", 
		"nov.", 
		"dec."
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Maand", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"days-format-abbr": [
		"zo", 
		"ma", 
		"di", 
		"wo", 
		"do", 
		"vr", 
		"za"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"Z", 
		"M", 
		"D", 
		"W", 
		"D", 
		"V", 
		"Z"
	], 
	"field-second": "Seconde", 
	"field-day": "Dag", 
	"dateFormatItem-MEd": "E d-M", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"zo", 
		"ma", 
		"di", 
		"wo", 
		"do", 
		"vr", 
		"za"
	], 
	"dateFormat-short": "dd-MM-yy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d-M", 
	"dateFormatItem-yMEd": "EEE d-M-y", 
	"months-format-wide": [
		"januari", 
		"februari", 
		"maart", 
		"april", 
		"mei", 
		"juni", 
		"juli", 
		"augustus", 
		"september", 
		"oktober", 
		"november", 
		"december"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1e kwartaal", 
		"2e kwartaal", 
		"3e kwartaal", 
		"4e kwartaal"
	], 
	"days-format-wide": [
		"zondag", 
		"maandag", 
		"dinsdag", 
		"woensdag", 
		"donderdag", 
		"vrijdag", 
		"zaterdag"
	], 
	"eraNarrow": [
		"v. Chr.", 
		"n. Chr."
	]
})