define(
//begin v1.x content
{
	"USD_displayName": "Dola yase Amelika",
	"TZS_displayName": "Shilingi yase Tanzaniya",
	"ZMW_displayName": "Kwacha yase Zambiya",
	"MAD_displayName": "Dirham yase Morokho",
	"NGN_displayName": "Nayira yase Nijeriya",
	"ZWD_displayName": "Dola yase Zimbabwe",
	"SDG_displayName": "Dinari yase Sudani",
	"MWK_displayName": "Kwacha yase Malawi",
	"KMF_displayName": "Fulenki yase Khomoro",
	"SCR_displayName": "Rupi yase Seyisheli",
	"EGP_displayName": "Phawundi laseGibhide",
	"CVE_displayName": "Escudo Caboverdiano",
	"LYD_displayName": "Dinari yase Libya",
	"CAD_displayName": "Dola yase Khanada",
	"INR_displayName": "Rupi yase Indiya",
	"JPY_displayName": "Yeni yase Japhani",
	"LRD_displayName": "Dola yase Libheriya",
	"ZAR_displayName": "Randi yase Afrika ye Zanzi",
	"AOA_displayName": "Kwanza yase Angola",
	"TND_displayName": "Dinari yase Tunisiya",
	"GHC_displayName": "Sedi yase Ghana",
	"BWP_displayName": "Phula yase Botswana",
	"DZD_displayName": "Dinali yase Aljeriya",
	"ZMK_displayName": "Kwacha yase Zambiya (1968–2012)",
	"NAD_displayName": "Dola yase Namibiya",
	"AED_displayName": "Dola laseArab",
	"ETB_displayName": "Dola laseEthiopia",
	"MZM_displayName": "Metikali yase Mozambiki",
	"BIF_displayName": "Fulenki yase Bhurundi",
	"RWF_displayName": "Fulenki yase Ruwanda",
	"STD_displayName": "Dobra yase Sao Tome lo Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakfa yase Eritrea",
	"SAR_displayName": "Riyal yase Saudi",
	"DJF_displayName": "Fulenki yase Jibhuthi",
	"CDF_displayName": "Fulenki yase Khongo",
	"GBP_displayName": "Phawundi yase Ngilandi",
	"CHF_displayName": "Fulenki yase Swisi",
	"MUR_displayName": "Rupi yase Morishasi",
	"SOS_displayName": "Shilingi yase Somaliya",
	"BHD_displayName": "Dinari yase Bhahareni",
	"XOF_displayName": "Fulenki CFA BCEAO",
	"GNS_displayName": "Fulenki yase Gine",
	"SLL_displayName": "Leyoni",
	"UGX_displayName": "Shilingi yase Uganda",
	"MGA_displayName": "Fulenki yase Malagasi",
	"SDP_displayName": "Phawundi yase Sudani",
	"AUD_displayName": "Dola yase Australia",
	"KES_displayName": "Shilingi yase Kenya",
	"SHP_displayName": "Phawundindi laseSt Helena",
	"XAF_displayName": "Fulenki CFA BEAC",
	"LSL_displayName": "Lothi yase Lesotho",
	"MRO_displayName": "Ugwiya yase Moritaniya",
	"CNY_displayName": "Yuan Renminbi yase China",
	"GMD_displayName": "Dalasi yase Gambia"
}
//end v1.x content
);