define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-minute": "Umuzuzu",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Izolo",
	"field-weekday": "Ilanga leviki",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-hour": "Ihola",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Lamuhla",
	"field-day-relative+1": "Kusasa",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Isikhathi",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Umnyaka",
	"field-week": "Iviki",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Inyangacale",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "Isekendi",
	"field-day": "Ilanga",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);