define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} - {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} - {0}",
	"dateTimeFormat-medium": "{1} - {0}",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-ms": "mm:ss",
	"dateTimeFormat-long": "{1} - {0}",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-HHmm": "HH:mm",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);