({
	"field-dayperiod": "ΠΜ/ΜΜ", 
	"field-minute": "Λεπτό", 
	"eraNames": [
		"π.Χ.", 
		"μ.Χ."
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"dateFormatItem-MMdd": "dd/MM", 
	"field-weekday": "Ημέρα Εβδομάδας", 
	"days-standAlone-wide": [
		"Κυριακή", 
		"Δευτέρα", 
		"Τρίτη", 
		"Τετάρτη", 
		"Πέμπτη", 
		"Παρασκευή", 
		"Σάββατο"
	], 
	"patternChars": "GanjkHmsSEDFwWxhKzAeugXZvcL", 
	"months-standAlone-narrow": [
		"Ι", 
		"Φ", 
		"Μ", 
		"Α", 
		"Μ", 
		"Ι", 
		"Ι", 
		"Α", 
		"Σ", 
		"Ο", 
		"Ν", 
		"Δ"
	], 
	"field-era": "Περίοδος", 
	"field-hour": "Ώρα", 
	"quarters-standAlone-abbr": [
		"Τ1", 
		"Τ2", 
		"Τ3", 
		"Τ4"
	], 
	"timeFormat-full": "h:mm:ss a v", 
	"dateFormatItem-yyyy": "yyyy", 
	"months-standAlone-abbr": [
		"Ιαν", 
		"Φεβ", 
		"Μαρ", 
		"Απρ", 
		"Μαϊ", 
		"Ιουν", 
		"Ιουλ", 
		"Αυγ", 
		"Σεπ", 
		"Οκτ", 
		"Νοε", 
		"Δεκ"
	], 
	"dateFormatItem-Ed": "E d", 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"Κ", 
		"Δ", 
		"Τ", 
		"Τ", 
		"Π", 
		"Π", 
		"Σ"
	], 
	"eraAbbr": [
		"π.Χ.", 
		"μ.Χ."
	], 
	"dateFormatItem-yyyyMM": "MM/yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "dd MMMM yyyy", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Ζώνη", 
	"dateFormat-medium": "dd MMM yyyy", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"dateFormatItem-yyQQQQ": "QQQQ yy", 
	"quarters-standAlone-wide": [
		"1ο τρίμηνο", 
		"2ο τρίμηνο", 
		"3ο τρίμηνο", 
		"4ο τρίμηνο"
	], 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMMM": "LLLL yyyy", 
	"field-year": "Έτος", 
	"dateFormatItem-HHmmss": "HH:mm:ss", 
	"months-standAlone-wide": [
		"Ιανουάριος", 
		"Φεβρουάριος", 
		"Μάρτιος", 
		"Απρίλιος", 
		"Μάιος", 
		"Ιούνιος", 
		"Ιούλιος", 
		"Αύγουστος", 
		"Σεπτέμβριος", 
		"Οκτώβριος", 
		"Νοέμβριος", 
		"Δεκέμβριος"
	], 
	"field-week": "Εβδομάδα", 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-HHmm": "HH:mm", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Ιαν", 
		"Φεβ", 
		"Μαρ", 
		"Απρ", 
		"Μαϊ", 
		"Ιουν", 
		"Ιουλ", 
		"Αυγ", 
		"Σεπ", 
		"Οκτ", 
		"Νοε", 
		"Δεκ"
	], 
	"timeFormat-short": "h:mm a", 
	"dateFormatItem-H": "H", 
	"field-month": "Μήνας", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"Τ1", 
		"Τ2", 
		"Τ3", 
		"Τ4"
	], 
	"days-format-abbr": [
		"Κυρ", 
		"Δευ", 
		"Τρι", 
		"Τετ", 
		"Πεμ", 
		"Παρ", 
		"Σαβ"
	], 
	"dateFormatItem-MMMMdd": "dd MMMM", 
	"pm": "μ.μ.", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"Κ", 
		"Δ", 
		"Τ", 
		"Τ", 
		"Π", 
		"Π", 
		"Σ"
	], 
	"field-second": "Δευτερόλεπτο", 
	"field-day": "Ημέρα", 
	"dateFormatItem-MEd": "E, d-M", 
	"months-format-narrow": [
		"Ι", 
		"Φ", 
		"Μ", 
		"Α", 
		"Μ", 
		"Ι", 
		"Ι", 
		"Α", 
		"Σ", 
		"Ο", 
		"Ν", 
		"Δ"
	], 
	"am": "π.μ.", 
	"days-standAlone-abbr": [
		"Κυρ", 
		"Δευ", 
		"Τρι", 
		"Τετ", 
		"Πεμ", 
		"Παρ", 
		"Σαβ"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM yyyy", 
	"dateFormat-full": "EEEE, dd MMMM yyyy", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE, d-M-yyyy", 
	"months-format-wide": [
		"Ιανουαρίου", 
		"Φεβρουαρίου", 
		"Μαρτίου", 
		"Απριλίου", 
		"Μαΐου", 
		"Ιουνίου", 
		"Ιουλίου", 
		"Αυγούστου", 
		"Σεπτεμβρίου", 
		"Οκτωβρίου", 
		"Νοεμβρίου", 
		"Δεκεμβρίου"
	], 
	"quarters-format-wide": [
		"1ο τρίμηνο", 
		"2ο τρίμηνο", 
		"3ο τρίμηνο", 
		"4ο τρίμηνο"
	], 
	"days-format-wide": [
		"Κυριακή", 
		"Δευτέρα", 
		"Τρίτη", 
		"Τετάρτη", 
		"Πέμπτη", 
		"Παρασκευή", 
		"Σάββατο"
	], 
	"eraNarrow": [
		"π.Χ.", 
		"μ.Χ."
	]
})