define(
//begin v1.x content
{
	"field-quarter-short-relative+0": "este trim.",
	"field-quarter-short-relative+1": "próximo trim.",
	"field-tue-relative+-1": "terça-feira passada",
	"field-year": "ano",
	"dateFormatItem-Hm": "HH:mm",
	"field-wed-relative+0": "esta quarta-feira",
	"field-wed-relative+1": "próxima quarta-feira",
	"dateFormatItem-ms": "mm:ss",
	"field-minute": "minuto",
	"field-month-narrow-relative+-1": "mês passado",
	"field-tue-narrow-relative+0": "esta ter.",
	"field-tue-narrow-relative+1": "próxima ter.",
	"field-day-short-relative+-1": "ontem",
	"field-thu-short-relative+0": "esta quinta",
	"dateTimeFormat-short": "{1}, {0}",
	"field-day-relative+0": "hoje",
	"field-day-short-relative+-2": "anteontem",
	"field-thu-short-relative+1": "próxima quinta",
	"field-day-relative+1": "amanhã",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-day-relative+2": "depois de amanhã",
	"field-week-narrow-relative+1": "↑↑↑",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-wed-narrow-relative+-1": "qua. passada",
	"field-year-narrow": "ano",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "este ano",
	"field-tue-relative+0": "esta terça-feira",
	"field-year-narrow-relative+1": "próximo ano",
	"field-tue-relative+1": "próxima terça-feira",
	"field-weekdayOfMonth": "dia da semana do mês",
	"field-second-short": "s",
	"dateFormatItem-MMMd": "↑↑↑",
	"field-weekdayOfMonth-narrow": "dia da sem. do mês",
	"field-week-relative+0": "esta semana",
	"field-month-relative+0": "este mês",
	"field-week-relative+1": "próxima semana",
	"field-month-relative+1": "próximo mês",
	"field-sun-narrow-relative+0": "este dom.",
	"field-mon-short-relative+0": "esta segunda",
	"field-sun-narrow-relative+1": "próximo dom.",
	"field-mon-short-relative+1": "próxima segunda",
	"field-second-relative+0": "↑↑↑",
	"dateFormatItem-yyyyQQQ": "QQQQ 'de' y G",
	"field-weekOfMonth": "semana do mês",
	"field-month-short": "mês",
	"dateFormatItem-GyMMMEd": "↑↑↑",
	"dateFormatItem-yyyyMd": "↑↑↑",
	"field-day": "dia",
	"field-dayOfYear-short": "dia do ano",
	"field-year-relative+-1": "ano passado",
	"field-sat-short-relative+-1": "sábado passado",
	"dateFormatItem-yyyyMMMMd": "↑↑↑",
	"field-hour-relative+0": "esta hora",
	"dateFormatItem-yyyyMEd": "↑↑↑",
	"field-wed-relative+-1": "quarta-feira passada",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-sat-narrow-relative+-1": "sáb. passado",
	"field-second": "segundo",
	"dateFormatItem-Ehms": "↑↑↑",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormatItem-GyMMMd": "↑↑↑",
	"field-quarter": "trimestre",
	"field-week-short": "sem.",
	"field-day-narrow-relative+0": "hoje",
	"field-day-narrow-relative+1": "amanhã",
	"field-day-narrow-relative+2": "depois de amanhã",
	"dateFormatItem-yyyyMMMMEd": "↑↑↑",
	"field-tue-short-relative+0": "esta terça",
	"field-tue-short-relative+1": "próxima terça",
	"field-month-short-relative+-1": "mês passado",
	"field-mon-relative+-1": "segunda-feira passada",
	"dateFormatItem-GyMMM": "↑↑↑",
	"field-month": "mês",
	"field-day-narrow": "dia",
	"dateFormatItem-MMM": "↑↑↑",
	"field-minute-short": "min",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "este sábado",
	"field-sat-short-relative+1": "próximo sábado",
	"dateFormat-medium": "↑↑↑",
	"dateFormatItem-yyyyMMMM": "MMMM 'de' y G",
	"dateFormatItem-yyyyM": "↑↑↑",
	"field-second-narrow": "s",
	"field-mon-relative+0": "esta segunda-feira",
	"field-day-narrow-relative+-1": "ontem",
	"field-year-short": "ano",
	"field-mon-relative+1": "próxima segunda-feira",
	"field-day-narrow-relative+-2": "anteontem",
	"field-quarter-relative+-1": "trimestre passado",
	"dateFormatItem-yyyyMMMd": "d/MM/y G",
	"field-dayperiod-narrow": "am/pm",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-dayOfYear": "dia do ano",
	"field-sat-relative+-1": "sábado passado",
	"dateTimeFormat-long": "{1} 'às' {0}",
	"dateFormatItem-Md": "↑↑↑",
	"field-hour": "hora",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"field-month-relative+-1": "mês passado",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-quarter-short": "trim.",
	"field-sat-narrow-relative+0": "este sáb.",
	"field-fri-relative+0": "esta sexta-feira",
	"field-sat-narrow-relative+1": "próximo sáb.",
	"field-fri-relative+1": "próxima sexta-feira",
	"dateFormatItem-EBhm": "↑↑↑",
	"field-month-narrow-relative+0": "este mês",
	"field-month-narrow-relative+1": "próximo mês",
	"field-sun-short-relative+0": "este domingo",
	"field-sun-short-relative+1": "próximo domingo",
	"field-week-relative+-1": "semana passada",
	"field-quarter-short-relative+-1": "trim. passado",
	"dateFormatItem-Ehm": "↑↑↑",
	"field-quarter-relative+0": "este trimestre",
	"field-minute-relative+0": "este minuto",
	"field-quarter-relative+1": "próximo trimestre",
	"field-wed-short-relative+-1": "quarta passada",
	"dateFormat-short": "d/M/y G",
	"dateFormatItem-Bh": "↑↑↑",
	"field-year-narrow-relative+-1": "ano passado",
	"field-thu-short-relative+-1": "quinta passada",
	"dateFormatItem-yyyyMMMEd": "E, d/MM/y G",
	"field-mon-narrow-relative+-1": "seg. passada",
	"dateFormatItem-MMMMd": "↑↑↑",
	"field-thu-narrow-relative+-1": "qui. passada",
	"dateFormatItem-E": "↑↑↑",
	"dateFormatItem-H": "HH",
	"field-weekOfMonth-short": "sem. do mês",
	"field-tue-narrow-relative+-1": "ter. passada",
	"dateFormatItem-yyyy": "↑↑↑",
	"dateFormatItem-M": "↑↑↑",
	"field-wed-short-relative+0": "esta quarta",
	"field-wed-short-relative+1": "próxima quarta",
	"field-sun-relative+-1": "domingo passado",
	"dateFormatItem-MMMMEd": "↑↑↑",
	"dateTimeFormat-full": "{1} 'às' {0}",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-d": "↑↑↑",
	"field-weekday": "dia da semana",
	"field-day-short-relative+0": "hoje",
	"field-quarter-narrow-relative+0": "este trim.",
	"field-day-short-relative+1": "amanhã",
	"field-sat-relative+0": "este sábado",
	"field-quarter-narrow-relative+1": "próximo trim.",
	"dateFormatItem-h": "h a",
	"field-day-short-relative+2": "depois de amanhã",
	"field-sat-relative+1": "próximo sábado",
	"field-week-short-relative+0": "esta semana",
	"field-week-short-relative+1": "próxima semana",
	"field-dayOfYear-narrow": "↑↑↑",
	"field-month-short-relative+0": "este mês",
	"field-month-short-relative+1": "próximo mês",
	"field-weekdayOfMonth-short": "dia da sem. do mês",
	"dateFormatItem-MEd": "↑↑↑",
	"field-zone-narrow": "fuso horário",
	"dateFormatItem-y": "↑↑↑",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-sun-narrow-relative+-1": "dom. passado",
	"field-mon-short-relative+-1": "segunda passada",
	"field-thu-narrow-relative+1": "próxima qui.",
	"field-thu-relative+0": "esta quinta-feira",
	"field-thu-relative+1": "próxima quinta-feira",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-fri-short-relative+-1": "sexta passada",
	"field-thu-relative+-1": "quinta-feira passada",
	"field-week": "semana",
	"dateFormatItem-Ed": "↑↑↑",
	"field-wed-narrow-relative+0": "esta qua.",
	"field-wed-narrow-relative+1": "próxima qua.",
	"dateFormatItem-yyyyMMMEEEEd": "EEEE, d/MM/y",
	"field-quarter-narrow-relative+-1": "trim. passado",
	"field-year-short-relative+0": "este ano",
	"dateFormatItem-yyyyMMM": "MM/y G",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "próximo ano",
	"field-fri-short-relative+0": "esta sexta",
	"field-fri-short-relative+1": "próxima sexta",
	"field-week-short-relative+-1": "semana passada",
	"dateFormatItem-yyyyQQQQ": "QQQQ 'de' y G",
	"field-hour-short": "h",
	"field-zone-short": "fuso horário",
	"field-month-narrow": "mês",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "sex. passada",
	"field-year-relative+0": "este ano",
	"field-year-relative+1": "próximo ano",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "sexta-feira passada",
	"dateFormatItem-Bhms": "↑↑↑",
	"field-tue-short-relative+-1": "terça passada",
	"field-minute-narrow": "min",
	"field-mon-narrow-relative+0": "esta seg.",
	"dateFormatItem-EHm": "↑↑↑",
	"field-mon-narrow-relative+1": "próxima seg.",
	"field-year-short-relative+-1": "ano passado",
	"field-zone": "fuso horário",
	"dateFormatItem-MMMEd": "↑↑↑",
	"field-weekOfMonth-narrow": "sem. do mês",
	"dateFormatItem-EHms": "↑↑↑",
	"field-weekday-narrow": "↑↑↑",
	"field-quarter-narrow": "trim.",
	"field-sun-short-relative+-1": "domingo passado",
	"field-day-relative+-1": "ontem",
	"field-day-relative+-2": "anteontem",
	"field-weekday-short": "↑↑↑",
	"dateFormatItem-Bhm": "↑↑↑",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "próximo domingo",
	"dateFormatItem-Gy": "↑↑↑",
	"field-day-short": "dia",
	"field-week-narrow": "sem.",
	"field-era": "era",
	"field-fri-narrow-relative+0": "esta sex.",
	"field-fri-narrow-relative+1": "próxima sex."
}
//end v1.x content
);