define(
//begin v1.x content
{
	"dateFormatItem-yMMMM": "MMMM 'de' y",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próxima qui.",
	"field-sun-narrow-relative+0": "este dom.",
	"field-sun-narrow-relative+1": "próximo dom.",
	"months-format-wide": [
		"janeiro",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-standAlone-abbr-pm": "p.m.",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-fri-narrow-relative+0": "esta sex.",
	"field-fri-narrow-relative+1": "próxima sex.",
	"eraNarrow": [
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-Hmv": "↑↑↑",
	"dateFormatItem-hmsv": "↑↑↑",
	"dateFormatItem-yMMMd": "d/MM/y",
	"dayPeriods-format-abbr-night1": "↑↑↑",
	"dayPeriods-format-narrow-evening1": "noite",
	"days-standAlone-narrow": [
		"D",
		"S",
		"T",
		"Q",
		"Q",
		"S",
		"S"
	],
	"days-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-abbr-afternoon1": "↑↑↑",
	"dayPeriods-format-wide-evening1": "da noite",
	"dateFormatItem-Ehm": "E, h:mm a",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-wed-narrow-relative+-1": "qua. passada",
	"dayPeriods-standAlone-wide-evening1": "↑↑↑",
	"days-format-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-yMM": "MM/y",
	"field-month-short-relative+0": "este mês",
	"field-month-short-relative+1": "próximo mês",
	"dateFormatItem-Ehms": "E, h:mm:ss a",
	"dayPeriods-standAlone-narrow-evening1": "noite",
	"dayPeriods-standAlone-abbr-afternoon1": "↑↑↑",
	"field-thu-relative+0": "esta quinta-feira",
	"dayPeriods-standAlone-abbr-night1": "↑↑↑",
	"field-thu-relative+1": "próxima quinta-feira",
	"dayPeriods-format-wide-am": "da manhã",
	"field-fri-relative+0": "esta sexta-feira",
	"field-fri-relative+1": "próxima sexta-feira",
	"dateFormatItem-yMd": "dd/MM/y",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "próximo trimestre",
	"field-sun-short-relative+0": "este domingo",
	"timeFormat-short": "HH:mm",
	"field-sun-short-relative+1": "próximo domingo",
	"dateFormatItem-hms": "h:mm:ss a",
	"dayPeriods-format-narrow-afternoon1": "tarde",
	"dateFormatItem-Md": "dd/MM",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "↑↑↑",
	"field-week-narrow": "sem.",
	"field-hour-relative+0": "esta hora",
	"field-day-relative+-1": "ontem",
	"field-day-relative+-2": "anteontem",
	"field-mon-narrow-relative+-1": "seg. passada",
	"field-minute-narrow": "min",
	"dateFormatItem-MMMMEd": "ccc, d 'de' MMMM",
	"field-thu-short-relative+0": "esta quinta",
	"field-mon-relative+0": "esta segunda-feira",
	"field-thu-short-relative+1": "próxima quinta",
	"field-mon-relative+1": "próxima segunda-feira",
	"field-day-narrow-relative+0": "hoje",
	"field-era-short": "↑↑↑",
	"field-day-narrow-relative+1": "amanhã",
	"field-sat-narrow-relative+0": "este sáb.",
	"field-day-narrow-relative+2": "depois de amanhã",
	"timeFormat-long": "HH:mm:ss z",
	"field-sat-narrow-relative+1": "próximo sáb.",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+0": "esta qua.",
	"field-wed-narrow-relative+1": "próxima qua.",
	"field-month": "mês",
	"months-standAlone-wide": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-weekday-narrow": "↑↑↑",
	"dayPeriods-standAlone-narrow-afternoon1": "tarde",
	"field-year-relative+0": "este ano",
	"field-year-relative+1": "próximo ano",
	"dayPeriods-format-abbr-evening1": "↑↑↑",
	"dayPeriods-format-abbr-noon": "meio-dia",
	"dayPeriods-format-narrow-midnight": "meia-noite",
	"dayPeriods-format-wide-midnight": "↑↑↑",
	"field-tue-relative+0": "esta terça-feira",
	"field-tue-relative+1": "próxima terça-feira",
	"dayPeriods-standAlone-abbr-evening1": "↑↑↑",
	"dateFormatItem-hm": "h:mm a",
	"dayPeriods-standAlone-wide-midnight": "↑↑↑",
	"field-year-narrow": "ano",
	"dayPeriods-standAlone-abbr-noon": "meio-dia",
	"field-tue-short-relative+0": "esta terça",
	"dayPeriods-standAlone-narrow-midnight": "meia-noite",
	"field-tue-short-relative+1": "próxima terça",
	"field-tue-narrow-relative+0": "esta ter.",
	"field-tue-narrow-relative+1": "próxima ter.",
	"dateTimeFormat-full": "{1} 'às' {0}",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-EBhm": "↑↑↑",
	"dateFormatItem-H": "HH",
	"field-wed-relative+0": "esta quarta-feira",
	"field-wed-relative+1": "próxima quarta-feira",
	"dateFormatItem-M": "L",
	"field-wed-short-relative+0": "esta quarta",
	"field-fri-short-relative+0": "esta sexta",
	"field-wed-short-relative+1": "próxima quarta",
	"field-fri-short-relative+1": "próxima sexta",
	"field-weekOfMonth-short": "sem. do mês",
	"field-quarter-short-relative+-1": "trim. passado",
	"field-year-short-relative+-1": "ano passado",
	"dateFormatItem-yMMMEEEEd": "EEEE, d/MM/y",
	"dateFormatItem-Bhm": "↑↑↑",
	"dayPeriods-format-wide-night1": "↑↑↑",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-quarter-narrow-relative+-1": "trim. passado",
	"dateFormatItem-d": "d",
	"dayPeriods-format-abbr-pm": "p.m.",
	"dateFormatItem-h": "h a",
	"quarters-standAlone-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"field-weekOfMonth-narrow": "sem. do mês",
	"dateFormatItem-y": "y",
	"field-minute-relative+0": "este minuto",
	"field-year-short-relative+0": "este ano",
	"dateFormatItem-EBhms": "↑↑↑",
	"field-year-short-relative+1": "próximo ano",
	"field-weekday": "dia da semana",
	"dayPeriods-format-narrow-pm": "p.m.",
	"field-tue-narrow-relative+-1": "ter. passada",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"dayPeriods-standAlone-wide-night1": "↑↑↑",
	"field-year-narrow-relative+-1": "ano passado",
	"field-sat-relative+-1": "sábado passado",
	"dayPeriods-format-abbr-midnight": "↑↑↑",
	"dayPeriods-format-narrow-morning1": "manhã",
	"dayPeriods-format-wide-morning1": "da manhã",
	"dayPeriods-standAlone-abbr-midnight": "↑↑↑",
	"dayPeriods-standAlone-narrow-pm": "p.m.",
	"dayPeriods-standAlone-wide-morning1": "↑↑↑",
	"field-mon-narrow-relative+0": "esta seg.",
	"field-mon-narrow-relative+1": "próxima seg.",
	"field-second": "segundo",
	"dateFormatItem-yMMMEd": "E, d/MM/y",
	"field-year-relative+-1": "ano passado",
	"field-weekdayOfMonth-short": "dia da sem. do mês",
	"dateFormat-short": "dd/MM/yy",
	"eraNames": [
		"↑↑↑",
		"↑↑↑"
	],
	"field-second-short": "s",
	"field-thu-short-relative+-1": "quinta passada",
	"field-zone": "fuso horário",
	"field-dayperiod-narrow": "am/pm",
	"field-sun-short-relative+-1": "domingo passado",
	"dayPeriods-standAlone-narrow-morning1": "manhã",
	"eraAbbr": [
		"↑↑↑",
		"↑↑↑"
	],
	"field-week-short": "sem.",
	"dayPeriods-standAlone-abbr-am": "a.m.",
	"dayPeriods-standAlone-wide-pm": "tarde",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+0": "hoje",
	"field-day-relative+1": "amanhã",
	"field-day-relative+2": "depois de amanhã",
	"field-day-short-relative+0": "hoje",
	"field-dayOfYear-short": "dia do ano",
	"field-day-short-relative+1": "amanhã",
	"dateFormat-long": "d 'de' MMMM 'de' y",
	"field-day-short-relative+2": "depois de amanhã",
	"field-sun-narrow-relative+-1": "dom. passado",
	"dayPeriods-format-wide-noon": "meio-dia",
	"field-second-relative+0": "↑↑↑",
	"field-quarter-relative+-1": "trimestre passado",
	"dayPeriods-format-narrow-night1": "madrugada",
	"quarters-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-standAlone-wide-noon": "↑↑↑",
	"dayPeriods-standAlone-narrow-night1": "madrugada",
	"field-week-relative+-1": "semana passada",
	"dayPeriods-format-abbr-morning1": "↑↑↑",
	"field-month-relative+-1": "mês passado",
	"months-format-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-year": "ano",
	"field-era": "era",
	"dayPeriods-standAlone-abbr-morning1": "↑↑↑",
	"days-standAlone-short": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dateFormatItem-yQQQQ": "QQQQ 'de' y",
	"field-day-short-relative+-1": "ontem",
	"field-day-short-relative+-2": "anteontem",
	"dateFormatItem-GyMMM": "MMM 'de' y G",
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateFormatItem-Bhms": "↑↑↑",
	"field-hour": "hora",
	"field-dayOfYear-narrow": "↑↑↑",
	"field-quarter": "trimestre",
	"field-month-narrow-relative+0": "este mês",
	"field-month-narrow-relative+1": "próximo mês",
	"dateFormatItem-MMdd": "dd/MM",
	"field-day": "dia",
	"field-mon-relative+-1": "segunda-feira passada",
	"field-dayOfYear": "dia do ano",
	"dateFormat-medium": "dd/MM/y",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-yMMM": "MM/y",
	"dateFormatItem-GyMMMd": "d 'de' MMM 'de' y G",
	"dateFormatItem-MEd": "E, dd/MM",
	"field-tue-short-relative+-1": "terça passada",
	"field-year-short": "ano",
	"field-month-short": "mês",
	"dateFormatItem-MMMEd": "E, d/MM",
	"dayPeriods-format-wide-afternoon1": "da tarde",
	"dateFormatItem-MMMd": "d/MM",
	"dateFormatItem-Bh": "↑↑↑",
	"months-format-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dayPeriods-format-abbr-am": "a.m.",
	"field-sat-relative+0": "este sábado",
	"field-sat-relative+1": "próximo sábado",
	"dayPeriods-format-wide-pm": "da tarde",
	"field-zone-short": "fuso horário",
	"days-standAlone-abbr": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"field-week-short-relative+0": "esta semana",
	"dateFormatItem-yMMMMd": "d 'de' MMMM 'de' y",
	"field-week-short-relative+1": "próxima semana",
	"dayPeriods-standAlone-wide-afternoon1": "↑↑↑",
	"field-fri-short-relative+-1": "sexta passada",
	"field-month-narrow": "mês",
	"dayPeriods-format-narrow-am": "a.m.",
	"field-month-narrow-relative+-1": "mês passado",
	"days-format-abbr": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"field-weekday-short": "↑↑↑",
	"field-day-narrow-relative+-1": "ontem",
	"field-day-narrow-relative+-2": "anteontem",
	"field-quarter-short": "trim.",
	"days-format-short": [
		"dom.",
		"seg.",
		"ter.",
		"qua.",
		"qui.",
		"sex.",
		"sáb."
	],
	"months-standAlone-narrow": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"J",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"days-format-narrow": [
		"D",
		"S",
		"T",
		"Q",
		"Q",
		"S",
		"S"
	],
	"dateFormatItem-EHm": "E, HH:mm",
	"field-quarter-narrow": "trim.",
	"field-mon-short-relative+0": "esta segunda",
	"field-mon-short-relative+1": "próxima segunda",
	"field-dayperiod-short": "am/pm",
	"dayPeriods-standAlone-narrow-am": "a.m.",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-thu-relative+-1": "quinta-feira passada",
	"field-fri-narrow-relative+-1": "sex. passada",
	"field-mon-short-relative+-1": "segunda passada",
	"timeFormat-medium": "HH:mm:ss",
	"field-quarter-short-relative+0": "este trim.",
	"field-quarter-short-relative+1": "próximo trim.",
	"dateFormatItem-Ed": "E, d",
	"field-wed-relative+-1": "quarta-feira passada",
	"field-weekOfMonth": "semana do mês",
	"field-weekdayOfMonth-narrow": "dia da sem. do mês",
	"dayPeriods-standAlone-wide-am": "manhã",
	"dateFormatItem-yQQQ": "QQQQ 'de' y",
	"field-fri-relative+-1": "sexta-feira passada",
	"field-minute": "minuto",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"field-day-short": "dia",
	"field-dayperiod": "am/pm",
	"field-hour-short": "h",
	"months-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"field-second-narrow": "s",
	"field-month-relative+0": "este mês",
	"field-month-relative+1": "próximo mês",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y",
	"field-era-narrow": "↑↑↑",
	"field-sat-short-relative+-1": "sábado passado",
	"dayPeriods-format-narrow-noon": "meio-dia",
	"field-week-short-relative+-1": "semana passada",
	"dateFormatItem-yMMMMEd": "ccc, d 'de' MMMM 'de' y",
	"dateTimeFormat-long": "{1} 'às' {0}",
	"dateFormatItem-yM": "MM/y",
	"field-sun-relative+-1": "domingo passado",
	"field-wed-short-relative+-1": "quarta passada",
	"field-weekdayOfMonth": "dia da semana do mês",
	"field-quarter-narrow-relative+0": "este trim.",
	"dateFormatItem-GyMMMEd": "E, d 'de' MMM 'de' y G",
	"field-quarter-narrow-relative+1": "próximo trim.",
	"field-sat-short-relative+0": "este sábado",
	"field-hour-narrow": "h",
	"field-sat-short-relative+1": "próximo sábado",
	"field-year-narrow-relative+0": "este ano",
	"field-year-narrow-relative+1": "próximo ano",
	"dateFormatItem-Gy": "y G",
	"field-zone-narrow": "fuso horário",
	"dayPeriods-standAlone-narrow-noon": "meio-dia",
	"field-tue-relative+-1": "terça-feira passada",
	"field-minute-short": "min",
	"dateFormatItem-yw": "w.'ª' 'semana' 'de' Y",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+0": "esta semana",
	"field-week-relative+1": "próxima semana",
	"dateFormatItem-MMM": "LLL",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "próximo domingo",
	"field-sat-narrow-relative+-1": "sáb. passado",
	"quarters-standAlone-abbr": [
		"↑↑↑",
		"↑↑↑",
		"↑↑↑",
		"↑↑↑"
	],
	"dateFormatItem-MMMMW": "W.'ª' 'semana' 'de' MMMM",
	"field-month-short-relative+-1": "mês passado",
	"dateFormatItem-EHms": "E, HH:mm:ss",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"field-week": "semana",
	"field-day-narrow": "dia"
}
//end v1.x content
);