define(
//begin v1.x content
{
	"dateFormatItem-yQ": "QQQ 'de' yyyy",
	"dayPeriods-format-wide-pm": "p.m.",
	"dayPeriods-standAlone-abbr-pm": "p.m.",
	"dateFormatItem-MMMEd": "E, d/MM",
	"dateFormatItem-yQQQ": "QQQ 'de' y",
	"dayPeriods-format-wide-am": "a.m.",
	"dayPeriods-standAlone-abbr-am": "a.m.",
	"timeFormat-full": "H:mm:ss zzzz",
	"dayPeriods-standAlone-wide-pm": "p.m.",
	"dateFormatItem-yMMM": "MM/y",
	"dateFormatItem-yMMMMEd": "E, d 'de' MMMM 'de' y",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+-1": "Última semana",
	"dayPeriods-standAlone-wide-am": "a.m.",
	"dayPeriods-format-narrow-pm": "p.m.",
	"dateFormatItem-yyMMM": "MM/yy",
	"field-year-relative+-1": "Último ano",
	"dateFormatItem-yMMMM": "MMMM 'de' y",
	"dateFormatItem-yMMMMd": "d 'de' MMMM 'de' y",
	"dateFormatItem-ms": "mm:ss",
	"dayPeriods-format-narrow-am": "a.m.",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-yyMMMd": "d/MM/yy",
	"dateFormatItem-MMMMEd": "E, d 'de' MMMM",
	"dateFormatItem-MMMd": "d/MM",
	"dateFormatItem-HHmm": "HH:mm",
	"dateFormatItem-yyMMMEd": "E, d/MM/yy",
	"dateFormatItem-yyQ": "QQQ 'de' yy",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"Jan",
		"Fev",
		"Mar",
		"Abr",
		"Mai",
		"Jun",
		"Jul",
		"Ago",
		"Set",
		"Out",
		"Nov",
		"Dez"
	],
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-yMMMd": "d/MM/y",
	"dayPeriods-format-abbr-pm": "p.m.",
	"dateFormatItem-yMMMEd": "E, d/MM/y",
	"months-format-wide": [
		"Janeiro",
		"Fevereiro",
		"Março",
		"Abril",
		"Maio",
		"Junho",
		"Julho",
		"Agosto",
		"Setembro",
		"Outubro",
		"Novembro",
		"Dezembro"
	],
	"dayPeriods-format-abbr-am": "a.m.",
	"quarters-format-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"field-month-relative+-1": "Último mês",
	"days-format-wide": [
		"Domingo",
		"Segunda-feira",
		"Terça-feira",
		"Quarta-feira",
		"Quinta-feira",
		"Sexta-feira",
		"Sábado"
	]
}
//end v1.x content
);