define(
//begin v1.x content
{
	"field-quarter-short-relative+0": "este trim.",
	"field-quarter-short-relative+1": "próximo trim.",
	"field-tue-relative+-1": "terça-feira passada",
	"field-year": "ano",
	"field-wed-relative+0": "esta quarta-feira",
	"field-wed-relative+1": "próxima quarta-feira",
	"field-minute": "minuto",
	"field-month-narrow-relative+-1": "mês passado",
	"field-tue-narrow-relative+0": "esta ter.",
	"field-tue-narrow-relative+1": "próxima ter.",
	"field-thu-short-relative+0": "esta quinta",
	"field-day-short-relative+-1": "ontem",
	"field-thu-short-relative+1": "próxima quinta",
	"field-day-relative+0": "hoje",
	"field-day-short-relative+-2": "anteontem",
	"field-day-relative+1": "amanhã",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-day-relative+2": "depois de amanhã",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+-1": "qua. passada",
	"field-year-narrow": "ano",
	"field-era-short": "↑↑↑",
	"field-year-narrow-relative+0": "este ano",
	"field-tue-relative+0": "esta terça-feira",
	"field-year-narrow-relative+1": "próximo ano",
	"field-tue-relative+1": "próxima terça-feira",
	"field-weekdayOfMonth": "dia da semana do mês",
	"field-second-short": "s",
	"field-weekdayOfMonth-narrow": "dia da sem. do mês",
	"field-week-relative+0": "esta semana",
	"field-month-relative+0": "este mês",
	"field-week-relative+1": "próxima semana",
	"field-month-relative+1": "próximo mês",
	"field-sun-narrow-relative+0": "este dom.",
	"field-mon-short-relative+0": "esta segunda",
	"field-sun-narrow-relative+1": "próximo dom.",
	"field-mon-short-relative+1": "próxima segunda",
	"field-second-relative+0": "↑↑↑",
	"field-weekOfMonth": "semana do mês",
	"field-month-short": "mês",
	"field-day": "dia",
	"field-dayOfYear-short": "dia do ano",
	"field-year-relative+-1": "ano passado",
	"field-sat-short-relative+-1": "sábado passado",
	"field-hour-relative+0": "esta hora",
	"field-wed-relative+-1": "quarta-feira passada",
	"field-sat-narrow-relative+-1": "sáb. passado",
	"field-second": "segundo",
	"field-quarter": "trimestre",
	"field-week-short": "sem.",
	"field-day-narrow-relative+0": "hoje",
	"field-day-narrow-relative+1": "amanhã",
	"field-day-narrow-relative+2": "depois de amanhã",
	"field-tue-short-relative+0": "esta terça",
	"field-tue-short-relative+1": "próxima terça",
	"field-month-short-relative+-1": "mês passado",
	"field-mon-relative+-1": "segunda-feira passada",
	"field-month": "mês",
	"field-day-narrow": "dia",
	"field-minute-short": "min",
	"field-dayperiod": "am/pm",
	"field-sat-short-relative+0": "este sábado",
	"field-sat-short-relative+1": "próximo sábado",
	"field-second-narrow": "s",
	"field-mon-relative+0": "esta segunda-feira",
	"field-mon-relative+1": "próxima segunda-feira",
	"field-day-narrow-relative+-1": "ontem",
	"field-year-short": "ano",
	"field-day-narrow-relative+-2": "anteontem",
	"field-quarter-relative+-1": "trimestre passado",
	"field-dayperiod-narrow": "am/pm",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-dayOfYear": "dia do ano",
	"field-sat-relative+-1": "sábado passado",
	"field-hour": "hora",
	"field-month-relative+-1": "mês passado",
	"field-quarter-short": "trim.",
	"field-sat-narrow-relative+0": "este sáb.",
	"field-fri-relative+0": "esta sexta-feira",
	"field-sat-narrow-relative+1": "próximo sáb.",
	"field-fri-relative+1": "próxima sexta-feira",
	"field-month-narrow-relative+0": "este mês",
	"field-month-narrow-relative+1": "próximo mês",
	"field-sun-short-relative+0": "este domingo",
	"field-sun-short-relative+1": "próximo domingo",
	"field-week-relative+-1": "semana passada",
	"field-quarter-short-relative+-1": "trim. passado",
	"field-quarter-relative+0": "este trimestre",
	"field-minute-relative+0": "este minuto",
	"field-quarter-relative+1": "próximo trimestre",
	"field-wed-short-relative+-1": "quarta passada",
	"dateFormat-short": "d/M/y G",
	"field-thu-short-relative+-1": "quinta passada",
	"field-year-narrow-relative+-1": "ano passado",
	"field-mon-narrow-relative+-1": "seg. passada",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-tue-narrow-relative+-1": "ter. passada",
	"field-weekOfMonth-short": "sem. do mês",
	"field-wed-short-relative+0": "esta quarta",
	"field-wed-short-relative+1": "próxima quarta",
	"field-sun-relative+-1": "domingo passado",
	"field-weekday": "dia da semana",
	"field-day-short-relative+0": "hoje",
	"field-quarter-narrow-relative+0": "este trim.",
	"field-sat-relative+0": "este sábado",
	"field-day-short-relative+1": "amanhã",
	"field-quarter-narrow-relative+1": "próximo trim.",
	"field-sat-relative+1": "próximo sábado",
	"field-day-short-relative+2": "depois de amanhã",
	"field-week-short-relative+0": "esta semana",
	"field-week-short-relative+1": "próxima semana",
	"field-dayOfYear-narrow": "↑↑↑",
	"field-month-short-relative+0": "este mês",
	"field-month-short-relative+1": "próximo mês",
	"field-weekdayOfMonth-short": "dia da sem. do mês",
	"field-zone-narrow": "fuso horário",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próxima qui.",
	"field-sun-narrow-relative+-1": "dom. passado",
	"field-mon-short-relative+-1": "segunda passada",
	"field-thu-relative+0": "esta quinta-feira",
	"field-thu-relative+1": "próxima quinta-feira",
	"field-fri-short-relative+-1": "sexta passada",
	"field-thu-relative+-1": "quinta-feira passada",
	"field-week": "semana",
	"field-wed-narrow-relative+0": "esta qua.",
	"field-wed-narrow-relative+1": "próxima qua.",
	"field-quarter-narrow-relative+-1": "trim. passado",
	"field-year-short-relative+0": "este ano",
	"field-dayperiod-short": "am/pm",
	"field-year-short-relative+1": "próximo ano",
	"field-fri-short-relative+0": "esta sexta",
	"field-fri-short-relative+1": "próxima sexta",
	"field-week-short-relative+-1": "semana passada",
	"field-hour-short": "h",
	"field-zone-short": "fuso horário",
	"field-month-narrow": "mês",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "sex. passada",
	"field-year-relative+0": "este ano",
	"field-year-relative+1": "próximo ano",
	"field-era-narrow": "↑↑↑",
	"field-fri-relative+-1": "sexta-feira passada",
	"field-tue-short-relative+-1": "terça passada",
	"field-minute-narrow": "min",
	"field-mon-narrow-relative+0": "esta seg.",
	"field-mon-narrow-relative+1": "próxima seg.",
	"field-year-short-relative+-1": "ano passado",
	"field-zone": "fuso horário",
	"field-weekOfMonth-narrow": "sem. do mês",
	"field-weekday-narrow": "↑↑↑",
	"field-quarter-narrow": "trim.",
	"field-sun-short-relative+-1": "domingo passado",
	"field-day-relative+-1": "ontem",
	"field-day-relative+-2": "anteontem",
	"field-weekday-short": "↑↑↑",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "próximo domingo",
	"field-day-short": "dia",
	"field-week-narrow": "sem.",
	"field-era": "era",
	"field-fri-narrow-relative+0": "esta sex.",
	"field-fri-narrow-relative+1": "próxima sex."
}
//end v1.x content
);