// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
	"dateFormatItem-yM": "yyyy/M", 
	"field-minute": "分鐘", 
	"eraNames": [
		"西元前", 
		"西元"
	], 
	"field-weekday": "週天", 
	"dateFormatItem-MMdd": "MM/dd", 
	"field-day-relative+-3": "大前天", 
	"field-relative-day": "大後天", 
	"months-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"field-era": "年代", 
	"field-hour": "小時", 
	"quarters-standAlone-abbr": [
		"第1季", 
		"第2季", 
		"第3季", 
		"第4季"
	], 
	"timeFormat-full": "zzzzah時mm分ss秒", 
	"months-standAlone-abbr": [
		"1月", 
		"2月", 
		"3月", 
		"4月", 
		"5月", 
		"6月", 
		"7月", 
		"8月", 
		"9月", 
		"10月", 
		"11月", 
		"12月"
	], 
	"dateFormatItem-Ed": "d日(E)", 
	"dateFormatItem-yMMM": "y年M月", 
	"eraAbbr": [
		"西元前", 
		"西元"
	], 
	"field-day-relative+2": "後天", 
	"field-day-relative+3": "大後天", 
	"timeFormat-medium": "ah:mm:ss", 
	"field-zone": "區域", 
	"dateFormatItem-yyMM": "yy-MM", 
	"dateFormat-medium": "yyyy/M/d", 
	"quarters-standAlone-wide": [
		"第1季", 
		"第2季", 
		"第3季", 
		"第4季"
	], 
	"dateFormatItem-yMMMM": "y年M月", 
	"dateFormatItem-HHmmss": "H:mm:ss", 
	"months-standAlone-wide": [
		"1月", 
		"2月", 
		"3月", 
		"4月", 
		"5月", 
		"6月", 
		"7月", 
		"8月", 
		"9月", 
		"10月", 
		"11月", 
		"12月"
	], 
	"field-week": "週", 
	"dateFormatItem-HHmm": "H:mm", 
	"timeFormat-long": "zah時mm分ss秒", 
	"dateFormatItem-H": "H時", 
	"quarters-format-abbr": [
		"第1季", 
		"第2季", 
		"第3季", 
		"第4季"
	], 
	"days-format-abbr": [
		"週日", 
		"週一", 
		"週二", 
		"週三", 
		"週四", 
		"週五", 
		"週六"
	], 
	"field-second": "秒", 
	"dateFormatItem-MEd": "M/d（E）", 
	"months-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"days-standAlone-abbr": [
		"週日", 
		"週一", 
		"週二", 
		"週三", 
		"週四", 
		"週五", 
		"週六"
	], 
	"dateFormat-short": "yy/M/d", 
	"dateFormatItem-yMMMEd": "y年M月d日EEE", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "yyyy/M/d（EEE）", 
	"dateTimeAvailableFormats": [
		"d日（E）", 
		"H:mm", 
		"H:mm:ss", 
		"M-d（E）", 
		"MM/dd", 
		"M/d", 
		"yyyy/M", 
		"yyyy/M/d（EEE）", 
		"yyyy年M月", 
		"yyyy年M月", 
		"yyyy/MM", 
		"MMMMdd日", 
		"MMMd日", 
		"MM-dd", 
		"M-d", 
		"d日", 
		"mm:ss", 
		"mm:ss", 
		"yyyy年", 
		"yyyy-M", 
		"yyyy年M月d日，E", 
		"yyyy年MMM", 
		"yyyy年MMMd日EEE", 
		"yyyy年MMMM", 
		"yyyy年QQQ", 
		"y年QQQ", 
		"yy-MM", 
		"yy年MMM", 
		"yy年第Q季度", 
		"yyyy年", 
		"yyyy年M月", 
		"yyyy年MMMM"
	], 
	"quarters-format-wide": [
		"第1季", 
		"第2季", 
		"第3季", 
		"第4季"
	], 
	"eraNarrow": [
		"西元前", 
		"西元"
	]
})