define(
//begin v1.x content
{
	"USD_displayName": "Doola ey'Amerika",
	"TZS_displayName": "Silingi ey'eTanzaniya",
	"ZMW_displayName": "Kwaca ey'eZambya",
	"MAD_displayName": "Diraamu ey'eMoroko",
	"NGN_displayName": "Nayira ey'eNayijerya",
	"ZWD_displayName": "Doola ey'eZimbabwe",
	"SDG_displayName": "Dinaali ey'eSudaani",
	"MWK_displayName": "Kwaca ey'eMalawi",
	"KMF_displayName": "Faranga ey'eKomoro",
	"SCR_displayName": "Rupiya ey'eSesere",
	"EGP_displayName": "Pawundi ey'eMisiri",
	"CVE_displayName": "Esikudo ey'Keepu Veredi",
	"LYD_displayName": "Dinaali ey'eLibya",
	"CAD_displayName": "Doola ey'eKanada",
	"INR_displayName": "Rupiya ey'eBuyindi",
	"JPY_displayName": "Yeni ey'eJapani",
	"LRD_displayName": "Doola ey'eLiberya",
	"ZAR_displayName": "Randi ey'eSawusafirika",
	"AOA_displayName": "Kwanza ey'Angola",
	"TND_displayName": "Dinaali ey'eTunizya",
	"GHC_displayName": "Sedi ey'eGana",
	"BWP_displayName": "Pula ey'eBotiswana",
	"DZD_displayName": "Dinaali ey'Aligerya",
	"ZMK_displayName": "Kwaca ey'eZambya (1968–2012)",
	"NAD_displayName": "Doola ey'eNamibiya",
	"AED_displayName": "Diraamu eya Emireeti",
	"ETB_displayName": "Biiru ey'Esyopya",
	"MZM_displayName": "Metikaali ey'eMozambiiki",
	"BIF_displayName": "Faranga ey'eburundi",
	"RWF_displayName": "Faranga ey'eRwanda",
	"STD_displayName": "Dobura ey'eSantome ne Purincipe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakifa ey'Eritureya",
	"SAR_displayName": "Riyaali ey'eBuwarabu",
	"DJF_displayName": "Faranga ey'eJjibuti",
	"CDF_displayName": "Faranga ey'eKongo",
	"GBP_displayName": "Pawundi ey'eBungereza",
	"CHF_displayName": "Faranga ey'eSwitizirandi",
	"MUR_displayName": "Rupiya ey'eMawurisyasi",
	"SOS_displayName": "Silingi ey'eSomaliya",
	"BHD_displayName": "Dinaali ey'eBaareeni",
	"XOF_displayName": "Faranga ey'omu Afirika ey'ebugwanjuba",
	"UGX_symbol": "USh",
	"GNS_displayName": "Faranga ey'eGini",
	"SLL_displayName": "Lewone",
	"UGX_displayName": "Silingi eya Yuganda",
	"MGA_displayName": "Faranga ey'eMalagase",
	"SDP_displayName": "Pawundi ey'eSudaani",
	"AUD_displayName": "Doola ey'Awusiturelya",
	"KES_displayName": "Silingi ey'eKenya",
	"SHP_displayName": "Pawundi ey'eSenti Herena",
	"XAF_displayName": "Faranga ey'omu Afirika eya wakati",
	"LSL_displayName": "Loti ey'eLesoso",
	"MRO_displayName": "Wugwiya ey'eMawritenya",
	"CNY_displayName": "Yuwani Reniminibi ey'eCayina",
	"GMD_displayName": "Dalasi ey'eGambya"
}
//end v1.x content
);