define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMdd": "d.MM",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yyyyMM": "MM.y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "d.MM.y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, d.MM.y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-MEd": "E, d.MM",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd.MM.y G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d.MM",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);