({
	"months-format-narrow": [
		"s", 
		"l", 
		"m", 
		"k", 
		"m", 
		"c", 
		"l", 
		"s", 
		"w", 
		"p", 
		"l", 
		"g"
	], 
	"field-weekday": "Dzień tygodnia", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"dateFormatItem-yMEd": "EEE, d-M-y", 
	"dayPeriods-earlyMorning-format-wide": "nad ranem", 
	"dateFormatItem-MMMEd": "d MMM E", 
	"dayPeriods-evening-format-wide": "wieczorem", 
	"eraNarrow": [
		"p.n.e.", 
		"n.e."
	], 
	"dayPeriods-pm-format-wide": "PM", 
	"dateFormat-long": "d MMMM y", 
	"months-format-wide": [
		"stycznia", 
		"lutego", 
		"marca", 
		"kwietnia", 
		"maja", 
		"czerwca", 
		"lipca", 
		"sierpnia", 
		"września", 
		"października", 
		"listopada", 
		"grudnia"
	], 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dayPeriods-afternoon-format-wide": "po południu", 
	"dateFormatItem-Md": "d-M", 
	"dayPeriods-morning-format-wide": "rano", 
	"field-era": "Era", 
	"dateFormatItem-yM": "M-y", 
	"months-standAlone-wide": [
		"styczeń", 
		"luty", 
		"marzec", 
		"kwiecień", 
		"maj", 
		"czerwiec", 
		"lipiec", 
		"sierpień", 
		"wrzesień", 
		"październik", 
		"listopad", 
		"grudzień"
	], 
	"timeFormat-short": "HH:mm", 
	"quarters-format-wide": [
		"I kwartał", 
		"II kwartał", 
		"III kwartał", 
		"IV kwartał"
	], 
	"timeFormat-long": "HH:mm:ss z", 
	"field-year": "Rok", 
	"dateFormatItem-yQ": "yyyy Q", 
	"dateFormatItem-yyyyMMMM": "LLLL y", 
	"field-hour": "Godzina", 
	"dateFormatItem-MMdd": "dd-MM", 
	"months-format-abbr": [
		"sty", 
		"lut", 
		"mar", 
		"kwi", 
		"maj", 
		"cze", 
		"lip", 
		"sie", 
		"wrz", 
		"paź", 
		"lis", 
		"gru"
	], 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"sty", 
		"lut", 
		"mar", 
		"kwi", 
		"maj", 
		"cze", 
		"lip", 
		"sie", 
		"wrz", 
		"paź", 
		"lis", 
		"gru"
	], 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"quarters-standAlone-wide": [
		"I kwartał", 
		"II kwartał", 
		"III kwartał", 
		"IV kwartał"
	], 
	"dateFormatItem-M": "L", 
	"days-standAlone-wide": [
		"niedziela", 
		"poniedziałek", 
		"wtorek", 
		"środa", 
		"czwartek", 
		"piątek", 
		"sobota"
	], 
	"dateFormatItem-MMMMd": "d MMMM", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"timeFormat-medium": "HH:mm:ss", 
	"dayPeriods-am-format-wide": "AM", 
	"dateFormatItem-Hm": "HH:mm", 
	"quarters-standAlone-abbr": [
		"1 kw.", 
		"2 kw.", 
		"3 kw.", 
		"4 kw."
	], 
	"eraAbbr": [
		"p.n.e.", 
		"n.e."
	], 
	"field-minute": "Minuta", 
	"field-dayperiod": "Dayperiod", 
	"days-standAlone-abbr": [
		"niedz.", 
		"pon.", 
		"wt.", 
		"śr.", 
		"czw.", 
		"pt.", 
		"sob."
	], 
	"dateFormatItem-d": "d", 
	"dateFormatItem-ms": "mm:ss", 
	"dateFormatItem-h": "hh a", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-MEd": "E, d-M", 
	"dateFormatItem-yMMMM": "LLLL y", 
	"field-day": "Dzień", 
	"days-format-wide": [
		"niedziela", 
		"poniedziałek", 
		"wtorek", 
		"środa", 
		"czwartek", 
		"piątek", 
		"sobota"
	], 
	"field-zone": "Strefa", 
	"dateFormatItem-yyyyMM": "yyyy-MM", 
	"dateFormatItem-y": "y", 
	"months-standAlone-narrow": [
		"s", 
		"l", 
		"m", 
		"k", 
		"m", 
		"c", 
		"l", 
		"s", 
		"w", 
		"p", 
		"l", 
		"g"
	], 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-hm": "hh:mm a", 
	"days-format-abbr": [
		"niedz.", 
		"pon.", 
		"wt.", 
		"śr.", 
		"czw.", 
		"pt.", 
		"sob."
	], 
	"eraNames": [
		"p.n.e.", 
		"n.e."
	], 
	"days-format-narrow": [
		"N", 
		"P", 
		"W", 
		"Ś", 
		"C", 
		"P", 
		"S"
	], 
	"field-month": "Miesiąc", 
	"days-standAlone-narrow": [
		"N", 
		"P", 
		"W", 
		"Ś", 
		"C", 
		"P", 
		"S"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-night-format-wide": "w nocy", 
	"dateFormat-short": "dd-MM-yy", 
	"field-second": "Sekunda", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"dayPeriods-lateMorning-format-wide": "przed południem", 
	"field-week": "Tydzień", 
	"dateFormat-medium": "dd-MM-yyyy", 
	"dayPeriods-noon-format-wide": "w południe", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-hms": "hh:mm:ss a"
})