define(
//begin v1.x content
{
	"dateFormatItem-GyMMM": "U年MMM",
	"dateFormat-medium": "U年MMMd日",
	"dateFormatItem-yMd": "U年M月d日",
	"dateFormatItem-MMMEd": "MMMd日E",
	"dateFormatItem-MEd": "M/dE",
	"dateFormatItem-yyyyMMM": "U年MMM",
	"dateFormatItem-GyMMMd": "U年MMMd日",
	"dateFormatItem-y": "U年",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyQQQQ": "U年QQQQ",
	"months-standAlone-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"十一",
		"十二"
	],
	"dateFormatItem-GyMMMEd": "U年MMMd日E",
	"dateFormatItem-M": "MMM",
	"dateFormatItem-yyyyMMMEd": "U年MMMd日E",
	"dateFormatItem-yyyyMEd": "U年M月d日，E",
	"dateFormatItem-yyyy": "U年",
	"dateFormat-long": "U年MMMd日",
	"dateFormatItem-yyyyQQQ": "U年QQQQ",
	"dateFormat-short": "U/M/d",
	"months-format-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"十二月"
	],
	"dateFormatItem-Gy": "U年",
	"dateFormatItem-d": "d日",
	"dateFormatItem-yyyyMMMd": "U年MMMd日",
	"dateFormatItem-yyyyM": "U年M月",
	"dateFormat-full": "U年MMMd日EEEE",
	"dateFormatItem-MMMd": "MMMd日",
	"dateFormatItem-yyyyMd": "U年M月d日",
	"dateFormatItem-Ed": "d日E"
}
//end v1.x content
);