define(
//begin v1.x content
{
	"dateFormat-medium": "Gy/M/d",
	"dateFormatItem-MMMEd": "M月d日E",
	"dateFormatItem-MEd": "M/d（E）",
	"dateFormatItem-MMdd": "MM/dd",
	"dateFormatItem-yyyyMMM": "Gy年M月",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-H": "H時",
	"dateFormatItem-hm": "ah:mm",
	"dateFormatItem-Md": "M/d",
	"months-standAlone-wide": [
		"穆哈蘭姆月",
		"色法爾月",
		"賴比月 I",
		"賴比月 II",
		"主馬達月 I",
		"主馬達月 II",
		"賴哲卜月",
		"舍爾邦月",
		"賴買丹月",
		"閃瓦魯月",
		"都爾喀爾德月",
		"都爾黑哲月"
	],
	"dateFormatItem-M": "M月",
	"dateFormatItem-yyyy": "Gy年",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormat-long": "Gy年M月d日",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "Gy/M/d",
	"months-format-wide": [
		"穆哈蘭姆月",
		"色法爾月",
		"賴比月 I",
		"賴比月 II",
		"主馬達月 I",
		"主馬達月 II",
		"賴哲卜月",
		"舍爾邦月",
		"賴買丹月",
		"閃瓦魯月",
		"都爾喀爾德月",
		"都爾黑哲月"
	],
	"dateFormatItem-d": "d日",
	"dateFormatItem-MMMMdd": "M月dd日",
	"dateFormatItem-yyyyMMMd": "Gy年M月d日",
	"dateFormatItem-h": "ah時",
	"dateFormatItem-yyyyM": "Gy/M",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "Gy年M月d日EEEE",
	"dateFormatItem-MMMd": "M月d日",
	"dateFormatItem-yyyyMd": "Gy/M/d",
	"dateFormatItem-yyyyQ": "Gy年QQQ",
	"dateFormatItem-Ed": "d日（E）"
}
//end v1.x content
);