define(
//begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"dateFormatItem-yQ": "y年QQQ",
	"dayPeriods-format-wide-pm": "下午",
	"dateFormatItem-MMMEd": "M月d日E",
	"dateTimeFormat-full": "{1}{0}",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yQQQ": "y年QQQ",
	"dateFormatItem-MMdd": "MM/dd",
	"days-standAlone-wide": [
		"星期日",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "上午",
	"quarters-standAlone-abbr": [
		"一季度",
		"二季度",
		"三季度",
		"四季度"
	],
	"timeFormat-full": "zzzzah時mm分ss秒",
	"dateFormatItem-yyyy": "Gy年",
	"months-standAlone-abbr": [
		"穆哈蘭姆月",
		"色法爾月",
		"賴比月 I",
		"賴比月 II",
		"主馬達月 I",
		"主馬達月 II",
		"賴哲卜月",
		"舍爾邦月",
		"賴買丹月",
		"閃瓦魯月",
		"都爾喀爾德月",
		"都爾黑哲月"
	],
	"dateFormatItem-Ed": "d日（E）",
	"days-standAlone-narrow": [
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六"
	],
	"dateFormat-long": "Gy年M月d日",
	"timeFormat-medium": "ah:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "Gy/M/d",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "y/M/d",
	"quarters-standAlone-wide": [
		"第一季度",
		"第二季度",
		"第三季度",
		"第四季度"
	],
	"dateFormatItem-ms": "mm:ss",
	"dateTimeFormat-long": "{1}{0}",
	"months-standAlone-wide": [
		"穆哈蘭姆月",
		"色法爾月",
		"賴比月 I",
		"賴比月 II",
		"主馬達月 I",
		"主馬達月 II",
		"賴哲卜月",
		"舍爾邦月",
		"賴買丹月",
		"閃瓦魯月",
		"都爾喀爾德月",
		"都爾黑哲月"
	],
	"dateFormatItem-yyyyMd": "Gy/M/d",
	"dateFormatItem-yyyyMMMd": "Gy年M月d日",
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "zah時mm分ss秒",
	"months-format-abbr": [
		"穆哈蘭姆月",
		"色法爾月",
		"賴比月 I",
		"賴比月 II",
		"主馬達月 I",
		"主馬達月 II",
		"賴哲卜月",
		"舍爾邦月",
		"賴買丹月",
		"閃瓦魯月",
		"都爾喀爾德月",
		"都爾黑哲月"
	],
	"timeFormat-short": "ah:mm",
	"dateFormatItem-H": "H時",
	"quarters-format-abbr": [
		"1季",
		"2季",
		"3季",
		"4季"
	],
	"dateFormatItem-MMMMdd": "M月dd日",
	"days-format-abbr": [
		"週日",
		"週一",
		"週二",
		"週三",
		"週四",
		"週五",
		"週六"
	],
	"dateFormatItem-M": "M月",
	"days-format-narrow": [
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六"
	],
	"dateFormatItem-yMMMd": "y年M月d日",
	"dateFormatItem-MEd": "M/d（E）",
	"dateFormatItem-hm": "ah:mm",
	"days-standAlone-abbr": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"dateFormat-short": "Gy/M/d",
	"dateFormatItem-yyyyM": "Gy/M",
	"dateFormat-full": "Gy年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyQ": "Gy年QQQ",
	"dateFormatItem-yMEd": "y/M/d（E）",
	"months-format-wide": [
		"穆哈蘭姆月",
		"色法爾月",
		"賴比月 I",
		"賴比月 II",
		"主馬達月 I",
		"主馬達月 II",
		"賴哲卜月",
		"舍爾邦月",
		"賴買丹月",
		"閃瓦魯月",
		"都爾喀爾德月",
		"都爾黑哲月"
	],
	"dateFormatItem-yyyyMMM": "Gy年M月",
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"第1季",
		"第2季",
		"第3季",
		"第4季"
	],
	"days-format-wide": [
		"星期日",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六"
	],
	"dateFormatItem-h": "ah時"
}
//end v1.x content
);