define(
//begin v1.x content
{
	"field-sat-relative+0": "dizze sneon",
	"field-sat-relative+1": "folgjende wike sneon",
	"field-sun-relative+-1": "ôfrûne snein",
	"field-mon-relative+-1": "ôfrûne moandei",
	"field-day-relative+-1": "gisteren",
	"field-day-relative+-2": "eergisteren",
	"field-sun-relative+0": "dizze snein",
	"field-sun-relative+1": "folgjende wike snein",
	"field-wed-relative+-1": "ôfrûne woansdei",
	"field-day-relative+0": "vandaag",
	"field-day-relative+1": "morgen",
	"field-day-relative+2": "Oermorgen",
	"field-tue-relative+0": "dizze tiisdei",
	"field-tue-relative+1": "folgjende wike tiisdei",
	"field-week-relative+-1": "foarige wike",
	"field-year-relative+0": "dit jier",
	"field-year-relative+1": "folgjend jier",
	"field-sat-relative+-1": "ôfrûne sneon",
	"field-year-relative+-1": "foarich jier",
	"field-fri-relative+0": "dizze freed",
	"field-fri-relative+1": "folgjende wike freed",
	"field-week-relative+0": "dizze wike",
	"field-week-relative+1": "folgjende wike",
	"field-month-relative+0": "dizze moanne",
	"field-month-relative+1": "folgjende moanne",
	"field-fri-relative+-1": "ôfrûne freed",
	"field-tue-relative+-1": "ôfrûne tiisdei",
	"field-mon-relative+0": "dizze moandei",
	"field-mon-relative+1": "folgjende wike moandei",
	"field-thu-relative+0": "dizze tongersdei",
	"field-second-relative+0": "nu",
	"field-thu-relative+1": "folgjende wike tongersdei",
	"field-wed-relative+0": "dizze woansdei",
	"field-wed-relative+1": "folgjende wike woansdei",
	"field-month-relative+-1": "foarige moanne",
	"field-thu-relative+-1": "ôfrûne tongersdei"
}
//end v1.x content
);