define([
	'./AdapterRegistry',
	'./Evented',
	'./Stateful',
	'./_base',
	'./colors',
	'./currency',
	'./date',
	'./date/locale',
	'./date/stamp',
	'./fx/easing',
	'./io-query',
	'./json',
	'./on',
	'./promise',
	'./regexp',
	'./request',
	'./store',
	'./string',
	'./topic',
	'./when',

	//  // host-specific tests
	'dojo/has!host-browser?./dom-form',
	'dojo/has!host-browser?./hash',
	'dojo/has!host-browser?./io/iframe',
	'dojo/has!host-browser?./mouse',
	'dojo/has!host-node?./node',
	'dojo/has!host-browser?./require/require',
	'dojo/has!host-browser?./router'
], function () {});
