define(
//begin v1.x content
{
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"field-week": "Lóokuŋ",
	"dateFormatItem-Hm": "HH:mm",
	"field-day-relative+-1": "Fucen",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-M": "L",
	"field-year": "Emit",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+0": "Jaat",
	"field-day-relative+1": "Kajom",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "d MMMM y G",
	"field-day": "Funak",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-dayperiod": "Bujom / Kalíim",
	"dateFormatItem-ms": "m:ss",
	"field-month": "Fuleeŋ",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormatItem-d": "d",
	"field-era": "Jamanay",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-Ed": "E d"
}
//end v1.x content
);