define(
//begin v1.x content
{
	"USD_displayName": "Doora ya America",
	"TZS_displayName": "Eshiringi ya Tanzania",
	"ZMW_displayName": "Kwacha ya Zambia",
	"MAD_displayName": "Dirram ya Moroko",
	"NGN_displayName": "Naira ya Naigyeriya",
	"ZWD_displayName": "Doora ya Zimbabwe",
	"SDG_displayName": "Dinari ya Sudani",
	"MWK_displayName": "Kwaca ya Malawi",
	"KMF_displayName": "Faranga ya Komoro",
	"SCR_displayName": "Rupiiha ya Sherisheri",
	"EGP_displayName": "Paundi ya Misiri",
	"CVE_displayName": "Eskudo ya Kepuvede",
	"LYD_displayName": "Dinari ya Libya",
	"CAD_displayName": "Doora ya Kanada",
	"INR_displayName": "Rupiya ya India",
	"JPY_displayName": "Yeni ya Japaani",
	"LRD_displayName": "Doora ya Liberia",
	"ZAR_displayName": "Randi ya Sausi Afirika",
	"AOA_displayName": "Kwanza ya Angora",
	"TND_displayName": "Dinari ya Tunisia",
	"GHC_displayName": "Cedi ya Ghana",
	"BWP_displayName": "Pura ya Botswana",
	"DZD_displayName": "Dinari ya Arigyeriya",
	"ZMK_displayName": "Kwacha ya Zambia (1968–2012)",
	"NAD_displayName": "Doora ya Namibiya",
	"AED_displayName": "Dirham za Buharabu",
	"ETB_displayName": "Birr ya Ethiopiya",
	"MZM_displayName": "Metikari ya Mozambikwi",
	"BIF_displayName": "Faranga ya Burundi",
	"RWF_displayName": "Faranga ya Rwanda",
	"STD_displayName": "Dobra ya Sao Tome na Purinsipo",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakfa ya Eritireya",
	"SAR_displayName": "Riya ya Saudi",
	"DJF_displayName": "Faranga ya Gyibuti",
	"CDF_displayName": "Faranga ya Kongo",
	"GBP_displayName": "Paundi ya Bungyereza",
	"CHF_displayName": "Faranga ya Swisi",
	"MUR_displayName": "Rupiiha ya Mauritiasi",
	"SOS_displayName": "Eshiringi ya Somalia",
	"BHD_displayName": "Dinari ya Bahareni",
	"XOF_displayName": "Faranga ya CFA BCEAO",
	"UGX_symbol": "USh",
	"GNS_displayName": "Faranga ya Guinea",
	"SLL_displayName": "Leone",
	"UGX_displayName": "Eshiringi ya Uganda",
	"MGA_displayName": "Ariari ya Maragariita",
	"SDP_displayName": "Paundi ya Sudan",
	"AUD_displayName": "Doora ya Austureeriya",
	"KES_displayName": "Shiringi ya Kenya",
	"SHP_displayName": "Paundi ya Senti Herena",
	"XAF_displayName": "Faranga ya CFA BEAC",
	"LSL_displayName": "Loti ya Lesoto",
	"MRO_displayName": "Ougwiya ya Mouriteeniya",
	"CNY_displayName": "Yuan Renminbi ya China",
	"GMD_displayName": "Dalasi ya Gambia"
}
//end v1.x content
);