define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-minute": "idakika",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "n'chana",
	"field-weekday": "nihuku no mwisho wa wiki",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "kal'lai",
	"field-hour": "isaa",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "lel'lo",
	"field-day-relative+1": "me'llo",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "yaka",
	"field-week": "iwiki mocha",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "mweri",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d, y",
	"field-second": "isekunde",
	"field-day": "nihuku",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);