define(
//begin v1.x content
{
	"field-second-relative+0": "азыр",
	"field-weekday": "апта күнү",
	"field-wed-relative+0": "ушул Шаршембиде",
	"field-wed-relative+1": "эмки Шаршембиде",
	"dateFormatItem-GyMMMEd": "G y-'ж'. d-MMM, E",
	"dateFormatItem-MMMEd": "d-MMM, E",
	"field-tue-relative+-1": "өткөн Шейшембиде",
	"dateFormat-long": "d-MMMM G y-'ж'.",
	"field-fri-relative+-1": "өткөн Жума көнү",
	"field-wed-relative+-1": "өткөн Шаршембиде",
	"dateFormatItem-yyyyQQQ": "G y-'ж'. QQQ",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE, G d-MMMM y-'ж'.",
	"dateFormatItem-yyyyMEd": "GGGGG y-MM-dd, E",
	"field-thu-relative+-1": "өткөн Бейшембиде",
	"dateFormatItem-Md": "MM-dd",
	"field-era": "заман",
	"field-year": "жыл",
	"field-hour": "саат",
	"field-sat-relative+0": "ушул Ишембиде",
	"field-sat-relative+1": "келерки Ишембиде",
	"field-day-relative+0": "бүгүн",
	"field-thu-relative+0": "ушул Бейшембиде",
	"field-day-relative+1": "эртеӊ",
	"field-thu-relative+1": "эмдиги Бейшембиде",
	"dateFormatItem-GyMMMd": "G y-'ж'. d-MMM",
	"field-day-relative+2": "бүрсүгүнү",
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-yyyyMMMEd": "G y-'ж'. d-MMM, E",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "G y-'ж'. MMM",
	"dateFormatItem-yyyyMMMd": "G y-'ж'. d-MMM",
	"field-sun-relative+0": "ушул дем алышта",
	"field-sun-relative+1": "келерки дем алышта",
	"field-minute": "мүнөт",
	"field-dayperiod": "ТЧ/ТК",
	"dateFormatItem-d": "d",
	"field-day-relative+-1": "кечээ",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "мурдагы күнү",
	"dateFormatItem-MMMd": "d-MMM",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "ушул Жума күнү",
	"field-fri-relative+1": "эмдиги Жума күнү",
	"field-day": "күн",
	"field-zone": "саат алкагы",
	"dateFormatItem-y": "y-G",
	"field-year-relative+-1": "былтыр",
	"field-month-relative+-1": "өткөн айда",
	"dateFormatItem-yyyyMd": "GGGGG y-MM-dd",
	"field-month": "ай",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "ушул Шейшембиде",
	"field-tue-relative+1": "эмки Шейшембиде",
	"field-mon-relative+0": "ушул Дүйшөмбүдө",
	"field-mon-relative+1": "кийинки Дүйшөмбүдө",
	"dateFormat-short": "dd.MM.y GGGGG",
	"field-second": "секунд",
	"field-sat-relative+-1": "өткөн Ишембиде",
	"field-sun-relative+-1": "өткөн дем алышта",
	"field-month-relative+0": "бул айда",
	"field-month-relative+1": "эмдиги айда",
	"dateFormatItem-Ed": "d, E",
	"field-week": "апта",
	"dateFormat-medium": "dd.MM.y G",
	"field-year-relative+0": "быйыл",
	"field-week-relative+-1": "өткөн аптада",
	"dateFormatItem-yyyyM": "GGGGG y-MM",
	"field-year-relative+1": "эмдиги жылы",
	"dateFormatItem-yyyyQQQQ": "G y-'ж'. QQQQ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-GyMMM": "G y MMM",
	"field-mon-relative+-1": "өткөн Дүйшөмбүдө",
	"dateFormatItem-yyyy": "y-G",
	"field-week-relative+0": "ушул аптада",
	"field-week-relative+1": "келерки аптада"
}
//end v1.x content
);