define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-MMM": "MMM",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E 'd'. d.",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-yyyyMEd": "E d/M/y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "M",
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "h.mm a",
	"dateFormat-short": "d/M/y",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d.",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);