define(
//begin v1.x content
{
	"field-weekday": "ugedag",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E. d/M/y",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormat-long": "d. MMM y",
	"months-format-wide": [
		"januar",
		"februar",
		"marts",
		"april",
		"maj",
		"juni",
		"juli",
		"august",
		"september",
		"oktober",
		"november",
		"december"
	],
	"dayPeriods-format-wide-pm": "e.m.",
	"dateFormat-full": "EEEE 'den' d. MMMM y",
	"dateFormatItem-Md": "d/M",
	"dayPeriods-format-wide-noon": "middag",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "æra",
	"dateFormatItem-yM": "M/y",
	"timeFormat-short": "HH.mm",
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"timeFormat-long": "HH.mm.ss z",
	"field-year": "år",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q yyyy",
	"dateFormatItem-MMdd": "dd/MM",
	"field-hour": "time",
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mar.",
		"apr.",
		"maj",
		"jun.",
		"jul.",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"dateFormatItem-yyQ": "Q. 'kvartal' yy",
	"timeFormat-full": "HH.mm.ss zzzz",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgen",
	"field-day-relative+2": "i overmorgen",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"maj",
		"jun",
		"jul",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"dateFormatItem-M": "M",
	"dateFormatItem-yyyyMMM": "MMM y",
	"dayPeriods-format-abbr-noon": "middag",
	"dateFormatItem-yyMMM": "MMM yy",
	"timeFormat-medium": "HH.mm.ss",
	"dateFormatItem-Hm": "HH.mm",
	"eraAbbr": [
		"f.Kr.",
		"e.Kr."
	],
	"field-minute": "minut",
	"field-dayperiod": "dagtid",
	"dateFormatItem-d": "d.",
	"dateFormatItem-ms": "mm.ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "i går",
	"field-day-relative+-2": "i forgårs",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E. d/M",
	"field-day": "dag",
	"days-format-wide": [
		"søndag",
		"mandag",
		"tirsdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lørdag"
	],
	"field-zone": "tidszone",
	"dateFormatItem-yyyyMM": "MM/yyyy",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-year-relative+-1": "Sidste år",
	"field-month-relative+-1": "Sidste måned",
	"dateFormatItem-yyMM": "MM/yy",
	"dateFormatItem-hm": "h.mm a",
	"days-format-abbr": [
		"søn",
		"man",
		"tir",
		"ons",
		"tor",
		"fre",
		"lør"
	],
	"dateFormatItem-yMMMd": "d. MMM y",
	"eraNames": [
		"f.Kr.",
		"e.Kr."
	],
	"field-month": "måned",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"dateFormatItem-MMM": "MMM",
	"dayPeriods-format-wide-am": "f.m.",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormat-short": "dd/MM/yy",
	"dayPeriods-format-narrow-noon": "middag",
	"field-second": "sekund",
	"dateFormatItem-yMMMEd": "E. d. MMM y",
	"field-month-relative+0": "Denne måned",
	"field-month-relative+1": "Næste måned",
	"dateFormatItem-Ed": "E d.",
	"field-week": "uge",
	"dateFormat-medium": "dd/MM/yyyy",
	"field-year-relative+0": "I år",
	"field-week-relative+-1": "Sidste uge",
	"field-year-relative+1": "Næste år",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-yyyy": "y",
	"field-week-relative+0": "Denne uge",
	"field-week-relative+1": "Næste uge"
}
//end v1.x content
);