define(
//begin v1.x content
{
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormatItem-H": "HH",
	"dateFormatItem-yyMMM": "MMM y G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-hm": "h.mm a",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateFormatItem-M": "M",
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-yyyyMEd": "E d/M/y GGGGG",
	"dateFormatItem-yyyyMM": "MM/y GGGGG",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyMM": "MM/y GGGGG",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-ms": "mm.ss",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-d": "d.",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-MMM": "MMM",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"dateFormatItem-Ed": "E d."
}
//end v1.x content
);