define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "གཟའ་E, G ལོy ཟླ་MMM ཚེ་d",
	"field-dayperiod": "སྔ་ཆ/ཕྱི་ཆ་",
	"field-minute": "སྐར་མ",
	"dateFormatItem-MMMEd": "E, སྤྱི་LLL ཚེ་d",
	"dateTimeFormat-full": "{1} {0}",
	"field-day-relative+-1": "ཁ་ཙ་",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-day-relative+-2": "ཁ་ཉིམ",
	"field-weekday": "བདུན་ཕྲག་གི་ཉིམ",
	"dateFormatItem-MMM": "སྤྱི་LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "G y",
	"dateTimeFormat-medium": "{1} {0}",
	"field-era": "དུས་བསྐལ",
	"field-hour": "ཆུ་ཚོད",
	"dateFormatItem-y": "G y",
	"dateFormatItem-yyyy": "G y",
	"dateFormatItem-Ed": "d E",
	"field-day-relative+0": "ད་རིས་",
	"field-day-relative+1": "ནངས་པ་",
	"field-day-relative+2": "གནངས་ཚེ",
	"dateFormatItem-GyMMMd": "G y MMM d",
	"dateFormat-long": "G སྤྱི་ལོ་y MMMM ཚེས་ dd",
	"field-zone": "དུས་ཀུལ",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "G སྤྱི་ལོ་y ཟླ་MMM ཚེས་dd",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"field-year": "ལོ",
	"dateTimeFormat-long": "{1} {0}",
	"field-week": "བདུན་ཕྲག",
	"dateFormatItem-yyyyMd": "G y-M-d",
	"dateFormatItem-yyyyMMMd": "G y MMM d",
	"dateFormatItem-yyyyMEd": "E, G y-M-d",
	"dateFormatItem-MMMd": "སྤྱི་LLL ཚེ་d",
	"dateFormatItem-H": "ཆུ་ཚོད་HH",
	"field-month": "ཟླ་ཝ་",
	"dateFormatItem-M": "L",
	"field-second": "སྐར་ཆཱ་",
	"dateFormatItem-GyMMMEd": "གཟའ་E, G ལོy ཟླ་MMM ཚེ་d",
	"dateFormatItem-GyMMM": "G y སྤྱི་ཟླ་MMM",
	"field-day": "ཚེས་",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-yyyyQQQ": "G y QQQ",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG y-MM-dd",
	"dateFormatItem-yyyyM": "G y-M",
	"dateFormat-full": "EEEE, G སྤྱི་ལོ་y MMMM ཚེས་dd",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yyyyMMM": "G y སྤྱི་ཟླ་MMM",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "ཆུ་ཚོད་h a"
}
//end v1.x content
);