define(
//begin v1.x content
{
	"BRE_displayName": "cruzeiro brasilian (1990–1993)",
	"DEM_displayName": "marc tudestg",
	"CUP_displayName": "peso cuban",
	"PYG_displayName": "guarani paraguaian",
	"CLE_displayName": "escudo chilen",
	"MDC_displayName": "cupon moldav",
	"MDL_displayName": "leu moldav",
	"DOP_displayName": "peso dominican",
	"NGN_displayName": "naira nigeriana",
	"KZT_displayName": "tenge casac",
	"MXV_displayName": "unidad de inversion mexicana (UDI)",
	"LTT_displayName": "talonas lituan",
	"LAK_displayName": "kip laot",
	"LKR_displayName": "rupia da la Sri Lanka",
	"AOR_displayName": "kwanza angolan reajustado",
	"USS_displayName": "dollar dals Stadis Unids da l'America (medem di)",
	"MNT_displayName": "tugrik mongolic",
	"RHD_displayName": "dollar rodesian",
	"MOP_displayName": "pataca dal Macao",
	"TJR_displayName": "rubel dal Tadschikistan",
	"LUC_displayName": "franc convertibel luxemburgais",
	"LUL_displayName": "franc finanzial luxemburgais",
	"AON_displayName": "nov kwanza angolan",
	"BEF_displayName": "franc beltg",
	"GHS_displayName": "cedi ghanais",
	"IEP_displayName": "glivra indonaisa",
	"SBD_displayName": "dollar da las Salomonas",
	"KRO_displayName": "vegl won da la Corea dal Sid",
	"GRD_displayName": "drachma greca",
	"NIC_displayName": "cordoba nicaraguan",
	"AZM_displayName": "manat aserbaidschanic (1993–2006)",
	"MTP_displayName": "glivra maltaisa",
	"MKN_displayName": "vegl dinar macedon",
	"LVR_displayName": "rubel letton",
	"GNF_displayName": "franc da la Guinea",
	"GIP_displayName": "glivra da Gibraltar",
	"SRG_displayName": "flurin surinam",
	"BAD_displayName": "dinar da la Bosnia ed Erzegovina",
	"FJD_displayName": "dollar dal Fidschi",
	"BAM_displayName": "marc convertibel bosniac",
	"CDF_displayName": "franc congolais",
	"HRD_displayName": "dinar croat",
	"BZD_displayName": "dollar dal Belize",
	"MLF_displayName": "franc dal Mali",
	"EGP_displayName": "glivra egipziana",
	"MVR_displayName": "rufiyaa da las Maledivas",
	"BAN_displayName": "nov dinar da la Bosnia ed Erzegovina",
	"TRY_displayName": "nova lira tirca",
	"ILR_displayName": "vegl sheqel israelian",
	"SDP_displayName": "glivra sudanaisa (1956–2007)",
	"XRE_displayName": "fonds RINET",
	"ARM_displayName": "peso argentin moneda nacional",
	"NPR_displayName": "rupia nepalaisa",
	"PHP_displayName": "peso filippin",
	"WST_displayName": "tala da la Samoa",
	"TRL_displayName": "lira tirca",
	"JPY_displayName": "yen giapunais",
	"TMM_displayName": "manat turkmen",
	"BGN_displayName": "nov lev bulgar",
	"KYD_displayName": "dollar da las Inslas Cayman",
	"VUV_displayName": "vatu dal Vanuatu",
	"IRR_displayName": "rial iranais",
	"DJF_displayName": "franc dal Dschibuti",
	"XDR_displayName": "dretgs da prelevaziun spezials",
	"ECS_displayName": "sucre equadorian",
	"NLG_displayName": "flurin ollandais",
	"ISJ_displayName": "veglia cruna islandaisa",
	"MWK_displayName": "kwacha dal Malawi",
	"HTG_displayName": "gourde haitian",
	"PES_displayName": "sol peruan",
	"LYD_displayName": "dinar libic",
	"BRR_displayName": "cruzeiro brasilian",
	"XXX_displayName": "valuta nunenconuschenta",
	"IDR_displayName": "rupia indonaisa",
	"USD_displayName": "dollar dals Stadis Unids da l'America",
	"KGS_displayName": "som kirghis",
	"BRN_displayName": "cruzado novo brasilian",
	"CHF_displayName": "franc svizzer",
	"ISK_displayName": "cruna islandaisa",
	"LUF_displayName": "franc luxemburgais",
	"SVC_displayName": "colon da l'El Salvador",
	"ZMK_displayName": "kwacha da la sambia (1968–2012)",
	"TOP_displayName": "pa'anga da Tonga",
	"ITL_displayName": "lira taliana",
	"USN_displayName": "dollar dals Stadis Unids da l'America (proxim di)",
	"KWD_displayName": "dinar dal Kuwait",
	"NIO_displayName": "cordoba oro nicaraguan",
	"KMF_displayName": "franc comorian",
	"UYI_displayName": "peso da l'Uruguay (unidades indexadas)",
	"MYR_displayName": "ringgit da la Malaisia",
	"XFU_displayName": "franc UIC franzos",
	"GMD_displayName": "dalasi gambic",
	"LVL_displayName": "lats letton",
	"AUD_displayName": "dollar australian",
	"XPF_displayName": "franc CFP",
	"LBP_displayName": "glivra libanaisa",
	"ALK_displayName": "lek albanais (1947–1961)",
	"BYB_displayName": "nov rubel bieloruss (1994–1999)",
	"MKD_displayName": "dinar da la Macedonia",
	"GWP_displayName": "peso da la Guinea-Bissau",
	"CNY_displayName": "yuan renminbi chinais",
	"MAF_displayName": "franc marocan",
	"JOD_displayName": "dinar jordanic",
	"OMR_displayName": "rial da l'Oman",
	"BOV_displayName": "mvdol bolivian",
	"XPT_displayName": "platin",
	"NOK_displayName": "cruna norvegiaisa",
	"SCR_displayName": "rupia da las Seychellas",
	"XBA_displayName": "unitad europeica cumponida",
	"CSK_displayName": "cruna tschecoslovaca",
	"PLZ_displayName": "zloty polac (1950–1995)",
	"UAK_displayName": "karbovanetz ucranais",
	"MGF_displayName": "franc madagasc",
	"GNS_displayName": "syli da la Guinea",
	"YUN_displayName": "dinar jugoslav convertibel",
	"GYD_displayName": "dollar da la Guyana",
	"QAR_displayName": "riyal da Katar",
	"ALL_displayName": "lek",
	"BBD_displayName": "dollar da Barbados",
	"RON_displayName": "leu rumen",
	"AMD_displayName": "dram armen",
	"ARL_displayName": "peso argentin ley",
	"CYP_displayName": "glivra cipriota",
	"SEK_displayName": "cruna svedaisa",
	"MMK_displayName": "Kyat dal Myanmar",
	"ZAR_displayName": "rand sidafrican",
	"ECV_displayName": "unitad da scuntrada da l'Ecuador",
	"BGM_displayName": "lev bulgar socialistic",
	"AWG_displayName": "flurin da l'Aruba",
	"STD_displayName": "dobra da São Tomé e Principe",
	"CAD_displayName": "dollar canadais",
	"ADP_displayName": "peseta andorrana",
	"MRO_displayName": "ouguiya da la Mauretania",
	"ESB_displayName": "peseta spagnola (conto convertibel)",
	"LSL_displayName": "loti dal Lesotho",
	"TND_displayName": "dinar tunesian",
	"BRC_displayName": "cruzado brasilian",
	"BMD_displayName": "dollar da las Bermudas",
	"BRL_displayName": "real brasilian",
	"JMD_displayName": "dollar giamaican",
	"SOS_displayName": "schilling somalian",
	"SAR_displayName": "riyal saudit",
	"PEI_displayName": "inti peruan",
	"ESP_displayName": "peseta spagnola",
	"HKD_displayName": "dollar da Hongkong",
	"BWP_displayName": "pula da la Botswana",
	"TTD_displayName": "dollar da Trinidad e Tobago",
	"BRZ_displayName": "vegl cruzeiro brasilian",
	"BSD_displayName": "dollar da las Bahamas",
	"BIF_displayName": "franc dal Burundi",
	"FRF_displayName": "franc franzos",
	"DKK_displayName": "cruna danaisa",
	"AED_displayName": "dirham dals Emirats Arabs Unids",
	"AOK_displayName": "kwanza angolan (1977–1990)",
	"ATS_displayName": "schilling austriac",
	"PEN_displayName": "nov sol peruan",
	"CRC_displayName": "colon da la Costa Rica",
	"PAB_displayName": "balboa dal Panama",
	"CHE_displayName": "euro WIR",
	"GQE_displayName": "ekwele da la Guinea Equatoriala",
	"DZD_displayName": "dinar algerian",
	"EEK_displayName": "cruna estona",
	"YDD_displayName": "dinar dal Jemen",
	"GHC_displayName": "cedi ghanais (1979–2007)",
	"MXP_displayName": "peso d'argient mexican (1861–1992)",
	"XPD_displayName": "palladi",
	"KRH_displayName": "hwan da la Corea dal Sid",
	"XAG_displayName": "argient",
	"AFN_displayName": "afghani",
	"XFO_displayName": "franc d'aur franzos",
	"GWE_displayName": "escudo da la Guinea Portugaisa",
	"BOB_displayName": "boliviano",
	"VND_displayName": "dong vietnamais",
	"AFA_displayName": "afghani (1927–2002)",
	"ZWD_displayName": "dollar dal Simbabwe",
	"SRD_displayName": "dollar surinam",
	"ZRN_displayName": "nov zaire dal Zaire",
	"XAU_displayName": "aur",
	"BOP_displayName": "peso bolivian",
	"XBD_displayName": "unitad dal quint europeica (XBD)",
	"TZS_displayName": "schilling tansanian",
	"BOL_displayName": "vegl boliviano",
	"ROL_displayName": "vegl leu rumen",
	"VNN_displayName": "vegl dong vietnamais",
	"LRD_displayName": "dollar liberian",
	"KRW_displayName": "won da la Corea dal Sid",
	"SHP_displayName": "glivra da Sontg'Elena",
	"MZE_displayName": "escudo dal mozambican",
	"MZN_displayName": "metical dal mozambican",
	"SDD_displayName": "dinar sudanais",
	"HRK_displayName": "kuna croata",
	"FKP_displayName": "glivra dal Falkland",
	"COP_displayName": "peso columbian",
	"YUD_displayName": "dinar jugoslav (1966–1990)",
	"YUM_displayName": "nov dinar jugoslav",
	"THB_displayName": "baht tailandais",
	"UZS_displayName": "sum usbec",
	"MGA_displayName": "ariary madagasc",
	"MVP_displayName": "rupia da las Maledivas",
	"COU_displayName": "unidad de valor real",
	"TWD_displayName": "nov dollar taiwanais",
	"UGS_displayName": "schilling ucranais",
	"YUR_displayName": "dinar jugoslav refurmà",
	"ZAL_displayName": "rand sidafrican (finanzial)",
	"GEL_displayName": "lari georgian",
	"ILP_displayName": "glivra israeliana",
	"DDM_displayName": "marc da la Germania da l'Ost",
	"KES_displayName": "schilling kenian",
	"CZK_displayName": "cruna tscheca",
	"UGX_displayName": "schilling ugandais",
	"BGL_displayName": "lev bulgar",
	"ARP_displayName": "peso argentin (1983–1985)",
	"RUR_displayName": "rubel russ (vegl)",
	"ERN_displayName": "nakfa eritreic",
	"ESA_displayName": "peseta spagnola (conto A)",
	"CLF_displayName": "unidades de fomento chilenas",
	"BRB_displayName": "cruzeiro novo brasilian (1967–1986)",
	"BHD_displayName": "dinar dal Bahrain",
	"SYP_displayName": "glivra siriana",
	"SZL_displayName": "lilangeni dal Swaziland",
	"INR_displayName": "rupia indica",
	"PTE_displayName": "escudo portugais",
	"KPW_displayName": "won da la Corea dal Nord",
	"XOF_displayName": "franc CFA BCEAO",
	"MXN_displayName": "peso mexican",
	"RWF_displayName": "franc ruandais",
	"ETB_displayName": "birr etiopic",
	"LTL_displayName": "litas lituan",
	"BND_displayName": "dollar dal Brunei",
	"SUR_displayName": "rubel sovietic",
	"SKK_displayName": "cruna slovaca",
	"AOA_displayName": "kwanza angolan",
	"CVE_displayName": "escudo dal Cap Verd",
	"XTS_displayName": "code per verifitgar la valuta",
	"CLP_displayName": "peso chilen",
	"HUF_displayName": "forint ungarais",
	"TJS_displayName": "somoni dal Tadschikistan",
	"GBP_displayName": "glivra sterlina",
	"TPE_displayName": "escudo da Timor",
	"BDT_displayName": "taka bangladais",
	"SGD_displayName": "dollar dal Singapur",
	"SLL_displayName": "leone da la Sierra Leone",
	"XAF_displayName": "franc CFA BEAC",
	"MTL_displayName": "lira maltaisa",
	"ZRZ_displayName": "zaire dal Zaire",
	"KHR_displayName": "riel cambodschan",
	"RSD_displayName": "dinar serb",
	"BEC_displayName": "franc beltg (convertibel)",
	"BEL_displayName": "franc beltg (finanzial)",
	"AZN_displayName": "manat aserbaidschanic",
	"FIM_displayName": "marc finlandais",
	"PKR_displayName": "rupia pakistana",
	"UYP_displayName": "nov peso da l'Uruguay (1975–1993)",
	"ZMW_displayName": "kwacha da la sambia",
	"CHW_displayName": "franc WIR",
	"PLN_displayName": "zloty polac",
	"UAH_displayName": "hryvnia ucranais",
	"BTN_displayName": "ngultrum butanais",
	"YER_displayName": "rial dal Jemen",
	"UYU_displayName": "peso da l'Uruguay",
	"CSD_displayName": "vegl dinar serb",
	"VEF_displayName": "bolivar venezuelan",
	"PGK_displayName": "kina da la Papua Nova Guinea",
	"XBC_displayName": "unitad dal quint europeica (XBC)",
	"EUR_displayName": "euro",
	"MUR_displayName": "rupia dal Mauritius",
	"MAD_displayName": "dirham marocan",
	"SDG_displayName": "glivra sudanaisa",
	"BYR_displayName": "rubel bieloruss",
	"VEB_displayName": "bolivar venezuelan (1871–2008)",
	"IQD_displayName": "dinar iracais",
	"MZM_displayName": "vegl metical mozambican",
	"CHF_symbol": "CHF",
	"SIT_displayName": "tolar sloven",
	"XCD_displayName": "dollar da la Caribica Orientala",
	"RUB_displayName": "rubel russ (nov)",
	"BUK_displayName": "Kyat burmais",
	"ILS_displayName": "sheqel",
	"NAD_displayName": "dollar namibian",
	"HNL_displayName": "lempira hondurian",
	"GTQ_displayName": "quetzal da la Guatemala",
	"MCF_displayName": "franc monegas",
	"GEK_displayName": "kupon larit georgian",
	"NZD_displayName": "dollar da la Nova Zelanda",
	"BGO_displayName": "vegl lev bulgar",
	"ARA_displayName": "austral argentin",
	"ARS_displayName": "peso argentin",
	"ANG_displayName": "flurin da las Antillas Olandaisas"
}
//end v1.x content
);