define(
//begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "mesadad dal di",
	"field-minute": "minuta",
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "ier",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd.MM.",
	"field-day-relative+-2": "stersas",
	"field-weekday": "di da l'emna",
	"dateFormatItem-MMM": "LLL",
	"field-era": "epoca",
	"field-hour": "ura",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-yMMdd": "dd.MM.y",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "oz",
	"field-day-relative+1": "damaun",
	"field-day-relative+2": "puschmaun",
	"dateFormat-long": "d 'da' MMMM y G",
	"field-zone": "zona d'urari",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-MMd": "d.MM.",
	"dateFormat-medium": "dd-MM-y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "onn",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"field-week": "emna",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-HHmm": "HH:mm",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "mais",
	"dateFormatItem-H": "H",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"field-second": "secunda",
	"field-day": "Tag",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormat-short": "dd-MM-yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"dateFormat-full": "EEEE, 'ils' d 'da' MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-d": "d"
}
//end v1.x content
);