define(
//begin v1.x content
{
	"field-sat-relative+0": "цієї суботи",
	"field-sat-relative+1": "наступної суботи",
	"field-dayperiod": "Частина доби",
	"field-sun-relative+-1": "минулої неділі",
	"field-mon-relative+-1": "минулого понеділка",
	"field-minute": "Хвилина",
	"field-day-relative+-1": "учора",
	"field-weekday": "День тижня",
	"field-day-relative+-2": "позавчора",
	"field-era": "Ера",
	"field-hour": "Година",
	"field-sun-relative+0": "цієї неділі",
	"field-sun-relative+1": "наступної неділі",
	"field-wed-relative+-1": "минулої середи",
	"field-day-relative+0": "сьогодні",
	"field-day-relative+1": "завтра",
	"field-day-relative+2": "післязавтра",
	"field-tue-relative+0": "цього вівторка",
	"field-zone": "Часовий пояс",
	"field-tue-relative+1": "наступного вівторка",
	"field-week-relative+-1": "минулого тижня",
	"field-year-relative+0": "цього року",
	"field-year-relative+1": "наступного року",
	"field-sat-relative+-1": "минулої суботи",
	"field-year-relative+-1": "минулого року",
	"field-year": "Рік",
	"field-fri-relative+0": "цієї п’ятниці",
	"field-fri-relative+1": "наступної п’ятниці",
	"field-week": "Тиждень",
	"field-week-relative+0": "цього тижня",
	"field-week-relative+1": "наступного тижня",
	"field-month-relative+0": "цього місяця",
	"field-month": "Місяць",
	"field-month-relative+1": "наступного місяця",
	"field-fri-relative+-1": "минулої п’ятниці",
	"field-second": "Секунда",
	"field-tue-relative+-1": "минулого вівторка",
	"field-day": "День",
	"field-mon-relative+0": "цього понеділка",
	"field-mon-relative+1": "наступного понеділка",
	"field-thu-relative+0": "цього четверга",
	"field-second-relative+0": "зараз",
	"field-thu-relative+1": "наступного четверга",
	"field-wed-relative+0": "цієї середи",
	"months-format-wide": [
		"Тот",
		"Бабе",
		"Хатур",
		"Кіхак",
		"Тобе",
		"Амшир",
		"Барамхат",
		"Бармуда",
		"Башнас",
		"Бауна",
		"Абіб",
		"Мисра",
		"Насі"
	],
	"field-wed-relative+1": "наступної середи",
	"field-month-relative+-1": "минулого місяця",
	"field-thu-relative+-1": "минулого четверга"
}
//end v1.x content
);