define(
//begin v1.x content
{
	"days-standAlone-short": [
		"ອ.ທ.",
		"ຈັນ",
		"ຄ",
		"ພ",
		"ພຫ",
		"ວັນສຸກ",
		"ເສົາ"
	],
	"field-second-relative+0": "ຕອນນີ້",
	"field-weekday": "ມື້ຂອງອາທິດ",
	"field-wed-relative+0": "ວັນພຸດນີ້",
	"field-wed-relative+1": "ວັນພຸດໜ້າ",
	"dateFormatItem-GyMMMEd": "G E, d MMM y",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-tue-relative+-1": "ວັນອັງຄານແລ້ວ",
	"days-format-short": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"dateFormat-long": "d MMMM y G",
	"field-fri-relative+-1": "ວັນສຸກແລ້ວ",
	"field-wed-relative+-1": "ວັນພຸດແລ້ວ",
	"months-format-wide": [
		"ມັງກອນ",
		"ກຸມພາ",
		"ມີນາ",
		"ເມສາ",
		"ພຶດສະພາ",
		"ມິຖຸນາ",
		"ກໍລະກົດ",
		"ສິງຫາ",
		"ກັນຍາ",
		"ຕຸລາ",
		"ພະຈິກ",
		"ທັນວາ"
	],
	"dateFormatItem-yyyyQQQ": "G QQQ y",
	"dateTimeFormat-medium": "{1}, {0}",
	"dayPeriods-format-wide-pm": "ຫຼັງທ່ຽງ",
	"dateFormat-full": "EEEEທີ d MMMM y G",
	"dateFormatItem-yyyyMEd": "E, G d/M/y",
	"field-thu-relative+-1": "ວັນພະຫັດແລ້ວ",
	"dateFormatItem-Md": "d/M",
	"field-era": "ສະໄໝ",
	"months-standAlone-wide": [
		"ມັງກອນ",
		"ກຸມພາ",
		"ມີນາ",
		"ເມສາ",
		"ພຶດສະພາ",
		"ມິຖຸນາ",
		"ກໍລະກົດ",
		"ສິງຫາ",
		"ກັນຍາ",
		"ຕຸລາ",
		"ພະຈິກ",
		"ທັນວາ"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"ໄຕຣມາດ 1",
		"ໄຕຣມາດ 2",
		"ໄຕຣມາດ 3",
		"ໄຕຣມາດ 4"
	],
	"timeFormat-long": "H ໂມງ m ນາທີ ss ວິນາທີ z",
	"field-year": "ປີ",
	"field-hour": "ຊົ່ວໂມງ",
	"months-format-abbr": [
		"ມ.ກ.",
		"ກ.ພ.",
		"ມ.ນ.",
		"ມ.ສ.",
		"ພ.ພ.",
		"ມິ.ຖ.",
		"ກ.ລ.",
		"ສ.ຫ.",
		"ກ.ຍ.",
		"ຕ.ລ.",
		"ພ.ຈ.",
		"ທ.ວ."
	],
	"field-sat-relative+0": "ວັນເສົານີ້",
	"field-sat-relative+1": "ວັນເສົາໜ້າ",
	"timeFormat-full": "H ໂມງ m ນາທີ ss ວິນາທີ zzzz",
	"field-day-relative+0": "ມື້ນີ້",
	"field-thu-relative+0": "ວັນພະຫັດນີ້",
	"field-day-relative+1": "ມື້ອື່ນ",
	"field-thu-relative+1": "ວັນພະຫັດໜ້າ",
	"dateFormatItem-GyMMMd": "G d MMM y",
	"field-day-relative+2": "ມື້ຮື",
	"months-standAlone-abbr": [
		"ມ.ກ.",
		"ກ.ພ.",
		"ມ.ນ.",
		"ມ.ສ.",
		"ພ.ພ.",
		"ມິ.ຖ.",
		"ກ.ລ.",
		"ສ.ຫ.",
		"ກ.ຍ.",
		"ຕ.ລ.",
		"ພ.ຈ.",
		"ທ.ວ."
	],
	"quarters-format-abbr": [
		"ຕມ1",
		"ຕມ2",
		"ຕມ3",
		"ຕມ4"
	],
	"quarters-standAlone-wide": [
		"ໄຕຣມາດ 1",
		"ໄຕຣມາດ 2",
		"ໄຕຣມາດ 3",
		"ໄຕຣມາດ 4"
	],
	"dateFormatItem-yyyyMMMEd": "E, G d MMM y",
	"days-standAlone-wide": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"dateFormatItem-yyyyMMM": "G MMM y",
	"dateFormatItem-yyyyMMMd": "G d MMM y",
	"timeFormat-medium": "H:mm:ss",
	"field-sun-relative+0": "ວັນເສົານີ້",
	"field-sun-relative+1": "ວັນເສົາໜ້າ",
	"quarters-standAlone-abbr": [
		"ຕ1",
		"ຕ2",
		"ຕ3",
		"ຕ4"
	],
	"field-minute": "ນາທີ",
	"field-dayperiod": "ກ່ອນທ່ຽງ/ຫຼັງທ່ຽງ",
	"days-standAlone-abbr": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"field-day-relative+-1": "ມື້ວານ",
	"dateFormatItem-h": "h ໂມງa",
	"dateTimeFormat-long": "{1}, {0}",
	"field-day-relative+-2": "ມື້ກ່ອນ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d/M",
	"dateTimeFormat-full": "{1}, {0}",
	"field-fri-relative+0": "ວັນສຸກນີ້",
	"field-fri-relative+1": "ວັນສຸກໜ້າ",
	"field-day": "ມື້",
	"days-format-wide": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"field-zone": "ເຂດເວລາ",
	"field-year-relative+-1": "ປີກາຍ",
	"field-month-relative+-1": "ເດືອນແລ້ວ",
	"days-format-abbr": [
		"ວັນອາທິດ",
		"ວັນຈັນ",
		"ວັນອັງຄານ",
		"ວັນພຸດ",
		"ວັນພະຫັດ",
		"ວັນສຸກ",
		"ວັນເສົາ"
	],
	"days-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"dateFormatItem-yyyyMd": "G d/M/y",
	"field-month": "ເດືອນ",
	"days-standAlone-narrow": [
		"ທ",
		"ຈ",
		"ຄ",
		"ພຸ",
		"ພ",
		"ສຸ",
		"ສ"
	],
	"field-tue-relative+0": "ວັນອັງຄານນີ້",
	"field-tue-relative+1": "ວັນອັງຄານໜ້າ",
	"dayPeriods-format-wide-am": "ກ່ອນທ່ຽງ",
	"field-mon-relative+0": "ວັນຈັນນີ້",
	"field-mon-relative+1": "ວັນຈັນໜ້າ",
	"dateFormat-short": "d/M/y GGGGG",
	"field-second": "ວິນາທີ",
	"field-sat-relative+-1": "ວັນເສົາແລ້ວ",
	"field-sun-relative+-1": "ວັນເສົາແລ້ວ",
	"field-month-relative+0": "ເດືອນນີ້",
	"field-month-relative+1": "ເດືອນໜ້າ",
	"dateFormatItem-Ed": "E d",
	"field-week": "ອາທິດ",
	"dateFormat-medium": "d MMM y G",
	"field-year-relative+0": "ປີນີ້",
	"field-week-relative+-1": "ອາທິດແລ້ວ",
	"dateFormatItem-yyyyM": "G M/y",
	"field-year-relative+1": "ປີໜ້າ",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-GyMMM": "G MMM y",
	"field-mon-relative+-1": "ວັນຈັນແລ້ວ",
	"field-week-relative+0": "ອາທິດນີ້",
	"field-week-relative+1": "ອາທິດໜ້າ"
}
//end v1.x content
);