define(
//begin v1.x content
{
	"field-sat-relative+0": "ວັນເສົານີ້",
	"field-sat-relative+1": "ວັນເສົາໜ້າ",
	"field-dayperiod": "ກ່ອນທ່ຽງ/ຫຼັງທ່ຽງ",
	"field-sun-relative+-1": "ວັນເສົາແລ້ວ",
	"field-mon-relative+-1": "ວັນຈັນແລ້ວ",
	"field-minute": "ນາທີ",
	"field-day-relative+-1": "ມື້ວານ",
	"field-weekday": "ມື້ຂອງອາທິດ",
	"field-day-relative+-2": "ມື້ກ່ອນ",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"field-era": "ສະໄໝ",
	"field-hour": "ຊົ່ວໂມງ",
	"field-sun-relative+0": "ວັນເສົານີ້",
	"field-sun-relative+1": "ວັນເສົາໜ້າ",
	"months-standAlone-abbr": [
		"ແມສເຄີແຣມ",
		"ເຕເກມ",
		"ເຮດາ",
		"ທາຊັສ",
		"ເທີ",
		"ເຍຄາທິດ",
		"ເມກາບິດ",
		"ເມຍເຊຍ",
		"ເຈນບອດ",
		"ເຊເນ",
		"ຮຳເລ",
		"ເນແຮສ໌",
		"ພາກູເມນ"
	],
	"field-wed-relative+-1": "ວັນພຸດແລ້ວ",
	"field-day-relative+0": "ມື້ນີ້",
	"field-day-relative+1": "ມື້ອື່ນ",
	"field-day-relative+2": "ມື້ຮື",
	"field-tue-relative+0": "ວັນອັງຄານນີ້",
	"field-zone": "ເຂດເວລາ",
	"field-tue-relative+1": "ວັນອັງຄານໜ້າ",
	"field-week-relative+-1": "ອາທິດແລ້ວ",
	"field-year-relative+0": "ປີນີ້",
	"field-year-relative+1": "ປີໜ້າ",
	"field-sat-relative+-1": "ວັນເສົາແລ້ວ",
	"field-year-relative+-1": "ປີກາຍ",
	"field-year": "ປີ",
	"field-fri-relative+0": "ວັນສຸກນີ້",
	"field-fri-relative+1": "ວັນສຸກໜ້າ",
	"months-standAlone-wide": [
		"ແມສເຄີແຣມ",
		"ເຕເກມ",
		"ເຮດາ",
		"ທາຊັສ",
		"ເທີ",
		"ເຍຄາທິດ",
		"ເມກາບິດ",
		"ເມຍເຊຍ",
		"ເຈນບອດ",
		"ເຊເນ",
		"ຮຳເລ",
		"ເນແຮສ໌",
		"ພາກູເມນ"
	],
	"field-week": "ອາທິດ",
	"field-week-relative+0": "ອາທິດນີ້",
	"field-week-relative+1": "ອາທິດໜ້າ",
	"months-format-abbr": [
		"ແມສເຄີແຣມ",
		"ເຕເກມ",
		"ເຮດາ",
		"ທາຊັສ",
		"ເທີ",
		"ເຍຄາທິດ",
		"ເມກາບິດ",
		"ເມຍເຊຍ",
		"ເຈນບອດ",
		"ເຊເນ",
		"ຮຳເລ",
		"ເນແຮສ໌",
		"ພາກູເມນ"
	],
	"field-month-relative+0": "ເດືອນນີ້",
	"field-month": "ເດືອນ",
	"field-month-relative+1": "ເດືອນໜ້າ",
	"field-fri-relative+-1": "ວັນສຸກແລ້ວ",
	"field-second": "ວິນາທີ",
	"field-tue-relative+-1": "ວັນອັງຄານແລ້ວ",
	"field-day": "ມື້",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"field-mon-relative+0": "ວັນຈັນນີ້",
	"field-mon-relative+1": "ວັນຈັນໜ້າ",
	"field-thu-relative+0": "ວັນພະຫັດນີ້",
	"field-second-relative+0": "ຕອນນີ້",
	"field-thu-relative+1": "ວັນພະຫັດໜ້າ",
	"months-format-wide": [
		"ແມສເຄີແຣມ",
		"ເຕເກມ",
		"ເຮດາ",
		"ທາຊັສ",
		"ເທີ",
		"ເຍຄາທິດ",
		"ເມກາບິດ",
		"ເມຍເຊຍ",
		"ເຈນບອດ",
		"ເຊເນ",
		"ຮຳເລ",
		"ເນແຮສ໌",
		"ພາກູເມນ"
	],
	"field-wed-relative+0": "ວັນພຸດນີ້",
	"field-wed-relative+1": "ວັນພຸດໜ້າ",
	"field-month-relative+-1": "ເດືອນແລ້ວ",
	"field-thu-relative+-1": "ວັນພະຫັດແລ້ວ"
}
//end v1.x content
);