// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
        'months-format-abbr':["janv.","févr.","mars","avr.","mai","juin","juil.","août","sept.","oct.","nov.","déc."],
        'months-format-wide':["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"],
        'months-standAlone-narrow':["J","F","M","A","M","J","J","A","S","O","N","D"],
        'days-format-abbr':["dim.","lun.","mar.","mer.","jeu.","ven.","sam."],
        'days-format-wide':["dimanche","lundi","mardi","mercredi","jeudi","vendredi","samedi"],
        'days-standAlone-narrow':["D","L","M","M","J","V","S"],
        'quarters-format-abbreviated':["T1","T2","T3","T4"],
        'quarters-format-wide':["1er trimestre","2e trimestre","3e trimestre","4e trimestre"],
        'quarters-stand-alone-narrow':["1","2","3","4"],
        'am':"AM",
        'pm':"PM",
        'eraNames':["avant Jésus-Christ","après Jésus-Christ"],
        'eraAbbr':["av. J.-C.","ap. J.-C."],
        'dateFormat-full': "EEEE d MMMM yyyy",
        'dateFormat-long': "d MMMM yyyy",
        'dateFormat-medium': "d MMM yyyy",
        'dateFormat-short': "dd/MM/yy",
        'timeFormat-full': "HH:mm:ss v",
        'timeFormat-long': "HH:mm:ss z",
        'timeFormat-medium': "HH:mm:ss",
        'timeFormat-short': "HH:mm",
        'dateTimeFormat': "{1} {0}" ,
        'dateTimeAvailableFormats':["HH:mm","HH:mm:ss","E d MMM","d MMMM","dd/MM","d/M","mm:ss","MM/yy","MMM yy","Q yy","QQQQ yy","MMMM yyyy"],
        'field-era':"ère",
        'field-year':"année",
        'field-month':"mois",
        'field-week':"semaine",
        'field-day':"jour",
        'field-weekday':"jour de la semaine",
        'field-dayperiod':"cadran",
        'field-hour':"heure",
        'field-minute':"minute",
        'field-second':"seconde",
        'field-zone':"fuseau horaire"
})
                        