define(
//begin v1.x content
{
	"field-sat-relative+0": "Samschtig diese Wuche",
	"field-dayperiod": "Tageshälfti",
	"field-sat-relative+1": "Samschtig nächste Wuche",
	"field-sun-relative+-1": "Sunntig letzte Wuche",
	"dayPeriods-format-wide-pm": "nam.",
	"field-mon-relative+-1": "Määntig letzte Wuche",
	"field-minute": "Minuute",
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "geschter",
	"field-weekday": "Wuchetag",
	"field-day-relative+-2": "vorgeschter",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-era": "Epoche",
	"field-hour": "Schtund",
	"dayPeriods-format-wide-am": "vorm.",
	"dateFormatItem-y": "y",
	"field-sun-relative+0": "Sunntig diese Wuche",
	"field-sun-relative+1": "Sunntig nächste Wuche",
	"field-wed-relative+-1": "Mittwuch letzte Wuche",
	"dateFormatItem-Ed": "E d.",
	"field-day-relative+0": "hüt",
	"field-day-relative+1": "moorn",
	"days-standAlone-narrow": [
		"S",
		"M",
		"D",
		"M",
		"D",
		"F",
		"S"
	],
	"field-day-relative+2": "übermoorn",
	"dateFormat-long": "d. MMMM y G",
	"field-zone": "Zone",
	"field-tue-relative+0": "Ziischtig diese Wuche",
	"field-tue-relative+1": "Ziischtig nächste Wuche",
	"dateFormatItem-Hm": "H:mm",
	"field-week-relative+-1": "letzte Wuche",
	"dateFormat-medium": "d. MMM y G",
	"field-year-relative+0": "diese Jaar",
	"field-year-relative+1": "nächste Jaar",
	"field-sat-relative+-1": "Samschtig letzte Wuche",
	"field-year-relative+-1": "letzte Jaar",
	"field-year": "Jaar",
	"field-fri-relative+0": "Friitig diese Wuche",
	"field-fri-relative+1": "Friitig nächste Wuche",
	"field-week": "Wuche",
	"field-week-relative+0": "diese Wuche",
	"dateFormatItem-MMMd": "d. MMM",
	"field-week-relative+1": "nächste Wuche",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mär",
		"Apr",
		"Mai",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Okt",
		"Nov",
		"Dez"
	],
	"field-month-relative+0": "diese Monet",
	"field-month": "Monet",
	"field-month-relative+1": "nächste Monet",
	"field-fri-relative+-1": "Friitig letzte Wuche",
	"dateFormatItem-H": "H",
	"days-format-abbr": [
		"Su.",
		"Mä.",
		"Zi.",
		"Mi.",
		"Du.",
		"Fr.",
		"Sa."
	],
	"field-second": "Sekunde",
	"field-tue-relative+-1": "Ziischtig letzte Wuche",
	"field-day": "Tag",
	"dateFormatItem-MEd": "E, d.M.",
	"field-mon-relative+0": "Määntig diese Wuche",
	"field-mon-relative+1": "Määntig nächste Wuche",
	"field-thu-relative+0": "Dunschtig diese Wuche",
	"dateFormat-short": "d.M.y",
	"field-thu-relative+1": "Dunschtig nächste Wuche",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"field-wed-relative+0": "Mittwuch diese Wuche",
	"months-format-wide": [
		"Januar",
		"Februar",
		"März",
		"April",
		"Mai",
		"Juni",
		"Juli",
		"Auguscht",
		"Septämber",
		"Oktoober",
		"Novämber",
		"Dezämber"
	],
	"field-wed-relative+1": "Mittwuch nächste Wuche",
	"field-month-relative+-1": "letzte Monet",
	"quarters-format-wide": [
		"1. Quartal",
		"2. Quartal",
		"3. Quartal",
		"4. Quartal"
	],
	"days-format-wide": [
		"Sunntig",
		"Määntig",
		"Ziischtig",
		"Mittwuch",
		"Dunschtig",
		"Friitig",
		"Samschtig"
	],
	"field-thu-relative+-1": "Dunschtig letzte Wuche"
}
//end v1.x content
);