define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.y G",
	"dateFormatItem-yyMMdd": "dd.MM.y G",
	"dateFormatItem-yQ": "Q y G",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-MMdd": "dd.MM.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d.MM.",
	"dateFormatItem-yyMM": "MM.y G",
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM y G",
	"dateFormatItem-yyQQQQ": "QQQQ y G",
	"dateFormatItem-yMd": "d.M.y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyQ": "Q y G",
	"dateFormatItem-H": "HH 'Uhr'",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d. MMM y G",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormat-short": "d.M.yyyy",
	"dateFormatItem-yMMMEd": "E, d. MMM y G",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "E, d.M.y G",
	"dateFormatItem-d": "d"
}
//end v1.x content
);