// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"Andorranische Pesete",
	AED_displayName:"UAE Dirham",
	AFA_displayName:"Afghani (1927-2002)",
	AFN_displayName:"Afghani",
	AFN_symbol:"Af",
	ALL_displayName:"Lek",
	AMD_displayName:"Dram",
	ANG_displayName:"Niederl. Antillen Gulden",
	AOA_displayName:"Kwanza",
	AOK_displayName:"Angolanischer Kwanza (1977-1990)",
	AON_displayName:"Neuer Kwanza",
	AOR_displayName:"Kwanza Reajustado",
	ARA_displayName:"Argentinischer Austral",
	ARP_displayName:"Argentinischer Peso (1983-1985)",
	ARS_displayName:"Argentinischer Peso",
	ARS_symbol:"Arg$",
	ATS_displayName:"Österreichischer Schilling",
	ATS_symbol:"öS",
	AUD_displayName:"Australischer Dollar",
	AUD_symbol:"$A",
	AWG_displayName:"Aruba Florin",
	AZM_displayName:"Aserbeidschan Manat",
	AZN_displayName:"Aserbaidschan-Manat",
	BAD_displayName:"Bosnien und Herzegowina Dinar",
	BAM_displayName:"Konvertierbare Mark",
	BAM_symbol:"KM",
	BBD_displayName:"Barbados-Dollar",
	BBD_symbol:"BDS$",
	BDT_displayName:"Taka",
	BDT_symbol:"Tk",
	BEC_displayName:"Belgischer Franc (konvertibel)",
	BEF_displayName:"Belgischer Franc",
	BEF_symbol:"BF",
	BEL_displayName:"Belgischer Finanz-Franc",
	BGL_displayName:"Lew (1962-1999)",
	BGL_symbol:"lev",
	BGN_displayName:"Lew",
	BHD_displayName:"Bahrain-Dinar",
	BHD_symbol:"BD",
	BIF_displayName:"Burundi-Franc",
	BIF_symbol:"Fbu",
	BMD_displayName:"Bermuda-Dollar",
	BMD_symbol:"Ber$",
	BND_displayName:"Brunei-Dollar",
	BOB_displayName:"Boliviano",
	BOB_symbol:"Bs",
	BOP_displayName:"Bolivianischer Peso",
	BOV_displayName:"Mvdol",
	BRB_displayName:"Brasilianischer Cruzeiro Novo (1967-1986)",
	BRC_displayName:"Brasilianischer Cruzado",
	BRE_displayName:"Brasilianischer Cruzeiro (1990-1993)",
	BRL_displayName:"Real",
	BRN_displayName:"Brasilianischer Cruzado Novo",
	BRR_displayName:"Brasilianischer Cruzeiro",
	BSD_displayName:"Bahama-Dollar",
	BTN_displayName:"Ngultrum",
	BTN_symbol:"Nu",
	BUK_displayName:"Birmanischer Kyat",
	BWP_displayName:"Pula",
	BYB_displayName:"Belarus Rubel (alt)",
	BYR_displayName:"Belarus Rubel (neu)",
	BYR_symbol:"Rbl",
	BZD_displayName:"Belize-Dollar",
	BZD_symbol:"BZ$",
	CAD_displayName:"Kanadischer Dollar",
	CAD_symbol:"Can$",
	CDF_displayName:"Franc congolais",
	CHE_displayName:"WIR-Euro",
	CHF_displayName:"Schweizer Franken",
	CHF_symbol:"SFr.",
	CHW_displayName:"WIR Franken",
	CLF_displayName:"Unidades de Fomento",
	CLP_displayName:"Chilenischer Peso",
	CLP_symbol:"Ch$",
	CNY_displayName:"Renminbi Yuan",
	CNY_symbol:"Y",
	COP_displayName:"Kolumbianischer Peso",
	COP_symbol:"Col$",
	COU_displayName:"Unidad de Valor Real",
	CRC_displayName:"Costa Rica Colon",
	CRC_symbol:"C",
	CSD_displayName:"Alter Serbischer Dinar",
	CSK_displayName:"Tschechoslowakische Krone",
	CUP_displayName:"Kubanischer Peso",
	CVE_displayName:"Kap Verde Escudo",
	CVE_symbol:"CVEsc",
	CYP_displayName:"Zypern Pfund",
	CYP_symbol:"£C",
	CZK_displayName:"Tschechische Krone",
	DDM_displayName:"Mark der DDR",
	DEM_displayName:"Deutsche Mark",
	DEM_symbol:"DM",
	DJF_displayName:"Dschibuti-Franc",
	DJF_symbol:"DF",
	DKK_displayName:"Dänische Krone",
	DOP_displayName:"Dominikanischer Peso",
	DZD_displayName:"Algerischer Dinar",
	DZD_symbol:"DA",
	ECS_displayName:"Ecuadorianischer Sucre",
	ECV_displayName:"Verrechnungseinheit für EC",
	EEK_displayName:"Estnische Krone",
	EGP_displayName:"Ägyptisches Pfund",
	EQE_displayName:"Ekwele",
	ERN_displayName:"Nakfa",
	ESA_displayName:"Spanische Peseta (A-Konten)",
	ESB_displayName:"Spanische Peseta (konvertibel)",
	ESP_displayName:"Spanische Pesete",
	ESP_symbol:"₧",
	ETB_displayName:"Birr",
	ETB_symbol:"Br",
	EUR_displayName:"Euro",
	FIM_displayName:"Finnische Mark",
	FJD_displayName:"Fidschi Dollar",
	FJD_symbol:"F$",
	FKP_displayName:"Falkland Pfund",
	FRF_displayName:"Französischer Franc",
	FRF_symbol:"FF",
	GBP_displayName:"Pfund Sterling",
	GBP_symbol:"£",
	GEK_displayName:"Georgischer Kupon Larit",
	GEL_displayName:"Georgischer Lari",
	GEL_symbol:"lari",
	GHC_displayName:"Cedi",
	GHS_displayName:"Ghanaische Cedi",
	GIP_displayName:"Gibraltar Pfund",
	GMD_displayName:"Dalasi",
	GNF_displayName:"Guinea Franc",
	GNF_symbol:"GF",
	GNS_displayName:"Guineischer Syli",
	GQE_displayName:"Äquatorialguinea Ekwele Guineana",
	GRD_displayName:"Griechische Drachme",
	GTQ_displayName:"Quetzal",
	GWE_displayName:"Portugiesisch Guinea Escudo",
	GWP_displayName:"Guinea Bissau Peso",
	GYD_displayName:"Guyana Dollar",
	GYD_symbol:"G$",
	HKD_displayName:"Hongkong-Dollar",
	HNL_displayName:"Lempira",
	HNL_symbol:"L",
	HRD_displayName:"Kroatischer Dinar",
	HRK_displayName:"Kuna",
	HTG_displayName:"Gourde",
	HUF_displayName:"Forint",
	HUF_symbol:"Ft",
	IDR_displayName:"Rupiah",
	IDR_symbol:"Rp",
	IEP_displayName:"Irisches Pfund",
	IEP_symbol:"IR£",
	ILP_displayName:"Israelisches Pfund",
	ILS_displayName:"Schekel",
	INR_displayName:"Indische Rupie",
	INR_symbol:"0≤Rs.|1≤Re.|1<Rs.",
	IQD_displayName:"Irak Dinar",
	IQD_symbol:"ID",
	IRR_displayName:"Rial",
	IRR_symbol:"RI",
	ISK_displayName:"Isländische Krone",
	ITL_displayName:"Italienische Lire",
	ITL_symbol:"₤",
	JMD_displayName:"Jamaika Dollar",
	JMD_symbol:"J$",
	JOD_displayName:"Jordanischer Dinar",
	JOD_symbol:"JD",
	JPY_displayName:"Yen",
	JPY_symbol:"¥",
	KES_displayName:"Kenia Schilling",
	KES_symbol:"K Sh",
	KGS_displayName:"Som",
	KGS_symbol:"som",
	KHR_displayName:"Riel",
	KHR_symbol:"CR",
	KMF_displayName:"Komoren Franc",
	KMF_symbol:"CF",
	KPW_displayName:"Nordkoreanischer Won",
	KRW_displayName:"Südkoreanischer Won",
	KWD_displayName:"Kuwait Dinar",
	KWD_symbol:"KD",
	KYD_displayName:"Kaiman-Dollar",
	KZT_displayName:"Tenge",
	KZT_symbol:"T",
	LAK_displayName:"Kip",
	LBP_displayName:"Libanesisches Pfund",
	LBP_symbol:"LL",
	LKR_displayName:"Sri Lanka Rupie",
	LKR_symbol:"SL Re",
	LRD_displayName:"Liberianischer Dollar",
	LSL_displayName:"Loti",
	LSL_symbol:"M",
	LSM_displayName:"Maloti",
	LTL_displayName:"Litauischer Litas",
	LTT_displayName:"Litauischer Talonas",
	LUC_displayName:"Luxemburgischer Franc (konvertibel)",
	LUF_displayName:"Luxemburgischer Franc",
	LUL_displayName:"Luxemburgischer Finanz-Franc",
	LVL_displayName:"Lettischer Lats",
	LVR_displayName:"Lettischer Rubel",
	LYD_displayName:"Libyscher Dinar",
	LYD_symbol:"LD",
	MAD_displayName:"Marokkanischer Dirham",
	MAF_displayName:"Marokkanischer Franc",
	MDL_displayName:"Moldau Leu",
	MGA_displayName:"Madagaskar Ariary",
	MGF_displayName:"Madagaskar Franc",
	MKD_displayName:"Denar",
	MKD_symbol:"MDen",
	MLF_displayName:"Malischer Franc",
	MMK_displayName:"Kyat",
	MNT_displayName:"Tugrik",
	MNT_symbol:"Tug",
	MOP_displayName:"Pataca",
	MRO_displayName:"Ouguiya",
	MRO_symbol:"UM",
	MTL_displayName:"Maltesische Lira",
	MTL_symbol:"Lm",
	MTP_displayName:"Maltesisches Pfund",
	MUR_displayName:"Mauritius Rupie",
	MVR_displayName:"Rufiyaa",
	MWK_displayName:"Malawi Kwacha",
	MWK_symbol:"MK",
	MXN_displayName:"Mexikanischer Peso",
	MXN_symbol:"MEX$",
	MXP_displayName:"Mexikanischer Silber-Peso (1861-1992)",
	MXV_displayName:"Mexican Unidad de Inversion (UDI)",
	MYR_displayName:"Malaysischer Ringgit",
	MYR_symbol:"RM",
	MZE_displayName:"Mosambikanischer Escudo",
	MZM_displayName:"Alter Metical",
	MZM_symbol:"Mt",
	MZN_displayName:"Metical",
	MZN_symbol:"MTn",
	NAD_displayName:"Namibia Dollar",
	NAD_symbol:"N$",
	NGN_displayName:"Naira",
	NIC_displayName:"Cordoba",
	NIO_displayName:"Gold-Cordoba",
	NLG_displayName:"Holländischer Gulden",
	NOK_displayName:"Norwegische Krone",
	NOK_symbol:"NKr",
	NPR_displayName:"Nepalesische Rupie",
	NPR_symbol:"Nrs",
	NZD_displayName:"Neuseeland-Dollar",
	NZD_symbol:"$NZ",
	OMR_displayName:"Rial Omani",
	OMR_symbol:"RO",
	PAB_displayName:"Balboa",
	PEI_displayName:"Peruanischer Inti",
	PEN_displayName:"Neuer Sol",
	PES_displayName:"Sol",
	PGK_displayName:"Kina",
	PHP_displayName:"Philippinischer Peso",
	PHP_symbol:"Php",
	PKR_displayName:"Pakistanische Rupie",
	PKR_symbol:"Pra",
	PLN_displayName:"Zloty",
	PLN_symbol:"Zl",
	PLZ_displayName:"Zloty (1950-1995)",
	PTE_displayName:"Portugiesischer Escudo",
	PYG_displayName:"Guarani",
	QAR_displayName:"Katar Riyal",
	QAR_symbol:"QR",
	RHD_displayName:"Rhodesischer Dollar",
	ROL_displayName:"Leu",
	RON_displayName:"Rumänischer Leu",
	RSD_displayName:"Serbischer Dinar",
	RUB_displayName:"Russischer Rubel (neu)",
	RUR_displayName:"Russischer Rubel (alt)",
	RWF_displayName:"Ruanda Franc",
	SAR_displayName:"Saudi Riyal",
	SAR_symbol:"SRl",
	SBD_displayName:"Salomonen Dollar",
	SBD_symbol:"SI$",
	SCR_displayName:"Seychellen Rupie",
	SCR_symbol:"SR",
	SDD_displayName:"Sudanesischer Dinar",
	SDG_displayName:"Sudanesisches Pfund",
	SDP_displayName:"Sudanesisches Pfund (alt)",
	SEK_displayName:"Schwedische Krone",
	SGD_displayName:"Singapur-Dollar",
	SGD_symbol:"S$",
	SHP_displayName:"St. Helena Pfund",
	SIT_displayName:"Tolar",
	SKK_displayName:"Slowakische Krone",
	SKK_symbol:"Sk",
	SLL_displayName:"Leone",
	SOS_displayName:"Somalia Schilling",
	SRD_displayName:"Surinamischer Dollar",
	SRG_displayName:"Suriname Gulden",
	SRG_symbol:"Sf",
	STD_displayName:"Dobra",
	STD_symbol:"Db",
	SUR_displayName:"Sowjetischer Rubel",
	SVC_displayName:"El Salvador Colon",
	SYP_displayName:"Syrisches Pfund",
	SYP_symbol:"LS",
	SZL_displayName:"Lilangeni",
	SZL_symbol:"E",
	THB_displayName:"Baht",
	TJR_displayName:"Tadschikistan Rubel",
	TJS_displayName:"Tadschikistan Somoni",
	TMM_displayName:"Turkmenistan-Manat",
	TND_displayName:"Tunesischer Dinar",
	TOP_displayName:"Paʻanga",
	TOP_symbol:"T$",
	TPE_displayName:"Timor Escudo",
	TRL_displayName:"Türkische Lira",
	TRL_symbol:"TL",
	TRY_displayName:"Neue Türkische Lira",
	TTD_displayName:"Trinidad und Tobago Dollar",
	TTD_symbol:"TT$",
	TWD_displayName:"Neuer Taiwan Dollar",
	TWD_symbol:"NT$",
	TZS_displayName:"Tansania Schilling",
	TZS_symbol:"T Sh",
	UAH_displayName:"Hryvnia",
	UAK_displayName:"Ukrainischer Karbovanetz",
	UGS_displayName:"Uganda Schilling (1966-1987)",
	UGX_displayName:"Uganda Schilling",
	UGX_symbol:"U Sh",
	USD_displayName:"US-Dollar",
	USD_symbol:"$",
	USN_displayName:"US Dollar (Nächster Tag)",
	USS_displayName:"US Dollar (Gleicher Tag)",
	UYP_displayName:"Uruguayischer Neuer Peso (1975-1993)",
	UYU_displayName:"Uruguayischer Peso",
	UYU_symbol:"Ur$",
	UZS_displayName:"Usbekistan Sum",
	VEB_displayName:"Bolivar",
	VEB_symbol:"Be",
	VEF_displayName:"Bolívar Fuerte",
	VND_displayName:"Dong",
	VUV_displayName:"Vatu",
	WST_displayName:"Tala",
	XAF_displayName:"CFA Franc (Äquatorial)",
	XAG_displayName:"Silber",
	XAU_displayName:"Gold",
	XBA_displayName:"Europäische Rechnungseinheit",
	XBB_displayName:"Europäische Währungseinheit (XBB)",
	XBC_displayName:"Europäische Rechnungseinheit (XBC)",
	XBD_displayName:"Europäische Rechnungseinheit (XBD)",
	XCD_displayName:"Ostkaribischer Dollar",
	XCD_symbol:"EC$",
	XDR_displayName:"Sonderziehungsrechte",
	XEU_displayName:"Europäische Währungseinheit (XEU)",
	XFO_displayName:"Französischer Gold-Franc",
	XFU_displayName:"Französischer UIC-Franc",
	XOF_displayName:"CFA Franc (West)",
	XPD_displayName:"Palladium",
	XPF_displayName:"CFP Franc",
	XPT_displayName:"Platin",
	XRE_displayName:"RINET Funds",
	XTS_displayName:"Testwährung",
	XXX_displayName:"Unbekannte Währung",
	YDD_displayName:"Jemen Dinar",
	YER_displayName:"Jemen Rial",
	YER_symbol:"YRl",
	YUD_displayName:"Jugoslawischer Dinar (1966-1990)",
	YUM_displayName:"Neuer Dinar",
	YUN_displayName:"Jugoslawischer Dinar (konvertibel)",
	ZAR_displayName:"Rand",
	ZAR_symbol:"R",
	ZMK_displayName:"Kwacha",
	ZRN_displayName:"Neuer Zaire",
	ZRZ_displayName:"Zaire",
	ZWD_displayName:"Simbabwe Dollar",
	ZWD_symbol:"Z$"
})
                 