({
	"field-zone": "Zone", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"dateFormat-medium": "dd.MM.yyyy", 
	"field-second": "Sekunde", 
	"field-week": "Woche", 
	"pm": "nachm.", 
	"timeFormat-full": "HH:mm:ss v", 
	"dateTimeFormat": "{1} {0}", 
	"dateTimeAvailableFormats": [
		"E d.", 
		"H", 
		"HH:mm", 
		"HH:mm:ss", 
		"H:mm", 
		"L", 
		"E, d.M.", 
		"LLL", 
		"E d. MMM", 
		"E d. MMMM", 
		"d. MMMM", 
		"dd. MMMM", 
		"d. MMM", 
		"d.MM.", 
		"dd.MM.", 
		"d.M.", 
		"d", 
		"HH:mm", 
		"HH:mm:ss", 
		"mm:ss", 
		"mm:ss", 
		"yyyy", 
		"yyyy-M", 
		"EEE, yyyy-M-d", 
		"MMM yyyy", 
		"EEE, d. MMM yyyy", 
		"MMMM yyyy", 
		"Q yyyy", 
		"QQQ yyyy", 
		"MM.yy", 
		"MMM yy", 
		"dd.MM.yy", 
		"Q yy", 
		"QQQQ yy", 
		"yyyy", 
		"MMMM yyyy"
	], 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"am": "vorm.", 
	"days-standAlone-narrow": [
		"S", 
		"M", 
		"D", 
		"M", 
		"D", 
		"F", 
		"S"
	], 
	"eraNames": [
		"v. Chr.", 
		"n. Chr."
	], 
	"field-year": "Jahr", 
	"months-standAlone-abbr": [
		"1", 
		"2", 
		"Mär", 
		"4", 
		"5", 
		"6", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Dez"
	], 
	"field-minute": "Minute", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"timeFormat-medium": "HH:mm:ss", 
	"field-hour": "Stunde", 
	"dateFormat-long": "d. MMMM yyyy", 
	"field-day": "Tag", 
	"field-dayperiod": "Tageshälfte", 
	"field-month": "Monat", 
	"dateFormat-short": "dd.MM.yy", 
	"months-format-wide": [
		"Januar", 
		"Februar", 
		"März", 
		"April", 
		"Mai", 
		"Juni", 
		"Juli", 
		"August", 
		"September", 
		"Oktober", 
		"November", 
		"Dezember"
	], 
	"field-era": "Epoche", 
	"timeFormat-short": "HH:mm", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mrz", 
		"Apr", 
		"Mai", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Dez"
	], 
	"eraAbbr": [
		"v. Chr.", 
		"n. Chr."
	], 
	"days-format-wide": [
		"Sonntag", 
		"Montag", 
		"Dienstag", 
		"Mittwoch", 
		"Donnerstag", 
		"Freitag", 
		"Samstag"
	], 
	"timeFormat-long": "HH:mm:ss z", 
	"quarters-format-wide": [
		"1. Quartal", 
		"2. Quartal", 
		"3. Quartal", 
		"4. Quartal"
	], 
	"dateFormat-full": "EEEE, d. MMMM yyyy", 
	"days-format-abbr": [
		"So.", 
		"Mo.", 
		"Di.", 
		"Mi.", 
		"Do.", 
		"Fr.", 
		"Sa."
	], 
	"field-weekday": "Wochentag"
})