define(
//begin v1.x content
{
	"dateFormatItem-yyMMdd": "dd.MM.y GGGGG",
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMdd": "dd.MM.",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-H": "HH 'Uhr'",
	"dateFormatItem-yyMMM": "MMM y G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yyQQQQ": "QQQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "E, d. MMM y G",
	"dateFormatItem-yyyyMEd": "E, d.M.y GGGGG",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-MMd": "d.MM.",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyMM": "MM.y GGGGG",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyQQQ": "QQQ y G",
	"dateFormat-short": "d.M.y GGGGG",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyM": "M.y GGGGG",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-Ed": "E d."
}
//end v1.x content
);