define(
//begin v1.x content
{
	"field-second-relative+0": "bây giờ",
	"field-weekday": "Ngày trong tuần",
	"field-wed-relative+0": "Thứ Tư tuần này",
	"dateFormatItem-GyMMMEd": "E, dd MMM y G",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"field-wed-relative+1": "Thứ Tư tuần sau",
	"field-tue-relative+-1": "Thứ Ba tuần trước",
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"field-fri-relative+-1": "Thứ Sáu tuần trước",
	"field-wed-relative+-1": "Thứ Tư tuần trước",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{0} {1}",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y G",
	"dateFormatItem-yyyyMEd": "E, dd-M-y G",
	"field-thu-relative+-1": "Thứ Năm tuần trước",
	"dateFormatItem-Md": "dd-M",
	"field-era": "Thời đại",
	"field-year": "Năm",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-MMdd": "dd-MM",
	"field-hour": "Giờ",
	"field-sat-relative+0": "Thứ Bảy tuần này",
	"field-sat-relative+1": "Thứ Bảy tuần sau",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-thu-relative+0": "Thứ Năm tuần này",
	"dateFormatItem-GyMMMd": "dd MMM, y G",
	"field-day-relative+2": "Ngày kia",
	"field-thu-relative+1": "Thứ Năm tuần sau",
	"dateFormatItem-H": "HH'h'",
	"dateFormatItem-Gy": "'Năm' y G",
	"dateFormatItem-yyyyMMMEd": "E, dd MMM y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "dd MMM, y G",
	"dateFormatItem-MMMMd": "dd MMMM",
	"field-sun-relative+0": "Chủ Nhật tuần này",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "Chủ Nhật tuần sau",
	"field-minute": "Phút",
	"field-dayperiod": "SA/CH",
	"dateFormatItem-d": "'Ngày' dd",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "Hôm qua",
	"dateFormatItem-h": "h'h' a",
	"dateTimeFormat-long": "{0} {1}",
	"field-day-relative+-2": "Hôm kia",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-MEd": "E, dd-M",
	"dateTimeFormat-full": "{0} {1}",
	"field-fri-relative+0": "Thứ Sáu tuần này",
	"field-fri-relative+1": "Thứ Sáu tuần sau",
	"field-day": "Ngày",
	"field-zone": "Múi giờ",
	"dateFormatItem-yyyyMM": "MM-y G",
	"dateFormatItem-y": "'Năm' y G",
	"field-year-relative+-1": "năm ngoái",
	"field-month-relative+-1": "tháng trước",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"field-month": "Tháng",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "Thứ Ba tuần này",
	"field-tue-relative+1": "Thứ Ba tuần sau",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"field-mon-relative+0": "Thứ Hai tuần này",
	"field-mon-relative+1": "Thứ Hai tuần sau",
	"dateFormat-short": "dd/MM/y GGGGG",
	"field-second": "Giây",
	"field-sat-relative+-1": "Thứ Bảy tuần trước",
	"field-sun-relative+-1": "Chủ Nhật tuần trước",
	"field-month-relative+0": "tháng này",
	"field-month-relative+1": "tháng sau",
	"dateFormatItem-Ed": "E, dd",
	"field-week": "Tuần",
	"dateFormat-medium": "dd-MM-y G",
	"field-year-relative+0": "năm nay",
	"field-week-relative+-1": "tuần trước",
	"dateFormatItem-yyyyM": "M/y G",
	"field-year-relative+1": "năm sau",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "Thứ Hai tuần trước",
	"dateFormatItem-yyyy": "'Năm' y G",
	"field-week-relative+0": "tuần này",
	"field-week-relative+1": "tuần sau"
}
//end v1.x content
);