define(
//begin v1.x content
{
	"field-sat-relative+0": "Thứ Bảy tuần này",
	"field-sat-relative+1": "Thứ Bảy tuần sau",
	"field-dayperiod": "SA/CH",
	"field-sun-relative+-1": "Chủ Nhật tuần trước",
	"field-mon-relative+-1": "Thứ Hai tuần trước",
	"field-minute": "Phút",
	"field-day-relative+-1": "Hôm qua",
	"field-weekday": "Ngày trong tuần",
	"field-day-relative+-2": "Hôm kia",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Thời đại",
	"field-hour": "Giờ",
	"field-sun-relative+0": "Chủ Nhật tuần này",
	"field-sun-relative+1": "Chủ Nhật tuần sau",
	"field-wed-relative+-1": "Thứ Tư tuần trước",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"eraAbbr": [
		"Trước R.O.C",
		"R.O.C."
	],
	"field-day-relative+2": "Ngày kia",
	"field-tue-relative+0": "Thứ Ba tuần này",
	"field-zone": "Múi giờ",
	"field-tue-relative+1": "Thứ Ba tuần sau",
	"field-week-relative+-1": "tuần trước",
	"field-year-relative+0": "năm nay",
	"field-year-relative+1": "năm sau",
	"field-sat-relative+-1": "Thứ Bảy tuần trước",
	"field-year-relative+-1": "năm ngoái",
	"field-year": "Năm",
	"field-fri-relative+0": "Thứ Sáu tuần này",
	"field-fri-relative+1": "Thứ Sáu tuần sau",
	"field-week": "Tuần",
	"field-week-relative+0": "tuần này",
	"field-week-relative+1": "tuần sau",
	"field-month-relative+0": "tháng này",
	"field-month": "Tháng",
	"field-month-relative+1": "tháng sau",
	"field-fri-relative+-1": "Thứ Sáu tuần trước",
	"dateFormatItem-M": "'tháng' L",
	"field-second": "Giây",
	"field-tue-relative+-1": "Thứ Ba tuần trước",
	"field-day": "Ngày",
	"field-mon-relative+0": "Thứ Hai tuần này",
	"field-mon-relative+1": "Thứ Hai tuần sau",
	"field-thu-relative+0": "Thứ Năm tuần này",
	"field-second-relative+0": "bây giờ",
	"field-thu-relative+1": "Thứ Năm tuần sau",
	"field-wed-relative+0": "Thứ Tư tuần này",
	"field-wed-relative+1": "Thứ Tư tuần sau",
	"field-month-relative+-1": "tháng trước",
	"field-thu-relative+-1": "Thứ Năm tuần trước"
}
//end v1.x content
);