define(
//begin v1.x content
{
	"USD_displayName": "Dolara amerikanina",
	"TZS_displayName": "Shilling tanzanianina",
	"ZMW_displayName": "Kwacha zambianina",
	"MAD_displayName": "Dirham marokianina",
	"NGN_displayName": "Naira nigerianina",
	"ZWD_displayName": "Dôlara Zimbaboeanina",
	"SDG_displayName": "Dinara Sodaney",
	"MWK_displayName": "kwacha malawite",
	"KMF_displayName": "Farantsa Komorianina",
	"SCR_displayName": "Ropia Seysheloà",
	"EGP_displayName": "vola venty ejipsiana",
	"CVE_displayName": "Escudo",
	"LYD_displayName": "Dinara Libyanina",
	"MGA_symbol": "Ar",
	"CAD_displayName": "Dôlara Kanadianina",
	"INR_displayName": "Ropia Indianina",
	"JPY_displayName": "Yen Japoney",
	"LRD_displayName": "Dôlara Liberianina",
	"ZAR_displayName": "Rand afrikanina tatsimo",
	"AOA_displayName": "kwanza angoley",
	"TND_displayName": "Dinar tonizianina",
	"GHC_displayName": "cédi",
	"BWP_displayName": "Pola botsoaney",
	"DZD_displayName": "Dinara alzerianina",
	"ZMK_displayName": "Kwacha zambianina (1968–2012)",
	"NAD_displayName": "Dolara namibianina",
	"AED_displayName": "Dirham",
	"ETB_displayName": "Bir etiopianina",
	"MZM_displayName": "Metikaly",
	"BIF_displayName": "Farantsa Borondi",
	"RWF_displayName": "Farantsa Roande",
	"STD_displayName": "Dobra",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Eoro",
	"ERN_displayName": "Nakfà Eritreanina",
	"SAR_displayName": "Rial saodianina",
	"DJF_displayName": "Farantsa Djibotianina",
	"CDF_displayName": "Farantsa kôngôley",
	"GBP_displayName": "livre sterling",
	"CHF_displayName": "Farantsa soisa",
	"MUR_displayName": "Ropia maorisianina",
	"SOS_displayName": "Shilling somalianina",
	"BHD_displayName": "dinar bahreïni",
	"XOF_displayName": "Farantsa CFA (BCEAO)",
	"GNS_displayName": "Farantsa Gineanina",
	"SLL_displayName": "Leone",
	"UGX_displayName": "Shilling ogandianina",
	"MGA_displayName": "Ariary",
	"SDP_displayName": "livre soudanaise (1956–2007)",
	"AUD_displayName": "Dolara aostralianina",
	"KES_displayName": "Shilling kenianina",
	"SHP_displayName": "livre de Sainte-Hélène",
	"XAF_displayName": "Farantsa CFA (BEAC)",
	"LSL_displayName": "Loti",
	"MRO_displayName": "Ouguiya moritanianina",
	"CNY_displayName": "Yoan sinoa Renminbi",
	"GMD_displayName": "Dalasi gambianina"
}
//end v1.x content
);