define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "AM/PM",
	"field-minute": "Minitra",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Omaly",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "Era",
	"field-hour": "Ora",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Anio",
	"field-day-relative+1": "Rahampitso",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Taona",
	"field-week": "Herinandro",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Volana",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Segondra",
	"field-day": "Andro",
	"dateFormatItem-MEd": "E d/M",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);