define(
//begin v1.x content
{
	"field-sat-relative+0": "memleɖa sia",
	"field-sat-relative+1": "memleɖa si gbɔ na",
	"field-dayperiod": "ŋkekea me",
	"field-sun-relative+-1": "kɔsiɖa si va yi",
	"field-mon-relative+-1": "dzoɖa si va yi",
	"field-minute": "aɖabaƒoƒo",
	"field-day-relative+-1": "etsɔ si va yi",
	"field-weekday": "kɔsiɖa me ŋkeke",
	"field-day-relative+-2": "nyitsɔ si va yi",
	"field-era": "ŋɔli",
	"field-hour": "gaƒoƒo",
	"field-sun-relative+0": "kɔsiɖa sia",
	"field-sun-relative+1": "kɔsiɖa si gbɔ na",
	"field-wed-relative+-1": "kuɖa si va yi",
	"field-day-relative+0": "egbe",
	"field-day-relative+1": "etsɔ si gbɔna",
	"field-day-relative+2": "nyitsɔ si gbɔna",
	"field-tue-relative+0": "blaɖa sia",
	"field-zone": "nutomegaƒoƒo",
	"field-tue-relative+1": "blaɖa si gbɔ na",
	"field-week-relative+-1": "kɔsiɖa si va yi",
	"field-year-relative+0": "ƒe sia",
	"field-year-relative+1": "ƒe si gbɔ na",
	"field-sat-relative+-1": "memleɖa si va yi",
	"field-year-relative+-1": "ƒe si va yi",
	"field-year": "ƒe",
	"field-fri-relative+0": "fiɖa sia",
	"field-fri-relative+1": "fiɖa si gbɔ na",
	"field-week": "kɔsiɖa ɖeka",
	"field-week-relative+0": "kɔsiɖa sia",
	"field-week-relative+1": "kɔsiɖa si gbɔ na",
	"field-month-relative+0": "ɣleti sia",
	"field-month": "ɣleti",
	"field-month-relative+1": "ɣleti si gbɔ na",
	"field-fri-relative+-1": "fiɖa si va yi",
	"field-second": "sekend",
	"field-tue-relative+-1": "blaɖa si va yi",
	"field-day": "ŋkeke",
	"field-mon-relative+0": "dzoɖa sia",
	"field-mon-relative+1": "dzoɖa si gbɔ na",
	"field-thu-relative+0": "yawoɖa sia",
	"field-second-relative+0": "fifi",
	"field-thu-relative+1": "yawoɖa si gbɔ na",
	"field-wed-relative+0": "kuɖa sia",
	"field-wed-relative+1": "kuɖa si gbɔ na",
	"field-month-relative+-1": "ɣleti si va yi",
	"field-thu-relative+-1": "yawoɖa si va yi"
}
//end v1.x content
);