define(
//begin v1.x content
{
	"field-second-relative+0": "fifi",
	"field-weekday": "kɔsiɖa me ŋkeke",
	"field-wed-relative+0": "kuɖa sia",
	"dateFormatItem-GyMMMEd": "E, MMM d 'lia' y G",
	"dateFormatItem-MMMEd": "E, MMM d 'lia'",
	"field-wed-relative+1": "kuɖa si gbɔ na",
	"field-tue-relative+-1": "blaɖa si va yi",
	"dateFormat-long": "MMMM d 'lia' y G",
	"field-fri-relative+-1": "fiɖa si va yi",
	"field-wed-relative+-1": "kuɖa si va yi",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{0} {1}",
	"dateFormat-full": "EEEE, MMMM d 'lia' y G",
	"dateFormatItem-yyyyMEd": "E, M/d/y G",
	"field-thu-relative+-1": "yawoɖa si va yi",
	"dateFormatItem-Md": "M/d",
	"field-era": "ŋɔli",
	"field-year": "ƒe",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"field-hour": "gaƒoƒo",
	"field-sat-relative+0": "memleɖa sia",
	"field-sat-relative+1": "memleɖa si gbɔ na",
	"field-day-relative+0": "egbe",
	"field-day-relative+1": "etsɔ si gbɔna",
	"field-thu-relative+0": "yawoɖa sia",
	"dateFormatItem-GyMMMd": "MMM d 'lia', y G",
	"field-day-relative+2": "nyitsɔ si gbɔna",
	"field-thu-relative+1": "yawoɖa si gbɔ na",
	"dateFormatItem-H": "HH",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E, MMM d 'lia' y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "MMM d 'lia', y G",
	"dateFormatItem-MMMMd": "MMMM d 'lia'",
	"field-sun-relative+0": "kɔsiɖa sia",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "kɔsiɖa si gbɔ na",
	"field-minute": "aɖabaƒoƒo",
	"field-dayperiod": "ŋkekea me",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "'aɖabaƒoƒo' mm:ss",
	"field-day-relative+-1": "etsɔ si va yi",
	"dateFormatItem-h": "a 'ga' h",
	"dateTimeFormat-long": "{0} {1}",
	"field-day-relative+-2": "nyitsɔ si va yi",
	"dateFormatItem-MMMd": "MMM d 'lia'",
	"dateFormatItem-MEd": "E, M/d",
	"dateTimeFormat-full": "{0} {1}",
	"field-fri-relative+0": "fiɖa sia",
	"field-fri-relative+1": "fiɖa si gbɔ na",
	"field-day": "ŋkeke",
	"field-zone": "nutomegaƒoƒo",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "ƒe si va yi",
	"field-month-relative+-1": "ɣleti si va yi",
	"dateFormatItem-hm": "a 'ga' h:mm",
	"dateFormatItem-yyyyMd": "M/d/y G",
	"field-month": "ɣleti",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "blaɖa sia",
	"field-tue-relative+1": "blaɖa si gbɔ na",
	"dateFormatItem-MMMMEd": "E, MMMM d 'lia'",
	"field-mon-relative+0": "dzoɖa sia",
	"field-mon-relative+1": "dzoɖa si gbɔ na",
	"dateFormat-short": "M/d/y GGGGG",
	"field-second": "sekend",
	"field-sat-relative+-1": "memleɖa si va yi",
	"field-sun-relative+-1": "kɔsiɖa si va yi",
	"field-month-relative+0": "ɣleti sia",
	"field-month-relative+1": "ɣleti si gbɔ na",
	"dateFormatItem-Ed": "E d",
	"field-week": "kɔsiɖa ɖeka",
	"dateFormat-medium": "MMM d 'lia', y G",
	"field-year-relative+0": "ƒe sia",
	"field-week-relative+-1": "kɔsiɖa si va yi",
	"dateFormatItem-yyyyM": "M/y G",
	"field-year-relative+1": "ƒe si gbɔ na",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "a 'ga' h:mm:ss",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "dzoɖa si va yi",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "kɔsiɖa sia",
	"field-week-relative+1": "kɔsiɖa si gbɔ na"
}
//end v1.x content
);