define(
//begin v1.x content
{
	"days-standAlone-short": [
		"kɔs",
		"dzo",
		"bla",
		"kuɖ",
		"yaw",
		"fiɖ",
		"mem"
	],
	"months-format-narrow": [
		"d",
		"d",
		"t",
		"a",
		"d",
		"m",
		"s",
		"d",
		"a",
		"k",
		"a",
		"d"
	],
	"field-second-relative+0": "fifi",
	"field-weekday": "kɔsiɖa me ŋkeke",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, M/d/y",
	"field-wed-relative+0": "kuɖa sia",
	"field-wed-relative+1": "kuɖa si gbɔ na",
	"dateFormatItem-GyMMMEd": "E, MMM d 'lia' y G",
	"dateFormatItem-MMMEd": "E, MMM d 'lia'",
	"eraNarrow": [
		"hY",
		"Yŋ"
	],
	"field-tue-relative+-1": "blaɖa si va yi",
	"dayPeriods-format-wide-earlyMorning": "fɔŋli",
	"dayPeriods-format-wide-morning": "ŋdi",
	"days-format-short": [
		"kɔs",
		"dzo",
		"bla",
		"kuɖ",
		"yaw",
		"fiɖ",
		"mem"
	],
	"dateFormat-long": "MMMM d 'lia' y",
	"field-fri-relative+-1": "fiɖa si va yi",
	"field-wed-relative+-1": "kuɖa si va yi",
	"months-format-wide": [
		"dzove",
		"dzodze",
		"tedoxe",
		"afɔfĩe",
		"dama",
		"masa",
		"siamlɔm",
		"deasiamime",
		"anyɔnyɔ",
		"kele",
		"adeɛmekpɔxe",
		"dzome"
	],
	"dayPeriods-format-wide-evening": "fiẽ",
	"dateTimeFormat-medium": "{0} {1}",
	"dayPeriods-format-wide-pm": "ɣetrɔ",
	"dateFormat-full": "EEEE, MMMM d 'lia' y",
	"field-thu-relative+-1": "yawoɖa si va yi",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMd": "M/d/y",
	"field-era": "ŋɔli",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"dzove",
		"dzodze",
		"tedoxe",
		"afɔfĩe",
		"dama",
		"masa",
		"siamlɔm",
		"deasiamime",
		"anyɔnyɔ",
		"kele",
		"adeɛmekpɔxe",
		"dzome"
	],
	"timeFormat-short": "a 'ga' h:mm",
	"quarters-format-wide": [
		"kɔta gbãtɔ",
		"kɔta evelia",
		"kɔta etɔ̃lia",
		"kɔta enelia"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"timeFormat-long": "a 'ga' h:mm:ss z",
	"field-year": "ƒe",
	"dateFormatItem-yMMM": "MMM y",
	"field-hour": "gaƒoƒo",
	"months-format-abbr": [
		"dzv",
		"dzd",
		"ted",
		"afɔ",
		"dam",
		"mas",
		"sia",
		"dea",
		"any",
		"kel",
		"ade",
		"dzm"
	],
	"field-sat-relative+0": "memleɖa sia",
	"field-sat-relative+1": "memleɖa si gbɔ na",
	"timeFormat-full": "a h:mm:ss zzzz",
	"dayPeriods-format-wide-earlyAfternoon": "ŋdɔ",
	"field-day-relative+0": "egbe",
	"field-thu-relative+0": "yawoɖa sia",
	"field-day-relative+1": "etsɔ si gbɔna",
	"field-thu-relative+1": "yawoɖa si gbɔ na",
	"dateFormatItem-GyMMMd": "MMM d 'lia', y G",
	"field-day-relative+2": "nyitsɔ si gbɔna",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"dzv",
		"dzd",
		"ted",
		"afɔ",
		"dam",
		"mas",
		"sia",
		"dea",
		"any",
		"kel",
		"ade",
		"dzm"
	],
	"quarters-format-abbr": [
		"k1",
		"k2",
		"k3",
		"k4"
	],
	"quarters-standAlone-wide": [
		"kɔta gbãtɔ",
		"kɔta evelia",
		"kɔta etɔ̃lia",
		"kɔta enelia"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"kɔsiɖa",
		"dzoɖa",
		"blaɖa",
		"kuɖa",
		"yawoɖa",
		"fiɖa",
		"memleɖa"
	],
	"dateFormatItem-MMMMd": "MMMM d 'lia'",
	"timeFormat-medium": "a 'ga' h:mm:ss",
	"field-sun-relative+0": "kɔsiɖa sia",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "kɔsiɖa si gbɔ na",
	"quarters-standAlone-abbr": [
		"k1",
		"k2",
		"k3",
		"k4"
	],
	"eraAbbr": [
		"hY",
		"Yŋ"
	],
	"field-minute": "aɖabaƒoƒo",
	"field-dayperiod": "ŋkekea me",
	"days-standAlone-abbr": [
		"kɔs",
		"dzo",
		"bla",
		"kuɖ",
		"yaw",
		"fiɖ",
		"mem"
	],
	"dayPeriods-format-wide-night": "zã",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "'aɖabaƒoƒo' mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "etsɔ si va yi",
	"dateFormatItem-h": "a 'ga' h",
	"dateTimeFormat-long": "{0} {1}",
	"field-day-relative+-2": "nyitsɔ si va yi",
	"dateFormatItem-MMMd": "MMM d 'lia'",
	"dateFormatItem-MEd": "E, M/d",
	"dateTimeFormat-full": "{0} {1}",
	"field-fri-relative+0": "fiɖa sia",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-fri-relative+1": "fiɖa si gbɔ na",
	"field-day": "ŋkeke",
	"days-format-wide": [
		"kɔsiɖa",
		"dzoɖa",
		"blaɖa",
		"kuɖa",
		"yawoɖa",
		"fiɖa",
		"memleɖa"
	],
	"field-zone": "nutomegaƒoƒo",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"d",
		"d",
		"t",
		"a",
		"d",
		"m",
		"s",
		"d",
		"a",
		"k",
		"a",
		"d"
	],
	"field-year-relative+-1": "ƒe si va yi",
	"field-month-relative+-1": "ɣleti si va yi",
	"dateFormatItem-hm": "a 'ga' h:mm",
	"days-format-abbr": [
		"kɔs",
		"dzo",
		"bla",
		"kuɖ",
		"yaw",
		"fiɖ",
		"mem"
	],
	"dateFormatItem-yMMMd": "MMM d 'lia', y",
	"eraNames": [
		"Hafi Yesu Va Do ŋgɔ",
		"Yesu Ŋɔli"
	],
	"days-format-narrow": [
		"k",
		"d",
		"b",
		"k",
		"y",
		"f",
		"m"
	],
	"days-standAlone-narrow": [
		"k",
		"d",
		"b",
		"k",
		"y",
		"f",
		"m"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "ɣleti",
	"field-tue-relative+0": "blaɖa sia",
	"field-tue-relative+1": "blaɖa si gbɔ na",
	"dayPeriods-format-wide-am": "ŋdi",
	"dateFormatItem-MMMMEd": "E, MMMM d 'lia'",
	"field-mon-relative+0": "dzoɖa sia",
	"field-mon-relative+1": "dzoɖa si gbɔ na",
	"dateFormat-short": "M/d/yy",
	"dayPeriods-format-wide-afternoon": "ɣetrɔ",
	"field-second": "sekend",
	"field-sat-relative+-1": "memleɖa si va yi",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"field-sun-relative+-1": "kɔsiɖa si va yi",
	"field-month-relative+0": "ɣleti sia",
	"field-month-relative+1": "ɣleti si gbɔ na",
	"dateFormatItem-Ed": "E d",
	"field-week": "kɔsiɖa ɖeka",
	"dateFormat-medium": "MMM d 'lia', y",
	"field-year-relative+0": "ƒe sia",
	"field-week-relative+-1": "kɔsiɖa si va yi",
	"field-year-relative+1": "ƒe si gbɔ na",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "a 'ga' h:mm:ss",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "dzoɖa si va yi",
	"field-week-relative+0": "kɔsiɖa sia",
	"field-week-relative+1": "kɔsiɖa si gbɔ na"
}
//end v1.x content
);