define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "फुं/बेलासे",
	"field-minute": "मिनिथ",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "मैया",
	"field-weekday": "सप्ताह के दिन",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "जौथाय",
	"field-hour": "रिंगा",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "दिनै",
	"field-day-relative+1": "गाबोन",
	"dateFormat-long": "MMMM d, y G",
	"field-zone": "ओनसोल",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "बोसोर",
	"field-week": "सबथा/हबथा",
	"dateFormatItem-GGGGyMMMMEEEEdd": "EEEE,dd MMMM GGGGy",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "d-MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "दान",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "सेखेन्द",
	"field-day": "सान",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "M/d/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, MMMM d, y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);