// generated from ldml/main/*.xml, xpath: ldml/numbers
({
	'decimal':",",
	'decimal':"٫",
	'group':".",
	'group':"٬",
	'list':";",
	'list':"؛",
	'percentSign':"%",
	'percentSign':"٪",
	'nativeZeroDigit':"0",
	'nativeZeroDigit':"٠",
	'patternDigit':"#",
	'plusSign':"+",
	'minusSign':"-",
	'exponential':"E",
	'exponential':"اس",
	'perMille':"‰",
	'perMille':"؉",
	'infinity':"∞",
	'nan':"NaN",
	'nan':"ليس رقم",
	'decimalFormat':"#,##0.###;#,##0.###-",
	'currencyFormat':"¤ #,##0.00;¤ #,##0.00-"
})
