define(
//begin v1.x content
{
	"KES_symbol": "Ksh",
	"USD_displayName": "Dola ya Amerika",
	"TZS_displayName": "Shilingi ya Tanzania",
	"ZMW_displayName": "Kwacha ya Zambia",
	"MAD_displayName": "Dirham ya Moroko",
	"NGN_displayName": "Naira ya Nijeria",
	"ZWD_displayName": "Dola ya Zimbabwe",
	"SDG_displayName": "Paũndi ya Sudani",
	"MWK_displayName": "Kwacha ya Malawi",
	"KMF_displayName": "Faranga ya Komoro",
	"SCR_displayName": "Rupia ya Shelisheli",
	"EGP_displayName": "Paũndi ya Misri",
	"CVE_displayName": "Eskudo ya Kepuvede",
	"LYD_displayName": "Dinari ya Libya",
	"CAD_displayName": "Dola ya Kanada",
	"INR_displayName": "Rupia ya India",
	"JPY_displayName": "Sarafu ya japani",
	"LRD_displayName": "Dola ya Liberia",
	"ZAR_displayName": "Randi ya Afrika ya Sauthi",
	"AOA_displayName": "Kwanza ya Angola",
	"TND_displayName": "Dinari ya Tunisia",
	"GHC_displayName": "Sedi ya Ghana",
	"BWP_displayName": "Pula ya Botswana",
	"DZD_displayName": "Dinari ya Anjĩria",
	"ZMK_displayName": "Kwacha ya Zambia (1968–2012)",
	"NAD_displayName": "Dola ya Namibia",
	"AED_displayName": "Dirham ya Falme cia Kiarabu",
	"ETB_displayName": "Bĩrũ ya Ithiopia",
	"MZM_displayName": "Metikali ya Mozambĩkĩ",
	"BIF_displayName": "Faranga ya Burundi",
	"RWF_displayName": "Faranga ya Rwanda",
	"STD_displayName": "Dobra ya Sao Tome na Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakfa ya Eritrea",
	"SAR_displayName": "Riyal ya Saudi Arĩbia",
	"DJF_displayName": "Faranga ya Jibuti",
	"CDF_displayName": "Faranga ya Kongo",
	"GBP_displayName": "Paũndi ya Ngeretha",
	"CHF_displayName": "Faranga ya Swisilandi",
	"MUR_displayName": "Rupia ya Maurĩtiasi",
	"SOS_displayName": "Shilingi ya Somalia",
	"BHD_displayName": "Dinari ya Baharini",
	"XOF_displayName": "Faranga CFA BCEAO",
	"GNS_displayName": "Faranga ya Gine",
	"SLL_displayName": "Leoni",
	"UGX_displayName": "Shilingi ya Uganda",
	"MGA_displayName": "Ariarĩ ya Bukini",
	"AUD_displayName": "Dola ya Austrĩlia",
	"KES_displayName": "Shilingi ya Kenya",
	"SHP_displayName": "Paũndi ya Santahelena",
	"XAF_displayName": "Faranga CFA BEAC",
	"LSL_displayName": "Loti ya Lesoto",
	"MRO_displayName": "Ugwiya ya Mauritania",
	"CNY_displayName": "Yuan Renminbi ya China",
	"GMD_displayName": "Dalasi ya Gambia"
}
//end v1.x content
);