{
 ar: "Arabic",
 cs: "Czech",
 de: "German",
 el: "Greek",
 en: "English",
 'en-au': "English (Australia)",
 'en-us-hawaii': "English (US-Hawaii)",
 'en-us-new_york-brooklyn': "English (Brooklynese)",
 'en-us-texas': "English (Texas)",
 es: "Spanish",
 fa: "Farsi",
 fr: "French",
 he: "Hebrew",
 hi: "Hindi",
 it: "Italian",
 ja: "Japanese",
 ko: "Korean",
 pl: "Polish",
 pt: "Portugese",
 ru: "Russian",
 sw: "Kiswahili",
 th: "Thai",
 tr: "Turkish",
 yi: "Yiddish",
 'zh-cn': "Chinese (Simplified)",
 'zh-tw': "Chinese (Traditional)",
 hello: "Hello",
 dojo: "Dojo",
 hello_dojo: "${hello}, ${dojo}!",
 file_not_found:"The file you requested, ${0}, is not found."
}
