define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Vuche/Vwira",
	"field-minute": "Idagika",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Mgorova",
	"field-weekday": "Mrisiza",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Rimenya",
	"field-hour": "Isaa",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Lero",
	"field-day-relative+1": "Mgamba",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Havundu",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Muhiga",
	"field-week": "Risiza",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Mweri",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "Sekunde",
	"field-day": "Ridiku",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);