define(
//begin v1.x content
{
	"USD_displayName": "edola lok' Amareka",
	"TZS_displayName": "Ango'otol lok' Tanzania",
	"ZMW_displayName": "Ango'otol lok' Zambia",
	"MAD_displayName": "Ango'otol lok' Moroko",
	"NGN_displayName": "Ango'otol lok' Nijeria",
	"ZWD_displayName": "Edola lok'Zimbabwe",
	"SDG_displayName": "Epaunt Lok' Sudan",
	"MWK_displayName": "Ango'otol lok' Malawi",
	"KMF_displayName": "Ango'otol lok' Komoro",
	"SCR_displayName": "Ango'otol lok' Shelisheli",
	"EGP_displayName": "Epaunt lok' Misri",
	"CVE_displayName": "Ango'otol lok' Kepuvede",
	"LYD_displayName": "Ango'otol lok' Libya",
	"CAD_displayName": "Edola lok'Kanada",
	"INR_displayName": "Ango'otol lok' India",
	"JPY_displayName": "Ango'otol lok' Kijapani",
	"LRD_displayName": "edola lok' Liberia",
	"ZAR_displayName": "Ango'otol lok' Afrika Kusini",
	"AOA_displayName": "Ango'otol lok' Angola",
	"TND_displayName": "Ango'otol lok' Tunisia",
	"GHC_displayName": "Sedi ya Ghana",
	"BWP_displayName": "Ango'otol lok' Botswana",
	"DZD_displayName": "Ango'otol lok' Aljeria",
	"ZMK_displayName": "Ango'otol lok' Zambia (1968–2012)",
	"NAD_displayName": "Ango'otol lok' Namibia",
	"AED_displayName": "Ango'otol lok' Falme za Kiarabu",
	"ETB_displayName": "Ango'otol lok' Uhabeshi",
	"MZM_displayName": "Ango'otol lok' Msumbiji",
	"BIF_displayName": "Ango'otol lok' Burundi",
	"RWF_displayName": "Ango'otol lok' Rwanda",
	"STD_displayName": "Ango'otol lok' Sao Tome na Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Ango'otol lok' Eritrea",
	"SAR_displayName": "Ango'otol lok' Saudia",
	"DJF_displayName": "Ango'otol lok' Jibuti",
	"CDF_displayName": "Ango'otol lok' Kongo",
	"GBP_displayName": "Epaunt lok' Uingereza",
	"CHF_displayName": "Ango'otol lok' Uswisi",
	"MUR_displayName": "Ango'otol lok' Morisi",
	"SOS_displayName": "Ango'otol lok' Somalia",
	"BHD_displayName": "Ango'otol lok' Bahareni",
	"XOF_displayName": "Ango'otol lok' CFA BCEAO",
	"UGX_symbol": "USh",
	"GNS_displayName": "Ango'otol lok' Gine",
	"SLL_displayName": "Leoni",
	"UGX_displayName": "Ango'otol lok' Uganda",
	"MGA_displayName": "Ango'otol lok' Bukini",
	"AUD_displayName": "Ango'otol lok' Australia",
	"KES_displayName": "Ango'otol lok' Kenya",
	"SHP_displayName": "Ango'otol lok' Santahelena",
	"XAF_displayName": "Ango'otol lok' CFA BEAC",
	"LSL_displayName": "Ango'otol lok' Lesoto",
	"MRO_displayName": "Ango'otol lok' Moritania",
	"CNY_displayName": "Ango'otol lok' China",
	"GMD_displayName": "Dalasi ya Gambia"
}
//end v1.x content
);