define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, MMM d, U",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} 'at' {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Gy": "U",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-y": "U",
	"dateFormatItem-yyyy": "U",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-GyMMMd": "MMM d, U",
	"dateFormat-long": "MMMM d, U",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "MMM d, U",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "M/d/y",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ U",
	"dateTimeFormat-long": "{1} 'at' {0}",
	"dateFormatItem-yyyyMd": "M/d/y",
	"dateFormatItem-yyyyMMMd": "MMM d, U",
	"dateFormatItem-yyyyMEd": "E, M/d/y",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"months-format-abbr": [
		"Mo1",
		"Mo2",
		"Mo3",
		"Mo4",
		"Mo5",
		"Mo6",
		"Mo7",
		"Mo8",
		"Mo9",
		"Mo10",
		"Mo11",
		"Mo12"
	],
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E, MMM d, U",
	"dateFormatItem-GyMMM": "MMM U",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-yyyyQQQ": "QQQ U",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "M/d/yy",
	"dateFormatItem-yyyyM": "M/y",
	"dateFormat-full": "EEEE, MMMM d, U",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-EHm": "E HH:mm",
	"months-format-wide": [
		"Month1",
		"Month2",
		"Month3",
		"Month4",
		"Month5",
		"Month6",
		"Month7",
		"Month8",
		"Month9",
		"Month10",
		"Month11",
		"Month12"
	],
	"dateFormatItem-yyyyMMM": "MMM U",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);