// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"Andorran Peseta",
	AED_displayName:"United Arab Emirates Dirham",
	AFA_displayName:"Afghani (1927-2002)",
	AFN_displayName:"Afghani",
	AFN_symbol:"Af",
	ALL_displayName:"Albanian Lek",
	ALL_symbol:"lek",
	AMD_displayName:"Armenian Dram",
	AMD_symbol:"dram",
	ANG_displayName:"Netherlands Antillan Guilder",
	ANG_symbol:"NAf.",
	AOA_displayName:"Angolan Kwanza",
	AOA_symbol:"Kz",
	AOK_displayName:"Angolan Kwanza (1977-1990)",
	AON_displayName:"Angolan New Kwanza (1990-2000)",
	AOR_displayName:"Angolan Kwanza Reajustado (1995-1999)",
	ARA_displayName:"Argentine Austral",
	ARP_displayName:"Argentine Peso (1983-1985)",
	ARS_displayName:"Argentine Peso",
	ARS_symbol:"AR$",
	ATS_displayName:"Austrian Schilling",
	AUD_displayName:"Australian Dollar",
	AUD_symbol:"A$",
	AWG_displayName:"Aruban Florin",
	AWG_symbol:"Afl.",
	AZM_displayName:"Azerbaijanian Manat (1993-2006)",
	AZN_displayName:"Azerbaijanian Manat",
	AZN_symbol:"man.",
	BAD_displayName:"Bosnia-Herzegovina Dinar",
	BAM_displayName:"Bosnia-Herzegovina Convertible Mark",
	BAM_symbol:"KM",
	BBD_displayName:"Barbados Dollar",
	BBD_symbol:"Bds$",
	BDT_displayName:"Bangladeshi Taka",
	BDT_symbol:"Tk",
	BEC_displayName:"Belgian Franc (convertible)",
	BEF_displayName:"Belgian Franc",
	BEF_symbol:"BF",
	BEL_displayName:"Belgian Franc (financial)",
	BGL_displayName:"Bulgarian Hard Lev",
	BGL_symbol:"lev",
	BGN_displayName:"Bulgarian Lev",
	BHD_displayName:"Bahraini Dinar",
	BHD_symbol:"BD",
	BIF_displayName:"Burundi Franc",
	BIF_symbol:"FBu",
	BMD_displayName:"Bermudan Dollar",
	BMD_symbol:"BD$",
	BND_displayName:"Brunei Dollar",
	BND_symbol:"B$",
	BOB_displayName:"Boliviano",
	BOB_symbol:"Bs",
	BOP_displayName:"Bolivian Peso",
	BOV_displayName:"Bolivian Mvdol",
	BRB_displayName:"Brazilian Cruzeiro Novo (1967-1986)",
	BRC_displayName:"Brazilian Cruzado",
	BRE_displayName:"Brazilian Cruzeiro (1990-1993)",
	BRL_displayName:"Brazilian Real",
	BRN_displayName:"Brazilian Cruzado Novo",
	BRR_displayName:"Brazilian Cruzeiro",
	BSD_displayName:"Bahamian Dollar",
	BTN_displayName:"Bhutan Ngultrum",
	BTN_symbol:"Nu",
	BUK_displayName:"Burmese Kyat",
	BWP_displayName:"Botswanan Pula",
	BWP_symbol:"P",
	BYB_displayName:"Belarussian New Ruble (1994-1999)",
	BYR_displayName:"Belarussian Ruble",
	BYR_symbol:"Rbl",
	BZD_displayName:"Belize Dollar",
	BZD_symbol:"BZ$",
	CAD_displayName:"Canadian Dollar",
	CAD_symbol:"CA$",
	CDF_displayName:"Congolese Franc Congolais",
	CHE_displayName:"WIR Euro",
	CHF_displayName:"Swiss Franc",
	CHF_symbol:"Fr.",
	CHW_displayName:"WIR Franc",
	CLF_displayName:"Chilean Unidades de Fomento",
	CLP_displayName:"Chilean Peso",
	CLP_symbol:"CL$",
	CNY_displayName:"Chinese Yuan Renminbi",
	CNY_symbol:"RMB",
	COP_displayName:"Colombian Peso",
	COP_symbol:"CO$",
	COU_displayName:"Unidad de Valor Real",
	CRC_displayName:"Costa Rican Colon",
	CRC_symbol:"₡",
	CSD_displayName:"Old Serbian Dinar",
	CSK_displayName:"Czechoslovak Hard Koruna",
	CUP_displayName:"Cuban Peso",
	CVE_displayName:"Cape Verde Escudo",
	CVE_symbol:"Esc",
	CYP_displayName:"Cyprus Pound",
	CYP_symbol:"£C",
	CZK_displayName:"Czech Republic Koruna",
	CZK_symbol:"Kč",
	DDM_displayName:"East German Ostmark",
	DEM_displayName:"Deutsche Mark",
	DJF_displayName:"Djibouti Franc",
	DJF_symbol:"Fdj",
	DKK_displayName:"Danish Krone",
	DKK_symbol:"Dkr",
	DOP_displayName:"Dominican Peso",
	DOP_symbol:"RD$",
	DZD_displayName:"Algerian Dinar",
	DZD_symbol:"DA",
	ECS_displayName:"Ecuador Sucre",
	ECV_displayName:"Ecuador Unidad de Valor Constante (UVC)",
	EEK_displayName:"Estonian Kroon",
	EGP_displayName:"Egyptian Pound",
	EQE_displayName:"Ekwele",
	ERN_displayName:"Eritrean Nakfa",
	ESA_displayName:"Spanish Peseta (A account)",
	ESB_displayName:"Spanish Peseta (convertible account)",
	ESP_displayName:"Spanish Peseta",
	ESP_symbol:"₧",
	ETB_displayName:"Ethiopian Birr",
	ETB_symbol:"Br",
	EUR_displayName:"Euro",
	FIM_displayName:"Finnish Markka",
	FJD_displayName:"Fiji Dollar",
	FJD_symbol:"F$",
	FKP_displayName:"Falkland Islands Pound",
	FRF_displayName:"French Franc",
	GBP_displayName:"British Pound Sterling",
	GBP_symbol:"£",
	GEK_displayName:"Georgian Kupon Larit",
	GEL_displayName:"Georgian Lari",
	GEL_symbol:"lari",
	GHC_displayName:"Ghana Cedi (1979-2007)",
	GHS_displayName:"Ghana Cedi",
	GHS_symbol:"₵",
	GIP_displayName:"Gibraltar Pound",
	GMD_displayName:"Gambia Dalasi",
	GNF_displayName:"Guinea Franc",
	GNF_symbol:"GF",
	GNS_displayName:"Guinea Syli",
	GQE_displayName:"Equatorial Guinea Ekwele Guineana",
	GRD_displayName:"Greek Drachma",
	GTQ_displayName:"Guatemala Quetzal",
	GTQ_symbol:"Q",
	GWE_displayName:"Portuguese Guinea Escudo",
	GWP_displayName:"Guinea-Bissau Peso",
	GYD_displayName:"Guyana Dollar",
	GYD_symbol:"G$",
	HKD_displayName:"Hong Kong Dollar",
	HKD_symbol:"HK$",
	HNL_displayName:"Honduras Lempira",
	HNL_symbol:"L",
	HRD_displayName:"Croatian Dinar",
	HRK_displayName:"Croatian Kuna",
	HTG_displayName:"Haitian Gourde",
	HUF_displayName:"Hungarian Forint",
	HUF_symbol:"Ft",
	IDR_displayName:"Indonesian Rupiah",
	IDR_symbol:"Rp",
	IEP_displayName:"Irish Pound",
	IEP_symbol:"IR£",
	ILP_displayName:"Israeli Pound",
	ILS_displayName:"New Israeli Sheqel",
	ILS_symbol:"₪",
	INR_displayName:"Indian Rupee",
	INR_symbol:"₨",
	IQD_displayName:"Iraqi Dinar",
	IQD_symbol:"ID",
	IRR_displayName:"Iranian Rial",
	IRR_symbol:"RI",
	ISK_displayName:"Icelandic Krona",
	ITL_displayName:"Italian Lira",
	ITL_symbol:"₤",
	JMD_displayName:"Jamaican Dollar",
	JMD_symbol:"J$",
	JOD_displayName:"Jordanian Dinar",
	JOD_symbol:"JD",
	JPY_displayName:"Japanese Yen",
	JPY_symbol:"¥",
	KES_displayName:"Kenyan Shilling",
	KES_symbol:"K Sh",
	KGS_displayName:"Kyrgystan Som",
	KGS_symbol:"som",
	KHR_displayName:"Cambodian Riel",
	KHR_symbol:"CR",
	KMF_displayName:"Comoro Franc",
	KMF_symbol:"CF",
	KPW_displayName:"North Korean Won",
	KRW_displayName:"South Korean Won",
	KRW_symbol:"₩",
	KWD_displayName:"Kuwaiti Dinar",
	KWD_symbol:"KD",
	KYD_displayName:"Cayman Islands Dollar",
	KZT_displayName:"Kazakhstan Tenge",
	KZT_symbol:"T",
	LAK_displayName:"Laotian Kip",
	LBP_displayName:"Lebanese Pound",
	LBP_symbol:"LL",
	LKR_displayName:"Sri Lanka Rupee",
	LKR_symbol:"SL Re",
	LRD_displayName:"Liberian Dollar",
	LSL_displayName:"Lesotho Loti",
	LSL_symbol:"M",
	LSM_displayName:"Maloti",
	LTL_displayName:"Lithuanian Lita",
	LTT_displayName:"Lithuanian Talonas",
	LUC_displayName:"Luxembourg Convertible Franc",
	LUF_displayName:"Luxembourg Franc",
	LUL_displayName:"Luxembourg Financial Franc",
	LVL_displayName:"Latvian Lats",
	LVR_displayName:"Latvian Ruble",
	LYD_displayName:"Libyan Dinar",
	LYD_symbol:"LD",
	MAD_displayName:"Moroccan Dirham",
	MAF_displayName:"Moroccan Franc",
	MDL_displayName:"Moldovan Leu",
	MGA_displayName:"Madagascar Ariary",
	MGF_displayName:"Madagascar Franc",
	MKD_displayName:"Macedonian Denar",
	MKD_symbol:"MDen",
	MLF_displayName:"Mali Franc",
	MMK_displayName:"Myanmar Kyat",
	MNT_displayName:"Mongolian Tugrik",
	MNT_symbol:"₮",
	MOP_displayName:"Macao Pataca",
	MRO_displayName:"Mauritania Ouguiya",
	MRO_symbol:"UM",
	MTL_displayName:"Maltese Lira",
	MTL_symbol:"Lm",
	MTP_displayName:"Maltese Pound",
	MUR_displayName:"Mauritius Rupee",
	MVR_displayName:"Maldive Islands Rufiyaa",
	MWK_displayName:"Malawi Kwacha",
	MWK_symbol:"MK",
	MXN_displayName:"Mexican Peso",
	MXN_symbol:"MEX$",
	MXP_displayName:"Mexican Silver Peso (1861-1992)",
	MXV_displayName:"Mexican Unidad de Inversion (UDI)",
	MYR_displayName:"Malaysian Ringgit",
	MYR_symbol:"RM",
	MZE_displayName:"Mozambique Escudo",
	MZM_displayName:"Old Mozambique Metical",
	MZM_symbol:"Mt",
	MZN_displayName:"Mozambique Metical",
	MZN_symbol:"MTn",
	NAD_displayName:"Namibia Dollar",
	NAD_symbol:"N$",
	NGN_displayName:"Nigerian Naira",
	NGN_symbol:"₦",
	NIC_displayName:"Nicaraguan Cordoba",
	NIC_symbol:"C$",
	NIO_displayName:"Nicaraguan Cordoba Oro",
	NLG_displayName:"Netherlands Guilder",
	NOK_displayName:"Norwegian Krone",
	NOK_symbol:"NKr",
	NPR_displayName:"Nepalese Rupee",
	NPR_symbol:"Nrs",
	NZD_displayName:"New Zealand Dollar",
	NZD_symbol:"NZ$",
	OMR_displayName:"Oman Rial",
	OMR_symbol:"RO",
	PAB_displayName:"Panamanian Balboa",
	PEI_displayName:"Peruvian Inti",
	PEN_displayName:"Peruvian Sol Nuevo",
	PES_displayName:"Peruvian Sol",
	PGK_displayName:"Papua New Guinea Kina",
	PHP_displayName:"Philippine Peso",
	PHP_symbol:"₱",
	PKR_displayName:"Pakistan Rupee",
	PKR_symbol:"Pra",
	PLN_displayName:"Polish Zloty",
	PLN_symbol:"zł",
	PLZ_displayName:"Polish Zloty (1950-1995)",
	PTE_displayName:"Portuguese Escudo",
	PYG_displayName:"Paraguay Guarani",
	PYG_symbol:"₲",
	QAR_displayName:"Qatari Rial",
	QAR_symbol:"QR",
	RHD_displayName:"Rhodesian Dollar",
	ROL_displayName:"Old Romanian Leu",
	RON_displayName:"Romanian Leu",
	RSD_displayName:"Serbian Dinar",
	RUB_displayName:"Russian Ruble",
	RUR_displayName:"Russian Ruble (1991-1998)",
	RWF_displayName:"Rwandan Franc",
	SAR_displayName:"Saudi Riyal",
	SAR_symbol:"SRl",
	SBD_displayName:"Solomon Islands Dollar",
	SBD_symbol:"SI$",
	SCR_displayName:"Seychelles Rupee",
	SCR_symbol:"SR",
	SDD_displayName:"Old Sudanese Dinar",
	SDG_displayName:"Sudanese Pound",
	SDP_displayName:"Old Sudanese Pound",
	SEK_displayName:"Swedish Krona",
	SEK_symbol:"SKr",
	SGD_displayName:"Singapore Dollar",
	SGD_symbol:"S$",
	SHP_displayName:"Saint Helena Pound",
	SIT_displayName:"Slovenia Tolar",
	SKK_displayName:"Slovak Koruna",
	SKK_symbol:"Sk",
	SLL_displayName:"Sierra Leone Leone",
	SOS_displayName:"Somali Shilling",
	SOS_symbol:"Sh.",
	SRD_displayName:"Surinam Dollar",
	SRG_displayName:"Suriname Guilder",
	SRG_symbol:"Sf",
	STD_displayName:"Sao Tome and Principe Dobra",
	STD_symbol:"Db",
	SUR_displayName:"Soviet Rouble",
	SVC_displayName:"El Salvador Colon",
	SYP_displayName:"Syrian Pound",
	SYP_symbol:"LS",
	SZL_displayName:"Swaziland Lilangeni",
	SZL_symbol:"E",
	THB_displayName:"Thai Baht",
	THB_symbol:"฿",
	TJR_displayName:"Tajikistan Ruble",
	TJS_displayName:"Tajikistan Somoni",
	TMM_displayName:"Turkmenistan Manat",
	TND_displayName:"Tunisian Dinar",
	TOP_displayName:"Tonga Paʻanga",
	TOP_symbol:"T$",
	TPE_displayName:"Timor Escudo",
	TRL_displayName:"Old Turkish Lira",
	TRL_symbol:"TL",
	TRY_displayName:"Turkish Lira",
	TTD_displayName:"Trinidad and Tobago Dollar",
	TTD_symbol:"TT$",
	TWD_displayName:"Taiwan New Dollar",
	TWD_symbol:"NT$",
	TZS_displayName:"Tanzanian Shilling",
	TZS_symbol:"T Sh",
	UAH_displayName:"Ukrainian Hryvnia",
	UAH_symbol:"₴",
	UAK_displayName:"Ukrainian Karbovanetz",
	UGS_displayName:"Ugandan Shilling (1966-1987)",
	UGX_displayName:"Ugandan Shilling",
	UGX_symbol:"U Sh",
	USD_displayName:"US Dollar",
	USD_symbol:"$",
	USN_displayName:"US Dollar (Next day)",
	USS_displayName:"US Dollar (Same day)",
	UYI_displayName:"Uruguay Peso en Unidades Indexadas",
	UYP_displayName:"Uruguay Peso (1975-1993)",
	UYU_displayName:"Uruguay Peso Uruguayo",
	UYU_symbol:"Ur$",
	UZS_displayName:"Uzbekistan Sum",
	VEB_displayName:"Venezuelan Bolivar",
	VEB_symbol:"Be",
	VEF_displayName:"Venezuelan Bolivar Fuerte",
	VEF_symbol:"BsF",
	VND_displayName:"Vietnamese Dong",
	VND_symbol:"₫",
	VUV_displayName:"Vanuatu Vatu",
	VUV_symbol:"VT",
	WST_displayName:"Western Samoa Tala",
	XAF_displayName:"CFA Franc BEAC",
	XAG_displayName:"Silver",
	XAU_displayName:"Gold",
	XBA_displayName:"European Composite Unit",
	XBB_displayName:"European Monetary Unit",
	XBC_displayName:"European Unit of Account (XBC)",
	XBD_displayName:"European Unit of Account (XBD)",
	XCD_displayName:"East Caribbean Dollar",
	XCD_symbol:"EC$",
	XDR_displayName:"Special Drawing Rights",
	XEU_displayName:"European Currency Unit",
	XFO_displayName:"French Gold Franc",
	XFU_displayName:"French UIC-Franc",
	XOF_displayName:"CFA Franc BCEAO",
	XPD_displayName:"Palladium",
	XPF_displayName:"CFP Franc",
	XPF_symbol:"CFPF",
	XPT_displayName:"Platinum",
	XRE_displayName:"RINET Funds",
	XTS_displayName:"Testing Currency Code",
	XXX_displayName:"Unknown or Invalid Currency",
	YDD_displayName:"Yemeni Dinar",
	YER_displayName:"Yemeni Rial",
	YER_symbol:"YRl",
	YUD_displayName:"Yugoslavian Hard Dinar",
	YUM_displayName:"Yugoslavian Noviy Dinar",
	YUN_displayName:"Yugoslavian Convertible Dinar",
	ZAL_displayName:"South African Rand (financial)",
	ZAR_displayName:"South African Rand",
	ZAR_symbol:"R",
	ZMK_displayName:"Zambian Kwacha",
	ZRN_displayName:"Zairean New Zaire",
	ZRZ_displayName:"Zairean Zaire",
	ZWD_displayName:"Zimbabwe Dollar",
	ZWD_symbol:"Z$"
})
                 