define(
//begin v1.x content
{
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})",
	"dateFormatItem-yyyyMMMEd": "E, MMM d, y G",
	"dateFormatItem-MMMEd": "E, MMM d",
	"dateTimeFormat-full": "{1} 'at' {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormats-appendItem-Year": "{0} {1}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-y": "y G",
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})",
	"dateFormatItem-yyyy": "y G",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"dateFormatItem-Ed": "d E",
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})",
	"dateFormatItem-GyMMMd": "MMM d, y G",
	"dateFormat-long": "MMMM d, y G",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "MMM d, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{1} 'at' {0}",
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})",
	"dateFormatItem-yyyyMd": "M/d/y GGGGG",
	"dateFormatItem-yyyyMMMd": "MMM d, y G",
	"dateFormatItem-yyyyMEd": "E, M/d/y GGGGG",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-H": "HH",
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E, MMM d, y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}",
	"dateFormatItem-hm": "h:mm a",
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})",
	"dateFormat-short": "M/d/y GGGGG",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormat-full": "EEEE, MMMM d, y G",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"dateTimeFormats-appendItem-Era": "{0} {1}",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);