({
	"dateFormatItem-yM": "M/yyyy", 
	"field-dayperiod": "AM/PM", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-minute": "Minute", 
	"eraNames": [
		"Before Christ", 
		"Anno Domini"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"dateFormatItem-yQQQ": "QQQ yyyy", 
	"field-weekday": "Day of the Week", 
	"days-standAlone-wide": [
		"Sunday", 
		"Monday", 
		"Tuesday", 
		"Wednesday", 
		"Thursday", 
		"Friday", 
		"Saturday"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "Era", 
	"field-hour": "Hour", 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "h:mm:ss a v", 
	"months-standAlone-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"May", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Oct", 
		"Nov", 
		"Dec"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"S", 
		"M", 
		"T", 
		"W", 
		"T", 
		"F", 
		"S"
	], 
	"eraAbbr": [
		"BC", 
		"AD"
	], 
	"dateFormat-long": "MMMM d, yyyy", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Zone", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "MMM d, yyyy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"1st quarter", 
		"2nd quarter", 
		"3rd quarter", 
		"4th quarter"
	], 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMMM": "MMMM yyyy", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Year", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"field-week": "Week", 
	"months-standAlone-wide": [
		"January", 
		"February", 
		"March", 
		"April", 
		"May", 
		"June", 
		"July", 
		"August", 
		"September", 
		"October", 
		"November", 
		"December"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"May", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Oct", 
		"Nov", 
		"Dec"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Month", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"Sun", 
		"Mon", 
		"Tue", 
		"Wed", 
		"Thu", 
		"Fri", 
		"Sat"
	], 
	"pm": "PM", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"S", 
		"M", 
		"T", 
		"W", 
		"T", 
		"F", 
		"S"
	], 
	"field-second": "Second", 
	"field-day": "Day", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"am": "AM", 
	"days-standAlone-abbr": [
		"Sun", 
		"Mon", 
		"Tue", 
		"Wed", 
		"Thu", 
		"Fri", 
		"Sat"
	], 
	"dateFormat-short": "M/d/yy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, yyyy", 
	"dateFormat-full": "EEEE, MMMM d, yyyy", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/yyyy", 
	"months-format-wide": [
		"January", 
		"February", 
		"March", 
		"April", 
		"May", 
		"June", 
		"July", 
		"August", 
		"September", 
		"October", 
		"November", 
		"December"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1st quarter", 
		"2nd quarter", 
		"3rd quarter", 
		"4th quarter"
	], 
	"days-format-wide": [
		"Sunday", 
		"Monday", 
		"Tuesday", 
		"Wednesday", 
		"Thursday", 
		"Friday", 
		"Saturday"
	], 
	"eraNarrow": [
		"B", 
		"A"
	]
})