define(
//begin v1.x content
{
	"USD_displayName": "Ameriki Dollar",
	"TZS_displayName": "Tanzaani Šiiliŋ",
	"ZMW_displayName": "Zambi Kwaca",
	"MAD_displayName": "Maarok Dirham",
	"NGN_displayName": "Naajiriya Neera",
	"ZWD_displayName": "Zimbabwe Dollar",
	"SDG_displayName": "Suudaŋ Dinar",
	"MWK_displayName": "Malaawi Kwaca",
	"KMF_displayName": "Komoor Fraŋ",
	"SCR_displayName": "Seešel Rupii",
	"EGP_displayName": "Misra Pund",
	"CVE_displayName": "Kapuver Escudo",
	"LYD_displayName": "Liibi Dinar",
	"CAD_displayName": "Kanaada Dollar",
	"INR_displayName": "Indu Rupii",
	"JPY_displayName": "Jaapoŋ Yen",
	"LRD_displayName": "Liberia Dollar",
	"ZAR_displayName": "Hawasa Afriki Rand",
	"AOA_displayName": "Angoola Kwanza",
	"TND_displayName": "Tunizi Dinar",
	"GHC_displayName": "Gaana Šiidi",
	"BWP_displayName": "Botswaana Pund",
	"DZD_displayName": "Alžeeri Dinar",
	"ZMK_displayName": "Zambi Kwaca (1968–2012)",
	"NAD_displayName": "Naamibi Dollar",
	"AED_displayName": "Laaraw Immaara Margantey Dirham",
	"ETB_displayName": "Ecioopi Birr",
	"MZM_displayName": "Mozambik Metikal",
	"BIF_displayName": "Burundi Fraŋ",
	"RWF_displayName": "Rwanda Fraŋ",
	"STD_displayName": "Sao Tome nda Prinsipe Dobra",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Eero",
	"ERN_displayName": "Eritree Nafka",
	"SAR_displayName": "Saudiya Riyal",
	"DJF_displayName": "Jibuuti Fraŋ",
	"CDF_displayName": "Kongo Fraŋ",
	"GBP_displayName": "Britin Pund",
	"CHF_displayName": "Swisu Fraŋ",
	"MUR_displayName": "Mooris Rupii",
	"SOS_displayName": "Somaali Šiiliŋ",
	"BHD_displayName": "Bahareen Dinar",
	"XOF_displayName": "CFA Fraŋ (BCEAO)",
	"GNS_displayName": "Ginee Fraŋ",
	"SLL_displayName": "Leeon",
	"UGX_displayName": "Uganda Šiiliŋ",
	"MGA_displayName": "Malgaaši Fraŋ",
	"SDP_displayName": "Suudaŋ Pund",
	"AUD_displayName": "Ostraali Dollar",
	"KES_displayName": "Keeniya Šiiliŋ",
	"SHP_displayName": "Seŋ Helena Fraŋ",
	"XAF_displayName": "CFA Fraŋ (BEAC)",
	"LSL_displayName": "Leezoto Loti",
	"MRO_displayName": "Mooritaani Ugiya",
	"CNY_displayName": "Sinwa Yuan Renminbi",
	"GMD_displayName": "Gambi Dalasi"
}
//end v1.x content
);