define(
//begin v1.x content
{
	"dateFormatItem-yMMMM": "MMMM y",
	"field-thu-narrow-relative+0": "الخميس الحالي",
	"field-thu-narrow-relative+1": "الخميس القادم",
	"field-sun-narrow-relative+0": "الأحد الحالي",
	"field-sun-narrow-relative+1": "الأحد القادم",
	"months-format-wide": [
		"يناير",
		"فبراير",
		"مارس",
		"أبريل",
		"مايو",
		"يونيو",
		"يوليو",
		"أغسطس",
		"سبتمبر",
		"أكتوبر",
		"نوفمبر",
		"ديسمبر"
	],
	"dayPeriods-standAlone-abbr-pm": "م",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-fri-narrow-relative+0": "الجمعة الحالي",
	"field-fri-narrow-relative+1": "الجمعة القادم",
	"eraNarrow": [
		"ق.م",
		"م"
	],
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-yMMMd": "d MMM y",
	"dayPeriods-format-abbr-night1": "في المساء",
	"dayPeriods-format-abbr-night2": "ليلاً",
	"dayPeriods-format-narrow-evening1": "مساءً",
	"days-standAlone-narrow": [
		"ح",
		"ن",
		"ث",
		"ر",
		"خ",
		"ج",
		"س"
	],
	"days-standAlone-wide": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"dayPeriods-format-abbr-afternoon1": "ظهرًا",
	"dayPeriods-format-wide-evening1": "مساءً",
	"dayPeriods-format-abbr-afternoon2": "بعد الظهر",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-wed-narrow-relative+-1": "الأربعاء الماضي",
	"dayPeriods-standAlone-wide-evening1": "مساءً",
	"days-format-wide": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"dateFormatItem-yMM": "MM‏/y",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dayPeriods-standAlone-narrow-evening1": "مساءً",
	"dayPeriods-standAlone-abbr-afternoon1": "ظهرًا",
	"dayPeriods-standAlone-abbr-afternoon2": "بعد الظهر",
	"field-thu-relative+0": "الخميس الحالي",
	"dayPeriods-standAlone-abbr-night1": "منتصف الليل",
	"field-thu-relative+1": "الخميس القادم",
	"dayPeriods-standAlone-abbr-night2": "ليلاً",
	"dayPeriods-format-wide-am": "ص",
	"field-fri-relative+0": "الجمعة الحالي",
	"field-fri-relative+1": "الجمعة القادم",
	"dateFormatItem-yMd": "d‏/M‏/y",
	"field-thu-narrow-relative+-1": "الخميس الماضي",
	"field-quarter-relative+0": "هذا الربع",
	"field-quarter-relative+1": "الربع القادم",
	"field-sun-short-relative+0": "الأحد الحالي",
	"timeFormat-short": "h:mm a",
	"field-sun-short-relative+1": "الأحد القادم",
	"dateFormatItem-hms": "h:mm:ss a",
	"dayPeriods-format-narrow-afternoon1": "ظهرًا",
	"dateFormatItem-Md": "d/‏M",
	"dayPeriods-format-narrow-afternoon2": "بعد الظهر",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"field-week-narrow": "الأسبوع",
	"field-hour-relative+0": "الساعة الحالية",
	"field-day-relative+-1": "أمس",
	"field-day-relative+-2": "أول أمس",
	"field-mon-narrow-relative+-1": "الإثنين الماضي",
	"field-minute-narrow": "الدقائق",
	"dateFormatItem-MMMMEd": "E، d MMMM",
	"field-thu-short-relative+0": "الخميس الحالي",
	"field-mon-relative+0": "الإثنين الحالي",
	"field-thu-short-relative+1": "الخميس القادم",
	"field-mon-relative+1": "الإثنين القادم",
	"field-day-narrow-relative+0": "اليوم",
	"field-era-short": "العصر",
	"field-day-narrow-relative+1": "غدًا",
	"field-sat-narrow-relative+0": "السبت الحالي",
	"field-day-narrow-relative+2": "بعد الغد",
	"timeFormat-long": "h:mm:ss a z",
	"field-sat-narrow-relative+1": "السبت القادم",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+0": "الأربعاء الحالي",
	"field-wed-narrow-relative+1": "الأربعاء القادم",
	"field-month": "الشهر",
	"months-standAlone-wide": [
		"يناير",
		"فبراير",
		"مارس",
		"أبريل",
		"مايو",
		"يونيو",
		"يوليو",
		"أغسطس",
		"سبتمبر",
		"أكتوبر",
		"نوفمبر",
		"ديسمبر"
	],
	"field-weekday-narrow": "اليوم",
	"dayPeriods-standAlone-narrow-afternoon1": "ظهرًا",
	"dayPeriods-standAlone-narrow-afternoon2": "بعد الظهر",
	"field-year-relative+0": "السنة الحالية",
	"field-year-relative+1": "السنة القادمة",
	"dayPeriods-format-abbr-evening1": "مساءً",
	"field-tue-relative+0": "الثلاثاء الحالي",
	"field-tue-relative+1": "الثلاثاء القادم",
	"dayPeriods-standAlone-abbr-evening1": "مساءً",
	"dateFormatItem-hm": "h:mm a",
	"field-year-narrow": "السنة",
	"field-tue-short-relative+0": "الثلاثاء الحالي",
	"field-tue-short-relative+1": "الثلاثاء القادم",
	"field-tue-narrow-relative+0": "الثلاثاء الحالي",
	"field-tue-narrow-relative+1": "الثلاثاء القادم",
	"dateTimeFormat-full": "{1} في {0}",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-EBhm": "E h:mm B",
	"dateFormatItem-H": "HH",
	"field-wed-relative+0": "الأربعاء الحالي",
	"field-wed-relative+1": "الأربعاء القادم",
	"dateFormatItem-M": "L",
	"field-wed-short-relative+0": "الأربعاء الحالي",
	"field-fri-short-relative+0": "الجمعة الحالي",
	"field-wed-short-relative+1": "الأربعاء القادم",
	"field-fri-short-relative+1": "الجمعة القادم",
	"field-weekOfMonth-short": "أسبوع من شهر",
	"field-quarter-short-relative+-1": "الربع الأخير",
	"field-year-short-relative+-1": "↑↑↑",
	"dateFormatItem-Bhm": "h:mm B",
	"dayPeriods-format-wide-night1": "في المساء",
	"dayPeriods-format-wide-night2": "ليلاً",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-quarter-narrow-relative+-1": "الربع الأخير",
	"dateFormatItem-d": "d",
	"dayPeriods-format-abbr-pm": "م",
	"dateFormatItem-h": "h a",
	"quarters-standAlone-wide": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"field-weekOfMonth-narrow": "أسبوع/شهر",
	"dateFormatItem-y": "y",
	"field-minute-relative+0": "هذه الدقيقة",
	"field-year-short-relative+0": "↑↑↑",
	"dateFormatItem-EBhms": "E h:mm:ss B",
	"field-year-short-relative+1": "↑↑↑",
	"field-weekday": "اليوم",
	"dayPeriods-format-narrow-pm": "م",
	"field-tue-narrow-relative+-1": "الثلاثاء الماضي",
	"dateFormatItem-yMEd": "E، d/‏M/‏y",
	"dayPeriods-standAlone-wide-night1": "منتصف الليل",
	"dayPeriods-standAlone-wide-night2": "ليلاً",
	"field-year-narrow-relative+-1": "↑↑↑",
	"field-sat-relative+-1": "السبت الماضي",
	"dayPeriods-format-narrow-morning1": "فجرًا",
	"dayPeriods-format-narrow-morning2": "صباحًا",
	"dayPeriods-format-wide-morning1": "في الصباح",
	"dayPeriods-format-wide-morning2": "صباحًا",
	"dayPeriods-standAlone-narrow-pm": "م",
	"dayPeriods-standAlone-wide-morning1": "فجرًا",
	"field-mon-narrow-relative+0": "الإثنين الحالي",
	"dayPeriods-standAlone-wide-morning2": "صباحًا",
	"field-mon-narrow-relative+1": "الإثنين القادم",
	"field-second": "الثواني",
	"dateFormatItem-yMMMEd": "E، d MMM y",
	"field-year-relative+-1": "السنة الماضية",
	"field-weekdayOfMonth-short": "يوم عمل من شهر",
	"dateFormat-short": "d‏/M‏/y",
	"eraNames": [
		"قبل الميلاد",
		"ميلادي"
	],
	"field-second-short": "الثواني",
	"field-thu-short-relative+-1": "الخميس الماضي",
	"field-zone": "التوقيت",
	"field-dayperiod-narrow": "ص/م",
	"field-sun-short-relative+-1": "الأحد الماضي",
	"dayPeriods-standAlone-narrow-morning1": "فجرًا",
	"dayPeriods-standAlone-narrow-morning2": "صباحًا",
	"eraAbbr": [
		"ق.م",
		"م"
	],
	"field-week-short": "الأسبوع",
	"dayPeriods-standAlone-abbr-am": "ص",
	"dayPeriods-standAlone-wide-pm": "مساءً",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+0": "اليوم",
	"field-day-relative+1": "غدًا",
	"field-day-relative+2": "بعد الغد",
	"field-day-short-relative+0": "اليوم",
	"field-dayOfYear-short": "يوم من سنة",
	"field-day-short-relative+1": "غدًا",
	"dateFormat-long": "d MMMM y",
	"field-day-short-relative+2": "بعد الغد",
	"field-sun-narrow-relative+-1": "الأحد الماضي",
	"field-second-relative+0": "الآن",
	"field-quarter-relative+-1": "الربع الأخير",
	"dayPeriods-format-narrow-night1": "منتصف الليل",
	"dayPeriods-format-narrow-night2": "ليلاً",
	"quarters-format-abbr": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"dayPeriods-standAlone-narrow-night1": "منتصف الليل",
	"dayPeriods-standAlone-narrow-night2": "ليلاً",
	"field-week-relative+-1": "الأسبوع الماضي",
	"dayPeriods-format-abbr-morning1": "فجرًا",
	"field-month-relative+-1": "الشهر الماضي",
	"dayPeriods-format-abbr-morning2": "ص",
	"months-format-narrow": [
		"ي",
		"ف",
		"م",
		"أ",
		"و",
		"ن",
		"ل",
		"غ",
		"س",
		"ك",
		"ب",
		"د"
	],
	"field-year": "السنة",
	"field-era": "العصر",
	"dayPeriods-standAlone-abbr-morning1": "فجرًا",
	"dayPeriods-standAlone-abbr-morning2": "ص",
	"days-standAlone-short": [
		"أحد",
		"إثنين",
		"ثلاثاء",
		"أربعاء",
		"خميس",
		"جمعة",
		"سبت"
	],
	"quarters-format-narrow": [
		"١",
		"٢",
		"٣",
		"٤"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-day-short-relative+-1": "أمس",
	"field-day-short-relative+-2": "أول أمس",
	"dateFormatItem-GyMMM": "MMM y G",
	"timeFormat-full": "h:mm:ss a zzzz",
	"dateFormatItem-Bhms": "h:mm:ss B",
	"field-hour": "الساعات",
	"field-dayOfYear-narrow": "يوم/سنة",
	"field-quarter": "ربع السنة",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"dateFormatItem-MMdd": "dd‏/MM",
	"field-day": "يوم",
	"field-mon-relative+-1": "الإثنين الماضي",
	"field-dayOfYear": "يوم من السنة",
	"dateFormat-medium": "dd‏/MM‏/y",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-MEd": "E، d/‏M",
	"field-tue-short-relative+-1": "الثلاثاء الماضي",
	"field-year-short": "السنة",
	"field-month-short": "الشهر",
	"dateFormatItem-MMMEd": "E، d MMM",
	"dayPeriods-format-wide-afternoon1": "ظهرًا",
	"dateFormatItem-MMMd": "d MMM",
	"dayPeriods-format-wide-afternoon2": "بعد الظهر",
	"dateFormatItem-Bh": "h B",
	"months-format-abbr": [
		"يناير",
		"فبراير",
		"مارس",
		"أبريل",
		"مايو",
		"يونيو",
		"يوليو",
		"أغسطس",
		"سبتمبر",
		"أكتوبر",
		"نوفمبر",
		"ديسمبر"
	],
	"dayPeriods-format-abbr-am": "ص",
	"field-sat-relative+0": "السبت الحالي",
	"field-sat-relative+1": "السبت القادم",
	"dayPeriods-format-wide-pm": "م",
	"field-zone-short": "توقيت",
	"days-standAlone-abbr": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"field-week-short-relative+0": "↑↑↑",
	"field-week-short-relative+1": "↑↑↑",
	"dayPeriods-standAlone-wide-afternoon1": "ظهرًا",
	"dayPeriods-standAlone-wide-afternoon2": "بعد الظهر",
	"field-fri-short-relative+-1": "الجمعة الماضي",
	"field-month-narrow": "الشهر",
	"dayPeriods-format-narrow-am": "ص",
	"field-month-narrow-relative+-1": "↑↑↑",
	"days-format-abbr": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"field-weekday-short": "اليوم",
	"field-day-narrow-relative+-1": "أمس",
	"field-day-narrow-relative+-2": "أول أمس",
	"field-quarter-short": "ربع السنة",
	"days-format-short": [
		"أحد",
		"إثنين",
		"ثلاثاء",
		"أربعاء",
		"خميس",
		"جمعة",
		"سبت"
	],
	"months-standAlone-narrow": [
		"ي",
		"ف",
		"م",
		"أ",
		"و",
		"ن",
		"ل",
		"غ",
		"س",
		"ك",
		"ب",
		"د"
	],
	"days-format-narrow": [
		"ح",
		"ن",
		"ث",
		"ر",
		"خ",
		"ج",
		"س"
	],
	"dateFormatItem-EHm": "E HH:mm",
	"field-quarter-narrow": "ربع السنة",
	"field-mon-short-relative+0": "الإثنين الحالي",
	"field-mon-short-relative+1": "الإثنين القادم",
	"field-dayperiod-short": "ص/م",
	"dayPeriods-standAlone-narrow-am": "ص",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-thu-relative+-1": "الخميس الماضي",
	"field-fri-narrow-relative+-1": "الجمعة الماضي",
	"field-mon-short-relative+-1": "الإثنين الماضي",
	"timeFormat-medium": "h:mm:ss a",
	"field-quarter-short-relative+0": "هذا الربع",
	"field-quarter-short-relative+1": "الربع القادم",
	"dateFormatItem-Ed": "E، d",
	"field-wed-relative+-1": "الأربعاء الماضي",
	"field-weekOfMonth": "الأسبوع من الشهر",
	"field-weekdayOfMonth-narrow": "يوم عمل/شهر",
	"dayPeriods-standAlone-wide-am": "صباحًا",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-fri-relative+-1": "الجمعة الماضي",
	"field-minute": "الدقائق",
	"quarters-standAlone-narrow": [
		"١",
		"٢",
		"٣",
		"٤"
	],
	"quarters-format-wide": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"field-day-short": "يوم",
	"field-dayperiod": "ص/م",
	"field-hour-short": "الساعات",
	"months-standAlone-abbr": [
		"يناير",
		"فبراير",
		"مارس",
		"أبريل",
		"مايو",
		"يونيو",
		"يوليو",
		"أغسطس",
		"سبتمبر",
		"أكتوبر",
		"نوفمبر",
		"ديسمبر"
	],
	"field-second-narrow": "الثواني",
	"field-month-relative+0": "هذا الشهر",
	"field-month-relative+1": "الشهر القادم",
	"dateFormat-full": "EEEE، d MMMM y",
	"field-era-narrow": "العصر",
	"field-sat-short-relative+-1": "السبت الماضي",
	"field-week-short-relative+-1": "↑↑↑",
	"dateTimeFormat-long": "{1} في {0}",
	"dateFormatItem-yM": "M‏/y",
	"field-sun-relative+-1": "الأحد الماضي",
	"field-wed-short-relative+-1": "الأربعاء الماضي",
	"field-weekdayOfMonth": "يوم عمل من الشهر",
	"field-quarter-narrow-relative+0": "هذا الربع",
	"dateFormatItem-GyMMMEd": "E، d MMM y G",
	"field-quarter-narrow-relative+1": "الربع القادم",
	"field-sat-short-relative+0": "السبت الحالي",
	"field-hour-narrow": "الساعات",
	"field-sat-short-relative+1": "السبت القادم",
	"field-year-narrow-relative+0": "↑↑↑",
	"field-year-narrow-relative+1": "↑↑↑",
	"dateFormatItem-Gy": "y G",
	"field-zone-narrow": "توقيت",
	"field-tue-relative+-1": "الثلاثاء الماضي",
	"field-minute-short": "الدقائق",
	"dateFormatItem-yw": "الأسبوع w من سنة Y",
	"dateFormatItem-Hm": "HH:mm",
	"field-week-relative+0": "هذا الأسبوع",
	"field-week-relative+1": "الأسبوع القادم",
	"dateFormatItem-MMM": "LLL",
	"field-sun-relative+0": "الأحد الحالي",
	"field-sun-relative+1": "الأحد القادم",
	"field-sat-narrow-relative+-1": "السبت الماضي",
	"quarters-standAlone-abbr": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"dateFormatItem-MMMMW": "الأسبوع W من MMMM",
	"field-month-short-relative+-1": "↑↑↑",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-week": "الأسبوع",
	"field-day-narrow": "يوم"
}
//end v1.x content
);