({
	"quarters-format-abbr": [
		"الربع الأول", 
		"الربع الثاني", 
		"الربع الثالث", 
		"الربع الرابع"
	], 
	"dateFormat-medium": "dd‏/MM‏/yyyy", 
	"dateFormatItem-MMMEd": "E d MMM", 
	"dateFormatItem-yMEd": "EEE، d/‏M/‏yyyy", 
	"timeFormat-full": "zzzz h:mm:ss a", 
	"dateFormatItem-Md": "d/‏M", 
	"months-standAlone-wide": [
		"تشري", 
		"مرحشوان", 
		"كيسلو", 
		"طيفت", 
		"شباط", 
		"آذار الأول", 
		"آذار الثاني", 
		"نيسان", 
		"أيار", 
		"سيفان", 
		"تموز", 
		"آب"
	], 
	"days-standAlone-narrow": [
		"ح", 
		"ن", 
		"ث", 
		"ر", 
		"خ", 
		"ج", 
		"س"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"months-standAlone-abbr": [
		"تشري", 
		"مرحشوان", 
		"كيسلو", 
		"طيفت", 
		"شباط", 
		"آذار الأول", 
		"آذار الثاني", 
		"نيسان", 
		"أيار", 
		"سيفان", 
		"تموز", 
		"آب", 
		"أيلول"
	], 
	"quarters-standAlone-narrow": [
		"١", 
		"٢", 
		"٣", 
		"٤"
	], 
	"timeFormat-medium": "h:mm:ss a", 
	"dateFormat-long": "d MMMM، y", 
	"dateFormat-short": "d‏/M‏/yyyy", 
	"dateFormatItem-yMMMEd": "EEE، d MMMM y", 
	"months-format-wide": [
		"تشري", 
		"مرحشوان", 
		"كيسلو", 
		"طيفت", 
		"شباط", 
		"آذار الأول", 
		"آذار الثاني", 
		"نيسان", 
		"أيار", 
		"سيفان", 
		"تموز", 
		"آب"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-yM": "M‏/yyyy", 
	"timeFormat-short": "h:mm a", 
	"months-format-abbr": [
		"تشري", 
		"مرحشوان", 
		"كيسلو", 
		"طيفت", 
		"شباط", 
		"آذار الأول", 
		"آذار الثاني", 
		"نيسان", 
		"أيار", 
		"سيفان", 
		"تموز", 
		"آب", 
		"أيلول"
	], 
	"days-format-wide": [
		"الأحد", 
		"الإثنين", 
		"الثلاثاء", 
		"الأربعاء", 
		"الخميس", 
		"الجمعة", 
		"السبت"
	], 
	"timeFormat-long": "z h:mm:ss a", 
	"dateFormatItem-yQ": "yyyy Q", 
	"dateFormatItem-yMMM": "MMM y", 
	"quarters-format-wide": [
		"الربع الأول", 
		"الربع الثاني", 
		"الربع الثالث", 
		"الربع الرابع"
	], 
	"dateFormat-full": "EEEE، d MMMM، y", 
	"dateFormatItem-MMMd": "d MMM", 
	"days-format-abbr": [
		"أحد", 
		"إثنين", 
		"ثلاثاء", 
		"أربعاء", 
		"خميس", 
		"جمعة", 
		"سبت"
	]
})