define(
//begin v1.x content
{
	"dateFormat-medium": "d MMM، y G",
	"dateFormatItem-MMMEd": "E، d MMM",
	"dateFormatItem-MEd": "E، d-M",
	"dateFormatItem-yMEd": "E، d/‏M/‏yyyy",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-H": "HH",
	"months-format-narrow": [
		"١",
		"٢",
		"٣",
		"٤",
		"٥",
		"٦",
		"٧",
		"٨",
		"٩",
		"١٠",
		"١١",
		"١٢"
	],
	"dateFormatItem-y": "y",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Md": "d/‏M",
	"months-standAlone-narrow": [
		"م",
		"ص",
		"ر",
		"ر",
		"ج",
		"ج",
		"ر",
		"ش",
		"ر",
		"ش",
		"ذ",
		"ذ"
	],
	"months-standAlone-wide": [
		"محرم",
		null,
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		null,
		null,
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-MMMMEd": "E، d MMMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"months-standAlone-abbr": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormat-long": "d MMMM y",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "d‏/M‏/yyyy",
	"dateFormatItem-yMMMEd": "E، d MMM y",
	"months-format-wide": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-d": "d",
	"dateFormatItem-yM": "M‏/yyyy",
	"months-format-abbr": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"eraAbbr": [
		"هـ"
	],
	"dateFormatItem-h": "h a",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormat-full": "EEEE، d MMMM y",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-Ed": "d E"
}
//end v1.x content
);