define(
//begin v1.x content
{
	"USD_displayName": "Amɛrika Dɔla",
	"TZS_displayName": "Tanzania Hyelen",
	"ZMW_displayName": "Zambia Kwacha",
	"MAD_displayName": "Moroko Diram",
	"NGN_displayName": "Naegyeria Naira",
	"ZWD_displayName": "Zimbabwe Dɔla",
	"SDG_displayName": "Sudan Dina",
	"GHS_displayName": "Ghana Sidi",
	"MWK_displayName": "Malawi Kwacha",
	"KMF_displayName": "Komoro Frank",
	"SCR_displayName": "Seyhyɛls Rupi",
	"EGP_displayName": "Egypt Pɔn",
	"CVE_displayName": "Ɛskudo",
	"LYD_displayName": "Libya Dina",
	"CAD_displayName": "Kanada Dɔla",
	"INR_displayName": "India Rupi",
	"JPY_displayName": "Gyapan Yɛn",
	"LRD_displayName": "Laeberia Dɔla",
	"ZAR_displayName": "Afrika Anaafo Rand",
	"AOA_displayName": "Angola Kwanza",
	"TND_displayName": "Tunisia Dina",
	"GHC_displayName": "Ghana Sidi (1979–2007)",
	"BWP_displayName": "Botswana Pula",
	"DZD_displayName": "Ɔlgyeria Dina",
	"ZMK_displayName": "Zambia Kwacha (1968–2012)",
	"NAD_displayName": "Namibia Dɔla",
	"AED_displayName": "Ɛmirete Arab Nkabɔmu Deram",
	"ETB_displayName": "Itiopia Bir",
	"MZM_displayName": "Mozambik Metical",
	"BIF_displayName": "Burundi Frank",
	"RWF_displayName": "Rewanda Frank",
	"STD_displayName": "Sao Tome ne Principe Dobra",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Iro",
	"ERN_displayName": "Ɛretereya Nakfa",
	"SAR_displayName": "Saudi Riyal",
	"GHS_symbol": "GH₵",
	"DJF_displayName": "Gyebuti Frank",
	"GBP_displayName": "Breten Pɔn",
	"CDF_displayName": "Kongo Frank",
	"MUR_displayName": "Mɔrehyeɔs Rupi",
	"SOS_displayName": "Somailia Hyelen",
	"BHD_displayName": "Baren Dina",
	"GNS_displayName": "Gini Frank",
	"SLL_displayName": "Leone",
	"UGX_displayName": "Uganda Hyelen",
	"MGA_displayName": "Madagasi Frank",
	"SDP_displayName": "Sudan Pɔn",
	"AUD_displayName": "Ɔstrelia Dɔla",
	"KES_displayName": "Kenya Hyelen",
	"SHP_displayName": "St Helena Pɔn",
	"XAF_displayName": "Sefa",
	"LSL_displayName": "Lesoto Loti",
	"MRO_displayName": "Mɔretenia Ouguiya",
	"CNY_displayName": "Yuan",
	"GMD_displayName": "Gambia Dalasi"
}
//end v1.x content
);