define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Da bere",
	"field-minute": "Sema",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Ndeda",
	"field-weekday": "Dapɛn mu da",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Bere",
	"field-hour": "Dɔnhwer",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Ndɛ",
	"field-day-relative+1": "Ɔkyena",
	"dateFormat-long": "G y MMMM d",
	"field-zone": "Bere apaamu",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "G y MMM d",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "y/M/d",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Afe",
	"field-week": "Dapɛn",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Bosome",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "Sɛkɛnd",
	"field-day": "Da",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "GGGGG yy/MM/dd",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, G y MMMM dd",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);