({
	"dateFormatItem-yM": "M.yyyy", 
	"field-dayperiod": "לפה״צ/אחה״צ", 
	"dayPeriods-format-wide-pm": "אחה״צ", 
	"dateFormatItem-yQ": "yyyy Q", 
	"field-minute": "דקה", 
	"eraNames": [
		"לפני הספירה", 
		"לספירה"
	], 
	"dateFormatItem-MMMEd": "E, d בMMM", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"field-weekday": "יום בשבוע", 
	"days-standAlone-wide": [
		"יום ראשון", 
		"יום שני", 
		"יום שלישי", 
		"יום רביעי", 
		"יום חמישי", 
		"יום שישי", 
		"יום שבת"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-format-wide-am": "לפנה״צ", 
	"field-era": "תקופה", 
	"field-hour": "שעה", 
	"quarters-standAlone-abbr": [
		"רבעון 1", 
		"רבעון 2", 
		"רבעון 3", 
		"רבעון 4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-yyyy": "y", 
	"months-standAlone-abbr": [
		"ינו׳", 
		"פבר׳", 
		"מרס", 
		"אפר׳", 
		"מאי", 
		"יונ׳", 
		"יול׳", 
		"אוג׳", 
		"ספט׳", 
		"אוק׳", 
		"נוב׳", 
		"דצמ׳"
	], 
	"dateFormatItem-Ed": "E ה-d", 
	"dateFormatItem-yMMM": "MMM y", 
	"days-standAlone-narrow": [
		"א", 
		"ב", 
		"ג", 
		"ד", 
		"ה", 
		"ו", 
		"ש"
	], 
	"eraAbbr": [
		"לפנה״ס", 
		"לסה״נ"
	], 
	"dateFormatItem-yyyyMM": "MM/yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d בMMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-EEEd": "EEE ה-d", 
	"field-zone": "אזור", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d בMMM yyyy", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yyMMM": "MMM yyyy", 
	"quarters-standAlone-wide": [
		"רבעון 1", 
		"רבעון 2", 
		"רבעון 3", 
		"רבעון 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "שנה", 
	"field-week": "שבוע", 
	"months-standAlone-wide": [
		"ינואר", 
		"פברואר", 
		"מרס", 
		"אפריל", 
		"מאי", 
		"יוני", 
		"יולי", 
		"אוגוסט", 
		"ספטמבר", 
		"אוקטובר", 
		"נובמבר", 
		"דצמבר"
	], 
	"dateFormatItem-MMMMEd": "E, d בMMMM", 
	"dateFormatItem-MMMd": "d בMMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"ינו", 
		"פבר", 
		"מרס", 
		"אפר", 
		"מאי", 
		"יונ", 
		"יול", 
		"אוג", 
		"ספט", 
		"אוק", 
		"נוב", 
		"דצמ"
	], 
	"timeFormat-short": "HH:mm", 
	"dateFormatItem-H": "HH", 
	"field-month": "חודש", 
	"dateFormatItem-MMMMd": "d בMMMM", 
	"quarters-format-abbr": [
		"רבעון 1", 
		"רבעון 2", 
		"רבעון 3", 
		"רבעון 4"
	], 
	"days-format-abbr": [
		"יום א׳", 
		"יום ב׳", 
		"יום ג׳", 
		"יום ד׳", 
		"יום ה׳", 
		"יום ו׳", 
		"שבת"
	], 
	"dateFormatItem-M": "L", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"א", 
		"ב", 
		"ג", 
		"ד", 
		"ה", 
		"ו", 
		"ש"
	], 
	"field-second": "שנייה", 
	"field-day": "יום", 
	"dateFormatItem-MEd": "E, M-d", 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"יום א׳", 
		"יום ב׳", 
		"יום ג׳", 
		"יום ד׳", 
		"יום ה׳", 
		"יום ו׳", 
		"שבת"
	], 
	"dateFormat-short": "dd/MM/yy", 
	"dateFormatItem-yMMMEd": "EEE, d בMMM y", 
	"dateFormat-full": "EEEE, d בMMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE, d.M.yyyy", 
	"months-format-wide": [
		"ינואר", 
		"פברואר", 
		"מרס", 
		"אפריל", 
		"מאי", 
		"יוני", 
		"יולי", 
		"אוגוסט", 
		"ספטמבר", 
		"אוקטובר", 
		"נובמבר", 
		"דצמבר"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"רבעון 1", 
		"רבעון 2", 
		"רבעון 3", 
		"רבעון 4"
	], 
	"days-format-wide": [
		"יום ראשון", 
		"יום שני", 
		"יום שלישי", 
		"יום רביעי", 
		"יום חמישי", 
		"יום שישי", 
		"יום שבת"
	], 
	"eraNarrow": [
		"לפנה״ס", 
		"לסה״נ"
	]
})