// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
        'months-format-abbr':["ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic"],
        'months-format-wide':["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],
        'months-standAlone-narrow':["E","F","M","A","M","J","J","A","S","O","N","D"],
        'days-format-abbr':["dom","lun","mar","mié","jue","vie","sáb"],
        'days-format-wide':["domingo","lunes","martes","miércoles","jueves","viernes","sábado"],
        'days-standAlone-narrow':["D","L","M","M","J","V","S"],
        'quarters-format-abbreviated':["T1","T2","T3","T4"],
        'quarters-format-wide':["1er trimestre","2º trimestre","3er trimestre","4º trimestre"],
        'am':"a.m.",
        'pm':"p.m.",
        'eraNames':["antes de Cristo","anno Dómini"],
        'eraAbbr':["a.C.","d.C."],
        'dateFormat-full': "EEEE d 'de' MMMM 'de' yyyy",
        'dateFormat-long': "d 'de' MMMM 'de' yyyy",
        'dateFormat-medium': "dd/MM/yyyy",
        'dateFormat-short': "dd/MM/yy",
        'timeFormat-full': "hh:mm:ss a v",
        'dateTimeAvailableFormats':"QQQQ 'de' yy",
        'field-era':"era",
        'field-year':"año",
        'field-month':"mes",
        'field-week':"semana",
        'field-day':"día",
        'field-weekday':"día de la semana",
        'field-dayperiod':"periodo del día",
        'field-hour':"hora",
        'field-minute':"minuto",
        'field-second':"segundo",
        'field-zone':"zona"
})
                        