define(
//begin v1.x content
{
	"USD_displayName": "Dóola ya Amerɨ́ka",
	"TZS_displayName": "Shilíingi ya Taansanía",
	"ZMW_displayName": "Kwácha ya Sámbia",
	"MAD_displayName": "Diriháamu ya Moróoko",
	"NGN_displayName": "Naíira ya Niijéria",
	"ZWD_displayName": "Dóola ya Simbáabwe",
	"SDG_displayName": "Páundi ya Sudáani",
	"MWK_displayName": "Kwáacha ya Maláawi",
	"KMF_displayName": "Faráanga ya Komóoro",
	"SCR_displayName": "Rupía ya Shelishéeli",
	"EGP_displayName": "Páundi ya Mísiri",
	"CVE_displayName": "Esikúudo ya Kepuvéede",
	"LYD_displayName": "Dináari ya Líbia",
	"CAD_displayName": "Dóola ya Kánada",
	"INR_displayName": "Rupía ya Índia",
	"JPY_displayName": "Yéeni ya Japáani",
	"TZS_symbol": "TSh",
	"LRD_displayName": "Dóola ya Libéria",
	"ZAR_displayName": "Ráandi ya Afɨrɨka ya Saame",
	"AOA_displayName": "Kwáanza ya Angóola",
	"TND_displayName": "Dináari ya Tunísia",
	"GHC_displayName": "Séedi ya Gáana",
	"BWP_displayName": "Púula ya Botiswáana",
	"DZD_displayName": "Dináairi ya Alijéria",
	"ZMK_displayName": "Kwácha ya Sámbia (1968–2012)",
	"NAD_displayName": "Dóola ya Namíbia",
	"AED_displayName": "Diriháamu ya Ʉtemi wa Kɨaráabu",
	"ETB_displayName": "Bíiri ya Ʉhabéeshi",
	"MZM_displayName": "Metikáali ya Musumbíiji",
	"BIF_displayName": "Faráanga ya Burúundi",
	"RWF_displayName": "Faráanga ya Rwáanda",
	"STD_displayName": "Dóbura ya SaoTóome na Pirínsipe",
	"SZL_displayName": "Lilengéeni",
	"EUR_displayName": "Yúuro",
	"ERN_displayName": "Nákɨfa ya Eriterea",
	"SAR_displayName": "Riyáali ya Saudía",
	"DJF_displayName": "Faráanga ya Jibóuti",
	"CDF_displayName": "Faráanga ya Kóongo",
	"GBP_displayName": "Páundi ya Ʉɨngɨréesa",
	"CHF_displayName": "Faráaka ya Uswíisi",
	"MUR_displayName": "Rupía ya Moríisi",
	"SOS_displayName": "Shilíingi ya Somália",
	"BHD_displayName": "Dináari ya Baharéeni",
	"XOF_displayName": "Faráanga ya CFA BCEAO",
	"GNS_displayName": "Faráanga ya Gíine",
	"SLL_displayName": "Leóoni",
	"UGX_displayName": "Shilíingi ya Ugáanda",
	"MGA_displayName": "Mpía ya bukini",
	"AUD_displayName": "Dóola ya Ausitereelía",
	"KES_displayName": "Shilíingi ya Kéenya",
	"SHP_displayName": "Páundi ya Mʉtakatíifu Heléena",
	"XAF_displayName": "Faráanga ya CFA BEAC",
	"LSL_displayName": "Lóoti ya Lesóoto",
	"MRO_displayName": "Ungwíiya ya Moritánia",
	"CNY_displayName": "Yúani Renimínibi ya Chíina",
	"GMD_displayName": "Daláasi ya Gámbia"
}
//end v1.x content
);