define(
//begin v1.x content
{
	"USD_displayName": "Dalar Amurka",
	"TZS_displayName": "Sulen Tanzaniya",
	"ZMW_displayName": "Kuɗin Zambiya",
	"MAD_displayName": "Kuɗin Maroko",
	"NGN_displayName": "Naira",
	"ZWD_displayName": "Dalar zimbabuwe",
	"SDG_displayName": "Fam kin Sudan",
	"MWK_displayName": "Kuɗin Malawi",
	"KMF_displayName": "Kuɗin Kwamoras",
	"SCR_displayName": "Kuɗin Saishal",
	"EGP_displayName": "Fam kin Masar",
	"CVE_displayName": "Kuɗin Tsibiran Kap Barde",
	"LYD_displayName": "Kuɗin Libiya",
	"CAD_displayName": "Dalar Kanada",
	"INR_displayName": "Kuɗin Indiya",
	"JPY_displayName": "Kuɗin Japan",
	"LRD_displayName": "Dalar Laberiya",
	"ZAR_displayName": "Kuɗin Afirka Ta Kudu",
	"AOA_displayName": "Kuɗin Angola",
	"TND_displayName": "Kuɗin Tunisiya",
	"GHC_displayName": "Cedi",
	"BWP_displayName": "Kuɗin Baswana",
	"DZD_displayName": "Kuɗin Aljeriya",
	"ZMK_displayName": "Kuɗin Zambiya (1968–2012)",
	"NAD_displayName": "Dalar Namibiya",
	"AED_displayName": "Kuɗin Haɗaɗɗiyar Daular Larabawa",
	"ETB_displayName": "Kuɗin Habasha",
	"MZM_displayName": "Kuɗin Mozambik",
	"BIF_displayName": "Kuɗin Burundi",
	"RWF_displayName": "Kuɗin Ruwanda",
	"STD_displayName": "Kuɗin Sawo Tome da Paransip",
	"SZL_displayName": "Kuɗin Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Kuɗin Eritireya",
	"SAR_displayName": "Riyal",
	"DJF_displayName": "Kuɗin Jibuti",
	"CDF_displayName": "Kuɗin Kongo",
	"GBP_displayName": "Fam kin Ingila",
	"CHF_displayName": "Kuɗin Suwizalan",
	"MUR_displayName": "Kuɗin Moritus",
	"SOS_displayName": "Sulen Somaliya",
	"BHD_displayName": "Kuɗin Baharan",
	"XOF_displayName": "Kuɗin Sefa na Afirka Ta Yamma",
	"GNS_displayName": "Kuɗin Gini",
	"SLL_displayName": "Kuɗin Salewo",
	"UGX_displayName": "Sule Yuganda",
	"MGA_displayName": "Kuɗin Madagaskar",
	"AUD_displayName": "Dalar Ostareliya",
	"KES_displayName": "Sulen Kenya",
	"SHP_displayName": "Fam kin San Helena",
	"XAF_displayName": "Kuɗin Sefa na Afirka Ta Tsakiya",
	"LSL_displayName": "Kuɗin Lesoto",
	"MRO_displayName": "Kuɗin Moritaniya",
	"NGN_symbol": "₦",
	"CNY_displayName": "Kuɗin Caina/Sin",
	"GMD_displayName": "Kuɗin Gambiya"
}
//end v1.x content
);