define(
//begin v1.x content
{
	"USD_displayName": "US Dollari",
	"TZS_displayName": "Tanzanian Shillings",
	"ZMW_displayName": "Zambian Kwachab",
	"MAD_displayName": "Moroccan Dirham",
	"NGN_displayName": "Nigerian Naira",
	"ZWD_displayName": "Zimbabwe Dollari",
	"SDG_displayName": "Sudanese Dinar",
	"MWK_displayName": "Malawian Kwachab",
	"KMF_displayName": "Comorian Franc",
	"SCR_displayName": "Seychelles Rupee",
	"EGP_displayName": "Egytian Ponds",
	"CVE_displayName": "Escudo Caboverdiano",
	"LYD_displayName": "Libyan Dinar",
	"CAD_displayName": "Canadian Dollari",
	"INR_displayName": "Indian Rupee",
	"JPY_displayName": "Japanese Yenni",
	"LRD_displayName": "Liberian Dollar",
	"NAD_symbol": "$",
	"ZAR_displayName": "South African Randi",
	"AOA_displayName": "Angolan Kwanzab",
	"TND_displayName": "Tunisian Dinar",
	"GHC_displayName": "Ghana Cedi",
	"BWP_displayName": "Botswanan Pulab",
	"DZD_displayName": "Algerian Dinar",
	"ZMK_displayName": "Zambian Kwachab (1968–2012)",
	"NAD_displayName": "Namibia Dollari",
	"AED_displayName": "United Arab Emirates Dirham",
	"ETB_displayName": "Ethiopian Birr",
	"MZM_displayName": "Mozambique Metical",
	"BIF_displayName": "Burundi Franc",
	"RWF_displayName": "Rwanda Franci",
	"STD_displayName": "Sao Tome and Principe Dobra",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Eurob",
	"ERN_displayName": "Eritreian Nakfa",
	"SAR_displayName": "Saudi Riyal",
	"DJF_displayName": "Djibouti Franc",
	"CDF_displayName": "Congolese Franc",
	"GBP_displayName": "British Ponds",
	"CHF_displayName": "Swiss Franci",
	"MUR_displayName": "Mauritius Rupeeb",
	"SOS_displayName": "Somali Shillings",
	"BHD_displayName": "Bahrain Dinar",
	"XOF_displayName": "CFA Franc BCEAO",
	"GNS_displayName": "Guinea Franc",
	"SLL_displayName": "Leone",
	"UGX_displayName": "Ugandan Shillings",
	"MGA_displayName": "Malagasy Franc",
	"SDP_displayName": "Sudanese Ponds",
	"AUD_displayName": "Australian Dollari",
	"KES_displayName": "Kenyan Shilling",
	"SHP_displayName": "St Helena Ponds",
	"XAF_displayName": "CFA Franc BEAC",
	"LSL_displayName": "Lesotho Loti",
	"MRO_displayName": "Mauritania Ouguiya",
	"CNY_displayName": "Chinese Yuan Renminbi",
	"GMD_displayName": "Gambia Dalasi"
}
//end v1.x content
);