define(
//begin v1.x content
{
	"COP_displayName": "Kolumbiya pesosi",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Yamayka dollari",
	"AWG_displayName": "Aruba florini",
	"USD_symbol": "US$",
	"LYD_displayName": "Liviya dinori",
	"BMD_displayName": "Bermuda dollari",
	"XCD_displayName": "Sharqiy Karib dollari",
	"SEK_displayName": "Shvetsiya kronasi",
	"CNY_displayName": "Xitoy yuani",
	"IDR_displayName": "Indoneziya rupiyasi",
	"TTD_displayName": "Trinidad va Tobago dollari",
	"TRY_displayName": "Turk lirasi",
	"CNY_symbol": "CN¥",
	"EUR_displayName": "Yevro",
	"BBD_displayName": "Barbados dollari",
	"BSD_displayName": "Bagama dollari",
	"RUB_displayName": "Rus rubli",
	"INR_symbol": "₹",
	"ARS_displayName": "Argentina pesosi",
	"MAD_displayName": "Marokash dirhami",
	"BOB_displayName": "Boliviya bolviani",
	"MXN_displayName": "Meksika pesosi",
	"SRD_displayName": "Surinam dollari",
	"MXN_symbol": "MX$",
	"DZD_displayName": "Jazoir dinori",
	"PEN_displayName": "Peru nuyevo sol",
	"GTQ_displayName": "Gvatemala kvetzali",
	"CAD_displayName": "Kanada dollari",
	"BZD_displayName": "Beliz dollari",
	"CLP_displayName": "Chili pesosi",
	"CUC_displayName": "Kuba Ayirboshlash pesosi",
	"NOK_displayName": "Norvegiya kronasi",
	"DOP_displayName": "Dominikan pesosi",
	"JPY_symbol": "JP¥",
	"UYU_displayName": "Urugvay pesosi",
	"KRW_displayName": "Janubiy Koreya voni",
	"USD_displayName": "AQSH dollari",
	"UZS_displayName": "Oʻzbekiston soʻm",
	"XOF_symbol": "CFA",
	"SAR_displayName": "Saudiya Arabistoni riyoli",
	"XXX_displayName": "Noma'lum valyuta",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Misr funti",
	"KYD_displayName": "Kayman oroli Dollari",
	"GBP_displayName": "Ingliz funt sterlingi",
	"ANG_displayName": "Golland Antil guldeni",
	"TWD_displayName": "Yangi Tayvan dollari",
	"PAB_displayName": "Panama balboasi",
	"PLN_displayName": "Polsha zlotiyi",
	"VEF_displayName": "Venesuela bolivari",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Brazil reali",
	"GYD_displayName": "Gayana dollari",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Gonkong dollari",
	"NIO_displayName": "Nikaragua kordobasi",
	"THB_symbol": "฿",
	"TWD_symbol": "NT$",
	"UZS_symbol": "soʻm",
	"FKP_displayName": "Folklend oroli funti",
	"GBP_symbol": "£",
	"DKK_displayName": "Daniya kronasi",
	"THB_displayName": "Tayland bahti",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yapon yenasi",
	"PYG_displayName": "Paragvay guarani",
	"VND_symbol": "₫",
	"HNL_displayName": "Gonduras lempirasi",
	"CHF_displayName": "Shvetsariya franki",
	"CRC_displayName": "Kosta-Rika koloni",
	"INR_displayName": "Hind rupiyasi",
	"XAF_symbol": "FCFA",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Janubiy Afrika randi",
	"XCD_symbol": "EC$",
	"AUD_displayName": "Avstraliya dollari",
	"XPF_symbol": "CFPF",
	"HTG_displayName": "Gaiti gurdasi",
	"CUP_displayName": "Kuba pesosi"
}
//end v1.x content
);