define(
//begin v1.x content
{
	"field-second-relative+0": "hozir",
	"field-weekday": "Hafta kuni",
	"field-wed-relative+0": "this Wednesday",
	"field-wed-relative+1": "keyingi chorshanba",
	"dateFormatItem-GyMMMEd": "G y MMM d, E",
	"dateFormatItem-MMMEd": "MMM d, E",
	"field-tue-relative+-1": "oʻtgan seshanba",
	"dateFormat-long": "G y MMMM d",
	"field-fri-relative+-1": "oʻtgan juma",
	"field-wed-relative+-1": "oʻtgan chorshanba",
	"dateFormatItem-yyyyQQQ": "G y QQQ",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE, G y MMMM dd",
	"dateFormatItem-yyyyMEd": "GGGGG y-MM-dd, E",
	"field-thu-relative+-1": "oʻtgan payshanba",
	"dateFormatItem-Md": "MM-dd",
	"field-era": "Era",
	"field-year": "Yil",
	"field-hour": "Soat",
	"field-sat-relative+0": "bu shanba",
	"field-sat-relative+1": "keyingi shanba",
	"field-day-relative+0": "bugun",
	"field-thu-relative+0": "bu payshanba",
	"field-day-relative+1": "ertaga",
	"field-thu-relative+1": "keyingi payshanba",
	"dateFormatItem-GyMMMd": "G y MMM d",
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-yyyyMMMEd": "G y MMM d, E",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "G y MMM",
	"dateFormatItem-yyyyMMMd": "G y MMM d",
	"field-sun-relative+0": "bu yakshanba",
	"field-sun-relative+1": "keyingi yakshanba",
	"field-minute": "Daqiqa",
	"field-dayperiod": "Kun vaqti",
	"dateFormatItem-d": "d",
	"field-day-relative+-1": "kecha",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "bu juma",
	"field-fri-relative+1": "keyingi juma",
	"field-day": "Kun",
	"field-zone": "Mintaqa",
	"dateFormatItem-y": "G y",
	"field-year-relative+-1": "oʻtgan yil",
	"field-month-relative+-1": "oʻtgan oy",
	"dateFormatItem-yyyyMd": "GGGGG y-MM-dd",
	"field-month": "Oy",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "bu seshanba",
	"field-tue-relative+1": "keyingi seshanba",
	"field-mon-relative+0": "bu dushanba",
	"field-mon-relative+1": "keyingi dushanba",
	"dateFormat-short": "GGGGG y/MM/dd",
	"field-second": "Soniya",
	"field-sat-relative+-1": "oʻtgan shanba",
	"field-sun-relative+-1": "oʻtgan yakshanba",
	"field-month-relative+0": "bu oy",
	"field-month-relative+1": "keyingi oy",
	"dateFormatItem-Ed": "d, E",
	"field-week": "Hafta",
	"dateFormat-medium": "G y MMM d",
	"field-year-relative+0": "bu yil",
	"field-week-relative+-1": "oʻtgan hafta",
	"dateFormatItem-yyyyM": "GGGGG y-MM",
	"field-year-relative+1": "keyingi yil",
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-GyMMM": "G y MMM",
	"field-mon-relative+-1": "oʻtgan dushanba",
	"dateFormatItem-yyyy": "G y",
	"field-week-relative+0": "bu hafta",
	"field-week-relative+1": "keyingi hafta"
}
//end v1.x content
);