({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray. 
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "[ßälice blüe~~~~~de]",
antiquewhite: "[ßäntiqüe white~~~~~~~~de]",
aqua: "[ßäqüä~~de]",
aquamarine: "[ßäqüämärine~~~~~de]",
azure: "[ßäzüre~~~de]",
beige: "[ßbeige~~~de]",
bisque: "[ßbisqüe~~~~de]",
black: "[ßbläck~~~de]",
blanchedalmond: "[ßblänched älmönd~~~~~~~~~de]",
blue: "[ßblüe~~de]",
blueviolet: "[ßblüe-viölet~~~~~~de]",
brown: "[ßbröwn~~~de]",
burlywood: "[ßbürlywööd~~~~~de]",
cadetblue: "[ßcädet blüe~~~~~de]",
chartreuse: "[ßchärtreüse~~~~~de]",
chocolate: "[ßchöcöläte~~~~~de]",
coral: "[ßcöräl~~~de]",
cornflowerblue: "[ßcörnflöwer blüe~~~~~~~~~de]",
cornsilk: "[ßcörnsilk~~~~~de]",
crimson: "[ßcrimsön~~~~~de]",
cyan: "[ßcyän~~de]",
darkblue: "[ßdärk blüe~~~~~de]",
darkcyan: "[ßdärk cyän~~~~~de]",
darkgoldenrod: "[ßdärk göldenröd~~~~~~~~~de]",
darkgray: "[ßdärk gräy~~~~~de]",
darkgreen: "[ßdärk green~~~~~de]",
darkgrey: "[ßdärk gräy~~~~~de]", // same as darkgray
darkkhaki: "[ßdärk khäki~~~~~de]",
darkmagenta: "[ßdärk mägentä~~~~~~~de]",
darkolivegreen: "[ßdärk ölive green~~~~~~~~~~de]",
darkorange: "[ßdärk öränge~~~~~~de]",
darkorchid: "[ßdärk örchid~~~~~~de]",
darkred: "[ßdärk red~~~~~de]",
darksalmon: "[ßdärk sälmön~~~~~~de]",
darkseagreen: "[ßdärk seä green~~~~~~~~~de]",
darkslateblue: "[ßdärk släte blüe~~~~~~~~~de]",
darkslategray: "[ßdärk släte gräy~~~~~~~~~de]",
darkslategrey: "[ßdärk släte gräy~~~~~~~~~de]", // same as darkslategray
darkturquoise: "[ßdärk türqüöise~~~~~~~~~de]",
darkviolet: "[ßdärk viölet~~~~~~de]",
deeppink: "[ßdeep pink~~~~~de]",
deepskyblue: "[ßdeep sky blüe~~~~~~~~de]",
dimgray: "[ßdim gräy~~~~~de]",
dimgrey: "[ßdim gräy~~~~~de]", // same as dimgray
dodgerblue: "[ßdödger blüe~~~~~~de]",
firebrick: "[ßfire brick~~~~~de]",
floralwhite: "[ßflöräl white~~~~~~~de]",
forestgreen: "[ßförest green~~~~~~~de]",
fuchsia: "[ßfüchsiä~~~~~de]",
gainsboro: "[ßgäinsbörö~~~~~de]",
ghostwhite: "[ßghöst white~~~~~~de]",
gold: "[ßgöld~~de]",
goldenrod: "[ßgöldenröd~~~~~de]",
gray: "[ßgräy~~de]",
green: "[ßgreen~~~de]",
greenyellow: "[ßgreen-yellöw~~~~~~~de]",
grey: "[ßgräy~~de]", // same as gray
honeydew: "[ßhöneydew~~~~~de]",
hotpink: "[ßhöt pink~~~~~de]",
indianred: "[ßindiän red~~~~~de]",
indigo: "[ßindigö~~~~de]",
ivory: "[ßivöry~~~de]",
khaki: "[ßkhäki~~~de]",
lavender: "[ßlävender~~~~~de]",
lavenderblush: "[ßlävender blüsh~~~~~~~~~de]",
lawngreen: "[ßläwn green~~~~~de]",
lemonchiffon: "[ßlemön chiffön~~~~~~~~de]",
lightblue: "[ßlight blüe~~~~~de]",
lightcoral: "[ßlight cöräl~~~~~~de]",
lightcyan: "[ßlight cyän~~~~~de]",
lightgoldenrodyellow: "[ßlight göldenröd yellöw~~~~~~~~~~~~~de]",
lightgray: "[ßlight gräy~~~~~de]",
lightgreen: "[ßlight green~~~~~~de]",
lightgrey: "[ßlight gräy~~~~~de]", // same as lightgray
lightpink: "[ßlight pink~~~~~de]",
lightsalmon: "[ßlight sälmön~~~~~~~de]",
lightseagreen: "[ßlight seä green~~~~~~~~~de]",
lightskyblue: "[ßlight sky blüe~~~~~~~~~de]",
lightslategray: "[ßlight släte gräy~~~~~~~~~~de]",
lightslategrey: "[ßlight släte gräy~~~~~~~~~~de]", // same as lightslategray
lightsteelblue: "[ßlight steel blüe~~~~~~~~~~de]",
lightyellow: "[ßlight yellöw~~~~~~~de]",
lime: "[ßlime~~de]",
limegreen: "[ßlime green~~~~~de]",
linen: "[ßlinen~~~de]",
magenta: "[ßmägentä~~~~~de]",
maroon: "[ßmäröön~~~~de]",
mediumaquamarine: "[ßmediüm äqüämärine~~~~~~~~~~de]",
mediumblue: "[ßmediüm blüe~~~~~~de]",
mediumorchid: "[ßmediüm örchid~~~~~~~~de]",
mediumpurple: "[ßmediüm pürple~~~~~~~~de]",
mediumseagreen: "[ßmediüm seä green~~~~~~~~~~de]",
mediumslateblue: "[ßmediüm släte blüe~~~~~~~~~~de]",
mediumspringgreen: "[ßmediüm spring green~~~~~~~~~~~de]",
mediumturquoise: "[ßmediüm türqüöise~~~~~~~~~~de]",
mediumvioletred: "[ßmediüm viölet-red~~~~~~~~~~de]",
midnightblue: "[ßmidnight blüe~~~~~~~~de]",
mintcream: "[ßmint creäm~~~~~de]",
mistyrose: "[ßmisty röse~~~~~de]",
moccasin: "[ßmöccäsin~~~~~de]",
navajowhite: "[ßnäväjö white~~~~~~~de]",
navy: "[ßnävy~~de]",
oldlace: "[ßöld läce~~~~~de]",
olive: "[ßölive~~~de]",
olivedrab: "[ßölive dräb~~~~~de]",
orange: "[ßöränge~~~~de]",
orangered: "[ßöränge red~~~~~de]",
orchid: "[ßörchid~~~~de]",
palegoldenrod: "[ßpäle göldenröd~~~~~~~~~de]",
palegreen: "[ßpäle green~~~~~de]",
paleturquoise: "[ßpäle türqüöise~~~~~~~~~de]",
palevioletred: "[ßpäle viölet-red~~~~~~~~~de]",
papayawhip: "[ßpäpäyä whip~~~~~~de]",
peachpuff: "[ßpeäch püff~~~~~de]",
peru: "[ßperü~~de]",
pink: "[ßpink~~de]",
plum: "[ßplüm~~de]",
powderblue: "[ßpöwder blüe~~~~~~de]",
purple: "[ßpürple~~~~de]",
red: "[ßred~de]",
rosybrown: "[ßrösy bröwn~~~~~de]",
royalblue: "[ßröyäl blüe~~~~~de]",
saddlebrown: "[ßsäddle bröwn~~~~~~~de]",
salmon: "[ßsälmön~~~~de]",
sandybrown: "[ßsändy bröwn~~~~~~de]",
seagreen: "[ßseä green~~~~~de]",
seashell: "[ßseäshell~~~~~de]",
sienna: "[ßsiennä~~~~de]",
silver: "[ßsilver~~~~de]",
skyblue: "[ßsky blüe~~~~~de]",
slateblue: "[ßsläte blüe~~~~~de]",
slategray: "[ßsläte gräy~~~~~de]",
slategrey: "[ßsläte gräy~~~~~de]", // same as slategray
snow: "[ßsnöw~~de]",
springgreen: "[ßspring green~~~~~~~de]",
steelblue: "[ßsteel blüe~~~~~de]",
tan: "[ßtän~de]",
teal: "[ßteäl~~de]",
thistle: "[ßthistle~~~~~de]",
tomato: "[ßtömätö~~~~de]",
turquoise: "[ßtürqüöise~~~~~de]",
violet: "[ßviölet~~~~de]",
wheat: "[ßwheät~~~de]",
white: "[ßwhite~~~de]",
whitesmoke: "[ßwhite smöke~~~~~~de]",
yellow: "[ßyellöw~~~~de]",
yellowgreen: "[ßyellöw green~~~~~~~de]"
})
