define(
//begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"dateFormatItem-yyyyMMMEd": "GGGGy年M月d日(E)",
	"dateFormatItem-yQ": "y/Q",
	"dayPeriods-format-wide-pm": "午後",
	"dateFormatItem-GGGGyMd": "GGGGy年M月d日",
	"eraNames": [
		"仏暦"
	],
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateFormatItem-hms": "aK:mm:ss",
	"dateFormatItem-yQQQ": "yQQQ",
	"dateFormatItem-MMdd": "MM/dd",
	"dateFormatItem-MMM": "M月",
	"dateFormatItem-Gy": "Gy年",
	"dayPeriods-format-wide-am": "午前",
	"dateFormatItem-y": "GGGGy年",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"dateFormatItem-yyyy": "GGGGy年",
	"dateFormatItem-Ed": "d日(E)",
	"dateFormatItem-yMMM": "y年M月",
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-yyyyMM": "Gy/MM",
	"dateFormat-long": "GGGGy年M月d日",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "Gy/MM/dd",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "y/M/d",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyMd": "Gy/M/d",
	"dateFormatItem-yyyyMMMd": "GGGGy年M月d日",
	"dateFormatItem-yyyyMEd": "Gy/M/d(E)",
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H時",
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-M": "M月",
	"dateFormatItem-yMMMd": "y年M月d日",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-hm": "aK:mm",
	"dateFormat-short": "Gy/MM/dd",
	"dateFormatItem-yMMMEd": "y年M月d日(E)",
	"dateFormat-full": "GGGGy年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyQ": "Gy/Q",
	"dateFormatItem-yMEd": "y/M/d(E)",
	"months-format-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"dateFormatItem-yyyyMMM": "GGGGy年M月",
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dateFormatItem-h": "aK時"
}
//end v1.x content
);