define(
//begin v1.x content
{
	"dateFormat-medium": "U年MMMd日",
	"dateFormatItem-yMd": "U年M月d日",
	"dateFormatItem-MMMEd": "MMMd日(E)",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-yMEd": "U年M月d日(E)",
	"months-format-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"十一",
		"十二"
	],
	"dateFormatItem-y": "U年",
	"dateFormatItem-yMMMd": "U年MMMd日",
	"dateFormatItem-Md": "M/d",
	"months-standAlone-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"十一",
		"十二"
	],
	"dateFormatItem-M": "MMM",
	"dateFormatItem-yQQQ": "U/QQQ",
	"dateFormatItem-MMMEEEEd": "MMMd日EEEE",
	"dateFormat-long": "U年MMMd日",
	"dateFormatItem-yMMMEEEEd": "U年MMMd日EEEE",
	"dateFormatItem-EEEEd": "d日EEEE",
	"dateFormatItem-yMEEEEd": "U年M月d日EEEE",
	"dateFormatItem-yQQQQ": "UQQQQ",
	"dateFormat-short": "U-M-d",
	"dateFormatItem-yMMMEd": "U年MMMd日(E)",
	"months-format-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"十二月"
	],
	"dateFormatItem-d": "d日",
	"dateFormatItem-yM": "U年M月",
	"dateFormatItem-yMMM": "U年MMM",
	"dateFormat-full": "U年MMMd日EEEE",
	"dateFormatItem-MMMd": "MMMd日",
	"dateFormatItem-Ed": "d日(E)"
}
//end v1.x content
);