define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "U年MMMd日(E)",
	"dateFormatItem-MMMEd": "MMMd日(E)",
	"dateFormatItem-hms": "aK:mm:ss",
	"months-standAlone-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"十一",
		"十二"
	],
	"dateFormatItem-Gy": "U年",
	"dateFormatItem-y": "U年",
	"dateFormatItem-yyyy": "U年",
	"dateFormatItem-yyyyMMMEEEEd": "U年MMMd日EEEE",
	"dateFormatItem-EEEEd": "d日EEEE",
	"dateFormatItem-Ed": "d日(E)",
	"dateFormatItem-GyMMMd": "U年MMMd日",
	"dateFormat-long": "U年MMMd日",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-MMMEEEEd": "MMMd日EEEE",
	"dateFormat-medium": "U年MMMd日",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "U年M月d日",
	"dateFormatItem-yyyyQQQQ": "UQQQQ",
	"dateFormatItem-GyMMMEEEEd": "U年MMMd日EEEE",
	"dateFormatItem-yyyyMd": "U年M月d日",
	"dateFormatItem-yyyyMMMd": "U年MMMd日",
	"dateFormatItem-yyyyMEd": "U年M月d日(E)",
	"dateFormatItem-yyyyMEEEEd": "U年M月d日EEEE",
	"dateFormatItem-MMMd": "MMMd日",
	"dateFormatItem-H": "H時",
	"dateFormatItem-M": "MMM",
	"dateFormatItem-GyMMMEd": "U年MMMd日(E)",
	"dateFormatItem-GyMMM": "U年MMM",
	"dateFormatItem-MEEEEd": "M/dEEEE",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-yyyyQQQ": "U/QQQ",
	"months-format-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"十一",
		"十二"
	],
	"dateFormatItem-hm": "aK:mm",
	"dateFormat-short": "U-M-d",
	"dateFormatItem-yyyyM": "U年M月",
	"dateFormat-full": "U年MMMd日EEEE",
	"dateFormatItem-Md": "M/d",
	"months-format-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"十二月"
	],
	"dateFormatItem-yyyyMMM": "U年MMM",
	"dateFormatItem-d": "d日",
	"dateFormatItem-h": "aK時"
}
//end v1.x content
);