// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"アンドラ ペセタ",
	AED_displayName:"UAE ディルハム",
	AFA_displayName:"アフガニー (1927-2002)",
	AFN_displayName:"アフガニー",
	AFN_symbol:"Af",
	ALL_displayName:"アルバニア レク",
	AMD_displayName:"アルメニア ドラム",
	ANG_displayName:"オランダ領アンティル ギルダー",
	AOA_displayName:"クワンザ",
	AOK_displayName:"クワンザ (1977-1990)",
	AON_displayName:"アンゴラ 新クワンザ (1990-2000)",
	AOR_displayName:"アンゴラ 旧クワンザ (1995-1999)",
	ARA_displayName:"アルゼンチン アゥストラール",
	ARP_displayName:"アルゼンチン ペソ (1983-1985)",
	ARS_displayName:"アルゼンチン ペソ",
	ATS_displayName:"オーストリア シリング",
	AUD_displayName:"オーストラリア ドル",
	AWG_displayName:"アルバ ギルダー",
	AZM_displayName:"アゼルバイジャン マナト (1993-2006)",
	AZN_displayName:"アゼルバイジャン マナト",
	BAD_displayName:"ボスニア ディナール",
	BAM_displayName:"ボスニア マルク (BAM)",
	BBD_displayName:"バルバドス ドル",
	BDT_displayName:"バングラデシュ タカ",
	BEC_displayName:"ベルギー フラン (BEC)",
	BEF_displayName:"ベルギー フラン",
	BEL_displayName:"ベルギー フラン (BEL)",
	BGL_displayName:"ブルガリア レフ",
	BGN_displayName:"ブルガリア 新レフ",
	BHD_displayName:"バーレーン ディナール",
	BIF_displayName:"ブルンジ フラン",
	BMD_displayName:"バミューダ ドル",
	BND_displayName:"ブルネイ ドル",
	BOB_displayName:"ボリビアーノ",
	BOP_displayName:"ボリビア ペソ",
	BOV_displayName:"ボリビア Mvdol",
	BRB_displayName:"ブラジル 新クルゼイロ (1967-1986)",
	BRC_displayName:"ブラジル クルゼイロ",
	BRE_displayName:"ブラジル クルゼイロ (1990-1993)",
	BRL_displayName:"ブラジル レアル",
	BRN_displayName:"ブラジル 新クルゼイロ",
	BRR_displayName:"ブラジル クルゼイロ レアル",
	BSD_displayName:"バハマ ドル",
	BTN_displayName:"ブータン ニュルタム",
	BUK_displayName:"ビルマ チャット",
	BWP_displayName:"ボツワナ プラ",
	BYB_displayName:"ベラルーシ ルーブル (1994-1999)",
	BYR_displayName:"ベラルーシ ルーブル",
	BZD_displayName:"ベリーズ ドル",
	CAD_displayName:"カナダ ドル",
	CDF_displayName:"コンゴ フラン",
	CHE_displayName:"WIR ユーロ",
	CHF_displayName:"スイス フラン",
	CHW_displayName:"WIR フラン",
	CLF_displayName:"チリ ウニダ デ フォメント",
	CLP_displayName:"チリ ペソ",
	CNY_displayName:"中国人民元",
	CNY_symbol:"元",
	COP_displayName:"コロンビア ペソ",
	COU_displayName:"レアル (UVR)",
	CRC_displayName:"コスタリカ コロン",
	CSD_displayName:"セルビアン ディナール",
	CSK_displayName:"チェコスロバキア コルナ",
	CUP_displayName:"キューバ ペソ",
	CVE_displayName:"カーボベルデ エスクード",
	CYP_displayName:"キプロス ポンド",
	CZK_displayName:"チェコ コルナ",
	DDM_displayName:"東ドイツ マルク",
	DEM_displayName:"ドイツ マルク",
	DJF_displayName:"ジブチ フラン",
	DKK_displayName:"デンマーク クローネ",
	DOP_displayName:"ドミニカ ペソ",
	DZD_displayName:"アルジェリア ディナール",
	ECS_displayName:"エクアドル スクレ",
	ECV_displayName:"エクアドル UVC",
	EEK_displayName:"エストニア クルーン",
	EGP_displayName:"エジプト ポンド",
	EQE_displayName:"エクウェレ",
	ERN_displayName:"エリトリア ナクファ",
	ESP_displayName:"スペイン ペセタ",
	ETB_displayName:"エチオピア ブル",
	EUR_displayName:"ユーロ",
	FIM_displayName:"フィンランド マルカ",
	FJD_displayName:"フィジー諸島 ドル",
	FKP_displayName:"フォークランド（マルビナス）諸島 ポンド",
	FRF_displayName:"フランス フラン",
	GBP_displayName:"英国ポンド",
	GEK_displayName:"グルジア クーポン ラリ",
	GEL_displayName:"グルジア ラリ",
	GHC_displayName:"ガーナ セディ (1979-2007)",
	GHS_displayName:"ガーナ セディ",
	GIP_displayName:"ジブラルタル ポンド",
	GMD_displayName:"ガンビア ダラシ",
	GNF_displayName:"ギニア フラン",
	GNS_displayName:"ギニア シリー",
	GQE_displayName:"赤道ギニア ギニー",
	GRD_displayName:"ギリシャ ドラクマ",
	GTQ_displayName:"グアテマラ ケツァル",
	GWE_displayName:"ポルトガル領ギニア エスクード",
	GWP_displayName:"ギニアビサウ ペソ",
	GYD_displayName:"ガイアナ ドル",
	HKD_displayName:"香港ドル",
	HNL_displayName:"ホンジュラス レンピラ",
	HRD_displayName:"クロアチア ディナール",
	HRK_displayName:"クロアチア クーナ",
	HTG_displayName:"ハイチ グールド",
	HUF_displayName:"ハンガリー フォリント",
	IDR_displayName:"インドネシア ルピア",
	IEP_displayName:"アイリッシュ ポンド",
	ILP_displayName:"イスラエル ポンド",
	ILS_displayName:"イスラエル新シェケル",
	INR_displayName:"インド ルピー",
	INR_symbol:"INR",
	IQD_displayName:"イラク ディナール",
	IRR_displayName:"イラン リアル",
	ISK_displayName:"アイスランド クローナ",
	ITL_displayName:"イタリア リラ",
	JMD_displayName:"ジャマイカ ドル",
	JOD_displayName:"ヨルダン ディナール",
	JPY_displayName:"日本円",
	JPY_symbol:"￥",
	KES_displayName:"ケニア シリング",
	KGS_displayName:"キルギスタン ソム",
	KHR_displayName:"カンボジア リエル",
	KMF_displayName:"コモロ フラン",
	KPW_displayName:"北朝鮮 ウォン",
	KRW_displayName:"韓国 ウォン",
	KRW_symbol:"￦",
	KWD_displayName:"クウェート ディナール",
	KYD_displayName:"ケイマン諸島 ドル",
	KZT_displayName:"カザフスタン テンゲ",
	LAK_displayName:"ラオス キープ",
	LBP_displayName:"レバノン ポンド",
	LKR_displayName:"スリランカ ルピー",
	LRD_displayName:"リベリア ドル",
	LSL_displayName:"レソト ロティ",
	LSM_displayName:"マロティ",
	LTL_displayName:"リトアニア リタス",
	LTT_displayName:"リトアニア タロナ",
	LUF_displayName:"ルクセンブルグ フラン",
	LVL_displayName:"ラトビア ラッツ",
	LVR_displayName:"ラトビア ルーブル",
	LYD_displayName:"リビア ディナール",
	MAD_displayName:"モロッコ ディルハム",
	MAF_displayName:"モロッコ フラン",
	MDL_displayName:"モルドバ レイ",
	MGA_displayName:"マダガスカル アリアリ",
	MGF_displayName:"マダガスカル フラン",
	MKD_displayName:"マケドニア デナル",
	MLF_displayName:"マリ フラン",
	MMK_displayName:"ミャンマー チャット",
	MNT_displayName:"モンゴル トグログ",
	MOP_displayName:"マカオ パタカ",
	MRO_displayName:"モーリタニア ウギア",
	MTL_displayName:"マルタ リラ",
	MTP_displayName:"マルタ ポンド",
	MUR_displayName:"モーリシャス ルピー",
	MVR_displayName:"モルディブ諸島 ルフィア",
	MWK_displayName:"マラウィ クワチャ",
	MXN_displayName:"メキシコ ペソ",
	MXP_displayName:"メキシコ ペソ (1861-1992)",
	MXV_displayName:"メキシコ UDI",
	MYR_displayName:"マレーシア リンギット",
	MZE_displayName:"モザンピーク エスクード",
	MZM_displayName:"モザンピーク メティカル",
	NAD_displayName:"ナミビア ドル",
	NGN_displayName:"ナイジェリア ナイラ",
	NIC_displayName:"ニカラグア コルドバ",
	NIO_displayName:"ニカラグア コルドバ オロ",
	NLG_displayName:"オランダ ギルダー",
	NOK_displayName:"ノルウェー クローネ",
	NPR_displayName:"ネパール ルピー",
	NZD_displayName:"ニュージーランド ドル",
	OMR_displayName:"オマーン リアル",
	PAB_displayName:"パナマ バルボア",
	PEI_displayName:"ペルー インティ",
	PEN_displayName:"ペルー 新ソル",
	PES_displayName:"ペルー ソル",
	PGK_displayName:"パプアニューギニア キナ",
	PHP_displayName:"フィリピン ペソ",
	PKR_displayName:"パキスタン ルピー",
	PLN_displayName:"ポーランド ズウォティ",
	PLZ_displayName:"ポーランド ズウォティ (1950-1995)",
	PTE_displayName:"ポルトガル エスクード",
	PYG_displayName:"パラグアイ グアラニ",
	QAR_displayName:"カタール リアル",
	RHD_displayName:"ローデシア ドル",
	ROL_displayName:"ルーマニア 旧レイ",
	RON_displayName:"ルーマニア レイ",
	RUB_displayName:"ロシア ルーブル",
	RUR_displayName:"ロシア ルーブル (1991-1998)",
	RWF_displayName:"ルワンダ フラン",
	SAR_displayName:"サウジ リヤル",
	SBD_displayName:"ソロモン諸島 ドル",
	SCR_displayName:"セイシェル ルピー",
	SDD_displayName:"スーダン ディナール",
	SDG_displayName:"スーダン ポンド",
	SDP_displayName:"旧スーダン ポンド",
	SEK_displayName:"スウェーデン クローナ",
	SGD_displayName:"シンガポール ドル",
	SHP_displayName:"セントヘレナ島 ポンド",
	SIT_displayName:"スロベニア トラール",
	SKK_displayName:"スロバキア コルナ",
	SLL_displayName:"シエラレオネ レオン",
	SOS_displayName:"ソマリア シリング",
	SRG_displayName:"スリナム ギルダー",
	STD_displayName:"サントメ・プリンシペ ドブラ",
	SUR_displayName:"ソ連 ルーブル",
	SVC_displayName:"エルサルバドル コロン",
	SYP_displayName:"シリア ポンド",
	SZL_displayName:"スワジランド リランゲニ",
	THB_displayName:"タイ バーツ",
	TJR_displayName:"タジキスタン ルーブル",
	TJS_displayName:"タジキスタン ソモニ",
	TMM_displayName:"トルクメニスタン マナト",
	TND_displayName:"チュニジア ディナール",
	TOP_displayName:"トンガ パ・アンガ",
	TPE_displayName:"ティモール エスクード",
	TRL_displayName:"トルコ リラ",
	TRY_displayName:"新トルコリラ",
	TTD_displayName:"トリニダードトバゴ ドル",
	TWD_displayName:"新台湾ドル",
	TZS_displayName:"タンザニア シリング",
	UAH_displayName:"ウクライナ グリブナ",
	UAK_displayName:"ウクライナ カルボバネツ",
	UGS_displayName:"ウガンダ シリング (1966-1987)",
	UGX_displayName:"ウガンダ シリング",
	USD_displayName:"米ドル",
	USN_displayName:"米ドル (翌日)",
	USS_displayName:"米ドル (当日)",
	UYP_displayName:"ウルグアイ ペソ (1975-1993)",
	UYU_displayName:"ウルグアイ ペソ",
	UZS_displayName:"ウズベキスタン スム",
	VEB_displayName:"ベネズエラ ボリバル",
	VEF_displayName:"ベネズエラ ボリバルフエルテ",
	VND_displayName:"ベトナム ドン",
	VND_symbol:"đ",
	VUV_displayName:"バヌアツ バツ",
	WST_displayName:"西サモア タラ",
	XAF_displayName:"CFA フラン BEAC",
	XAU_displayName:"金",
	XBA_displayName:"ヨーロッパ混合単位 (EURCO)",
	XBB_displayName:"ヨーロッパ通貨単位 (EMU-6)",
	XBC_displayName:"ヨーロッパ勘定単位 (EUA-9)",
	XBD_displayName:"ヨーロッパ勘定単位 (EUA-17)",
	XCD_displayName:"東カリブ ドル",
	XCD_symbol:"EC$",
	XDR_displayName:"特別引き出し権",
	XEU_displayName:"ヨーロッパ通貨単位",
	XFO_displayName:"フランス金フラン",
	XFU_displayName:"フランス UIC フラン",
	XOF_displayName:"CFA フラン BCEAO",
	XPF_displayName:"CFP フラン",
	YDD_displayName:"イエメン ディナール",
	YER_displayName:"イエメン リアル",
	YUD_displayName:"ユーゴスラビア ディナール",
	YUM_displayName:"ユーゴスラビア スーパー ディナール",
	YUN_displayName:"ユーゴスラビア 新ディナール (YUN)",
	ZAL_displayName:"南アフリカ ランド (ZAL)",
	ZAR_displayName:"南アフリカ ランド",
	ZRN_displayName:"ザイール 新ザイール",
	ZRZ_displayName:"ザイール ザイール",
	ZWD_displayName:"ジンバブエ ドル"
})
                 