define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "Gy年M月d日(E)",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "aK:mm:ss",
	"dateFormatItem-MMM": "M月",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "Gy年",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "Gy年",
	"dateFormatItem-yyyy": "Gy年",
	"dateFormatItem-yyyyMMMEEEEd": "Gy年M月d日EEEE",
	"dateFormatItem-EEEEd": "d日EEEE",
	"dateFormatItem-Ed": "d日(E)",
	"dateFormatItem-GyMMMd": "Gy年M月d日",
	"dateFormat-long": "Gy年M月d日",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-MMMEEEEd": "M月d日EEEE",
	"dateFormat-medium": "Gy/MM/dd",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "GyQQQQ",
	"dateFormatItem-GyMMMEEEEd": "Gy年M月d日EEEE",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "Gy/M/d",
	"dateFormatItem-yyyyMMMd": "Gy年M月d日",
	"dateFormatItem-yyyyMEd": "Gy/M/d(E)",
	"dateFormatItem-yyyyMEEEEd": "Gy/M/dEEEE",
	"dateFormatItem-MMMd": "M月d日",
	"dateFormatItem-H": "H時",
	"dateFormatItem-M": "M月",
	"dateFormatItem-GyMMMEd": "Gy年M月d日(E)",
	"dateFormatItem-GyMMM": "Gy年M月",
	"dateFormatItem-MEEEEd": "M/dEEEE",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-yyyyQQQ": "Gy/QQQ",
	"dateFormatItem-hm": "aK:mm",
	"dateFormat-short": "Gy/MM/dd",
	"dateFormatItem-yyyyM": "Gy/M",
	"dateFormat-full": "Gy年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yyyyMMM": "Gy年M月",
	"dateFormatItem-d": "d日",
	"dateFormatItem-h": "aK時"
}
//end v1.x content
);