// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
	'months-format-abbr':["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
	'months-format-wide':["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
	'months-standAlone-abbr':["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'days-format-abbr':["日","月","火","水","木","金","土"],
	'days-format-wide':["日曜日","月曜日","火曜日","水曜日","木曜日","金曜日","土曜日"],
	'days-standAlone-narrow':["日","月","火","水","木","金","土"],
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-wide':["第1四半期","第2四半期","第3四半期","第4四半期"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'am':"午前",
	'pm':"午後",
	'eraNames':["紀元前","西暦"],
	'eraAbbr':["紀元前","西暦"],
	'dateFormat-full': "yyyy年M月d日EEEE",
	'dateFormat-long': "yyyy年M月d日",
	'dateFormat-medium': "yyyy/MM/dd",
	'dateFormat-short': "yy/MM/dd",
	'timeFormat-full': "H時mm分ss秒v",
	'timeFormat-long': "HH:mm:ssz",
	'timeFormat-medium': "H:mm:ss",
	'timeFormat-short': "H:mm",
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeAvailableFormats':["d日(EEE)","GGGGy年M月d日","H時","H:mm","L","M/d(E)","LLL","M月d日(E)","M月d日(E)","M月d日","M月d日","MM/dd","M/d","d日","mm:ss","mm:ss","y","y/M","y/M/d(EEE)","y年M月","y年M月d日(EEE)","y年M月","y/Q","yyyyQQQ","y年M月","yy/Q","y年","yyyy/MM"],
        'field-era':"時代",
        'field-year':"年",
        'field-month':"月",
        'field-week':"週",
        'field-day':"日",
        'field-weekday':"曜日",
        'field-dayperiod':"午前/午後",
        'field-hour':"時",
        'field-minute':"分",
        'field-second':"秒",
        'field-zone':"タイムゾーン"
})
                        