define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "Gy年M月d日(E)",
	"dayPeriods-format-wide-pm": "午後",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateFormatItem-hms": "aK:mm:ss",
	"dateFormatItem-MMM": "M月",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-Gy": "Gy年",
	"dayPeriods-format-wide-am": "午前",
	"dateFormatItem-y": "Gy年",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"dateFormatItem-yyyy": "Gy年",
	"months-standAlone-abbr": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"dateFormatItem-Ed": "d日(E)",
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"eraAbbr": [
		"AH"
	],
	"dateFormatItem-GyMMMd": "Gy年M月d日",
	"dateFormat-long": "Gy年M月d日",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "Gy/MM/dd",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyyyQQQQ": "GyQQQQ",
	"months-standAlone-wide": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"dateFormatItem-yyyyMd": "Gy/M/d",
	"dateFormatItem-yyyyMMMd": "Gy年M月d日",
	"dateFormatItem-yyyyMEd": "Gy/M/d(E)",
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H時",
	"quarters-format-abbr": [
		"1Q",
		"2Q",
		"3Q",
		"4Q"
	],
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-M": "M月",
	"dateFormatItem-GyMMMEd": "Gy年M月d日(E)",
	"dateFormatItem-GyMMM": "Gy年M月",
	"dateFormatItem-yyyyQQQ": "Gy/QQQ",
	"dateFormatItem-MEd": "M/d(E)",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"days-standAlone-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-hm": "aK:mm",
	"dateFormat-short": "Gy/MM/dd",
	"dateFormatItem-yyyyM": "Gy/M",
	"dateFormat-full": "Gy年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"months-format-wide": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"days-format-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-yyyyMMM": "Gy年M月",
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dateFormatItem-h": "aK時"
}
//end v1.x content
);