define(
//begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"dateFormatItem-yQ": "y/Q",
	"dayPeriods-format-wide-pm": "午後",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateFormatItem-hms": "aK:mm:ss",
	"dateFormatItem-yQQQ": "yQQQ",
	"dateFormatItem-MMM": "M月",
	"dayPeriods-format-wide-am": "午前",
	"dateFormatItem-y": "y年",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"months-standAlone-abbr": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"dateFormatItem-Ed": "d日(E)",
	"dateFormatItem-yMMM": "y年M月",
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormat-long": "y年M月d日",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "yyyy/MM/dd",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "y/M/d",
	"months-standAlone-wide": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H時",
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-M": "M月",
	"dateFormatItem-yMMMd": "y年M月d日",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-hm": "aK:mm",
	"dateFormat-short": "yyyy/MM/dd",
	"dateFormatItem-yMMMEd": "y年M月d日(E)",
	"dateFormat-full": "y年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "y/M/d(E)",
	"months-format-wide": [
		"ムハッラム",
		"サフアル",
		"ラビー・ウル・アウワル",
		"ラビー・ウッ・サーニー",
		"ジュマーダル・アウワル",
		"ジュマーダッサーニー",
		"ラジャブ",
		"シャアバーン",
		"ラマダーン",
		"シャウワール",
		"ズル・カイダ",
		"ズル・ヒッジャ"
	],
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dateFormatItem-h": "aK時"
}
//end v1.x content
);