define(
//begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"dateFormatItem-yQ": "y/Q",
	"dayPeriods-format-wide-pm": "午後",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateFormatItem-hms": "aK:mm:ss",
	"dateFormatItem-yQQQ": "yQQQ",
	"dateFormatItem-MMM": "M月",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dayPeriods-format-wide-am": "午前",
	"dateFormatItem-y": "y年",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"months-standAlone-abbr": [
		"ファルヴァルディーン",
		"オルディーベヘシュト",
		"ホルダード",
		"ティール",
		"モルダード",
		"シャハリーヴァル",
		"メフル",
		"アーバーン",
		"アーザル",
		"デイ",
		"バフマン",
		"エスファンド"
	],
	"dateFormatItem-Ed": "d日(E)",
	"dateFormatItem-yMMM": "y年M月",
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"eraAbbr": [
		"AP"
	],
	"dateFormat-long": "y年M月d日",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "yyyy/MM/dd",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "y/M/d",
	"months-standAlone-wide": [
		"ファルヴァルディーン",
		"オルディーベヘシュト",
		"ホルダード",
		"ティール",
		"モルダード",
		"シャハリーヴァル",
		"メフル",
		"アーバーン",
		"アーザル",
		"デイ",
		"バフマン",
		"エスファンド"
	],
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"ファルヴァルディーン",
		"オルディーベヘシュト",
		"ホルダード",
		"ティール",
		"モルダード",
		"シャハリーヴァル",
		"メフル",
		"アーバーン",
		"アーザル",
		"デイ",
		"バフマン",
		"エスファンド"
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H時",
	"quarters-format-abbr": [
		"1Q",
		"2Q",
		"3Q",
		"4Q"
	],
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-M": "M月",
	"dateFormatItem-yMMMd": "y年M月d日",
	"dateFormatItem-MEd": "M/d(E)",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"days-standAlone-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-hm": "aK:mm",
	"dateFormat-short": "yyyy/MM/dd",
	"dateFormatItem-yMMMEd": "y年M月d日(E)",
	"dateFormat-full": "y年M月d日EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "y/M/d(E)",
	"months-format-wide": [
		"ファルヴァルディーン",
		"オルディーベヘシュト",
		"ホルダード",
		"ティール",
		"モルダード",
		"シャハリーヴァル",
		"メフル",
		"アーバーン",
		"アーザル",
		"デイ",
		"バフマン",
		"エスファンド"
	],
	"days-format-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dateFormatItem-h": "aK時"
}
//end v1.x content
);