define(
//begin v1.x content
{
	"field-sat-relative+0": "የአሁኑ ቅዳሜ",
	"field-sat-relative+1": "የሚቀጥለው ቅዳሜ",
	"field-dayperiod": "ጥዋት/ከሰዓት",
	"field-sun-relative+-1": "ያለፈው እሑድ",
	"field-mon-relative+-1": "ያለፈው ሰኞ",
	"field-minute": "ደቂቃ",
	"field-day-relative+-1": "ትናንት",
	"field-weekday": "አዘቦት",
	"field-day-relative+-2": "ከትናንት ወዲያ",
	"field-era": "ዘመን",
	"field-hour": "ሰዓት",
	"field-sun-relative+0": "የአሁኑ እሑድ",
	"field-sun-relative+1": "የሚቀጥለው እሑድ",
	"field-wed-relative+-1": "ያለፈው እሮብ",
	"field-day-relative+0": "ዛሬ",
	"field-day-relative+1": "ነገ",
	"field-day-relative+2": "ከነገ ወዲያ",
	"field-tue-relative+0": "የአሁኑ ማክሰኞ",
	"field-zone": "የሰዓት ሰቅ",
	"field-tue-relative+1": "የሚቀጥለው ማክሰኞ",
	"field-week-relative+-1": "ባለፈው ሳምንት",
	"field-year-relative+0": "በዚህ ዓመት",
	"field-year-relative+1": "የሚቀጥለው ዓመት",
	"field-sat-relative+-1": "የባለፈው ቅዳሜ",
	"field-year-relative+-1": "ያለፈው ዓመት",
	"field-year": "ዓመት",
	"field-fri-relative+0": "የአሁኑ አርብ",
	"field-fri-relative+1": "የሚቀጥለው አርብ",
	"field-week": "ሳምንት",
	"field-week-relative+0": "በዚህ ሣምንት",
	"field-week-relative+1": "የሚቀጥለው ሳምንት",
	"field-month-relative+0": "በዚህ ወር",
	"field-month": "ወር",
	"field-month-relative+1": "የሚቀጥለው ወር",
	"field-fri-relative+-1": "ያለፈው አርብ",
	"field-second": "ሰከንድ",
	"field-tue-relative+-1": "ያለፈው ማክሰኞ",
	"field-day": "ቀን",
	"field-mon-relative+0": "የአሁኑ ሰኞ",
	"field-mon-relative+1": "የሚቀጥለው ሰኞ",
	"field-thu-relative+0": "የአሁኑ ሐሙስ",
	"field-second-relative+0": "አሁን",
	"field-thu-relative+1": "የሚቀጥለው ሐሙስ",
	"field-wed-relative+0": "የአሁኑ እሮብ",
	"field-wed-relative+1": "የሚቀጥለው እሮብ",
	"field-month-relative+-1": "ያለፈው ወር",
	"field-thu-relative+-1": "ያለፈው ሐመስ"
}
//end v1.x content
);