define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "d MMM y G E",
	"dateFormatItem-MMMEd": "d MMMM E",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-GyMMMd": "dd MMM y G",
	"dateFormatItem-yyyyMM": "MM.y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "G y/QQQQ",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMMMd": "dd MMM y G",
	"dateFormatItem-MMMMEd": "dd MMMM E",
	"dateFormatItem-yyyyMEd": "dd.MM.y G E",
	"dateFormatItem-MMMd": "d MMMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "d MMM y G E",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "dd.MM E",
	"dateFormatItem-yyyyQQQ": "G y/QQQ",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d.MM.y G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormat-full": "d MMMM y G EEEE",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);