define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/yyyy",
	"field-dayperiod": "AM/PM",
	"dayPeriods-format-wide-pm": "PM",
	"dateFormatItem-yQ": "Q yyyy",
	"field-minute": "Dakika",
	"eraNames": [
		"Milattan Önce",
		"Milattan Sonra"
	],
	"dateFormatItem-MMMEd": "dd MMM E",
	"field-day-relative+-1": "Dün",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "Evvelsi gün",
	"field-weekday": "Haftanın Günü",
	"field-day-relative+-3": "Üç gün önce",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"O",
		"Ş",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"dayPeriods-format-wide-am": "AM",
	"field-era": "Miladi Dönem",
	"field-hour": "Saat",
	"dateFormatItem-y": "y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateFormatItem-yyyy": "y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Bugün",
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"field-day-relative+1": "Yarın",
	"eraAbbr": [
		"MÖ",
		"MS"
	],
	"field-day-relative+2": "Yarından sonraki gün",
	"field-day-relative+3": "Üç gün sonra",
	"dateFormat-long": "dd MMMM y",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-EEEd": "d EEE",
	"field-zone": "Saat Dilimi",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd MMM y",
	"dateFormatItem-yyMM": "MM/yy",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM yy",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Yıl",
	"field-week": "Hafta",
	"dateFormatItem-MMMMEd": "dd MMMM E",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"Oca",
		"Şub",
		"Mar",
		"Nis",
		"May",
		"Haz",
		"Tem",
		"Ağu",
		"Eyl",
		"Eki",
		"Kas",
		"Ara"
	],
	"timeFormat-short": "HH:mm",
	"dateFormatItem-H": "HH",
	"field-month": "Ay",
	"dateFormatItem-MMMMd": "dd MMMM",
	"quarters-format-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-mmss": "mm:ss",
	"field-second": "Saniye",
	"field-day": "Gün",
	"dateFormatItem-MEd": "dd/MM E",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yyyy",
	"dateFormatItem-yMMMEd": "dd MMM y EEE",
	"dateFormat-full": "dd MMMM y EEEE",
	"dateFormatItem-Md": "dd/MM",
	"dateFormatItem-yMEd": "dd.MM.yyyy EEE",
	"months-format-wide": [
		"Ocak",
		"Şubat",
		"Mart",
		"Nisan",
		"Mayıs",
		"Haziran",
		"Temmuz",
		"Ağustos",
		"Eylül",
		"Ekim",
		"Kasım",
		"Aralık"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	]
}
//end v1.x content
);