({
	"dateFormatItem-yM": "M/yyyy", 
	"field-dayperiod": "AM/PM", 
	"dayPeriods-format-wide-pm": "PM", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-minute": "Dakika", 
	"eraNames": [
		"Milattan Önce", 
		"Milattan Sonra"
	], 
	"dateFormatItem-MMMEd": "dd MMM E", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Haftanın Günü", 
	"days-standAlone-wide": [
		"Pazar", 
		"Pazartesi", 
		"Salı", 
		"Çarşamba", 
		"Perşembe", 
		"Cuma", 
		"Cumartesi"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"O", 
		"Ş", 
		"M", 
		"N", 
		"M", 
		"H", 
		"T", 
		"A", 
		"E", 
		"E", 
		"K", 
		"A"
	], 
	"dayPeriods-format-wide-am": "AM", 
	"field-era": "Miladi Dönem", 
	"field-hour": "Saat", 
	"quarters-standAlone-abbr": [
		"Ç1", 
		"Ç2", 
		"Ç3", 
		"Ç4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-yyyy": "y", 
	"months-standAlone-abbr": [
		"Oca", 
		"Şub", 
		"Mar", 
		"Nis", 
		"May", 
		"Haz", 
		"Tem", 
		"Ağu", 
		"Eyl", 
		"Eki", 
		"Kas", 
		"Ara"
	], 
	"dateFormatItem-Ed": "d E", 
	"dateFormatItem-yMMM": "MMM y", 
	"days-standAlone-narrow": [
		"P", 
		"P", 
		"S", 
		"Ç", 
		"P", 
		"C", 
		"C"
	], 
	"eraAbbr": [
		"MÖ", 
		"MS"
	], 
	"dateFormat-long": "dd MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-EEEd": "d EEE", 
	"field-zone": "Saat Dilimi", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "dd MMM y", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"dateFormatItem-yyQQQQ": "QQQQ yy", 
	"quarters-standAlone-wide": [
		"1. çeyrek", 
		"2. çeyrek", 
		"3. çeyrek", 
		"4. çeyrek"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Yıl", 
	"field-week": "Hafta", 
	"months-standAlone-wide": [
		"Ocak", 
		"Şubat", 
		"Mart", 
		"Nisan", 
		"Mayıs", 
		"Haziran", 
		"Temmuz", 
		"Ağustos", 
		"Eylül", 
		"Ekim", 
		"Kasım", 
		"Aralık"
	], 
	"dateFormatItem-MMMMEd": "dd MMMM E", 
	"dateFormatItem-MMMd": "dd MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Oca", 
		"Şub", 
		"Mar", 
		"Nis", 
		"May", 
		"Haz", 
		"Tem", 
		"Ağu", 
		"Eyl", 
		"Eki", 
		"Kas", 
		"Ara"
	], 
	"timeFormat-short": "HH:mm", 
	"dateFormatItem-H": "HH", 
	"field-month": "Ay", 
	"dateFormatItem-MMMMd": "dd MMMM", 
	"quarters-format-abbr": [
		"Ç1", 
		"Ç2", 
		"Ç3", 
		"Ç4"
	], 
	"days-format-abbr": [
		"Paz", 
		"Pzt", 
		"Sal", 
		"Çar", 
		"Per", 
		"Cum", 
		"Cmt"
	], 
	"dateFormatItem-M": "L", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"P", 
		"P", 
		"S", 
		"Ç", 
		"P", 
		"C", 
		"C"
	], 
	"field-second": "Saniye", 
	"field-day": "Gün", 
	"dateFormatItem-MEd": "dd/MM E", 
	"months-format-narrow": [
		"O", 
		"Ş", 
		"M", 
		"N", 
		"M", 
		"H", 
		"T", 
		"A", 
		"E", 
		"E", 
		"K", 
		"A"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Paz", 
		"Pzt", 
		"Sal", 
		"Çar", 
		"Per", 
		"Cum", 
		"Cmt"
	], 
	"dateFormat-short": "dd.MM.yyyy", 
	"dateFormatItem-yMMMEd": "dd MMM y EEE", 
	"dateFormat-full": "dd MMMM y EEEE", 
	"dateFormatItem-Md": "dd/MM", 
	"dateFormatItem-yMEd": "dd.MM.yyyy EEE", 
	"months-format-wide": [
		"Ocak", 
		"Şubat", 
		"Mart", 
		"Nisan", 
		"Mayıs", 
		"Haziran", 
		"Temmuz", 
		"Ağustos", 
		"Eylül", 
		"Ekim", 
		"Kasım", 
		"Aralık"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1. çeyrek", 
		"2. çeyrek", 
		"3. çeyrek", 
		"4. çeyrek"
	], 
	"days-format-wide": [
		"Pazar", 
		"Pazartesi", 
		"Salı", 
		"Çarşamba", 
		"Perşembe", 
		"Cuma", 
		"Cumartesi"
	], 
	"eraNarrow": [
		"MÖ", 
		"MS"
	]
})