define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM.yy",
	"dateFormatItem-yyyyMMMEd": "dd MMM y G E",
	"dateFormatItem-yQ": "y-Q",
	"dateFormatItem-MMMEd": "dd MMM E",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y-QQQ",
	"days-standAlone-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	],
	"dateFormatItem-MMM": "LLL",
	"quarters-standAlone-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"Muharrem",
		"Safer",
		"Rebiülevvel",
		"Rebiülahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"Şaban",
		"Ramazan",
		"Şevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "MMM y",
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "dd MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-yyMM": "MM.yy G",
	"dateFormat-medium": "dd MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM yy G",
	"dateFormatItem-yyQQQQ": "QQQQ yy G",
	"dateFormatItem-yMd": "dd.MM.yyyy",
	"quarters-standAlone-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"dateFormatItem-ms": "mm:ss",
	"months-standAlone-wide": [
		"Muharrem",
		"Safer",
		"Rebiülevvel",
		"Rebiülahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"Şaban",
		"Ramazan",
		"Şevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMMMd": "dd MMM y G",
	"dateFormatItem-yyyyMEd": "dd.MM.y G E",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-yyQ": "Q yy G",
	"months-format-abbr": [
		"Muharrem",
		"Safer",
		"Rebiülevvel",
		"Rebiülahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"Şaban",
		"Ramazan",
		"Şevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-H": "HH",
	"quarters-format-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"days-format-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"dateFormatItem-yMMMd": "dd MMM y",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "dd.MM E",
	"dateFormatItem-hm": "h:mm a",
	"days-standAlone-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"dateFormat-short": "dd.MM.yyyy G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormatItem-yMMMEd": "d MMM y E",
	"dateFormat-full": "dd MMMM y G EEEE",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yyyyQ": "Q y G",
	"dateFormatItem-yMEd": "dd.MM.yyyy E",
	"months-format-wide": [
		"Muharrem",
		"Safer",
		"Rebiülevvel",
		"Rebiülahir",
		"Cemaziyelevvel",
		"Cemaziyelahir",
		"Recep",
		"Şaban",
		"Ramazan",
		"Şevval",
		"Zilkade",
		"Zilhicce"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	]
}
//end v1.x content
);