define(
//begin v1.x content
{
	"dateFormat-medium": "dd MMM y G",
	"dateFormatItem-MMMEd": "dd MMM E",
	"dateFormatItem-MEd": "dd.MM E",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-H": "HH",
	"dateFormatItem-yyMMM": "MMM yy G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yyQQQQ": "QQQQ yy G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "dd MMM y G E",
	"dateFormatItem-yyyyMEd": "dd.MM.y G E",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyMM": "MM.yy G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "dd MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyQQQ": "QQQ yy G",
	"dateFormat-short": "d.MM.yyyy G",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-yyyyMMMd": "dd MMM y G",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "dd MMMM y G EEEE",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-Ed": "d E"
}
//end v1.x content
);