define(
//begin v1.x content
{
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-yMd": "d. M. y",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MEd": "E, d. MM.",
	"dateFormatItem-yMEd": "E, d. M. y",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-H": "HH",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMMd": "d. MMM y",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-M": "L",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "dd. MMMM y G",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "d. MM. yy GGGGG",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-h": "h a",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormat-full": "EEEE, dd. MMMM y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-Ed": "E, d."
}
//end v1.x content
);