({
	"field-dayperiod": "Čas dneva", 
	"dayPeriods-format-wide-pm": "pop.", 
	"field-minute": "Minuta", 
	"eraNames": [
		"pred našim štetjem", 
		"naše štetje"
	], 
	"field-day-relative+-1": "Včeraj", 
	"field-day-relative+-2": "Predvčerajšnjim", 
	"field-weekday": "Dan v tednu", 
	"field-day-relative+-3": "Pred tremi dnevi", 
	"days-standAlone-wide": [
		"nedelja", 
		"ponedeljek", 
		"torek", 
		"sreda", 
		"četrtek", 
		"petek", 
		"sobota"
	], 
	"months-standAlone-narrow": [
		"j", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"a", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"field-era": "Doba", 
	"dayPeriods-format-wide-am": "dop.", 
	"field-hour": "Ura", 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maj", 
		"jun", 
		"jul", 
		"avg", 
		"sep", 
		"okt", 
		"nov", 
		"dec"
	], 
	"field-day-relative+0": "Danes", 
	"days-standAlone-narrow": [
		"n", 
		"p", 
		"t", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"field-day-relative+1": "Jutri", 
	"eraAbbr": [
		"pr. n. št.", 
		"po Kr."
	], 
	"field-day-relative+2": "Pojutrišnjem", 
	"field-day-relative+3": "Čez tri dni", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "dd. MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Območje", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d. MMM. yyyy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"1. četrtletje", 
		"2. četrtletje", 
		"3. četrtletje", 
		"4. četrtletje"
	], 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Leto", 
	"field-week": "Teden", 
	"months-standAlone-wide": [
		"januar", 
		"februar", 
		"marec", 
		"april", 
		"maj", 
		"junij", 
		"julij", 
		"avgust", 
		"september", 
		"oktober", 
		"november", 
		"december"
	], 
	"dateFormatItem-yyQ": "Q/yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maj", 
		"jun", 
		"jul", 
		"avg", 
		"sep", 
		"okt", 
		"nov", 
		"dec"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Mesec", 
	"dateFormatItem-MMMMd": "d. MMMM", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"ned", 
		"pon", 
		"tor", 
		"sre", 
		"čet", 
		"pet", 
		"sob"
	], 
	"dateFormatItem-MMMMdd": "dd. MMMM", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"n", 
		"p", 
		"t", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"field-second": "Sekunda", 
	"field-day": "Dan", 
	"months-format-narrow": [
		"j", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"a", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"days-standAlone-abbr": [
		"ned", 
		"pon", 
		"tor", 
		"sre", 
		"čet", 
		"pet", 
		"sob"
	], 
	"dateFormat-short": "d. MM. yy", 
	"dateFormatItem-yyyyM": "M/yyyy", 
	"dateFormat-full": "EEEE, dd. MMMM y", 
	"dateFormatItem-Md": "d. M.", 
	"months-format-wide": [
		"januar", 
		"februar", 
		"marec", 
		"april", 
		"maj", 
		"junij", 
		"julij", 
		"avgust", 
		"september", 
		"oktober", 
		"november", 
		"december"
	], 
	"quarters-format-wide": [
		"1. četrtletje", 
		"2. četrtletje", 
		"3. četrtletje", 
		"4. četrtletje"
	], 
	"days-format-wide": [
		"nedelja", 
		"ponedeljek", 
		"torek", 
		"sreda", 
		"četrtek", 
		"petek", 
		"sobota"
	], 
	"eraNarrow": [
		"pr. n. št.", 
		"po Kr."
	]
})