define(
//begin v1.x content
{
	"field-second-relative+0": "tani",
	"field-weekday": "ditë e javës",
	"field-wed-relative+0": "këtë të mërkurë",
	"field-wed-relative+1": "të mërkurën e ardhshme",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-tue-relative+-1": "të martën e kaluar",
	"dateFormat-long": "dd MMMM y G",
	"field-fri-relative+-1": "të premten e kaluar",
	"field-wed-relative+-1": "të mërkurën e kaluar",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE dd MMMM y G",
	"dateFormatItem-yyyyMEd": "E d/M/y G",
	"field-thu-relative+-1": "të enjten e kaluar",
	"dateFormatItem-Md": "d/M",
	"field-era": "erë",
	"field-year": "vit",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"field-hour": "orë",
	"field-sat-relative+0": "këtë të shtunë",
	"field-sat-relative+1": "të shtunën e ardhshme",
	"field-day-relative+0": "sot",
	"field-day-relative+1": "nesër",
	"field-thu-relative+0": "këtë të enjte",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-thu-relative+1": "të enjten e ardhshme",
	"dateFormatItem-H": "H",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-sun-relative+0": "këtë të diel",
	"dateFormatItem-Hm": "H.mm",
	"field-sun-relative+1": "të dielën e ardhshme",
	"field-minute": "minutë",
	"field-dayperiod": "periudhë e ditës",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm.ss",
	"field-day-relative+-1": "dje",
	"dateFormatItem-h": "h.a",
	"dateTimeFormat-long": "{1} 'në' {0}",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E d/M",
	"dateTimeFormat-full": "{1} 'në' {0}",
	"field-fri-relative+0": "këtë të premte",
	"field-fri-relative+1": "të premten e ardhshme",
	"field-day": "ditë",
	"field-zone": "zonë",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "vitin e kaluar",
	"field-month-relative+-1": "muajin e kaluar",
	"dateFormatItem-hm": "h.mm.a",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"field-month": "muaj",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "këtë të martë",
	"field-tue-relative+1": "të martën e ardhshme",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"field-mon-relative+0": "këtë të hënë",
	"field-mon-relative+1": "të hënën e ardhshme",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"field-second": "sekondë",
	"field-sat-relative+-1": "të shtunën e kaluar",
	"field-sun-relative+-1": "të dielën e kaluar",
	"field-month-relative+0": "këtë muaj",
	"field-month-relative+1": "muajin e ardhshëm",
	"dateFormatItem-Ed": "E d",
	"field-week": "javë",
	"dateFormat-medium": "dd/MMM/y G",
	"field-year-relative+0": "këtë vit",
	"field-week-relative+-1": "javën e kaluar",
	"dateFormatItem-yyyyM": "M/y G",
	"field-year-relative+1": "vitin e ardhshëm",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-hms": "h.mm.ss.a",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "të hënën e kaluar",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "këtë javë",
	"field-week-relative+1": "javën e ardhshme"
}
//end v1.x content
);