define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"field-dayperiod": "ДП/ПП",
	"field-minute": "хвіліна",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "учора",
	"dateFormatItem-hms": "h.mm.ss a",
	"field-day-relative+-2": "пазаўчора",
	"field-weekday": "дзень тыдня",
	"dateFormatItem-MMM": "LLL",
	"field-era": "эра",
	"dateFormatItem-Gy": "y G",
	"field-hour": "гадзіна",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E, d",
	"field-day-relative+0": "сёння",
	"field-day-relative+1": "заўтра",
	"field-day-relative+2": "паслязаўтра",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Zone",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "год",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-week": "тыдзень",
	"dateFormatItem-yyyyMd": "d.M.y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, d.M.y G",
	"dateFormatItem-MMMd": "d MMM",
	"field-month": "месяц",
	"dateFormatItem-M": "L",
	"field-second": "секунда",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"field-day": "дзень",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, d.M",
	"dateFormatItem-hm": "h.mm a",
	"dateFormat-short": "d.M.y GGGGG",
	"dateFormatItem-yyyyM": "M.y G",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d"
}
//end v1.x content
);