({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray. 
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "azul-bebê",
antiquewhite: "branco velho",
aqua: "azul-água",
aquamarine: "água-marinha",
azure: "azul-celeste",
beige: "bege",
bisque: "biscuit",
black: "preto",
blanchedalmond: "branco-amêndoa",
blue: "azul",
blueviolet: "violeta azulado",
brown: "marrom",
burlywood: "madeira",
cadetblue: "azul-cadete",
chartreuse: "verde-amarelado",
chocolate: "chocolate",
coral: "coral",
cornflowerblue: "centáurea azul",
cornsilk: "fios de milho",
crimson: "carmim",
cyan: "ciano",
darkblue: "azul-escuro",
darkcyan: "ciano-escuro",
darkgoldenrod: "ouro-escuro",
darkgray: "cinza-escuro",
darkgreen: "verde-escuro",
darkgrey: "cinza-escuro", // same as darkgray
darkkhaki: "cáqui-escuro",
darkmagenta: "magenta-escuro",
darkolivegreen: "verde-oliva escuro",
darkorange: "laranja-escuro",
darkorchid: "orquídea-escuro",
darkred: "vermelho-escuro",
darksalmon: "salmão escuro",
darkseagreen: "verde-mar escuro",
darkslateblue: "ardósia azul-escuro",
darkslategray: "ardósia cinza-escuro",
darkslategrey: "ardósia cinza-escuro", // same as darkslategray
darkturquoise: "turquesa-escuro",
darkviolet: "violeta-escuro",
deeppink: "rosa profundo",
deepskyblue: "azul celeste profundo",
dimgray: "cinza-escuro",
dimgrey: "cinza-escuro", // same as dimgray
dodgerblue: "azul fugidio",
firebrick: "tijolo queimado",
floralwhite: "branco floral",
forestgreen: "verde floresta",
fuchsia: "fúcsia",
gainsboro: "gainsboro",
ghostwhite: "branco sombreado",
gold: "dourado",
goldenrod: "ouro",
gray: "cinza",
green: "verde",
greenyellow: "verde-amarelado",
grey: "cinza", // same as gray
honeydew: "verde mel",
hotpink: "rosa quente",
indianred: "vermelho oriental",
indigo: "índigo",
ivory: "marfim",
khaki: "cáqui",
lavender: "lavanda",
lavenderblush: "lavanda avermelhada",
lawngreen: "verde grama",
lemonchiffon: "gaze limão",
lightblue: "azul-claro",
lightcoral: "coral-claro",
lightcyan: "ciano-claro",
lightgoldenrodyellow: "amarelo-claro",
lightgray: "cinza-claro",
lightgreen: "verde-claro",
lightgrey: "cinza-claro", // same as lightgray
lightpink: "rosa-claro",
lightsalmon: "salmão claro",
lightseagreen: "verde-mar claro",
lightskyblue: "azul celeste claro",
lightslategray: "ardósia cinza-claro",
lightslategrey: "ardósia cinza-claro", // same as lightslategray
lightsteelblue: "azul metálico claro",
lightyellow: "amarelo-claro",
lime: "lima",
limegreen: "verde lima",
linen: "linho",
magenta: "magenta",
maroon: "castanho",
mediumaquamarine: "verde-azulado temperado",
mediumblue: "azul temperado",
mediumorchid: "orquídea temperado",
mediumpurple: "púrpura temperado",
mediumseagreen: "verde mar temperado",
mediumslateblue: "ardósia azul médio",
mediumspringgreen: "verde primavera médio",
mediumturquoise: "turquesa médio",
mediumvioletred: "violeta avermelhado médio",
midnightblue: "azul noturno",
mintcream: "menta",
mistyrose: "rosa nublado",
moccasin: "mocassim",
navajowhite: "branco navajo",
navy: "marinho",
oldlace: "fita velha",
olive: "verde-oliva",
olivedrab: "verde-acastanhado",
orange: "laranja",
orangered: "vermelho-alaranjado",
orchid: "orquídea",
palegoldenrod: "ouro pálido",
palegreen: "verde pálido",
paleturquoise: "turquesa pálida",
palevioletred: "violeta pálida",
papayawhip: "mamão papaia",
peachpuff: "pêssego",
peru: "peru",
pink: "rosado",
plum: "ameixa",
powderblue: "azul pólvora",
purple: "púrpura",
red: "vermelho",
rosybrown: "marrom rosado",
royalblue: "azul real",
saddlebrown: "marrom couro",
salmon: "salmão",
sandybrown: "marrom arenoso",
seagreen: "verde-mar",
seashell: "concha marinha",
sienna: "marrom-avermelhado",
silver: "prata",
skyblue: "azul celeste",
slateblue: "ardósia azul",
slategray: "ardósia cinza",
slategrey: "ardósia cinza", // same as slategray
snow: "branco neve",
springgreen: "verde primavera",
steelblue: "azul metálico",
tan: "canela",
teal: "azul-esverdeado",
thistle: "cardo",
tomato: "vermelho tomate",
turquoise: "turquesa",
violet: "violeta",
wheat: "trigo",
white: "branco",
whitesmoke: "branco esfumaçado",
yellow: "amarelo",
yellowgreen: "amarelo esverdeado"
})
