define(
//begin v1.x content
{
	"USD_displayName": "Ndola wa Ameriki",
	"TZS_displayName": "Nshili wa Tanzani",
	"ZMW_displayName": "Kwasha wa Zambi",
	"MAD_displayName": "Ndiriha wa Maroke",
	"NGN_displayName": "Naira wa Nizerya",
	"ZWD_displayName": "Ndola wa Zimbabwe",
	"SDG_displayName": "Ndina wa Suda",
	"MWK_displayName": "Kwasha wa Malawi",
	"KMF_displayName": "Nfalanga wa Komoru",
	"SCR_displayName": "Rupya wa Seshele",
	"CDF_symbol": "FC",
	"EGP_displayName": "Pauni wa Mushidi",
	"CVE_displayName": "Esikuludo wa Kapevere",
	"LYD_displayName": "Ndina wa Libi",
	"CAD_displayName": "Ndola wa Kanada",
	"INR_displayName": "Rupi wa Inde",
	"JPY_displayName": "Yeni wa Zapɔ",
	"LRD_displayName": "Ndola wa Liberya",
	"ZAR_displayName": "Rande wa Afrika wa Mwinshi",
	"AOA_displayName": "Kwanza wa Angola",
	"TND_displayName": "Ndina wa Tinizi",
	"GHC_displayName": "Sedi wa Ngana",
	"BWP_displayName": "Pula wa Botswana",
	"DZD_displayName": "Ndina wa Alijeri",
	"ZMK_displayName": "Kwasha wa Zambi (1968–2012)",
	"NAD_displayName": "Ndola wa Namibi",
	"AED_displayName": "Ndiriha wa Lemila alabu",
	"ETB_displayName": "Bira wa Etshiopi",
	"MZM_displayName": "Metikali wa Mozambiki",
	"BIF_displayName": "Nfalanga wa Bulundi",
	"RWF_displayName": "Nfalanga wa Rwanda",
	"STD_displayName": "Dobra wa Sao Tome ne Presipe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Iro",
	"ERN_displayName": "Nakfa wa Elitle",
	"SAR_displayName": "Riyale wa Alabu Nsawu",
	"DJF_displayName": "Nfalanga wa Dzibuti",
	"CDF_displayName": "Nfalanga wa Kongu",
	"GBP_displayName": "Pauni wa Angeletele",
	"CHF_displayName": "Nfalanga wa Swise",
	"MUR_displayName": "Rupia wa Morisi",
	"SOS_displayName": "Nshili wa Somali",
	"BHD_displayName": "Ndina wa Bahrene",
	"XOF_displayName": "Nfalanga CFA BCEAO",
	"GNS_displayName": "Nfalanga wa Ngina",
	"SLL_displayName": "Leone",
	"UGX_displayName": "Nshili wa Uganda",
	"MGA_displayName": "Nfalanga wa Madagasikare",
	"SDP_displayName": "Pauni wa Suda",
	"AUD_displayName": "Ndola wa Ositali",
	"KES_displayName": "Nshili wa Kenya",
	"SHP_displayName": "Pauni wa Santu Elena",
	"XAF_displayName": "Nfalanga CFA BEAC",
	"LSL_displayName": "Loti wa Lesoto",
	"MRO_displayName": "Ugwiya wa Moritani",
	"CNY_displayName": "Yuani Renminbi wa Shine",
	"GMD_displayName": "Ndalasi wa Ngambi"
}
//end v1.x content
);