define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Mutantshi wa diba",
	"field-minute": "Kasunsu",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Makelela",
	"field-weekday": "Dituku dia lubingu",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Tshipungu",
	"field-hour": "Diba",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Lelu",
	"field-day-relative+1": "Malaba",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Nzeepu",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Tshidimu",
	"field-week": "Lubingu",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Ngondo",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Kasunsukusu",
	"field-day": "Dituku",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);