define(
//begin v1.x content
{
	"dateFormatItem-GyMMM": "MMM U",
	"dateFormat-medium": "d MMM U",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyMMM": "MMM U",
	"dateFormatItem-GyMMMd": "d MMM U",
	"dateFormatItem-y": "U",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyQQQQ": "QQQQ U",
	"dateFormatItem-GyMMMEd": "E d MMM U",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "E d MMM U",
	"dateFormatItem-yyyyMEd": "E d/M/y",
	"dateFormatItem-yyyy": "U",
	"dateFormat-long": "d MMMM U",
	"dateFormatItem-yyyyQQQ": "QQQ U",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "d/M/y",
	"months-format-wide": [
		"zhēngyuè",
		"èryuè",
		"sānyuè",
		"sìyuè",
		"wǔyuè",
		"liùyuè",
		"qīyuè",
		"bāyuè",
		"jiǔyuè",
		"shíyuè",
		"shíyīyuè",
		"shí’èryuè"
	],
	"dateFormatItem-Gy": "U",
	"months-format-abbr": [
		"1yuè",
		"2yuè",
		"3yuè",
		"4yuè",
		"5yuè",
		"6yuè",
		"7yuè",
		"8yuè",
		"9yuè",
		"10yuè",
		"11yuè",
		"12yuè"
	],
	"dateFormatItem-yyyyMMMd": "d MMM U",
	"dateFormatItem-yyyyM": "M/y",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "EEEE d MMMM U",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyyyMd": "d/M/y"
}
//end v1.x content
);