// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"peseta andorrane",
	ADP_symbol:"₧A",
	AED_displayName:"dirham des Émirats arabes unis",
	AFA_displayName:"afghani (1927–2002)",
	AFN_displayName:"afghani",
	AFN_symbol:"Af",
	ALL_displayName:"lek albanais",
	ALL_symbol:"lek",
	AMD_displayName:"dram arménien",
	AMD_symbol:"dram",
	ANG_displayName:"florin antillais",
	ANG_symbol:"f.NA",
	AOA_displayName:"kwanza angolais",
	AOK_displayName:"kwanza angolais (1977-1990)",
	AON_displayName:"nouveau kwanza angolais (1990-2000)",
	AOR_displayName:"kwanza angolais réajusté (1995-1999)",
	ARA_displayName:"austral argentin",
	ARP_displayName:"peso argentin (1983-1985)",
	ARS_displayName:"peso argentin",
	ARS_symbol:"Arg$",
	ATS_displayName:"schilling autrichien",
	AUD_displayName:"dollar australien",
	AUD_symbol:"$A",
	AWG_displayName:"florin arubais",
	AZM_displayName:"manat azéri (1993-2006)",
	AZN_displayName:"manat azéri",
	BAD_displayName:"dinar bosniaque",
	BAM_displayName:"mark convertible bosniaque",
	BAM_symbol:"KM",
	BBD_displayName:"dollar barbadien",
	BBD_symbol:"$Bds",
	BDT_displayName:"taka bangladeshi",
	BEC_displayName:"franc belge (convertible)",
	BEF_displayName:"franc belge",
	BEF_symbol:"FB",
	BEL_displayName:"franc belge (financier)",
	BGL_displayName:"lev bulgare (1962–1999)",
	BGN_displayName:"nouveau lev bulgare",
	BGN_symbol:"NB",
	BHD_displayName:"dinar bahreïni",
	BIF_displayName:"franc burundais",
	BIF_symbol:"FBu",
	BMD_displayName:"dollar bermudien",
	BMD_symbol:"$Bm",
	BND_displayName:"dollar brunéien",
	BND_symbol:"$Bn",
	BOB_displayName:"boliviano",
	BOB_symbol:"Bs",
	BOP_displayName:"peso bolivien",
	BOV_displayName:"mvdol bolivien",
	BRB_displayName:"nouveau cruzeiro brésilien (1967–1986)",
	BRC_displayName:"cruzado brésilien (1986–1989)",
	BRE_displayName:"cruzeiro brésilien (1990–1993)",
	BRL_displayName:"réal brésilien",
	BRN_displayName:"nouveau cruzado",
	BRR_displayName:"cruzeiro",
	BSD_displayName:"dollar bahaméen",
	BTN_displayName:"ngultrum bouthanais",
	BTN_symbol:"Nu",
	BUK_displayName:"kyat birman",
	BWP_displayName:"pula botswanais",
	BYB_displayName:"nouveau rouble biélorusse (1994-1999)",
	BYR_displayName:"rouble biélorusse",
	BYR_symbol:"Rbl",
	BZD_displayName:"dollar bélizéen",
	BZD_symbol:"$Bz",
	CAD_displayName:"dollar canadien",
	CAD_symbol:"$Ca",
	CDF_displayName:"franc congolais",
	CDF_symbol:"FrCD",
	CHE_displayName:"euro WIR",
	CHF_displayName:"franc suisse",
	CHF_symbol:"sFr.",
	CHW_displayName:"franc WIR",
	CLF_displayName:"unité d’investissement chilienne",
	CLP_displayName:"peso chilien",
	CLP_symbol:"$Ch",
	CNY_displayName:"yuan renminbi chinois",
	CNY_symbol:"Ұ",
	COP_displayName:"peso colombien",
	COP_symbol:"PsCo",
	COU_displayName:"Unité de valeur réelle colombienne",
	CRC_displayName:"colón costaricain",
	CRC_symbol:"C",
	CSD_displayName:"dinar serbo-monténégrin",
	CSD_symbol:"DS",
	CSK_displayName:"couronne forte tchécoslovaque",
	CUP_displayName:"peso cubain",
	CUP_symbol:"PsCu",
	CVE_displayName:"escudo capverdien",
	CVE_symbol:"EscCV",
	CYP_displayName:"livre chypriote",
	CYP_symbol:"£C",
	CZK_displayName:"couronne tchèque",
	CZK_symbol:"CrCz",
	DDM_displayName:"mark est-allemand",
	DEM_displayName:"mark allemand",
	DEM_symbol:"DM",
	DJF_displayName:"franc djiboutien",
	DJF_symbol:"DF",
	DKK_displayName:"couronne danoise",
	DKK_symbol:"CrD",
	DOP_displayName:"peso dominicain",
	DZD_displayName:"dinar algérien",
	DZD_symbol:"DA",
	ECS_displayName:"sucre équatorien",
	ECV_displayName:"unité de valeur constante équatoriale (UVC)",
	EEK_displayName:"couronne estonienne",
	EEK_symbol:"CrE",
	EGP_displayName:"livre égyptienne",
	EGP_symbol:"£Eg",
	EQE_displayName:"ekwélé",
	ERN_displayName:"nafka érythréen",
	ESA_displayName:"peseta espagnole (compte A)",
	ESB_displayName:"peseta espagnole (compte convertible)",
	ESP_displayName:"peseta espagnole",
	ESP_symbol:"₧",
	ETB_displayName:"birr éthiopien",
	ETB_symbol:"Br",
	EUR_displayName:"euro",
	FIM_displayName:"mark finlandais",
	FJD_displayName:"dollar fidjien",
	FJD_symbol:"$F",
	FKP_displayName:"livre des Falkland",
	FKP_symbol:"£Fk",
	FRF_displayName:"franc français",
	FRF_symbol:"F",
	GBP_displayName:"livre sterling",
	GBP_symbol:"£UK",
	GEK_displayName:"Georgian Kupon Larit",
	GEL_displayName:"lari géorgien",
	GEL_symbol:"lari",
	GHC_displayName:"cédi",
	GHS_displayName:"cédi ghanéen",
	GIP_displayName:"livre de Gibraltar",
	GIP_symbol:"£Gi",
	GMD_displayName:"dalasi gambien",
	GMD_symbol:"Ds",
	GNF_displayName:"franc guinéen",
	GNF_symbol:"GF",
	GNS_displayName:"syli guinéen",
	GQE_displayName:"ekwélé équatoguinéen",
	GRD_displayName:"drachme grecque",
	GTQ_displayName:"quetzal guatémaltèque",
	GWE_displayName:"escudo de Guinée portugaise",
	GWP_displayName:"peso bissau-guinéen",
	GYD_displayName:"dollar du Guyana",
	GYD_symbol:"G$",
	HKD_displayName:"dollar de Hong Kong",
	HKD_symbol:"$HK",
	HNL_displayName:"lempira hondurien",
	HNL_symbol:"LH",
	HRD_displayName:"dinar croate",
	HRK_displayName:"kuna croate",
	HRK_symbol:"Ku",
	HTG_displayName:"gourde haïtienne",
	HTG_symbol:"Gd",
	HUF_displayName:"forint hongrois",
	HUF_symbol:"Ft",
	IDR_displayName:"roupie indonésienne",
	IEP_displayName:"livre irlandaise",
	IEP_symbol:"£IE",
	ILP_displayName:"livre israélienne",
	ILP_symbol:"£IL",
	ILS_displayName:"nouveau shekel israélien",
	INR_displayName:"roupie indienne",
	INR_symbol:"INR",
	IQD_displayName:"dinar irakien",
	IQD_symbol:"DI",
	IRR_displayName:"rial iranien",
	ISK_displayName:"couronne islandaise",
	ISK_symbol:"KrIs",
	ITL_displayName:"lire italienne",
	ITL_symbol:"₤IT",
	JMD_displayName:"dollar jamaïcain",
	JMD_symbol:"$JM",
	JOD_displayName:"dinar jordanien",
	JOD_symbol:"DJ",
	JPY_displayName:"yen japonais",
	JPY_symbol:"¥JP",
	KES_displayName:"shilling kényan",
	KES_symbol:"ShK",
	KGS_displayName:"som kirghize",
	KGS_symbol:"som",
	KHR_displayName:"riel cambodgien",
	KMF_displayName:"franc comorien",
	KMF_symbol:"FC",
	KPW_displayName:"won nord-coréen",
	KPW_symbol:"₩kp",
	KRW_displayName:"won sud-coréen",
	KRW_symbol:"₩kr",
	KWD_displayName:"dinar koweïtien",
	KWD_symbol:"DK",
	KYD_displayName:"dollar des îles Caïmanes",
	KYD_symbol:"$KY",
	KZT_displayName:"tenge kazakh",
	KZT_symbol:"T",
	LAK_displayName:"kip loatien",
	LAK_symbol:"KL",
	LBP_displayName:"livre libanaise",
	LBP_symbol:"£LB",
	LKR_displayName:"roupie srilankaise",
	LRD_displayName:"dollar libérien",
	LRD_symbol:"$LR",
	LSL_displayName:"loti lesothan",
	LSL_symbol:"M",
	LSM_displayName:"maloti",
	LTL_displayName:"litas lituanien",
	LTT_displayName:"talonas lituanien",
	LUC_displayName:"franc convertible luxembourgeois",
	LUF_displayName:"franc luxembourgeois",
	LUL_displayName:"franc financier luxembourgeois",
	LVL_displayName:"lats letton",
	LVR_displayName:"rouble letton",
	LYD_displayName:"dinar lybien",
	LYD_symbol:"LD",
	MAD_displayName:"dirham marocain",
	MAD_symbol:"Dm",
	MAF_displayName:"franc marocain",
	MDL_displayName:"leu moldave",
	MGA_displayName:"ariary malgache",
	MGF_displayName:"franc malgache",
	MKD_displayName:"denar macédonien",
	MKD_symbol:"MDen",
	MLF_displayName:"franc malien",
	MMK_displayName:"kyat myanmarais",
	MNT_displayName:"tugrik mongol",
	MOP_displayName:"pataca macanaise",
	MRO_displayName:"ouguiya mauritanien",
	MTL_displayName:"lire maltaise",
	MTL_symbol:"Lm",
	MTP_displayName:"livre maltaise",
	MUR_displayName:"roupie mauricienne",
	MVR_displayName:"rufiyaa maldivienne",
	MWK_displayName:"kwacha malawite",
	MXN_displayName:"peso mexicain",
	MXN_symbol:"$Mex",
	MXP_displayName:"peso d’argent mexicain (1861–1992)",
	MXV_displayName:"unité de conversion mexicaine (UDI)",
	MYR_displayName:"ringgit malais",
	MZE_displayName:"escudo mozambicain",
	MZM_displayName:"métical",
	MZN_displayName:"metical mozambicain",
	NAD_displayName:"dollar namibien",
	NAD_symbol:"N$",
	NGN_displayName:"naira nigérian",
	NIC_displayName:"cordoba",
	NIO_displayName:"córdoba oro nicaraguayen",
	NLG_displayName:"florin néerlandais",
	NOK_displayName:"couronne norvégienne",
	NPR_displayName:"roupie népalaise",
	NZD_displayName:"dollar néo-zélandais",
	NZD_symbol:"$NZ",
	OMR_displayName:"rial omani",
	PAB_displayName:"balboa panaméen",
	PEI_displayName:"inti péruvien",
	PEN_displayName:"nouveau sol péruvien",
	PES_displayName:"sol péruvien",
	PGK_displayName:"kina papouan-néo-guinéen",
	PHP_displayName:"peso philippin",
	PKR_displayName:"roupie pakistanaise",
	PLN_displayName:"zloty polonais",
	PLZ_displayName:"zloty (1950-1995)",
	PTE_displayName:"escudo portugais",
	PYG_displayName:"guaraní paraguayen",
	QAR_displayName:"rial qatari",
	RHD_displayName:"dollar rhodésien",
	ROL_displayName:"ancien leu roumain",
	RON_displayName:"leu roumain",
	RSD_displayName:"dinar serbe",
	RUB_displayName:"rouble russe",
	RUR_displayName:"rouble russe (1991–1998)",
	RWF_displayName:"franc rwandais",
	SAR_displayName:"rial saoudien",
	SBD_displayName:"dollar des îles Salomon",
	SCR_displayName:"roupie des Seychelles",
	SDD_displayName:"dinar soudanais",
	SDG_displayName:"livre soudanaise",
	SDP_displayName:"livre soudanaise (1956–2007)",
	SEK_displayName:"couronne suédoise",
	SGD_displayName:"dollar de Singapour",
	SHP_displayName:"livre de Sainte-Hélène",
	SIT_displayName:"tolar slovène",
	SKK_displayName:"couronne slovaque",
	SLL_displayName:"leone sierra-léonais",
	SOS_displayName:"shilling somalien",
	SRD_displayName:"dollar surinamais",
	SRG_displayName:"florin surinamais",
	STD_displayName:"dobra santoméen",
	SUR_displayName:"rouble soviétique",
	SVC_displayName:"colón salvadorien",
	SYP_displayName:"livre syrienne",
	SYP_symbol:"£SY",
	SZL_displayName:"lilangeni swazi",
	SZL_symbol:"Li",
	THB_displayName:"baht thaïlandais",
	TJR_displayName:"rouble tadjik",
	TJS_displayName:"somoni tadjik",
	TMM_displayName:"manat turkmène",
	TND_displayName:"dinar tunisien",
	TOP_displayName:"pa’anga tongan",
	TPE_displayName:"escudo timorais",
	TRL_displayName:"livre turque",
	TRL_symbol:"TL",
	TRY_displayName:"nouvelle livre turque",
	TTD_displayName:"dollar trinidadien",
	TWD_displayName:"nouveau dollar taïwanais",
	TZS_displayName:"shilling tanzanien",
	UAH_displayName:"hryvnia ukrainienne",
	UAK_displayName:"karbovanetz",
	UGS_displayName:"shilling ougandais (1966-1987)",
	UGX_displayName:"shilling ougandais",
	UGX_symbol:"U Sh",
	USD_displayName:"dollar des États-Unis",
	USD_symbol:"$US",
	USN_displayName:"dollar des Etats-Unis (jour suivant)",
	USS_displayName:"dollar des Etats-Unis (jour même)",
	UYP_displayName:"peso uruguayen (1975–1993)",
	UYU_displayName:"peso uruguayen",
	UYU_symbol:"Ur$",
	UZS_displayName:"sum ouzbek",
	VEB_displayName:"bolivar",
	VEB_symbol:"Be",
	VEF_displayName:"bolivar fuerte vénézuélien",
	VND_displayName:"dông vietnamien",
	VUV_displayName:"vatu vanuatuan",
	WST_displayName:"tala samoan",
	XAF_displayName:"franc CFA (BEAC)",
	XAG_displayName:"argent",
	XAU_displayName:"or",
	XBA_displayName:"unité européenne composée",
	XBB_displayName:"unité monétaire européenne",
	XBC_displayName:"unité de compte européenne (XBC)",
	XBD_displayName:"unité de compte européenne (XBD)",
	XCD_displayName:"dollar des Caraïbes orientales",
	XCD_symbol:"$EC",
	XDR_displayName:"droit de tirage spécial",
	XEU_displayName:"unité de compte européenne (ECU)",
	XFO_displayName:"franc or",
	XFU_displayName:"franc UIC",
	XOF_displayName:"franc CFA (BCEAO)",
	XPD_displayName:"palladium",
	XPF_displayName:"franc CFP",
	XPF_symbol:"FCFP",
	XPT_displayName:"platine",
	XRE_displayName:"type de fonds RINET",
	XXX_displayName:"devise inconnue ou non valide",
	YDD_displayName:"dinar du Yémen",
	YER_displayName:"rial yéménite",
	YUD_displayName:"nouveau dinar yougoslave",
	YUM_displayName:"dinar yougoslave Noviy",
	YUN_displayName:"dinar yougoslave convertible",
	ZAL_displayName:"rand sud-africain (financier)",
	ZAR_displayName:"rand sud-africain",
	ZMK_displayName:"kwacha zambien",
	ZRN_displayName:"nouveau zaïre zaïrien",
	ZRZ_displayName:"zaïre zaïrois",
	ZWD_displayName:"dollar zimbabwéen",
	ZWD_symbol:"Z$"
})
                 