define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/yyyy",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-yQ": "'T'Q y",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-MMMdd": "dd MMM",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"Mouh.",
		"Saf.",
		"Rabiʻ-oul-A.",
		"Rabiʻ-out-T.",
		"Djoum.-l-O.",
		"Djoum.-t-T.",
		"Radj.",
		"Cha.",
		"Ram.",
		"Chaou.",
		"Dou-l-Q.",
		"Dou-l-H."
	],
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"M",
		"J",
		"V",
		"S"
	],
	"eraAbbr": [
		"AH"
	],
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d/MM",
	"dateFormatItem-yyMM": "MM/y G",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dayPeriods-format-narrow-pm": "p",
	"dateFormatItem-yyMMM": "MMM y G",
	"dateFormatItem-yyQQQQ": "QQQQ y G",
	"dateFormatItem-yMd": "d/M/yyyy",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyMMMd": "d MMM y G",
	"months-standAlone-wide": [
		"Mouharram",
		null,
		"Rabiʻ-oul-Aououal",
		"Rabiʻ-out-Tani",
		"Djoumada-l-Oula",
		"Djoumada-t-Tania",
		"Radjab",
		"Chaʻban",
		null,
		"Chaououal",
		"Dou-l-Qaʻda",
		"Dou-l-Hidjja"
	],
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-yyyyMEd": "E d/M/y G",
	"dateFormatItem-MMMd": "d MMM",
	"quarters-format-narrow": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"dateFormatItem-yyMMMEd": "E d MMM y G",
	"dateFormatItem-yyQ": "'T'Q y G",
	"months-format-abbr": [
		"Mouh.",
		"Saf.",
		"Rabiʻ-oul-A.",
		"Rabiʻ-out-T.",
		"Djoum.-l-O.",
		"Djoum.-t-T.",
		"Radj.",
		"Cha.",
		"Ram.",
		"Chaou.",
		"Dou-l-Q.",
		"Dou-l-H."
	],
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"days-format-abbr": [
		"dim.",
		"lun.",
		"mar.",
		"mer.",
		"jeu.",
		"ven.",
		"sam."
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"days-standAlone-abbr": [
		"dim.",
		"lun.",
		"mar.",
		"mer.",
		"jeu.",
		"ven.",
		"sam."
	],
	"dateFormat-short": "d/M/y G",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyQ": "'T'Q y G",
	"dateFormatItem-yMEd": "E d/M/yyyy",
	"months-format-wide": [
		"Mouharram",
		null,
		"Rabiʻ-oul-Aououal",
		"Rabiʻ-out-Tani",
		"Djoumada-l-Oula",
		"Djoumada-t-Tania",
		"Radjab",
		"Chaʻban",
		null,
		"Chaououal",
		"Dou-l-Qaʻda",
		"Dou-l-Hidjja"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1er trimestre",
		"2e trimestre",
		"3e trimestre",
		"4e trimestre"
	],
	"days-format-wide": [
		"dimanche",
		"lundi",
		"mardi",
		"mercredi",
		"jeudi",
		"vendredi",
		"samedi"
	]
}
//end v1.x content
);