define(
//begin v1.x content
{
	"dateFormatItem-GyMMM": "G y. MMM",
	"dateFormat-medium": "G y.MM.dd.",
	"dateFormatItem-MMMEd": "MMM d., E",
	"dateFormatItem-MEd": "M. d., E",
	"dateFormatItem-yyyyMMM": "G y. MMM",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-H": "H",
	"dateFormatItem-GyMMMd": "G y. MMM d.",
	"dateFormatItem-y": "G y",
	"dateFormatItem-hm": "a h:mm",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-yyyyQQQQ": "G y. QQQQ",
	"dateFormatItem-GyMMMEd": "G y. MMM d., E",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "G y. MMM d., E",
	"dateFormatItem-yyyyMEd": "G y.MM.dd., E",
	"dateFormatItem-yyyyMMMM": "G y. MMMM",
	"dateFormatItem-MMMMd": "MMMM d.",
	"dateFormatItem-yyyy": "G y",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormat-long": "G y. MMMM d.",
	"dateFormatItem-yyyyQQQ": "G y. QQQ",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "GGGGG y.MM.dd.",
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-d": "d",
	"dateFormatItem-yyyyMMMd": "G y. MMM d.",
	"dateFormatItem-h": "a h",
	"dateFormatItem-yyyyM": "G y.M.",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "G y. MMMM d., EEEE",
	"dateFormatItem-MMMd": "MMM d.",
	"dateFormatItem-yyyyMd": "G y.MM.dd.",
	"dateFormatItem-Ed": "d., E"
}
//end v1.x content
);