define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y G",
	"dateFormatItem-yQ": "Q y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-MMMdd": "dd-MMM",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y G",
	"dateFormatItem-yyyyMM": "MM/y G",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d/MM",
	"dateFormatItem-yyMM": "MM/y G",
	"dateFormat-medium": "dd/MM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM-y G",
	"dateFormatItem-yMd": "d/M/y G",
	"dateFormatItem-yyQQQQ": "QQQQ 'de' y G",
	"dateFormatItem-yMMMM": "MMMM 'de' y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q y G",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y G",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-yMMMEd": "E, d MMM y G",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);