define(
//begin v1.x content
{
	"dateFormatItem-GyMMM": "M-y",
	"dateFormat-medium": "d-M-y",
	"dateFormatItem-MMMEd": "E d-M",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-yyyyMMM": "M-y",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-H": "HH",
	"dateFormatItem-GyMMMd": "d-M-y",
	"dateFormatItem-y": "y",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yyyyQQQQ": "QQQQ y",
	"dateFormatItem-GyMMMEd": "E, d-M-y",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "E, d-M-y",
	"dateFormatItem-yyyyMEd": "E, d-M-y",
	"dateFormatItem-yyyyMMMM": "M-y",
	"dateFormatItem-yyyy": "y",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "d-M-y",
	"dateFormatItem-yyyyQQQ": "QQQ y",
	"dateFormatItem-ms": "mm:ss",
	"dateFormat-short": "d-M-y",
	"dateFormatItem-Gy": "y",
	"dateFormatItem-d": "d",
	"dateFormatItem-yyyyMMMd": "d-M-y",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-yyyyM": "M-y",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMM": "L",
	"dateFormat-full": "EEEE, d-M-y",
	"dateFormatItem-MMMd": "d-M",
	"dateFormatItem-yyyyMd": "d-M-y",
	"dateFormatItem-Ed": "E d"
}
//end v1.x content
);