// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"peseta andorrana",
	AED_displayName:"dírham de los Emiratos Árabes Unidos",
	AFA_displayName:"afgani (1927-2002)",
	AFN_displayName:"afgani",
	AFN_symbol:"Af",
	ALL_displayName:"lek albanés",
	ALL_symbol:"lek",
	AMD_displayName:"dram armenio",
	AMD_symbol:"dram",
	ANG_displayName:"florín de las Antillas Neerlandesas",
	ANG_symbol:"NA f.",
	AOA_displayName:"kwanza angoleño",
	AOK_displayName:"kwanza angoleño (1977-1990)",
	AON_displayName:"nuevo kwanza angoleño (1990-2000)",
	AOR_displayName:"kwanza reajustado angoleño (1995-1999)",
	ARA_displayName:"austral argentino",
	ARP_displayName:"peso argentino (1983-1985)",
	ARS_displayName:"peso argentino",
	ARS_symbol:"Arg$",
	ATS_displayName:"chelín austriaco",
	AUD_displayName:"dólar australiano",
	AUD_symbol:"$A",
	AWG_displayName:"florín de Aruba",
	AZM_displayName:"manat azerí (1993-2006)",
	AZN_displayName:"manat azerí",
	BAD_displayName:"dinar bosnio",
	BAM_displayName:"marco convertible de Bosnia-Herzegovina",
	BAM_symbol:"KM",
	BBD_displayName:"dólar de Barbados",
	BBD_symbol:"BDS$",
	BDT_displayName:"taka de Bangladesh",
	BDT_symbol:"Tk",
	BEC_displayName:"franco belga (convertible)",
	BEF_displayName:"franco belga",
	BEF_symbol:"BF",
	BEL_displayName:"franco belga (financiero)",
	BGL_displayName:"lev fuerte búlgaro",
	BGL_symbol:"lev",
	BGN_displayName:"nuevo lev búlgaro",
	BHD_displayName:"dinar bahreiní",
	BHD_symbol:"BD",
	BIF_displayName:"franco de Burundi",
	BIF_symbol:"Fbu",
	BMD_displayName:"dólar de Bermudas",
	BMD_symbol:"Ber$",
	BND_displayName:"dólar de Brunéi",
	BOB_displayName:"boliviano",
	BOB_symbol:"Bs",
	BOP_displayName:"peso boliviano",
	BOV_displayName:"MVDOL boliviano",
	BRB_displayName:"nuevo cruceiro brasileño (1967-1986)",
	BRC_displayName:"cruzado brasileño",
	BRE_displayName:"cruceiro brasileño (1990-1993)",
	BRL_displayName:"real brasileño",
	BRN_displayName:"nuevo cruzado brasileño",
	BRR_displayName:"cruceiro brasileño",
	BSD_displayName:"dólar de las Bahamas",
	BTN_displayName:"ngultrum butanés",
	BTN_symbol:"Nu",
	BUK_displayName:"kyat birmano",
	BWP_displayName:"pula botsuano",
	BYB_displayName:"nuevo rublo bielorruso (1994-1999)",
	BYR_displayName:"rublo bielorruso",
	BYR_symbol:"Rbl",
	BZD_displayName:"dólar de Belice",
	BZD_symbol:"BZ$",
	CAD_displayName:"dólar canadiense",
	CAD_symbol:"Can$",
	CDF_displayName:"franco congoleño",
	CHE_displayName:"euro WIR",
	CHF_displayName:"franco suizo",
	CHF_symbol:"SwF",
	CHW_displayName:"franco WIR",
	CLF_displayName:"unidad de fomento chilena",
	CLP_displayName:"peso chileno",
	CLP_symbol:"Ch$",
	CNY_displayName:"yuan renminbi chino",
	CNY_symbol:"Y",
	COP_displayName:"peso colombiano",
	COP_symbol:"Col$",
	COU_displayName:"unidad de valor real colombiana",
	CRC_displayName:"colón costarricense",
	CRC_symbol:"C",
	CSD_displayName:"antiguo dinar serbio",
	CSK_displayName:"corona fuerte checoslovaca",
	CUP_displayName:"peso cubano",
	CVE_displayName:"escudo de Cabo Verde",
	CVE_symbol:"CVEsc",
	CYP_displayName:"libra chipriota",
	CYP_symbol:"£C",
	CZK_displayName:"corona checa",
	DDM_displayName:"ostmark de Alemania del Este",
	DEM_displayName:"marco alemán",
	DJF_displayName:"franco de Yibuti",
	DJF_symbol:"DF",
	DKK_displayName:"corona danesa",
	DKK_symbol:"DKr",
	DOP_displayName:"peso dominicano",
	DOP_symbol:"RD$",
	DZD_displayName:"dinar argelino",
	DZD_symbol:"DA",
	ECS_displayName:"sucre ecuatoriano",
	ECV_displayName:"unidad de valor constante (UVC) ecuatoriana",
	EEK_displayName:"corona estonia",
	EGP_displayName:"libra egipcia",
	EQE_displayName:"ekuele",
	ERN_displayName:"nakfa eritreo",
	ESA_displayName:"peseta española (cuenta A)",
	ESB_displayName:"peseta española (cuenta convertible)",
	ESP_displayName:"peseta española",
	ESP_symbol:"₧",
	ETB_displayName:"birr etíope",
	ETB_symbol:"Br",
	EUR_displayName:"euro",
	FIM_displayName:"marco finlandés",
	FJD_displayName:"dólar de las Islas Fiyi",
	FJD_symbol:"F$",
	FKP_displayName:"libra de las Islas Malvinas",
	FRF_displayName:"franco francés",
	GBP_displayName:"libra esterlina británica",
	GEK_displayName:"kupon larit georgiano",
	GEL_displayName:"lari georgiano",
	GEL_symbol:"lari",
	GHC_displayName:"cedi ghanés",
	GIP_displayName:"libra de Gibraltar",
	GMD_displayName:"dalasi gambiano",
	GNF_displayName:"franco guineano",
	GNF_symbol:"GF",
	GNS_displayName:"syli guineano",
	GQE_displayName:"ekuele de Guinea Ecuatorial",
	GRD_displayName:"dracma griego",
	GTQ_displayName:"quetzal guatemalteco",
	GTQ_symbol:"Q",
	GWE_displayName:"escudo de Guinea Portuguesa",
	GWP_displayName:"peso de Guinea-Bissáu",
	GYD_displayName:"dólar guyanés",
	GYD_symbol:"G$",
	HKD_displayName:"dólar de Hong Kong",
	HKD_symbol:"HK$",
	HNL_displayName:"lempira hondureño",
	HNL_symbol:"L",
	HRD_displayName:"dinar croata",
	HRK_displayName:"kuna croata",
	HTG_displayName:"gourde haitiano",
	HUF_displayName:"florín húngaro",
	HUF_symbol:"Ft",
	IDR_displayName:"rupia indonesia",
	IDR_symbol:"Rp",
	IEP_displayName:"libra irlandesa",
	IEP_symbol:"IR£",
	ILP_displayName:"libra israelí",
	ILS_displayName:"nuevo sheqel israelí",
	INR_displayName:"rupia india",
	IQD_displayName:"dinar iraquí",
	IQD_symbol:"ID",
	IRR_displayName:"rial iraní",
	IRR_symbol:"RI",
	ISK_displayName:"corona islandesa",
	ITL_displayName:"lira italiana",
	JMD_displayName:"dólar de Jamaica",
	JMD_symbol:"J$",
	JOD_displayName:"dinar jordano",
	JOD_symbol:"JD",
	JPY_displayName:"yen japonés",
	KES_displayName:"chelín keniata",
	KES_symbol:"K Sh",
	KGS_displayName:"som kirguís",
	KGS_symbol:"som",
	KHR_displayName:"riel camboyano",
	KHR_symbol:"CR",
	KMF_displayName:"franco comorense",
	KMF_symbol:"CF",
	KPW_displayName:"won norcoreano",
	KRW_displayName:"won surcoreano",
	KWD_displayName:"dinar kuwaití",
	KWD_symbol:"KD",
	KYD_displayName:"dólar de las Islas Caimán",
	KZT_displayName:"tenge kazako",
	KZT_symbol:"T",
	LAK_displayName:"kip laosiano",
	LBP_displayName:"libra libanesa",
	LBP_symbol:"LL",
	LKR_displayName:"rupia de Sri Lanka",
	LKR_symbol:"SL Re",
	LRD_displayName:"dólar liberiano",
	LSL_displayName:"loti lesothense",
	LSL_symbol:"M",
	LSM_displayName:"maloti",
	LTL_displayName:"litas lituano",
	LTT_displayName:"talonas lituano",
	LUC_displayName:"franco convertible luxemburgués",
	LUF_displayName:"franco luxemburgués",
	LUL_displayName:"franco financiero luxemburgués",
	LVL_displayName:"lats letón",
	LVR_displayName:"rublo letón",
	LYD_displayName:"dinar libio",
	LYD_symbol:"LD",
	MAD_displayName:"dirham marroquí",
	MAF_displayName:"franco marroquí",
	MDL_displayName:"leu moldavo",
	MGA_displayName:"ariary malgache",
	MGF_displayName:"franco malgache",
	MKD_displayName:"dinar macedonio",
	MKD_symbol:"MDen",
	MLF_displayName:"franco malí",
	MMK_displayName:"kyat de Myanmar",
	MNT_displayName:"tugrik mongol",
	MNT_symbol:"Tug",
	MOP_displayName:"pataca de Macao",
	MRO_displayName:"ouguiya mauritano",
	MRO_symbol:"UM",
	MTL_displayName:"lira maltesa",
	MTL_symbol:"Lm",
	MTP_displayName:"libra maltesa",
	MUR_displayName:"rupia mauriciana",
	MVR_displayName:"rufiyaa de Maldivas",
	MWK_displayName:"kwacha de Malawi",
	MWK_symbol:"MK",
	MXN_displayName:"peso mexicano",
	MXN_symbol:"MEX$",
	MXP_displayName:"peso de plata mexicano (1861-1992)",
	MXV_displayName:"unidad de inversión (UDI) mexicana",
	MYR_displayName:"ringgit malasio",
	MYR_symbol:"RM",
	MZE_displayName:"escudo mozambiqueño",
	MZM_displayName:"antiguo metical mozambiqueño",
	MZM_symbol:"Mt",
	MZN_displayName:"metical mozambiqueño",
	NAD_displayName:"dólar de Namibia",
	NAD_symbol:"N$",
	NGN_displayName:"naira nigeriano",
	NIC_displayName:"córdoba nicaragüense",
	NIO_displayName:"córdoba oro nicaragüense",
	NIO_symbol:"C$",
	NLG_displayName:"florín neerlandés",
	NOK_displayName:"corona noruega",
	NOK_symbol:"NKr",
	NPR_displayName:"rupia nepalesa",
	NPR_symbol:"Nrs",
	NZD_displayName:"dólar neozelandés",
	NZD_symbol:"$NZ",
	OMR_displayName:"rial omaní",
	OMR_symbol:"RO",
	PAB_displayName:"balboa panameño",
	PEI_displayName:"inti peruano",
	PEN_displayName:"nuevo sol peruano",
	PES_displayName:"sol peruano",
	PGK_displayName:"kina de Papúa Nueva Guinea",
	PHP_displayName:"peso filipino",
	PKR_displayName:"rupia pakistaní",
	PKR_symbol:"Pra",
	PLN_displayName:"zloty polaco",
	PLN_symbol:"Zl",
	PLZ_displayName:"zloty polaco (1950-1995)",
	PTE_displayName:"escudo portugués",
	PYG_displayName:"guaraní paraguayo",
	QAR_displayName:"riyal de Qatar",
	QAR_symbol:"QR",
	RHD_displayName:"dólar rodesiano",
	ROL_displayName:"antiguo leu rumano",
	ROL_symbol:"leu",
	RON_displayName:"leu rumano",
	RSD_displayName:"dinar serbio",
	RUB_displayName:"rublo ruso",
	RUR_displayName:"rublo ruso (1991-1998)",
	RWF_displayName:"franco ruandés",
	SAR_displayName:"riyal saudí",
	SAR_symbol:"SRl",
	SBD_displayName:"dólar de las Islas Salomón",
	SBD_symbol:"SI$",
	SCR_displayName:"rupia de Seychelles",
	SCR_symbol:"SR",
	SDD_displayName:"dinar sudanés",
	SDP_displayName:"libra sudanesa",
	SEK_displayName:"corona sueca",
	SEK_symbol:"SKr",
	SGD_displayName:"dólar singapurense",
	SGD_symbol:"S$",
	SHP_displayName:"libra de Santa Elena",
	SIT_displayName:"tólar esloveno",
	SKK_displayName:"corona eslovaca",
	SKK_symbol:"Sk",
	SLL_displayName:"leone de Sierra Leona",
	SOS_displayName:"chelín somalí",
	SOS_symbol:"S",
	SRD_displayName:"dólar surinamés",
	SRG_displayName:"florín surinamés",
	SRG_symbol:"Sf",
	STD_displayName:"dobra de Santo Tomé y Príncipe",
	STD_symbol:"Db",
	SUR_displayName:"rublo soviético",
	SVC_displayName:"colón salvadoreño",
	SYP_displayName:"libra siria",
	SYP_symbol:"LS",
	SZL_displayName:"lilangeni suazi",
	SZL_symbol:"E",
	THB_displayName:"baht tailandés",
	TJR_displayName:"rublo tayiko",
	TJS_displayName:"somoni tayiko",
	TMM_displayName:"manat turcomano",
	TND_displayName:"dinar tunecino",
	TOP_displayName:"paʻanga tongano",
	TOP_symbol:"T$",
	TPE_displayName:"escudo timorense",
	TRL_displayName:"lira turca antigua",
	TRL_symbol:"TL",
	TRY_displayName:"nueva lira turca",
	TTD_displayName:"dólar de Trinidad y Tobago",
	TTD_symbol:"TT$",
	TWD_displayName:"nuevo dólar taiwanés",
	TWD_symbol:"NT$",
	TZS_displayName:"chelín tanzano",
	TZS_symbol:"T Sh",
	UAH_displayName:"grivna ucraniana",
	UAK_displayName:"karbovanet ucraniano",
	UGS_displayName:"chelín ugandés (1966-1987)",
	UGX_displayName:"chelín ugandés",
	UGX_symbol:"U Sh",
	USD_displayName:"dólar estadounidense",
	USN_displayName:"dólar estadounidense (día siguiente)",
	USS_displayName:"dólar estadounidense (mismo día)",
	UYI_displayName:"peso uruguayo en unidades indexadas",
	UYP_displayName:"peso uruguayo (1975-1993)",
	UYU_displayName:"peso uruguayo",
	UYU_symbol:"Ur$",
	UZS_displayName:"sum uzbeko",
	VEB_displayName:"bolívar venezolano",
	VEB_symbol:"Be",
	VEF_displayName:"bolívar fuerte venezolano",
	VEF_symbol:"BsF",
	VND_displayName:"dong vietnamita",
	VUV_displayName:"vatu vanuatuense",
	VUV_symbol:"VT",
	WST_displayName:"tala samoano",
	XAF_displayName:"franco CFA BEAC",
	XAG_displayName:"plata",
	XAU_displayName:"oro",
	XBA_displayName:"unidad compuesta europea",
	XBB_displayName:"unidad monetaria europea",
	XBC_displayName:"unidad de cuenta europea (XBC)",
	XBD_displayName:"unidad de cuenta europea (XBD)",
	XCD_displayName:"dólar del Caribe Oriental",
	XCD_symbol:"EC$",
	XDR_displayName:"derechos especiales de giro",
	XEU_displayName:"unidad de moneda europea",
	XFO_displayName:"franco oro francés",
	XFU_displayName:"franco UIC francés",
	XOF_displayName:"franco CFA BCEAO",
	XPD_displayName:"paladio",
	XPF_displayName:"franco CFP",
	XPF_symbol:"CFPF",
	XPT_displayName:"platino",
	XRE_displayName:"fondos RINET",
	XTS_displayName:"código reservado para pruebas",
	XXX_displayName:"Sin divisa",
	YDD_displayName:"dinar yemení",
	YER_displayName:"rial yemení",
	YER_symbol:"YRl",
	YUD_displayName:"dinar fuerte yugoslavo",
	YUM_displayName:"super dinar yugoslavo",
	YUN_displayName:"dinar convertible yugoslavo",
	ZAL_displayName:"rand sudafricano (financiero)",
	ZAR_displayName:"rand sudafricano",
	ZAR_symbol:"R",
	ZMK_displayName:"kwacha zambiano",
	ZRN_displayName:"nuevo zaire zaireño",
	ZRZ_displayName:"zaire zaireño",
	ZWD_displayName:"dólar de Zimbabue",
	ZWD_symbol:"Z$"
})
                 