define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d 'de' MMMM 'de' y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-MMMdd": "dd-MMM",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM 'de' y G",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd/MM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ 'de' y G",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E, d/M/y GGGGG",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E, d 'de' MMMM 'de' y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);