define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "periodo del día",
	"dayPeriods-format-wide-pm": "p.m.",
	"dateFormatItem-yQ": "Q y",
	"field-minute": "minuto",
	"eraNames": [
		"antes de Cristo",
		"anno Dómini"
	],
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "ayer",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "antes de ayer",
	"field-weekday": "día de la semana",
	"field-day-relative+-3": "Hace tres días",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"E",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-format-wide-am": "a.m.",
	"field-era": "era",
	"field-hour": "hora",
	"dateFormatItem-y": "y",
	"dateFormatItem-MMMdd": "dd-MMM",
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "hoy",
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"M",
		"J",
		"V",
		"S"
	],
	"field-day-relative+1": "mañana",
	"eraAbbr": [
		"a.C.",
		"d.C."
	],
	"field-day-relative+2": "pasado mañana",
	"field-day-relative+3": "Dentro de tres días",
	"dateFormatItem-yyyyMM": "MM/yyyy",
	"dateFormat-long": "d 'de' MMMM 'de' y",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-EEEd": "EEE d",
	"field-zone": "zona",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "dd/MM/yyyy",
	"dateFormatItem-yyMM": "MM/yy",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM-yy",
	"dateFormatItem-yyQQQQ": "QQQQ 'de' yy",
	"dateFormatItem-yMMMM": "MMMM 'de' y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "año",
	"field-week": "semana",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"ene",
		"feb",
		"mar",
		"abr",
		"may",
		"jun",
		"jul",
		"ago",
		"sep",
		"oct",
		"nov",
		"dic"
	],
	"timeFormat-short": "HH:mm",
	"field-month": "mes",
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"days-format-abbr": [
		"dom",
		"lun",
		"mar",
		"mié",
		"jue",
		"vie",
		"sáb"
	],
	"dateFormatItem-M": "L",
	"field-second": "segundo",
	"field-day": "día",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd/MM/yy",
	"dateFormatItem-yMMMEd": "EEE, d MMM y",
	"dateFormat-full": "EEEE d 'de' MMMM 'de' y",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "EEE d/M/y",
	"months-format-wide": [
		"enero",
		"febrero",
		"marzo",
		"abril",
		"mayo",
		"junio",
		"julio",
		"agosto",
		"septiembre",
		"octubre",
		"noviembre",
		"diciembre"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1er trimestre",
		"2º trimestre",
		"3er trimestre",
		"4º trimestre"
	],
	"days-format-wide": [
		"domingo",
		"lunes",
		"martes",
		"miércoles",
		"jueves",
		"viernes",
		"sábado"
	],
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);