define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "EEE, d MMM y G",
	"eraNames": [
		"AH"
	],
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-MMMdd": "dd-MMM",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-abbr": [
		"Muh.",
		"Saf.",
		"Rab. I",
		"Rab. II",
		"Jum. I",
		"Jum. II",
		"Raj.",
		"Sha.",
		"Ram.",
		"Shaw.",
		"Dhuʻl-Q.",
		"Dhuʻl-H."
	],
	"eraAbbr": [
		"AH"
	],
	"dateFormatItem-yyyyMMMM": "MMMM 'de' y G",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormatItem-EEEd": "EEE d",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-MMd": "d/MM",
	"dateFormatItem-yyMM": "MM/y G",
	"dateFormat-medium": "dd/MM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM-y G",
	"dateFormatItem-yyQQQQ": "QQQQ 'de' y G",
	"dateFormatItem-ms": "mm:ss",
	"months-standAlone-wide": [
		"Muharram",
		"Safar",
		"Rabiʻ I",
		"Rabiʻ II",
		"Jumada I",
		"Jumada II",
		"Rajab",
		"Shaʻban",
		"Ramadan",
		"Shawwal",
		"Dhuʻl-Qiʻdah",
		"Dhuʻl-Hijjah"
	],
	"dateFormatItem-yyyyMEd": "EEE d/M/y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q y G",
	"months-format-abbr": [
		"Muh.",
		"Saf.",
		"Rab. I",
		"Rab. II",
		"Jum. I",
		"Jum. II",
		"Raj.",
		"Sha.",
		"Ram.",
		"Shaw.",
		"Dhuʻl-Q.",
		"Dhuʻl-H."
	],
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E, d/M",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormat-full": "EEEE d 'de' MMMM 'de' y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyQ": "Q y G",
	"months-format-wide": [
		"Muharram",
		"Safar",
		"Rabiʻ I",
		"Rabiʻ II",
		"Jumada I",
		"Jumada II",
		"Rajab",
		"Shaʻban",
		"Ramadan",
		"Shawwal",
		"Dhuʻl-Qiʻdah",
		"Dhuʻl-Hijjah"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"eraNarrow": [
		"AH"
	],
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);