define(
//begin v1.x content
{
	"days-standAlone-short": [
		"нед",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"months-format-narrow": [
		"Я",
		"Ф",
		"М",
		"А",
		"М",
		"Ю",
		"Ю",
		"А",
		"С",
		"О",
		"Н",
		"Д"
	],
	"field-weekday": "Ден от седмицата",
	"dateFormatItem-yQQQ": "QQQ y 'г'.",
	"dateFormatItem-yMEd": "ccc, d.MM.y 'г'.",
	"dateFormatItem-GyMMMEd": "E, d MMM y Г",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"eraNarrow": [
		"пp. хp.",
		"сл. хр.."
	],
	"dateFormatItem-yMM": "MM.y",
	"days-format-short": [
		"нед",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"dateFormat-long": "d MMMM y 'г'.",
	"months-format-wide": [
		"януари",
		"февруари",
		"март",
		"април",
		"май",
		"юни",
		"юли",
		"август",
		"септември",
		"октомври",
		"ноември",
		"декември"
	],
	"dateTimeFormat-medium": "{1}, {0}",
	"dayPeriods-format-wide-pm": "следобед",
	"dateFormat-full": "EEEE, d MMMM y 'г'.",
	"dateFormatItem-Md": "dd.MM",
	"dayPeriods-format-abbr-am": "преди обяд",
	"dateFormatItem-yMd": "dd.MM.y",
	"dateFormatItem-yM": "MM.y",
	"field-era": "Eра",
	"months-standAlone-wide": [
		"Януари",
    "Февруари",
    "Март",
    "Април",
    "Май",
    "Юни",
    "Юли",
    "Август",
    "Септември",
    "Октомври",
    "Ноември",
    "Декември"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"1-и квартал",
		"2-и квартал",
		"3-и квартал",
		"4-и квартал"
	],
	"timeFormat-long": "H:mm:ss z",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yQQQQ": "QQQQ y 'г'.",
	"field-year": "Год",
	"dateFormatItem-MMdd": "dd.MM",
	"field-hour": "Час",
	"months-format-abbr": [
    "ян.",
    "февр.",
    "март",
    "апр.",
    "май",
    "юни",
    "юли",
    "авг.",
    "септ.",
    "окт.",
    "ноем.",
    "дек."
	],
	"timeFormat-full": "H:mm:ss zzzz",
	"dateFormatItem-E": "ccc",
	"field-day-relative+0": "Днес",
	"field-day-relative+1": "Утре",
	"dateFormatItem-GyMMMd": "d MMM y 'г'. G",
	"field-day-relative+2": "Вдругиден",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
    "Ян.",
    "Февр.",
    "Март",
    "Апр.",
    "Май",
    "Юни",
    "Юли",
    "Авг.",
    "Септ.",
    "Окт.",
    "Ноем.",
    "Дек."
	],
	"quarters-format-abbr": [
		"1-и кв.",
		"2-и кв.",
		"3-и кв.",
		"4-и кв."
	],
	"quarters-standAlone-wide": [
		"1-и квартал",
		"2-и квартал",
		"3-и квартал",
		"4-и квартал"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
    "Неделя",
    "Понеделник",
    "Вторник",
    "Сряда",
    "Четвъртък",
    "Петък",
    "Събота"
	],
	"dateFormatItem-yLLLL": "LLLL y",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"1-и кв.",
		"2-и кв.",
		"3-и кв.",
		"4-и кв."
	],
	"eraAbbr": [
		"np. xp.",
		"сл. xp."
	],
	"field-minute": "Минута",
	"field-dayperiod": "ПО/СО",
	"days-standAlone-abbr": [
		"Нед",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Вчера",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1}, {0}",
	"dayPeriods-format-narrow-am": "дп",
	"field-day-relative+-2": "Завчера",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateTimeFormat-full": "{1}, {0}",
	"dateFormatItem-yMMMM": "LLLL y",
	"field-day": "Ден",
	"days-format-wide": [
    "неделя",
    "понеделник",
    "вторник",
    "сряда",
    "четвъртък",
    "петък",
    "събота"
	],
	"field-zone": "Часова зона",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"Я",
		"Ф",
		"М",
		"А",
		"М",
		"Ю",
		"Ю",
		"А",
		"С",
		"О",
		"Н",
		"Д"
	],
	"field-year-relative+-1": "През изминалата година",
	"field-month-relative+-1": "Миналия месец",
	"dateFormatItem-hm": "h:mm a",
	"dayPeriods-format-abbr-pm": "следобед",
	"days-format-abbr": [
		"нед",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"dateFormatItem-yMMMd": "d MMM y 'г'.",
	"eraNames": [
		"np. Хр.",
		"cл. Хр."
	],
	"days-format-narrow": [
		"нед",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-standAlone-narrow": [
		"Н",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "Mесец",
	"dayPeriods-format-wide-am": "преди обяд",
	"dateFormat-short": "dd.MM.yy",
	"field-second": "Секунда",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"field-month-relative+0": "Този месец",
	"field-month-relative+1": "На следващия месец",
	"dateFormatItem-Ed": "ccc, d",
	"field-week": "Cедмица",
	"dateFormat-medium": "dd MMM y 'г'.",
	"field-year-relative+0": "Тази година",
	"field-week-relative+-1": "Последна седмица",
	"field-year-relative+1": "На следващата година",
	"dayPeriods-format-narrow-pm": "пп",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "LLL y G",
	"field-week-relative+0": "Тази седмица",
	"field-week-relative+1": "Следваща седмица"
}
//end v1.x content
);