define(
//begin v1.x content
{
	"field-sat-relative+0": "тази събота",
	"field-sat-relative+1": "следващата събота",
	"field-dayperiod": "пр.об./сл.об.",
	"field-sun-relative+-1": "миналата неделя",
	"field-mon-relative+-1": "миналият понеделник",
	"field-minute": "минута",
	"field-day-relative+-1": "вчера",
	"field-weekday": "ден от седмицата",
	"field-day-relative+-2": "онзи ден",
	"field-era": "ера",
	"field-hour": "час",
	"field-sun-relative+0": "тази неделя",
	"field-sun-relative+1": "следващата неделя",
	"field-wed-relative+-1": "миналата сряда",
	"field-day-relative+0": "днес",
	"field-day-relative+1": "утре",
	"field-day-relative+2": "вдругиден",
	"field-tue-relative+0": "този вторник",
	"field-zone": "часова зона",
	"field-tue-relative+1": "следващият вторник",
	"field-week-relative+-1": "миналата седмица",
	"field-year-relative+0": "тази година",
	"field-year-relative+1": "следващата година",
	"field-sat-relative+-1": "миналата събота",
	"field-year-relative+-1": "миналата година",
	"field-year": "година",
	"field-fri-relative+0": "този петък",
	"field-fri-relative+1": "следващият петък",
	"field-week": "седмица",
	"field-week-relative+0": "тази седмица",
	"field-week-relative+1": "следващата седмица",
	"field-month-relative+0": "този месец",
	"field-month": "месец",
	"field-month-relative+1": "следващият месец",
	"field-fri-relative+-1": "миналият петък",
	"field-second": "секунда",
	"field-tue-relative+-1": "миналият вторник",
	"field-day": "ден",
	"field-mon-relative+0": "този понеделник",
	"field-mon-relative+1": "следващият понеделник",
	"field-thu-relative+0": "този четвъртък",
	"field-second-relative+0": "сега",
	"field-thu-relative+1": "следващият четвъртък",
	"field-wed-relative+0": "тази сряда",
	"months-format-wide": [
		"чайтра",
		"вайсакха",
		"джаинтха",
		"асадха",
		"сравана",
		"бхада",
		"азвина",
		"картика",
		"аграхайана",
		"пауза",
		"магха",
		"пхалгуна"
	],
	"field-wed-relative+1": "следващата сряда",
	"field-month-relative+-1": "миналият месец",
	"field-thu-relative+-1": "миналият четвъртък"
}
//end v1.x content
);