define(
//begin v1.x content
{
	"field-thu-relative+1": "sisamanngorneq tulleq sapaatip-akunnera",
	"field-year-relative+-1": "kingulleq ukioq",
	"field-month-relative+-1": "kingulleq qaammat",
	"field-day-relative+-1": "ippassaq",
	"field-sat-relative+-1": "arfininngorneq kingulleq sapaatip-akunnera",
	"field-sun-relative+-1": "sapaat kingulleq sapaatip-akunnera",
	"field-day-relative+-2": "ippassaani",
	"field-tue-relative+-1": "marlunngorneq kingulleq sapaatip-akunnera",
	"field-sun-relative+0": "sapaat manna sapaatip-akunnera",
	"field-sun-relative+1": "sapaat tulleq sapaatip-akunnera",
	"field-week-relative+0": "manna sapaatip-akunnera",
	"field-fri-relative+-1": "tallimanngorneq kingulleq sapaatip-akunnera",
	"field-week-relative+1": "tulleq sapaatip-akunnera",
	"field-sat-relative+0": "arfininngorneq manna sapaatip-akunnera",
	"field-mon-relative+0": "ataasinngorneq manna sapaatip-akunnera",
	"field-thu-relative+-1": "sisamanngorneq kingulleq sapaatip-akunnera",
	"field-sat-relative+1": "arfininngorneq tulleq sapaatip-akunnera",
	"field-mon-relative+1": "ataasinngorneq tulleq sapaatip-akunnera",
	"field-week-relative+-1": "kingulleq sapaatip-akunnera",
	"field-day-relative+0": "ullumi",
	"field-day-relative+1": "aqagu",
	"field-day-relative+2": "aqaguagu",
	"field-mon-relative+-1": "ataasinngorneq kingulleq sapaatip-akunnera",
	"field-month-relative+0": "manna qaammat",
	"field-month-relative+1": "tulleq qaammat",
	"field-fri-relative+0": "tallimanngorneq manna sapaatip-akunnera",
	"field-wed-relative+-1": "pingasunngorneq kingulleq sapaatip-akunnera",
	"field-fri-relative+1": "tallimanngorneq tulleq sapaatip-akunnera",
	"field-year-relative+0": "manna ukioq",
	"field-year-relative+1": "tulleq ukioq",
	"field-wed-relative+0": "pingasunngorneq manna sapaatip-akunnera",
	"field-tue-relative+0": "marlunngorneq manna sapaatip-akunnera",
	"field-wed-relative+1": "pingasunngorneq tulleq sapaatip-akunnera",
	"field-tue-relative+1": "marlunngorneq tulleq sapaatip-akunnera",
	"field-thu-relative+0": "sisamanngorneq manna sapaatip-akunnera"
}
//end v1.x content
);