({
	"months-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"dateFormatItem-yQQQ": "y QQQ", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"dateFormatItem-MMMEd": "E MMM d", 
	"eraNarrow": [
		"BE"
	], 
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}", 
	"dayPeriods-pm-format-wide": "PM", 
	"dateFormat-long": "MMMM d, y G", 
	"months-format-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"dateFormatItem-EEEd": "EEE d", 
	"dateFormat-full": "EEEE, MMMM d, y G", 
	"dateFormatItem-Md": "M-d", 
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})", 
	"dayPeriods-pm-format-abbr": "PM", 
	"dateFormatItem-yM": "M/y", 
	"months-standAlone-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"timeFormat-short": "HH:mm", 
	"quarters-format-wide": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"dateTimeFormat": "{1} {0}", 
	"timeFormat-long": "HH:mm:ss z", 
	"dateFormatItem-yMMM": "MMM, y", 
	"dateFormatItem-yQ": "y Q", 
	"dateTimeFormats-appendItem-Era": "{0} {1}", 
	"months-format-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})", 
	"dateFormatItem-H": "HH", 
	"months-standAlone-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"quarters-standAlone-wide": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"dateFormatItem-M": "L", 
	"days-standAlone-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"dateFormatItem-MMMMd": "MMMM d", 
	"timeFormat-medium": "HH:mm:ss", 
	"dayPeriods-am-format-wide": "AM", 
	"dayPeriods-am-format-narrow": "AM", 
	"dateFormatItem-Hm": "HH:mm", 
	"quarters-standAlone-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"eraAbbr": [
		"BE"
	], 
	"days-standAlone-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"dateFormatItem-d": "d", 
	"dateFormatItem-ms": "mm:ss", 
	"quarters-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"dateFormatItem-h": "h a", 
	"dayPeriods-am-format-abbr": "AM", 
	"dateFormatItem-MMMd": "MMM d", 
	"dateFormatItem-MEd": "E, M-d", 
	"dateFormatItem-yMMMM": "MMMM, y", 
	"days-format-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})", 
	"dateFormatItem-y": "y", 
	"months-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"dateTimeFormats-appendItem-Year": "{0} {1}", 
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})", 
	"days-format-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"eraNames": [
		"BE"
	], 
	"days-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"days-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})", 
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})", 
	"dateFormatItem-MMMMEd": "E MMMM d", 
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})", 
	"dateFormat-short": "M/d/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateTimeFormats-appendItem-Timezone": "{0} {1}", 
	"dateFormat-medium": "MMM d, y G", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dayPeriods-pm-format-narrow": "PM"
})