// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
	'months-format-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-abbr@localeAlias':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-narrow@localeAlias':{'target':"months-standAlone-narrow",'bundle':"gregorian"},
	'months-format-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-abbr@localeAlias':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias':{'target':"months-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-abbr@localeAlias':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias':{'target':"days-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-abbr@localeAlias':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-narrow@localeAlias':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-wide@localeAlias':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias':{'target':"eraAbbr", 'bundle':"gregorian"},
	'eraNames':["BCE","CE"],
	'eraAbbr':["BCE","CE"],
	'eraNarrow@localeAlias':{'target':"eraAbbr", 'bundle':"gregorian"},
	'eraNarrow':["BCE","CE"],
	'dateFormat-full': "EEEE, yyyy MMMM dd",
	'dateFormat-long': "yyyy MMMM d",
	'dateFormat-medium': "yyyy MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeAvailableFormats':["H:mm","L","E, M-d","LLL","E MMM d","E MMMM d","MMMM d","MMM d","M-d","d","mm:ss","yyyy","yyyy-M","EEE, yyyy-M-d","yyyy MMM","EEE, yyyy MMM d","yyyy MMMM","yyyy Q","yyyy QQQ"],
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}",
	'field-era':"Era",
	'field-year':"Year",
	'field-month':"Month",
	'field-week':"Week",
	'field-day':"Day",
	'field-weekday':"Day of the Week",
	'field-dayperiod':"Dayperiod",
	'field-hour':"Hour",
	'field-minute':"Minute",
	'field-second':"Second",
	'field-zone':"Zone"
})
                        