({
	"months-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"dateFormatItem-yQQQ": "yyyy QQQ", 
	"field-weekday": "Day of the Week", 
	"dateFormatItem-yMEd": "EEE, yyyy-M-d", 
	"dateFormatItem-MMMEd": "E MMM d", 
	"eraNarrow": [
		"BCE", 
		"CE"
	], 
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}", 
	"dateFormat-long": "yyyy MMMM d", 
	"months-format-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"dateFormat-full": "EEEE, yyyy MMMM dd", 
	"dateFormatItem-Md": "M-d", 
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})", 
	"field-era": "Era", 
	"months-standAlone-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"timeFormat-short": "HH:mm", 
	"quarters-format-wide": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"timeFormat-long": "HH:mm:ss z", 
	"dateTimeFormats-appendItem-Era": "{0} {1}", 
	"field-year": "Year", 
	"months-format-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMM": "yyyy MMM", 
	"field-hour": "Hour", 
	"patternChars": "GyMdkHmsSEDFwWahKzYeugAZvcL", 
	"dateFormatItem-yQ": "yyyy Q", 
	"timeFormat-full": "HH:mm:ss v", 
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})", 
	"dateFormatItem-yM": "yyyy-M", 
	"am": "AM", 
	"months-standAlone-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"quarters-standAlone-wide": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"dateFormatItem-M": "L", 
	"days-standAlone-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"dateFormatItem-MMMMd": "MMMM d", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-Hm": "H:mm", 
	"eraAbbr": [
		"BCE", 
		"CE"
	], 
	"quarters-standAlone-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"field-minute": "Minute", 
	"days-standAlone-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"field-dayperiod": "Dayperiod", 
	"dateFormatItem-d": "d", 
	"dateFormatItem-ms": "mm:ss", 
	"quarters-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"dateFormatItem-MMMd": "MMM d", 
	"dateFormatItem-MEd": "E, M-d", 
	"dateFormatItem-yMMMM": "yyyy MMMM", 
	"field-day": "Day", 
	"days-format-wide": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"field-zone": "Zone", 
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})", 
	"dateFormatItem-y": "yyyy", 
	"months-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"dateTimeFormats-appendItem-Year": "{0} {1}", 
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})", 
	"days-format-abbr": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"eraNames": [
		"BCE", 
		"CE"
	], 
	"days-format-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"field-month": "Month", 
	"days-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})", 
	"pm": "PM", 
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})", 
	"dateFormatItem-MMMMEd": "E MMMM d", 
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})", 
	"dateFormat-short": "yyyy-MM-dd", 
	"field-second": "Second", 
	"dateFormatItem-yMMMEd": "EEE, yyyy MMM d", 
	"dateTimeFormats-appendItem-Timezone": "{0} {1}", 
	"field-week": "Week", 
	"dateFormat-medium": "yyyy MMM d"
})