// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-hebrew
({
    	"patternChars":"GyMdkHmsSEDFwWahKzYeugAZvcL",
	
	'months-format-abbr@localeAlias103':{'target':"months-format-wide",'bundle':"hebrew"},
	'months-format-abbr':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'months-format-narrow@localeAlias104':{'target':"months-standAlone-narrow",'bundle':"hebrew"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-format-wide':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'months-standAlone-abbr@localeAlias105':{'target':"months-format-abbr",'bundle':"hebrew"},
	'months-standAlone-abbr@localeAlias106':{'target':"months-format-wide",'bundle':"hebrew"},
	'months-standAlone-abbr':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-standAlone-wide@localeAlias107':{'target':"months-format-wide",'bundle':"hebrew"},
	'months-standAlone-wide':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'days@localeAlias108':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias109':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias110':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias111':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias112':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias113':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias114':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias115':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias116':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias117':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias118':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias119':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias120':{'target':"eraAbbr", 'bundle':"hebrew"},
	'eraNames':["AM"],
	'eraAbbr':["AM"],
	'eraNarrow@localeAlias121':{'target':"eraAbbr", 'bundle':"hebrew"},
	'eraNarrow':["AM"],
	'dateFormat@localeAlias122':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, yyyy MMMM dd",
	'dateFormat-long': "yyyy MMMM d",
	'dateFormat-medium': "yyyy MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias123':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias124':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-M':"L",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-d':"d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"yyyy",
	'dateFormatItem-yM':"yyyy-M",
	'dateFormatItem-yMEd':"EEE, yyyy-M-d",
	'dateFormatItem-yMMM':"yyyy MMM",
	'dateFormatItem-yMMMEd':"EEE, yyyy MMM d",
	'dateFormatItem-yMMMM':"yyyy MMMM",
	'dateFormatItem-yQ':"yyyy Q",
	'dateFormatItem-yQQQ':"yyyy QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        