// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-hebrew
({
	'months-format-abbr@localeAlias129':{'target':"months-format-wide",'bundle':"hebrew"},
	'months-format-abbr':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'months-format-narrow@localeAlias130':{'target':"months-standAlone-narrow",'bundle':"hebrew"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-format-wide':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'months-standAlone-abbr@localeAlias131':{'target':"months-format-abbr",'bundle':"hebrew"},
	'months-standAlone-abbr@localeAlias132':{'target':"months-format-wide",'bundle':"hebrew"},
	'months-standAlone-abbr':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-standAlone-wide@localeAlias133':{'target':"months-format-wide",'bundle':"hebrew"},
	'months-standAlone-wide':["Tishri","Heshvan","Kislev","Tevet","Shevat","Adar I","Adar","Nisan","Iyar","Sivan","Tamuz","Av","Elul"],
	'days@localeAlias134':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias135':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias136':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias137':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias138':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias139':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias140':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias141':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias142':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias143':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias144':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias145':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias146':{'target':"eraAbbr", 'bundle':"hebrew"},
	'eraNames':["AM"],
	'eraAbbr':["AM"],
	'eraNarrow@localeAlias147':{'target':"eraAbbr", 'bundle':"hebrew"},
	'eraNarrow':["AM"],
	'dateFormat@localeAlias148':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, y MMMM dd",
	'dateFormat-long': "y MMMM d",
	'dateFormat-medium': "y MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias149':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias150':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat-full': "{1} {0}" ,
	'dateTimeFormat-long': "{1} {0}" ,
	'dateTimeFormat-medium': "{1} {0}" ,
	'dateTimeFormat-short': "{1} {0}" ,
	'dateFormatItem-EEEd':"d EEE",
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-Hms':"H:mm:ss",
	'dateFormatItem-M':"L",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-d':"d",
	'dateFormatItem-hm':"h:mm a",
	'dateFormatItem-hms':"h:mm:ss a",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"y",
	'dateFormatItem-yM':"y-M",
	'dateFormatItem-yMEd':"EEE, y-M-d",
	'dateFormatItem-yMMM':"y MMM",
	'dateFormatItem-yMMMEd':"EEE, y MMM d",
	'dateFormatItem-yMMMM':"y MMMM",
	'dateFormatItem-yQ':"y Q",
	'dateFormatItem-yQQQ':"y QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        