// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-islamic-civil
({
	'*@localeAlias195':{'target':"*", 'bundle':"islamic"},
	'months-format-abbr@localeAlias196':{'target':"months-format-wide",'bundle':"islamic"},
	'months-format-abbr':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'months-format-narrow@localeAlias197':{'target':"months-standAlone-narrow",'bundle':"islamic"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'months-standAlone-abbr@localeAlias198':{'target':"months-format-abbr",'bundle':"islamic"},
	'months-standAlone-abbr@localeAlias199':{'target':"months-format-wide",'bundle':"islamic"},
	'months-standAlone-abbr':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias200':{'target':"months-format-wide",'bundle':"islamic"},
	'months-standAlone-wide':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'days@localeAlias201':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias202':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias203':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias204':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias205':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias206':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias207':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias208':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias209':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias210':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias211':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias212':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias213':{'target':"eraAbbr", 'bundle':"islamic"},
	'eraNames':["AH"],
	'eraAbbr':["AH"],
	'eraNarrow@localeAlias214':{'target':"eraAbbr", 'bundle':"islamic"},
	'eraNarrow':["AH"],
	'dateFormat@localeAlias215':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, y MMMM dd",
	'dateFormat-long': "y MMMM d",
	'dateFormat-medium': "y MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias216':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias217':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat-full': "{1} {0}" ,
	'dateTimeFormat-long': "{1} {0}" ,
	'dateTimeFormat-medium': "{1} {0}" ,
	'dateTimeFormat-short': "{1} {0}" ,
	'dateFormatItem-d':"d",
	'dateFormatItem-EEEd':"d EEE",
	'dateFormatItem-hm':"h:mm a",
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-hms':"h:mm:ss a",
	'dateFormatItem-Hms':"H:mm:ss",
	'dateFormatItem-M':"L",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"y",
	'dateFormatItem-yM':"y-M",
	'dateFormatItem-yMEd':"EEE, y-M-d",
	'dateFormatItem-yMMM':"y MMM",
	'dateFormatItem-yMMMEd':"EEE, y MMM d",
	'dateFormatItem-yMMMM':"y MMMM",
	'dateFormatItem-yQ':"y Q",
	'dateFormatItem-yQQQ':"y QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        