// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-islamic
({
    	"patternChars":"GyMdkHmsSEDFwWahKzYeugAZvcL",
	
	'months-format-abbr@localeAlias147':{'target':"months-format-wide",'bundle':"islamic"},
	'months-format-abbr':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'months-format-narrow@localeAlias148':{'target':"months-standAlone-narrow",'bundle':"islamic"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'months-standAlone-abbr@localeAlias149':{'target':"months-format-abbr",'bundle':"islamic"},
	'months-standAlone-abbr@localeAlias150':{'target':"months-format-wide",'bundle':"islamic"},
	'months-standAlone-abbr':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias151':{'target':"months-format-wide",'bundle':"islamic"},
	'months-standAlone-wide':["Muharram","Safar","Rabiʻ I","Rabiʻ II","Jumada I","Jumada II","Rajab","Shaʻban","Ramadan","Shawwal","Dhuʻl-Qiʻdah","Dhuʻl-Hijjah"],
	'days@localeAlias152':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias153':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias154':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias155':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias156':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias157':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias158':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias159':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias160':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias161':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias162':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias163':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias164':{'target':"eraAbbr", 'bundle':"islamic"},
	'eraNames':["AH"],
	'eraAbbr':["AH"],
	'eraNarrow@localeAlias165':{'target':"eraAbbr", 'bundle':"islamic"},
	'eraNarrow':["AH"],
	'dateFormat@localeAlias166':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, yyyy MMMM dd",
	'dateFormat-long': "yyyy MMMM d",
	'dateFormat-medium': "yyyy MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias167':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias168':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-M':"L",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-d':"d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"yyyy",
	'dateFormatItem-yM':"yyyy-M",
	'dateFormatItem-yMEd':"EEE, yyyy-M-d",
	'dateFormatItem-yMMM':"yyyy MMM",
	'dateFormatItem-yMMMEd':"EEE, yyyy MMM d",
	'dateFormatItem-yMMMM':"yyyy MMMM",
	'dateFormatItem-yQ':"yyyy Q",
	'dateFormatItem-yQQQ':"yyyy QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        