define({ root: 
//begin v1.x content
// generated from ldml/main/*.xml, xpath: ldml/numbers
({
	'decimal':".",
	'group':",",
	'list':";",
	'percentSign':"%",
	'nativeZeroDigit':"0",
	'patternDigit':"#",
	'plusSign':"+",
	'minusSign':"-",
	'exponential':"E",
	'perMille':"‰",
	'infinity':"∞",
	'nan':"NaN",
	'decimalFormat':"#,##0.###",
	'scientificFormat':"#E0",
	'percentFormat':"#,##0%",
	'currencySpacing-beforeCurrency-currencyMatch':"[:letter:]",
	'currencySpacing-beforeCurrency-surroundingMatch':"[:digit:]",
	'currencySpacing-beforeCurrency-insertBetween':" ",
	'currencySpacing-afterCurrency-currencyMatch':"[:letter:]",
	'currencySpacing-afterCurrency-surroundingMatch':"[:digit:]",
	'currencySpacing-afterCurrency-insertBetween':" ",
	'currencyFormat':"¤ #,##0.00"
})
//end v1.x content
,
"zh": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"ja": true,
"it": true,
"hu": true,
"he": true,
"fr": true,
"fi": true,
"es": true,
"en": true,
"en-gb": true,
"en-au": true,
"el": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"ar": true
});
