define("i18n!dojo/cldr/nls/number", { root: 
//begin v1.x content
// generated from ldml/main/*.xml, xpath: ldml/numbers
({
	'decimal':".",
	'group':",",
	'list':";",
	'percentSign':"%",
	'nativeZeroDigit':"0",
	'patternDigit':"#",
	'plusSign':"+",
	'minusSign':"-",
	'exponential':"E",
	'perMille':"‰",
	'infinity':"∞",
	'nan':"NaN",
	'decimalFormat':"#,##0.###",
	'scientificFormat':"#E0",
	'percentFormat':"#,##0%",
	'currencySpacing-beforeCurrency-currencyMatch':"[:letter:]",
	'currencySpacing-beforeCurrency-surroundingMatch':"[:digit:]",
	'currencySpacing-beforeCurrency-insertBetween':" ",
	'currencySpacing-afterCurrency-currencyMatch':"[:letter:]",
	'currencySpacing-afterCurrency-surroundingMatch':"[:digit:]",
	'currencySpacing-afterCurrency-insertBetween':" ",
	'currencyFormat':"¤ #,##0.00"
})
//end v1.x content
,
"zh":1,
"tr":1,
"th":1,
"sv":1,
"sl":1,
"sk":1,
"ru":1,
"pt":1,
"pt-pt":1,
"pl":1,
"nl":1,
"nb":1,
"ko":1,
"ja":1,
"it":1,
"hu":1,
"he":1,
"fr":1,
"fi":1,
"es":1,
"en":1,
"en-gb":1,
"en-au":1,
"el":1,
"de":1,
"da":1,
"cs":1,
"ca":1,
"ar":1
});
