// generated from ldml/main/*.xml, xpath: ldml/numbers
({
        'decimal':".",
        'group':",",
        'list':";",
        'percentSign':"%",
        'nativeZeroDigit':"0",
        'patternDigit':"#",
        'plusSign':"+",
        'minusSign':"-",
        'exponential':"E",
        'perMille':"‰",
        'infinity':"∞",
        'nan':"NaN",
        'decimalFormat':"#,##0.###",
        'scientificFormat':"#E0",
        'percentFormat':"#,##0%",
        'currencySpacing-beforeCurrency-currencyMatch':"[:letter:]",
        'currencySpacing-beforeCurrency-surroundingMatch':"[:digit:]",
        'currencySpacing-beforeCurrency-insertBetween':" ",
        'currencySpacing-afterCurrency-currencyMatch':"[:letter:]",
        'currencySpacing-afterCurrency-surroundingMatch':"[:digit:]",
        'currencySpacing-afterCurrency-insertBetween':" ",
        'currencyFormat':"¤ #,##0.00"
})
