define(
//begin v1.x content
{
	"HNL_displayName": "Гондурас лемпираси",
	"UZS_symbol": "сўм",
	"BMD_displayName": "Бермуда доллари",
	"USD_displayName": "АҚШ доллари",
	"BBD_displayName": "Барбадос доллари",
	"MAD_displayName": "Марокаш дирҳами",
	"XAF_symbol": "FCFA",
	"XOF_symbol": "CFA",
	"VND_symbol": "₫",
	"JPY_symbol": "JP¥",
	"JMD_displayName": "Ямайка доллари",
	"HTG_displayName": "Гаити гурдаси",
	"EGP_displayName": "Миср фунти",
	"LYD_displayName": "Ливия динори",
	"USD_symbol": "US$",
	"CUP_displayName": "Куба песоси",
	"CAD_displayName": "Канада доллари",
	"KRW_symbol": "₩",
	"INR_displayName": "Ҳинд рупияси",
	"GYD_displayName": "Гаяна доллари",
	"THB_symbol": "฿",
	"VEF_displayName": "Венесуэла боливари",
	"JPY_displayName": "Япон йенаси",
	"AWG_displayName": "Аруба флорини",
	"MXN_displayName": "Мексика песоси",
	"HKD_symbol": "HK$",
	"CUC_displayName": "Куба Айирбошлаш песоси",
	"PEN_displayName": "Перу нуево сол",
	"DZD_displayName": "Жазоир динори",
	"XCD_symbol": "EC$",
	"GBP_symbol": "£",
	"CNY_symbol": "CN¥",
	"UZS_displayName": "Ўзбекистон сўм",
	"CRC_displayName": "Коста-Рика колони",
	"AUD_symbol": "A$",
	"ILS_symbol": "₪",
	"ARS_displayName": "Аргентина песоси",
	"COP_displayName": "Колумбия песоси",
	"EUR_symbol": "€",
	"BZD_displayName": "Белиз доллари",
	"EUR_displayName": "Евро",
	"CAD_symbol": "CA$",
	"GBP_displayName": "Инглиз фунт стерлинги",
	"PYG_displayName": "Парагвай гуарани",
	"FKP_displayName": "Фолькленд ороли фунти",
	"PAB_displayName": "Панама бальбоаси",
	"NZD_symbol": "NZ$",
	"BSD_displayName": "Багама доллари",
	"TWD_symbol": "NT$",
	"XPF_symbol": "CFPF",
	"INR_symbol": "₹",
	"CLP_displayName": "Чили песоси",
	"UYU_displayName": "Уругвай песоси",
	"GTQ_displayName": "Гватемала кветзали",
	"BRL_displayName": "Бразил реали",
	"KYD_displayName": "Кайман ороли Доллари",
	"ANG_displayName": "Голланд Антил гульдени",
	"RUB_displayName": "Рус рубли",
	"XCD_displayName": "Шарқий Кариб доллари",
	"NIO_displayName": "Никарагуа кордобаси",
	"MXN_symbol": "MX$",
	"BRL_symbol": "R$",
	"TTD_displayName": "Тринидад ва Тобаго доллари",
	"DOP_displayName": "Доминикан песоси",
	"CNY_displayName": "Хитой юани",
	"BOB_displayName": "Боливия болвиани",
	"SRD_displayName": "Суринам доллари"
}
//end v1.x content
);