define(
//begin v1.x content
{
	"field-second-relative+0": "ҳозир",
	"field-weekday": "Ҳафта куни",
	"field-wed-relative+0": "this Wednesday",
	"field-wed-relative+1": "кейинги чоршанба",
	"dateFormatItem-GyMMMEd": "G y MMM d, E",
	"dateFormatItem-MMMEd": "MMM d, E",
	"field-tue-relative+-1": "ўтган сешанба",
	"dateFormat-long": "G y MMMM d",
	"field-fri-relative+-1": "ўтган жума",
	"field-wed-relative+-1": "ўтган чоршанба",
	"dateFormatItem-yyyyQQQ": "G y QQQ",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE, G y MMMM dd",
	"dateFormatItem-yyyyMEd": "GGGGG y-MM-dd, E",
	"field-thu-relative+-1": "ўтган пайшанба",
	"dateFormatItem-Md": "MM-dd",
	"field-era": "Эра",
	"field-year": "Йил",
	"field-hour": "Соат",
	"field-sat-relative+0": "бу шанба",
	"field-sat-relative+1": "кейинги шанба",
	"field-day-relative+0": "бугун",
	"field-thu-relative+0": "бу пайшанба",
	"field-day-relative+1": "эртага",
	"field-thu-relative+1": "кейинги пайшанба",
	"dateFormatItem-GyMMMd": "G y MMM d",
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-yyyyMMMEd": "G y MMM d, E",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "G y MMM",
	"dateFormatItem-yyyyMMMd": "G y MMM d",
	"field-sun-relative+0": "бу якшанба",
	"field-sun-relative+1": "кейинги якшанба",
	"field-minute": "Дақиқа",
	"field-dayperiod": "Кун вақти",
	"dateFormatItem-d": "d",
	"field-day-relative+-1": "кеча",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "бу жума",
	"field-fri-relative+1": "кейинги жума",
	"field-day": "Кун",
	"field-zone": "Минтақа",
	"dateFormatItem-y": "G y",
	"field-year-relative+-1": "ўтган йил",
	"field-month-relative+-1": "ўтган ой",
	"dateFormatItem-yyyyMd": "GGGGG y-MM-dd",
	"field-month": "Ой",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "бу сешанба",
	"field-tue-relative+1": "кейинги сешанба",
	"field-mon-relative+0": "бу душанба",
	"field-mon-relative+1": "кейинги душанба",
	"dateFormat-short": "GGGGG y/MM/dd",
	"field-second": "Сония",
	"field-sat-relative+-1": "ўтган шанба",
	"field-sun-relative+-1": "ўтган якшанба",
	"field-month-relative+0": "бу ой",
	"field-month-relative+1": "кейинги ой",
	"dateFormatItem-Ed": "d, E",
	"field-week": "Ҳафта",
	"dateFormat-medium": "G y MMM d",
	"field-year-relative+0": "бу йил",
	"field-week-relative+-1": "ўтган ҳафта",
	"dateFormatItem-yyyyM": "GGGGG y-MM",
	"field-year-relative+1": "кейинги йил",
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-GyMMM": "G y MMM",
	"field-mon-relative+-1": "ўтган душанба",
	"dateFormatItem-yyyy": "G y",
	"field-week-relative+0": "бу ҳафта",
	"field-week-relative+1": "кейинги ҳафта"
}
//end v1.x content
);