define(
//begin v1.x content
{
	"field-second-relative+0": "sasa",
	"field-weekday": "Siku ya wiki",
	"field-wed-relative+0": "Jumatano hii",
	"field-wed-relative+1": "Jumatano ijayo",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-tue-relative+-1": "Jumanne iliyopita",
	"dateFormat-long": "d MMMM y G",
	"field-fri-relative+-1": "Ijumaa iliyopita",
	"field-wed-relative+-1": "Jumatano iliyopita",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-yyyyMEd": "E, d/M/y G",
	"field-thu-relative+-1": "Alhamisi iliyopita",
	"dateFormatItem-Md": "d-M",
	"field-era": "Enzi",
	"field-year": "Mwaka",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"field-hour": "Saa",
	"field-sat-relative+0": "Jumamosi hii",
	"field-sat-relative+1": "Jumamosi ijayo",
	"field-day-relative+0": "leo",
	"field-day-relative+1": "kesho",
	"field-thu-relative+0": "Alhamisi hii",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-day-relative+2": "kesho kutwa",
	"field-thu-relative+1": "Alhamisi ijayo",
	"dateFormatItem-H": "HH",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-sun-relative+0": "Jumapili hii",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "Jumapili ijayo",
	"field-minute": "Dakika",
	"field-dayperiod": "Muda wa siku",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "jana",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "juzi",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d/M",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "Ijumaa hii",
	"field-fri-relative+1": "Ijumaa ijayo",
	"field-day": "Siku",
	"field-zone": "Majira ya saa",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "mwaka uliopita",
	"field-month-relative+-1": "mwezi uliopita",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"field-month": "Mwezi",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "Jumanne hii",
	"field-tue-relative+1": "Jumanne ijayo",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"field-mon-relative+0": "Jumatatu hii",
	"field-mon-relative+1": "Jumatatu ijayo",
	"dateFormat-short": "dd/MM/y GGGGG",
	"field-second": "Sekunde",
	"field-sat-relative+-1": "Jumamosi iliyopita",
	"field-sun-relative+-1": "Jumapili iliyopita",
	"field-month-relative+0": "mwezi huu",
	"field-month-relative+1": "mwezi ujao",
	"dateFormatItem-Ed": "d E",
	"field-week": "Wiki",
	"dateFormat-medium": "d MMM y G",
	"field-year-relative+0": "mwaka huu",
	"field-week-relative+-1": "wiki iliyopita",
	"dateFormatItem-yyyyM": "M/y G",
	"field-year-relative+1": "mwaka ujao",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "Jumatatu iliyopita",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "wiki hii",
	"field-week-relative+1": "wiki ijayo"
}
//end v1.x content
);