define(
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.
//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "aliceblå",
antiquewhite: "antikvit",
aqua: "vattenblå",
aquamarine: "akvamarin",
azure: "azurblå",
beige: "beige",
bisque: "biskvi",
black: "svart",
blanchedalmond: "mandel",
blue: "blå",
blueviolet: "blålila",
brown: "brun",
burlywood: "trä",
cadetblue: "kadettblå",
chartreuse: "chartreuse",
chocolate: "choklad",
coral: "korallröd",
cornflowerblue: "majsblomsblå",
cornsilk: "majsgul",
crimson: "blodröd",
cyan: "cyan",
darkblue: "mörkt blå",
darkcyan: "mörkt cyan",
darkgoldenrod: "mörkt gullris",
darkgray: "mörkt grå",
darkgreen: "mörkt grön",
darkgrey: "mörkt grå", // same as darkgray
darkkhaki: "mörkt kaki",
darkmagenta: "mörkt magenta",
darkolivegreen: "mörkt olivgrön",
darkorange: "mörkt orange",
darkorchid: "mörkt orkidé",
darkred: "mörkt röd",
darksalmon: "mörkt laxrosa",
darkseagreen: "mörkt havsgrön",
darkslateblue: "mörkt skifferblå",
darkslategray: "mörkt skiffergrå",
darkslategrey: "mörkt skiffergrå", // same as darkslategray
darkturquoise: "mörkt turkos",
darkviolet: "mörkt lila",
deeppink: "djupt rosa",
deepskyblue: "djupt himmelsblå",
dimgray: "dimgrå",
dimgrey: "dimgrå", // same as dimgray
dodgerblue: "uniformsblå",
firebrick: "tegelsten",
floralwhite: "blomvit",
forestgreen: "skogsgrön",
fuchsia: "fuchsia",
gainsboro: "pastellblå",
ghostwhite: "spökvit",
gold: "guld",
goldenrod: "gullris",
gray: "grå",
green: "grön",
greenyellow: "gröngul",
grey: "grå", // same as gray
honeydew: "honungsgul",
hotpink: "starkt rosa",
indianred: "indianröd",
indigo: "indigo",
ivory: "elfenben",
khaki: "kaki",
lavender: "lavendel",
lavenderblush: "lavendelblå",
lawngreen: "gräsgrön",
lemonchiffon: "citrongul",
lightblue: "ljust blå",
lightcoral: "ljust korallröd",
lightcyan: "ljust cyan",
lightgoldenrodyellow: "ljust gyllenrisgul",
lightgray: "ljust grå",
lightgreen: "ljust grön",
lightgrey: "ljust grå", // same as lightgray
lightpink: "ljust rosa",
lightsalmon: "ljust laxrosa",
lightseagreen: "ljust havsgrön",
lightskyblue: "ljust himmelsblå",
lightslategray: "ljust skiffergrå",
lightslategrey: "ljust skiffergrå", // same as lightslategray
lightsteelblue: "ljust stålblå",
lightyellow: "ljust gul",
lime: "lime",
limegreen: "limegrön",
linen: "linnevit",
magenta: "magenta",
maroon: "rödbrun",
mediumaquamarine: "medel vattenblå",
mediumblue: "medel blå",
mediumorchid: "medel orkidé",
mediumpurple: "medel purpur",
mediumseagreen: "medel havsgrön",
mediumslateblue: "medel skifferblå",
mediumspringgreen: "medel vårgrön",
mediumturquoise: "medel turkos",
mediumvioletred: "medel lilaröd",
midnightblue: "midnattsblå",
mintcream: "mint",
mistyrose: "dimrosa",
moccasin: "mockasin",
navajowhite: "navajovit",
navy: "marin",
oldlace: "spetsgul",
olive: "oliv",
olivedrab: "militärgrön",
orange: "orange",
orangered: "orangeröd",
orchid: "orkidé",
palegoldenrod: "blekt gullris",
palegreen: "blekt grön",
paleturquoise: "blekt turkos",
palevioletred: "blekt lilaröd",
papayawhip: "papaya",
peachpuff: "persika",
peru: "peru",
pink: "rosa",
plum: "plommon",
powderblue: "krutblå",
purple: "purpur",
red: "röd",
rosybrown: "rosabrun",
royalblue: "kungsblå",
saddlebrown: "sadelbrun",
salmon: "laxrosa",
sandybrown: "sandbrun",
seagreen: "havsgrön",
seashell: "snäckskal",
sienna: "brungul",
silver: "silver",
skyblue: "himmelsblå",
slateblue: "skifferblå",
slategray: "skiffergrå",
slategrey: "skiffergrå", // same as slategray
snow: "snö",
springgreen: "vårgrön",
steelblue: "stålblå",
tan: "solbrun",
teal: "blågrön",
thistle: "tistel",
tomato: "tomat",
transparent: "transparent",
turquoise: "turkos",
violet: "lila",
wheat: "vetegul",
white: "vit",
whitesmoke: "vit rök",
yellow: "gul",
yellowgreen: "gulgrön"
})
);
