define(
//begin v1.x content
{
	"field-sat-relative+0": "осы сенбі",
	"field-sat-relative+1": "келесі сенбі",
	"field-dayperiod": "түске дейін/түстен кейін",
	"field-sun-relative+-1": "өткен жексенбі",
	"field-mon-relative+-1": "өткен дүйсенбі",
	"field-minute": "минут",
	"field-day-relative+-1": "кеше",
	"field-weekday": "апта күні",
	"field-day-relative+-2": "алдыңғы күні",
	"field-era": "ғасыр",
	"field-hour": "сағат",
	"field-sun-relative+0": "осы жексенбі",
	"field-sun-relative+1": "келесі жексенбі",
	"field-wed-relative+-1": "өткен сәрсенбі",
	"field-day-relative+0": "бүгін",
	"field-day-relative+1": "ертең",
	"field-day-relative+2": "арғы күні",
	"field-tue-relative+0": "осы сейсенбі",
	"field-zone": "уақыт белдеуі",
	"field-tue-relative+1": "келесі сейсенбі",
	"field-week-relative+-1": "өткен апта",
	"field-year-relative+0": "биылғы жыл",
	"field-year-relative+1": "келесі жыл",
	"field-sat-relative+-1": "өткен сенбі",
	"field-year-relative+-1": "былтырғы жыл",
	"field-year": "жыл",
	"field-fri-relative+0": "осы жұма",
	"field-fri-relative+1": "келесі жұма",
	"field-week": "апта",
	"field-week-relative+0": "осы апта",
	"field-week-relative+1": "келесі апта",
	"field-month-relative+0": "осы ай",
	"field-month": "ай",
	"field-month-relative+1": "келесі ай",
	"field-fri-relative+-1": "өткен жұма",
	"field-second": "секунд",
	"field-tue-relative+-1": "өткен сейсенбі",
	"field-day": "күн",
	"field-mon-relative+0": "осы дүйсенбі",
	"field-mon-relative+1": "келесі дүйсенбі",
	"field-thu-relative+0": "осы бейсенбі",
	"field-second-relative+0": "қазір",
	"field-thu-relative+1": "келесі бейсенбі",
	"field-wed-relative+0": "осы сәрсенбі",
	"field-wed-relative+1": "келесі сәрсенбі",
	"field-month-relative+-1": "өткен ай",
	"field-thu-relative+-1": "өткен бейсенбі"
}
//end v1.x content
);