define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateTimeFormat-full": "{0} {1}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "d.M.",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{0} {1}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yyyyMM": "MM.y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d. MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{0} {1}",
	"dateFormatItem-yyyyMd": "d.M.y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMEd": "E d.MM.y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "E d.M",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d.M y G",
	"dateFormatItem-yyyyM": "M y G",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d.",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);