define(
//begin v1.x content
{
	"dateFormatItem-yM": "M y",
	"field-dayperiod": "AM/PM",
	"dayPeriods-format-wide-pm": "PM",
	"dateFormatItem-yQ": "Q yyyy",
	"field-minute": "minutt",
	"eraNames": [
		"f.Kr.",
		"e.Kr."
	],
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "i går",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMdd": "dd.MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "i forgårs",
	"field-weekday": "ukedag",
	"field-day-relative+-3": "i forforgårs",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-format-wide-am": "AM",
	"field-era": "tidsalder",
	"field-hour": "time",
	"dateFormatItem-y": "y",
	"timeFormat-full": "'kl'. HH:mm:ss zzzz",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "i dag",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"field-day-relative+1": "i morgen",
	"eraAbbr": [
		"f.Kr.",
		"e.Kr."
	],
	"field-day-relative+2": "i overmorgen",
	"field-day-relative+3": "i overovermorgen",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"dateFormat-long": "d. MMMM y",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-EEEd": "EEE d.",
	"field-zone": "sone",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d. MMM y",
	"dateFormatItem-yyMM": "MM.yy",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyMMM": "MMM yy",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-ms": "mm.ss",
	"field-year": "år",
	"field-week": "uke",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"mai",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"des."
	],
	"timeFormat-short": "HH:mm",
	"field-month": "måned",
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"days-format-abbr": [
		"søn.",
		"man.",
		"tir.",
		"ons.",
		"tor.",
		"fre.",
		"lør."
	],
	"dateFormatItem-M": "L",
	"field-second": "sekund",
	"field-day": "dag",
	"dateFormatItem-MEd": "E d.M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy",
	"dateFormatItem-yMMMEd": "EEE d. MMM y",
	"dateFormat-full": "EEEE d. MMMM y",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "EEE d.M.yyyy",
	"months-format-wide": [
		"januar",
		"februar",
		"mars",
		"april",
		"mai",
		"juni",
		"juli",
		"august",
		"september",
		"oktober",
		"november",
		"desember"
	],
	"dateFormatItem-d": "d.",
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"days-format-wide": [
		"søndag",
		"mandag",
		"tirsdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lørdag"
	]
}
//end v1.x content
);