define(
//begin v1.x content
{
	"field-sat-relative+0": "larunbat hau",
	"field-sat-relative+1": "hurrengo larunbata",
	"field-dayperiod": "AM//PM",
	"field-sun-relative+-1": "aurreko igandea",
	"field-mon-relative+-1": "aurreko astelehena",
	"field-minute": "Minutua",
	"field-day-relative+-1": "atzo",
	"field-weekday": "Asteguna",
	"field-day-relative+-2": "herenegun",
	"field-era": "Aroa",
	"field-hour": "Ordua",
	"field-sun-relative+0": "igande hau",
	"field-sun-relative+1": "hurrengo igandea",
	"field-wed-relative+-1": "aurreko asteazkena",
	"field-day-relative+0": "gaur",
	"field-day-relative+1": "bihar",
	"eraAbbr": [
		"R.O.C. aurretik",
		"R.O.C."
	],
	"field-day-relative+2": "etzi",
	"field-tue-relative+0": "astearte hau",
	"field-zone": "Ordu-zona",
	"field-tue-relative+1": "hurrengo asteartea",
	"field-week-relative+-1": "aurreko astea",
	"field-year-relative+0": "aurten",
	"field-year-relative+1": "hurrengo urtea",
	"field-sat-relative+-1": "aurreko larunbata",
	"field-year-relative+-1": "aurreko urtea",
	"field-year": "Urtea",
	"field-fri-relative+0": "ostiral hau",
	"field-fri-relative+1": "hurrengo ostirala",
	"field-week": "Astea",
	"field-week-relative+0": "aste hau",
	"field-week-relative+1": "hurrengo astea",
	"field-month-relative+0": "hilabete hau",
	"field-month": "Hilabetea",
	"field-month-relative+1": "hurrengo hilabetea",
	"field-fri-relative+-1": "aurreko ostirala",
	"field-second": "Segundoa",
	"field-tue-relative+-1": "aurreko asteartea",
	"field-day": "Eguna",
	"field-mon-relative+0": "astelehen hau",
	"field-mon-relative+1": "hurrengo astelehena",
	"field-thu-relative+0": "ostegun hau",
	"field-second-relative+0": "orain",
	"field-thu-relative+1": "hurrengo osteguna",
	"field-wed-relative+0": "asteazken hau",
	"field-wed-relative+1": "hurrengo asteazkena",
	"field-month-relative+-1": "aurreko hilabetea",
	"field-thu-relative+-1": "aurreko osteguna"
}
//end v1.x content
);