define(
//begin v1.x content
{
	"USD_displayName": "mɔni mǝ á amɛrika",
	"TZS_displayName": "mɔni mǝ á tanzaní",
	"ZMW_displayName": "mɔni mǝ á zambí",
	"MAD_displayName": "mɔni mǝ á marɔk",
	"NGN_displayName": "mɔni mǝ á nijɛ́rya",
	"ZWD_displayName": "mɔni mǝ á zimbabwɛ́",
	"SDG_displayName": "mɔni mǝ á sudan",
	"MWK_displayName": "mɔni mǝ á malawi",
	"KMF_displayName": "mɔni mǝ á komɔr",
	"SCR_displayName": "mɔni mǝ á sɛcɛl",
	"EGP_displayName": "mɔni mǝ á ɛjípt",
	"CVE_displayName": "mɔni mǝ á kapvɛr",
	"LYD_displayName": "mɔni mǝ á libí",
	"CAD_displayName": "mɔni mǝ á kanada",
	"INR_displayName": "mɔni mǝ á indí",
	"JPY_displayName": "mɔni mǝ á japɔ́ŋ",
	"LRD_displayName": "mɔni mǝ á libɛrya",
	"ZAR_displayName": "mɔni mǝ á afrik anǝ a sud",
	"AOA_displayName": "mɔni mǝ á angóla",
	"TND_displayName": "mɔni mǝ á tunɛsí",
	"GHC_displayName": "mɔni mǝ á gána",
	"BWP_displayName": "mɔni mǝ á botswana",
	"DZD_displayName": "mɔni mǝ á aljɛrí",
	"ZMK_displayName": "mɔni mǝ á zambí (1968–2012)",
	"NAD_displayName": "mɔni mǝ á namibí",
	"AED_displayName": "mɔni mǝ á bǝlɔŋ bǝ kaksa bɛ táatáaŋzǝn",
	"ETB_displayName": "mɔni mǝ á ɛtyɔpí",
	"MZM_displayName": "mɔni mǝ á mosambík",
	"BIF_displayName": "mɔni mǝ á burundí",
	"RWF_displayName": "mɔni mǝ á rwanda",
	"STD_displayName": "mɔni mǝ á saotomɛ́ ri priŋsib",
	"SZL_displayName": "mɔni mǝ á swazilan",
	"EUR_displayName": "mɔni mǝ á pɛrɛsǝ́",
	"ERN_displayName": "mɔni mǝ á ɛritrɛ́",
	"SAR_displayName": "mɔni mǝ á arabí saodí",
	"DJF_displayName": "mɔni mǝ á dyibutí",
	"CDF_displayName": "mɔni mǝ á kɔngó",
	"GBP_displayName": "mɔni mǝ á ingɛrís",
	"CHF_displayName": "mɔni mǝ á swís",
	"MUR_displayName": "mɔni mǝ á mwarís",
	"SOS_displayName": "mɔni mǝ á somalí",
	"BHD_displayName": "mɔni mǝ á barǝ́n",
	"XOF_displayName": "mɔni mǝ á afríka aná wɛs",
	"GNS_displayName": "mɔni mǝ á ginɛ́",
	"SLL_displayName": "mɔni mǝ á syɛraleon",
	"UGX_displayName": "mɔni mǝ á uganda",
	"MGA_displayName": "mɔni mǝ á madagaska",
	"AUD_displayName": "mɔni mǝ á ɔstralí",
	"KES_displayName": "mɔni mǝ á kɛnya",
	"SHP_displayName": "mɔni mǝ á sɛntɛ́len",
	"XAF_displayName": "fráŋ",
	"LSL_displayName": "mɔni mǝ á lǝsóto",
	"MRO_displayName": "mɔni mǝ á mwaritaní",
	"CNY_displayName": "mɔni mǝ á cín",
	"GMD_displayName": "mɔni mǝ á gambí"
}
//end v1.x content
);