define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Sárúwá / Cɛɛ́nko",
	"field-minute": "Mǝnít",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Rinkɔɔ́",
	"field-weekday": "Mǝrú mǝ sɔ́ndǝ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Byámɛɛn",
	"field-hour": "Cámɛɛn",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Gɛ́ɛnǝ",
	"field-day-relative+1": "Ridúrǝ́",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Wáas",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Bǝk",
	"field-week": "Sɔ́ndǝ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Ŋwíí",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Háu",
	"field-day": "Ŋwós",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);