define(
//begin v1.x content
{
	"USD_displayName": "Dolaar Dowlaaji Dentuɗi",
	"TZS_displayName": "Siling Tansanii",
	"ZMW_displayName": "Kuwacca Sammbi",
	"MAD_displayName": "Diraham Maruk",
	"NGN_displayName": "Nayraa Nijeriyaa",
	"ZWD_displayName": "Dolaar Simbaabuwe",
	"SDG_displayName": "Liibar Sudaan",
	"MWK_displayName": "Kuwacca Malaawi",
	"KMF_displayName": "Faraa Komoor",
	"SCR_displayName": "Rupii Seysel",
	"EGP_displayName": "Liibar Ejipt",
	"CVE_displayName": "Eskudoo Kap Weer",
	"LYD_displayName": "Dinaar Libi",
	"CAD_displayName": "Dolaar Kandaaa",
	"INR_displayName": "Rupii Enndo",
	"JPY_displayName": "Yen Sapoo",
	"LRD_displayName": "Dolaar Liberiyaa",
	"ZAR_displayName": "Rannda Afrik Bŋ Worgo",
	"AOA_displayName": "Kwansaa Anngolaa",
	"TND_displayName": "Dinaar Tunisii",
	"GHC_displayName": "Sedi Ganaa",
	"BWP_displayName": "Pulaa Botwanaa",
	"DZD_displayName": "Dinaar Alaseri",
	"ZMK_displayName": "Kuwacca Sammbi (1968–2012)",
	"NAD_displayName": "Dolaar Namibii",
	"AED_displayName": "Dirham Emiraati Araab Dentuɗi",
	"ETB_displayName": "Biir Ecoppi",
	"MZM_displayName": "Metikal Mosammbik",
	"BIF_displayName": "Mbuuɗu Burunndi",
	"RWF_displayName": "Faraa Ruwanndaa",
	"STD_displayName": "Dobra Sawo Tome e Prensipe",
	"SZL_displayName": "Lilangeni Swaasilannda",
	"EUR_displayName": "Oroo",
	"ERN_displayName": "Nafka Eriteree",
	"SAR_displayName": "Riyaal Arabi Sawdit",
	"DJF_displayName": "Faraa Jibutii",
	"CDF_displayName": "Faraa Konngo",
	"GBP_displayName": "Liibar Sterling",
	"CHF_displayName": "Faraa Suwiis",
	"MUR_displayName": "Rupii Moriis",
	"SOS_displayName": "Siling Soomali",
	"BHD_displayName": "Dinaar Bahrayn",
	"XOF_displayName": "Mbuuɗu Seefaa BCEAO",
	"GNS_displayName": "Faraa Gine",
	"SLL_displayName": "Lewoon Seraa Liyon",
	"UGX_displayName": "Siling Uganndaa",
	"MGA_displayName": "Ariyari Madagaskaar",
	"AUD_displayName": "Dolaar Ostaraalii",
	"KES_displayName": "Siling Keñaa",
	"SHP_displayName": "Liibar Sent Helen",
	"XAF_displayName": "Mbuuɗi Seefaa BEAC",
	"LSL_displayName": "Loti Lesotoo",
	"MRO_displayName": "Ugiyya Muritani",
	"CNY_displayName": "Yuam Siin",
	"GMD_displayName": "Dalasi Gammbi"
}
//end v1.x content
);