define(
//begin v1.x content
{
	"USD_displayName": "Ihela ya Malekani",
	"TZS_displayName": "Ihela ya Tansaniya",
	"ZMW_displayName": "Ihela ya Sambiya",
	"MAD_displayName": "Ihela ya Moloko",
	"NGN_displayName": "Ihela ya Nijeliya",
	"ZWD_displayName": "Ihela ya Simbabwe",
	"SDG_displayName": "Ihela ya Sudani",
	"MWK_displayName": "Ihela ya Malawi",
	"KMF_displayName": "Ihela ya Komolo",
	"SCR_displayName": "Ihela ya Shelisheli",
	"EGP_displayName": "Ihela ya Misili",
	"CVE_displayName": "Ihela ya Kepuvede",
	"LYD_displayName": "Ihela ya Libiya",
	"CAD_displayName": "Ihela ya Kanada",
	"INR_displayName": "Ihela ya Indiya",
	"JPY_displayName": "Ihela ya Japani",
	"TZS_symbol": "TSh",
	"LRD_displayName": "Ihela ya Libeliya",
	"ZAR_displayName": "Ihela ya Afilika Kusini",
	"AOA_displayName": "Ihela ya Angola",
	"TND_displayName": "Ihela ya Tunisiya",
	"GHC_displayName": "Ihela ya Ghana",
	"BWP_displayName": "Ihela ya Botiswana",
	"DZD_displayName": "Ihela ya Alijeliya",
	"ZMK_displayName": "Ihela ya Sambiya (1968–2012)",
	"NAD_displayName": "Ihela ya Namibiya",
	"AED_displayName": "Ihela ya Shitwa sha Shiyalabu",
	"ETB_displayName": "Ihela ya Uhabeshi",
	"MZM_displayName": "Ihela ya Musumbiji",
	"BIF_displayName": "Ihela ya Bulundi",
	"RWF_displayName": "Ihela ya Lwanda",
	"STD_displayName": "Ihela ya Sao Tome ni Pilinsipe",
	"SZL_displayName": "Ihela ya Uswasi",
	"EUR_displayName": "Ihela ya Ulaya",
	"ERN_displayName": "Ihela ya Elitileya",
	"SAR_displayName": "Ihela ya Sawudiya",
	"DJF_displayName": "Ihela ya Jibuti",
	"CDF_displayName": "Ihela ya Kongo",
	"GBP_displayName": "Ihela ya Uwingelesa",
	"CHF_displayName": "Ihela ya Uswisi",
	"MUR_displayName": "Ihela ya Molisi",
	"SOS_displayName": "Ihela ya Somaliya",
	"BHD_displayName": "Ihela ya Bahaleni",
	"XOF_displayName": "Ihela ya CFA BCEAO",
	"GNS_displayName": "Ihela ya Gine",
	"SLL_displayName": "Ihela ya Siela Liyoni",
	"UGX_displayName": "Ihela ya Uganda",
	"MGA_displayName": "Ihela ya Bukini",
	"AUD_displayName": "Ihela ya Awusitilaliya",
	"KES_displayName": "Ihela ya Kenya",
	"SHP_displayName": "Ihela ya Santahelena",
	"XAF_displayName": "Ihela ya CFA BEAC",
	"LSL_displayName": "Ihela ya Lesoto",
	"MRO_displayName": "Ihela ya Molitaniya",
	"CNY_displayName": "Ihela ya Shina",
	"GMD_displayName": "Ihela ya Gambiya"
}
//end v1.x content
);