define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Uluhaavi lwa lusiku",
	"field-minute": "Idakika",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Imehe",
	"field-weekday": "Ulusiku lwa Lijuma",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Uluhaavi lwa",
	"field-hour": "Ilisala",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Ineng'uni",
	"field-day-relative+1": "Pamulaawu",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Uluhaavi lwa lisaa",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "M/d/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Mwakha",
	"field-week": "Ilijuma",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Mwesi",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d y",
	"field-second": "Isekunde",
	"field-day": "Lusiku",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);