define(
//begin v1.x content
{
	"USD_displayName": "Solai Amerika",
	"TZS_displayName": "Solai Tanzaniya",
	"ZMW_displayName": "Solai Zambiya",
	"MAD_displayName": "Solai Marok",
	"NGN_displayName": "Solai Nigeriya",
	"ZWD_displayName": "Solai Zimbabwe",
	"SDG_displayName": "Solai Sudaŋ ma dii ne dinar",
	"MWK_displayName": "Solai Malawi",
	"KMF_displayName": "solai Komorya",
	"SCR_displayName": "Solai Saichel",
	"EGP_displayName": "solai Egypt",
	"CVE_displayName": "solai Kapverdiya",
	"LYD_displayName": "solai Libya",
	"CAD_displayName": "solai Kanada",
	"INR_displayName": "solai India",
	"JPY_displayName": "solai Japoŋ",
	"LRD_displayName": "solai Liberiya",
	"ZAR_displayName": "Solai Africa nekǝsǝŋ",
	"AOA_displayName": "solai Angola",
	"TND_displayName": "Solai Tunisiya",
	"GHC_displayName": "solai Gana",
	"BWP_displayName": "solai Botswana",
	"DZD_displayName": "solai Algerya",
	"ZMK_displayName": "Solai Zambiya (1968–2012)",
	"NAD_displayName": "Solai Namibiya",
	"AED_displayName": "Solai Arabiya",
	"ETB_displayName": "solai Etiopia",
	"MZM_displayName": "Solai Mozambika",
	"BIF_displayName": "solai Burundi",
	"RWF_displayName": "Solai Rwanda",
	"STD_displayName": "Solai Sao Tome",
	"SZL_displayName": "solai Swaziland",
	"EUR_displayName": "solai Euro",
	"ERN_displayName": "solai Eritre",
	"SAR_displayName": "Solai Saudiya",
	"DJF_displayName": "solai Djibouti",
	"CDF_displayName": "solai Kongo",
	"GBP_displayName": "solai Britaniya",
	"CHF_displayName": "Solai Swiss",
	"MUR_displayName": "Solai Mauricǝ",
	"SOS_displayName": "Solai Somaliya",
	"BHD_displayName": "solai Barenya",
	"XOF_displayName": "solai BCEAO",
	"GNS_displayName": "solai Guine",
	"SLL_displayName": "solai Sierra leonǝ",
	"UGX_displayName": "Solai Uganda",
	"MGA_displayName": "Solai Malagasya",
	"SDP_displayName": "Solai Sudaŋ ma dii ne livre",
	"AUD_displayName": "solai Australya",
	"KES_displayName": "solai Kenia",
	"SHP_displayName": "Solai Helena",
	"XAF_displayName": "solai BEAC",
	"LSL_displayName": "solai Lesotho",
	"MRO_displayName": "Solai Mauritaniya",
	"CNY_displayName": "solai Syiŋ",
	"GMD_displayName": "solai Gambiya"
}
//end v1.x content
);