define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-minute": "Cok comme ma laŋne",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Tǝsoo",
	"field-weekday": "Kǝsyil luma",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Syii ma tãa",
	"field-hour": "Cok comme",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Tǝ'nahko",
	"field-day-relative+1": "Tǝ'nane",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Waŋ cok comme",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Syii",
	"field-week": "Luma",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Fĩi",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Cok comme ma laŋ tǝ biŋ",
	"field-day": "Zah'nane/ Comme",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);