define(
//begin v1.x content
{
	"USD_displayName": "Dólar norte-americano",
	"TZS_displayName": "Xelim da Tanzânia",
	"ZMW_displayName": "Cuacha zambiano",
	"MZN_symbol": "MTn",
	"MAD_displayName": "Dirém marroquino",
	"NGN_displayName": "Naira nigeriana",
	"ZWD_displayName": "Dólar do Zimbábue",
	"SDG_displayName": "Dinar sudanês",
	"MWK_displayName": "Cuacha do Maláui",
	"KMF_displayName": "Franco de Comores",
	"SCR_displayName": "Rupia das Seychelles",
	"EGP_displayName": "Libra egípcia",
	"CVE_displayName": "Escudo cabo-verdiano",
	"LYD_displayName": "Dinar líbio",
	"CAD_displayName": "Dólar canadense",
	"INR_displayName": "Rúpia indiana",
	"JPY_displayName": "Iene japonês",
	"LRD_displayName": "Dólar liberiano",
	"ZAR_displayName": "Rand sul-africano",
	"AOA_displayName": "Cuanza angolano",
	"TND_displayName": "Dinar tunisiano",
	"GHC_displayName": "Cedi de Gana (1979–2007)",
	"BWP_displayName": "Pula botsuanesa",
	"DZD_displayName": "Dinar argelino",
	"ZMK_displayName": "Cuacha zambiano (1968–2012)",
	"NAD_displayName": "Dólar da Namíbia",
	"AED_displayName": "Dirém dos Emirados Árabes Unidos",
	"ETB_displayName": "Birr etíope",
	"MZM_displayName": "Metical antigo de Moçambique",
	"BIF_displayName": "Franco do Burundi",
	"RWF_displayName": "Franco ruandês",
	"STD_displayName": "Dobra de São Tomé e Príncipe",
	"SZL_displayName": "Lilangeni da Suazilândia",
	"EUR_displayName": "Euro",
	"ERN_displayName": "Nakfa da Eritréia",
	"SAR_displayName": "Rial saudita",
	"DJF_displayName": "Franco do Djibuti",
	"CDF_displayName": "Franco congolês",
	"GBP_displayName": "Libra esterlina britânica",
	"CHF_displayName": "Franco suíço",
	"MUR_displayName": "Rupia de Maurício",
	"SOS_displayName": "Xelim somali",
	"BHD_displayName": "Dinar bareinita",
	"XOF_displayName": "Franco CFA BCEAO",
	"GNS_displayName": "Syli da Guiné",
	"SLL_displayName": "Leone de Serra Leoa",
	"UGX_displayName": "Xelim ugandense (1966–1987)",
	"MGA_displayName": "Franco de Madagascar",
	"SDP_displayName": "Libra sudanesa antiga",
	"MZN_displayName": "Metical de Moçambique",
	"AUD_displayName": "Dólar australiano",
	"KES_displayName": "Xelim queniano",
	"SHP_displayName": "Libra de Santa Helena",
	"XAF_displayName": "Franco CFA BEAC",
	"LSL_displayName": "Loti do Lesoto",
	"MRO_displayName": "Ouguiya da Mauritânia",
	"CNY_displayName": "Yuan Renminbi chinês",
	"GMD_displayName": "Dalasi de Gâmbia"
}
//end v1.x content
);