define(
//begin v1.x content
{
	"dateFormatItem-yM": "MM/y",
	"field-minute": "Minuto",
	"dateFormatItem-MMMEd": "E, d MMM",
	"field-day-relative+-1": "Zuro",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "LLL",
	"field-hour": "Hora",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM 'de' y",
	"field-day-relative+0": "Lero",
	"field-day-relative+1": "Manguana",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "d 'de' MMM 'de' y G",
	"dateFormatItem-yMMMM": "MMMM 'de' y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Chaka",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-HHmm": "HH:mm",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"field-month": "Mwezi",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d 'de' MMM 'de' y",
	"field-second": "Segundo",
	"field-day": "Ntsiku",
	"dateFormatItem-MEd": "E, dd/MM",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E, d 'de' MMM 'de' y",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);