define(
//begin v1.x content
{
	"field-thu-relative+1": "Dunnersdaach nächste Woche",
	"field-year-relative+-1": "läz Johr",
	"field-month-relative+-1": "lätzde Mohnd",
	"field-day-relative+-1": "jestere",
	"field-sat-relative+-1": "Samsdaach letzte Woche",
	"field-sun-relative+-1": "Sunndaach letzte Woche",
	"field-day-relative+-2": "vörjestere",
	"field-tue-relative+-1": "Dinnsdaach letzte Woche",
	"field-sun-relative+0": "Sunndaach diese Woche",
	"field-sun-relative+1": "Sunndaach nächste Woche",
	"field-week-relative+0": "di Woch",
	"field-fri-relative+-1": "Friidaach letzte Woche",
	"field-week-relative+1": "nächste Woche",
	"field-sat-relative+0": "Samsdaach diese Woche",
	"field-mon-relative+0": "Moondaach diese Woche",
	"field-thu-relative+-1": "Dunnersdaach letzte Woche",
	"field-sat-relative+1": "Samsdaach nächste Woche",
	"field-mon-relative+1": "Moondaach nächste Woche",
	"field-week-relative+-1": "läz Woch",
	"field-day-relative+0": "hück",
	"field-day-relative+1": "morje",
	"field-day-relative+2": "övvermorje",
	"field-mon-relative+-1": "Moondaach letzte Woche",
	"field-month-relative+0": "diese Mohnd",
	"field-month-relative+1": "nächste Mohnd",
	"field-fri-relative+0": "Friidaach diese Woche",
	"field-wed-relative+-1": "Metwoch letzte Woche",
	"field-fri-relative+1": "Friidaach nächste Woche",
	"field-year-relative+0": "diese Johr",
	"field-year-relative+1": "nächste Johr",
	"field-wed-relative+0": "Metwoch diese Woche",
	"field-tue-relative+0": "Dinnsdaach diese Woche",
	"field-wed-relative+1": "Metwoch nächste Woche",
	"field-tue-relative+1": "Dinnsdaach nächste Woche",
	"field-thu-relative+0": "Dunnersdaach diese Woche"
}
//end v1.x content
);