define(
//begin v1.x content
{
	"field-second-relative+0": "indi",
	"field-weekday": "həftə günü",
	"field-wed-relative+0": "bu çərşənbə",
	"field-wed-relative+1": "gələn çərşənbə",
	"dateFormatItem-GyMMMEd": "G d MMM y, E",
	"dateFormatItem-MMMEd": "d MMM, E",
	"field-tue-relative+-1": "keçən çərşənbə axşamı",
	"dateFormat-long": "G d MMMM, y",
	"field-fri-relative+-1": "keçən cümə",
	"field-wed-relative+-1": "keçən çərşənbə",
	"dateFormatItem-yyyyQQQ": "G y QQQ",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "G d MMMM y, EEEE",
	"dateFormatItem-yyyyMEd": "GGGGG dd.MM.y, E",
	"field-thu-relative+-1": "keçən cümə axşamı",
	"dateFormatItem-Md": "dd.MM",
	"field-era": "era",
	"field-year": "il",
	"field-hour": "saat",
	"field-sat-relative+0": "bu şənbə",
	"field-sat-relative+1": "gələn şənbə",
	"field-day-relative+0": "bu gün",
	"field-thu-relative+0": "bu cümə axşamı",
	"field-day-relative+1": "sabah",
	"field-thu-relative+1": "gələn cümə axşamı",
	"dateFormatItem-GyMMMd": "G d MMM y",
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-yyyyMMMEd": "G d MMM y, E",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "G MMM y",
	"dateFormatItem-yyyyMMMd": "G d MMM y",
	"field-sun-relative+0": "bu bazar",
	"field-sun-relative+1": "gələn bazar",
	"field-minute": "dəqiqə",
	"field-dayperiod": "günün vaxtı",
	"dateFormatItem-d": "d",
	"field-day-relative+-1": "dünən",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "dd.MM, E",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "bu cümə",
	"field-fri-relative+1": "gələn cümə",
	"field-day": "bu gün",
	"field-zone": "saat zolağı",
	"dateFormatItem-y": "G y",
	"field-year-relative+-1": "keçən il",
	"field-month-relative+-1": "keçən ay",
	"dateFormatItem-yyyyMd": "GGGGG dd.MM.y",
	"field-month": "ay",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "bu çərşənbə axşamı",
	"field-tue-relative+1": "gələn çərşənbə axşamı",
	"field-mon-relative+0": "bu bazar ertəsi",
	"field-mon-relative+1": "gələn bazar ertəsi",
	"dateFormat-short": "GGGGG dd.MM.y",
	"field-second": "saniyə",
	"field-sat-relative+-1": "keçən şənbə",
	"field-sun-relative+-1": "keçən bazar",
	"field-month-relative+0": "bu ay",
	"field-month-relative+1": "gələn ay",
	"dateFormatItem-Ed": "d, E",
	"field-week": "həftə",
	"dateFormat-medium": "G d MMM y",
	"field-year-relative+0": "bu il",
	"field-week-relative+-1": "keçən həftə",
	"dateFormatItem-yyyyM": "GGGGG MM y",
	"field-year-relative+1": "gələn il",
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-GyMMM": "G MMM y",
	"field-mon-relative+-1": "keçən bazar ertəsi",
	"dateFormatItem-yyyy": "G y",
	"field-week-relative+0": "bu həftə",
	"field-week-relative+1": "gələn həftə"
}
//end v1.x content
);