define(
//begin v1.x content
{
	"field-sat-relative+0": "यह शनिवार",
	"field-sat-relative+1": "अगला शनिवार",
	"field-dayperiod": "AM/PM",
	"field-sun-relative+-1": "पिछला रविवार",
	"field-mon-relative+-1": "पिछला सोमवार",
	"field-minute": "मिनट",
	"field-day-relative+-1": "बीता कल",
	"field-weekday": "सप्ताह का दिन",
	"field-day-relative+-2": "बीता परसों",
	"field-era": "युग",
	"field-hour": "घंटा",
	"field-sun-relative+0": "यह रविवार",
	"field-sun-relative+1": "अगला रविवार",
	"field-wed-relative+-1": "पिछला बुधवार",
	"field-day-relative+0": "आज",
	"field-day-relative+1": "आने वाला कल",
	"field-day-relative+2": "परसों",
	"field-tue-relative+0": "यह मंगलवार",
	"field-zone": "समय क्षेत्र",
	"field-tue-relative+1": "अगला मंगलवार",
	"field-week-relative+-1": "पिछला सप्ताह",
	"field-year-relative+0": "यह वर्ष",
	"field-year-relative+1": "अगला वर्ष",
	"field-sat-relative+-1": "पिछला शनिवार",
	"field-year-relative+-1": "पिछला वर्ष",
	"field-year": "वर्ष",
	"field-fri-relative+0": "यह शुक्रवार",
	"field-fri-relative+1": "अगला शुक्रवार",
	"field-week": "सप्ताह",
	"field-week-relative+0": "यह सप्ताह",
	"field-week-relative+1": "अगला सप्ताह",
	"field-month-relative+0": "यह माह",
	"field-month": "माह",
	"field-month-relative+1": "अगला माह",
	"field-fri-relative+-1": "पिछला शुक्रवार",
	"field-second": "सेकंड",
	"field-tue-relative+-1": "पिछला मंगलवार",
	"field-day": "दिन",
	"field-mon-relative+0": "यह सोमवार",
	"field-mon-relative+1": "अगला सोमवार",
	"field-thu-relative+0": "यह गुरुवार",
	"field-second-relative+0": "अब",
	"field-thu-relative+1": "अगला गुरुवार",
	"field-wed-relative+0": "यह बुधवार",
	"months-format-wide": [
		"मस्केरेम",
		"टेकेम्ट",
		"हेदर",
		"तहसास",
		"टर",
		"येकाटिट",
		"मेगाबिट",
		"मियाज़िया",
		"गनबोट",
		"सेन",
		"हम्ले",
		"नेहासे",
		"पागूमन"
	],
	"field-wed-relative+1": "अगला बुधवार",
	"field-month-relative+-1": "पिछला माह",
	"field-thu-relative+-1": "पिछला गुरुवार"
}
//end v1.x content
);