// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"安道尔比塞塔",
	AED_displayName:"阿联酋迪拉姆",
	AFA_displayName:"阿富汗尼 (1927-2002)",
	AFN_displayName:"阿富汗尼",
	ALL_displayName:"阿尔巴尼亚列克",
	AMD_displayName:"亚美尼亚德拉姆",
	ANG_displayName:"荷兰安替兰盾",
	AOA_displayName:"安哥拉宽扎",
	AOK_displayName:"安哥拉宽扎 (1977-1990)",
	AON_displayName:"安哥拉新宽扎 (1990-2000)",
	AOR_displayName:"安哥拉宽扎 Reajustado (1995-1999)",
	ARA_displayName:"阿根廷奥斯特",
	ARP_displayName:"阿根廷比索 (1983-1985)",
	ARS_displayName:"阿根廷比索",
	ATS_displayName:"奥地利先令",
	AUD_displayName:"澳大利亚元",
	AWG_displayName:"阿鲁巴基尔德元",
	AZM_displayName:"阿塞拜疆马纳特 (1993-2006)",
	AZN_displayName:"阿塞拜疆马纳特",
	BAD_displayName:"波士尼亚-赫塞哥维纳第纳尔",
	BAM_displayName:"波士尼亚-赫塞哥维纳兑换券",
	BBD_displayName:"巴巴多斯元",
	BDT_displayName:"孟加拉塔卡",
	BEC_displayName:"比利时法郎兑换券",
	BEF_displayName:"比利时法郎",
	BEL_displayName:"比利时法郎（金融）",
	BGL_displayName:"保加利亚硬列弗",
	BGN_displayName:"保加利亚新列弗",
	BHD_displayName:"巴林第纳尔",
	BIF_displayName:"布隆迪法郎",
	BMD_displayName:"百慕大元",
	BND_displayName:"文莱元",
	BOB_displayName:"玻利维亚诺",
	BOP_displayName:"玻利维亚比索",
	BOV_displayName:"玻利维亚 Mvdol（资金）",
	BRB_displayName:"巴西克鲁赛罗 Novo (1967-1986)",
	BRC_displayName:"巴西克鲁扎多",
	BRE_displayName:"巴西克鲁塞罗 (1990-1993)",
	BRL_displayName:"巴西雷亚尔",
	BRN_displayName:"巴西克鲁扎多 Novo",
	BRR_displayName:"巴西克鲁塞罗",
	BSD_displayName:"巴哈马元",
	BTN_displayName:"不丹努扎姆",
	BUK_displayName:"缅元",
	BWP_displayName:"博茨瓦纳普拉",
	BYB_displayName:"白俄罗斯新卢布 (1994-1999)",
	BYR_displayName:"白俄罗斯卢布",
	BZD_displayName:"伯利兹元",
	CAD_displayName:"加拿大元",
	CDF_displayName:"刚果法郎",
	CHF_displayName:"瑞士法郎",
	CLF_displayName:"智利 Unidades de Fomento（资金）",
	CLP_displayName:"智利比索",
	CNY_displayName:"人民币",
	CNY_symbol:"￥",
	COP_displayName:"哥伦比亚比索",
	CRC_displayName:"哥斯达黎加科朗",
	CSD_displayName:"旧塞尔维亚第纳尔",
	CSK_displayName:"捷克硬克郎",
	CUP_displayName:"古巴比索",
	CVE_displayName:"佛得角埃斯库多",
	CYP_displayName:"塞浦路斯镑",
	CZK_displayName:"捷克克郎",
	DDM_displayName:"东德奥斯特马克",
	DEM_displayName:"德国马克",
	DJF_displayName:"吉布提法郎",
	DKK_displayName:"丹麦克朗",
	DOP_displayName:"多米尼加比索",
	DZD_displayName:"阿尔及利亚第纳尔",
	ECS_displayName:"厄瓜多尔苏克雷",
	ECV_displayName:"厄瓜多尔 Unidad de Valor Constante (UVC)",
	EEK_displayName:"爱沙尼亚克朗",
	EGP_displayName:"埃及镑",
	EQE_displayName:"埃奎勒",
	ERN_displayName:"厄立特里亚纳克法",
	ESA_displayName:"西班牙比塞塔（帐户 A）",
	ESB_displayName:"西班牙比塞塔（兑换帐户）",
	ESP_displayName:"西班牙比塞塔",
	ETB_displayName:"埃塞俄比亚比尔",
	EUR_displayName:"欧元",
	FIM_displayName:"芬兰马克",
	FJD_displayName:"斐济元",
	FKP_displayName:"福克兰镑",
	FRF_displayName:"法国法郎",
	GBP_displayName:"英镑",
	GEK_displayName:"乔治亚库蓬拉瑞特",
	GEL_displayName:"乔治亚拉瑞",
	GHC_displayName:"加纳塞第",
	GHS_displayName:"加纳塞迪",
	GIP_displayName:"直布罗陀镑",
	GMD_displayName:"冈比亚达拉西",
	GNF_displayName:"几内亚法郎",
	GNS_displayName:"几内亚西里",
	GQE_displayName:"赤道几内亚埃奎勒",
	GRD_displayName:"希腊德拉克马",
	GTQ_displayName:"危地马拉格查尔",
	GWE_displayName:"葡萄牙几内亚埃斯库多",
	GWP_displayName:"几内亚比绍比索",
	GYD_displayName:"圭亚那元",
	HKD_displayName:"港元",
	HKD_symbol:"HK$",
	HNL_displayName:"洪都拉斯拉伦皮拉",
	HRD_displayName:"克罗地亚第纳尔",
	HRK_displayName:"克罗地亚库纳",
	HTG_displayName:"海地古德",
	HUF_displayName:"匈牙利福林",
	IDR_displayName:"印度尼西亚盾",
	IEP_displayName:"爱尔兰镑",
	ILP_displayName:"以色列镑",
	ILS_displayName:"以色列新谢克尔",
	INR_displayName:"印度卢比",
	IQD_displayName:"伊拉克第纳尔",
	IRR_displayName:"伊朗里亚尔",
	ISK_displayName:"冰岛克朗",
	ITL_displayName:"意大利里拉",
	ITL_symbol:"ITL",
	JMD_displayName:"牙买加元",
	JOD_displayName:"约旦第纳尔",
	JPY_displayName:"日元",
	KES_displayName:"肯尼亚先令",
	KGS_displayName:"吉尔吉斯斯坦索姆",
	KHR_displayName:"柬埔寨瑞尔",
	KMF_displayName:"科摩罗法郎",
	KPW_displayName:"朝鲜圆",
	KRW_displayName:"韩圆",
	KRW_symbol:"￦",
	KWD_displayName:"科威特第纳尔",
	KYD_displayName:"开曼元",
	KZT_displayName:"哈萨克斯坦坚戈",
	LAK_displayName:"老挝基普",
	LBP_displayName:"黎巴嫩镑",
	LKR_displayName:"斯里兰卡卢比",
	LRD_displayName:"利比亚元",
	LSL_displayName:"莱索托洛蒂",
	LSM_displayName:"马洛蒂",
	LTL_displayName:"立陶宛立特",
	LTT_displayName:"立陶宛塔咯呐司",
	LUC_displayName:"卢森堡可兑换法郎",
	LUF_displayName:"卢森堡法郎",
	LUL_displayName:"卢森堡金融法郎",
	LVL_displayName:"拉脱维亚拉特",
	LVR_displayName:"拉脱维亚卢布",
	LYD_displayName:"利比亚第纳尔",
	MAD_displayName:"摩洛哥迪拉姆",
	MAF_displayName:"摩洛哥法郎",
	MDL_displayName:"摩尔多瓦列伊",
	MGA_displayName:"马达加斯加阿里亚里",
	MGF_displayName:"马达加斯加法郎",
	MKD_displayName:"马其顿戴代纳尔",
	MLF_displayName:"马里法郎",
	MMK_displayName:"缅甸开亚特",
	MNT_displayName:"蒙古图格里克",
	MOP_displayName:"澳门元",
	MOP_symbol:"P",
	MRO_displayName:"毛里塔尼亚乌吉亚",
	MTL_displayName:"马耳他里拉",
	MTP_displayName:"马耳他镑",
	MUR_displayName:"毛里求斯卢比",
	MVR_displayName:"马尔代夫拉菲亚",
	MWK_displayName:"马拉维克瓦查",
	MXN_displayName:"墨西哥比索",
	MXP_displayName:"墨西哥银比索 (1861-1992)",
	MXV_displayName:"墨西哥 Unidad de Inversion (UDI)（资金）",
	MYR_displayName:"马来西亚林吉特",
	MZE_displayName:"莫桑比克埃斯库多",
	MZM_displayName:"莫桑比克梅蒂卡尔",
	MZN_displayName:"莫桑比克美提卡",
	NAD_displayName:"纳米比亚元",
	NGN_displayName:"尼日利亚奈拉",
	NIC_displayName:"尼加拉瓜科多巴",
	NIO_displayName:"尼加拉瓜金科多巴",
	NLG_displayName:"荷兰盾",
	NOK_displayName:"挪威克朗",
	NPR_displayName:"尼泊尔卢比",
	NZD_displayName:"新西兰元",
	OMR_displayName:"阿曼里亚尔",
	PAB_displayName:"巴拿马巴波亚",
	PEI_displayName:"秘鲁印锑",
	PEN_displayName:"秘鲁新索尔",
	PES_displayName:"秘鲁索尔",
	PGK_displayName:"巴布亚新几内亚基那",
	PHP_displayName:"菲律宾比索",
	PKR_displayName:"巴基斯坦卢比",
	PLN_displayName:"波兰兹罗提",
	PLZ_displayName:"波兰兹罗提 (1950-1995)",
	PTE_displayName:"葡萄牙埃斯库多",
	PYG_displayName:"巴拉圭瓜拉尼",
	QAR_displayName:"卡塔尔里亚尔",
	RHD_displayName:"罗得西亚元",
	ROL_displayName:"旧罗马尼亚列伊",
	RON_displayName:"罗马尼亚列伊",
	RSD_displayName:"塞尔维亚第纳尔",
	RUB_displayName:"俄国卢布",
	RUR_displayName:"俄国卢布 (1991-1998)",
	RWF_displayName:"卢旺达法郎",
	SAR_displayName:"沙特里亚尔",
	SAR_symbol:"SRl",
	SBD_displayName:"所罗门群岛元",
	SCR_displayName:"塞舌尔卢比",
	SDD_displayName:"苏丹第纳尔",
	SDG_displayName:"苏丹镑",
	SDP_displayName:"旧苏丹镑",
	SEK_displayName:"瑞典克朗",
	SGD_displayName:"新加坡元",
	SGD_symbol:"S$",
	SHP_displayName:"圣赫勒拿镑",
	SIT_displayName:"斯洛文尼亚托拉尔",
	SKK_displayName:"斯洛伐克克朗",
	SLL_displayName:"塞拉利昂利昂",
	SOS_displayName:"索马里先令",
	SRD_displayName:"苏里南元",
	SRG_displayName:"苏里南盾",
	STD_displayName:"圣多美和普林西比多布拉",
	SUR_displayName:"苏联卢布",
	SVC_displayName:"萨尔瓦多科朗",
	SYP_displayName:"叙利亚镑",
	SZL_displayName:"斯威士兰里兰吉尼",
	THB_displayName:"泰铢",
	TJR_displayName:"塔吉克斯坦卢布",
	TJS_displayName:"塔吉克斯坦索莫尼",
	TMM_displayName:"土库曼斯坦马纳特",
	TND_displayName:"突尼斯第纳尔",
	TOP_displayName:"汤加潘加",
	TPE_displayName:"帝汶埃斯库多",
	TRL_displayName:"土耳其里拉",
	TRY_displayName:"新土耳其里拉",
	TTD_displayName:"特立尼达和多巴哥元",
	TWD_displayName:"新台币元",
	TWD_symbol:"NT$",
	TZS_displayName:"坦桑尼亚先令",
	UAH_displayName:"乌克兰格里夫尼亚",
	UAK_displayName:"乌克兰币",
	UGS_displayName:"乌干达先令 (1966-1987)",
	UGX_displayName:"乌干达先令",
	USD_displayName:"美元",
	USN_displayName:"美元（次日）",
	USS_displayName:"美元（当日）",
	UYP_displayName:"乌拉圭新比索 (1975-1993)",
	UYU_displayName:"乌拉圭比索",
	UZS_displayName:"乌兹别克斯苏姆",
	VEB_displayName:"委内瑞拉博利瓦",
	VEF_displayName:"Venezuelan Bolivar Fuerte",
	VND_displayName:"越南盾",
	VUV_displayName:"瓦努阿图瓦图",
	WST_displayName:"西萨摩亚塔拉",
	XAF_displayName:"中非金融合作法郎",
	XAG_displayName:"银",
	XAU_displayName:"黄金",
	XBA_displayName:"欧洲复合单位",
	XBB_displayName:"欧洲货币联盟",
	XBC_displayName:"欧洲计算单位 (XBC)",
	XBD_displayName:"欧洲计算单位 (XBD)",
	XCD_displayName:"东加勒比元",
	XDR_displayName:"特别提款权",
	XEU_displayName:"欧洲货币单位",
	XFO_displayName:"法国金法郎",
	XFU_displayName:"法国 UIC 法郎",
	XOF_displayName:"非洲金融共同体法郎",
	XPD_displayName:"钯",
	XPF_displayName:"太平洋法郎",
	XPT_displayName:"铂",
	XRE_displayName:"RINET 基金",
	XTS_displayName:"为测试保留的代码",
	XXX_displayName:"货币未知或无效",
	YDD_displayName:"也门第纳尔",
	YER_displayName:"也门里亚尔",
	YUD_displayName:"南斯拉夫硬第纳尔",
	YUM_displayName:"南斯拉夫偌威第纳尔",
	YUN_displayName:"南斯拉夫可兑换第纳尔",
	ZAL_displayName:"南非兰特 (金融)",
	ZAR_displayName:"南非兰特",
	ZMK_displayName:"赞比亚克瓦查",
	ZRN_displayName:"新扎伊尔",
	ZRZ_displayName:"扎伊尔",
	ZWD_displayName:"津巴布韦元"
})
                 