// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-gregorian
({
	'months-format-abbr':["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
	'months-format-wide':["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
	'months-standAlone-abbr':["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
	'months-standAlone-narrow':["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
	'months-standAlone-wide':["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
	'days-format-abbr':["周日","周一","周二","周三","周四","周五","周六"],
	'days-format-wide':["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
	'days-standAlone-narrow':["日","一","二","三","四","五","六"],
	'quarters-format-abbr':["1季","2季","3季","4季"],
	'quarters-format-wide':["第1季度","第2季度","第3季度","第4季度"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'am':"上午",
	'pm':"下午",
	'eraNames':["公元前","公元"],
	'eraAbbr':["公元前","公元"],
	'dateFormat-full': "yyyy年M月d日EEEE",
	'dateFormat-long': "yyyy年M月d日",
	'dateFormat-medium': "yyyy-M-d",
	'dateFormat-short': "yy-M-d",
	'timeFormat-full': "ahh时mm分ss秒v",
	'timeFormat-long': "ahh时mm分ss秒z",
	'timeFormat-medium': "ahh:mm:ss",
	'timeFormat-short': "ah:mm",
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeAvailableFormats':["d日E","H时","HH:mm","HH:mm:ss","H:mm","L","M-dE","LLL","MMMd日E","MMMMd日E","MMMMd日","MMMMdd日","MMMd日","MM-dd","M-d","d日","mm:ss","mm:ss","yyyy年","yyyy-M","yyyy年M月d日，E","yyyy年MMM","yyyy年MMMd日EEE","yyyy年MMMM","yyyy年QQQ","y年QQQ","yy-MM","yy年MMM","yy年第Q季度","yyyy年","yyyy年M月","yyyy年MMMM"],
        'field-era':"时期",
        'field-year':"年",
        'field-month':"月",
        'field-week':"周",
        'field-day':"日",
        'field-weekday':"周天",
        'field-dayperiod':"上午/下午",
        'field-hour':"小时",
        'field-minute':"分钟",
        'field-second':"秒钟",
        'field-zone':"区域"
})
                        