define(
//begin v1.x content
{
	"dateFormatItem-yM": "yyyy-M",
	"dateFormatItem-yQ": "y年QQQ",
	"months-standAlone-abbr-leap": "Adar II",
	"dayPeriods-format-wide-pm": "下午",
	"dateFormatItem-MMMEd": "M月d日E",
	"dateTimeFormat-full": "{1}{0}",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yQQQ": "y年QQQ",
	"days-standAlone-wide": [
		"星期日",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六"
	],
	"dayPeriods-format-wide-am": "上午",
	"months-format-abbr-leap": "Adar II",
	"quarters-standAlone-abbr": [
		"一季度",
		"二季度",
		"三季度",
		"四季度"
	],
	"dateFormatItem-y": "y年",
	"timeFormat-full": "zzzzah时mm分ss秒",
	"months-standAlone-abbr": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"dateFormatItem-Ed": "d日E",
	"dateFormatItem-yMMM": "y年M月",
	"days-standAlone-narrow": [
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六"
	],
	"dateFormat-long": "y年M月d日",
	"timeFormat-medium": "ah:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "yyyy-M-d",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "y年M月d日",
	"quarters-standAlone-wide": [
		"第一季度",
		"第二季度",
		"第三季度",
		"第四季度"
	],
	"dateTimeFormat-long": "{1}{0}",
	"months-standAlone-wide": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"dateFormatItem-MMMd": "M月d日",
	"timeFormat-long": "zah时mm分ss秒",
	"months-format-abbr": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"timeFormat-short": "ah:mm",
	"dateFormatItem-H": "H时",
	"quarters-format-abbr": [
		"1季",
		"2季",
		"3季",
		"4季"
	],
	"days-format-abbr": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"dateFormatItem-M": "M月",
	"days-format-narrow": [
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六"
	],
	"dateFormatItem-yMMMd": "y年M月d日",
	"dateFormatItem-MEd": "M-dE",
	"dateFormatItem-hm": "ah:mm",
	"days-standAlone-abbr": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"months-standAlone-wide-leap": "Adar II",
	"dateFormat-short": "yy-M-d",
	"dateFormatItem-yMMMEd": "y年M月d日E",
	"dateFormat-full": "y年M月d日EEEE",
	"dateFormatItem-yMEd": "y年M月d日，E",
	"months-format-wide": [
		"Tishri",
		"Heshvan",
		"Kislev",
		"Tevet",
		"Shevat",
		"Adar I",
		"Adar",
		"Nisan",
		"Iyar",
		"Sivan",
		"Tamuz",
		"Av",
		"Elul"
	],
	"dateFormatItem-d": "d日",
	"quarters-format-wide": [
		"第1季度",
		"第2季度",
		"第3季度",
		"第4季度"
	],
	"months-format-wide-leap": "Adar II",
	"days-format-wide": [
		"星期日",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六"
	],
	"dateFormatItem-h": "ah时"
}
//end v1.x content
);