// generated from ldml/main/*.xml, xpath: ldml/numbers/currencies
({
	ADP_displayName:"Peseta Andorrana",
	AED_displayName:"Dirham degli Emirati Arabi Uniti",
	AFA_displayName:"Afgani (1927-2002)",
	AFN_displayName:"Afgani",
	AFN_symbol:"Af",
	ALL_displayName:"Lek Albanese",
	ALL_symbol:"lek",
	AMD_displayName:"Dram Armeno",
	AMD_symbol:"dram",
	ANG_displayName:"Fiorino delle Antille Olandesi",
	AOA_displayName:"Kwanza Angolano",
	AOK_displayName:"Kwanza Angolano (1977-1990)",
	AON_displayName:"Nuovo Kwanza Angolano (1990-2000)",
	AOR_displayName:"Kwanza Reajustado Angolano (1995-1999)",
	ARA_displayName:"Austral Argentino",
	ARP_displayName:"Peso Argentino (vecchio Cod.)",
	ARS_displayName:"Peso Argentino",
	ATS_displayName:"Scellino Austriaco",
	AUD_displayName:"Dollaro Australiano",
	AWG_displayName:"Fiorino di Aruba",
	AZM_displayName:"Manat Azero",
	AZN_displayName:"manat azero",
	BAD_displayName:"Dinar Bosnia-Herzegovina",
	BAM_displayName:"Marco Conv. Bosnia-Erzegovina",
	BAM_symbol:"KM",
	BBD_displayName:"Dollaro di Barbados",
	BBD_symbol:"BDS$",
	BDT_displayName:"Taka Bangladese",
	BDT_symbol:"Tk",
	BEC_displayName:"Franco Belga (convertibile)",
	BEF_displayName:"Franco Belga",
	BEL_displayName:"Franco Belga (finanziario)",
	BGL_displayName:"Lev Bulgaro",
	BGN_displayName:"Nuovo Lev Bulgaro",
	BGN_symbol:"lev",
	BHD_displayName:"Dinaro del Bahraini",
	BHD_symbol:"BD",
	BIF_displayName:"Franco del Burundi",
	BIF_symbol:"Fbu",
	BMD_displayName:"Dollaro delle Bermuda",
	BMD_symbol:"Ber$",
	BND_displayName:"Dollaro del Brunei",
	BOB_displayName:"Boliviano",
	BOP_displayName:"Peso Boliviano",
	BOV_displayName:"Mvdol Boliviano",
	BRB_displayName:"Cruzeiro Novo Brasiliano (1967-1986)",
	BRC_displayName:"Cruzado Brasiliano",
	BRE_displayName:"Cruzeiro Brasiliano (1990-1993)",
	BRL_displayName:"Real Brasiliano",
	BRN_displayName:"Cruzado Novo Brasiliano",
	BRR_displayName:"Cruzeiro Brasiliano",
	BSD_displayName:"Dollaro delle Bahamas",
	BTN_displayName:"Ngultrum Butanese",
	BTN_symbol:"Nu",
	BUK_displayName:"Kyat Birmano",
	BWP_displayName:"Pula del Botswana",
	BYB_displayName:"Nuovo Rublo Bielorussia (1994-1999)",
	BYR_displayName:"Rublo Bielorussia",
	BYR_symbol:"Rbl",
	BZD_displayName:"Dollaro Belize",
	BZD_symbol:"BZ$",
	CAD_displayName:"Dollaro Canadese",
	CDF_displayName:"Franco Congolese",
	CHF_displayName:"Franco Svizzero",
	CHF_symbol:"SFr.",
	CLF_displayName:"Unidades de Fomento Chilene",
	CLP_displayName:"Peso Cileno",
	CNY_displayName:"Renmimbi Cinese",
	COP_displayName:"Peso Colombiano",
	COP_symbol:"Col$",
	CRC_displayName:"Colón Costaricano",
	CRC_symbol:"C",
	CSD_displayName:"antico dinaro serbo",
	CSK_displayName:"Corona forte cecoslovacca",
	CUP_displayName:"Peso Cubano",
	CVE_displayName:"Escudo del Capo Verde",
	CVE_symbol:"CVEsc",
	CYP_displayName:"Sterlina Cipriota",
	CZK_displayName:"Corona Ceca",
	DDM_displayName:"Ostmark della Germania Orientale",
	DEM_displayName:"Marco Tedesco",
	DJF_displayName:"Franco Gibutiano",
	DJF_symbol:"DF",
	DKK_displayName:"Corona Danese",
	DOP_displayName:"Peso Dominicano",
	DOP_symbol:"RD$",
	DZD_displayName:"Dinaro Algerino",
	DZD_symbol:"DA",
	ECS_displayName:"Sucre dell’Ecuador",
	ECV_displayName:"Unidad de Valor Constante (UVC) dell’Ecuador",
	EEK_displayName:"Corona dell’Estonia",
	EGP_displayName:"Sterlina Egiziana",
	ERN_displayName:"Nakfa Eritreo",
	ESA_displayName:"peseta spagnola account",
	ESB_displayName:"peseta spagnola account convertibile",
	ESP_displayName:"Peseta Spagnola",
	ETB_displayName:"Birr Etiopico",
	ETB_symbol:"Br",
	EUR_displayName:"Euro",
	FIM_displayName:"Markka Finlandese",
	FJD_displayName:"Dollaro delle Figi",
	FJD_symbol:"F$",
	FKP_displayName:"Sterlina delle Falkland",
	FRF_displayName:"Franco Francese",
	GBP_displayName:"Sterlina Inglese",
	GEK_displayName:"Kupon Larit Georgiano",
	GEL_displayName:"Lari Georgiano",
	GEL_symbol:"lari",
	GHC_displayName:"Cedi del Ghana",
	GIP_displayName:"Sterlina di Gibilterra",
	GMD_displayName:"Dalasi del Gambia",
	GNF_displayName:"Franco della Guinea",
	GNF_symbol:"GF",
	GNS_displayName:"Syli della Guinea",
	GQE_displayName:"Ekwele della Guinea Equatoriale",
	GRD_displayName:"Dracma Greca",
	GTQ_displayName:"Quetzal Guatemalteco",
	GTQ_symbol:"Q",
	GWE_displayName:"Escudo della Guinea portoghese",
	GWP_displayName:"Peso della Guinea-Bissau",
	GYD_displayName:"Dollaro della Guyana",
	GYD_symbol:"G$",
	HKD_displayName:"Dollaro di Hong Kong",
	HNL_displayName:"Lempira Hoduregno",
	HNL_symbol:"L",
	HRD_displayName:"Dinaro Croato",
	HRK_displayName:"Kuna Croata",
	HTG_displayName:"Gourde Haitiano",
	HUF_displayName:"Fiorino Ungherese",
	IDR_displayName:"Rupia Indonesiana",
	IDR_symbol:"Rp",
	IEP_displayName:"Lira Irlandese",
	IEP_symbol:"IR£",
	ILP_displayName:"Sterlina Israeliana",
	ILS_displayName:"Nuovo sheqel israeliano",
	INR_displayName:"Rupia Indiana",
	IQD_displayName:"Dinaro Iracheno",
	IQD_symbol:"ID",
	IRR_displayName:"Rial Iraniano",
	IRR_symbol:"RI",
	ISK_displayName:"Corona Islandese",
	ITL_pattern:"¤ #,##0;-¤ #,##0",
	ITL_displayName:"Lira Italiana",
	ITL_symbol:"₤",
	ITL_decimal:",",
	ITL_group:".",
	JMD_displayName:"Dollaro Giamaicano",
	JMD_symbol:"J$",
	JOD_displayName:"Dinaro Giordano",
	JPY_displayName:"Yen Giapponese",
	KES_displayName:"Scellino Keniota",
	KES_symbol:"K Sh",
	KGS_displayName:"Som  Kirghiso",
	KGS_symbol:"som",
	KHR_displayName:"Riel Cambogiano",
	KHR_symbol:"CR",
	KMF_displayName:"Franco Comoriano",
	KMF_symbol:"CF",
	KPW_displayName:"Won Nordcoreano",
	KRW_displayName:"Won Sudcoreano",
	KWD_displayName:"Dinaro Kuwaitiano",
	KWD_symbol:"KD",
	KYD_displayName:"Dollaro delle Isole Cayman",
	KZT_displayName:"Tenge Kazaco",
	KZT_symbol:"T",
	LAK_displayName:"Kip Laotiano",
	LBP_displayName:"Sterlina Libanese",
	LBP_symbol:"LL",
	LKR_displayName:"Rupia di Sri Lanka",
	LKR_symbol:"SL Re",
	LRD_displayName:"Dollaro Liberiano",
	LSL_displayName:"Loti del Lesotho",
	LSL_symbol:"M",
	LSM_displayName:"maloti",
	LTL_displayName:"Lita Lituana",
	LTT_displayName:"Talonas Lituani",
	LUC_displayName:"franco convertibile del Lussemburgo",
	LUF_displayName:"Franco del Lussemburgo",
	LUL_displayName:"franco finanziario del Lussemburgo",
	LVL_displayName:"Lat Lettone",
	LVR_displayName:"Rublo Lettone",
	LYD_displayName:"Dinaro Libico",
	LYD_symbol:"LD",
	MAD_displayName:"Dirham Marocchino",
	MAF_displayName:"Franco Marocchino",
	MDL_displayName:"Leu Moldavo",
	MGA_displayName:"Ariary Malgascio",
	MGF_displayName:"Franco Malgascio",
	MKD_displayName:"Dinaro Macedone",
	MKD_symbol:"MDen",
	MLF_displayName:"Franco di Mali",
	MMK_displayName:"Kyat di Myanmar",
	MNT_displayName:"Tugrik Mongolo",
	MNT_symbol:"Tug",
	MOP_displayName:"Pataca di Macao",
	MRO_displayName:"Ouguiya della Mauritania",
	MRO_symbol:"UM",
	MTL_displayName:"Lira Maltese",
	MTL_symbol:"Lm",
	MTP_displayName:"Sterlina Maltese",
	MUR_displayName:"Rupia Mauriziana",
	MVR_displayName:"Rufiyaa delle Maldive",
	MWK_displayName:"Kwacha Malawiano",
	MWK_symbol:"MK",
	MXN_displayName:"Peso Messicano",
	MXN_symbol:"MEX$",
	MXP_displayName:"Peso messicano d’argento (1861-1992)",
	MXV_displayName:"Unidad de Inversion (UDI) Messicana",
	MYR_displayName:"Ringgit della Malesia",
	MYR_symbol:"RM",
	MZE_displayName:"Escudo del Mozambico",
	MZM_displayName:"Metical del Mozambico",
	MZM_symbol:"Mt",
	MZN_displayName:"metical del Mozambico",
	NAD_displayName:"Dollaro Namibiano",
	NAD_symbol:"N$",
	NGN_displayName:"Naira Nigeriana",
	NIC_displayName:"Cordoba Nicaraguense",
	NIO_displayName:"Córdoba oro nicaraguense",
	NLG_displayName:"Fiorino Olandese",
	NOK_displayName:"Corona Norvegese",
	NPR_displayName:"Rupia Nepalese",
	NPR_symbol:"Nrs",
	NZD_displayName:"Dollaro Neozelandese",
	NZD_symbol:"$NZ",
	OMR_displayName:"Rial Omanita",
	OMR_symbol:"RO",
	PAB_displayName:"Balboa di Panama",
	PEI_displayName:"Inti Peruviano",
	PEN_displayName:"Sol Nuevo Peruviano",
	PES_displayName:"Sol Peruviano",
	PGK_displayName:"Kina della Papua Nuova Guinea",
	PHP_displayName:"Peso delle Filippine",
	PKR_displayName:"Rupia del Pakistan",
	PKR_symbol:"Pra",
	PLN_displayName:"Zloty Polacco",
	PLN_symbol:"Zl",
	PLZ_displayName:"Zloty Polacco (1950-1995)",
	PTE_displayName:"Escudo Portoghese",
	PYG_displayName:"Guarani del Paraguay",
	QAR_displayName:"Rial del Qatar",
	QAR_symbol:"QR",
	RHD_displayName:"dollaro della Rhodesia",
	ROL_displayName:"Leu della Romania",
	RON_displayName:"leu rumeno",
	RSD_displayName:"Dinaro serbo",
	RUB_displayName:"Rublo Russo",
	RUR_displayName:"Rublo della CSI",
	RWF_displayName:"Franco Ruandese",
	SAR_displayName:"Ryal Saudita",
	SBD_displayName:"Dollaro delle Isole Solomon",
	SBD_symbol:"SI$",
	SCR_displayName:"Rupia delle Seychelles",
	SCR_symbol:"SR",
	SDD_displayName:"Dinaro Sudanese",
	SDP_displayName:"Sterlina Sudanese",
	SEK_displayName:"Corona Svedese",
	SGD_displayName:"Dollaro di Singapore",
	SHP_displayName:"Sterlina di Sant’Elena",
	SIT_displayName:"Tallero Sloveno",
	SKK_displayName:"Corona Slovacca",
	SKK_symbol:"Sk",
	SLL_displayName:"Leone della Sierra Leone",
	SOS_displayName:"Scellino Somalo",
	SOS_symbol:"Sh.",
	SRG_displayName:"Fiorino del Suriname",
	SRG_symbol:"Sf",
	STD_displayName:"Dobra di Sao Tomé e Principe",
	STD_symbol:"Db",
	SUR_displayName:"Rublo Sovietico",
	SVC_displayName:"Colón Salvadoregno",
	SYP_displayName:"Sterlina Siriana",
	SYP_symbol:"LS",
	SZL_displayName:"Lilangeni dello Swaziland",
	SZL_symbol:"E",
	THB_displayName:"Baht Tailandese",
	TJR_displayName:"Rublo del Tajikistan",
	TJS_displayName:"Somoni del Tajikistan",
	TMM_displayName:"Manat Turkmeno",
	TND_displayName:"Dinaro Tunisino",
	TOP_displayName:"Paʻanga di Tonga",
	TOP_symbol:"T$",
	TPE_displayName:"Escudo di Timor",
	TRL_displayName:"Lira Turca",
	TRY_displayName:"nuova Lira turca",
	TTD_displayName:"Dollaro di Trinidad e Tobago",
	TTD_symbol:"TT$",
	TWD_displayName:"Nuovo dollaro taiwanese",
	TWD_symbol:"NT$",
	TZS_displayName:"Scellino della Tanzania",
	TZS_symbol:"T Sh",
	UAH_displayName:"Hrivna Ucraina",
	UAK_displayName:"Karbovanetz Ucraino",
	UGS_displayName:"Scellino Ugandese (1966-1987)",
	UGX_displayName:"Scellino Ugandese",
	UGX_symbol:"U Sh",
	USD_displayName:"Dollaro Statunitense",
	USN_displayName:"Dollaro Statunitense (Next day)",
	USS_displayName:"Dollaro Statunitense (Same day)",
	UYP_displayName:"Peso Uruguaiano (1975-1993)",
	UYU_displayName:"Peso Uruguayo uruguaiano",
	UYU_symbol:"Ur$",
	UZS_displayName:"Sum dell’Uzbekistan",
	VEB_displayName:"Bolivar Venezuelano",
	VEB_symbol:"Be",
	VND_displayName:"Dong Vietnamita",
	VUV_displayName:"Vatu di Vanuatu",
	VUV_symbol:"VT",
	WST_displayName:"Tala della Samoa Occidentale",
	XAF_displayName:"Franco CFA BEAC",
	XAU_displayName:"Oro",
	XBA_displayName:"Unità composita europea",
	XBB_displayName:"Unità monetaria europea",
	XBC_displayName:"Unità di acconto europea (XBC)",
	XBD_displayName:"Unità di acconto europea (XBD)",
	XCD_displayName:"Dollaro dei Caraibi Orientali",
	XCD_symbol:"EC$",
	XDR_displayName:"Diritti Speciali di Incasso",
	XEU_displayName:"Unità Monetaria Europea",
	XFO_displayName:"Franco Oro Francese",
	XFU_displayName:"Franco UIC Francese",
	XOF_displayName:"Franco CFA BCEAO",
	XPF_displayName:"Franco CFP",
	XPF_symbol:"CFPF",
	XPT_displayName:"platino",
	XRE_displayName:"fondi RINET",
	XTS_displayName:"codice di verifica della valuta",
	XXX_displayName:"Nessuna valuta",
	YDD_displayName:"Dinaro dello Yemen",
	YER_displayName:"Rial dello Yemen",
	YER_symbol:"YRl",
	YUD_displayName:"Dinaro Forte Yugoslavo",
	YUM_displayName:"Dinaro Noviy Yugoslavo",
	YUN_displayName:"Dinaro Convertibile Yugoslavo",
	ZAL_displayName:"Rand Sudafricano (finanziario)",
	ZAR_displayName:"Rand Sudafricano",
	ZMK_displayName:"Kwacha dello Zambia",
	ZRN_displayName:"Nuovo Zaire dello Zaire",
	ZRZ_displayName:"Zaire dello Zaire",
	ZWD_displayName:"Dollaro dello Zimbabwe",
	ZWD_symbol:"Z$"
})
                 