define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "dd MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd/MMM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMEd": "E d/M/y GGGGG",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-H": "HH",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);