define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "periodo del giorno",
	"dayPeriods-format-wide-pm": "p.",
	"dateFormatItem-yQ": "Q-yyyy",
	"field-minute": "minuto",
	"eraNames": [
		"a.C.",
		"d.C"
	],
	"dateFormatItem-MMMEd": "EEE d MMM",
	"field-day-relative+-1": "ieri",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "l'altro ieri",
	"field-weekday": "giorno della settimana",
	"field-day-relative+-3": "tre giorni fa",
	"days-standAlone-wide": [
		"Domenica",
		"Lunedì",
		"Martedì",
		"Mercoledì",
		"Giovedì",
		"Venerdì",
		"Sabato"
	],
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"G",
		"F",
		"M",
		"A",
		"M",
		"G",
		"L",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dayPeriods-format-wide-am": "m.",
	"field-era": "era",
	"field-hour": "ora",
	"dateFormatItem-y": "y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "oggi",
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"M",
		"G",
		"V",
		"S"
	],
	"field-day-relative+1": "domani",
	"eraAbbr": [
		"aC",
		"dC"
	],
	"field-day-relative+2": "dopodomani",
	"field-day-relative+3": "tra tre giorni",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"dateFormat-long": "dd MMMM y",
	"timeFormat-medium": "HH:mm:ss",
	"field-zone": "zona",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd/MMM/y",
	"dateFormatItem-yyMM": "MM/yy",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "anno",
	"months-standAlone-wide": [
		"Gennaio",
		"Febbraio",
		"Marzo",
		"Aprile",
		"Maggio",
		"Giugno",
		"Luglio",
		"Agosto",
		"Settembre",
		"Ottobre",
		"Novembre",
		"Dicembre"
	],
	"field-week": "settimana",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"gen",
		"feb",
		"mar",
		"apr",
		"mag",
		"giu",
		"lug",
		"ago",
		"set",
		"ott",
		"nov",
		"dic"
	],
	"timeFormat-short": "HH:mm",
	"field-month": "mese",
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"days-format-abbr": [
		"dom",
		"lun",
		"mar",
		"mer",
		"gio",
		"ven",
		"sab"
	],
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-M": "L",
	"field-second": "secondo",
	"field-day": "giorno",
	"dateFormatItem-MEd": "EEE d/M",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormat-short": "dd/MM/yy",
	"dateFormatItem-yMMMEd": "EEE d MMM y",
	"dateFormat-full": "EEEE d MMMM y",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "EEE, d/M/y",
	"months-format-wide": [
		"gennaio",
		"febbraio",
		"marzo",
		"aprile",
		"maggio",
		"giugno",
		"luglio",
		"agosto",
		"settembre",
		"ottobre",
		"novembre",
		"dicembre"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"1o trimestre",
		"2o trimestre",
		"3o trimestre",
		"4o trimestre"
	],
	"days-format-wide": [
		"domenica",
		"lunedì",
		"martedì",
		"mercoledì",
		"giovedì",
		"venerdì",
		"sabato"
	],
	"dateFormatItem-h": "hh a"
}
//end v1.x content
);