({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "periodo del giorno", 
	"dateFormatItem-yQ": "Q-yyyy", 
	"field-minute": "minuto", 
	"eraNames": [
		"a.C.", 
		"d.C"
	], 
	"dateFormatItem-MMMEd": "EEE d MMM", 
	"dateFormatItem-hms": "hh:mm:ss a", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "giorno della settimana", 
	"days-standAlone-wide": [
		"Domenica", 
		"Lunedì", 
		"Martedì", 
		"Mercoledì", 
		"Giovedì", 
		"Venerdì", 
		"Sabato"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"G", 
		"F", 
		"M", 
		"A", 
		"M", 
		"G", 
		"L", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "era", 
	"field-hour": "ora", 
	"dayPeriods-am-format-wide": "m.", 
	"quarters-standAlone-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dayPeriods-pm-format-wide": "p.", 
	"months-standAlone-abbr": [
		"gen", 
		"feb", 
		"mar", 
		"apr", 
		"mag", 
		"giu", 
		"lug", 
		"ago", 
		"set", 
		"ott", 
		"nov", 
		"dic"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"days-standAlone-narrow": [
		"D", 
		"L", 
		"M", 
		"M", 
		"G", 
		"V", 
		"S"
	], 
	"eraAbbr": [
		"aC", 
		"dC"
	], 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "dd MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "zona", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "dd/MMM/y", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yyQQQQ": "QQQQ yy", 
	"quarters-standAlone-wide": [
		"1o trimestre", 
		"2o trimestre", 
		"3o trimestre", 
		"4o trimestre"
	], 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "anno", 
	"months-standAlone-wide": [
		"Gennaio", 
		"Febbraio", 
		"Marzo", 
		"Aprile", 
		"Maggio", 
		"Giugno", 
		"Luglio", 
		"Agosto", 
		"Settembre", 
		"Ottobre", 
		"Novembre", 
		"Dicembre"
	], 
	"field-week": "settimana", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"gen", 
		"feb", 
		"mar", 
		"apr", 
		"mag", 
		"giu", 
		"lug", 
		"ago", 
		"set", 
		"ott", 
		"nov", 
		"dic"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "mese", 
	"quarters-format-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"days-format-abbr": [
		"dom", 
		"lun", 
		"mar", 
		"mer", 
		"gio", 
		"ven", 
		"sab"
	], 
	"dateFormatItem-MMMMdd": "dd MMMM", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"D", 
		"L", 
		"M", 
		"M", 
		"G", 
		"V", 
		"S"
	], 
	"field-second": "secondo", 
	"field-day": "giorno", 
	"dateFormatItem-MEd": "EEE d/M", 
	"months-format-narrow": [
		"G", 
		"F", 
		"M", 
		"A", 
		"M", 
		"G", 
		"L", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "hh:mm a", 
	"days-standAlone-abbr": [
		"dom", 
		"lun", 
		"mar", 
		"mer", 
		"gio", 
		"ven", 
		"sab"
	], 
	"dateFormat-short": "dd/MM/yy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE, d/M/y", 
	"months-format-wide": [
		"gennaio", 
		"febbraio", 
		"marzo", 
		"aprile", 
		"maggio", 
		"giugno", 
		"luglio", 
		"agosto", 
		"settembre", 
		"ottobre", 
		"novembre", 
		"dicembre"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1o trimestre", 
		"2o trimestre", 
		"3o trimestre", 
		"4o trimestre"
	], 
	"days-format-wide": [
		"domenica", 
		"lunedì", 
		"martedì", 
		"mercoledì", 
		"giovedì", 
		"venerdì", 
		"sabato"
	], 
	"eraNarrow": [
		"aC", 
		"dC"
	], 
	"dateFormatItem-h": "hh a"
})