define(
//begin v1.x content
{
	"dateFormat-medium": "dd/MMM/y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-y": "y G",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyQQQQ": "QQQQ y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-yyyyMEd": "E, d/M/y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyMM": "MM/y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormat-long": "dd MMMM y G",
	"dateFormatItem-yQQQQ": "QQQQ y G",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyQQQ": "QQQ y G",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-Ed": "E d"
}
//end v1.x content
);