define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Adduha wala Aluula",
	"field-minute": "Miniti",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Bi",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "Zaman",
	"field-hour": "Guuru",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Hõo",
	"field-day-relative+1": "Suba",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Leerazuu",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Jiiri",
	"field-week": "Hebu",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Handu",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Miti",
	"field-day": "Zaari",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);