define(
//begin v1.x content
{
	"USD_displayName": "Dɔ́llɔ Amɛŕka",
	"TZS_displayName": "Mɔn Tanzania",
	"ZMW_displayName": "Mɔn Zambia",
	"MAD_displayName": "Mɔn Marɔk",
	"NGN_displayName": "Naïra Nigeria",
	"ZWD_displayName": "Dɔ́llɔ Zimbabwǝ (1980–2008)",
	"SDG_displayName": "Mɔn Sudan",
	"MWK_displayName": "Mɔn Malawi",
	"KMF_displayName": "Fraŋ bó Kɔmɔr",
	"SCR_displayName": "Mɔn Seychɛlle",
	"EGP_displayName": "Mɔn Ägyptɛn",
	"CVE_displayName": "Mɔn Kapvɛrt",
	"LYD_displayName": "Mɔn Libya",
	"CAD_displayName": "Dɔ́llɔ Kanada",
	"INR_displayName": "Mɔn India",
	"JPY_displayName": "Mɔn Japɔn",
	"LRD_displayName": "Dɔ́llɔ Liberia",
	"ZAR_displayName": "Mɔn Afrik yí sí",
	"AOA_displayName": "Mɔn Angola",
	"TND_displayName": "Mɔn Tunisia",
	"GHC_displayName": "Mɔn Gana",
	"BWP_displayName": "Mɔn Botswana",
	"DZD_displayName": "Mɔn Algeria",
	"ZMK_displayName": "Mɔn Zambia (1968–2012)",
	"NAD_displayName": "Dɔ́llɔ Namibia",
	"AED_displayName": "Mɔn B ´Arabe",
	"ETB_displayName": "Mɔn Ethiopia",
	"MZM_displayName": "Mɔn Mozambik",
	"BIF_displayName": "Fraŋ Burundi",
	"RWF_displayName": "Fraŋ Rwanda",
	"STD_displayName": "Mɔn Sao tomé na prinship",
	"SZL_displayName": "Mɔn Ligangeni",
	"EUR_displayName": "Euro",
	"ERN_displayName": "Mɔn Erytré",
	"SAR_displayName": "Mɔn Saudi Arabia",
	"DJF_displayName": "Fraŋ Jibuti",
	"CDF_displayName": "Fraŋ bó Kongolɛ̌",
	"GBP_displayName": "Mɔn Ngɛ̄lɛ̄n",
	"CHF_displayName": "Fraŋ Suisse",
	"MUR_displayName": "Mɔn Moriss",
	"SOS_displayName": "Mɔn Somalía",
	"BHD_displayName": "Mɔn Bahrein",
	"XOF_displayName": "Fraŋ CFA BCEAO",
	"GNS_displayName": "Fraŋ Guiné",
	"SLL_displayName": "Mɔn Leɔne",
	"UGX_displayName": "Mɔn Uganda",
	"MGA_displayName": "Mɔn Madagaskar",
	"SDP_displayName": "Mɔn Sudan (1957–1998)",
	"AUD_displayName": "Dɔ́llɔ Ɔstralia",
	"KES_displayName": "Mɔn Kɛnya",
	"SHP_displayName": "Mɔn má Saint Lina",
	"XAF_displayName": "Fraŋ CFA BEAC",
	"LSL_displayName": "Mɔn Lesoto",
	"MRO_displayName": "Mɔn Moritania",
	"CNY_displayName": "Mɔn bó Chinois",
	"GMD_displayName": "Mɔn Gambia"
}
//end v1.x content
);