define(
//begin v1.x content
{
	"USD_displayName": "adular n iwunak imunn",
	"TZS_displayName": "acilin n ṭanẓanya",
	"ZMW_displayName": "akwaca n zambya",
	"MAD_displayName": "adrim n lmɣrib",
	"NGN_displayName": "nayra n nijirya",
	"ZWD_displayName": "adular n zimbabwi",
	"SDG_displayName": "adinar n ssudan",
	"MWK_displayName": "kwaca n malawi",
	"KMF_displayName": "frank n qumuṛ",
	"SCR_displayName": "arubi n ssicil",
	"EGP_displayName": "ajnih n miṣṛ",
	"CVE_displayName": "iskudu n kabbirdi",
	"LYD_displayName": "adinar n libya",
	"CAD_displayName": "adular n kanada",
	"INR_displayName": "arubi n lhind",
	"JPY_displayName": "ayan n lyaban",
	"LRD_displayName": "adular n libirya",
	"ZAR_displayName": "arand n afriqya n iffus",
	"AOA_displayName": "kwanza n angula",
	"TND_displayName": "adinar n tuns",
	"GHC_displayName": "sidi n ɣana",
	"BWP_displayName": "abula n butswana",
	"DZD_displayName": "adinar n dzayr",
	"ZMK_displayName": "akwaca n zambya (1968–2012)",
	"NAD_displayName": "adular n namibya",
	"AED_displayName": "adrim n limarat",
	"ETB_displayName": "bir n ityubya",
	"MZM_displayName": "amitikl n muznbiq",
	"BIF_displayName": "frank n burundi",
	"RWF_displayName": "afrank n rwanda",
	"STD_displayName": "adubra n sanṭumi",
	"SZL_displayName": "lilanjini",
	"EUR_displayName": "uru",
	"ERN_displayName": "nafka n iritirya",
	"SAR_displayName": "aryal n ssaɛudiya",
	"DJF_displayName": "frank n djibuti",
	"CDF_displayName": "frank n kungu",
	"GBP_displayName": "ajnih astrlini n nngliz",
	"CHF_displayName": "afrank n swisra",
	"MUR_displayName": "arubi n muris",
	"SOS_displayName": "acilin n ṣṣumal",
	"BHD_displayName": "adinar n bḥrayn",
	"XOF_displayName": "frank ṣifa bisaw",
	"GNS_displayName": "frank n ɣinya",
	"SLL_displayName": "liyun",
	"UGX_displayName": "acilin n uɣanda",
	"MGA_displayName": "frank n madaɣacqar",
	"SDP_displayName": "ajnih n ssudan",
	"AUD_displayName": "adular n ustralya",
	"KES_displayName": "acilin n kinya",
	"SHP_displayName": "ajnih n santilin",
	"XAF_displayName": "frank ṣifa",
	"LSL_displayName": "luti n liṣuṭu",
	"MRO_displayName": "uqiyya n muṛiṭanya",
	"CNY_displayName": "ayan n ccinwa",
	"GMD_displayName": "dalasi n gambya"
}
//end v1.x content
);