define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "tizi g wass: tifawt / tadggʷat",
	"field-minute": "tusdidt",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "iḍlli",
	"field-weekday": "ass g imalass",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "tasut",
	"field-hour": "tasragt",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "assa",
	"field-day-relative+1": "askka",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "akud n ugmmaḍ",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "asggʷas",
	"field-week": "imalass",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "ayyur",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"field-second": "tasint",
	"field-day": "ass",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);