define(
//begin v1.x content
{
	"field-tue-relative+-1": "prošli utorak",
	"field-year": "godina",
	"field-wed-relative+0": "ova srijeda",
	"field-wed-relative+1": "sljedeća srijeda",
	"field-minute": "minuta",
	"field-month-narrow-relative+-1": "↑↑↑",
	"field-tue-narrow-relative+0": "ovaj uto.",
	"field-tue-narrow-relative+1": "sljedeći uto.",
	"field-thu-short-relative+0": "ovaj čet.",
	"field-day-short-relative+-1": "↑↑↑",
	"field-thu-short-relative+1": "sljedeći čet.",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-week-narrow-relative+0": "↑↑↑",
	"field-day-relative+2": "prekosutra",
	"field-week-narrow-relative+1": "↑↑↑",
	"field-wed-narrow-relative+-1": "prošla sri.",
	"field-year-narrow": "g.",
	"field-era-short": "era",
	"field-year-narrow-relative+0": "↑↑↑",
	"field-tue-relative+0": "ovaj utorak",
	"field-year-narrow-relative+1": "↑↑↑",
	"field-tue-relative+1": "sljedeći utorak",
	"field-weekdayOfMonth": "dan u mjesecu",
	"field-second-short": "sek.",
	"dateFormatItem-MMMd": "d. MMM",
	"field-weekdayOfMonth-narrow": "d. u mj.",
	"field-week-relative+0": "ove sedmice",
	"field-month-relative+0": "ovaj mjesec",
	"field-week-relative+1": "sljedeće sedmice",
	"field-month-relative+1": "sljedeći mjesec",
	"field-sun-narrow-relative+0": "ova ned.",
	"field-mon-short-relative+0": "ovaj pon.",
	"field-sun-narrow-relative+1": "sljedeća ned.",
	"field-mon-short-relative+1": "sljedeći pon",
	"field-second-relative+0": "sada",
	"field-weekOfMonth": "sedmica u mjesecu",
	"field-month-short": "mj.",
	"field-day": "dan",
	"field-dayOfYear-short": "dan u god.",
	"field-year-relative+-1": "prošle godine",
	"field-sat-short-relative+-1": "prošla sub.",
	"field-hour-relative+0": "ovaj sat",
	"field-wed-relative+-1": "prošla srijeda",
	"field-sat-narrow-relative+-1": "prošla sub.",
	"field-second": "sekunda",
	"field-quarter": "kvartal",
	"field-week-short": "sed.",
	"field-day-narrow-relative+0": "↑↑↑",
	"field-day-narrow-relative+1": "↑↑↑",
	"field-tue-short-relative+0": "ovaj uto.",
	"field-tue-short-relative+1": "sljedeći uto.",
	"field-month-short-relative+-1": "↑↑↑",
	"field-mon-relative+-1": "prošli ponedjeljak",
	"field-month": "mjesec",
	"field-day-narrow": "dan",
	"dateFormatItem-MMM": "LLL",
	"field-minute-short": "min.",
	"field-dayperiod": "prijepodne/poslijepodne",
	"field-sat-short-relative+0": "ova sub.",
	"field-sat-short-relative+1": "sljedeća sub.",
	"eraAbbr": [
		"prije R.O.C.",
		"R.O.C."
	],
	"field-second-narrow": "s",
	"field-mon-relative+0": "ovaj ponedjeljak",
	"field-mon-relative+1": "sljedeći ponedjeljak",
	"field-day-narrow-relative+-1": "↑↑↑",
	"field-year-short": "god.",
	"field-quarter-relative+-1": "posljednji kvartal",
	"field-dayperiod-narrow": "prijepodne/poslijepodne",
	"field-week-narrow-relative+-1": "↑↑↑",
	"field-dayOfYear": "dan u godini",
	"field-sat-relative+-1": "prošla subota",
	"field-hour": "sat",
	"field-month-relative+-1": "prošli mjesec",
	"field-quarter-short": "kv.",
	"field-sat-narrow-relative+0": "ova sub.",
	"field-fri-relative+0": "ovaj petak",
	"field-sat-narrow-relative+1": "sljedeća sub.",
	"field-fri-relative+1": "sljedeći petak",
	"field-month-narrow-relative+0": "↑↑↑",
	"field-month-narrow-relative+1": "↑↑↑",
	"field-sun-short-relative+0": "ova ned.",
	"field-sun-short-relative+1": "sljedeća ned.",
	"field-week-relative+-1": "prošle sedmice",
	"field-quarter-relative+0": "ovaj kvartal",
	"field-minute-relative+0": "ova minuta",
	"field-quarter-relative+1": "sljedeći kvartal",
	"field-wed-short-relative+-1": "prošla sri.",
	"field-thu-short-relative+-1": "prošli čet.",
	"field-year-narrow-relative+-1": "↑↑↑",
	"field-mon-narrow-relative+-1": "prošli pon.",
	"field-thu-narrow-relative+-1": "prošli čet.",
	"field-tue-narrow-relative+-1": "prošli uto.",
	"field-weekOfMonth-short": "sed. u mj.",
	"field-wed-short-relative+0": "ova sri.",
	"dateFormatItem-M": "L.",
	"field-wed-short-relative+1": "sljedeća sri.",
	"field-sun-relative+-1": "prošla nedjelja",
	"dateFormatItem-d": "d.",
	"field-weekday": "dan u sedmici",
	"field-day-short-relative+0": "↑↑↑",
	"field-sat-relative+0": "ova subota",
	"field-day-short-relative+1": "↑↑↑",
	"field-sat-relative+1": "sljedeća subota",
	"field-week-short-relative+0": "↑↑↑",
	"field-week-short-relative+1": "↑↑↑",
	"field-dayOfYear-narrow": "dan u g.",
	"field-month-short-relative+0": "↑↑↑",
	"field-month-short-relative+1": "↑↑↑",
	"field-weekdayOfMonth-short": "dan u mj.",
	"field-zone-narrow": "zona",
	"field-thu-narrow-relative+0": "ovaj čet.",
	"field-thu-narrow-relative+1": "sljedeći čet.",
	"field-sun-narrow-relative+-1": "prošla ned.",
	"field-mon-short-relative+-1": "prošli pon.",
	"field-thu-relative+0": "ovaj četvrtak",
	"field-thu-relative+1": "sljedeći četvrtak",
	"field-fri-short-relative+-1": "prošli pet.",
	"field-thu-relative+-1": "prošli četvrtak",
	"field-week": "sedmica",
	"field-wed-narrow-relative+0": "ova sri.",
	"field-wed-narrow-relative+1": "sljedeća sri.",
	"field-year-short-relative+0": "↑↑↑",
	"field-dayperiod-short": "prijepodne/poslijepodne",
	"field-year-short-relative+1": "↑↑↑",
	"field-fri-short-relative+0": "ovaj pet.",
	"field-fri-short-relative+1": "sljedeći pet.",
	"field-week-short-relative+-1": "↑↑↑",
	"field-hour-short": "h",
	"field-zone-short": "zona",
	"field-month-narrow": "mj.",
	"field-hour-narrow": "h",
	"field-fri-narrow-relative+-1": "prošli pet.",
	"field-year-relative+0": "ove godine",
	"field-year-relative+1": "sljedeće godine",
	"field-era-narrow": "era",
	"field-fri-relative+-1": "prošli petak",
	"field-tue-short-relative+-1": "prošli uto.",
	"field-minute-narrow": "min.",
	"field-mon-narrow-relative+0": "ovaj pon.",
	"field-mon-narrow-relative+1": "sljedeći pon.",
	"field-year-short-relative+-1": "↑↑↑",
	"field-zone": "vremenska zona",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"field-weekOfMonth-narrow": "s. u mj.",
	"field-weekday-narrow": "dan u sed.",
	"field-quarter-narrow": "kv.",
	"field-sun-short-relative+-1": "prošla ned.",
	"field-day-relative+-1": "jučer",
	"field-day-relative+-2": "prekjučer",
	"field-weekday-short": "dan u sed.",
	"field-sun-relative+0": "ova nedjelja",
	"field-sun-relative+1": "sljedeća nedjelja",
	"field-day-short": "dan",
	"field-week-narrow": "sed.",
	"field-era": "era",
	"field-fri-narrow-relative+0": "ovaj pet.",
	"field-fri-narrow-relative+1": "sljedeći pet."
}
//end v1.x content
);