define(
//begin v1.x content
{
	"dateFormatItem-Ehm": "E h:mm a",
	"days-standAlone-short": [
		"კვ",
		"ორ",
		"სმ",
		"ოთ",
		"ხთ",
		"პრ",
		"შბ"
	],
	"months-format-narrow": [
		"ი",
		"თ",
		"მ",
		"ა",
		"მ",
		"ი",
		"ი",
		"ა",
		"ს",
		"ო",
		"ნ",
		"დ"
	],
	"field-second-relative+0": "ახლა",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-weekday": "კვირის დღე",
	"dateFormatItem-yQQQ": "QQQ, y",
	"dateFormatItem-yMEd": "E, d.M.y",
	"field-wed-relative+0": "ამ ოთხშაბათს",
	"field-wed-relative+1": "მომავალ ოთხშაბათს",
	"dateFormatItem-GyMMMEd": "E, d MMM, y G",
	"dateFormatItem-MMMEd": "E, d MMM",
	"eraNarrow": [
		"ძვ. წ.",
		"ახ. წ."
	],
	"field-tue-relative+-1": "გასულ სამშაბათს",
	"days-format-short": [
		"კვ",
		"ორ",
		"სმ",
		"ოთ",
		"ხთ",
		"პრ",
		"შბ"
	],
	"dateFormat-long": "d MMMM, y",
	"field-fri-relative+-1": "გასულ პარასკევს",
	"field-wed-relative+-1": "გასულ ოთხშაბათს",
	"months-format-wide": [
		"იანვარი",
		"თებერვალი",
		"მარტი",
		"აპრილი",
		"მაისი",
		"ივნისი",
		"ივლისი",
		"აგვისტო",
		"სექტემბერი",
		"ოქტომბერი",
		"ნოემბერი",
		"დეკემბერი"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "საღამოს",
	"dateFormat-full": "EEEE, dd MMMM, y",
	"field-thu-relative+-1": "გასულ ხუთშაბათს",
	"dateFormatItem-Md": "d.M",
	"dayPeriods-format-abbr-am": "AM",
	"dateFormatItem-yMd": "d.M.y",
	"field-era": "ეპოქა",
	"dateFormatItem-yM": "M.y",
	"months-standAlone-wide": [
		"იანვარი",
		"თებერვალი",
		"მარტი",
		"აპრილი",
		"მაისი",
		"ივნისი",
		"ივლისი",
		"აგვისტო",
		"სექტემბერი",
		"ოქტომბერი",
		"ნოემბერი",
		"დეკემბერი"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"I კვარტალი",
		"II კვარტალი",
		"III კვარტალი",
		"IV კვარტალი"
	],
	"dateFormatItem-yQQQQ": "QQQQ, y",
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "წელი",
	"dateFormatItem-yMMM": "MMM, y",
	"field-hour": "საათი",
	"months-format-abbr": [
		"იან",
		"თებ",
		"მარ",
		"აპრ",
		"მაი",
		"ივნ",
		"ივლ",
		"აგვ",
		"სექ",
		"ოქტ",
		"ნოე",
		"დეკ"
	],
	"field-sat-relative+0": "ამ შაბათს",
	"field-sat-relative+1": "მომავალ შაბათს",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "დღეს",
	"field-thu-relative+0": "ამ ხუთშაბათს",
	"field-day-relative+1": "ხვალ",
	"field-thu-relative+1": "მომავალ ხუთშაბათს",
	"dateFormatItem-GyMMMd": "d MMM, y G",
	"field-day-relative+2": "ზეგ",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"იან",
		"თებ",
		"მარ",
		"აპრ",
		"მაი",
		"ივნ",
		"ივლ",
		"აგვ",
		"სექ",
		"ოქტ",
		"ნოე",
		"დეკ"
	],
	"quarters-format-abbr": [
		"I კვ.",
		"II კვ.",
		"III კვ.",
		"IV კვ."
	],
	"quarters-standAlone-wide": [
		"I კვარტალი",
		"II კვარტალი",
		"III კვარტალი",
		"IV კვარტალი"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"კვირა",
		"ორშაბათი",
		"სამშაბათი",
		"ოთხშაბათი",
		"ხუთშაბათი",
		"პარასკევი",
		"შაბათი"
	],
	"timeFormat-medium": "HH:mm:ss",
	"field-sun-relative+0": "ამ კვირას",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "მომავალ კვირას",
	"quarters-standAlone-abbr": [
		"I კვ.",
		"II კვ.",
		"III კვ.",
		"IV კვ."
	],
	"eraAbbr": [
		"ძვ. წ.",
		"ახ. წ."
	],
	"field-minute": "წუთი",
	"field-dayperiod": "დღის ნახევარი",
	"days-standAlone-abbr": [
		"კვი",
		"ორშ",
		"სამ",
		"ოთხ",
		"ხუთ",
		"პარ",
		"შაბ"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "გუშინ",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1}, {0}",
	"dayPeriods-format-narrow-am": "AM",
	"field-day-relative+-2": "გუშინწინ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d.M",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "ამ პარასკევს",
	"field-fri-relative+1": "მომავალ პარასკევს",
	"field-day": "დღე",
	"days-format-wide": [
		"კვირა",
		"ორშაბათი",
		"სამშაბათი",
		"ოთხშაბათი",
		"ხუთშაბათი",
		"პარასკევი",
		"შაბათი"
	],
	"field-zone": "დროის სარტყელი",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"ი",
		"თ",
		"მ",
		"ა",
		"მ",
		"ი",
		"ი",
		"ა",
		"ს",
		"ო",
		"ნ",
		"დ"
	],
	"field-year-relative+-1": "გასულ წელს",
	"field-month-relative+-1": "გასულ თვეს",
	"dateFormatItem-hm": "h:mm a",
	"dayPeriods-format-abbr-pm": "PM",
	"days-format-abbr": [
		"კვი",
		"ორშ",
		"სამ",
		"ოთხ",
		"ხუთ",
		"პარ",
		"შაბ"
	],
	"dateFormatItem-yMMMd": "d MMM, y",
	"eraNames": [
		"ძველი წელთაღრიცხვით",
		"ახალი წელთაღრიცხვით"
	],
	"days-format-narrow": [
		"კ",
		"ო",
		"ს",
		"ო",
		"ხ",
		"პ",
		"შ"
	],
	"days-standAlone-narrow": [
		"კ",
		"ო",
		"ს",
		"ო",
		"ხ",
		"პ",
		"შ"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "თვე",
	"field-tue-relative+0": "ამ სამშაბათს",
	"field-tue-relative+1": "მომავალ სამშაბათს",
	"dayPeriods-format-wide-am": "დილის",
	"dateFormatItem-EHm": "E HH:mm",
	"field-mon-relative+0": "ამ ორშაბათს",
	"field-mon-relative+1": "მომავალ ორშაბათს",
	"dateFormat-short": "dd.MM.yy",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"field-second": "წამი",
	"field-sat-relative+-1": "გასულ შაბათს",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"field-sun-relative+-1": "გასულ კვირას",
	"field-month-relative+0": "ამ თვეში",
	"field-month-relative+1": "მომავალ თვეს",
	"dateFormatItem-Ed": "d E",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-week": "კვირა",
	"dateFormat-medium": "d MMM, y",
	"field-year-relative+0": "ამ წელს",
	"field-week-relative+-1": "გასულ კვირაში",
	"field-year-relative+1": "მომავალ წელს",
	"dayPeriods-format-narrow-pm": "PM",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM, y G",
	"field-mon-relative+-1": "გასულ ორშაბათს",
	"field-week-relative+0": "ამ კვირაში",
	"field-week-relative+1": "მომავალ კვირაში"
}
//end v1.x content
);