define(
//begin v1.x content
{
	"USD_displayName": "Dɔla àmerkà",
	"TZS_displayName": "Silîŋ tànzànià",
	"ZMW_displayName": "Kwàca sàmbià",
	"MAD_displayName": "Dìrham màrôk",
	"NGN_displayName": "Nayrà nìgerìà",
	"ZWD_displayName": "Dɔ̀lâr sìmbàbwê",
	"SDG_displayName": "Dìnâr sùdân",
	"MWK_displayName": "Kwaca màlawì",
	"KMF_displayName": "Frǎŋ kòmorà",
	"SCR_displayName": "Rùpiɛ̀ sèsɛ̂l",
	"EGP_displayName": "Paùnd ègîptò",
	"CVE_displayName": "Èskudò kabwe᷆r",
	"LYD_displayName": "Dìnâr libìà",
	"CAD_displayName": "Dɔ̀lâr kànadà",
	"INR_displayName": "Rùpi īndìà",
	"JPY_displayName": "Yɛ̂n yàpân",
	"LRD_displayName": "Dɔ̀lâr lìberìà",
	"ZAR_displayName": "Rân àfrǐkàsɔ̀",
	"AOA_displayName": "Kwànza àŋgolà",
	"TND_displayName": "Dìnâr tùnîs",
	"GHC_displayName": "Sèdi gānà",
	"BWP_displayName": "Pùla Bòtswanà",
	"DZD_displayName": "Dìnâr àlgerìà",
	"ZMK_displayName": "Kwàca sàmbià (1968–2012)",
	"NAD_displayName": "Dɔ̀lâr nàmibìà",
	"AED_displayName": "Dirhàm èmìrâ",
	"ETB_displayName": "Bîr ètìopìà",
	"MZM_displayName": "Mètìkal mòsàmbîk",
	"BIF_displayName": "Frǎŋ bùrundì",
	"RWF_displayName": "Frǎŋ Rùandà",
	"STD_displayName": "Dobrà sàotòme",
	"SZL_displayName": "Lìlàŋgeni swàzì",
	"EUR_displayName": "Èrô",
	"ERN_displayName": "Nafkà èrìtrěà",
	"SAR_displayName": "Rìal sàudì",
	"DJF_displayName": "Frǎŋ jìbutì",
	"CDF_displayName": "Frǎŋ kòŋgo",
	"GBP_displayName": "Stɛrlìŋ ŋgìsì",
	"CHF_displayName": "Frǎŋ sùwîs",
	"MUR_displayName": "Rupìɛ̀ mòrîs",
	"SOS_displayName": "Silîŋ sòmàli",
	"BHD_displayName": "Dinâr Bàraìn",
	"XOF_displayName": "Frǎŋ CFA (BCEAO)",
	"GNS_displayName": "Frǎŋ gìnê",
	"SLL_displayName": "Lèonɛ̀",
	"UGX_displayName": "Silîŋ ùgàndà",
	"MGA_displayName": "Frǎŋ màlàgasì",
	"SDP_displayName": "Paùnd sùdân",
	"AUD_displayName": "Dɔ̀lâr òstralìà",
	"KES_displayName": "Silîŋ kenìà",
	"SHP_displayName": "Paùnd hèlenà",
	"XAF_displayName": "Frǎŋ CFA (BEAC)",
	"LSL_displayName": "Lotì lèsòtò",
	"MRO_displayName": "Ùgwiya mòrìtanìa",
	"CNY_displayName": "Yùan kinà",
	"GMD_displayName": "Dalasì gambìà"
}
//end v1.x content
);