define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "njǎmùha",
	"field-minute": "ŋget",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "yààni",
	"field-weekday": "hìlɔ hi sɔndɛ̂",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "kèk",
	"field-hour": "ŋgɛŋ",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "lɛ̀n",
	"field-day-relative+1": "yàni",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "komboo i ŋgɛŋ",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "ŋwìi",
	"field-week": "sɔndɛ̂",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "soŋ",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "hìŋgeŋget",
	"field-day": "kɛl",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);