define(
//begin v1.x content
{
	"USD_displayName": "Dọla ti Orílẹ́ède Amerika",
	"TZS_displayName": "Sile ti Orílẹ́ède Tansania",
	"ZMW_displayName": "Kawaṣa ti Orílẹ́ède Saabia",
	"MAD_displayName": "Dirami ti Orílẹ́ède Moroko",
	"NGN_displayName": "Naira ti Orílẹ́ède Nàìjíríà",
	"ZWD_displayName": "Dọla ti Orílẹ́ède Siibabuwe",
	"SDG_displayName": "Dina ti Orílẹ́ède Sudani",
	"MWK_displayName": "Kaṣa ti Orílẹ́ède Malawi",
	"KMF_displayName": "Faransi ti Orílẹ́ède ṣomoriani",
	"SCR_displayName": "Rupi ti Orílẹ́ède Sayiselesi",
	"EGP_displayName": "pọọn ti Orílẹ́ède Egipiti",
	"CVE_displayName": "Kabofediano ti Orílẹ́ède Esuodo",
	"LYD_displayName": "Dina ti Orílẹ́ède Libiya",
	"CAD_displayName": "Dọla ti Orílẹ́ède Kánádà",
	"INR_displayName": "Rupi ti Orílẹ́ède Indina",
	"JPY_displayName": "Yeni ti Orílẹ́ède Japani",
	"LRD_displayName": "Dọla ti Orílẹ́ède Liberia",
	"ZAR_displayName": "Randi ti Orílẹ́ède Ariwa Afirika",
	"AOA_displayName": "Wansa ti Orílẹ́ède Àngólà",
	"TND_displayName": "Dina ti Orílẹ́ède Tunisia",
	"GHC_displayName": "ṣidi ti Orílẹ́ède Gana",
	"BWP_displayName": "Pula ti Orílẹ́ède Bọ̀tìsúwánà",
	"DZD_displayName": "Dina ti Orílẹ́ède Àlùgèríánì",
	"ZMK_displayName": "Kawaṣa ti Orílẹ́ède Saabia (1968–2012)",
	"NAD_displayName": "Dọla ti Orílẹ́ède Namibia",
	"AED_displayName": "Diami ti Awon Orílẹ́ède Arabu",
	"ETB_displayName": "Biri ti Orílẹ́ède Eutopia",
	"MZM_displayName": "Metika ti Orílẹ́ède Mosamibiki",
	"BIF_displayName": "Faransi ti Orílẹ́ède Bùùrúndì",
	"RWF_displayName": "Faransi ti Orílẹ́ède Ruwanda",
	"STD_displayName": "Dobira ti Orílẹ́ède Sao tome Ati Pirisipe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Uro",
	"ERN_displayName": "Nakifa ti Orílẹ́ède Eriteriani",
	"SAR_displayName": "Riya ti Orílẹ́ède Saudi",
	"DJF_displayName": "Faransi ti Orílẹ́ède Dibouti",
	"CDF_displayName": "Faransi ti Orílẹ́ède Kóngò",
	"GBP_displayName": "Pọọn ti Orílẹ́ède Bírítísì",
	"CHF_displayName": "Faransi ti Orílẹ́ède Siwisi",
	"MUR_displayName": "Rupi ti Orílẹ́ède Maritiusi",
	"SOS_displayName": "Sile ti Orílẹ́ède Somali",
	"BHD_displayName": "Dina ti Orílẹ́ède Báránì",
	"XOF_displayName": "Faransi ti Orílẹ́ède BIKEAO",
	"GNS_displayName": "Faransi ti Orílẹ́ède Gini",
	"SLL_displayName": "Lioni",
	"UGX_displayName": "Siile ti Orílẹ́ède Uganda",
	"MGA_displayName": "Faransi ti Orílẹ́ède Malagasi",
	"SDP_displayName": "Pọọun ti Orílẹ́ède Sudani",
	"AUD_displayName": "Dọla ti Orílẹ́ède Ástràlìá",
	"KES_displayName": "ṣiili ti Orílẹ́ède Kenya",
	"SHP_displayName": "Pọọun ti Orílẹ́ède ̣Elena",
	"XAF_displayName": "Faransi ti Orílẹ́ède BEKA",
	"LSL_displayName": "Loti ti Orílẹ́ède Lesoto",
	"MRO_displayName": "Ouguiya ti Orílẹ́ède Maritania",
	"NGN_symbol": "₦",
	"CNY_displayName": "Reminibi ti Orílẹ́ède ṣáínà",
	"GMD_displayName": "Dalasi ti Orílẹ́ède Gamibia"
}
//end v1.x content
);