define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Àárọ̀/ọ̀sán",
	"field-minute": "Ìsẹ́jú",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Àná",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "íjẹta",
	"field-weekday": "Ọjọ́ Ọ̀sẹ̀",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Ìgbà",
	"field-hour": "wákàtí",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Òní",
	"field-day-relative+1": "Ọ̀la",
	"field-day-relative+2": "òtúùnla",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Ibi Àkókò Àgbáyé",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Ọdún",
	"field-week": "Ọ̀sè",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Osù",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "Ìsẹ́jú Ààyá",
	"field-day": "Ọjọ́",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);