define(
//begin v1.x content
{
	"USD_displayName": "dola ya Marekani",
	"TZS_displayName": "shilingi ya Tandhania",
	"ZMW_displayName": "kwacha ya Dhambia",
	"MAD_displayName": "dirham ya Moroko",
	"NGN_displayName": "naira ya Nijeria",
	"ZWD_displayName": "dola ya Dhimbabwe",
	"SDG_displayName": "dinari ya Thudani",
	"MWK_displayName": "kwacha ya Malawi",
	"KMF_displayName": "faranga ya Komoro",
	"SCR_displayName": "rupia ya Shelisheli",
	"EGP_displayName": "pauni ya Mithri",
	"CVE_displayName": "ethkudo ya Kepuvede",
	"LYD_displayName": "dinari ya Libya",
	"CAD_displayName": "dola ya Kanada",
	"INR_displayName": "rupia ya India",
	"JPY_displayName": "tharafu ya Kijapani",
	"TZS_symbol": "TSh",
	"LRD_displayName": "dola ya Liberia",
	"ZAR_displayName": "randi ya Afrika Kuthini",
	"AOA_displayName": "kwandha ya Angola",
	"TND_displayName": "dinari ya Tunithia",
	"GHC_displayName": "thedi ya Ghana",
	"BWP_displayName": "pula ya Botthwana",
	"DZD_displayName": "dinari ya Aljeria",
	"ZMK_displayName": "kwacha ya Dhambia (1968–2012)",
	"NAD_displayName": "dola ya Namibia",
	"AED_displayName": "dirham ya Falme dha Kiarabu",
	"ETB_displayName": "bir ya Uhabeshi",
	"MZM_displayName": "metikali ya Mthumbiji",
	"BIF_displayName": "faranga ya Burundi",
	"RWF_displayName": "faranga ya Rwanda",
	"STD_displayName": "dobra ya Thao Tome na Principe",
	"SZL_displayName": "lilangeni",
	"EUR_displayName": "yuro",
	"ERN_displayName": "nakfa ya Eritrea",
	"SAR_displayName": "riyal ya Thaudia",
	"DJF_displayName": "faranga ya Jibuti",
	"CDF_displayName": "faranga ya Kongo",
	"GBP_displayName": "pauni ya Uingeredha",
	"CHF_displayName": "faranga ya Uthwithi",
	"MUR_displayName": "rupia ya Morithi",
	"SOS_displayName": "shilingi ya Thomalia",
	"BHD_displayName": "dinari ya Bahareni",
	"XOF_displayName": "faranga CFA BCEAO",
	"GNS_displayName": "faranga ya Gine",
	"SLL_displayName": "leoni",
	"UGX_displayName": "shilingi ya Uganda",
	"MGA_displayName": "faranga ya Bukini",
	"SDP_displayName": "pauni ya Thudani",
	"AUD_displayName": "dola ya Authtralia",
	"KES_displayName": "shilingi ya Kenya",
	"SHP_displayName": "pauni ya Thantahelena",
	"XAF_displayName": "faranga CFA BEAC",
	"LSL_displayName": "loti ya Lethoto",
	"MRO_displayName": "ugwiya ya Moritania",
	"CNY_displayName": "yuan renminbi ya China",
	"GMD_displayName": "dalathi ya Gambia"
}
//end v1.x content
);