define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Marango athiku",
	"field-minute": "Dakika",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Ighuo",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-weekday": "Thiku ya ndisha",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Edhi",
	"field-hour": "Thaa",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Iyoo",
	"field-day-relative+1": "Yavo",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Majira Athaa",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Mwaka",
	"field-week": "Ndisha",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Mweji",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Thekunde",
	"field-day": "Thiku",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);