define(
//begin v1.x content
{
	"dateFormatItem-yM": "M.yyyy",
	"field-dayperiod": "perioada zilei",
	"dayPeriods-format-wide-pm": "PM",
	"dateFormatItem-yQ": "'trimestrul' Q y",
	"field-minute": "minut",
	"eraNames": [
		"înainte de Hristos",
		"după Hristos"
	],
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "ieri",
	"dateFormatItem-MMdd": "dd.MM",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "alaltăieri",
	"field-weekday": "zi a săptămânii",
	"field-day-relative+-3": "răsalaltăieri",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"I",
		"F",
		"M",
		"A",
		"M",
		"I",
		"I",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dateTimeFormat-short": "{1}, {0}",
	"dayPeriods-format-wide-am": "AM",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-era": "eră",
	"field-hour": "oră",
	"dateFormatItem-y": "y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "azi",
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"M",
		"J",
		"V",
		"S"
	],
	"field-day-relative+1": "mâine",
	"eraAbbr": [
		"î.Hr.",
		"d.Hr."
	],
	"field-day-relative+2": "poimâine",
	"field-day-relative+3": "răspoimâine",
	"dateFormatItem-yyyyMM": "MM.yyyy",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"dateFormat-long": "d MMMM y",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-EEEd": "EEE d",
	"field-zone": "zonă",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd.MM.yyyy",
	"dateFormatItem-yyMM": "MM.yy",
	"dateFormatItem-yyMMM": "MMM yy",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "an",
	"quarters-standAlone-narrow": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "săptămână",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"ian.",
		"feb.",
		"mar.",
		"apr.",
		"mai",
		"iun.",
		"iul.",
		"aug.",
		"sept.",
		"oct.",
		"nov.",
		"dec."
	],
	"timeFormat-short": "HH:mm",
	"field-month": "lună",
	"quarters-format-abbr": [
		"trim. I",
		"trim. II",
		"trim. III",
		"trim. IV"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"days-format-abbr": [
		"Du",
		"Lu",
		"Ma",
		"Mi",
		"Jo",
		"Vi",
		"Sâ"
	],
	"dateFormatItem-M": "L",
	"field-second": "secundă",
	"field-day": "zi",
	"dateFormatItem-MEd": "E, d MMM",
	"dateFormatItem-MMMEEEd": "EEE, d MMM",
	"dateFormat-short": "dd.MM.yyyy",
	"dateFormatItem-yMMMEd": "EEE, d MMM y",
	"dateFormat-full": "EEEE, d MMMM y",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-yMEd": "EEE, d/M/yyyy",
	"months-format-wide": [
		"ianuarie",
		"februarie",
		"martie",
		"aprilie",
		"mai",
		"iunie",
		"iulie",
		"august",
		"septembrie",
		"octombrie",
		"noiembrie",
		"decembrie"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"trimestrul I",
		"trimestrul al II-lea",
		"trimestrul al III-lea",
		"trimestrul al IV-lea"
	],
	"days-format-wide": [
		"duminică",
		"luni",
		"marți",
		"miercuri",
		"joi",
		"vineri",
		"sâmbătă"
	]
}
//end v1.x content
);