define(
//begin v1.x content
{
	"field-sat-relative+0": "بۇ شەنبە",
	"field-sat-relative+1": "كېلەر شەنبە",
	"field-dayperiod": "چۈشتىن بۇرۇن/چۈشتىن كېيىن",
	"field-sun-relative+-1": "ئۆتكەن يەكشەنبە",
	"field-mon-relative+-1": "ئۆتكەن دۈشەنبە",
	"field-minute": "مىنۇت",
	"field-day-relative+-1": "تۈنۈگۈن",
	"field-weekday": "ھەپتە كۈنلىرى",
	"field-era": "مىلادىيە",
	"field-hour": "سائەت",
	"field-sun-relative+0": "بۇ يەكشەنبە",
	"field-sun-relative+1": "كېلەر يەكشەنبە",
	"field-wed-relative+-1": "ئۆتكەن چارشەنبە",
	"field-day-relative+0": "بۈگۈن",
	"field-day-relative+1": "ئەتە",
	"dateFormat-long": "MMMM d، U",
	"field-tue-relative+0": "بۇ سەيشەنبە",
	"field-zone": "ۋاقىت رايونى",
	"field-tue-relative+1": "كېلەر سەيشەنبە",
	"field-week-relative+-1": "ئۆتكەن ھەپتە",
	"dateFormat-medium": "MMM d، U",
	"field-year-relative+0": "بۇ يىل",
	"field-year-relative+1": "كېلەر يىل",
	"field-sat-relative+-1": "ئۆتكەن شەنبە",
	"field-year-relative+-1": "ئۆتكەن يىل",
	"field-year": "يىل",
	"field-fri-relative+0": "بۇ جۈمە",
	"field-fri-relative+1": "كېلەر جۈمە",
	"field-week": "ھەپتە",
	"field-week-relative+0": "بۇ ھەپتە",
	"field-week-relative+1": "كېلەر ھەپتە",
	"months-format-abbr": [
		"Mo1",
		"Mo2",
		"Mo3",
		"Mo4",
		"Mo5",
		"Mo6",
		"Mo7",
		"Mo8",
		"Mo9",
		"Mo10",
		"Mo11",
		"Mo12"
	],
	"field-month-relative+0": "بۇ ئاي",
	"field-month": "ئاي",
	"field-month-relative+1": "كېلەر ئاي",
	"field-fri-relative+-1": "ئۆتكەن جۈمە",
	"field-second": "سېكۇنت",
	"field-tue-relative+-1": "ئۆتكەن سەيشەنبە",
	"field-day": "كۈن",
	"field-mon-relative+0": "بۇ دۈشەنبە",
	"field-mon-relative+1": "كېلەر دۈشەنبە",
	"field-thu-relative+0": "بۇ پەيشەنبە",
	"dateFormat-short": "M/d/yy",
	"field-thu-relative+1": "كېلەر پەيشەنبە",
	"dateFormat-full": "EEEE، MMMM d، U",
	"field-wed-relative+0": "بۇ چارشەنبە",
	"months-format-wide": [
		"Month1",
		"Month2",
		"Month3",
		"Month4",
		"Month5",
		"Month6",
		"Month7",
		"Month8",
		"Month9",
		"Month10",
		"Month11",
		"Month12"
	],
	"field-wed-relative+1": "كېلەر چارشەنبە",
	"field-month-relative+-1": "ئۆتكەن ئاي",
	"field-thu-relative+-1": "ئۆتكەن پەيشەنبە"
}
//end v1.x content
);