define(
//begin v1.x content
{
	"field-weekday": "ھەپتە كۈنلىرى",
	"field-wed-relative+0": "بۇ چارشەنبە",
	"field-wed-relative+1": "كېلەر چارشەنبە",
	"dateFormatItem-GyMMMEd": "E، MMM d، y G",
	"dateFormatItem-MMMEd": "E، MMM d",
	"field-tue-relative+-1": "ئۆتكەن سەيشەنبە",
	"dateFormat-long": "MMMM d، y G",
	"field-fri-relative+-1": "ئۆتكەن جۈمە",
	"field-wed-relative+-1": "ئۆتكەن چارشەنبە",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{1}، {0}",
	"dateFormat-full": "EEEE، MMMM d، y G",
	"dateFormatItem-yyyyMEd": "E، M/d/y GGGGG",
	"field-thu-relative+-1": "ئۆتكەن پەيشەنبە",
	"dateFormatItem-Md": "M/d",
	"field-era": "مىلادىيە",
	"field-year": "يىل",
	"field-hour": "سائەت",
	"field-sat-relative+0": "بۇ شەنبە",
	"field-sat-relative+1": "كېلەر شەنبە",
	"field-day-relative+0": "بۈگۈن",
	"field-thu-relative+0": "بۇ پەيشەنبە",
	"field-day-relative+1": "ئەتە",
	"field-thu-relative+1": "كېلەر پەيشەنبە",
	"dateFormatItem-GyMMMd": "MMM d، y G",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E، MMM d، y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "MMM d، y G",
	"field-sun-relative+0": "بۇ يەكشەنبە",
	"field-sun-relative+1": "كېلەر يەكشەنبە",
	"field-minute": "مىنۇت",
	"field-dayperiod": "چۈشتىن بۇرۇن/چۈشتىن كېيىن",
	"dateFormatItem-d": "d",
	"field-day-relative+-1": "تۈنۈگۈن",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "E، M/d",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "بۇ جۈمە",
	"field-fri-relative+1": "كېلەر جۈمە",
	"field-day": "كۈن",
	"field-zone": "ۋاقىت رايونى",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "ئۆتكەن يىل",
	"field-month-relative+-1": "ئۆتكەن ئاي",
	"dateFormatItem-yyyyMd": "M/d/y GGGGG",
	"field-month": "ئاي",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "بۇ سەيشەنبە",
	"field-tue-relative+1": "كېلەر سەيشەنبە",
	"field-mon-relative+0": "بۇ دۈشەنبە",
	"field-mon-relative+1": "كېلەر دۈشەنبە",
	"dateFormat-short": "M/d/y GGGGG",
	"field-second": "سېكۇنت",
	"field-sat-relative+-1": "ئۆتكەن شەنبە",
	"field-sun-relative+-1": "ئۆتكەن يەكشەنبە",
	"field-month-relative+0": "بۇ ئاي",
	"field-month-relative+1": "كېلەر ئاي",
	"dateFormatItem-Ed": "d E",
	"field-week": "ھەپتە",
	"dateFormat-medium": "MMM d، y G",
	"field-year-relative+0": "بۇ يىل",
	"field-week-relative+-1": "ئۆتكەن ھەپتە",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"field-year-relative+1": "كېلەر يىل",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1}، {0}",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "ئۆتكەن دۈشەنبە",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "بۇ ھەپتە",
	"field-week-relative+1": "كېلەر ھەپتە"
}
//end v1.x content
);