define(
//begin v1.x content
{
	"field-sat-relative+0": "بۇ شەنبە",
	"field-sat-relative+1": "كېلەر شەنبە",
	"field-dayperiod": "چۈشتىن بۇرۇن/چۈشتىن كېيىن",
	"field-sun-relative+-1": "ئۆتكەن يەكشەنبە",
	"field-mon-relative+-1": "ئۆتكەن دۈشەنبە",
	"field-minute": "مىنۇت",
	"field-day-relative+-1": "تۈنۈگۈن",
	"field-weekday": "ھەپتە كۈنلىرى",
	"field-era": "مىلادىيە",
	"field-hour": "سائەت",
	"field-sun-relative+0": "بۇ يەكشەنبە",
	"field-sun-relative+1": "كېلەر يەكشەنبە",
	"field-wed-relative+-1": "ئۆتكەن چارشەنبە",
	"field-day-relative+0": "بۈگۈن",
	"field-day-relative+1": "ئەتە",
	"eraAbbr": [
		"جۇڭخۇا مىنگودىن بۇرۇن",
		"مىنگو"
	],
	"field-tue-relative+0": "بۇ سەيشەنبە",
	"field-zone": "ۋاقىت رايونى",
	"field-tue-relative+1": "كېلەر سەيشەنبە",
	"field-week-relative+-1": "ئۆتكەن ھەپتە",
	"field-year-relative+0": "بۇ يىل",
	"field-year-relative+1": "كېلەر يىل",
	"field-sat-relative+-1": "ئۆتكەن شەنبە",
	"field-year-relative+-1": "ئۆتكەن يىل",
	"field-year": "يىل",
	"field-fri-relative+0": "بۇ جۈمە",
	"field-fri-relative+1": "كېلەر جۈمە",
	"field-week": "ھەپتە",
	"field-week-relative+0": "بۇ ھەپتە",
	"field-week-relative+1": "كېلەر ھەپتە",
	"field-month-relative+0": "بۇ ئاي",
	"field-month": "ئاي",
	"field-month-relative+1": "كېلەر ئاي",
	"field-fri-relative+-1": "ئۆتكەن جۈمە",
	"field-second": "سېكۇنت",
	"field-tue-relative+-1": "ئۆتكەن سەيشەنبە",
	"field-day": "كۈن",
	"field-mon-relative+0": "بۇ دۈشەنبە",
	"field-mon-relative+1": "كېلەر دۈشەنبە",
	"field-thu-relative+0": "بۇ پەيشەنبە",
	"field-thu-relative+1": "كېلەر پەيشەنبە",
	"field-wed-relative+0": "بۇ چارشەنبە",
	"field-wed-relative+1": "كېلەر چارشەنبە",
	"field-month-relative+-1": "ئۆتكەن ئاي",
	"field-thu-relative+-1": "ئۆتكەن پەيشەنبە"
}
//end v1.x content
);