define(
//begin v1.x content
{
	"field-sat-relative+0": "این شنبه",
	"field-sat-relative+1": "شنبهٔ آینده",
	"field-dayperiod": "قبل/بعدازظهر",
	"field-sun-relative+-1": "یکشنبهٔ گذشته",
	"field-mon-relative+-1": "دوشنبهٔ گذشته",
	"field-minute": "دقیقه",
	"field-day-relative+-1": "دیروز",
	"field-weekday": "روز هفته",
	"field-day-relative+-2": "پریروز",
	"field-era": "دوره",
	"field-hour": "ساعت",
	"field-sun-relative+0": "این یکشنبه",
	"field-sun-relative+1": "یکشنبهٔ آینده",
	"field-wed-relative+-1": "چهارشنبهٔ گذشته",
	"field-day-relative+0": "امروز",
	"field-day-relative+1": "فردا",
	"field-day-relative+2": "پسفردا",
	"field-tue-relative+0": "این سهشنبه",
	"field-zone": "منطقهٔ زمانی",
	"field-tue-relative+1": "سهشنبهٔ آینده",
	"field-week-relative+-1": "هفتهٔ گذشته",
	"field-year-relative+0": "امسال",
	"field-year-relative+1": "سال آینده",
	"field-sat-relative+-1": "شنبهٔ گذشته",
	"field-year-relative+-1": "سال گذشته",
	"field-year": "سال",
	"field-fri-relative+0": "این جمعه",
	"field-fri-relative+1": "جمعهٔ آینده",
	"field-week": "هفته",
	"field-week-relative+0": "این هفته",
	"field-week-relative+1": "هفتهٔ آینده",
	"field-month-relative+0": "این ماه",
	"field-month": "ماه",
	"field-month-relative+1": "ماه آینده",
	"field-fri-relative+-1": "جمعهٔ گذشته",
	"field-second": "ثانیه",
	"field-tue-relative+-1": "سهشنبهٔ گذشته",
	"field-day": "روز",
	"field-mon-relative+0": "این دوشنبه",
	"field-mon-relative+1": "دوشنبهٔ آینده",
	"field-thu-relative+0": "این پنجشنبه",
	"field-second-relative+0": "اکنون",
	"field-thu-relative+1": "پنجشنبهٔ آینده",
	"field-wed-relative+0": "این چهارشنبه",
	"field-wed-relative+1": "چهارشنبهٔ آینده",
	"field-month-relative+-1": "ماه گذشته",
	"field-thu-relative+-1": "پنجشنبهٔ گذشته"
}
//end v1.x content
);