define(
//begin v1.x content
{
	"dateFormatItem-Ehm": "E h:mm a",
	"days-standAlone-short": [
		"۱ش",
		"۲ش",
		"۳ش",
		"۴ش",
		"۵ش",
		"ج",
		"ش"
	],
	"months-format-narrow": [
		"ژ",
		"ف",
		"م",
		"آ",
		"م",
		"ژ",
		"ژ",
		"ا",
		"س",
		"ا",
		"ن",
		"د"
	],
	"field-second-relative+0": "اکنون",
	"quarters-standAlone-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"field-weekday": "روز هفته",
	"dateFormatItem-yQQQ": "QQQQ y",
	"dateFormatItem-yMEd": "E y/M/d",
	"field-wed-relative+0": "این چهارشنبه",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d LLL",
	"field-wed-relative+1": "چهارشنبهٔ آینده",
	"eraNarrow": [
		"ق",
		"م"
	],
	"dayPeriods-format-wide-earlyMorning": "بامداد",
	"field-tue-relative+-1": "سهشنبهٔ گذشته",
	"dayPeriods-format-wide-morning": "صبح",
	"days-format-short": [
		"۱ش",
		"۲ش",
		"۳ش",
		"۴ش",
		"۵ش",
		"ج",
		"ش"
	],
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}",
	"dateFormat-long": "d MMMM y",
	"field-fri-relative+-1": "جمعهٔ گذشته",
	"field-wed-relative+-1": "چهارشنبهٔ گذشته",
	"months-format-wide": [
		"ژانویهٔ",
		"فوریهٔ",
		"مارس",
		"آوریل",
		"مهٔ",
		"ژوئن",
		"ژوئیهٔ",
		"اوت",
		"سپتامبر",
		"اکتبر",
		"نوامبر",
		"دسامبر"
	],
	"dateTimeFormat-medium": "{1}،‏ {0}",
	"dayPeriods-format-wide-pm": "بعدازظهر",
	"dateFormat-full": "EEEE d MMMM y",
	"field-thu-relative+-1": "پنجشنبهٔ گذشته",
	"dateFormatItem-Md": "M/d",
	"dayPeriods-format-wide-noon": "ظهر",
	"dateFormatItem-yMd": "y/M/d",
	"dateFormatItem-yM": "y/M",
	"field-era": "دوره",
	"months-standAlone-wide": [
		"ژانویه",
		"فوریه",
		"مارس",
		"آوریل",
		"مه",
		"ژوئن",
		"ژوئیه",
		"اوت",
		"سپتامبر",
		"اکتبر",
		"نوامبر",
		"دسامبر"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"timeFormat-long": "H:mm:ss (z)",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-year": "سال",
	"field-hour": "ساعت",
	"months-format-abbr": [
		"ژانویهٔ",
		"فوریهٔ",
		"مارس",
		"آوریل",
		"مهٔ",
		"ژوئن",
		"ژوئیهٔ",
		"اوت",
		"سپتامبر",
		"اکتبر",
		"نوامبر",
		"دسامبر"
	],
	"field-sat-relative+0": "این شنبه",
	"field-sat-relative+1": "شنبهٔ آینده",
	"timeFormat-full": "H:mm:ss (zzzz)",
	"field-day-relative+0": "امروز",
	"field-day-relative+1": "فردا",
	"field-thu-relative+0": "این پنجشنبه",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-day-relative+2": "پسفردا",
	"field-thu-relative+1": "پنجشنبهٔ آینده",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"ژانویه",
		"فوریه",
		"مارس",
		"آوریل",
		"مه",
		"ژوئن",
		"ژوئیه",
		"اوت",
		"سپتامبر",
		"اکتبر",
		"نوامبر",
		"دسامبر"
	],
	"quarters-format-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"quarters-standAlone-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"dateFormatItem-MMMMd": "d LLLL",
	"timeFormat-medium": "H:mm:ss",
	"field-sun-relative+0": "این یکشنبه",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"field-sun-relative+1": "یکشنبهٔ آینده",
	"eraAbbr": [
		"ق.م.",
		"م."
	],
	"field-minute": "دقیقه",
	"field-dayperiod": "قبل/بعدازظهر",
	"days-standAlone-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"dayPeriods-format-wide-night": "شب",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"field-day-relative+-1": "دیروز",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1}، ساعت {0}",
	"field-day-relative+-2": "پریروز",
	"dateFormatItem-MMMd": "d LLL",
	"dayPeriods-format-wide-midDay": "بعدازظهر",
	"dateFormatItem-MEd": "E M/d",
	"dateTimeFormat-full": "{1}، ساعت {0}",
	"field-fri-relative+0": "این جمعه",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-fri-relative+1": "جمعهٔ آینده",
	"field-day": "روز",
	"days-format-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"field-zone": "منطقهٔ زمانی",
	"months-standAlone-narrow": [
		"ژ",
		"ف",
		"م",
		"آ",
		"م",
		"ژ",
		"ژ",
		"ا",
		"س",
		"ا",
		"ن",
		"د"
	],
	"dateFormatItem-y": "y",
	"field-year-relative+-1": "سال گذشته",
	"field-month-relative+-1": "ماه گذشته",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"eraNames": [
		"قبل از میلاد",
		"میلادی"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"days-format-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dateFormatItem-HHmmZ": "HH:mm (Z)",
	"days-standAlone-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "ماه",
	"field-tue-relative+0": "این سهشنبه",
	"field-tue-relative+1": "سهشنبهٔ آینده",
	"dayPeriods-format-wide-am": "قبلازظهر",
	"dateFormatItem-MMMMEd": "E d LLLL",
	"dateFormatItem-EHm": "E H:mm",
	"dayPeriods-format-wide-weeHours": "نیمهشب",
	"field-mon-relative+0": "این دوشنبه",
	"field-mon-relative+1": "دوشنبهٔ آینده",
	"dateFormat-short": "y/M/d",
	"dayPeriods-format-wide-afternoon": "عصر",
	"dateFormatItem-EHms": "E H:mm:ss",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"field-second": "ثانیه",
	"field-sat-relative+-1": "شنبهٔ گذشته",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormatItem-yMMMMEEEEd": "EEEE d MMMM y",
	"field-sun-relative+-1": "یکشنبهٔ گذشته",
	"field-month-relative+0": "این ماه",
	"field-month-relative+1": "ماه آینده",
	"dateFormatItem-Ed": "E d",
	"dateTimeFormats-appendItem-Timezone": "{0} ({1})",
	"field-week": "هفته",
	"dateFormat-medium": "d MMM y",
	"field-year-relative+0": "امسال",
	"field-week-relative+-1": "هفتهٔ گذشته",
	"field-year-relative+1": "سال آینده",
	"dateFormatItem-mmss": "mm:ss",
	"dateTimeFormat-short": "{1}،‏ {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "دوشنبهٔ گذشته",
	"field-week-relative+0": "این هفته",
	"field-week-relative+1": "هفتهٔ آینده"
}
//end v1.x content
);