define(
//begin v1.x content
{
	"days-standAlone-short": [
		"۱ش",
		"۲ش",
		"۳ش",
		"۴ش",
		"۵ش",
		"ج",
		"ش"
	],
	"months-format-narrow": [
		"ت",
		"ح",
		"ک",
		"ط",
		"ش",
		"آ",
		"و",
		"ن",
		"ا",
		"س",
		"ت",
		"آ",
		"ا"
	],
	"field-second-relative+0": "اکنون",
	"quarters-standAlone-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"field-weekday": "روز هفته",
	"months-standAlone-narrow-leap": "و",
	"field-wed-relative+0": "این چهارشنبه",
	"field-wed-relative+1": "چهارشنبهٔ آینده",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d LLL",
	"field-tue-relative+-1": "سهشنبهٔ گذشته",
	"days-format-short": [
		"۱ش",
		"۲ش",
		"۳ش",
		"۴ش",
		"۵ش",
		"ج",
		"ش"
	],
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}",
	"dateFormat-long": "d MMMM y G",
	"field-fri-relative+-1": "جمعهٔ گذشته",
	"field-wed-relative+-1": "چهارشنبهٔ گذشته",
	"months-format-wide": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"dateFormatItem-yyyyQQQ": "QQQQ y G",
	"dateTimeFormat-medium": "{1}، {0}",
	"dayPeriods-format-wide-pm": "بعدازظهر",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-yyyyMEd": "E y/M/d G",
	"field-thu-relative+-1": "پنجشنبهٔ گذشته",
	"dateFormatItem-Md": "M/d",
	"dayPeriods-format-wide-noon": "ظهر",
	"field-era": "دوره",
	"months-standAlone-wide": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"timeFormat-long": "H:mm:ss (z)",
	"field-year": "سال",
	"field-hour": "ساعت",
	"months-format-abbr-leap": "واذار الثانی",
	"months-format-abbr": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"field-sat-relative+0": "این شنبه",
	"field-sat-relative+1": "شنبهٔ آینده",
	"timeFormat-full": "H:mm:ss (zzzz)",
	"field-day-relative+0": "امروز",
	"field-thu-relative+0": "این پنجشنبه",
	"field-day-relative+1": "فردا",
	"field-thu-relative+1": "پنجشنبهٔ آینده",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-day-relative+2": "پسفردا",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"quarters-format-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"quarters-standAlone-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"days-standAlone-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"months-standAlone-wide-leap": "واذار الثانی",
	"timeFormat-medium": "H:mm:ss",
	"field-sun-relative+0": "این یکشنبه",
	"dateFormatItem-Hm": "H:mm",
	"field-sun-relative+1": "یکشنبهٔ آینده",
	"quarters-standAlone-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"months-format-narrow-leap": "و",
	"field-minute": "دقیقه",
	"field-dayperiod": "قبل/بعدازظهر",
	"days-standAlone-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"quarters-format-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"field-day-relative+-1": "دیروز",
	"dateTimeFormat-long": "{1}، ساعت {0}",
	"field-day-relative+-2": "پریروز",
	"dateFormatItem-MMMd": "d LLL",
	"dateFormatItem-MEd": "E M/d",
	"dateTimeFormat-full": "{1}، ساعت {0}",
	"field-fri-relative+0": "این جمعه",
	"field-fri-relative+1": "جمعهٔ آینده",
	"field-day": "روز",
	"days-format-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"field-zone": "منطقهٔ زمانی",
	"months-standAlone-abbr-leap": "واذار الثانی",
	"months-standAlone-narrow": [
		"ت",
		"ح",
		"ک",
		"ط",
		"ش",
		"آ",
		"و",
		"ن",
		"ا",
		"س",
		"ت",
		"آ",
		"ا"
	],
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "سال گذشته",
	"field-month-relative+-1": "ماه گذشته",
	"days-format-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"days-format-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dateFormatItem-yyyyMd": "y/M/d G",
	"field-month": "ماه",
	"days-standAlone-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"field-tue-relative+0": "این سهشنبه",
	"field-tue-relative+1": "سهشنبهٔ آینده",
	"dayPeriods-format-wide-am": "قبلازظهر",
	"field-mon-relative+0": "این دوشنبه",
	"field-mon-relative+1": "دوشنبهٔ آینده",
	"dateFormat-short": "y/M/d G",
	"field-second": "ثانیه",
	"field-sat-relative+-1": "شنبهٔ گذشته",
	"field-sun-relative+-1": "یکشنبهٔ گذشته",
	"field-month-relative+0": "این ماه",
	"field-month-relative+1": "ماه آینده",
	"dateFormatItem-Ed": "E d",
	"dateTimeFormats-appendItem-Timezone": "{0} ({1})",
	"field-week": "هفته",
	"dateFormat-medium": "d MMM y G",
	"field-year-relative+0": "امسال",
	"field-week-relative+-1": "هفتهٔ گذشته",
	"dateFormatItem-yyyyM": "y/M G",
	"field-year-relative+1": "سال آینده",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1}، {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"months-format-wide-leap": "واذار الثانی",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "دوشنبهٔ گذشته",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "این هفته",
	"field-week-relative+1": "هفتهٔ آینده"
}
//end v1.x content
);