({
	"dateFormatItem-yM": "M/yyyy", 
	"dateFormatItem-yQ": "Q yyyy", 
	"eraNames": [
		"พุทธศักราช"
	], 
	"dateFormatItem-MMMEd": "Eท d MMM", 
	"dateTimeFormat-full": "{1}, {0}", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"dateTimeFormat-short": "{1}, {0}", 
	"dateTimeFormat-medium": "{1}, {0}", 
	"timeFormat-full": "H นาฬิกา m นาที ss วินาที zzzz", 
	"months-standAlone-abbr": [
		"Muharram", 
		"Safar", 
		"Rabiʻ I", 
		"Rabiʻ II", 
		"Jumada I", 
		"Jumada II", 
		"Rajab", 
		"Shaʻban", 
		"Ramadan", 
		"Shawwal", 
		"Dhuʻl-Qiʻdah", 
		"Dhuʻl-Hijjah"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"อ", 
		"จ", 
		"อ", 
		"พ", 
		"พ", 
		"ศ", 
		"ส"
	], 
	"eraAbbr": [
		"พ.ศ."
	], 
	"dateFormat-long": "d MMMM y", 
	"dateFormatItem-EEEd": "EEEท d", 
	"timeFormat-medium": "H:mm:ss", 
	"dateFormatItem-yyMM": "M/yyyy", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-yyMMM": "MMM y", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateTimeFormat-long": "{1}, {0}", 
	"months-standAlone-wide": [
		"Muharram", 
		"Safar", 
		"Rabiʻ I", 
		"Rabiʻ II", 
		"Jumada I", 
		"Jumada II", 
		"Rajab", 
		"Shaʻban", 
		"Ramadan", 
		"Shawwal", 
		"Dhuʻl-Qiʻdah", 
		"Dhuʻl-Hijjah"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "H นาฬิกา m นาที ss วินาที z", 
	"months-format-abbr": [
		"Muharram", 
		"Safar", 
		"Rabiʻ I", 
		"Rabiʻ II", 
		"Jumada I", 
		"Jumada II", 
		"Rajab", 
		"Shaʻban", 
		"Ramadan", 
		"Shawwal", 
		"Dhuʻl-Qiʻdah", 
		"Dhuʻl-Hijjah"
	], 
	"timeFormat-short": "H:mm", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"days-format-abbr": [
		"อา.", 
		"จ.", 
		"อ.", 
		"พ.", 
		"พฤ.", 
		"ศ.", 
		"ส."
	], 
	"pm": "หลังเที่ยง", 
	"dateFormatItem-MEd": "Eท d/M", 
	"dateFormatItem-MMMEEEd": "EEEท d MMM", 
	"am": "ก่อนเที่ยง", 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEEที่ d MMMM G y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"มุฮะร์รอม", 
		"ซอฟาร์", 
		"รอบี I", 
		"รอบี II", 
		"จุมาดา I", 
		"จุมาดา II", 
		"รอจับ", 
		"ชะอะบาน", 
		"รอมะดอน", 
		"เชาวัล", 
		"ดฮุุอัลกิดะห์", 
		"ดฮุอัลฮิจจะห์"
	], 
	"quarters-format-wide": [
		"ไตรมาส 1", 
		"ไตรมาส 2", 
		"ไตรมาส 3", 
		"ไตรมาส 4"
	], 
	"days-format-wide": [
		"วันอาทิตย์", 
		"วันจันทร์", 
		"วันอังคาร", 
		"วันพุธ", 
		"วันพฤหัสบดี", 
		"วันศุกร์", 
		"วันเสาร์"
	], 
	"eraNarrow": [
		"พ.ศ."
	]
})