define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/yyyy",
	"field-dayperiod": "ช่วงวัน",
	"dayPeriods-format-wide-pm": "หลังเที่ยง",
	"dateFormatItem-yQ": "Q yyyy",
	"field-minute": "นาที",
	"eraNames": [
		"ปีก่อนคริสต์ศักราช",
		"คริสต์ศักราช"
	],
	"dateFormatItem-MMMEd": "E d MMM",
	"dateTimeFormat-full": "{1}, {0}",
	"field-day-relative+-1": "เมื่อวาน",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "เมื่อวานซืน",
	"field-weekday": "วันในสัปดาห์",
	"field-day-relative+-3": "สามวันก่อน",
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"ม.ค.",
		"ก.พ.",
		"มี.ค.",
		"เม.ย.",
		"พ.ค.",
		"มิ.ย.",
		"ก.ค.",
		"ส.ค.",
		"ก.ย.",
		"ต.ค.",
		"พ.ย.",
		"ธ.ค."
	],
	"dateTimeFormat-short": "{1}, {0}",
	"dayPeriods-format-wide-am": "ก่อนเที่ยง",
	"dateTimeFormat-medium": "{1}, {0}",
	"field-era": "สมัย",
	"field-hour": "ชั่วโมง",
	"dateFormatItem-y": "y",
	"timeFormat-full": "H นาฬิกา m นาที ss วินาที zzzz",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "วันนี้",
	"days-standAlone-narrow": [
		"อ",
		"จ",
		"อ",
		"พ",
		"พ",
		"ศ",
		"ส"
	],
	"field-day-relative+1": "พรุ่งนี้",
	"eraAbbr": [
		"ปีก่อน ค.ศ.",
		"ค.ศ."
	],
	"field-day-relative+2": "มะรืนนี้",
	"field-day-relative+3": "สามวันต่อจากนี้",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"dateFormat-long": "d MMMM y",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-EEEd": "EEE d",
	"field-zone": "เขต",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "d MMM y",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "ปี",
	"dateTimeFormat-long": "{1}, {0}",
	"field-week": "สัปดาห์",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "H นาฬิกา m นาที ss วินาที z",
	"months-format-abbr": [
		"ม.ค.",
		"ก.พ.",
		"มี.ค.",
		"เม.ย.",
		"พ.ค.",
		"มิ.ย.",
		"ก.ค.",
		"ส.ค.",
		"ก.ย.",
		"ต.ค.",
		"พ.ย.",
		"ธ.ค."
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H",
	"field-month": "เดือน",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"days-format-abbr": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"dateFormatItem-M": "L",
	"dateFormatItem-mmss": "mm:ss",
	"field-second": "วินาที",
	"field-day": "วัน",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormat-short": "d/M/yyyy",
	"dateFormatItem-yyyyM": "M/yyyy",
	"dateFormatItem-yMMMEd": "EEE d MMM y",
	"dateFormat-full": "EEEEที่ d MMMM G y",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "EEE d/M/yyyy",
	"months-format-wide": [
		"มกราคม",
		"กุมภาพันธ์",
		"มีนาคม",
		"เมษายน",
		"พฤษภาคม",
		"มิถุนายน",
		"กรกฎาคม",
		"สิงหาคม",
		"กันยายน",
		"ตุลาคม",
		"พฤศจิกายน",
		"ธันวาคม"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"days-format-wide": [
		"วันอาทิตย์",
		"วันจันทร์",
		"วันอังคาร",
		"วันพุธ",
		"วันพฤหัสบดี",
		"วันศุกร์",
		"วันเสาร์"
	],
	"eraNarrow": [
		"ก่อน ค.ศ.",
		"ค.ศ."
	]
}
//end v1.x content
);