({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray. 
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "alice modra",
antiquewhite: "antično bela",
aqua: "akva",
aquamarine: "akvamarin",
azure: "azurna",
beige: "bež",
bisque: "porcelanasta",
black: "črna",
blanchedalmond: "mandljeva",
blue: "modra",
blueviolet: "modro vijolična",
brown: "rjava",
burlywood: "grčav les",
cadetblue: "zelenkasto modra",
chartreuse: "svetlo rumena zelena",
chocolate: "čokoladna",
coral: "koralna",
cornflowerblue: "plavično modra",
cornsilk: "koruzni laski",
crimson: "karminasta",
cyan: "cijan",
darkblue: "temno modra",
darkcyan: "temno cijan",
darkgoldenrod: "temno zlata rozga",
darkgray: "temno siva",
darkgreen: "temno zelena",
darkgrey: "temno siva", // same as darkgray
darkkhaki: "temno rumenkasto rjava",
darkmagenta: "temno magenta",
darkolivegreen: "temno olivno zelena",
darkorange: "temno oranžna",
darkorchid: "temno orhidejna",
darkred: "temno rdeča",
darksalmon: "temno lososova",
darkseagreen: "temno morsko zelena",
darkslateblue: "temno skrilasto modra",
darkslategray: "temno skrilasto siva",
darkslategrey: "temno skrilasto siva", // same as darkslategray
darkturquoise: "temno turkizna",
darkviolet: "temno vijolična",
deeppink: "temno roza",
deepskyblue: "temno nebesno modra",
dimgray: "umazano siva",
dimgrey: "umazano siva", // same as dimgray
dodgerblue: "koruzno modra",
firebrick: "opečnata",
floralwhite: "cvetno bela",
forestgreen: "gozdno zelena",
fuchsia: "fuksija",
gainsboro: "pepelnato siva",
ghostwhite: "prosojno bela",
gold: "zlata",
goldenrod: "zlata rozga",
gray: "siva",
green: "zelena",
greenyellow: "zeleno-rumena",
grey: "siva", // same as gray
honeydew: "medena rosa",
hotpink: "živo roza",
indianred: "indijansko rdeča",
indigo: "indigo",
ivory: "slonokoščena",
khaki: "rumenkasto rjava",
lavender: "sivka",
lavenderblush: "bleščeča sivka",
lawngreen: "travnato zelena",
lemonchiffon: "limonina",
lightblue: "svetlo modra",
lightcoral: "svetlo koralna",
lightcyan: "svetlo cijan",
lightgoldenrodyellow: "svetlo rumena zlata rozga",
lightgray: "svetlo siva",
lightgreen: "svetlo zelena",
lightgrey: "svetlo siva", // same as lightgray
lightpink: "svetlo roza",
lightsalmon: "svetlo lososova",
lightseagreen: "svetlo morsko zelena",
lightskyblue: "svetlo nebesno modra",
lightslategray: "svetlo skrilasto siva",
lightslategrey: "svetlo skrilasto siva", // same as lightslategray
lightsteelblue: "svetlo jeklena modra",
lightyellow: "svetlo rumena",
lime: "rumeno zelena",
limegreen: "citronsko zelena",
linen: "lanena",
magenta: "magenta",
maroon: "kostanjeva",
mediumaquamarine: "srednje akvamarin",
mediumblue: "srednje modra",
mediumorchid: "srednje orhidejna",
mediumpurple: "srednje škrlatna",
mediumseagreen: "srednje morsko zelena",
mediumslateblue: "srednje skrilasto modra",
mediumspringgreen: "srednje pomladno zelena",
mediumturquoise: "srednje turkizna",
mediumvioletred: "srednje vijolično-rdeča",
midnightblue: "polnočno modra",
mintcream: "mentolno smetanasta",
mistyrose: "megleno rožnata",
moccasin: "mokasinasta",
navajowhite: "navajsko bela",
navy: "mornarsko modra",
oldlace: "stara čipka",
olive: "olivna",
olivedrab: "olivno sivo rjava",
orange: "oranžna",
orangered: "oranžno-rdeča",
orchid: "orhidejna",
palegoldenrod: "bleda zlata rozga",
palegreen: "bledo zelena",
paleturquoise: "bledo turkizna",
palevioletred: "bledo vijolično-rdeča",
papayawhip: "papaja",
peachpuff: "breskova",
peru: "perujska",
pink: "roza",
plum: "slivova",
powderblue: "smodniško modra",
purple: "škrlatna",
red: "rdeča",
rosybrown: "rožnato rjava",
royalblue: "kraljevsko modra",
saddlebrown: "sedlasto rjava",
salmon: "lososova",
sandybrown: "peščeno rjava",
seagreen: "morsko zelena",
seashell: "morska školjka",
sienna: "siena",
silver: "srebrna",
skyblue: "nebesno modra",
slateblue: "skrilasto modra",
slategray: "skrilasto siva",
slategrey: "skrilasto siva", // same as slategray
snow: "snežena",
springgreen: "pomladno zelena",
steelblue: "jekleno modra",
tan: "kožno rjava",
teal: "zeleno modra",
thistle: "osatna",
tomato: "paradižnikova",
turquoise: "turkizna",
violet: "vijolična",
wheat: "žitna",
white: "bela",
whitesmoke: "umazano bela",
yellow: "rumena",
yellowgreen: "rumeno zelena"
})

