define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "sn./gn.",
	"field-minute": "Daqiiqad",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Shalay",
	"field-weekday": "Maalinta toddobaadka",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Qarni",
	"field-hour": "Saacad",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Maanta",
	"field-day-relative+1": "Berri",
	"dateFormat-long": "dd MMMM y G",
	"field-zone": "Xadka waqtiga",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd-MMM-y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Sanad",
	"field-week": "Toddobaad",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Bil",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"field-second": "Il biriqsi",
	"field-day": "Maalin",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, MMMM dd, y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);