define(
//begin v1.x content
{
	"USD_displayName": "Adular WD",
	"TZS_displayName": "Aciling Aṭanẓani",
	"ZMW_displayName": "Akwaca Azambi",
	"MAD_displayName": "Adirham Amerruki",
	"NGN_displayName": "Anayra Anijiri",
	"ZWD_displayName": "Adular Azimbabwi",
	"SDG_displayName": "Apund Asudani",
	"MWK_displayName": "Akwaca Amalawi",
	"KMF_displayName": "Afrank Akamiruni",
	"SCR_displayName": "Arupi Aseycili",
	"EGP_displayName": "Apund Amaṣri",
	"CVE_displayName": "Akabuviradinu Askudi",
	"LYD_displayName": "Adinar Alibi",
	"CAD_displayName": "Adular Akanadi",
	"INR_displayName": "Arupi Ahendi",
	"JPY_displayName": "Ayen Ajappuni",
	"LRD_displayName": "Adular Alibiri",
	"ZAR_displayName": "Arand Afriqi n Wadda",
	"AOA_displayName": "Akwanza n Ungula",
	"TND_displayName": "Adinar Atunsi",
	"GHC_displayName": "Asidi Aɣani",
	"BWP_displayName": "Apula Abusṭwanan",
	"DZD_displayName": "Adinar Azzayri",
	"ZMK_displayName": "Akwaca Azambi (1968–2012)",
	"NAD_displayName": "Adular Anamibi",
	"AED_displayName": "Adirham n Tgeldunin Taɛrabin Yedduklen",
	"ETB_displayName": "Abir Utyupi",
	"MZM_displayName": "Amitikal Amuzembiqi",
	"BIF_displayName": "Afrank Aburandi",
	"RWF_displayName": "Afrank Aruwandi",
	"STD_displayName": "Asw Ṭum d Udubra Amenzay",
	"SZL_displayName": "Alilangini",
	"EUR_displayName": "Uru",
	"ERN_displayName": "Anakfa Iritiri",
	"SAR_displayName": "Aryal Asuɛudi",
	"DJF_displayName": "Afrank Ajibuti",
	"CDF_displayName": "Afrank Akunguli",
	"GBP_displayName": "Apund Sterling Aglizi",
	"CHF_displayName": "Afrank Aswis",
	"MUR_displayName": "Arupi Amurisi",
	"SOS_displayName": "Aciling Aṣumali",
	"BHD_displayName": "Adinar Abaḥrini",
	"DZD_symbol": "DA",
	"XOF_displayName": "Afrank BCEAO CFA",
	"GNS_displayName": "Afrank Aɣini",
	"SLL_displayName": "Alyun",
	"UGX_displayName": "Aciling Awgandi",
	"MGA_displayName": "Aryari Amalgac",
	"AUD_displayName": "Adular n Lusṭrali",
	"KES_displayName": "Aciling Akini",
	"SHP_displayName": "Apund Asant Ilini",
	"XAF_displayName": "Afrank BCEA CFA",
	"LSL_displayName": "Aluṭi Alizuṭi",
	"MRO_displayName": "Agiya Amuriṭani",
	"CNY_displayName": "Ayuwan Renminbi Acinwa",
	"GMD_displayName": "Adalasi Agambi"
}
//end v1.x content
);