define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "n tufat / n tmeddit",
	"field-minute": "Tamrect",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "Iḍelli",
	"field-weekday": "Ussan n ddurt",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "Tallit",
	"field-hour": "Tamert",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Ass-a",
	"field-day-relative+1": "Azekka",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Aseglem asergan",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "Aseggas",
	"field-week": "Ddurt",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Aggur",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Tasint",
	"field-day": "Ass",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);