define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E, d. M. y G",
	"dateFormatItem-MMMEd": "E, d. M.",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-GyMMMd": "d. M. y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "d. M. y G",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "d. M. y GGGGG",
	"dateFormatItem-yyyyMMMd": "d. M. y G",
	"dateFormatItem-yyyyMEd": "E, d. M. y GGGGG",
	"dateFormatItem-MMMd": "d. M.",
	"dateFormatItem-H": "H",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E, d. M. y G",
	"dateFormatItem-GyMMM": "LLLL y G",
	"dateFormatItem-MEd": "E, d. M.",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormat-full": "EEEE, d. MMMM y G",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-yyyyMMM": "LLLL y G",
	"dateFormatItem-d": "d.",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);