define(
//begin v1.x content
{
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-weekday": "Den v týdnu",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, d. M. y",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"eraNarrow": [
		"př.n.l.",
		"n. l."
	],
	"dateFormat-long": "d. MMMM y",
	"months-format-wide": [
		"ledna",
		"února",
		"března",
		"dubna",
		"května",
		"června",
		"července",
		"srpna",
		"září",
		"října",
		"listopadu",
		"prosince"
	],
	"dayPeriods-format-wide-pm": "odp.",
	"dateFormat-full": "EEEE, d. MMMM y",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-yMd": "d. M. y",
	"field-era": "Letopočet",
	"dateFormatItem-yM": "M.y",
	"months-standAlone-wide": [
		"leden",
		"únor",
		"březen",
		"duben",
		"květen",
		"červen",
		"červenec",
		"srpen",
		"září",
		"říjen",
		"listopad",
		"prosinec"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"1. čtvrtletí",
		"2. čtvrtletí",
		"3. čtvrtletí",
		"4. čtvrtletí"
	],
	"timeFormat-long": "H:mm:ss z",
	"field-year": "Rok",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yQ": "Q yyyy",
	"dateFormatItem-yyyyMMMM": "LLLL y",
	"field-hour": "Hodina",
	"months-format-abbr": [
		"Led",
		"Úno",
		"Bře",
		"Dub",
		"Kvě",
		"Čer",
		"Čvc",
		"Srp",
		"Zář",
		"Říj",
		"Lis",
		"Pro"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "H:mm:ss zzzz",
	"field-day-relative+0": "Dnes",
	"field-day-relative+1": "Zítra",
	"field-day-relative+2": "Pozítří",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"1.",
		"2.",
		"3.",
		"4.",
		"5.",
		"6.",
		"7.",
		"8.",
		"9.",
		"10.",
		"11.",
		"12."
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"1. čtvrtletí",
		"2. čtvrtletí",
		"3. čtvrtletí",
		"4. čtvrtletí"
	],
	"days-standAlone-wide": [
		"neděle",
		"pondělí",
		"úterý",
		"středa",
		"čtvrtek",
		"pátek",
		"sobota"
	],
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"př. n. l.",
		"n. l."
	],
	"field-minute": "Minuta",
	"field-dayperiod": "AM/PM",
	"days-standAlone-abbr": [
		"ne",
		"po",
		"út",
		"st",
		"čt",
		"pá",
		"so"
	],
	"dateFormatItem-d": "d.",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Včera",
	"field-day-relative+-2": "Předevčírem",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, d. M.",
	"field-day": "Den",
	"days-format-wide": [
		"neděle",
		"pondělí",
		"úterý",
		"středa",
		"čtvrtek",
		"pátek",
		"sobota"
	],
	"field-zone": "Časové pásmo",
	"months-standAlone-narrow": [
		"l",
		"ú",
		"b",
		"d",
		"k",
		"č",
		"č",
		"s",
		"z",
		"ř",
		"l",
		"p"
	],
	"field-year-relative+-1": "Minulý rok",
	"field-month-relative+-1": "Minulý měsíc",
	"days-format-abbr": [
		"ne",
		"po",
		"út",
		"st",
		"čt",
		"pá",
		"so"
	],
	"dateFormatItem-yMMMd": "d. MMM y",
	"eraNames": [
		"př. n. l.",
		"n. l."
	],
	"days-format-narrow": [
		"N",
		"P",
		"Ú",
		"S",
		"Č",
		"P",
		"S"
	],
	"field-month": "Měsíc",
	"days-standAlone-narrow": [
		"N",
		"P",
		"Ú",
		"S",
		"Č",
		"P",
		"S"
	],
	"dayPeriods-format-wide-am": "dop.",
	"dateFormat-short": "dd.MM.yy",
	"field-second": "Sekunda",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"field-month-relative+0": "Tento měsíc",
	"field-month-relative+1": "Příští měsíc",
	"dateFormatItem-Ed": "E, d.",
	"field-week": "Týden",
	"dateFormat-medium": "d. M. yyyy",
	"field-year-relative+0": "Tento rok",
	"field-week-relative+-1": "Minulý týden",
	"dateFormatItem-yyyyM": "M.yyyy",
	"field-year-relative+1": "Příští rok",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyyy": "y",
	"field-week-relative+0": "Tento týden",
	"field-week-relative+1": "Příští týden"
}
//end v1.x content
);