define(
//begin v1.x content
{
	"field-sat-relative+0": "ఈ శనివారం",
	"field-sat-relative+1": "తదుపరి శనివారం",
	"field-dayperiod": "AM/PM",
	"field-sun-relative+-1": "గత ఆదివారం",
	"field-mon-relative+-1": "గత సోమవారం",
	"field-minute": "నిమిషము",
	"field-day-relative+-1": "నిన్న",
	"field-weekday": "వారంలో రోజు",
	"field-day-relative+-2": "మొన్న",
	"field-era": "యుగం, శకము",
	"field-hour": "గంట",
	"field-sun-relative+0": "ఈ ఆదివారం",
	"field-sun-relative+1": "తదుపరి ఆదివారం",
	"field-wed-relative+-1": "గత బుధవారం",
	"field-day-relative+0": "ఈ రోజు",
	"field-day-relative+1": "రేపు",
	"field-day-relative+2": "ఎల్లుండి",
	"field-tue-relative+0": "ఈ మంగళవారం",
	"field-zone": "మండలం",
	"field-tue-relative+1": "తదుపరి మంగళవారం",
	"field-week-relative+-1": "గత వారం",
	"field-year-relative+0": "ఈ సంవత్సరం",
	"field-year-relative+1": "తదుపరి సంవత్సరం",
	"field-sat-relative+-1": "గత శనివారం",
	"field-year-relative+-1": "గత సంవత్సరం",
	"field-year": "సంవత్సరం",
	"field-fri-relative+0": "ఈ శుక్రవారం",
	"field-fri-relative+1": "తదుపరి శుక్రవారం",
	"field-week": "వారము",
	"field-week-relative+0": "ఈ వారం",
	"field-week-relative+1": "తదుపరి వారం",
	"field-month-relative+0": "ఈ నెల",
	"field-month": "నెల",
	"field-month-relative+1": "తదుపరి నెల",
	"field-fri-relative+-1": "గత శుక్రవారం",
	"field-second": "క్షణం",
	"field-tue-relative+-1": "గత మంగళవారం",
	"field-day": "దినం",
	"field-mon-relative+0": "ఈ సోమవారం",
	"field-mon-relative+1": "తదుపరి సోమవారం",
	"field-thu-relative+0": "ఈ గురువారం",
	"field-second-relative+0": "ప్రస్తుతం",
	"field-thu-relative+1": "తదుపరి గురువారం",
	"field-wed-relative+0": "ఈ బుధవారం",
	"field-wed-relative+1": "తదుపరి బుధవారం",
	"field-month-relative+-1": "గత నెల",
	"field-thu-relative+-1": "గత గురువారం"
}
//end v1.x content
);