define(
//begin v1.x content
{
	"USD_displayName": "ameriki Dolar",
	"TZS_displayName": "tanzani Siling",
	"ZMW_displayName": "zambi Kwaca",
	"MAD_displayName": "marɔku Diram",
	"NGN_displayName": "nizeriya Nɛra",
	"ZWD_displayName": "zimbabuwe Dolar",
	"SDG_displayName": "sudani Dinar",
	"MWK_displayName": "malawi Kwaca",
	"KMF_displayName": "komɔri Fraŋ",
	"SCR_displayName": "sesɛli Rupi",
	"EGP_displayName": "eziputi Livri",
	"CVE_displayName": "capivɛrdi Esekudo",
	"LYD_displayName": "libi Dinar",
	"CAD_displayName": "kanada Dolar",
	"INR_displayName": "Ɛndu Rupi",
	"JPY_displayName": "zapɔne Yɛn",
	"LRD_displayName": "liberiya Dolar",
	"ZAR_displayName": "sudafriki Randi",
	"AOA_displayName": "angola Kwanza",
	"TND_displayName": "tunizi Dinar",
	"GHC_displayName": "gana Sedi",
	"BWP_displayName": "bɔtisiwana Pula",
	"DZD_displayName": "alizeri Dinar",
	"ZMK_displayName": "zambi Kwaca (1968–2012)",
	"NAD_displayName": "namibi Dolar",
	"AED_displayName": "arabu mara kafoli Diram",
	"ETB_displayName": "etiopi Bir",
	"MZM_displayName": "mozanbiki Metikali",
	"BIF_displayName": "burundi Fraŋ",
	"RWF_displayName": "ruwanda Fraŋ",
	"STD_displayName": "sawotome Dobra",
	"SZL_displayName": "swazilandi Lilangeni",
	"EUR_displayName": "ero",
	"ERN_displayName": "eritere Nafika",
	"SAR_displayName": "sawudiya Riyal",
	"DJF_displayName": "jibuti Fraŋ",
	"CDF_displayName": "kongole Fraŋ",
	"GBP_displayName": "angilɛ Livri Siterlingi",
	"CHF_displayName": "suwisi Fraŋ",
	"MUR_displayName": "morisi Rupi",
	"SOS_displayName": "somali Siling",
	"BHD_displayName": "bareyini Dinar",
	"XOF_displayName": "sefa Fraŋ (BCEAO)",
	"GNS_displayName": "gine Fraŋ",
	"SLL_displayName": "siyeralewɔni Lewɔni",
	"UGX_displayName": "uganda Siling",
	"MGA_displayName": "madagasikari Fraŋ",
	"SDP_displayName": "sudani Livri",
	"AUD_displayName": "ositirali Dolar",
	"KES_displayName": "keniya Siling",
	"SHP_displayName": "Ɛlɛni-Senu Livri",
	"XAF_displayName": "sefa Fraŋ (BEAC)",
	"LSL_displayName": "lesoto Loti",
	"MRO_displayName": "mɔritani Uguwiya",
	"CNY_displayName": "siniwa Yuwan",
	"GMD_displayName": "gambi Dalasi"
}
//end v1.x content
);