define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "sɔgɔma/tile/wula/su",
	"field-minute": "miniti",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "kunu",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "tile",
	"field-hour": "lɛrɛ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "bi",
	"field-day-relative+1": "sini",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "sigikun tilena",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "san",
	"field-week": "dɔgɔkun",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "kalo",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "sekondi",
	"field-day": "don",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);