define(
//begin v1.x content
{
	"dateFormatItem-Ehm": "E h:mm a",
	"days-standAlone-short": [
		"អាទិត្យ",
		"ចន្ទ",
		"អង្គារ",
		"ពុធ",
		"ព្រហស្បតិ៍",
		"សុក្រ",
		"សៅរ៍"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-second-relative+0": "ឥឡូវ",
	"quarters-standAlone-narrow": [
		"១",
		"២",
		"៣",
		"៤"
	],
	"field-weekday": "ថ្ងៃនៃសប្ដាហ៍",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E d-M-y",
	"field-wed-relative+0": "ថ្ងៃពុធនេះ",
	"field-wed-relative+1": "ថ្ងៃពុធក្រោយ",
	"dateFormatItem-GyMMMEd": "E d MMM y នៃ G",
	"dateFormatItem-MMMEd": "E d MMM",
	"eraNarrow": [
		"មុន គ.ស.",
		"ក្រោយ គ.ស.",
		"គ.ស."
	],
	"field-tue-relative+-1": "ថ្ងៃអង្គារមុន",
	"days-format-short": [
		"អាទិត្យ",
		"ចន្ទ",
		"អង្គារ",
		"ពុធ",
		"ព្រហស្បតិ៍",
		"សុក្រ",
		"សៅរ៍"
	],
	"dateFormat-long": "d MMMM y",
	"field-fri-relative+-1": "ថ្ងៃសុក្រមុន",
	"field-wed-relative+-1": "ថ្ងៃពុធមុន",
	"months-format-wide": [
		"មករា",
		"កុម្ភៈ",
		"មីនា",
		"មេសា",
		"ឧសភា",
		"មិថុនា",
		"កក្កដា",
		"សីហា",
		"កញ្ញា",
		"តុលា",
		"វិច្ឆិកា",
		"ធ្នូ"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "ល្ងាច",
	"dateFormat-full": "EEEE d MMMM y",
	"field-thu-relative+-1": "ថ្ងៃព្រហស្បតិ៍មុន",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yMd": "d-M-y",
	"field-era": "សករាជ",
	"dateFormatItem-yM": "M-y",
	"months-standAlone-wide": [
		"មករា",
		"កុម្ភៈ",
		"មីនា",
		"មេសា",
		"ឧសភា",
		"មិថុនា",
		"កក្កដា",
		"សីហា",
		"កញ្ញា",
		"តុលា",
		"វិច្ឆិកា",
		"ធ្នូ"
	],
	"timeFormat-short": "h:mm a",
	"quarters-format-wide": [
		"ត្រីមាសទី ១",
		"ត្រីមាសទី ២",
		"ត្រីមាសទី ៣",
		"ត្រីមាសទី ៤"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"timeFormat-long": "h:mm:ss a z",
	"field-year": "ឆ្នាំ",
	"dateFormatItem-yMMM": "MMM y",
	"field-hour": "ម៉ោង",
	"months-format-abbr": [
		"មករា",
		"កុម្ភៈ",
		"មីនា",
		"មេសា",
		"ឧសភា",
		"មិថុនា",
		"កក្កដា",
		"សីហា",
		"កញ្ញា",
		"តុលា",
		"វិច្ឆិកា",
		"ធ្នូ"
	],
	"field-sat-relative+0": "ថ្ងៃសៅរ៍នេះ",
	"field-sat-relative+1": "ថ្ងៃសៅរ៍ក្រោយ",
	"timeFormat-full": "h:mm:ss a zzzz",
	"field-day-relative+0": "ថ្ងៃនេះ",
	"field-thu-relative+0": "ថ្ងៃព្រហស្បតិ៍នេះ",
	"field-day-relative+1": "ថ្ងៃស្អែក",
	"field-thu-relative+1": "ថ្ងៃព្រហស្បតិ៍ក្រោយ",
	"dateFormatItem-GyMMMd": "d MMM y នៃ G",
	"field-day-relative+2": "ខានស្អែក",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"មករា",
		"កុម្ភៈ",
		"មីនា",
		"មេសា",
		"ឧសភា",
		"មិថុនា",
		"កក្កដា",
		"សីហា",
		"កញ្ញា",
		"តុលា",
		"វិច្ឆិកា",
		"ធ្នូ"
	],
	"quarters-format-abbr": [
		"ត្រីមាស ១",
		"ត្រីមាស ២",
		"ត្រីមាស ៣",
		"ត្រីមាស ៤"
	],
	"quarters-standAlone-wide": [
		"ត្រីមាសទី ១",
		"ត្រីមាសទី ២",
		"ត្រីមាសទី ៣",
		"ត្រីមាសទី ៤"
	],
	"dateFormatItem-Gy": "y នៃ G",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"អាទិត្យ",
		"ចន្ទ",
		"អង្គារ",
		"ពុធ",
		"ព្រហស្បតិ៍",
		"សុក្រ",
		"សៅរ៍"
	],
	"timeFormat-medium": "h:mm:ss a",
	"field-sun-relative+0": "ថ្ងៃអាទិត្យនេះ",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "ថ្ងៃអាទិត្យក្រោយ",
	"quarters-standAlone-abbr": [
		"ត្រីមាស ១",
		"ត្រីមាស ២",
		"ត្រីមាស ៣",
		"ត្រីមាស ៤"
	],
	"eraAbbr": [
		"មុន គ.ស.",
		"ក្រោយ គ.ស.",
		"គ.ស."
	],
	"field-minute": "នាទី",
	"field-dayperiod": "ព្រឹក/ល្ងាច",
	"days-standAlone-abbr": [
		"អាទិត្យ",
		"ចន្ទ",
		"អង្គារ",
		"ពុធ",
		"ព្រហស្បតិ៍",
		"សុក្រ",
		"សៅរ៍"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"១",
		"២",
		"៣",
		"៤"
	],
	"field-day-relative+-1": "ម្សិលមិញ",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "ម្សិលម៉្ងៃ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E d MMM",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "ថ្ងៃសុក្រនេះ",
	"field-fri-relative+1": "ថ្ងៃសុក្រក្រោយ",
	"field-day": "ថ្ងៃ",
	"days-format-wide": [
		"អាទិត្យ",
		"ចន្ទ",
		"អង្គារ",
		"ពុធ",
		"ព្រហស្បតិ៍",
		"សុក្រ",
		"សៅរ៍"
	],
	"field-zone": "តំបន់ពេលវេលា",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-year-relative+-1": "ឆ្នាំមុន",
	"field-month-relative+-1": "ខែមុន",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"អាទិត្យ",
		"ចន្ទ",
		"អង្គារ",
		"ពុធ",
		"ព្រហស្បតិ៍",
		"សុក្រ",
		"សៅរ៍"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"eraNames": [
		"មុនគ្រិស្តសករាជ",
		"គ្រិស្តសករាជ",
		"គ.ស."
	],
	"days-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"days-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "ខែ",
	"field-tue-relative+0": "ថ្ងៃអង្គារនេះ",
	"field-tue-relative+1": "ថ្ងៃអង្គារក្រោយ",
	"dayPeriods-format-wide-am": "ព្រឹក",
	"dateFormatItem-EHm": "E HH:mm",
	"field-mon-relative+0": "ថ្ងៃច័ន្ទនេះ",
	"field-mon-relative+1": "ថ្ងៃច័ន្ទក្រោយ",
	"dateFormat-short": "d/M/y",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"field-second": "វិនាទី",
	"field-sat-relative+-1": "ថ្ងៃសៅរ៍មុន",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"field-sun-relative+-1": "ថ្ងៃអាទិត្យមុន",
	"field-month-relative+0": "ខែនេះ",
	"field-month-relative+1": "ខែក្រោយ",
	"dateFormatItem-Ed": "d E",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-week": "សប្ដាហ៍",
	"dateFormat-medium": "d MMM y",
	"field-year-relative+0": "ឆ្នាំនេះ",
	"field-week-relative+-1": "សប្ដាហ៍មុន",
	"field-year-relative+1": "ឆ្នាំក្រោយ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM y នៃ G",
	"field-mon-relative+-1": "ថ្ងៃច័ន្ទមុន",
	"field-week-relative+0": "សប្ដាហ៍នេះ",
	"field-week-relative+1": "សប្ដាហ៍ក្រោយ"
}
//end v1.x content
);