define(
//begin v1.x content
{
	"dateFormatItem-yM": "L.y G",
	"dateFormatItem-yMMMMccccd": "cccc, d. MMMM y G",
	"dateFormatItem-yQ": "Q/y G",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-yQQQ": "QQQ y G",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-y": "y G",
	"dateFormatItem-Ed": "ccc d.",
	"dateFormatItem-yMMM": "LLLL y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-Hm": "H.mm",
	"dateFormatItem-yyMM": "M.y G",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-yyMMM": "LLLL y G",
	"dateFormatItem-yMd": "d.M.y G",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateFormatItem-yyyyMEd": "E d.M.y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyQ": "Q/y G",
	"dateFormatItem-H": "H",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d. MMM y G",
	"dateFormatItem-MEd": "E d.M.",
	"dateFormatItem-hm": "h.mm a",
	"dateFormat-short": "d.M.y G",
	"dateFormatItem-yyyyM": "M.y G",
	"dateFormatItem-yMMMEd": "E d. MMM y G",
	"dateFormat-full": "cccc d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "E d.M.y G",
	"dateFormatItem-d": "d"
}
//end v1.x content
);