define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"dateFormatItem-MMMEd": "ccc d. MMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Gy": "y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yyyyMM": "M.y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-yyyyMMMMccccd": "cccc d. MMMM y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-Hm": "H.mm",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yyyyMd": "d.M.y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMEd": "E d.M.y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-H": "H",
	"dateFormatItem-M": "L",
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-MEd": "E d.M.",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "h.mm a",
	"dateFormat-short": "d.M.y GGGGG",
	"dateFormatItem-yyyyM": "L.y G",
	"dateFormat-full": "cccc d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-h": "h a"
}
//end v1.x content
);