define(
//begin v1.x content
{
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"months-standAlone-abbr-leap": "adár II",
	"dayPeriods-format-wide-pm": "ip.",
	"dateFormatItem-MMMEd": "ccc d. MMM",
	"dateFormatItem-hms": "h.mm.ss a",
	"days-standAlone-wide": [
		"sunnuntai",
		"maanantai",
		"tiistai",
		"keskiviikko",
		"torstai",
		"perjantai",
		"lauantai"
	],
	"months-standAlone-narrow": [
		"T",
		"H",
		"K",
		"T",
		"S",
		"A",
		"A",
		"N",
		"I",
		"S",
		"T",
		"A",
		"E"
	],
	"dateFormatItem-Gy": "y G",
	"dayPeriods-format-wide-am": "ap.",
	"quarters-standAlone-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"dateFormatItem-y": "y G",
	"timeFormat-full": "H.mm.ss zzzz",
	"dateFormatItem-yyyy": "y G",
	"months-standAlone-narrow-leap": "A",
	"months-standAlone-abbr": [
		"tišrí",
		"hešván",
		"kislév",
		"tevét",
		"ševát",
		"adár I",
		"adár",
		"nisán",
		"ijjár",
		"siván",
		"tammúz",
		"ab",
		"elúl"
	],
	"dateFormatItem-Ed": "E d.",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormat-long": "d. MMMM y G",
	"timeFormat-medium": "H.mm.ss",
	"dateFormatItem-Hm": "H.mm",
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-Hms": "H.mm.ss",
	"dayPeriods-format-narrow-pm": "ip.",
	"quarters-standAlone-wide": [
		"1. neljännes",
		"2. neljännes",
		"3. neljännes",
		"4. neljännes"
	],
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dayPeriods-format-narrow-am": "ap.",
	"months-standAlone-wide": [
		"tišríkuu",
		"hešvánkuu",
		"kislévkuu",
		"tevétkuu",
		"ševátkuu",
		"adárkuu I",
		"adárkuu",
		"nisánkuu",
		"ijjárkuu",
		"sivánkuu",
		"tammúzkuu",
		"abkuu",
		"elúlkuu"
	],
	"dateFormatItem-yyyyMd": "d.M.y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMEd": "E d.M.y G",
	"dateFormatItem-MMMd": "d. MMM",
	"timeFormat-long": "H.mm.ss z",
	"months-format-abbr": [
		"tišríkuuta",
		"hešvánkuuta",
		"kislévkuuta",
		"tevétkuuta",
		"ševátkuuta",
		"adárkuuta I",
		"adárkuuta",
		"nisánkuuta",
		"ijjárkuuta",
		"sivánkuuta",
		"tammúzkuuta",
		"abkuuta",
		"elúlkuuta"
	],
	"timeFormat-short": "H.mm",
	"dateFormatItem-H": "H",
	"quarters-format-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"days-format-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-MEd": "E d.M.",
	"months-format-narrow": [
		"T",
		"H",
		"K",
		"T",
		"S",
		"A",
		"A",
		"N",
		"I",
		"S",
		"T",
		"A",
		"E"
	],
	"days-standAlone-short": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"dateFormatItem-hm": "h.mm a",
	"days-standAlone-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"months-standAlone-wide-leap": "adárkuu II",
	"dayPeriods-format-abbr-pm": "ip.",
	"dateFormat-short": "d.M.y GGGGG",
	"dateFormatItem-yyyyM": "L.y G",
	"dateFormat-full": "cccc d. MMMM y G",
	"dateFormatItem-Md": "d.M.",
	"months-format-wide": [
		"tišríkuuta",
		"hešvánkuuta",
		"kislévkuuta",
		"tevétkuuta",
		"ševátkuuta",
		"adárkuuta I",
		"adárkuuta",
		"nisánkuuta",
		"ijjárkuuta",
		"sivánkuuta",
		"tammúzkuuta",
		"abkuuta",
		"elúlkuuta"
	],
	"dayPeriods-format-abbr-am": "ap.",
	"days-format-short": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"dateFormatItem-yyyyMMM": "LLL y G",
	"quarters-format-wide": [
		"1. neljännes",
		"2. neljännes",
		"3. neljännes",
		"4. neljännes"
	],
	"months-format-wide-leap": "adárkuuta II",
	"days-format-wide": [
		"sunnuntaina",
		"maanantaina",
		"tiistaina",
		"keskiviikkona",
		"torstaina",
		"perjantaina",
		"lauantaina"
	]
}
//end v1.x content
);