define(
//begin v1.x content
{
	"dateFormat-medium": "d.M.y G",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-MEd": "E d.M.",
	"dateFormatItem-yyyyMMM": "LLLL y G",
	"dateFormatItem-Hm": "H.mm",
	"dateFormatItem-H": "H",
	"dateFormatItem-y": "y G",
	"dateFormatItem-hm": "h.mm a",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMMEd": "EEE d. MMM y G",
	"dateFormatItem-yyyyMEd": "EEE d.M.y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-yyyyMM": "M.y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormat-long": "d. MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-ms": "mm.ss",
	"dateFormat-short": "d.M.y G",
	"months-format-wide": [
		"muharram",
		"safar",
		"rabi’ al-awwal",
		"rabi’ al-akhir",
		"džumada-l-ula",
		"džumada-l-akhira",
		"radžab",
		"ša’ban",
		"ramadan",
		"šawwal",
		"dhu-l-qa’da",
		"dhu-l-hiddža"
	],
	"dateFormatItem-yyyyMMMMccccd": "cccc, d. MMMM y G",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-d": "d",
	"dateFormatItem-yyyyM": "M.y G",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-MMM": "LLL",
	"dateFormat-full": "cccc d. MMMM y G",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyyyQ": "Q/y G",
	"dateFormatItem-Ed": "ccc d."
}
//end v1.x content
);