define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "kiɛmɛ́ɛm,kisɛ́ndɛ",
	"field-minute": "minít",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "púyoó",
	"field-weekday": "metúk mɔ́sɔ́ndiɛ",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-era": "kipéŋén",
	"field-hour": "kisikɛl,",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ínaan",
	"field-day-relative+1": "nakinyám",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "kinúki kisikɛl ɔ́ pitɔŋ",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "yɔɔŋ",
	"field-week": "sɔ́ndiɛ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "oóli",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "síkɛn",
	"field-day": "puɔ́sɛ́",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);