define(
//begin v1.x content
{
	"USD_displayName": "Poo Dala",
	"TZS_displayName": "Taŋzaniya Siyeŋ",
	"ZMW_displayName": "Zambiya Kuwacha",
	"MAD_displayName": "Mɔroko Dihami",
	"NGN_displayName": "Naĩjiriya Naĩra",
	"ZWD_displayName": "Zimbhabhuwe Dala",
	"SDG_displayName": "Sudaniĩ Pɔɔ̃",
	"MWK_displayName": "Malawi Kuwacha",
	"KMF_displayName": "Komoro Furaŋki",
	"EGP_displayName": "Míséla Pɔɔ̃",
	"CVE_displayName": "Ɛsikudo Cabovɛdiyano",
	"LYD_displayName": "Libhiya Dina",
	"CAD_displayName": "Kanada Dala",
	"INR_displayName": "Índiya Rupi",
	"JPY_displayName": "Japaniĩ Yɛŋ",
	"LRD_displayName": "Laibhiya Dala",
	"ZAR_displayName": "Afirika Kɔi Leŋŋɛ lɔ Randi",
	"AOA_displayName": "Angola Kuwaŋza",
	"TND_displayName": "Tunisiya Dina",
	"GHC_displayName": "Gana Sidi",
	"BWP_displayName": "Bhosuwana Pula",
	"DZD_displayName": "Agiriya Dina",
	"ZMK_displayName": "Zambiya Kuwacha (1968–2012)",
	"LRD_symbol": "$",
	"NAD_displayName": "Namibiya Dala",
	"AED_displayName": "Yunaitɛ Arabhi Ɛmire Dihami",
	"ETB_displayName": "Ítiyopiya Bhii",
	"MZM_displayName": "Mozambiki Mɛtikali",
	"BIF_displayName": "Bhurundi Furaŋki",
	"RWF_displayName": "Rawunda Furaŋki",
	"STD_displayName": "Sawo Tombe ɓɛ a Gbawo Dobura",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Ɛritera Nakifa",
	"SAR_displayName": "Lahabu Sawodi Riya",
	"DJF_displayName": "Jibhuti Furaŋki",
	"CDF_displayName": "Kóngo Furaŋki",
	"GBP_displayName": "Jengési Pɔɔ̃ Sitɛ́liŋ",
	"CHF_displayName": "Suwesi Furaŋki",
	"MUR_displayName": "Mɔreshɔ Rupi",
	"SOS_displayName": "Somaliya Siyeŋ",
	"BHD_displayName": "Bharɛŋ Dina",
	"XOF_displayName": "Áfíríka Tele Jíí Sifa",
	"GNS_displayName": "Gini Furaŋki",
	"SLL_displayName": "Liyɔɔ̀",
	"UGX_displayName": "Yuganda Siyeŋ",
	"MGA_displayName": "Malagasi Ariyari",
	"AUD_displayName": "Ɔ́situwa Dala",
	"KES_displayName": "Kénya Siyeŋ",
	"SHP_displayName": "Siŋ Hɛlina Pɔɔ̃",
	"XAF_displayName": "Áfíríka Tɛ Sifa",
	"LSL_displayName": "Lisóto Loti",
	"MRO_displayName": "Mɔretani Yugiya",
	"CNY_displayName": "Chaníĩ Yuwaŋ Rɛŋmimbi",
	"GMD_displayName": "Gambiya Dalasi"
}
//end v1.x content
);