define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-minute": "mini",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "kunu",
	"field-weekday": "wikiyɛma tele",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMM": "LLL",
	"field-hour": "hawa",
	"dateFormatItem-y": "y",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "wɛlɛ",
	"field-day-relative+1": "sina",
	"dateFormat-long": "d MMMM y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "M/d/y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "saŋ",
	"field-week": "wiki",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "kalo",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "MMM d y",
	"field-second": "jaki-jaka",
	"field-day": "tele",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);