define(
//begin v1.x content
{
	"USD_displayName": "dola ya Malekani",
	"TZS_displayName": "shilingi ya Tanzania",
	"ZMW_displayName": "kwacha ya Zambia",
	"MAD_displayName": "dilham ya Moloko",
	"NGN_displayName": "naila ya Naijelia",
	"ZWD_displayName": "dola ya Zimbabwe",
	"SDG_displayName": "dinali ya Sudani",
	"MWK_displayName": "kwacha ya Malawi",
	"KMF_displayName": "falanga ya Komolo",
	"SCR_displayName": "lupia ya Shelisheli",
	"EGP_displayName": "pauni ya Misli",
	"CVE_displayName": "eskudo ya Kepuvede",
	"LYD_displayName": "dinali ya Libya",
	"CAD_displayName": "dola ya Kanada",
	"INR_displayName": "lupia ya India",
	"JPY_displayName": "salafu ya Kijapani",
	"TZS_symbol": "TSh",
	"LRD_displayName": "dola ya Libelia",
	"ZAR_displayName": "landi ya Aflika Kusini",
	"AOA_displayName": "kwanza ya Angola",
	"TND_displayName": "dinali ya Tunisia",
	"GHC_displayName": "sedi ya Ghana",
	"BWP_displayName": "pula ya Botswana",
	"DZD_displayName": "dinali ya Aljelia",
	"ZMK_displayName": "kwacha ya Zambia (1968–2012)",
	"NAD_displayName": "dola ya Namibia",
	"AED_displayName": "dilham ya Falme za Kialabu",
	"ETB_displayName": "bil ya Uhabeshi",
	"MZM_displayName": "metikali ya Msumbiji",
	"BIF_displayName": "falanga ya Bulundi",
	"RWF_displayName": "falanga ya Lwanda",
	"STD_displayName": "dobla ya Sao Tome na Plincipe",
	"SZL_displayName": "lilangeni",
	"EUR_displayName": "yulo",
	"ERN_displayName": "nakfa ya Elitlea",
	"SAR_displayName": "liyal ya Saudia",
	"DJF_displayName": "falanga ya Jibuti",
	"CDF_displayName": "falanga ya Kongo",
	"GBP_displayName": "pauni ya Uingeeza",
	"CHF_displayName": "falanga ya Uswisi",
	"MUR_displayName": "lupia ya Molisi",
	"SOS_displayName": "shilingi ya Somalia",
	"BHD_displayName": "dinali ya Bahaleni",
	"XOF_displayName": "falanga CFA BCEAO",
	"GNS_displayName": "falanga ya Gine",
	"SLL_displayName": "leoni",
	"UGX_displayName": "shilingi ya Uganda",
	"MGA_displayName": "falanga ya Bukini",
	"SDP_displayName": "pauni ya Sudani",
	"AUD_displayName": "dola ya Austlalia",
	"KES_displayName": "shilingi ya Kenya",
	"SHP_displayName": "pauni ya Santahelena",
	"XAF_displayName": "falanga CFA BEAC",
	"LSL_displayName": "loti ya Lesoto",
	"MRO_displayName": "ugwiya ya Molitania",
	"CNY_displayName": "yaun lenminbi ya China",
	"GMD_displayName": "dalasi ya Gambia"
}
//end v1.x content
);