define(
//begin v1.x content
{
	"field-sat-relative+0": "ove subote",
	"field-sat-relative+1": "sledeće subote",
	"field-dayperiod": "pre podne/popodne",
	"field-sun-relative+-1": "prošle nedelje",
	"field-mon-relative+-1": "prošlog ponedeljka",
	"field-minute": "minut",
	"field-day-relative+-1": "juče",
	"field-weekday": "dan u nedelji",
	"field-day-relative+-2": "prekjuče",
	"field-era": "era",
	"field-hour": "čas",
	"field-sun-relative+0": "ove nedelje",
	"field-sun-relative+1": "sledeće nedelje",
	"field-wed-relative+-1": "prošle srede",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"eraAbbr": [
		"SAKA"
	],
	"field-day-relative+2": "prekosutra",
	"field-tue-relative+0": "ovog utorka",
	"field-zone": "zona",
	"field-tue-relative+1": "sledećeg utorka",
	"field-week-relative+-1": "Prošle nedelje",
	"field-year-relative+0": "Ove godine",
	"field-year-relative+1": "Sledeće godine",
	"field-sat-relative+-1": "prošle subote",
	"field-year-relative+-1": "Prošle godine",
	"field-year": "godina",
	"field-fri-relative+0": "ovog petka",
	"field-fri-relative+1": "sledećeg petka",
	"field-week": "nedelja",
	"field-week-relative+0": "Ove nedelje",
	"field-week-relative+1": "Sledeće nedelje",
	"field-month-relative+0": "Ovog meseca",
	"field-month": "mesec",
	"field-month-relative+1": "Sledećeg meseca",
	"field-fri-relative+-1": "prošlog petka",
	"field-second": "sekund",
	"field-tue-relative+-1": "prošlog utorka",
	"field-day": "dan",
	"field-mon-relative+0": "ovog ponedeljka",
	"field-mon-relative+1": "sledećeg ponedeljka",
	"field-thu-relative+0": "ovog četvrtka",
	"field-second-relative+0": "sada",
	"field-thu-relative+1": "sledećeg četvrtka",
	"field-wed-relative+0": "ove srede",
	"months-format-wide": [
		"Čaitra",
		"Vaisaka",
		"Jiaista",
		"Asada",
		"Sravana",
		"Badra",
		"Asvina",
		"Kartika",
		"Argajana",
		"Pauza",
		"Maga",
		"Falguna"
	],
	"field-wed-relative+1": "sledeće srede",
	"field-month-relative+-1": "Prošlog meseca",
	"field-thu-relative+-1": "prošlog četvrtka"
}
//end v1.x content
);