define(
//begin v1.x content
{
	"KES_symbol": "Ksh",
	"USD_displayName": "Ndola ya Marekani",
	"TZS_displayName": "Silingi ya Tanzania",
	"ZMW_displayName": "Kwacha ya Zambia",
	"MAD_displayName": "Dirham ya Moroko",
	"NGN_displayName": "Naira ya Nijeria",
	"ZWD_displayName": "Ndola ya Zimbabwe",
	"SDG_displayName": "Vaũndi ya Sudani",
	"MWK_displayName": "Kwacha ya Malawi",
	"KMF_displayName": "Faranga ya Komoro",
	"SCR_displayName": "Rupia ya Shelisheli",
	"EGP_displayName": "Vaundi ya Misili",
	"CVE_displayName": "Eskudo ya Kepuvede",
	"LYD_displayName": "Dinari ya Libya",
	"CAD_displayName": "Ndola ya Kanada",
	"INR_displayName": "Rupia ya India",
	"JPY_displayName": "Sarafu ya Kijapani",
	"LRD_displayName": "Dola ya Liberia",
	"ZAR_displayName": "Randi ya Afrika Kusini",
	"AOA_displayName": "Kwanza ya Angola",
	"TND_displayName": "Ndinari ya Tunisia",
	"GHC_displayName": "Sedi ya Ghana",
	"BWP_displayName": "Pula ya Botswana",
	"DZD_displayName": "Dinari ya Aljeria",
	"ZMK_displayName": "Kwacha ya Zambia (1968–2012)",
	"NAD_displayName": "Ndola ya Namibia",
	"AED_displayName": "Dirham ya Falme za Kiarabu",
	"ETB_displayName": "Bir ya Uhabeshi",
	"MZM_displayName": "Metikali ya Msumbiji",
	"BIF_displayName": "Faranga ya Burundi",
	"RWF_displayName": "Faranga ya Rwanda",
	"STD_displayName": "Dobra ya Sao Tome na Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakfa ya Eritrea",
	"SAR_displayName": "Riyal ya Saudia",
	"DJF_displayName": "Faranga ya Jibuti",
	"CDF_displayName": "Faranga ya Kongo",
	"GBP_displayName": "Pauni ya Uingereza",
	"CHF_displayName": "Faranga ya Uswisi",
	"MUR_displayName": "Rupia ya Morisi",
	"SOS_displayName": "Silingi ya Somalia",
	"BHD_displayName": "Dinari ya Bahareni",
	"XOF_displayName": "Faranga CFA BCEAO",
	"GNS_displayName": "Faranga ya Gine",
	"SLL_displayName": "Leoni",
	"UGX_displayName": "Silingi ya Uganda",
	"MGA_displayName": "Ariary ya Bukini",
	"AUD_displayName": "Ndola ya Australia",
	"KES_displayName": "Silingi ya Kenya",
	"SHP_displayName": "Vaũndi ya Santahelena",
	"XAF_displayName": "Faranga CFA BEAC",
	"LSL_displayName": "Loti ya Lesoto",
	"MRO_displayName": "Ugwiya ya Moritania",
	"CNY_displayName": "Yuan Renminbi ya China",
	"GMD_displayName": "Ndalasi ya Gambia"
}
//end v1.x content
);