define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "ⵜⵉⵣⵉ ⴳ ⵡⴰⵙⵙ: ⵜⵉⴼⴰⵡⵜ/ⵜⴰⴷⴳⴳⵯⴰⵜ",
	"field-minute": "ⵜⵓⵙⴷⵉⴷⵜ",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-day-relative+-1": "ⵉⴹⵍⵍⵉ",
	"field-weekday": "ⴰⵙⵙ ⴳ ⵉⵎⴰⵍⴰⵙⵙ",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"field-era": "ⵜⴰⵙⵓⵜ",
	"field-hour": "ⵜⴰⵙⵔⴰⴳⵜ",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "ⴰⵙⵙⴰ",
	"field-day-relative+1": "ⴰⵙⴽⴽⴰ",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "ⴰⴽⵓⴷ ⵏ ⵓⴳⵎⵎⴰⴹ",
	"dateFormatItem-MMd": "d/MM",
	"dateFormat-medium": "d MMM, y G",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "m:ss",
	"field-year": "ⴰⵙⴳⴳⵯⴰⵙ",
	"field-week": "ⵉⵎⴰⵍⴰⵙⵙ",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "ⴰⵢⵢⵓⵔ",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-M": "M",
	"field-second": "ⵜⴰⵙⵉⵏⵜ",
	"field-day": "ⴰⵙⵙ",
	"dateFormat-short": "d/M/y GGGGG",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMEd": "E d/M/y"
}
//end v1.x content
);