define(
//begin v1.x content
{
	"KES_symbol": "Ksh",
	"USD_displayName": "Dola",
	"TZS_displayName": "Shilingi ya Tanzania",
	"ZMW_displayName": "Kwacha ya Zambia",
	"MAD_displayName": "Dirham ya Moroko",
	"NGN_displayName": "Naira ya Nijeria",
	"ZWD_displayName": "Dola ya Zimbabwe",
	"SDG_displayName": "Pauni ya Sudani",
	"MWK_displayName": "Kwacha ya Malawi",
	"KMF_displayName": "Faranga ya Komoro",
	"SCR_displayName": "Rupia ya Shelisheli",
	"EGP_displayName": "Paund mar Misri",
	"CVE_displayName": "Eskudo ya Kepuvede",
	"LYD_displayName": "Dinari ya Libya",
	"CAD_displayName": "Dola mar Kanada",
	"INR_displayName": "Rupia ya India",
	"JPY_displayName": "Yen mar Japan",
	"LRD_displayName": "Dola mar Liberia",
	"ZAR_displayName": "Randi ya Afrika Kusini",
	"AOA_displayName": "Kwanza ya Angola",
	"TND_displayName": "Dinari ya Tunisia",
	"GHC_displayName": "Sedi mar Ghana",
	"BWP_displayName": "Pula mar Botswana",
	"DZD_displayName": "Dinari ya Aljeria",
	"ZMK_displayName": "Kwacha ya Zambia (1968–2012)",
	"NAD_displayName": "Dola ya Namibia",
	"AED_displayName": "Dirham ya Falme za Kiarabu",
	"ETB_displayName": "Birr mar Ethiopia",
	"MZM_displayName": "Metikali ya Msumbiji",
	"BIF_displayName": "Faranga ya Burundi",
	"RWF_displayName": "Faranga ya Rwanda",
	"STD_displayName": "Dobra ya Sao Tome na Principe",
	"SZL_displayName": "Lilangeni",
	"EUR_displayName": "Yuro",
	"ERN_displayName": "Nakfa ya Eritrea",
	"SAR_displayName": "Riyal ya Saudia",
	"DJF_displayName": "Faranga ya Jibuti",
	"CDF_displayName": "Faranga ya Kongo",
	"GBP_displayName": "Pauni mar Uingereza",
	"CHF_displayName": "Faranga ya Uswisi",
	"MUR_displayName": "Rupia ya Morisi",
	"SOS_displayName": "Shilingi ya Somalia",
	"BHD_displayName": "Dinari ya Bahareni",
	"XOF_displayName": "Faranga CFA BCEAO",
	"GNS_displayName": "Faranga ya Gine",
	"SLL_displayName": "Leoni",
	"UGX_displayName": "Shilingi ya Uganda",
	"MGA_displayName": "Ariary ya Bukini",
	"AUD_displayName": "Dola ya Australia",
	"KES_displayName": "Siling mar Kenya",
	"SHP_displayName": "Pauni ya Santahelena",
	"XAF_displayName": "Faranga CFA BEAC",
	"LSL_displayName": "Loti ya Lesoto",
	"MRO_displayName": "Ugwiya ya Moritania",
	"CNY_displayName": "Yuan Renminbi ya China",
	"GMD_displayName": "Dalasi ya Gambia"
}
//end v1.x content
);