define(
//begin v1.x content
{
	"USD_displayName": "Lupila lwa Humalekani",
	"TZS_displayName": "Shilingi ya Hutanzania",
	"ZMW_displayName": "Lupila lwa Huzambia",
	"MAD_displayName": "Lupila lwa Humoloko",
	"NGN_displayName": "Lupila lwa Hunijelia",
	"ZWD_displayName": "Lupila lwa Huzimbabwe",
	"SDG_displayName": "Lupila lwa Husudani",
	"MWK_displayName": "Lupila lwa Humalawi",
	"KMF_displayName": "Lupila lwa Hukomoro",
	"SCR_displayName": "Lupila lwa Hushelisheli",
	"EGP_displayName": "Lupila lwa Humisri",
	"CVE_displayName": "Lupila lwa Hukepuvede",
	"LYD_displayName": "Lupila lwa Hulibya",
	"CAD_displayName": "Lupila lwa Hukanada",
	"INR_displayName": "Lupila lwa Huindia",
	"JPY_displayName": "Lupila lwa Hijapani",
	"TZS_symbol": "TSh",
	"LRD_displayName": "Lupila lwa Hulibelia",
	"ZAR_displayName": "Lupila lwa Huafriaka ya Hukusini",
	"AOA_displayName": "Lupila lwa Huangola",
	"TND_displayName": "Lupila lwa Hutunisia",
	"GHC_displayName": "Lupila lwa Hughana",
	"BWP_displayName": "Lupila lwa Hubotswana",
	"DZD_displayName": "Lupila lwa Hualjelia",
	"ZMK_displayName": "Lupila lwa Huzambia (1968–2012)",
	"NAD_displayName": "Lupila lwa Hunamibia",
	"AED_displayName": "Lupila lwa Hufalme dza Huhihalabu",
	"ETB_displayName": "Lupila lwa Huuhabeshi",
	"MZM_displayName": "Lupila lwa Humsumbiji",
	"BIF_displayName": "Lupila lwa Huburundi",
	"RWF_displayName": "Lupila lwa Hurwanda",
	"STD_displayName": "Lupila lwa Husaotome na Huprinisipe",
	"SZL_displayName": "Lupila lwa Lilangeni",
	"EUR_displayName": "Lupila lwa Yulo",
	"ERN_displayName": "Lupila lwa Hueritrea",
	"SAR_displayName": "Lupila lwa Husaudi",
	"DJF_displayName": "Lupila lwa Hujibuti",
	"CDF_displayName": "Lupila lwa Hukongo",
	"GBP_displayName": "Lupila lwa Huuingereza",
	"CHF_displayName": "Lupila lwa Huuswisi",
	"MUR_displayName": "Lupila lwa Humolisi",
	"SOS_displayName": "Lupila lwa Husomalia",
	"BHD_displayName": "Lupila lwa Hubahareni",
	"XOF_displayName": "Lupila lwa CFA BCEAO",
	"GNS_displayName": "Lupila lwa Hujine",
	"SLL_displayName": "Lupila lwa Lioni",
	"UGX_displayName": "Shilingi ya Huuganda",
	"MGA_displayName": "Lupila lwa Hubukini",
	"AUD_displayName": "Lupila lwa Huaustlalia",
	"KES_displayName": "Shilingi ya Hukenya",
	"SHP_displayName": "Lupila lwa Husantahelena",
	"XAF_displayName": "Lupila lwa CFA BEAC",
	"LSL_displayName": "Lupila lwa Hulesoto",
	"MRO_displayName": "Lupila lwa Humolitania",
	"CNY_displayName": "Lupila lwa Huchina",
	"GMD_displayName": "Lupila lwa Hugambia"
}
//end v1.x content
);