define(
//begin v1.x content
{
	"dateFormatItem-yM": "M/y",
	"field-dayperiod": "Lwamelau",
	"field-minute": "Dakika",
	"dateFormatItem-MMMEd": "E, MMM d",
	"field-day-relative+-1": "Igolo",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-weekday": "Sihudza kasi",
	"dateFormatItem-MMM": "LLL",
	"field-era": "Amajira",
	"field-hour": "Saa",
	"dateFormatItem-y": "y",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "Neng'u ni",
	"field-day-relative+1": "Hilawu",
	"dateFormat-long": "d MMMM y G",
	"field-zone": "Amajira ga saa",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "d MMM y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Mwaha",
	"field-week": "Mlungu gumamfu",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"field-month": "Mwedzi",
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-M": "L",
	"dateFormatItem-yMMMd": "d MMM y",
	"field-second": "Sekunde",
	"field-day": "Sihu",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-d": "d"
}
//end v1.x content
);