({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray. 
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "bladoniebieski",
antiquewhite: "biel antyczna",
aqua: "wodny",
aquamarine: "akwamaryna",
azure: "lazur",
beige: "beżowy",
bisque: "biszkoptowy",
black: "czarny",
blanchedalmond: "migdałowy",
blue: "niebieski",
blueviolet: "niebieskofioletowy",
brown: "brązowy",
burlywood: "kolor drewna",
cadetblue: "niebieskoszary",
chartreuse: "jaskrawozielony",
chocolate: "czekoladowy",
coral: "koralowy",
cornflowerblue: "chabrowy",
cornsilk: "kukurydziany",
crimson: "karmazynowy",
cyan: "cyjan",
darkblue: "ciemnoniebieski",
darkcyan: "ciemny cyjan",
darkgoldenrod: "ciemnogliniany",
darkgray: "ciemnoszary",
darkgreen: "ciemnozielony",
darkgrey: "ciemnoszary", // same as darkgray
darkkhaki: "ciemny khaki",
darkmagenta: "ciemna magenta",
darkolivegreen: "ciemnooliwkowy",
darkorange: "ciemnopomarańczowy",
darkorchid: "ciemna orchidea",
darkred: "ciemnoczerwony",
darksalmon: "ciemnołososiowy",
darkseagreen: "ciemna morska zieleń",
darkslateblue: "ciemny łupkowy niebieski",
darkslategray: "ciemny łupkowy szary",
darkslategrey: "ciemny łupkowy szary", // same as darkslategray
darkturquoise: "ciemnoturkusowy",
darkviolet: "ciemnofioletowy",
deeppink: "głęboki różowy",
deepskyblue: "intensywny błękit nieba",
dimgray: "przytłumiony szary",
dimgrey: "przytłumiony szary", // same as dimgray
dodgerblue: "błękit Dodgers",
firebrick: "ceglasty",
floralwhite: "kwiatowa biel",
forestgreen: "leśna zieleń",
fuchsia: "fuksja",
gainsboro: "bladoszary",
ghostwhite: "bladobiały",
gold: "złoty",
goldenrod: "gliniany",
gray: "szary",
green: "zielony",
greenyellow: "zielonożółty",
grey: "szary", // same as gray
honeydew: "melon",
hotpink: "intensywny różowy",
indianred: "kasztanowy",
indigo: "indygo",
ivory: "kość słoniowa",
khaki: "khaki",
lavender: "lawendowy",
lavenderblush: "lawendoworóżowy",
lawngreen: "trawiasty",
lemonchiffon: "cytrynowy",
lightblue: "jasnoniebieski",
lightcoral: "jasnokoralowy",
lightcyan: "jasny cyjan",
lightgoldenrodyellow: "jasnogliniana żółć",
lightgray: "jasnoszary",
lightgreen: "jasnozielony",
lightgrey: "jasnoszary", // same as lightgray
lightpink: "jasnoróżowy",
lightsalmon: "jasnołososiowy",
lightseagreen: "jasna morska zieleń",
lightskyblue: "jasny błękit nieba",
lightslategray: "jasny łupkowy szary",
lightslategrey: "jasny łupkowy szary", // same as lightslategray
lightsteelblue: "jasny stalowoniebieski",
lightyellow: "jasnożółty",
lime: "limetkowy",
limegreen: "limetkowozielony",
linen: "lniany",
magenta: "magenta",
maroon: "bordowy",
mediumaquamarine: "średnia akwamaryna",
mediumblue: "średni niebieski",
mediumorchid: "średnia orchidea",
mediumpurple: "średnia purpura",
mediumseagreen: "średnia morska zieleń",
mediumslateblue: "średni łupkowy niebieski",
mediumspringgreen: "średnia wiosenna zieleń",
mediumturquoise: "średni turkusowy",
mediumvioletred: "średni fioletowoczerwony",
midnightblue: "ciemnogranatowy",
mintcream: "jasnomiętowy",
mistyrose: "bladoróżany",
moccasin: "mokasynowy",
navajowhite: "piaskowy",
navy: "granatowy",
oldlace: "bladopomarańczowy",
olive: "oliwkowy",
olivedrab: "oliwkowa zieleń",
orange: "pomarańczowy",
orangered: "pomarańczowoczerwony",
orchid: "orchidea",
palegoldenrod: "bladogliniany",
palegreen: "bladozielony",
paleturquoise: "bladoturkusowy",
palevioletred: "blady fioletowoczerwony",
papayawhip: "papaja",
peachpuff: "brzoskwiniowy",
peru: "jasnobrązowy",
pink: "różowy",
plum: "śliwkowy",
powderblue: "pudrowy niebieski",
purple: "purpurowy",
red: "czerwony",
rosybrown: "różowobrązowy",
royalblue: "błękit królewski",
saddlebrown: "skórzany brązowy",
salmon: "łososiowy",
sandybrown: "piaskowy brąz",
seagreen: "morska zieleń",
seashell: "muszla",
sienna: "siena",
silver: "srebrny",
skyblue: "błękit nieba",
slateblue: "łupkowy niebieski",
slategray: "łupkowy szary",
slategrey: "łupkowy szary", // same as slategray
snow: "śnieżny",
springgreen: "wiosenna zieleń",
steelblue: "stalowy niebieski",
tan: "kawowy",
teal: "cyrankowy",
thistle: "bladofioletowy",
tomato: "pomidorowy",
turquoise: "turkusowy",
violet: "fioletowy",
wheat: "pszeniczny",
white: "biały",
whitesmoke: "przydymiony biały",
yellow: "żółty",
yellowgreen: "żółtozielony"
})
